### ISSUE TITLE
createWxaCodeUnlimit获取的file为null

### ISSUE THREAD

**Issue by weiyierlei** [binarywang/WxJava#1000]
File cn.binarywang.wx.miniapp.api.WxMaQrcodeService.createWxaCodeUnlimit(String scene, String page) throws WxErrorException

使用上述方法，返回的flie文件为null，没有抛出异常，导致后面的代码处理file时会报错。这个错误会不定时出现，有时重试一下就好了，有时重试也不行。版本是3.2.0

**Comment by binarywang** [comment]
用最新版本试试看有没有同样问题，因为你用的版本有点老，不确定最新版本是否修复过。

**Comment by binarywang** [comment]
楼主尝试过没有？

**Comment by weiyierlei** [comment]
试过升级为3.3.0版本了，问题还是一样。我现在是先用返回file方法获取，失败后（机返回为null时）再使用返回byte[]的方法重新获取一次

**Comment by weiyierlei** [comment]
> 楼主尝试过没有？

更新了3.3.0，目前没有出现报错，应该是修复了
