### ISSUE TITLE
微信支付支持多个子商户配置

### ISSUE THREAD

**Issue by silloy** [binarywang/WxJava#1004]
微信支付原有配置如下：
wx:
  pay:
    appId: #微信公众号或者小程序等的appid
    mchId: #微信支付商户号
    mchKey: #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）

请教如何动态增加子商户id？

**Comment by binarywang** [comment]
你这些配置不属于sdk里的吧？请在对应demo下讨论该问题。
另外，多商户支持，直接在请求参数里指定即可。
