### ISSUE TITLE
微信物流助手相关接口

### ISSUE THREAD

**Issue by ningxz** [binarywang/WxJava#1009]
微信物流助手小程序接入文档：
https://developers.weixin.qq.com/miniprogram/dev/api-backend/logistics.addOrder.html

微信物流助手接入指南：
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=21552623373Ym2z0&token=&lang=zh_CN

**Comment by huangxuankai** [comment]
* 请问，我通过使用顺丰月结帐号下单和微信官方提供的现付帐号下散单，下单成功，也能拿到面单数据，但是没有快递员上门取件是怎么回事？
* 我自行联系了快递小哥上门打印面单，快递小哥没有查到从微信物流助手下的运单

**Comment by binarywang** [comment]
期待楼主提供下PR，估计早都实现了吧

**Comment by binarywang** [comment]
3.6.1.B测试版本已添加，欢迎使用
