### ISSUE TITLE
建议实现微信支付分账接口

### ISSUE THREAD

**Issue by niuchang3** [binarywang/WxJava#1010]
[如文档所述](https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=24_4&index=4)

**Comment by wangjia2016** [comment]
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=24_2&index=2 
这里的开通流程 

1、服务商在产品中心-特约商户授权产品中开通服务商分账（服务商联系运营开通产品白名单后，才可在产品中心看到此功能）。 


要联系运营开通产品白名单？那意思是还没有对外开放吧，现在

**Comment by jianglin1008** [comment]
已经全面放开了

**Comment by binarywang** [comment]
3.5.8.B版本已实现，欢迎试用
