### ISSUE TITLE
小程序审核结果增加截屏字段的解析

### ISSUE THREAD

**Issue by onekr-billy** [binarywang/WxJava#1011]
微信开放平台的几个审核接口，官方已经增加了 审核失败的截图的返回， 请解析一下
具体接口为：
https://api.weixin.qq.com/wxa/get_auditstatus?access_token=TOKEN
https://api.weixin.qq.com/wxa/get_latest_auditstatus?access_token=TOKEN

字段为：ScreenShot

**Comment by binarywang** [comment]
请楼主给一下官方文档地址，而不是接口地址

**Comment by binarywang** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489140610_Uavc4&token=&lang=

**Comment by binarywang** [comment]
3.3.9.B测试版本已增加
