### ISSUE TITLE
H5支付 MWEB类型不支持吗？

### ISSUE THREAD

**Issue by illmm** [binarywang/WxJava#1017]
wxService.createOrder 方法传入MWEB 会返回该交易类型暂不支持

**Comment by illmm** [comment]
`  public <T> T createOrder(WxPayUnifiedOrderRequest request) throws WxPayException {
        WxPayUnifiedOrderResult unifiedOrderResult = this.unifiedOrder(request);
        String prepayId = unifiedOrderResult.getPrepayId();
        if (StringUtils.isBlank(prepayId)) {
            throw new RuntimeException(String.format("无法获取prepay id，错误代码： '%s'，信息：%s。", unifiedOrderResult.getErrCode(), unifiedOrderResult.getErrCodeDes()));
        } else {
            String timestamp = String.valueOf(System.currentTimeMillis() / 1000L);
            String nonceStr = String.valueOf(System.currentTimeMillis());
            String var6 = request.getTradeType();
            byte var7 = -1;
            switch(var6.hashCode()) {
            case -1999289321:
                if (var6.equals("NATIVE")) {
                    var7 = 0;
                }
                break;
            case 65025:
                if (var6.equals("APP")) {
                    var7 = 1;
                }
                break;
            case 70878225:
                if (var6.equals("JSAPI")) {
                    var7 = 2;
                }
            }

            String signType;
            switch(var7) {
            case 0:
                return WxPayNativeOrderResult.builder().codeUrl(unifiedOrderResult.getCodeURL()).build();
            case 1:
                signType = this.getConfig().getAppId();
                Map<String, String> configMap = new HashMap();
                String partnerId = this.getConfig().getMchId();
                configMap.put("prepayid", prepayId);
                configMap.put("partnerid", partnerId);
                String packageValue = "Sign=WXPay";
                configMap.put("package", packageValue);
                configMap.put("timestamp", timestamp);
                configMap.put("noncestr", nonceStr);
                configMap.put("appid", signType);
                return WxPayAppOrderResult.builder().sign(SignUtils.createSign(configMap, (String)null, this.getConfig().getMchKey(), false)).prepayId(prepayId).partnerId(partnerId).appId(signType).packageValue(packageValue).timeStamp(timestamp).nonceStr(nonceStr).build();
            case 2:
                signType = "MD5";
                WxPayMpOrderResult payResult = WxPayMpOrderResult.builder().appId(unifiedOrderResult.getAppid()).timeStamp(timestamp).nonceStr(nonceStr).packageValue("prepay_id=" + prepayId).signType(signType).build();
                payResult.setPaySign(SignUtils.createSign(payResult, signType, this.getConfig().getMchKey(), false));
                return payResult;
            default:
                throw new WxPayException("该交易类型暂不支持");
            }
        }
    }`

**Comment by illmm** [comment]
`
  public <T> T createOrder(WxPayUnifiedOrderRequest request) throws WxPayException {
        WxPayUnifiedOrderResult unifiedOrderResult = this.unifiedOrder(request);
        String prepayId = unifiedOrderResult.getPrepayId();
        if (StringUtils.isBlank(prepayId)) {
            throw new RuntimeException(String.format("无法获取prepay id，错误代码： '%s'，信息：%s。", unifiedOrderResult.getErrCode(), unifiedOrderResult.getErrCodeDes()));
        } else {
            String timestamp = String.valueOf(System.currentTimeMillis() / 1000L);
            String nonceStr = String.valueOf(System.currentTimeMillis());
            String var6 = request.getTradeType();
            byte var7 = -1;
            switch(var6.hashCode()) {
            case -1999289321:
                if (var6.equals("NATIVE")) {
                    var7 = 0;
                }
                break;
            case 65025:
                if (var6.equals("APP")) {
                    var7 = 1;
                }
                break;
            case 70878225:
                if (var6.equals("JSAPI")) {
                    var7 = 2;
                }
            }

            String signType;
            switch(var7) {
            case 0:
                return WxPayNativeOrderResult.builder().codeUrl(unifiedOrderResult.getCodeURL()).build();
            case 1:
                signType = this.getConfig().getAppId();
                Map<String, String> configMap = new HashMap();
                String partnerId = this.getConfig().getMchId();
                configMap.put("prepayid", prepayId);
                configMap.put("partnerid", partnerId);
                String packageValue = "Sign=WXPay";
                configMap.put("package", packageValue);
                configMap.put("timestamp", timestamp);
                configMap.put("noncestr", nonceStr);
                configMap.put("appid", signType);
                return WxPayAppOrderResult.builder().sign(SignUtils.createSign(configMap, (String)null, this.getConfig().getMchKey(), false)).prepayId(prepayId).partnerId(partnerId).appId(signType).packageValue(packageValue).timeStamp(timestamp).nonceStr(nonceStr).build();
            case 2:
                signType = "MD5";
                WxPayMpOrderResult payResult = WxPayMpOrderResult.builder().appId(unifiedOrderResult.getAppid()).timeStamp(timestamp).nonceStr(nonceStr).packageValue("prepay_id=" + prepayId).signType(signType).build();
                payResult.setPaySign(SignUtils.createSign(payResult, signType, this.getConfig().getMchKey(), false));
                return payResult;
            default:
                throw new WxPayException("该交易类型暂不支持");
            }
        }
    }
`

**Comment by illmm** [comment]
https://github.com/Wechat-Group/WxJava/blob/5fc4142885b8e56dd1577bdeef006838023ad1a9/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/BaseWxPayServiceImpl.java#L301-L380

**Comment by einsitang** [comment]
nweb 是啥？
另外，为什么你要贴上反编译的代码？

**Comment by illmm** [comment]
> nweb 是啥？
> 另外，为什么你要贴上反编译的代码？

改了，打错了
