### ISSUE TITLE
微信登录无法获取 openid

### ISSUE THREAD

**Issue by cyloer** [binarywang/WxJava#1018]
this.wxService.getUserService().getSessionInfo(code) 这个方法报空指针。无法获取openid。
![image](https://user-images.githubusercontent.com/18494465/56590564-e4c76880-6619-11e9-9251-32bf1ec79f8d.png)

**Comment by CuriousRookie** [comment]
是因为你没有给WxMaInMemeryConfig设置appid和secret吧？config里这两个属性都是null

**Comment by binarywang** [comment]
空指针问题其实最简单，找到导致空指针异常的值为null的对象，分析下为什么为空

**Comment by cyloer** [comment]
> 是因为你没有给WxMaInMemeryConfig设置appid和secret吧？config里这两个属性都是null

只需要在小程序里设置 appid 吗？

**Comment by cyloer** [comment]
> 空指针问题其实最简单，找到导致空指针异常的值为null的对象，分析下为什么为空
这块需要设置什么属性吗？
