### ISSUE TITLE
WxMpPayService refund 方法报错

### ISSUE THREAD

**Issue by lucyTheSlayer** [binarywang/WxJava#102]
java.lang.ClassCastException: me.chanjar.weixin.mp.bean.pay.request.WxPayRefundRequest cannot be cast to me.chanjar.weixin.mp.bean.pay.result.WxPayRefundResult
me.chanjar.weixin.mp.api.impl.WxMpPayServiceImpl.refund(WxMpPayServiceImpl.java:77)

貌似是WxPayRefundResult result = (WxPayRefundResult)xstream.fromXML(responseContent)此处强转出错了。
望大神解决！

**Comment by binarywang** [comment]
请问你是用的什么版本？

**Comment by lucyTheSlayer** [comment]
之前用的2.2.6,刚更新了2.4.0依然报这个错

**Comment by binarywang** [comment]
我看代码行数并不匹配，你确定是2.4.0吗？

**Comment by lucyTheSlayer** [comment]
刚更新的2.4.0maven忘clean了，重新build后，发现没有此问题了，感谢大神

**Comment by binarywang** [comment]
我记得这个问题确实是修复过的，2.2.6属于测试版本，测试版本是本身可能会有问题的，以后遇到问题，升级正式版后一般都会修复的
