### ISSUE TITLE
是否考虑加入导入抽样数据的接口支持

### ISSUE THREAD

**Issue by gongshsh** [binarywang/WxJava#1020]
将数据写入到setdynamicdata这个API。每个Post数据包不超过5K，若数据过多可开多进（线）程并发导入数据（例如：数据量为十万量级可以开50个线程并行导数据）。

官方接口：
http(s)://api.weixin.qq.com/wxa/setdynamicdata?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
大哥，问题内容改下呗？

**Comment by binarywang** [comment]
请明确接口是做什么的，至少贴一下官方文档地址吧

**Comment by gongshsh** [comment]
http(s)://api.weixin.qq.com/wxa/setdynamicdata?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
> http(s)://api.weixin.qq.com/wxa/setdynamicdata?access_token=ACCESS_TOKEN

你这有点惜字如金啊，官方文档地址能否贴下，其实这个才是最主要的

**Comment by gongshsh** [comment]
> > http(s)://api.weixin.qq.com/wxa/setdynamicdata?access_token=ACCESS_TOKEN
> 
> 你这有点惜字如金啊，官方文档地址能否贴下，其实这个才是最主要的

请问这个接口什么时候能支持？

**Comment by binarywang** [comment]
> > > http(s)://api.weixin.qq.com/wxa/setdynamicdata?access_token=ACCESS_TOKEN
> > 
> > 
> > 你这有点惜字如金啊，官方文档地址能否贴下，其实这个才是最主要的
> 
> 请问这个接口什么时候能支持？

大哥你文档地址都不肯给一下，谁给你完成啊，都不知道参数是什么

**Comment by gongshsh** [comment]
http(s)://api.weixin.qq.com/wxa/setdynamicdata?access_token=ACCESS_TOKEN

**Comment by Asanenter** [comment]
xswl，大哥有点搞不懂什么是API地址什么是官方文档地址

**Comment by binarywang** [comment]
楼主，你以为发了三遍接口地址，大家就能猜出来官方文档地址了吗？

**Comment by gongshsh** [comment]
https://developers.weixin.qq.com/miniprogram/introduction/widget/custom/quickstart/implement/import/index.html
忙晕了

**Comment by binarywang** [comment]
这个接口官方文档已经不存在了吗？

**Comment by gongshsh** [comment]
https://wsad.weixin.qq.com/wsad/zh_CN/htmledition/widget-docs-v3/html/custom/quickstart/implement/import/index.html
接口地址变为上面了。ths，binarywang

**Comment by binarywang** [comment]
所提到的接口 包含在 #1373 里，关闭此issue
