### ISSUE TITLE
微信小程序测试版uniformMessage提交字段问题

### ISSUE THREAD

**Issue by dyhack** [binarywang/WxJava#1021]
### 简要描述
使用线上发布的微信小程序能够正常调用，而使用微信的体验版小程序调用相同的接口提示字段名称不对。查看结构后发现是微信官方字段里是pagepath，而我修改为pagePath后，体验版小程序能够正常发送模板消息。

### 重现步骤
1. 正常发布的线上版小程序，走官方文档里的数据结构能够正常发送模板消息。
2. 体验版小程序，走同样的接口，同样的数据结构不能够发送
3. 修改pagepath字段为pagePath后能够正常发送

### 接口地址
[小程序向公众里发消息](https://developers.weixin.qq.com/miniprogram/dev/api-backend/uniformMessage.send.html)

 ###数据结构
``
{
	"touser": "ojmEg*****pdqQ-gI",
	"mp_template_msg": {
		"appid": "wx29ef**00288",
		"template_id": "v6LPtkk***1lpCzkdHT64WS5Q54XCY",
		"url": "http://***:61112/urGnWI",
		"miniprogram": {
			"appid": "wx5e41****8da256",
			"pagepath": "/pages/index/index"
		},
		"data": {
			"first": {
				"value": "硬盘读取时间"
			},
			"keyword1": {
				"value": "硬盘读取时间"
			},
			"keyword2": {
				"value": "(宇宙无敌战舰)"
			},
			"keyword3": {
				"value": "2019-04-24 23:03:43"
			},
			"keyword4": {
				"value": "更快达成交易"
			},
			"remark": {
				"value": "更快达成交易"
			}
		}
	}
}
``

微信报错结果
``
{
    "errcode": 40165,
    "errmsg": "invalid weapp pagepath hint: [zKjMka09173929]"
}
``

**Comment by dyhack** [comment]
![image](https://user-images.githubusercontent.com/22422580/56712810-5f030480-6762-11e9-906e-d12aceff2320.png)

**Comment by binarywang** [comment]
微信这么变态的问题坑过太多人了。

**Comment by dyhack** [comment]
> 微信这么变态的问题坑过太多人了。

这是我测试出来的，希望不要坑到更多的人，我不知道去哪里说。

**Comment by binarywang** [comment]
之前我记得是有path和pagepath两个值，所以你看源代码里MiniProgram类实际上提供了一个选择用哪个的参数，没想到现在又来了个新的写法pagePath，靠，恶心死人

**Comment by dyhack** [comment]
> 微信这么变态的问题坑过太多人了。

建议弄一个腾讯开发的踩坑指南，方便大家查看。
我线上正式发布版没有，只有体验版有这个问题

**Comment by dyhack** [comment]
> 之前我记得是有path和pagepath两个值，所以你看源代码里MiniProgram类实际上提供了一个选择用哪个的参数，没想到现在又来了个新的写法pagePath，靠，恶心死人

我还没有导入那个wx-java 的开发包，现在这个是我自己写的发送逻辑。

**Comment by dyhack** [comment]
> 之前我记得是有path和pagepath两个值，所以你看源代码里MiniProgram类实际上提供了一个选择用哪个的参数，没想到现在又来了个新的写法pagePath，靠，恶心死人

那您又要加上一个了，但是我不知道这几个的区别，主要是开发文档上给的就是pagepath，还是小写的，

**Comment by binarywang** [comment]
> > 之前我记得是有path和pagepath两个值，所以你看源代码里MiniProgram类实际上提供了一个选择用哪个的参数，没想到现在又来了个新的写法pagePath，靠，恶心死人
> 
> 那您又要加上一个了，但是我不知道这几个的区别，主要是开发文档上给的就是pagepath，还是小写的，

准备在`cn.binarywang.wx.miniapp.bean.WxMaUniformMessage.MiniProgram`里增加方法isUsePagePath，来判断是否使pagePath。

**Comment by binarywang** [comment]
3.3.9.B测试版本已增加相关方法，欢迎试用
