### ISSUE TITLE
上传视频素材后，视频素材一直没有审核状态

### ISSUE THREAD

**Issue by Kovvi** [binarywang/WxJava#1022]
### 简要描述
调用materialFileUpload方法上传视频永久素材，上传完成后，返回了media_id，但是视频素材一直未被审批，可以确定的是，视频内容、大小（3.5M）、格式(mp4)都是正确的。

### 模块版本情况

* WxJava 模块名: WxMpMaterialServiceImpl
* WxJava 版本号:weixin-java-mp-3.2.0.jar

### 重现步骤
1. 调用materialFileUpload方法上传视频永久素材
2. 在公众号管理后台查看素材，发现api上传的视频一直处于没有审核状态的状况，状态一栏为“-”

**Comment by binarywang** [comment]
能否去掉些没用的内容？不觉得很影响阅读吗？

**Comment by Kovvi** [comment]
> 能否去掉些没用的内容？不觉得很影响阅读吗？
好的，谢谢建议。issues中的问题，您有遇到过吗？被这个lock好几天了，是上传视频时有什么细节需要注意的吗？

**Comment by binarywang** [comment]
没遇到过，很久没做这块相关内容了

**Comment by Kovvi** [comment]
问题原因知道了，腾讯那边反馈说接口上传的视频素材，目前不支持审核，只能用于自动回复，不支持群发。望各位勿踩坑噢～
