### ISSUE TITLE
开放平台发送客服消息成功，主动回复失败

### ISSUE THREAD

**Issue by silloy** [binarywang/WxJava#1023]
1.  使用https://github.com/Wechat-Group/weixin-java-open-demo 里的notifyController测试
2. 加密前的outmessage是
outMessage：
<xml>
  <ToUserName><![CDATA[gh_8ffc5b7009e8]]></ToUserName>
  <FromUserName><![CDATA[oHbsv1F61YlvqWx00o4QrUz3qe5s]]></FromUserName>
  <CreateTime>1556256494</CreateTime>
  <MsgType><![CDATA[image]]></MsgType>
  <Image><MediaId><![CDATA[l9Nxln_NQF5SG96148pY4PNhiRZ2sr9sJ27H9Sl7dYA]]></MediaId></Image>
</xml>
加密后的内容
<xml>
<Encrypt><![CDATA[P5q+1O0PqkC3/D7+4WNCJ+96caGGZ6T3YQ99CeX7l2L4cxqMfpKTx1raSjNPaI6qO8Gh2c1iEBT82f6CZe6qwQFs0uRTk+rHPdRavFcIAcDdSjVWXiZyDmBtTLKOcneWq4rjCPUmKuHCvxjFvS8OsCbC5hgeQoiqDqrFaZbstAJOJ/jbXtJg9wCZBakdCgfsx6ZcrDtWphNUl+wV3U9QPOy9+K1IdKI/FewyRKvYYzbBFLuDEU06j/KGPbscp4Xqq5CGifJh9ZWROAtUIKtsxT4/FVmHnypscu7aONvleANQHcj4hMLxBIqdgpvuattt4sGCf7tJESJxUogxLFxzfj0XkTQwRmfialntD5JJO/GI+DgX6bAeePCa8ZZPqgsc5nVg4QkbCGiXtrYWjziz7NmVrHWmYTAwA8fLLFEJwvOQfYSg7tL+4VS34xFMafXLpJ8wtmQ3BX0RYw70LU/vDQ==]]></Encrypt>
<MsgSignature><![CDATA[70db1c102fd4358325378a9d214025c1dd01703a]]></MsgSignature>
<TimeStamp>1556256494</TimeStamp>
<Nonce><![CDATA[VIv50qtMDW9XV1GV]]></Nonce>
</xml>

发送失败，用户端显示服务故障

**Comment by binarywang** [comment]
demo的问题不要在这里询问，谢谢
