### ISSUE TITLE
wxPayService.createOrder()日志问题

### ISSUE THREAD

**Issue by BARERM** [binarywang/WxJava#1030]
### 模块版本情况

* WxJava 模块名: WxJava工程的WxPayService
* WxJava 版本号: 3.3.0

### 问题：
调用WxPayService统一下单时，控制台会打印大量日志，如图：
[http://netcafe.yqbing.com/WX20190430-005557@2x.png](url)

### 期望：
请问如何关闭这些日志的输出呢？
我尝试了各种设置都未能如愿。

**Comment by binarywang** [comment]
你怎么设置的？其实先看看是哪个类输出的日志，在对应日志框架设置更高的级别不就行了吗？

**Comment by BARERM** [comment]
> 你怎么设置的？其实先看看是哪个类输出的日志，在对应日志框架设置更高的级别不就行了吗？

谢谢您的解答！

是这个类输出的
com.github.binarywang.wxpay.service.impl.WxPayServiceImpl
但是是info的级别，所以无论如何都会输出啊。

**Comment by binarywang** [comment]
你确定info级别的没法设置了吗？

**Comment by hallkk** [comment]
可以更改下配置文件里`logging.level`的设置，应该就不会有这样的情况发生

**Comment by BARERM** [comment]
> 你确定info级别的没法设置了吗？

你好，我不确定是不是没法设置。
我的logging.level是info级，不知道是不是哪里设置的不对，所以来求助了～

**Comment by BARERM** [comment]
> 可以更改下配置文件里`logging.level`的设置，应该就不会有这样的情况发生

感谢你的回答。

loggin.level设置的是info，但好像这些日志在框架里也是info级别输出的。所以我不知道如何调整了。

**Comment by binarywang** [comment]
> > 可以更改下配置文件里`logging.level`的设置，应该就不会有这样的情况发生
> 
> 感谢你的回答。
> 
> loggin.level设置的是info，但好像这些日志在框架里也是info级别输出的。所以我不知道如何调整了。

先仔细学习下你要使用的日志框架，阅读下相关文档
