### ISSUE TITLE
微信会员卡对象没有设置一键跳转激活类型所需字段

### ISSUE THREAD

**Issue by zx3332352** [binarywang/WxJava#1031]
“wx_activate_after_submit”“wx_activate_after_submit_url”这两个字段

**Comment by zx3332352** [comment]
#卡券

**Comment by binarywang** [comment]
请提供下对应文档地址

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025283

**Comment by binarywang** [comment]
3.4.0版本已添加
