### ISSUE TITLE
无法加载bean到spring

### ISSUE THREAD

**Issue by senjyure** [binarywang/WxJava#1032]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__明确描述下你所遇到的问题，如果是新功能或接口需求，请提供对应微信官方文档地址以便查阅。__

### 模块版本情况

* WxJava 模块名: mp
* WxJava 版本号:3.3.0

### 期待结果 和 实际情况
__尽量详细描述__
启动时出现无法加载WxMpService到spring的情况，其使用springBoot框架
### 重现步骤
1. 添加Autowired注解后添加WxMpService模块，
2. 
3. 

### 日志
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'v1ErrorController': Unsatisfied dependency expressed through field 'weChatTemplateService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'weChatTemplateService': Unsatisfied dependency expressed through field 'wxMpService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'me.chanjar.weixin.mp.api.WxMpService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by binarywang** [comment]
首先提问问题时建议移除无用内容；其次，你的问题请参考demo项目解决即可，如果还有问题，在对应demo】下提问，谢谢合作
