### ISSUE TITLE
小程序发送模板内容字体颜色设置color无效

### ISSUE THREAD

**Issue by xczjj** [binarywang/WxJava#1035]
WxMaTemplateMessage 发送模板类中
List<WxMaTemplateData > data 属性

WxMaTemplateData 模板内容类
['{“name”:"keyword1","value":“审核状态”，“color”:"#FF0000”}]
需求设置keyword1的color属性为红色字体 

设置后模板推送消息字体颜色却依然是默认#000000（黑色）

微信官方文档没有color属性
![image](https://user-images.githubusercontent.com/49943748/57230563-34128d80-704b-11e9-913c-75af6d99366a.png)
是不是小程序不支持个性化设置字体颜色

**Comment by binarywang** [comment]
官方没有就是不支持了，你忽略就是了，可能是后来调整的

**Comment by xczjj** [comment]
好的 也只能如此了




 
---原始邮件---
发件人: "Binary Wang"<notifications@github.com>
发送时间: 2019年5月7日(星期二) 中午12:44
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com>;
抄送: "MKeyboard"<1349926002@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Wechat-Group/WxJava] 小程序发送模板内容字体颜色设置color无效 (#1035)



官方没有就是不支持了，你忽略就是了，可能是后来调整的

**Comment by binarywang** [comment]
3.3.9.B测试版本已移除
