### ISSUE TITLE
小程序支付增加receipt电子发票字段

### ISSUE THREAD

**Issue by chenhao0306** [binarywang/WxJava#1036]
### 简要描述
小程序微信支付下单需要使用电子发票
下单需要传递receipt参数
### 模块版本情况
* WxJava 模块名: weixin-java-pay:wxpay/bean/request/WxPayUnifiedOrderRequest.java

**Comment by binarywang** [comment]
请提供官方文档地址

**Comment by binarywang** [comment]
楼主呢？

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_1

**Comment by binarywang** [comment]
3.3.9.B测试版本已增加
