### ISSUE TITLE
发送模版消息出现48001错误

### ISSUE THREAD

**Issue by blackmanbachen** [binarywang/WxJava#1038]
### 问题描述
```js
{
    "errcode": 48001,
    "errmsg": "api unauthorized hint: [bMCwCa0505sz35!]"
}
```

### 问题原因

WxMaMsgService.java中的TEMPLATE_MSG_SEND_URL常量地址有问题，微信官方的地址是
`https://api.weixin.qq.com/cgi-bin/message/template/send`

**Comment by binarywang** [comment]
所谓的官方地址所在的文档的地址能否给一下？

**Comment by blackmanbachen** [comment]
`https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277`

**Comment by binarywang** [comment]
> `https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277`

大哥，你拿小程序的代码去请求公众号的，能不出问题吗？

**Comment by blackmanbachen** [comment]
我搞错了，sorry
