### ISSUE TITLE
建议微信接口地址可配置化

### ISSUE THREAD

**Issue by xiaweinixxw** [binarywang/WxJava#1039]
基于以下考虑：部分企业网络配置，应用服务器无法直接访问外网，访问微信接口地址时需要做防火墙映射成内网地址进行访问。建议将微信接口地址做成可配置化。

**Comment by binarywang** [comment]
这个实现起来可能比较麻烦，欢迎提供可行方案

**Comment by fcfc20050545** [comment]
你的这种场景，直接在你内网做微信域名解析到你的内网地址不就可以了。这样你的网络环境调整了，调整你的解析，不然服务多了还要去各个服务改这个接口地址

**Comment by apple0407** [comment]
问题是哪天WeChat改了接口Api的地址，又不能配置，怎么破，要等官方出新版本重新编译程序再上线吗？
所以个人也认为接口地址可配置化，如果没配置，再使用默认地址。

**Comment by fcfc20050545** [comment]
WeChat改api地址是不可能的，域名修改不可能，具体api路径修改更加不可，它作为一个第三方提供商，修改接口地址这种操作对用户带来对影响是巨大的。最极端的做法他是会废弃旧接口A，就是不提供更新，然后开放一个新接口A1。那时候你用它的新接口新功能你再用新的api。

**Comment by binarywang** [comment]
企业微信有私有化部署的场景，已经在https://github.com/Wechat-Group/WxJava/pull/1065 实现。
其他模块是否有必要，待商榷

**Comment by binarywang** [comment]
3.4.3.B 版本已增加公众号可配置接口请求域名地址的支持，具体参考 `me.chanjar.weixin.mp.api.WxMpConfigStorage#getHostConfig` 方法，如果需要，请实现该接口自行设置相关参数即可。
