### ISSUE TITLE
mvn下载相关源码后，所有中文都是乱码

### ISSUE THREAD

**Issue by vangogh-ken** [binarywang/WxJava#104]
mvn下载相关源码后，所有中文都是乱码。应该是打包的时候的问题吧，完全没发看了

**Comment by binarywang** [comment]
打包没问题，编码统一都是utf-8，是你自己的客户端编码设置问题吧！

**Comment by gyb** [comment]
估计是因为IDE默认的编码是GBK。
以eclipse为例，点Window->Preferences->General->Workspace，设置Text file encoding为UTF-8。如果还是乱码，重启eclipse就行了。
