### ISSUE TITLE
小程序和网页端的后台是一个项目，在这个项目中引入微信支付，appid应该怎么填

### ISSUE THREAD

**Issue by GitBiao** [binarywang/WxJava#1041]

**Comment by GitBiao** [comment]
![image](https://user-images.githubusercontent.com/28030821/57508893-5e0ecd00-7335-11e9-8e0d-19573dc41d6c.png)
如题，我这种情况该怎么处理

**Comment by binarywang** [comment]
网页端是个什么鬼，你用哪个帐号的微信支付，就写哪个帐号的appid

**Comment by GitBiao** [comment]
> 网页端是个什么鬼，你用哪个帐号的微信支付，就写哪个帐号的appid

微信支付账号是商户id，但是微信支付的Navicat支付和小程序支付分别是小程序的appid和公众号的appid

**Comment by Senorsen** [comment]
确实，这儿应该还是微信支付的 appid ，但小程序那边支付还要再签名一次（用小程序的 appId ，I 大写）。搜了一下，这个项目似乎还没有这个功能。
参考：https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=3#

**Comment by binarywang** [comment]
> 确实，这儿应该还是微信支付的 appid ，但小程序那边支付还要再签名一次（用小程序的 appId ，I 大写）。搜了一下，这个项目似乎还没有这个功能。
> 参考：https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=3#

你说的这个是createOrder这个方法已经封装好的了，跟jsapi的一样
