### ISSUE TITLE
@RequestMapping("/wx/portal/{appid}")  这个appId 直接传过来的？  还有别的方式 ？谢谢啦

### ISSUE THREAD

**Issue by hejie** [binarywang/WxJava#1043]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__明确描述下你所遇到的问题，如果是新功能或接口需求，请提供对应微信官方文档地址以便查阅。__
@RequestMapping("/wx/portal/{appid}")  这个appId 直接传过来的？  还有别的方式 ？谢谢啦

### 模块版本情况

* WxJava 模块名: 
* WxJava 版本号:

### 期待结果 和 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
大哥，注意下你发的东西内容，另外属于demo的问题，不要在这里提问，要对号入座，不要随意询问无关问题，谢谢合作
