### ISSUE TITLE
建议支持：“任务卡片”消息

### ISSUE THREAD

**Issue by domainname** [binarywang/WxJava#1046]
任务卡片为企业微信最新版本 2.8.2 加入。

官方说明详见：https://work.weixin.qq.com/api/doc#90000/90135/90236/%E4%BB%BB%E5%8A%A1%E5%8D%A1%E7%89%87%E6%B6%88%E6%81%AF

**Comment by binarywang** [comment]
还多了一个接口：更新任务卡片消息状态
https://work.weixin.qq.com/api/doc#90000/90135/91579

**Comment by binarywang** [comment]
关的有点早，我一般是等发布版本后再关

**Comment by domainname** [comment]
@binarywang 
哦，不太熟悉流程，抱歉 ;-)
BTW，计划什么时候发？

**Comment by binarywang** [comment]
已发布

**Comment by domainname** [comment]
Cheers!
