### ISSUE TITLE
2016开源软件评选

### ISSUE THREAD

**Issue by anjia0532** [binarywang/WxJava#105]
http://www.oschina.net/project/top_cn_2016

**Comment by binarywang** [comment]
别闹，这里面又没有我们的事，你想说啥？

**Comment by lovefrr** [comment]
支持参与。

**Comment by binarywang** [comment]
没我们的事，人家名单早就订好了，我们作为吃瓜群众静静的看着就行了

**Comment by binarywang** [comment]
https://www.oschina.net/p/weixin-java-tools-new 没事的都可以帮忙去评论或者完善文档什么的，明年能不能进榜单就得靠各位努力了！
