### ISSUE TITLE
企业微信getUserInfo的返回类型优化

### ISSUE THREAD

**Issue by Nemo1986** [binarywang/WxJava#1053]
getUserInfo现在返回的值类型是String[]，而这个接口https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo 返回的类型比较多，见页面（https://work.weixin.qq.com/api/doc#90000/90135/91023）。
a) 当用户为企业成员时返回示例如下：
```
{
   "errcode": 0,
   "errmsg": "ok",
   "UserId":"USERID",
   "DeviceId":"DEVICEID"
}
```
b) 非企业成员授权时返回示例如下：
```
{
   "errcode": 0,
   "errmsg": "ok",
   "OpenId":"OPENID",
   "DeviceId":"DEVICEID"
}
```
String[]的值类型根本无法反应真实情况，比如说我不知道获取到的值，是openid还是UserId。
可不可以返回成map，哪怕字符串也行。

**Comment by binarywang** [comment]
可以改，如果可以欢迎提供你认为可行的修改代码，并提交PR。

**Comment by binarywang** [comment]
3.4.1.B测试版本已优化
