### ISSUE TITLE
投放卡券-二维码缺失不少参数

### ISSUE THREAD

**Issue by ljg601105597** [binarywang/WxJava#1055]
缺失字段,比如 openid指定领取者的openid

**Comment by binarywang** [comment]
请提供完整文档地址，并尽量按照模版发issue，谢谢合作

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025062 请问是“1 创建二维码接口” 这个吗？

**Comment by ljg601105597** [comment]
对




------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>; 
发送时间: 2019年6月3日(星期一) 下午5:49
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com>; 
抄送: "错过的流年"<601105597@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Wechat-Group/WxJava] 投放卡券-二维码缺失不少参数 (#1055)




https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025062 请问是“1 创建二维码接口” 这个吗？

**Comment by binarywang** [comment]
3.4.3.B 版本 已添加，下次提issue请尽量详细些，谢谢楼主了
