### ISSUE TITLE
小程序getUserInfo rawData数据经过了URLEncode编码，解密数据也报错

### ISSUE THREAD

**Issue by 15915866929** [binarywang/WxJava#1056]
sessionKey----------------:tfx8N89JqjmzBMMCiE3Egw== 

rawData-------------------:{"nickName":"%f0%9f%91%80","gender":0,"language":"zh_CN","city":"","province":"","country":"","avatarUrl":"https%3a%2f%2fwx.qlogo.cn%2fmmopen%2fvi_32%2fpH1tMYOD6zH9tLE3fwFXR0x8mQtwM9Vd2ogWQWQI9BSkzQt9GNpSkicIYV6TdhnmFL4GrE3WYibPVBhxzj0lU6iag%2f132 

iv------------------------:OXMAx+EBxcd/iTad/WIILA== 

signature-----------------:e2ae3222e952475694dbf7ec0a91f34fb379c0f3 

encryptedData-----------------:7gHMSMOaV24RBd4oieEiWDHiDPfpE9jna9vC1S/yO/FqEHBeSNbYwOB7bBNQycXYX6TAzTb48F7uOGg0ZZyQIA415VQjmp1TXDN/WEgB8TUfU8edb6UMtZXDyEneqg99EC7KKAhjG1p5nVEyXeqmtX6NpchF149p5ExcfKX8EgBuBocZkVLH65GbOqs/dm1URMNIoEPmYTFaFmOYM/Z6marFkTS0nXh9shU5e4B/YY0syADYTQKuhIYdk9XX6l2B3PoMalzasDYsFEEIhf6Je6a2FD7DY0AeGbeqGMIxkIjl+MKK47Gms1hDrXsMdBc3iWpwdb43QNkn1XX8fUjRXmHZxYknbWV3k6FXnYMMdng+5igcAOeG3mmzExOup46U9yhx/jLFoUpqQsL+FIIdPkpsFx4wFcDgEXDY+9YGaCh4/KLoDuDxFmCUC0RJjcZ3a4fmWacFcwEBqhPg6w0C5FRp9BR0iaIpfIiNaqv9sRM=

**Comment by binarywang** [comment]
请先先参考下置顶区问题，如果依然无法解决，请按要求格式准确清晰描述问题，谢谢合作~
