### ISSUE TITLE
换取临时二维码ticket的方法参数不合理

### ISSUE THREAD

**Issue by lvxiaohao** [binarywang/WxJava#106]
官方文档对scene_id的解释为 
>场景值ID，临时二维码时为32位非0整型，永久二维码时最大值为100000（目前参数只支持1--100000） 

但是目前工具包中定义的第一个参数为int类型
```java
WxMpQrCodeTicket qrCodeCreateTmpTicket(int scene_id, Integer expire_seconds) throws WxErrorException;
```
无法满足较长数字作为临时二维码scene_id的需求。
建议增加第一参数为String类型第二参数为int类型的重载方法，参数校验时卡控scene_id长度32位以及不能出现非数字字符。

**Comment by binarywang** [comment]
楼主可能理解错了，32位的意思，不是说长度是32位，而是指二进制的位数是32位，java中int类型也正好是32位的，至于非零校验我觉得可以加上

**Comment by binarywang** [comment]
楼主没反应，我就当你理解了，先关闭了啊，如有问题再随时留言即可
