### ISSUE TITLE
微信卡券签名问题

### ISSUE THREAD

**Issue by zhanuuuuu** [binarywang/WxJava#1060]
### 简要描述
__微信公众号内,卡卷的网页投放方式,后端的签名有问题,不是遵循ACSII码从大到小的排序规则。__

### 模块版本情况

* WxJava 模块名: 卡卷投放
* WxJava 版本号:<weixin-java-mp.version>3.4.0</weixin-java-mp.version>

### 解决方法
1. 
![image](https://user-images.githubusercontent.com/35062847/58687135-5fbb3600-83b3-11e9-9533-9cd14577f3ba.png)

2. 
![image](https://user-images.githubusercontent.com/35062847/58687508-626a5b00-83b4-11e9-85f6-08f97d183bcb.png)

### 参考
__你可以看下这里就明白了 [强烈建议开发者使用卡券资料包中的签名工具SDK进行签名或使用debug工具进行校验](http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=cardsign) __

**Comment by binarywang** [comment]
欢迎直接提交PR代码

**Comment by binarywang** [comment]
3.4.2.B测试版本已修复，欢迎帮忙验证

**Comment by zidoshare** [comment]
![image](https://user-images.githubusercontent.com/11310504/60079444-8412f400-9760-11e9-9d87-847f4b4bd6fa.png)

@binarywang  仍然报错，签名错误

**Comment by binarywang** [comment]
> ![image](https://user-images.githubusercontent.com/11310504/60079444-8412f400-9760-11e9-9d87-847f4b4bd6fa.png)
> 
> @binarywang 仍然报错，签名错误

你这是同一个问题吗？明显不是，卡券都不是微信支付的东西，请仔细分析，如果确实有问题，请新开issue，不要在这里回复了，谢谢合作
