### ISSUE TITLE
请问更新人员功能，能让部门id支持String类型吗

### ISSUE THREAD

**Issue by yolkyliu** [binarywang/WxJava#1061]
请问更新人员功能，能让部门id支持String类型吗

**Comment by binarywang** [comment]
大哥，问题能否描述稍稍清楚些？比如是什么模块，哪个接口，文档地址是什么，微信那么多功能呢

**Comment by binarywang** [comment]
如果是指的企业微信里的部门id，那抱歉，不支持，官方就是数字，不可能改成string的
