### ISSUE TITLE
usePath 作用

### ISSUE THREAD

**Issue by shoemakers** [binarywang/WxJava#1066]
### 简要描述
在模板消息跳转小程序时，需要携带参数，在公众号官方文档中只有path一个变量，但是在使用WxJava发送模板消息时，发现有一个usePath的变量为true。不知道是否影响我携带参数。
并且查看源码发现，直接发送的请求，只是多了一个usePath的变量，不知道usePath的作用是什么，麻烦解答一下，谢谢。。。。

### 模块版本情况

* WxJava 模块名:  mp
* WxJava 版本号: 3.3.0

**Comment by binarywang** [comment]
请注意仔细看注释

**Comment by binarywang** [comment]
代码里有注释，请自行查看
