### ISSUE TITLE
有安全删除接口服务的功能吗？

### ISSUE THREAD

**Issue by zjxpcyc** [binarywang/WxJava#1068]
首先，我本人不是专业 JAVA 开发，但是能看懂 copy 一些简单代码。

我看 demo 上是支持多个微信服务一起注册，执行的。

如何实现，某个微信服务的热插拔，或者动态的删除增加。

我这边想封装一个类似微信服务中心的东西，由于我们公司要维护的公众号太多，而且很乱。我这边想做一个慢慢梳理收集的工作，就是把我们维护的公众号服务，全部收集到一个服务中心去。

这样就是势必涉及一个热插拔的问题。现在动态添加服务，我这边已经实现了。怎么能安全删除呢？

就是，我某个服务号到期不维护了，或者那个服务号因为某种原因不能再统一维护了，怎么能把它停掉，删掉 ？

**Comment by binarywang** [comment]
属于你前端调用的问题，你不调用对应公众号的接口不就行了吗？建议再仔细阅读下对应demo源码，深刻理解下，也许你就不会问这种问题了

**Comment by zjxpcyc** [comment]
你的意思是，只要不调用对应公众号的接口，那么对应的服务是不运行的是吧？ 比如 token 的定时获取任务，也是不执行的？

我比较担心的问题重点是，比如我从服务 bus （其实是一个 map） 里面把对应的 service remove之后，但是这个 service 还有异步的 task 在跑就不好了。

**Comment by binarywang** [comment]
> 你的意思是，只要不调用对应公众号的接口，那么对应的服务是不运行的是吧？ 比如 token 的定时获取任务，也是不执行的？
> 
> 我比较担心的问题重点是，比如我从服务 bus （其实是一个 map） 里面把对应的 service remove之后，但是这个 service 还有异步的 task 在跑就不好了。

这只是一个sdk，没有你所谓的定时获取任务，所有的接口调用都是你自己来控制的，自己控制好就行了

**Comment by zjxpcyc** [comment]
thx
