### ISSUE TITLE
微信会员卡设置里添加了小程序入口设置

### ISSUE THREAD

**Issue by varietyenen** [binarywang/WxJava#1069]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，谢谢合作~

### 简要描述
__请提供所需功能对应的微信官方文档地址以便进行确认。__

微信会员卡积分类目设置小程序
"bonus_app_brand_user_name":"小程序原始ID@app",
"bonus_app_brand_pass":"小程序路径",
类型设置小程序
"custom_field3": {
	"name_type": "FIELD_NAME_TYPE_TIMS",
	"url": "",
	"app_brand_user_name":"小程序原始ID@app",
	"app_brand_pass":"小程序路径"
}
微信会员卡中间按钮设置小程序
"center_app_brand_user_name":"小程序原始ID@app",
"center_app_brand_pass":"小程序路径",
使用入口-可以添加到2个
"custom_cell1": {
	"name": "使用入口1",
	"tips": "激活后显示1",
	"url": "http://www.qq.com",
	"app_brand_user_name":"小程序原始ID@app",
	"app_brand_pass":"小程序路径"
},"custom_cell2": {
	"name": "使用入口1",
	"tips": "激活后显示1",
	"url": "http://www.qq.com",
	"app_brand_user_name":"小程序原始ID@app",
	"app_brand_pass":"小程序路径"
},
立即使用小程序
"custom_app_brand_user_name": "小程序原始ID@app",
"custom_app_brand_pass":"小程序路径",

**Comment by binarywang** [comment]
请仔细描述，补充相关内容

**Comment by binarywang** [comment]
描述不清楚，直接关闭
