### ISSUE TITLE
多企业微信

### ISSUE THREAD

**Issue by libingspace** [binarywang/WxJava#1070]
请问是否可以支持多企业微信呢？thanks

**Comment by binarywang** [comment]
请参考demo实现

**Comment by libingspace** [comment]
> 请参考demo实现

啊？已经支持了的么？马上去看下

**Comment by libingspace** [comment]
@binarywang 老大，是多个企业微信的支持，我看到demo还是只能支持一个crop哈。只是支持一个企业微信下的多个应用而已

**Comment by binarywang** [comment]
有很大区别吗？

**Comment by libingspace** [comment]
哦 老大的意思是 自己扩展哈。明白，那就参考多公众号来扩展一下
