### ISSUE TITLE
有集成分账接口吗？

### ISSUE THREAD

**Issue by sxz1314** [binarywang/WxJava#1071]
有集成分账接口吗？

**Comment by binarywang** [comment]
请给出对应文档地址，并按照模版填写相关信息，谢谢配合

**Comment by sxz1314** [comment]
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_1&index=1

> 请给出对应文档地址，并按照模版填写相关信息，谢谢配合

https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_1&index=1

**Comment by binarywang** [comment]
> https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_1&index=1
> 
> > 请给出对应文档地址，并按照模版填写相关信息，谢谢配合
> 
> https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_1&index=1

#1010 你这个请求难道跟这个不是同一个吗？
