### ISSUE TITLE
wxCpService.getAccessToken();空指针异常

### ISSUE THREAD

**Issue by WangYi0220** [binarywang/WxJava#1072]
### 简要描述
wxCpService.getAccessToken();空指针异常

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:3.4.0

### 期待结果 和 实际情况
将accessToken放入缓存
wxCpService.getAccessToken();抛出空指针异常。
异常代码定位： me.chanjar.weixin.common.error.WxError   49行

### 模糊点
依据API及Demo，理解为accessToken自动获取、到期自动刷新
这样理解是否正确？

**Comment by WangYi0220** [comment]
已尝试过用HttpClient获取accessToken，返回为空白，无正确结果，无错误提示

**Comment by binarywang** [comment]
空指针问题很简单，自己仔细分析下是哪个变量为空

**Comment by WangYi0220** [comment]
> 
> 
> 空指针问题很简单，自己仔细分析下是哪个变量为空

不好意思，经验错误，用的测试号
