### ISSUE TITLE
小程序转发客服消息transfer_customer_service 没有实现

### ISSUE THREAD

**Issue by Huzhengtao** [binarywang/WxJava#1074]
小程序转发客服消息没有实现，WxMaMessageHandler为啥不像公众号的MessageHandler一样可以通过返回值来响应请求？

**Comment by binarywang** [comment]
请给出对应文档地址。小程序只有客服消息，没有被动回复消息，这一点你要清楚，区别还是很明显的

**Comment by binarywang** [comment]
没有下文，直接关闭

**Comment by jiffei** [comment]
需要在响应包中返回 MsgType 为 transfer_customer_service 的消息，微信服务器收到响应后会把当次发送的消息转发至客服系统。

**Comment by jiffei** [comment]
大佬竟然直接把这个问题关闭了。。。。

**Comment by jiffei** [comment]
小程序客服消息，服务端接管后可以自动回复，但是有些还是需要人工客服介入，需要把消息转发的人工客服。

**Comment by binarywang** [comment]
不按要求发issue的直接关闭，你如果能描述清楚，请新开issue，不要在这里跟帖了，谢谢合作

**Comment by jiffei** [comment]
文档地址：https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/customer-message/trans.html
期望大佬把这个加进去。

**Comment by xiaodong1978** [comment]
private final WxMaMessageHandler customerServiceMessageHandler = new WxMaMessageHandler() {
        @Override
        public WxMaXmlOutMessage handle(WxMaMessage message,
                                        Map<String, Object> context,
                                        WxMaService service,
                                        WxSessionManager sessionManager) {
            
            return new WxMaXmlOutMessage()
                    .setMsgType(WxConsts.XmlMsgType.TRANSFER_CUSTOMER_SERVICE)
                    .setFromUserName(message.getToUser())
                    .setCreateTime(Calendar.getInstance().getTimeInMillis() / 1000)
                    .setToUserName(message.getFromUser());
        }
    };

我也碰到这个问题，这样做也是无法转网页或移动端客服。

**Comment by xiaodong1978** [comment]
不知这个关闭的issues 还有没有人管

**Comment by awaken233** [comment]
> private final WxMaMessageHandler customerServiceMessageHandler = new WxMaMessageHandler() { @OverRide public WxMaXmlOutMessage handle(WxMaMessage message, Map<String, Object> context, WxMaService service, WxSessionManager sessionManager) {
> 
> ```
>         return new WxMaXmlOutMessage()
>                 .setMsgType(WxConsts.XmlMsgType.TRANSFER_CUSTOMER_SERVICE)
>                 .setFromUserName(message.getToUser())
>                 .setCreateTime(Calendar.getInstance().getTimeInMillis() / 1000)
>                 .setToUserName(message.getFromUser());
>     }
> };
> ```
> 
> 我也碰到这个问题，这样做也是无法转网页或移动端客服。

+1, 遇到同样的问题。解决同学能at我下吗？谢谢
