### ISSUE TITLE
小程序支持转发客服消息

### ISSUE THREAD

**Issue by jiffei** [binarywang/WxJava#1079]
文档地址：https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/customer-message/trans.html
期望大佬把这个加进去。

**Comment by jiffei** [comment]
好像有。。。

**Comment by binarywang** [comment]
你俩是同一个人？怎么发的标题都一样？

**Comment by jiffei** [comment]
不是同一个人，我懒，就ctrl+v了。

**Comment by jiffei** [comment]
公众号的已经实现了，小程序没有。

**Comment by binarywang** [comment]
3.4.5.B版本已支持，欢迎试用

**Comment by binarywang** [comment]
代码实现有问题，#1254 发现并修复
