### ISSUE TITLE
#997中新增加的接口的调整建议

### ISSUE THREAD

**Issue by danderCN** [binarywang/WxJava#1080]
#997问题中，新增了一个针对企业微信小程序登录wx.qy.login获取code，换取用户openid的jsCode2Session方法，但是新增方法的调用依然需要使用原有的WxCpService来调用，而WxCpService的获取需要使用到对应应用的agentid，可是在纯企微小程序的开发中没有对应的应用agentid。
因此建议针对企业微信小程序的jsCode2Session方法，是否能去掉agentid获取WxCpService？

**Comment by binarywang** [comment]
talk is cheap，show me the code

可以直接提交PR吗？

关联 #997

**Comment by danderCN** [comment]
对您的源码部分了解不多，无法提交pr来来帮助，惭愧。
表达能力有限，望理解
这边问题大概是这样的。
1、企业微信小程序开发本身和普通小程序一致，生成后是直接企业关联绑定，与企微的应用开发无关。
2、小程序端调用wx.qy.login拿到code传到后台，后台使用code请求
https://qyapi.weixin.qq.com/cgi-bin/miniprogram/jscode2session?access_token=ACCESS_TOKEN&js_code=CODE&grant_type=authorization_code
这个地址获取用户userid、corpid、session_key。
3、2中的ACCESS_TOKEN使用的是企业的corpid和corpsecret获取的，与应用无关。
4、解决以上问题您在#997中为WxCpService新增了jsCode2Session方法。
5、但WxCpService的获取，需要使用到agentId，WxCpConfiguration.getCpService(SysConst.AGENT_ID)，可是小程序开发实际并没有AGENT_ID可以用。
![image](https://user-images.githubusercontent.com/28424130/59892597-4c2c4980-940c-11e9-8d43-b15a0fee4014.png);

总结起来就是：企微小程序接口jscode2session，与企微应用无关，但是目前版本中调用jscode2session却需要使用到应用的agentId。

**Comment by binarywang** [comment]
既然与应用无关，你随便用一个应用不就可以了吗？

**Comment by binarywang** [comment]
另外所谓的corpsecret就是指某一个应用的secret，你可能对企业微信开发还不了解，建议仔细阅读下相关文档。

**Comment by CuriousRookie** [comment]
现在才看到，其实企业微信管理后台关联一个小程序就相当于添加企业微信的应用，是有分配agentid的，如果是自建而不是第三方的话还有secret，你可以进入企业微信管理后台看下

小程序要支持企业微信，服务端API目前需要调用的貌似就[获取access_token](https://work.weixin.qq.com/api/doc#10013/%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E8%8E%B7%E5%8F%96access_token)、[登录凭证校验](https://work.weixin.qq.com/api/doc#90000/90136/90289/%E7%99%BB%E5%BD%95%E5%87%AD%E8%AF%81%E6%A0%A1%E9%AA%8C)和[发送应用消息 - 小程序消息](https://work.weixin.qq.com/api/doc#90000/90135/90236/%E5%B0%8F%E7%A8%8B%E5%BA%8F%E9%80%9A%E7%9F%A5%E6%B6%88%E6%81%AF)(企业微信关联小程序应用不允许发送其他类型应用消息)，可以自己实现这三个接口调用，不需要引入WXCP。。。
