### ISSUE TITLE
小程序服务端接口auth.code2Session 调用出现45009错误，因为调了 AccessToken，但此接口并不需要 AccessToken。

### ISSUE THREAD

**Issue by qingyun111** [binarywang/WxJava#1085]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__明确描述下你所遇到的问题。__

### 模块版本情况

* WxJava 模块名: 
* WxJava 版本号:

### 期待结果 和 实际情况
__尽量详细描述__

### 重现步骤
1. 
2. 
3. 

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将url地址贴在这里__

**Comment by binarywang** [comment]
请注意规范下问题内容，直接关闭，下次发帖请注意

**Comment by qingyun111** [comment]
好吧，感谢你的回复




------------------ 原始邮件 ------------------
发件人: "Binary Wang"<notifications@github.com>;
发送时间: 2019年6月23日(星期天) 下午3:05
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com>;
抄送: "青云"<183546225@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Wechat-Group/WxJava] 小程序服务端接口auth.code2Session 调用出现45009错误，因为调了 AccessToken，但此接口并不需要 AccessToken。 (#1085)




请注意规范下问题内容，直接关闭，下次发帖请注意

**Comment by youyanghust** [comment]
+1
