### ISSUE TITLE
应该支持设置APIV3的秘钥

### ISSUE THREAD

**Issue by dltc** [binarywang/WxJava#1086]
### 简要描述
http://kf.qq.com/faq/180830E36vyQ180830AZFZvu.html
大意就是 下单的时候用的是key1进行签名，回调的数据是用的key2进行签名，SDK应该要支持设置这个APIv3密钥

**Comment by binarywang** [comment]
得配合新的api才能用吧？ https://wechatpay-api.gitbook.io/wechatpay-api-v3/

**Comment by 809662683** [comment]
我发现微信支付的文档不是一般的烂，一堆问题，另外这个APIv3应该是没启用吧，以前小微商那边好像有文档，现在直接都被删没了。我想知道哪里有看到这个API V3的使用场景？楼主能给下文档地址？我找到的唯一地址是https://pay.weixin.qq.com/wiki/doc/api/xiaowei.php?chapter=19_11#， 但是你会发现从左侧的导航栏里面压根找不到进这个地址的菜单。。。

**Comment by binarywang** [comment]
#1089

**Comment by binarywang** [comment]
如果无法使用，暂时不考虑了
