### ISSUE TITLE
微信支付结果通知 返回后 仍然继续通知多次

### ISSUE THREAD

**Issue by shenqiancheng** [binarywang/WxJava#1088]
return WxPayNotifyResponse.success("OK");
这样返回  微信仍然会通知多次 

` return "<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg></xml>";`
如果直接用原生的返回 微信就不会通知了

**Comment by binarywang** [comment]
检查下你的spring相关设置，是不是转换有问题，是什么导致的问题？

**Comment by binarywang** [comment]
看看你给微信回复的是什么东西

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_7&index=8
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_7&index=8
https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_7&index=3

看了三种微信支付通知结果的格式，均为如下：

```
<xml>
  <return_code><![CDATA[SUCCESS]]></return_code>
  <return_msg><![CDATA[OK]]></return_msg>
</xml>
```
跟代码输出结果一致，不知道你哪儿来的格式，不带外层的xml？

**Comment by shenqiancheng** [comment]
回复的时候直接复制过来的,  带外层的xml,  应该是github给我转义了.  我已经重新修改

**Comment by binarywang** [comment]
> 回复的时候直接复制过来的, 带外层的xml, 应该是github给我转义了. 我已经重新修改

那你再仔细检查下你回复给微信的内容是什么，有什么区别？

**Comment by einsitang** [comment]
@binarywang 我们公司的项目好像也有这个问题

**Comment by shenqiancheng** [comment]
> > 回复的时候直接复制过来的, 带外层的xml, 应该是github给我转义了. 我已经重新修改
> 
> 那你再仔细检查下你回复给微信的内容是什么，有什么区别？

二者返回给微信的内容
`<xml>\n  <return_code><![CDATA[SUCCESS]]></return_code>\n  <return_msg><![CDATA[OK]]></return_msg>\n</xml>`

`<xml><return_code><![CDATA[SUCCESS]]></return_code><return_msg><![CDATA[OK]]></return_msg></xml>`

**Comment by binarywang** [comment]
就因为多了几个换行符吗？

**Comment by shenqiancheng** [comment]
> 就因为多了几个换行符吗？

可能是吧

**Comment by binarywang** [comment]
什么鬼，如果真是这个问题，那就真是离谱到家了，他们自己提供的样例就是带换行和空格的。

**Comment by binarywang** [comment]
3.4.7.B测试版本 已修复，欢迎试用
