### ISSUE TITLE
增加微信支付API v3的支持

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#1089]
https://wechatpay-api.gitbook.io/wechatpay-api-v3/

**Comment by binarywang** [comment]
不知道现在是否可用，有在使用的麻烦给点信息

**Comment by rokaye** [comment]
v3 的接口可以使用，我们项目调试通过了

**Comment by binarywang** [comment]
> v3 的接口可以使用，我们项目调试通过了

欢迎提供代码，哈哈

**Comment by zhangalex** [comment]
https://github.com/wechatpay-apiv3/wechatpay-apache-httpclient

现在遇到比较坑的事情，海外版必须使用V3，上面的是httpclient相关的代码和文档。比起v2鉴权改动很大，可能需要完全重写了。
