### ISSUE TITLE
请问支持微信信用分，免押租借相关接口吗？

### ISSUE THREAD

**Issue by spvycf** [binarywang/WxJava#1090]
https://pay.weixin.qq.com/wiki/doc/apiv3/payscore.php?chapter=18_1&index=2

**Comment by binarywang** [comment]
v3的接口据说现在都没开放。另外请顺便仔细看下你发的内容。

**Comment by binarywang** [comment]
建议有在使用的提供下相关实现代码。

**Comment by spvycf** [comment]
我在公司实现了这块相关代码，怎么把相关代码提交给你看看

**Comment by spvycf** [comment]
> 建议有在使用的提供下相关实现代码。
我在公司实现了这块相关代码，怎么把相关代码提交给你看看

**Comment by binarywang** [comment]
> 我在公司实现了这块相关代码，怎么把相关代码提交给你看看

提交PR即可，看下代码贡献指南

**Comment by spvycf** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter3_1.shtml

**Comment by spvycf** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter3_1.shtml
微信更新了支付分相关api。此api应用于免押租借相关。官方文档更直接一点。

**Comment by binarywang** [comment]
> https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter3_1.shtml
> 微信更新了支付分相关api。此api应用于免押租借相关。官方文档更直接一点。

欢迎提交PR，谢谢

**Comment by binarywang** [comment]
3.8.0正式版本已增加相关接口，感谢楼主的贡献
