### ISSUE TITLE
网页授权获取OPENID

### ISSUE THREAD

**Issue by shenqiancheng** [binarywang/WxJava#1093]
JSAPI统一下单接口, 需要获取openid, 希望增加 code获取openid的接口.
文档地址: https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842

**Comment by binarywang** [comment]
你确定现在没有吗？

**Comment by shenqiancheng** [comment]
找到了.  这个方法在weixin-java-mp模块中,  而weixin-java-pay这个模板却没有. 我却偏偏只需要支付模块.

**Comment by binarywang** [comment]
准备在开放平台模块加入相关接口
