### ISSUE TITLE
自定义菜单支持更多的类型

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#11]
详细文档参考：http://mp.weixin.qq.com/wiki/10/0234e39a2025342c17a7d23595c6b40a.html

**Comment by kareanyi** [comment]
@binarywang 我在本地改了测试用例跑了单元测试，原先的结构就能够支持新增的按钮类型了。
WxConsts里面 有两个类型没有，但是这两个类型是“专门给第三方平台旗下未微信认证（具体而言，是资质认证未通过）的订阅号准备的事件类型，它们是没有事件推送的，能力相对受限，其他类型的公众号不必使用” 我不确定是否要添加

**Comment by binarywang** [comment]
@kareanyi 那加上也无所谓吧，有人想用就用，不用也不会影响的

**Comment by kareanyi** [comment]
嗯嗯。提了
