### ISSUE TITLE
微信付款 A component required a bean of type 'com.github.binarywang.wxpay.service.WxPayService' that could not be found.

### ISSUE THREAD

**Issue by ghl0903** [binarywang/WxJava#1102]
![image](https://user-images.githubusercontent.com/9345627/60814800-ea6c2d80-a1c8-11e9-8984-2cfb2fd8d02e.png)
![image](https://user-images.githubusercontent.com/9345627/60814814-ee984b00-a1c8-11e9-920b-d28337f95f1b.png)
![image](https://user-images.githubusercontent.com/9345627/60814823-f1933b80-a1c8-11e9-877e-9823b2f660fa.png)

调用微信支付的时候 遇到这个问题 有人遇到过吗

**Comment by binarywang** [comment]
请尽量不要使用图片，能用文字描述清楚，就不要发图片了，太浪费网络资源了

**Comment by binarywang** [comment]
你的问题看来像是基础问题，没有更多信息可进一步判断，建议加强学习一下spring相关基础知识。
