### ISSUE TITLE
微信支付回调处理

### ISSUE THREAD

**Issue by zhankun** [binarywang/WxJava#1104]
在微信支付回调处理中，文档中写到：“异步回调接口代码内部会自动校验结果签名和业务代码，您需要做的就是拿到结果之后直接处理就行了；”，示例代码中：
`WxPayOrderNotifyResult result = wxPayService.parseOrderNotifyResult(xmlResult);
    // 结果正确
    String orderId = result.getOutTradeNo();
    String tradeNo = result.getTransactionId();
    String totalFee = BaseWxPayResult.fenToYuan(result.getTotalFee());
    //自己处理订单的业务逻辑，需要判断订单是否已经支付过，否则可能会重复调用`
但是wxPayService.parseOrderNotifyResult这个方法里面并没有对回调结果进行校验，checkSuccess这个参数值为false。所以外面还需要自己校验支付结果是否成功才能进行业务处理

**Comment by binarywang** [comment]
文档是针对早期代码而言，未作同步更新。
实际上支付是否成功，应该由你自己去判断控制。
