### ISSUE TITLE
微信语音素材下载失败

### ISSUE THREAD

**Issue by yoqu** [binarywang/WxJava#1105]
### 简要描述
使用微信的js sdk进行录音并将录音文件进行上传，得到素材id。
因为业务需要所以下载语音素材需要speex格式，
调用https://api.weixin.qq.com/cgi-bin/media/get/jssdk接口提示权限异常，返回数据为：{"errcode":48001,"errmsg":"api unauthorized hint: [.cIurA0994z200!]"}。
调用https://api.weixin.qq.com/cgi-bin/media/get没有问题。
当前微信公众号的权限为订阅号，已排除不是自己代码调用问题，因为使用测试公众号能够下载语音素材。
请问下这个是否跟微信公众号的类型有关呢？

**Comment by binarywang** [comment]
应该有关系，订阅号权限很少，建议查看自己的权限列表来确认。
