### ISSUE TITLE
WxCpTp获取永久授权码解析JSON时 发生错误

### ISSUE THREAD

**Issue by yaoye6262** [binarywang/WxJava#1109]
企业安装应用时 获取auth_code

通过WxCpTpService.getPermanentCode(“预授权码”)

BaseWxCpTpServiceImpl getPermanentCode方法以下代码发生错误：

WxCpTpCorp wxCpTpCorp = WxCpTpCorp.fromJson(jsonObject.get("auth_corp_info").getAsString());
    wxCpTpCorp.setPermanentCode(jsonObject.get("permanent_code").getAsString());

直接抛异常！

### 模块版本情况

* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 3.4.6.B

**Comment by binarywang** [comment]
请删除无用内容，谢谢，如果需要尽快修复，建议自行提交PR

**Comment by binarywang** [comment]
@feye 请帮忙确认下问题，谢谢

**Comment by binarywang** [comment]
楼主如果确认问题所在，请指出，并给出完整出错信息，方便定位

**Comment by yaoye6262** [comment]
应该是 jsonObject.get("auth_corp_info").getAsString() 

在jsonObject.getAsString()时 抛出的异常 

只要.getAsString() 就会出现异常

按照源码走 .toString() 就没有任何问题

可是试着更新下 gson 包

**Comment by binarywang** [comment]
> 应该是 jsonObject.get("auth_corp_info").getAsString()
> 
> 在jsonObject.getAsString()时 抛出的异常
> 
> 只要.getAsString() 就会出现异常
> 
> 按照源码走 .toString() 就没有任何问题
> 
> 可是试着更新下 gson 包

按你的意思，auth_corp_info这个不是string？能否给出你那边的响应原始报文？

**Comment by binarywang** [comment]
经过模拟官方文档所提供数据进行测试，发现确实是代码有问题，原代码作者可能都没测试就把代码提交了上来，非常抱歉。

**Comment by binarywang** [comment]
官方文档地址：https://work.weixin.qq.com/api/doc#90001/90143/90603

**Comment by binarywang** [comment]
3.5.2.B 测试版本已修复，麻烦验证一下，谢谢了
