### ISSUE TITLE
微信支付-查询退款接口-对返回结果的签名校验出错

### ISSUE THREAD

**Issue by nopower** [binarywang/WxJava#111]
如下几个参数未参与签名校验
out_refund_no_0
refund_channel_0
refund_fee
refund_fee_0
refund_id_0
refund_recv_accout_0
refund_status_0
这是一次退款的返回结果，还可能有一次支付多次退款的结果查询

**Comment by binarywang** [comment]
退款查询接口确实是有问题，需要完善并修复一下

**Comment by binarywang** [comment]
已经做了修复，代码已经提交，并发布了2.4.7.BETA版本，你可以测试下看看，是否有问题，有问题请及时提出来，多谢~

**Comment by binarywang** [comment]
@nopower 不知道你是否已经做了验证，不过这个问题还是先关掉了，等你看到回复后有问题再随时留言即可

**Comment by nopower** [comment]
@binarywang ,谢谢，之前我已经自己override了一个实现，还想建议你不要用反序列化后的对象去构造签名，不过看你的后面的版本已修改了相应的toMap方法从源返回结果遍历构造了，哈哈非常感谢你的回复修改哈

**Comment by binarywang** [comment]
@nopower 欢迎随时提供好的修改建议。☺
