### ISSUE TITLE
针对境外支付，可否增加地址的选择和兼容问题

### ISSUE THREAD

**Issue by wzk9543** [binarywang/WxJava#1111]
接口地址
https://apihk.mch.weixin.qq.com/pay/unifiedorder    （建议接入点：东南亚）
https://apius.mch.weixin.qq.com/pay/unifiedorder    （建议接入点：其它）
https://api.mch.weixin.qq.com/pay/unifiedorder        （建议接入点：中国国内）
注：商户可根据实际请求情况选择最优域名进行访问，建议在接入时做好兼容，当访问其中一个域名出现异常时，可自动切换为其他域名。

微信文档:https://pay.weixin.qq.com/wiki/doc/api/external/jsapi.php?chapter=9_1

**Comment by binarywang** [comment]
楼主请注意下所发issue的内容

**Comment by binarywang** [comment]
3.4.8.B测试版本已添加对应配置参数，欢迎试用，如有新问题，请新开issue，谢谢；
另外自动切换的问题请自行解决，sdk无法判断。
