### ISSUE TITLE
企业微信WxCpUser类中缺少is_leader_in_dept字段

### ISSUE THREAD

**Issue by Moonlight15111** [binarywang/WxJava#1112]
这是3.4.0版本中此类的源码
![image](https://user-images.githubusercontent.com/26769031/61192456-13b81c80-a6e7-11e9-816c-44540df0daf9.png)
这是企业微信官方文档的参数说明
![image](https://user-images.githubusercontent.com/26769031/61192626-54646580-a6e8-11e9-8814-e8ecb86778e0.png)
在某些需要用到is_leader_in_dept字段的场景下，比如根据该字段对成员进行部门权限的分配，该类起到的作用就不是很大了，建议大佬在该类中新增此字段。

**Comment by binarywang** [comment]
请尽量贴出文档地址，或者发文字，不用发截图，不方便查看

**Comment by binarywang** [comment]
文档地址：https://work.weixin.qq.com/api/doc#90000/90135/90195

**Comment by binarywang** [comment]
3.4.8.B测试版本已添加该字段，欢迎试用，如有新问题，请新开issue，谢谢
