### ISSUE TITLE
WxCpTp有消息路由吗？

### ISSUE THREAD

**Issue by yaoye6262** [binarywang/WxJava#1114]
企业微信第三方 《成员通知事件》 《部门通知事件》《标签通知事件》WxCpMessageRouter处理不了这些事件！

我能否自己扩展 按照WxCpMessageRouter思路自建一个WxCpTpMessageRouter路由？

我这边是企业微信套件开发！类似suite_ticket 授权通知事件 等希望建个路由统一管理！
还是说我的使用方法错误？

**Comment by binarywang** [comment]
@feye 有空看下吗？

**Comment by binarywang** [comment]
暂时关闭
