### ISSUE TITLE
请问微信第三方代公众号实现逻辑的功能暂不支持吗？

### ISSUE THREAD

**Issue by ong-ing** [binarywang/WxJava#1115]
官方文档位置：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419318587&token=340ab6e8e69019d2064e4b922eccb42d7172f6c7&lang=zh_CN

关于WxJava的demo中，我查看了公众号开发和第三方开发的部分，发现公众号部分的自定义菜单是通过wxService.switchoverTo(appid)的形式去切换公众号配置的（需要配置在yml文件中），但是作为第三方平台，项目中已授权给我们的公众号信息是都存在数据库中，所以项目中我们需要一种可以手动配置appid和access_tokende的处理方法，目前我再源码中未找到这种方法，且第三方开发的demo项目里也没有这方面的代码，请问是现在WxJava项目中不支持第三方代公众号实现业务吗？还是另有其他方法实现？

**Comment by binarywang** [comment]
不要只看demo，Demo只是演示如何使用，具体看本SDK的源码

**Comment by ong-ing** [comment]
> 不要只看demo，Demo只是演示如何使用，具体看本SDK的源码

谢谢，方法我已经找到了，但是现在有个问题，我把代码贴一下
public String getAuthorizerMenuInfo(String appId){
        WxMpService wxMpService=new WxMpServiceImpl();
        Map authorizerInfoMap=appWechatAuthorizerService.getAuthorizerInfoByAppid(componentAppId,appId);
        WxMpInMemoryConfigStorage wxMpInMemoryConfigStorage=new WxMpInMemoryConfigStorage();
        wxMpInMemoryConfigStorage.setAppId(appId);
        wxMpInMemoryConfigStorage.setSecret(null);
        wxMpInMemoryConfigStorage.setAccessToken(getMapValue(authorizerInfoMap,"authorizer_access_token"));
        wxMpService.setWxMpConfigStorage(wxMpInMemoryConfigStorage);
        WxMpMenuService wxMpMenuService=new WxMpMenuServiceImpl(wxMpService);
        WxMpGetSelfMenuInfoResult wxMpGetSelfMenuInfoResult=null;
        try{
            wxMpGetSelfMenuInfoResult=wxMpMenuService.getSelfMenuInfo();
        }catch (WxErrorException e){
            e.printStackTrace();
        }
        return HttpUtil.outputSucc(wxMpGetSelfMenuInfoResult);
    }
这个运行会报me.chanjar.weixin.common.error.WxErrorException: {"errcode":40125,"errmsg":"invalid appsecret, view more at http://t.cn/RAEkdVq hint: [iitQqA00023612]"}，但是第三方获取公众号的菜单不应该只需要传入一个access_token就可以了么，请问是我方法引用的问题吗？

**Comment by 007gzs** [comment]
三方平台代公众号实现逻辑调用方法：
> WxMpService wxMpService = wxOpenService.getWxOpenComponentService().getWxMpServiceByAppid(appId);
>wxMpService.getMenuService().xxx

`wxMpService.switchoverTo`是多公众号开发切换公众号的逻辑，不是三方平台的

**Comment by 007gzs** [comment]
调用方式参考 https://github.com/Wechat-Group/weixin-java-open-demo/blob/1b516352f354b8ab43d1453679c4af9ba8db3c32/src/main/java/com/github/binarywang/demo/wx/open/controller/WechatNotifyController.java#L97

**Comment by ong-ing** [comment]
> 调用方式参考 https://github.com/Wechat-Group/weixin-java-open-demo/blob/1b516352f354b8ab43d1453679c4af9ba8db3c32/src/main/java/com/github/binarywang/demo/wx/open/controller/WechatNotifyController.java#L97

懂了，谢谢大佬😀
