### ISSUE TITLE
最近公司压测微信公众号的消息路由接口，cpu一直飙到100%

### ISSUE THREAD

**Issue by Ritian-Zhang** [binarywang/WxJava#1117]
![image](https://user-images.githubusercontent.com/26291144/61220211-68d84a80-a748-11e9-9c72-40e974dce7b5.png)

**Comment by binarywang** [comment]
楼主有何想法？认为是哪里的问题？

**Comment by binarywang** [comment]
没有进一步回应，暂时忽略

**Comment by hiteny** [comment]
我这里复现了,请问如何上传线程打印文件,帮忙协助解决?

**Comment by hiteny** [comment]
线程打印文件
[a.txt](https://github.com/Wechat-Group/WxJava/files/6002545/a.txt)
