### ISSUE TITLE
关注服务号会报"errcode":61023,"errmsg":"refresh_token is invalid hint:

### ISSUE THREAD

**Issue by gclsoft** [binarywang/WxJava#1119]
redis服务器重启导致redis数据丢了, 现在关注服务号会报【错误信息】：{"errcode":61023,"errmsg":"refresh_token is invalid hint
要怎么解决呢?

**Comment by gclsoft** [comment]
wxjava 第三方平台版本: 3.0.0

**Comment by gclsoft** [comment]
难道必须重新绑定第三方平台才可以解决问题吗? 我们有二十几个服务号,都要这样操作一遍吗?

**Comment by gclsoft** [comment]
急, 在线等

**Comment by gclsoft** [comment]
```
    public String getAuthorizerAccessToken(String appId, boolean forceRefresh) throws WxErrorException {
        if (this.getWxOpenConfigStorage().isAuthorizerAccessTokenExpired(appId) || forceRefresh) {
            JsonObject jsonObject = new JsonObject();
            jsonObject.addProperty("component_appid", this.getWxOpenConfigStorage().getComponentAppId());
            jsonObject.addProperty("authorizer_appid", appId);
            jsonObject.addProperty("authorizer_refresh_token", this.getWxOpenConfigStorage().getAuthorizerRefreshToken(appId));
```
在这一行获取的时候,就是null了, 因为wechat_authorizer_refresh_token:wx8d297785819f414c已经被丢失了, 要怎么再重新获取呢?

**Comment by gclsoft** [comment]
```
    @GetMapping("auth/jump")
    @ResponseBody
    public WxOpenQueryAuthResult jump(@RequestParam("auth_code") String authorizationCode){
        try {
            WxOpenQueryAuthResult queryAuthResult = wxOpenServiceDemo.getWxOpenComponentService().getQueryAuth(authorizationCode);
            logger.info("getQueryAuth", queryAuthResult);
            // 这里要进行缓存才行的吧
            String AppId = queryAuthResult.getAuthorizationInfo().getAuthorizerAppid();
            String reFreshToken = queryAuthResult.getAuthorizationInfo().getAuthorizerRefreshToken();
            wxOpenServiceDemo.getWxOpenConfigStorage().setAuthorizerRefreshToken(AppId, reFreshToken);
```
只有这个地方设置redis, 真的得全部重新绑定了?

**Comment by binarywang** [comment]
@007gzs 有空可以帮忙看下

**Comment by binarywang** [comment]
另外，楼主请仔细重新描述下你的问题，看起来很乱，现在

**Comment by gclsoft** [comment]
就是redis的数据都没了。导致这个问题。


现在已经全部都重新授权了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Binary Wang <notifications@github.com>
发送时间: 2019年7月18日 12:54
收件人: Wechat-Group/WxJava <WxJava@noreply.github.com>
抄送: uuyimei <gclsoft@qq.com>, Author <author@noreply.github.com>
主题: 回复：[Wechat-Group/WxJava] redis服务器重启导致redis数据丢了, 现在关注服务号会报【错误信息】：{"errcode":61023,"errmsg":"refresh_token is invalid hint: (#1119)




另外，楼主请仔细重新描述下你的问题，看起来很乱，现在

**Comment by 007gzs** [comment]
之前做的时候我记得微信文档里写的只有在授权时推送 refresh_token，丢失的话只能重新授权。
不过刚去看了下好像新增了个 api_get_authorizer_list 接口可以获取所有授权的appid及对应的refresh_token

**Comment by gclsoft** [comment]
好东西啊，希望尽快集成进来。不然两个小时超时就要重新授权，风险很大


------------------ 原始邮件 ------------------
发件人: 007gzs <notifications@github.com>
发送时间: 2019年7月18日 13:07
收件人: Wechat-Group/WxJava <WxJava@noreply.github.com>
抄送: uuyimei <gclsoft@qq.com>, Author <author@noreply.github.com>
主题: 回复：[Wechat-Group/WxJava] redis服务器重启导致redis数据丢了, 现在关注服务号会报【错误信息】：{"errcode":61023,"errmsg":"refresh_token is invalid hint: (#1119)




之前做的时候我记得微信文档里写的只有在授权时推送 refresh_token，丢失的话只能重新授权。
不过刚去看了下好像新增了个 api_get_authorizer_list 接口可以获取所有授权的appid及对应的refresh_token

**Comment by 007gzs** [comment]
dev貌似有人把接口加进来了，只不过没写到redis里

**Comment by gclsoft** [comment]
谢谢, 以后遇到同样问题了, 怎么调用这个public WxOpenAuthorizerListResult getAuthorizerList(int begin, int len)?  
直接调用 getAuthorizerList(0,100);就可以是吧?

**Comment by binarywang** [comment]
3.4.8.B测试版本已修复相关代码，欢迎试用，如有新问题，请新开issue，谢谢各位
