### ISSUE TITLE
WxOpenMpServiceImpl类非public不方便使用

### ISSUE THREAD

**Issue by yuchonghua** [binarywang/WxJava#1122]
![image](https://user-images.githubusercontent.com/17898715/61447218-1c2c8380-a983-11e9-9744-c69ef6ae7521.png)

![image](https://user-images.githubusercontent.com/17898715/61447247-277faf00-a983-11e9-91ae-1f30307469d7.png)

**Comment by binarywang** [comment]
@007gzs 有空看一下吧

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/61448041-ba6d1900-a984-11e9-98e3-d3cdd9aa5762.png)
目前使用这个方法解决

**Comment by 007gzs** [comment]
判断这个的原因是什么？open的需要做什么特殊处理么？

**Comment by yuchonghua** [comment]
是的，举个例子，比如redirectURI这个回调地址，公众号是页面将跳转至 redirect_uri/?code=CODE&state=STATE。然而开放平台是redirect_uri?code=CODE&state=STATE&appid=APPID
，这个时候，你会发现多了一个appid，这个appid在公众号是没有带回来的，就想手动带过去，这样就可以识别出那个应用授权，

再直接点说，就是有那么一些用户，想用自己的域名在公众号中使用，然而，又想绑定直接的域名，并且提供了key，这个时候就没有使用open平台，但是他又是在我这开了一个应用

**Comment by yuchonghua** [comment]
因为open的代授权，只能解决比如使用自己的域名

**Comment by yuchonghua** [comment]
![image](https://user-images.githubusercontent.com/17898715/61450859-a1fffd00-a98a-11e9-8861-3f49169ed3c5.png)
![image](https://user-images.githubusercontent.com/17898715/61451003-f73c0e80-a98a-11e9-9c16-5b173442fcca.png)
![image](https://user-images.githubusercontent.com/17898715/61451040-0b800b80-a98b-11e9-9639-058c8ed4ccd4.png)

**Comment by 007gzs** [comment]
`WxOpenMpServiceImpl`没开放出来是怕有些用户不知道该new那个讲`WxOpenMpServiceImpl`和`WxMpServiceImpl`混淆，你这个问题可以自己创建一个类继承`WxMpServiceImpl`用来做公众号的，判断不是公众号的就走开放平台逻辑

**Comment by 007gzs** [comment]
因为这两个的获取方式不同，大部分使用场景下，调用者应该是明白自己是要用三方平台还是直接公众号的，你这种情况继承一下比判断classname好点

**Comment by yuchonghua** [comment]
不过我认为一个标准的开发者还是能很清晰自己是在使用WxOpenMpServiceImpl还是WxMpServiceImpl的，毕竟Open是一个明确的标识，而且WxOpenMpServiceImpl 是集成 WxMpServiceImpl的。
不给我还是先去继承WxMpServiceImpl来实现判断先，还是期待有些类能公布出来

**Comment by binarywang** [comment]
可以，这个改为public，不用再讨论了。

**Comment by binarywang** [comment]
3.4.8.B测试版本已添加public参数，欢迎试用

**Comment by yuchonghua** [comment]
感谢
