### ISSUE TITLE
需要实现微信第三平台设置小程序“扫普通链接二维码打开小程序”能力的五个接口

### ISSUE THREAD

**Issue by onforyou** [binarywang/WxJava#1123]
10、修改小程序线上代码的可见状态（仅供第三方代小程序调用）
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489140610_Uavc4&token=d2e0590a276589baff38f215bf0f6e8f0abfb063&lang=

14. 设置小程序“扫普通链接二维码打开小程序”能力
5个api

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489140610_Uavc4&token=d2e0590a276589baff38f215bf0f6e8f0abfb063&lang=

**Comment by binarywang** [comment]
建议每个单独开issue， 谢谢

**Comment by arbing** [comment]
修改小程序线上代码的可见状态 `WxOpenMaService.getCodeService().changeVisitStatus`

**Comment by binarywang** [comment]
确实，楼上提到的接口是有的，请楼主下次提问前再仔细阅读下源码，减少不必要的重复检查工作。

**Comment by binarywang** [comment]
3.5.10.B测试版本 已添加，欢迎试用
