### ISSUE TITLE
下载对账单，ALL与Success中没有订单总金额.与申请退款总金额

### ISSUE THREAD

**Issue by ln0491** [binarywang/WxJava#1125]
/*
     * 总交易单数,应结订单总金额,退款总金额,充值券退款总金额,手续费总金额,订单总金额,申请退款总金额 `2,`0.02,`0.0,`0.0,`0
     * 参考以上格式进行取值
     */
    String[] totalTempStr = objStr.replaceAll(",", " ").split("`");
    billResult.setTotalRecord(totalTempStr[1].trim());
    billResult.setTotalFee(totalTempStr[2].trim());
    billResult.setTotalRefundFee(totalTempStr[3].trim());
    billResult.setTotalCouponFee(totalTempStr[4].trim());
    billResult.setTotalPoundageFee(totalTempStr[5].trim());
    return billResult;
没有对以下账值
  /**
   * 订单总金额.
   */
  private String totalAmount;
 /**
   * 申请退款总金额.
   */
  private String totalAppliedRefundFee;

**Comment by binarywang** [comment]
你确定最后两个值是有的吗？我看最新官方文档里没有提到后面两个字段。

如果你看到的文档是有的，请提供文档地址

**Comment by ln0491** [comment]
> 你确定最后两个值是有的吗？我看最新官方文档里没有提到后面两个字段。
> 
> 如果你看到的文档是有的，请提供文档地址

文档上是没有那2个字段的，解析出来的，是有值的，
总交易单数,应结订单总金额,退款总金额,充值券退款总金额,手续费总金额,订单总金额,申请退款总金额
`5,`0.14,`0.00,`0.00,`0.00000,`0.14,`0.00

**Comment by binarywang** [comment]
关闭的有点早，还没发布版本呢
