### ISSUE TITLE
WxCpXmlMessage类的is_leader_in_dept和departmentId问题

### ISSUE THREAD

**Issue by roguemaycry** [binarywang/WxJava#1126]
# 简要描述
#1112 中的is_leader_in_dept 和 #927 departmentId为inter的问题
在WxCpXmlMessage这个类里还需要同步修复。
```
   /**
   * 部门Id.
   */
  @XStreamAlias("Id")
  private Integer id;
```
不过暂时可以用allFieldsMap里的值替代

### 模块版本情况

* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 3.4.7.b

**Comment by binarywang** [comment]
3.4.9.B测试版本已修复，欢迎试用
