### ISSUE TITLE
微信支付单品优惠添加CDATA标签会导致签名失败

### ISSUE THREAD

**Issue by xavskye** [binarywang/WxJava#1128]
### 简要描述

服务商模式下调用统一支付接口并使用【单品优惠】功能，如果在构建WxPayUnifiedOrderRequest对象时，在detail字段拼接CDATA标签保护json数据，则微信支付签名认证报错。原因是代码中生成签名的时候带了CDATA数据，但是传到微信后会将xml中的CDATA标签去掉，导致签名不一致；如果不加CDATA标签保护，则json中的特殊字符会被转义，导致单品优惠调用失效。请问如何解决？

### 模块版本情况

* WxJava 模块名: 微信支付
* WxJava 版本号: 3.4.0

**Comment by binarywang** [comment]
你确定是这问题吗？CDATA的问题微信不会这么弱智处理吧

**Comment by xavskye** [comment]
> 你确定是这问题吗？CDATA的问题微信不会这么弱智处理吧

关键问题是出在checkAndSign签名方法上，这个动作发生在生成xml报文之前，是对请求参数字符串进行加密获得签名的。由于相关从生成签名到生成报文都封装在createOrder方法中，只能在构建WxPayUnifiedOrderRequest对象时就加上CDATA标签，所以带上CDATA标签的签名会不一致。尝试了修改源码在detail字段上加上XStreamCDataConverter可以解决这个问题

**Comment by binarywang** [comment]
欢迎直接提PR

**Comment by binarywang** [comment]
> > 你确定是这问题吗？CDATA的问题微信不会这么弱智处理吧
> 
> 关键问题是出在checkAndSign签名方法上，这个动作发生在生成xml报文之前，是对请求参数字符串进行加密获得签名的。由于相关从生成签名到生成报文都封装在createOrder方法中，只能在构建WxPayUnifiedOrderRequest对象时就加上CDATA标签，所以带上CDATA标签的签名会不一致。尝试了修改源码在detail字段上加上XStreamCDataConverter可以解决这个问题

我本地测试过，detail字段内容加不加CDATA，均可以下单成功，就是说这并不是个问题。
你如果确认觉得有问题，欢迎提供PR代码和对应的测试用例。

**Comment by binarywang** [comment]
楼主呢，有下文没？

**Comment by binarywang** [comment]
楼主还在吗？如果没回应，我就认为这个问题不存在，毕竟没有其他人提这个问题，都用了很久了
