### ISSUE TITLE
扫码支付生成二维码的功能应否加入到WxMpPayService内？

### ISSUE THREAD

**Issue by afa007** [binarywang/WxJava#113]
商户后台系统根据微信支付规定格式生成二维码（规则见下文），展示给用户扫码。此功能应否加入到WxMpPayService内？

**Comment by binarywang** [comment]
你是说扫码支付？没问题，可以加入

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_1# 看此文档，发现接口基本都已经实现过了吧？

**Comment by binarywang** [comment]
我又仔细看了下你的问题，你是说生成二维码的功能吧？

**Comment by gaigeshen** [comment]
他说的是这个：
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_1

**Comment by afa007** [comment]
对的，生成微信支付二维码，https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_1
请权衡

**Comment by binarywang** [comment]
这个可以有

**Comment by binarywang** [comment]
@afa007 接口已添加，请查阅最新版本2.4.8.BETA，并帮忙测试下，有问题请随时提出~
