### ISSUE TITLE
公众号自动回复文本换行

### ISSUE THREAD

**Issue by getanid** [binarywang/WxJava#1131]
回复内容中加\n不生效，有没有大神遇到同样的问题，求解决方案，在线等！

**Comment by Ritian-Zhang** [comment]
用\r\n

**Comment by binarywang** [comment]
楼主解决了没，也没个回信了？

**Comment by binarywang** [comment]
先关闭，人失踪了貌似

**Comment by MrCxin** [comment]
版本3.3.8.B
发送客服消息的接口 换行是OK的(\n)
关注回复的时候有问题

**Comment by binarywang** [comment]
> 版本3.3.8.B
> 发送客服消息的接口 换行是OK的(\n)
> 关注回复的时候有问题

请不要在已关闭的问题里回复，谢谢合作。
另外，请先更新到最新版本再看是否有问题。

**Comment by MrCxin** [comment]
👌,我只是浏览到了 补充下
(回复的真及时, 老哥666)
