### ISSUE TITLE
微信服务号模版消息打开小程序指定路径无效

### ISSUE THREAD

**Issue by wjie2014** [binarywang/WxJava#1136]
微信服务号模版消息，配置打开小程序指定页面无效，总是打开首页。若传递参数也收不到参数。
小程序设置：
WxMpTemplateMessage.MiniProgram miniProgram = new WxMpTemplateMessage.MiniProgram(xcxAppId,"pages/index/index?id=109",true);
发送模版消息：
wxMpService.getTemplateMsgService().sendTemplateMsg(templateMessage);

### 模块版本情况
* WxJava 模块名:weixin-java-mp
* WxJava 版本号:3.4.0

### 期待结果 和 实际情况
网上有说将pagePath 改为path的，不知道起不起作用。

**Comment by FFFro** [comment]
老哥我也是这个问题，他这个代码里就是path，不知道怎么解决

**Comment by FFFro** [comment]
老哥我也是个这个问题不知道怎么解决

**Comment by binarywang** [comment]
MiniProgram 有个参数你们看到过没？仔细阅读下源码？

**Comment by FFFro** [comment]
> MiniProgram 有个参数你们看到过没？仔细阅读下源码？

更新了版本好了，没注意看微信文档

**Comment by wjie2014** [comment]
> MiniProgram 有个参数你们看到过没？仔细阅读下源码？
哦，usePath需要改为false。感谢
