### ISSUE TITLE
获取自定义菜单配置接口结果中缺少小程序相关属性

### ISSUE THREAD

**Issue by lcaminy** [binarywang/WxJava#1138]
公众号开发中自定义菜单不支持小程序的APPID 属性以及跳转小程序对应page 是配置，是否可以进行支持？

**Comment by binarywang** [comment]
你是怎么看出不支持的？这应该很早就支持的了

**Comment by lcaminy** [comment]
WxMpGetSelfMenuInfoResult 这个类的定义的内部类 获取不到 配置的小程序的APPID 和 跳转地址。WxMpSelfMenuButton 中缺少两个属性。
 "https://api.weixin.qq.com/cgi-bin/get_current_selfmenu_info";
这个接口发返回值中的 小程序相关配置没有属性来承载。

**Comment by binarywang** [comment]
> WxMpGetSelfMenuInfoResult 这个类的定义的内部类 获取不到 配置的小程序的APPID 和 跳转地址。WxMpSelfMenuButton 中缺少两个属性。
> "https://api.weixin.qq.com/cgi-bin/get_current_selfmenu_info";
> 这个接口发返回值中的 小程序相关配置没有属性来承载。

你说的只是这个接口的问题，并不是不支持啊，其它接口包括创建接口是支持的，而且我看该接口官方文档并没有你说的两个属性的说明，可否给出相关说明或者样例？

**Comment by binarywang** [comment]
你提到的接口地址是这个吧？https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1434698695

**Comment by lcaminy** [comment]
是的，他的文档中没有提到相关内容，但是他的接口返回是有小程序配置的相关信息的。我这边请求我的配置接口获得的数据如下：
`{"is_menu_open":1,"selfmenu_info":{"button":[{"name":"学院","sub_button":{"list":[{"type":"miniprogram","name":"成语答题王","url":"http:\/\/host","appid":"wxf4dc5b4e7b35dcd1","pagepath":"pages\/index\/index"},{"type":"miniprogram","name":"大师课程","url":"https:\/\/host\/course\/tutorial","appid":"wxfd6acd566482c6cb","pagepath":"pages\/tutorialDetail\/tutorialDetail"}]}},{"type":"miniprogram","name":"学科商城","url":"https:\/\/host\/-dAEuY","appid":"wx720f9f1301595564","pagepath":"pages\/home\/dashboard\/index"}]}}
{"selfmenu_info":{"button":[{"name":"当学院","sub_button":{"list":[{"type":"miniprogram","name":"成语答题王","url":"http://host"},{"type":"miniprogram","name":"大师课程","url":"https://host/course/tutorial"}]}},{"type":"miniprogram","name":"学科商城","url":"https://host/-dAEuY"}]},"is_menu_open":1}`

**Comment by lcaminy** [comment]
有没有个结论啊？

**Comment by binarywang** [comment]
注意看下上面的相关消息，代码已经提交了并发布了正式版

**Comment by lcaminy** [comment]
看到更新了。
