### ISSUE TITLE
wxMpService.oauth2getUserInfo 返回WxMpUser对象中 subscribe字段为空，实际已关注服务号

### ISSUE THREAD

**Issue by RyanOrElse** [binarywang/WxJava#1139]
wxMpService.oauth2getUserInfo 返回WxMpUser对象中 subscribe字段为空，实际已关注服务号

**Comment by binarywang** [comment]
看微信实际返回的报文了吗？

**Comment by laienliang** [comment]
这个接口为什么升级到4.4.0后就不见了呢？用哪个api代替？

**Comment by binarywang** [comment]
很早的版本就已经重构过了，你自己看下有个oauth相关的服务类，或者直接看wiki相关部分
