### ISSUE TITLE
企业号的支付，也是调用mp中的服务吗

### ISSUE THREAD

**Issue by caizhongkun** [binarywang/WxJava#114]
我看到mp中支付服务，有提到企业付款

**Comment by binarywang** [comment]
企业付款跟企业号的支付不是一回事。
企业号支付文档在这里，http://qydev.weixin.qq.com/wiki/index.php?title=%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98

**Comment by binarywang** [comment]
如果没有去其他问题，先关闭了，有问题请随时留言回复。
