### ISSUE TITLE
商品详情字段detail没有增加CDATA转换

### ISSUE THREAD

**Issue by liuhuagui** [binarywang/WxJava#1140]
- 使用模块及版本：weixin-java-pay-3.2.0
- 统一下单API中，要求单品优惠`detail`是必传字段，而且必须使用CDATA标签包裹，但是在
`WxPayUnifiedOrderRequest`中的`detail`字段并没有使用注解`@XStreamConverter(XStreamCDataConverter.class)`，并且在`BaseWxPayRequest#toXML()`方法中也没有看到使用`xstream.registerLocalConverter()`为该字段注册转换器。

不只是否是在其他位置解决了该问题。
- 起初的解决办法是在设置datail字段值的时候，先包裹CDATA，但是这样CDATA会参与签名，会导致服务器验签失败。
- 目前我使用的方式是使用匿名对象复写作者的实现类，如下：
```java
@Bean
	public WxPayServiceImpl wxPayService() {
		WxPayServiceImpl wxPayService = new WxPayServiceImpl() {
			@Override
			public WxPayUnifiedOrderResult unifiedOrder(WxPayUnifiedOrderRequest request) throws WxPayException {
				request.checkAndSign(this.getConfig());
				/**
				 * 避免因CDATA块参与签名，而服务端接收XMl时会忽略CDATA导致的验签失败
				 * 像这样，生成签名以后，再用CDATA包裹。
				 */
				if (!StringUtils.isBlank(request.getDetail()))
					request.setDetail(baby.auxiliary.util.out.StringUtils.toCDATA(request.getDetail()));
				String url = this.getPayBaseUrl() + "/pay/unifiedorder";
				String responseContent = this.post(url, request.toXML(), false);
				WxPayUnifiedOrderResult result = BaseWxPayResult.fromXML(responseContent,
						WxPayUnifiedOrderResult.class);
				result.checkResult(this, request.getSignType(), true);
				return result;
			}
		};
		wxPayService.setConfig(wxPayConfig());
		return wxPayService;
	}
```

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1128 楼主是否看过这个

**Comment by liuhuagui** [comment]
您好，不好意思之前没有看到那个，您的意思是说detail字段可以不用CDATA保护也可以吗，但是官方文档上`提交支付数据举例`以及在您的`WxPayUnifiedOrderRequest`对该字段的注释上都出现了CDATA的保护

**Comment by binarywang** [comment]
> 您好，不好意思之前没有看到那个，您的意思是说detail字段可以不用CDATA保护也可以吗，但是官方文档上`提交支付数据举例`以及在您的`WxPayUnifiedOrderRequest`对该字段的注释上都出现了CDATA的保护

我是想得到你的确认，可能我的验证方法有问题，咱们都不能光凭猜测想当然得结论吧，至少也得实际验证下。

**Comment by liuhuagui** [comment]
在不使用CDATA的情况下可以，但无法确认任何情况都可以，所以就按照您的注释和微信的文档，去主动增加了CDATA保护

**Comment by binarywang** [comment]
> 在不使用CDATA的情况下可以，但无法确认任何情况都可以，所以就按照您的注释和微信的文档，去主动增加了CDATA保护

没看懂你的意思，到底是应该加不加CDATA？
目前源码是没有加，是有问题的吗？然后你加了后有问题吗？

**Comment by liuhuagui** [comment]
直接加CDATA，服务端会验签失败，需要想办法把CDATA绕过签名

**Comment by binarywang** [comment]
你不是看了我在另一个issue里说的吗？加不加cdata，都没有报错，所以问题到底出在哪里？

**Comment by liuhuagui** [comment]
您在加Cdata的时候是通过什么方式，复写toxml加转换器？

**Comment by binarywang** [comment]
注解，就是那里面提到的那个

**Comment by liuhuagui** [comment]
所以还是要修改您的源码，

**Comment by binarywang** [comment]
你咋看不懂我说的意思呢，我一直说了，加不加都一样，没有报错

**Comment by Thomas0512** [comment]
我都没加CDATA,一样可以核销单品券，没影响的

**Comment by liuhuagui** [comment]
好吧，我可能太死板了，受文档的影响吧，谢谢您了！
