### ISSUE TITLE
有考虑把jedis的依赖抽象出来吗？

### ISSUE THREAD

**Issue by refeccd** [binarywang/WxJava#1141]
现有代码看了下，只直接写死jedis的，可是现在springboot默认的已经不是jedis了。
有考虑把jedis的依赖抽象出来吗？

**Comment by binarywang** [comment]
欢迎提供实现，提交PR

**Comment by binarywang** [comment]
jedis的实现仅供参考，如果你想支持其他类型的存储，可以自己实现，这并不是本sdk所关心并应该提供的内容。不过还是非常欢迎你提供对应的实现以便供他人参考。
