### ISSUE TITLE
公众号对接获取素材列表未支持返回图文消息的情况。

### ISSUE THREAD

**Issue by lcaminy** [binarywang/WxJava#1143]
在通过分页批量获取永久素材的接口中，拉取图文素材时，无法获得图文素材返回的详细信息，源码中没有针对图文消息的返回情况做合理的处理。
接口地址如下：
https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=ACCESS_TOKEN
图文素材返回的情况如下：
```
{
	"media_id": "6Jni8axMiEnGkVga8sRjU81EYnO8PIylejjLFtH4Koc",
	"content": {
		"news_item": [{
			"title": "开团|英国进口有声挂图，贴墙每天10分钟英语进步神速！国外教室都在用~",
			"author": "叮当",
			"digest": "原版书太厚不好翻?进口挂图每天贴墙10分钟~娃英文口语好到飞起！",
			"content": "content",
			"content_source_url": "",
			"thumb_media_id": "6Jni8axMiEnGkVga8sRjU-nTOpjya7QWD7jmVHVPqvo",
			"show_cover_pic": 0,
			"url": "http://mp.weixin.qq.com/s?__biz=MzAwNTQyMDE1MA==&mid=502134188&idx=1&sn=5232d5f34809f8e9406e4a3abc5fc3d9&chksm=0305b0b5347239a3340d3c4f118e5c0069e544ff43d84b4ef175d1859d29112c6c9f00f0eb00#rd",
			"thumb_url": "http://mmbiz.qpic.cn/mmbiz_jpg/RnwC8icYbddDkDgtSKhznes3zp86SubokEVSicsgJFvSubMAAqL2YZwo3jsDKDVbEIMts6V0KS1WT6SqTTadxiaOA/0?wx_fmt=jpeg",
			"need_open_comment": 1,
			"only_fans_can_comment": 0
		}],
		"create_time": 1552370183,
		"update_time": 1552477704
	},
	"update_time": 1552477704
}
```

### 模块版本情况

* WxJava 模块名: 
weixin-java-mp-
* WxJava 版本号:
3.4.0
### 期待结果 和 实际情况
可以返回 图文消息的详细结果，未针对图文消息的特殊情况做处理。

**Comment by binarywang** [comment]
你确定是这样的吗？请仔细指出问题所在，news_item的处理逻辑一直都有

**Comment by binarywang** [comment]
看过 `me.chanjar.weixin.mp.bean.material.WxMpMaterialNews` 类和 `me.chanjar.weixin.mp.util.json.WxMpMaterialNewsGsonAdapter#deserialize`方法没？
或者你运行过相关方法没？你是怎么得出结论说没特殊处理的？特殊情况是指什么？

**Comment by lcaminy** [comment]
你可以看下这个me.chanjar.weixin.mp.api.impl.WxMpMaterialServiceImpl 中的 materialFileBatchGet 这个方法的返回值结果类me.chanjar.weixin.mp.bean.material.WxMpMaterialFileBatchGetResult 其属性 items 的类型WxMaterialFileBatchGetNewsItem 确实是没有将接口查询返回的图文消息做接收处理。

**Comment by lcaminy** [comment]
没有看到是分方法处理的。sorry.
