### ISSUE TITLE
下载对账单接口，下载的文件可以不删除吗？

### ISSUE THREAD

**Issue by ln0491** [binarywang/WxJava#1145]
下载对账单接口，下载的文件可以不删除吗？
有时需要去查看下，现在的状态是下载完对账的gzip文件就删除了.找不到

**Comment by binarywang** [comment]
如果不删会导致大量垃圾文件存在系统内，你还得清理。另外还有另外一个下载原始对账单的方法，你可以使用

**Comment by ln0491** [comment]
好的，谢谢，那我用另一个下载downloadRawBill
