### ISSUE TITLE
企业微信发送markdown类型应用信息，格式不对

### ISSUE THREAD

**Issue by yinxuan1128** [binarywang/WxJava#1146]
企业微信发送markdown类型应用信息，格式不对，
接口源代码是这样的：
![source](https://user-images.githubusercontent.com/29925036/62587901-6f488500-b8f6-11e9-88bb-59e632887f4b.jpg)
官方要求的格式是这样的：
![weixin](https://user-images.githubusercontent.com/29925036/62587935-87200900-b8f6-11e9-9aa0-fc82a07ded2d.jpg)

### 模块版本情况

* WxJava 模块名: WxCp
* WxJava 版本号: 3.4.0

**Comment by binarywang** [comment]
请使用文字描述，不要发截图，另外关掉是怎么回事？

**Comment by yinxuan1128** [comment]
关掉是因为我发现是自己用法的问题，不是接口问题，谢谢了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Binary Wang <notifications@github.com>
发送时间: 2019年8月7日 10:42
收件人: Wechat-Group/WxJava <WxJava@noreply.github.com>
抄送: yinxuan1128 <389923141@qq.com>, State change <state_change@noreply.github.com>
主题: 回复：[Wechat-Group/WxJava] 企业微信发送markdown类型应用信息，格式不对 (#1146)




请使用文字描述，不要发截图，另外关掉是怎么回事？
