### ISSUE TITLE
拉取评论签名长度错误

### ISSUE THREAD

**Issue by Ziyear** [binarywang/WxJava#1148]
### 简要描述
拉取评论签名长度错误

### 模块版本情况
* WxJava 模块名: 【pay】
* WxJava 版本号: 【3.4.0】

### 详细描述
com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl#queryComment(com.github.binarywang.wxpay.bean.request.WxPayQueryCommentRequest)
方法的设置签名类型应该在生成签名之前，测试使用WxPayQueryCommentRequest并设置签名类型后通过

**Comment by binarywang** [comment]
出错不是因为你的用法有问题吗？

**Comment by binarywang** [comment]
请准确详细描述下你的问题

**Comment by Ziyear** [comment]
不是用法问题，是代码中这个设置签名类型应该在签名之前，不好意思不能上传图片，这个错误我刚提交了代码

**Comment by Ziyear** [comment]
```
  @Override
  public String queryComment(WxPayQueryCommentRequest request) throws WxPayException {
    request.checkAndSign(this.getConfig());
    request.setSignType(SignType.HMAC_SHA256);

    String url = this.getPayBaseUrl() + "/billcommentsp/batchquerycomment";
    String responseContent = this.post(url, request.toXML(), true);
    if (responseContent.startsWith("<")) {
      throw WxPayException.from(BaseWxPayResult.fromXML(responseContent, WxPayCommonResult.class));
    }

    return responseContent;
  }
```
request.setSignType(SignType.HMAC_SHA256);应该在上边

**Comment by binarywang** [comment]
你的意思是签名类型只能选择：HMAC_SHA256？

**Comment by binarywang** [comment]
好吧，明白你的意思了，早知道你就直接提交PR就完事了，也省的这么来回交流才明白。
