### ISSUE TITLE
HttpServletRequest会报空指针

### ISSUE THREAD

**Issue by workcheng** [binarywang/WxJava#115]
![15](https://cloud.githubusercontent.com/assets/9999969/21677350/ac764a9e-d374-11e6-9237-24a32ac07412.png)
不论使用的同步还是异步，这里获取到的HttpServletRequest经常会报空指针

**Comment by binarywang** [comment]
如QQ群里讨论的那样，我暂且认为你已经解决了，没猜错的话，还是你代码使用有问题，先关闭了，如有问题可以继续讨论

**Comment by workcheng** [comment]
嗯，我使用了spring的注解@PostConstruct去初始化，然后在web.xml配置了spring缓存HttpServletRequest的方法，在非controller层使用HttpServletRequest，就直接注入一下就可以了
