### ISSUE TITLE
用户批量删除接口异常

### ISSUE THREAD

**Issue by pkaq** [binarywang/WxJava#1152]
企业微信用户批量删除时未拼接前置URL导致调用报错

**Comment by binarywang** [comment]
请详细准确描述虾你的问题，谢谢

**Comment by pkaq** [comment]
【请求地址】: /cgi-bin/user/batchdelete?access_token=wVDoG6zM
服务运行异常:org.apache.http.client.ClientProtocolExceptio

在调用  wxCpUserService.delete(ids); 时
可以看到请求地址里 前置url丢了
@binarywang

**Comment by binarywang** [comment]
确实是有问题，之后版本修复一下

**Comment by binarywang** [comment]
3.5.1.B版本已修复，请验证
