### ISSUE TITLE
WxPayMpOrderResult 参数有误 

### ISSUE THREAD

**Issue by ytylalal** [binarywang/WxJava#1155]
JSAPI  生成订单参数封装有问题

		"appId":"xxx,
		"nonceStr":"1565675088985",
error-> 	"packageValue":"prepay_id=wx1313444891807652e772d8411913704800",
		"paySign":"xxx",
		"signType":"MD5",
		"timeStamp":"1565675088"

**Comment by ytylalal** [comment]
看了下源码和文档，是需要这样封装的   打扰了。不得不说微信的文档架构比阿里要差远了

**Comment by binarywang** [comment]
没看明白你的意思，既然你已经搞明白，就无所谓了。
