### ISSUE TITLE
Xml解析失败

### ISSUE THREAD

**Issue by yaoye6262** [binarywang/WxJava#1159]
WxCpTpXmlPackage wxCpTpXmlPackage = WxCpTpXmlPackage.fromXml(requestBody);

报错异常：com.thoughtworks.xstream.security.ForbiddenClassException

**Comment by binarywang** [comment]
请提供更为详细的信息，比如出错的详细信息，相关参数是怎么样的

**Comment by binarywang** [comment]
3.5.1.B版本已修复，请验证

**Comment by binarywang** [comment]
经过简单测试，没发现问题，楼主你如果想解决此问题，请尽快提供更详细的信息出来，好快速定位解决。
