### ISSUE TITLE
关于error日志问题

### ISSUE THREAD

**Issue by Ziyear** [binarywang/WxJava#1164]
建议：
多处接口抛出error日志，简易排查尽可能去掉error替换成直接抛出异常方式
模块及版本：
* WxJava 模块名: 微信支付
* WxJava 版本号:3.4.0
举例：
测试对账单下载，发现对账单下载失败是NO Bill Exist，直接打印err日志和堆栈，异常未抛出。还有一个细节就是失败参数映射缺少err_code,原因是返回参数是error_code，导致映射失败。
BaseWxPayServiceImpl类中还有不少error日志，建议替换掉这种处理方式，交给使用者处理。

**Comment by binarywang** [comment]
建议你直接提交PR代码来辅助展示下你的想法，感觉你的描述不够清晰

**Comment by Ziyear** [comment]
尴尬，在页面提交好不方便，下班再提吧
