### ISSUE TITLE
OCR识别缺少File文件识别

### ISSUE THREAD

**Issue by 94zhaoyueran** [binarywang/WxJava#1166]
看到3.3.0的时候公众号和小程序没有OCR识别，但是再3.5.0-MP的时候看懂了OCR识别，但是是参数是URL，缺少FileImage文件识别方法。

我写了个想FileImage识别的相关代码（@Test通过），如果这边没有时间的话我可以推过来。

**Comment by binarywang** [comment]
确实只实现了一部分，你如果有现成测试通过的代码，欢迎随时提交PR，不用问，我们肯定是欢迎的。

**Comment by binarywang** [comment]
#1002 关联issue

**Comment by goodcto** [comment]
还有 。WxMaService 里面也需要这个功能的。 官方提供的组件 不能获取到图片流

**Comment by binarywang** [comment]
> 还有 。WxMaService 里面也需要这个功能的。 官方提供的组件 不能获取到图片流

你可以考虑抽取公共核心逻辑到common模块里，然后小程序和公众号模块都可以用

**Comment by 94zhaoyueran** [comment]
呀，这个抽取到common的话没有什么核心逻辑呀，就是实现了一个RequestExecutor

**Comment by binarywang** [comment]
我说的就是解析响应数据的逻辑，如果你觉得实现起来有难度，先把代码提交上来吧，后期我再来做优化

**Comment by 94zhaoyueran** [comment]
解析响应数据的逻辑，是用的现在已经有的。
