### ISSUE TITLE
sub_mch_id为什么非要设置值

### ISSUE THREAD

**Issue by fengyts** [binarywang/WxJava#1170]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
sub_mch_id没有值的情况下，请不要设置默认值为mch_id

### 模块版本情况
* WxJava 模块名: wx-java-pay-spring-boot-starter
* WxJava 版本号: 3.5.0

### 详细描述
支付报错，错误内容：

结果业务代码异常，返回结果：{return_msg=普通商户不允许传sub_mch_id, return_code=FAIL},
返回代码：FAIL，返回信息：普通商户不允许传sub_mch_id

代码如下：
WxPayUnifiedOrderRequest prepayInfo = WxPayUnifiedOrderRequest.newBuilder()
                .openid(model.getOpenid())
                .outTradeNo(model.getOutTradeNo())
                .totalFee(Integer.valueOf(model.getTotalFee()))
                .body(model.getBody())
                .tradeType(model.getTradeType())
                .spbillCreateIp(model.getSpbillCreateIp())
                .notifyUrl(model.getCallBackUrl())
                .build();

        ReturnModel returnModel = new ReturnModel();
        try {
            prepayInfo.setSubMchId(null);
            Map<String, String> payInfo = wxPayService.createOrder(prepayInfo);

我上面已经给强制设置为null：prepayInfo.setSubMchId(null);
但是在请求参数中还是有值，怎么解？
还是报这个错误，坑啊。
    
### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
把你的配置文件里对应项去掉

**Comment by fengyts** [comment]
好的，问题已解决。非常感谢
