### ISSUE TITLE
WxMaErrorMsgEnum错误码缺失

### ISSUE THREAD

**Issue by barryhippo** [binarywang/WxJava#1176]
### 简要描述
在使用微信小程序接口时发现WxMaErrorMsgEnum相关错误信息比较少缺失了不少常用的错误信息

### 官方文档地址
auth.code2Session接口：
-1 | 系统繁忙，此时请开发者稍候再试
40029 | code 无效

auth.getPaidUnionId接口
89002 | 没有绑定开放平台帐号 
89300 | 订单无效

updatableMessage.createActivityId接口
42001 | access_token 过期 

updatableMessage.setUpdatableMsg接口
44002 | post 数据为空 
47001 | post 数据中参数缺失 
47501 | 参数 activity_id 错误 
47502 | 参数 target_state 错误 
47503 | 参数 version_type 错误 
47504 | activity_id 过期

列举了部分，稍微有点多需要重新整理一下

**Comment by binarywang** [comment]
准备暂时补充你所提到的部分，其他如果发现，再加不迟

**Comment by binarywang** [comment]
3.5.3.B 版本 已添加，欢迎试用

**Comment by barryhippo** [comment]
OK，谢谢
