### ISSUE TITLE
qyapi.weixin.qq.com域名能统一做成可配置的吗？

### ISSUE THREAD

**Issue by langzhigang** [binarywang/WxJava#1178]
比如 qyapi.weixin.qq.com，open.weixin.qq.com 这两个基础域名，源码中都是写死在了各个方法中。
我现在有一个场景，当前机器不能直接访问这个域名，需要走一个正向代理，加一个端口（qyapi.weixin.qq.com:18888），然后由另外一台机器代理出去。
在没有配置的情况下，我表示很难操作。
只能修改源码自己打包？

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/1065  
https://github.com/Wechat-Group/WxJava/issues/1039
楼主是否看过最近版本修改记录？

**Comment by langzhigang** [comment]
> #1065
> #1039
> 楼主是否看过最近版本修改记录？

之前没注意，现在看到了。谢谢楼主。

**Comment by binarywang** [comment]
楼主不是你吗？😵

**Comment by langzhigang** [comment]
> 楼主不是你吗？😵

哈哈，感谢作者。这个点作者可以考虑加到常见问题的文档里面。

**Comment by langzhigang** [comment]
> > 楼主不是你吗？😵
> 
> 哈哈，感谢作者。这个点作者可以考虑加到常见问题的文档里面。

还有一个点，我从3.4.0升级到 3.5.0 发现有的类都被删除了。作者可以考虑 废弃的 直接过期吧，然后引导人家用新的类。这样会有好点=_=

**Comment by binarywang** [comment]
以前这么做过一段时间，但会导致很多垃圾代码，考虑到使用升级使用新版本的老用户不多，而使用新版本的新用户会相对比较多，为避免产生不必要的困惑，后来就直接进行重构，而且这种重构随着版本的演进会越来越少。而需要升级使用新版本的老用户，只要仔细阅读版本日志就很快完成升级，不会产生很多问题。
