### ISSUE TITLE
微信支付部分使用说明与SDK的实现不太一致

### ISSUE THREAD

**Issue by Starix610** [binarywang/WxJava#1179]
微信支付的使用说明与提供的示例中说：“异步回调接口代码内部会自动校验结果签名和业务代码，您需要做的就是拿到结果之后直接处理“。但是源码中WxPayService.parseOrderNotifyResult()方法只进行了签名校验，并没有对业务结果代码成功与否进行校验，result.checkResult()方法最后一个参数传的是false。
这样是不是需要我们自己进行业务结果代码成功与否进行校验后再处理后续的业务？

**Comment by Tobu-R** [comment]
下面是SDK的实现代码：
`@Override
  public WxPayOrderNotifyResult parseOrderNotifyResult(String xmlData) throws WxPayException {
    try {
      log.debug("微信支付异步通知请求参数：{}", xmlData);
      WxPayOrderNotifyResult result = WxPayOrderNotifyResult.fromXML(xmlData);
      log.debug("微信支付异步通知请求解析后的对象：{}", result);
      **result.checkResult(this, this.getConfig().getSignType(), false);**
      return result;
    } catch (WxPayException e) {
      log.error(e.getMessage(), e);
      throw e;
    } catch (Exception e) {
      log.error(e.getMessage(), e);
      throw new WxPayException("发生异常，" + e.getMessage(), e);
    }
  }`

**Comment by Starix610** [comment]
**文档第5条:** https://github.com/Wechat-Group/WxJava/wiki/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98
**SDK中的WxPayService实现代码:**`result.checkResult(this, this.getConfig().getSignType(), false);`，最后一个参数为fasle？

**Comment by binarywang** [comment]
这里不检查，是为了让你自己判断，然后实现自己的业务逻辑，你怎么渴望SDK帮你做这方面的判断？

**Comment by Starix610** [comment]
> 这里不检查，是为了让你自己判断，然后实现自己的业务逻辑，你怎么渴望SDK帮你做这方面的判断？

你说得对，的确应该自己判断。但是那篇使用说明文档里面说拿到回调之后直接处理业务逻辑，给的示例代码也是直接处理，如果不稍微看一下SDK里面的代码，可能会出问题。所以那篇文档是不是应该稍微更正一下或者给个提醒呀。。。

**Comment by binarywang** [comment]
实例仅供参考，你如果觉得那里的文档描述理解起来有问题，可以自己进行补充完善，随时欢迎。
