### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by w22296437978** [binarywang/WxJava#1182]
添加`wx-java-mp-spring-boot-starter`启动后报错,找不到`redis.clients.jedis.JedisPool`
我的项目里依赖里包含了`spring-boot-starter-data-redis`，并且我没有配置使用mp使用redis

**Comment by binarywang** [comment]
你需要自己添加jedis的依赖

**Comment by binarywang** [comment]
可能这是个问题，需要修复下

**Comment by binarywang** [comment]
@lkqm 如果有时间帮忙看下吧

**Comment by lkqm** [comment]
@binarywang 一会我修复下

**Comment by lkqm** [comment]
问题是由jedis依赖丢失, 已经修复并提PR, 等待合并, 稍后引入新版本依赖, 或者可以考虑在pom.xml中添加依赖:
```xml
<dependency>
    <groupId>redis.clients</groupId>
    <artifactId>jedis</artifactId>
    <version>3.1.0</version>
</dependency>
```
