### ISSUE TITLE
是否考虑增加 微信服务商 小微商户相关API

### ISSUE THREAD

**Issue by BoolTrue** [binarywang/WxJava#1187]
### 简要描述
小微商户进件相关API 自己开发起来非常麻烦，容易出错（包括图片上传）。但作为服务商模式的微信支付商户 对这个接口有很大的需求，请求考虑增加此接口，谢谢。

### 官方文档地址
小微商户 - 申请入驻API
https://pay.weixin.qq.com/wiki/doc/api/xiaowei.php?chapter=19_2

**Comment by binarywang** [comment]
期待有实现过此接口的开发者提交PR

**Comment by wangjia2016** [comment]
![image](https://user-images.githubusercontent.com/16084076/80953096-71ac2100-8e2d-11ea-9b1b-16238cd27a20.png)
小微商户是不是测试中的功能？官方文档中貌似没找到小微商户

**Comment by zlab** [comment]
无限期下线了

**Comment by binarywang** [comment]
> 无限期下线了

官方文档有说明？

**Comment by zlab** [comment]
![image](https://user-images.githubusercontent.com/2288630/82819672-56d04800-9ed3-11ea-830f-3614ba41b573.png)
https://developers.weixin.qq.com/community/develop/doc/000464d0510ba0bbf2a96742d5b000?highLine=%25E5%25B0%258F%25E5%25BE%25AE%25E5%2595%2586%25E6%2588%25B7%25E4%25B8%258B%25E7%25BA%25BF

https://developers.weixin.qq.com/community/develop/doc/000428aa240c50d60d5a2750f5fc00?highLine=%25E5%25B0%258F%25E5%25BE%25AE%25E5%2595%2586%25E6%2588%25B7%25E4%25B8%258B%25E7%25BA%25BF

**Comment by binarywang** [comment]
看样子是被“特约商户进件”替代了，大家不要考虑这个了。
