### ISSUE TITLE
代码优化，异常处理不彻底，代码冗余

### ISSUE THREAD

**Issue by silloy** [binarywang/WxJava#1189]
![image](https://user-images.githubusercontent.com/12909107/64148276-80cd7000-ce55-11e9-8178-2f4b2411ee1f.png)

当errorCode != 0 时，出现的异常已经被post或者get方法抛出，意味着当errorcode != 0 时， 网络请求层已经处理了异常并抛出wxerrorException，就不会走下面的逻辑，下面的判断和异常处理也就是没有意义的吧？同时也就是说 WxError.fromJson(String json, WxType type)中的type一直为null，即抛出的异常中的errorMsg永远为空

![image](https://user-images.githubusercontent.com/12909107/64148287-8925ab00-ce55-11e9-911f-174e32bfdafd.png)

异常error并没有得到正常处理，或者说没有处理彻底，调用方拿到仍然是一串英文字符串

**Comment by binarywang** [comment]
准备优化掉

**Comment by binarywang** [comment]
3.5.4.B版本已优化
