### ISSUE TITLE
循环调用，连接池溢出

### ISSUE THREAD

**Issue by a419506442** [binarywang/WxJava#1193]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
 me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751748976Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751781312Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751850984Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751886495Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751923767Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751966629Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.751999367Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752033614Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752066382Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752098822Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.75212924Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752164721Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.75219538Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752227061Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752260127Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752292129Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752322848Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752359191Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752390688Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752421819Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752559836Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752612886Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752648059Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752680088Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.752751528Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753074331Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753132113Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753166355Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753197986Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.75323218Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753281168Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753312662Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753351578Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753385318Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753417186Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753446201Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753591764Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753628908Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753659824Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753693427Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753724508Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.75375652Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753789618Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.execute(BaseWxMpServiceImpl.java:283)\r\n","stream":"stdout","time":"2019-09-05T05:11:08.753822168Z"}
{"log":"\u0009at me.chanjar.weixin.mp.api.impl.BaseWxMpServiceImpl.executeInternal(BaseWxMpServiceImpl.java:338)\r\n","

### 模块版本情况
* WxJava 模块名:  
* WxJava 版本号: 3.4.8.B

### 详细描述
  会出现循环调用，导致connection pool最终溢出

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
不是堆栈溢出吗，能看到微信的返回内容吗？

**Comment by binarywang** [comment]
问题不明确，且无下文，关闭
