### ISSUE TITLE
weixin-java-miniapp使用WxMaRedisConfigImpl存储token时,报空指针

### ISSUE THREAD

**Issue by jsnjfz** [binarywang/WxJava#1198]
### 简要描述
weixin-java-miniapp使用WxMaRedisConfigImpl存储token时，启动后第一次调用WxMaServiceImpl的getAccessToken报空指针

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:3.5.0

### 详细描述
使用WxMaRedisConfigImpl存储redis时，如果是启动后第一次调用WxMaServiceImpl的getAccessToken方法时，会报空指针，我看WxMpInRedisConfigStorage是用redis的ttl过期时间来处理的，即使是没有设置也不会返回空指针，会返回int值。WxMaRedisConfigImpl是单独设置了一个key,value，猜想第一次的时候没有设置expire，所以会报空指针。(accessToken值已写入redis)
另外顺带问下WxMaRedisConfigImpl支持多个小程序么，因为看redis中存储的结构也和WxMpInRedisConfigStorage不同

### 日志
https://paste.ubuntu.com/p/kMR848v6WQ/

**Comment by binarywang** [comment]
`WxMaRedisConfigImpl` 仅供参考，默认应该是只支持一个的，你自己扩展下即可支持多个

**Comment by binarywang** [comment]
#1100 @winter4666 有空帮忙看下吧，这个类应该是你实现的。

**Comment by winter4666** [comment]
看你贴的异常信息：
```
java.lang.NullPointerException: null
	at cn.binarywang.wx.miniapp.config.impl.WxMaRedisConfigImpl.getExpireFromRedis(WxMaRedisConfigImpl.java:89) ~[weixin-java-miniapp-3.5.0.jar!/:na]
```
是`WxMaRedisConfigImpl`类的第89行报了错误，而这个类的第89行代码是：
```java
try (Jedis jedis = jedisPool.getResource()) {
```
初步判定是你使用`WxMaRedisConfigImpl`类的时候没有使用`setJedisPool`设置`jedisPool`，可以检查下你使用该类的代码，或者把代码贴上来看看。

**Comment by jsnjfz** [comment]
我已经加了断点远程调试了，就是在getExpireFromRedis报错的，这个时候redis里面并没有expire的值，setJedisPool我肯定是set的，不然运行都运行不起来
代码：
JedisPool 做成一个bean，然后

    @Autowired
    private JedisPool jedisPool;

    @Bean
    public WxMaConfig wxMaConfig() {
        WxMaRedisConfigImpl config = new WxMaRedisConfigImpl();
        config.setJedisPool(jedisPool);
        config.setAppid(wxMaProperties.getConfigs().get(3).getAppid());
        config.setSecret(wxMaProperties.getConfigs().get(3).getSecret());
        config.setToken(wxMaProperties.getConfigs().get(3).getToken());
        config.setAesKey(wxMaProperties.getConfigs().get(3).getAesKey());
        config.setMsgDataFormat(wxMaProperties.getConfigs().get(3).getMsgDataFormat());
        return config;
    }

**Comment by winter4666** [comment]
下面是`getExpireFromRedis`方法的代码：
```java
  private long getExpireFromRedis(String key) {
    try (Jedis jedis = jedisPool.getResource()) {
      String expire = jedis.hget(getRedisKey(key), HASH_EXPIRE_FIELD);
      return expire == null ? 0 : Long.parseLong(expire);
    }
  }
```
可以看到这一行`String expire = jedis.hget(getRedisKey(key), HASH_EXPIRE_FIELD);`是从redis里面取`expire`值，而即使redis里面没有存这个`expire`（也就是第一次取的时候），实际上这一行代码也不会报错，而是会返回一个空值。
然后紧接着下一行代码`return expire == null ? 0 : Long.parseLong(expire);`这里是判了空的，假如`expire`为`null`，这个方法会以`0`返回，其实也不会有异常。

**Comment by jsnjfz** [comment]
看了你的代码，确实如你说的，我再断点看下
