### ISSUE TITLE
获取用户列表的同时，返回用户信息

### ISSUE THREAD

**Issue by wangjia2016** [binarywang/WxJava#12]
userList()方法，目前只是返回了一些openid的信息，这样如果后台有需要展示这些用户信息的话，得

`WxMpUserList  list = wxMpService.userList(null);

```
    List<String> openIdList = list.getOpenIds();

    List<WxMpUser> listUser = new ArrayList<WxMpUser>();
    WxMpUser user ;
    if(openIdList!=null&&openIdList.size()>0){
        for(String openId:openIdList){  
            user = wxMpService.userInfo(openId, "zh_CN");
            listUser.add(user);
        }
    }`
```

这样了，略微麻烦，希望新增一个接口，直接返回用户列表(带用户信息)并支持分页获取。

**Comment by kareanyi** [comment]
主要是微信官方提供的接口就是直接给的openId的列表呢

**Comment by binarywang** [comment]
可以考虑添加接口，方便客户端一次性得到想要的用户信息

**Comment by xrian** [comment]
感觉没必要啊,各自按需实现就行,因为微信返回的openid是一万个啊,循环一万次......很耗时间的
再说有的人不一定获取一万个用户的,只是获取100,1000呢

**Comment by binarywang** [comment]
@xrian 你说的问题我也考虑过，但是确实有需要获取多个用户信息的场景，比如同步用户数据时批量获取用户信息的时候保存到本地数据库，虽然这个只是个小概率场景，不推荐多次调用，用户多的时候确实很耗时

**Comment by binarywang** [comment]
而且每次获取的用户数量也是可以指定的，比如可以指定每次获取多少用户

**Comment by xrian** [comment]
@binarywang  我觉得这样实现会比较好些,写一个方法,传入list(或者数组或者list<Map>的形式),list里面是openid,这方法就是遍历list,然后根据openid获取用户信息,这样就不用考虑指定获取多少用户信息的情况了.
方法分同步和异步,如果数据少就可以用同步的方法,数据多可以用异步的
这样是否会好些呢

**Comment by wangjia2016** [comment]
@xrian 可以分页读取的，这种数据一般改动很少，也不是经常同步的，

**Comment by binarywang** [comment]
@wangjia2016  你可否帮忙实现一下？有人需要就用，不需要的话放那里也无妨

**Comment by wangjia2016** [comment]
@binarywang 可以，等我整理完了提交上来。

**Comment by binarywang** [comment]
@wangjia2016 最近有计划实现不？

**Comment by binarywang** [comment]
需求不强烈，暂时不实现
