### ISSUE TITLE
用户上下文问题

### ISSUE THREAD

**Issue by mr-m0nst3r** [binarywang/WxJava#1200]
### 简要描述
有个功能需求，就是不用小程序和其他网站，如何实现用户输入上下文的管理？

类似于电话银行，用户输入消息，返回列表供用户选择选项，服务器再根据用户的输入的列表序号确定用户选择的内容。

新手，多谢！

**Comment by binarywang** [comment]
你需要了解session的概念

**Comment by mr-m0nst3r** [comment]
@binarywang 
大佬好，我正在学习Java，问题有些蠢，看到wiki里面有关于session的内容，还有sessiontest，正在学习。谢谢
