### ISSUE TITLE
第三方平台代小程序登录报{"errcode":40029,"errmsg":"invalid code, hints: [ req_id: WeFeFXXBe-VCQ9va ]"}问题

### ISSUE THREAD

**Issue by Tim1999** [binarywang/WxJava#1201]
请求url中的code不是用code参数，使用的是js_code

官方文档：
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1492585163_FtTNA&token=&lang=zh_CN

**Comment by binarywang** [comment]
请详细准确描述问题，比如你使用的什么代码

**Comment by Tim1999** [comment]
> 请详细准确描述问题，比如你使用的什么代码

这是源码中的请求URL
![B4C3FCCC-CE8A-4e02-9337-505B63323262](https://user-images.githubusercontent.com/31530922/64748707-a4737300-d545-11e9-993c-dea1ea67d993.png)

这是官方文档中的URl
![8CB4212E-3090-4604-9DB9-630E99FB87E6](https://user-images.githubusercontent.com/31530922/64748722-b228f880-d545-11e9-9a99-6ba117b14170.png)

**Comment by binarywang** [comment]
描述不清楚，暂时关闭
