### ISSUE TITLE
公众号消息路由有关问题

### ISSUE THREAD

**Issue by xushuangshuang1234** [binarywang/WxJava#1204]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__
前提：用户已经关注该公众号，
步骤：
 1. 获取微信公众号二维码，
 2. app扫描二维码，进入聊天窗口后，后台有收到微信服务器发来的消息，此消息事件类型是SCAN，但此消息并没有走任何消息路由。
3. 接收到请求消息，内容：{
  "toUser": "gh_51f707b81597",
  "fromUser": "okrixxNjNNonE-eHGUaKTLpVg9a4",
  "createTime": 1568600174,
  "msgType": "event",
  "event": "SCAN",
  "eventKey": "123",
  "ticket": "gQG97zwAAAAAAAAAAS5odHRwOi8vd2VpeGluLnFxLmNvbS9xLzAyUmZEdUVIaVVlTjQxdk9NLU50Y3cAAgQ_8H5dAwS0AAAA"
}

### 模块版本情况
* WxJava 模块名:  weixin-java-mp
* WxJava 版本号: 2.9.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by xushuangshuang1234** [comment]
已经解决了，是我自己代码的问题！谢谢~

**Comment by zengyao0831** [comment]
请问一下您是怎么解决的！谢谢

**Comment by skillhome** [comment]
请问一下，遇到同样问题是怎么解决的？其它所有事件都是正常的，已关注的情况下，扫码事件未收到？
