### ISSUE TITLE
XStreamInitializer getInstance 高并发情况下性能问题

### ISSUE THREAD

**Issue by saber233** [binarywang/WxJava#1205]
### 简要描述
在压测过程中 对比高并发情况下trace getInstance() 发现实例化XStream 耗时比较高
这块有准备在上层做层缓存？

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.5.0

### 详细描述
普通
![image](https://user-images.githubusercontent.com/11989805/64933949-29c69280-d87a-11e9-8381-7388af4de103.png)
![image](https://user-images.githubusercontent.com/11989805/64933965-4793f780-d87a-11e9-8fcb-1b234e0fc37c.png)

并发30 
![image](https://user-images.githubusercontent.com/11989805/64933955-32b76400-d87a-11e9-9d72-5c076907c533.png)
![image](https://user-images.githubusercontent.com/11989805/64933981-609ca880-d87a-11e9-885e-7cc994ccec54.png)

**Comment by binarywang** [comment]
可以考虑，也欢迎楼主提供可行代码并提交PR

**Comment by binarywang** [comment]
#1390 已优化，请使用最新版本即可
