### ISSUE TITLE
微信第三方平台管理的小程序越来越多会不会出现性能问题？

### ISSUE THREAD

**Issue by Tim1999** [binarywang/WxJava#1206]
每一个授权给第三方的小程序，就会在WX_OPEN_MP_SERVICE_MAP中new一个新的对象，会不会因为所管理的第三方小程序越来越多而导致内存或性能问题？

用MAP缓存起来是可以减低重新创建对象和摧毁对象的开销，但会不会因为小程序越来越多 ，比如两三千个而导致其他问题？

源码如下：
![DC8D3E33-5A51-4386-992E-C48FBEAD0247](https://user-images.githubusercontent.com/31530922/64954293-bc395700-d8b7-11e9-8686-4b642d2fbeac.png)

**Comment by Tim1999** [comment]
?

**Comment by binarywang** [comment]
@007gzs  有空可以帮忙解答下

**Comment by chuntaojun** [comment]
或许可以考虑使用guava cache的过期缓存来做
