### ISSUE TITLE
企业微信通讯录回调 成员回调 （新增成员和编辑成员）xml解析错误

### ISSUE THREAD

**Issue by Pwenlee** [binarywang/WxJava#1208]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__
企业微信通讯录回调 成员回调 （新增成员和编辑成员）xml解析错误
### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:3.5.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
<xml><ToUserName><![CDATA[wwc0235021f5ca1a69]]></ToUserName><FromUserName><![CDATA[sys]]></FromUserName><CreateTime>1568700294</CreateTime><MsgType><![CDATA[event]]></MsgType><Event><![CDATA[change_contact]]></Event><ChangeType><![CDATA[update_user]]></ChangeType><UserID><![CDATA[LiPan]]></UserID><Department><![CDATA[6,1]]></Department><IsLeader>0</IsLeader><IsLeaderInDept><![CDATA[0,0]]></IsLeaderInDept></xml>
2019-09-17 14:04:56.368 [http-nio-8181-exec-2] [ERROR]  com.xsm.industry.wechat.init.WechatInit-77 : 获取企业微信回调数据失败Explicit selected converter cannot handle type
---- Debugging information ----
message             : Explicit selected converter cannot handle type
item-type           : [Ljava.lang.Long;
converter-type      : com.thoughtworks.xstream.converters.SingleValueConverterWrapper
class               : me.chanjar.weixin.cp.bean.WxCpXmlMessage
required-type       : me.chanjar.weixin.cp.bean.WxCpXmlMessage
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
line number         : 1
version             : 1.4.11
-------------------------------
企业微信回调的xml  Department节点解析成Long[]报错
### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__
https://paste.ubuntu.com/p/sRzRvZ9PpJ/

**Comment by binarywang** [comment]
#1169 已修复
