### ISSUE TITLE
客服信息接口 

### ISSUE THREAD

**Issue by fangzhilong** [binarywang/WxJava#121]
有提供获取48小时没有跟公众号产生交互的人的openId的接口吗

**Comment by xuyg** [comment]
谁有权限把他移除了。自己不会看文档和源码么？先看微信官方文档然看SDK源码，别老打扰大家，没找到就没有。一直邮件弹窗真TM 想爆粗口

**Comment by binarywang** [comment]
@XuYg 请先息怒，没人有什么权限可以这么做，这里都是开放的，谁都可以说话，不过你可以单独unsubscribe这个对话。你说的很有道理，楼主@fangzhilong确实得需要自己多用心看相关文档了。据我所知，目前没有这种接口。
