### ISSUE TITLE
集成微信云开发接口

### ISSUE THREAD

**Issue by jiangyang118** [binarywang/WxJava#1214]
### 简要描述
小程序云开发提供http api，请问有没有计划集成这些接口？谢谢

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-http-api/functions/invokeCloudFunction.html

**Comment by binarywang** [comment]
可以考虑，请提供优先级比较高的几个接口的页面，先实现下看看。

**Comment by outersky** [comment]
我写了个kotlin语言版本的供参考  [wx-cloud-kt](https://github.com/outersky/wx-cloud-kt) 
使用demo： [wx-cloud-kt-demo](https://github.com/outersky/wx-cloud-kt-demo)

**Comment by binarywang** [comment]
这个其实这两天一直在做，基本调试完毕

**Comment by binarywang** [comment]
3.6.8.B版本已实现，欢迎使用

**Comment by hanwei59** [comment]
> 3.6.8.B版本已实现，欢迎使用

这里还有一些接口，开通云开发、云环境、云函数相关的：https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/cloudbase/cloudbase.html

**Comment by binarywang** [comment]
那就是三方平台的了，可以单独提个issue

> > 3.6.8.B版本已实现，欢迎使用
> 
> 这里还有一些接口，开通云开发、云环境、云函数相关的：https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/cloudbase/cloudbase.html
