### ISSUE TITLE
微信支付相关接口增加分账支持的参数

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#1216]
文档：https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=24_3&index=3
开发步骤
1、服务商代子商户发起添加分账接收方请求（添加分账接收方API）

2、在统一下单API、付款码支付API、委托扣款API中上传新增参数profit_sharing，请求支付

3、支付完成后，调用请求分账接口，完成分账

字段名 | 变量名 | 必填 | 类型 | 示例值 | 描述
-- | -- | -- | -- | -- | --
是否指定服务商分账 | profit_sharing | 否 | String(16) | Y | Y-是，需要分账N-否，不分账字母要求大写，不传默认不分账

说明：实现分账只是在普通支付下单接口中新增了一个分账参数profit_sharing，其他与普通支付方式完全相同。目前支持付款码支付、JSAPI支付、Native支付、APP支付、小程序支付、H5支付、委托代扣。

**Comment by ciphermagic** [comment]
[请求分账接口](https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_1) 什么时候有呢

**Comment by binarywang** [comment]
分账相关问题统一参考 #1010
