### ISSUE TITLE
this.switchover(appId)导致ThreadLocal递增从而引起服务死机 (版本3.4.0)

### ISSUE THREAD

**Issue by zhangam** [binarywang/WxJava#1218]
这个方法里的ThreadLocal只有设置方法没有移除方法(暂时没找到),每次接受微信服务器发来的请求都会调用这个方法切换appid，也就是一直在新增TreadLocal,但是没找到你移除的地方，线上服务器一天死两次，我怀疑是这个地方。希望有人可以解答下
<img width="898" alt="WX20190922-011208@2x" src="https://user-images.githubusercontent.com/3468711/65376728-1716e800-dcd6-11e9-8cc7-f39b16b70f99.png">
<img width="700" alt="WX20190922-011200@2x" src="https://user-images.githubusercontent.com/3468711/65376729-17af7e80-dcd6-11e9-840a-393c5072cfeb.png">

**Comment by binarywang** [comment]
你确定是这个问题吗？

**Comment by zhangam** [comment]
仔细查了不是，但你们这个不释放也不太好吧

发自我的iPhone

**Comment by binarywang** [comment]
你建议怎么处理？目前看来，问题不大。

**Comment by zhangam** [comment]
只是存appid的话占内存不多，但不重启的话内存是一点点的在增加，多少是个隐患。看看能不能用aop处理下(愚见)

发自我的iPhone

**Comment by binarywang** [comment]
@chuntaojun 请问你有什么想法没？

**Comment by chuntaojun** [comment]
我明天看下

发自我的iPhone

在 2019年10月13日，23:46，Binary Wang <notifications@github.com> 写道：

﻿

@chuntaojun<https://github.com/chuntaojun> 请问你有什么想法没？

**Comment by binarywang** [comment]
> 我明天看下 

@chuntaojun 等待你的回复

**Comment by chuntaojun** [comment]
> > 我明天看下
> 
> @chuntaojun 等待你的回复

调用ThreadLocal.remove，及时移除即可，代码写好了，过几天pr下

**Comment by binarywang** [comment]
暂时关闭

**Comment by nadirvishun** [comment]
@zhangam 增加remove后有解决吗？确定是`ThreadLocal`导致的？感觉不太可能是，因为：
- 如果是单个线程调用，那当这个线程结束`ThreadLocal`会自动回收。
- 如果是用线程池，虽然第一个线程不回收，但是一旦复用线程调用`get`、`set`即便是不调用`remove`也会对旧的进行回收，所以最多存在一个旧的数据，而不是会累计引起oom。

-------
又查了下资料，`get`、`set`虽然会进行回收，但不一定100%回收，所以手动调用`remove`最保险。参考：[老周聊架构](https://mp.weixin.qq.com/s/fEpsnVXE8RF8aCzaXoDVwQ)
