### ISSUE TITLE
小程序内容安全接口新增了对语音的支持，希望咱们这个框架能能支持

### ISSUE THREAD

**Issue by juetianzuimeng** [binarywang/WxJava#1219]
security.mediaCheckAsync

语音风险识别：社交类用户发表的语音内容检测
具体的微信文档为：
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/sec-check/security.mediaCheckAsync.html

**Comment by binarywang** [comment]
重复 #1217
