### ISSUE TITLE
公众号删除永久素材数据格式出错

### ISSUE THREAD

**Issue by Cicinnus0407** [binarywang/WxJava#1220]
### 简要描述
公众号删除永久素材提示,{"errcode":47001,"errmsg":"data format error hint: [1vJ5iA02055190]"}

### 模块版本情况
* WxJava 模块名: wx-mp
* WxJava 版本号:3.5.0

### 详细描述
接口应该使用post json,但是SDK使用的是application/x-www-form-urlencoded

### 日志
[INFO ][2019-09-22 18:13:25][intercept] - --> POST https://api.weixin.qq.com/cgi-bin/material/del_material?access_token=25_NbiuoK4MEs4taJ-GNLjsv9Gz2Mpqxn57rGjWygYZJ7HOmupI0ZwQTJgBZ85o7xaMzMPQKfXWAWl_phsIg0EmK8K5KM6tgk5OWeoJvSPU-loqxIGI3ilVxJ1MFca_DB0ZN9YBmtP1_jZ_iirwMEQfACABTF
[INFO ][2019-09-22 18:13:25][intercept] - Content-Type: application/x-www-form-urlencoded
[INFO ][2019-09-22 18:13:25][intercept] - Content-Length: 52
[INFO ][2019-09-22 18:13:25][intercept] - 
[INFO ][2019-09-22 18:13:25][intercept] - media_id=F7pEBXzvKELjk1Hi3sHpoBjQGtdldJLUzDI_LIBeC7A
[INFO ][2019-09-22 18:13:25][intercept] - --> END POST (52-byte body)
[INFO ][2019-09-22 18:13:25][intercept] - <-- 200 OK https://api.weixin.qq.com/cgi-bin/material/del_material?access_token=25_NbiuoK4MEs4taJ-GNLjsv9Gz2Mpqxn57rGjWygYZJ7HOmupI0ZwQTJgBZ85o7xaMzMPQKfXWAWl_phsIg0EmK8K5KM6tgk5OWeoJvSPU-loqxIGI3ilVxJ1MFca_DB0ZN9YBmtP1_jZ_iirwMEQfACABTF (201ms)
[INFO ][2019-09-22 18:13:25][intercept] - Connection: keep-alive
[INFO ][2019-09-22 18:13:25][intercept] - Content-Type: text/plain
[INFO ][2019-09-22 18:13:25][intercept] - Date: Sun, 22 Sep 2019 10:13:25 GMT
[INFO ][2019-09-22 18:13:25][intercept] - Content-Length: 69
[INFO ][2019-09-22 18:13:25][intercept] - 
[INFO ][2019-09-22 18:13:25][intercept] - {"errcode":47001,"errmsg":"data format error hint: [1vJ5iA02055190]"}
[INFO ][2019-09-22 18:13:25][intercept] - <-- END HTTP (69-byte body)

**Comment by Cicinnus0407** [comment]
具体出错的类: me.chanjar.weixin.mp.util.requestexecuter.material.MaterialDeleteOkhttpRequestExecutor
41行.
```
RequestBody requestBody = new FormBody.Builder().add("media_id", materialId).build();
```

**Comment by binarywang** [comment]
看来是okhttp的实现有问题

**Comment by binarywang** [comment]
3.5.6.B 测试版本已修复，欢迎试用
