### ISSUE TITLE
请问能否支持支付的服务商功能

### ISSUE THREAD

**Issue by linghxz** [binarywang/WxJava#123]
请问能否支持支付的服务商功能，支持子商户模式

**Comment by binarywang** [comment]
请问楼主能否详细展开描述一下，比如文档地址在哪里什么的？可以稍后评估下是否能够实现

**Comment by belerweb** [comment]
服务商模式：https://pay.weixin.qq.com/wiki/doc/api/sl.html

**Comment by binarywang** [comment]
@belerweb 多谢，我大概了看了下，接口名称保持一致，只是增加了若干参数，之后可以考虑下如何整合进去

**Comment by linghxz** [comment]
好久没上了，没及时看不好意思，就是服务商模式，在参数上多了一个子商户的id，别的应该没有变动

**Comment by binarywang** [comment]
@linghxz 发布了一个最新的临时版本，你试下吧，如果有问题及时提出来

**Comment by akwolf** [comment]
@binarywang 请问一下临时版本是哪个版本

**Comment by binarywang** [comment]
看项目首页说明

**Comment by linghxz** [comment]
@binarywang 好的，知道了，谢谢。
