### ISSUE TITLE
企业微信第三方应用获取服务商凭证凭证接口

### ISSUE THREAD

**Issue by null64** [binarywang/WxJava#1230]
获取服务商凭证凭证这个接口没有，是不是遗漏了，还是说有其他的想法

### 官方文档地址
https://work.weixin.qq.com/api/doc#90001/90143/91200

**Comment by binarywang** [comment]
没啥想法，需要的话就补上呗，有可能是新开放的接口

**Comment by binarywang** [comment]
3.5.9.B版本已增加该接口，欢迎试用
