### ISSUE TITLE
是否考虑添加图像处理接口

### ISSUE THREAD

**Issue by TheoNie** [binarywang/WxJava#1235]
### 简要描述
微信OCR和图像能力做了大幅升级，看了源码没有找到图像处理接口，以及OCR接口目前也不是很全。
https://mp.weixin.qq.com/s?__biz=MjM5NDAxMDg4MA==&mid=2650959746&idx=1&sn=cfb27b680b30681af80aa52af50a7a8b&chksm=bd788ded8a0f04fb58e053d34e0dcf63f155685f3cd05ecc7ef5278ff8004c6aea86f56ba526&mpshare=1&scene=23&srcid=&sharer_sharetime=1568177772575&sharer_shareid=ad12f0aacdac5d948cea7b22c998edd1#rd

### 官方文档地址
图像处理接口文档：
https://developers.weixin.qq.com/doc/offiaccount/Intelligent_Interface/Img_Proc.html

**Comment by binarywang** [comment]
应该是新开放的接口，以前没注意到有

**Comment by binarywang** [comment]
3.5.7.B测试版本已添加，欢迎使用
