### ISSUE TITLE
企业微信第三方应用开发，缺少部分接口，是否考虑增加？

### ISSUE THREAD

**Issue by ggqi** [binarywang/WxJava#1236]
企业微信三方授权所需接口：
![image](https://user-images.githubusercontent.com/25816074/66647666-1b427f80-ec5c-11e9-9fc0-0b1515ab22ee.png)
获取访问用户身份接口。
主要是 三方应用开发和内部开发，部分接口是不一样的，可能有缺失。
### 官方文档地址
https://work.weixin.qq.com/api/doc#90001/90143/90597
https://work.weixin.qq.com/api/doc#90001/90143/91121

**Comment by binarywang** [comment]
列出具体使用到然后需要实现的接口，有的接口可能用不到，就不一定去实现了

**Comment by liquanjava** [comment]
版本3.4.1.B第三方应用开发，开发第三方应用时候只能用wxCpTpService了，不支持调用之前的那些接口，也没找到怎么通过wxCpTpService->转换得到wxCpService。没办法调用部门、人员等接口，因为第三方应用的api接收的传参没变，还是accessToken,而不是suiteAccessToken。wxCpTpService里面也没有这些之前的接口

**Comment by brooks-li** [comment]
https://work.weixin.qq.com/api/doc/90000/90135/91816

**Comment by brooks-li** [comment]
批量获取审批单号：https://work.weixin.qq.com/api/doc/90000/90135/91816
获取审批申请详情：https://work.weixin.qq.com/api/doc/90000/90135/91983

**Comment by binarywang** [comment]
楼上所列出的接口已实现，请使用最新版本即可
