### ISSUE TITLE
小程序请支持“订阅消息”通知

### ISSUE THREAD

**Issue by yearliny** [binarywang/WxJava#1238]
### 简要描述
> 请注意，小程序模板消息接口将于2020年1月10日下线，开发者可使用订阅消息功能

大约在两天前（2019-10-13）小程序已经决定将下线模板消息，替代它的是订阅消息，希望能尽快支持这个新特性。

### 官方文档地址
* [模板消息文档](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/template-message.html)
* [订阅消息文档](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/subscribe-message.html)

**Comment by binarywang** [comment]
已有同学提供了 https://github.com/Wechat-Group/WxJava/pull/1239
欢迎帮忙review

**Comment by binarywang** [comment]
3.5.7.B测试版本已添加，欢迎使用
