### ISSUE TITLE
支持微信仿真方式sandboxnew的开发吗

### ISSUE THREAD

**Issue by yaoyasong** [binarywang/WxJava#124]

**Comment by binarywang** [comment]
你是说的微信支付的仿真测试环境吧，之前有人提过这个问题，https://github.com/Wechat-Group/weixin-java-tools/issues/119 ，已实现代码，但发现可能该仿真环境不够完善，并不能真正使用，你可以自己测试下，如果发现什么可以改善的及时提出来。

**Comment by wangjia2016** [comment]
微信支付，可以用花生壳二级域名来搞，经本人测试、扫码支付+JSSDK支付都可以用花生壳的免费二级域名。@yaoyasong

**Comment by yaoyasong** [comment]
@binarywang 刚才自己实现了下调用sandbox服务，发现还是存在一样的问题，暂时没找到原因
"验证签名失败, 请调用getsignkey生成沙箱密钥”

**Comment by yaoyasong** [comment]
@wangjia2016 域名有了，主要是不想每次测试都要正式的转账，0.6%的手续费

**Comment by binarywang** [comment]
@yaoyasong 没错，就如那个issue里所说的，我就怀疑这个环境能否真正使用，你如果能找到代码里存在的问题请及时指出吧，否则就只能等那个环境真正能用的时候再用了。

**Comment by dracupid** [comment]
沙箱环境的signkey需要单独获取，和正式环境的不一样，参考https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1

**Comment by binarywang** [comment]
这个我也注意到了，准备添加新的接口 https://github.com/Wechat-Group/weixin-java-tools/issues/206

**Comment by dracupid** [comment]
好的，多谢～
