### ISSUE TITLE
3.5.7.B版本调用wxMaService.getQrcodeService().createWxaCodeUnlimit(scene,page)微信返回参数错误

### ISSUE THREAD

**Issue by BigTailMonkey** [binarywang/WxJava#1250]
使用3.5.7.B版本调用wxMaService.getQrcodeService().createWxaCodeUnlimit(scene,page)微信返回参数错误，经排查推测是httpPost.setEntity(new StringEntity(qrcodeWrapper.toJson()));此处构建对象时参数构建出问题：构建的参数中缺少line_color属性。

**Comment by BigTailMonkey** [comment]
3.5.0正式版本不存在此问题。

**Comment by binarywang** [comment]
> 3.5.0正式版本不存在此问题。

你确定吗？相关代码应该没做过变动

**Comment by binarywang** [comment]
楼主请提供更详细的信息，比如产生错误信息的具体调用代码，如何调用的，参数情况等

**Comment by binarywang** [comment]
楼主肯定是弄错了，既然没有响应，暂时关闭，如果有进一步需要澄清的事实，请重新开issue说明。
