### ISSUE TITLE
微信代扣（免密支付）

### ISSUE THREAD

**Issue by xq463364973** [binarywang/WxJava#1253]
### 微信免密支付
签约免密支付

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/pap.php?chapter=18_3&index=8

https://pay.weixin.qq.com/wiki/doc/api/wxpay_v2/papay/chapter2_6.shtml

**Comment by hallkk** [comment]
微信已经全面转向支付分，委托代扣不接受新的申请
不需要支持
