### ISSUE TITLE
企业微信：请问是否有支持群机器人（Webhook）的计划

### ISSUE THREAD

**Issue by domainname** [binarywang/WxJava#1255]
### 简要描述
Webhook 是大约 2019-5 新增的功能，又叫企业微信群机器人，请问是否有计划支持。

### 官方文档地址
https://work.weixin.qq.com/help?person_id=1&doc_id=13376&from=search&helpType=undefined

**Comment by binarywang** [comment]
这个使用的人目前看来并不是很多，如果可以，建议自己先行实现，并提交PR。

**Comment by domainname** [comment]
我开了个项目：https://github.com/domainname/wechat-work-bot
有需要的朋友可以自取。

**Comment by wtj1206** [comment]
群机器人啥时候可支持

**Comment by domainname** [comment]
@wtj1206 群机器人的功能相对比较单一，其实仅有一个 Webhook 功能，Webhook 主要用于接入各种应用的消息。所以，真正需要花精力的是把各种应用的消息转换成Markdown格式的消息，而通过企业微信群机器人 Webhook 发消息的代码量其实很少。我做了一个项目 wechat-work-bot，目前接入了 GitLab 的消息，欢迎大家提交 PR 接入更多的应用。https://github.com/domainname/wechat-work-bot

**Comment by binarywang** [comment]
暂时关闭
