### ISSUE TITLE
支付功能中http组件扩展性

### ISSUE THREAD

**Issue by lhjw9810** [binarywang/WxJava#1257]
WxPayServiceApacheHttpImpl与WxPayServiceJoddHttpImpl能否支持除了timeout之外的参数，比如maxTotal,maxPerRoute等参数，自定义的扩展 因为里面有ThreadLocal<WxPayApiData>包变量存在导致不好实现

**Comment by binarywang** [comment]
你说的这些参数在哪里可以看到？

**Comment by binarywang** [comment]
描述不清楚，且无进一步沟通回复，暂时关闭，如果能准确描述请新开issue说明，谢谢
