### ISSUE TITLE
小程序订阅消息

### ISSUE THREAD

**Issue by LPQingFeiDeYi** [binarywang/WxJava#1258]
### 简要描述
请问小程序的订阅消息接口什么时候也能封装一下，谢谢

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/subscribe-message.html

**Comment by lj19950508** [comment]
我也需要这个功能，微信小程序模板推送官方上于2020年1月份将下降， 推荐使用订阅。希望对这一个服务端API进行封装

**Comment by binarywang** [comment]
已经实现了。请关注下最新版本的更新日志，如果不想错过，关注公众号及时接受最新消息。

**Comment by binarywang** [comment]
已经实现了。请关注下最新版本的更新日志，如果不想错过，关注公众号及时接受最新消息。

**Comment by lj19950508** [comment]
啥时候发布3.6呢

**Comment by LPQingFeiDeYi** [comment]
谢谢，好的，已经关注
