### ISSUE TITLE
WxMenu中没有包含conditionalmenu属性

### ISSUE THREAD

**Issue by javafree** [binarywang/WxJava#126]
WxMenu 这个类里面少了两个属性，conditionalmenu和menuid 不然查询菜单没有返回menuid 无法删掉历史错误菜单，conditionalmenu 是自个性化菜单，public WxMenu menuTryMatch(String userid) throws WxErrorException 没有返回。

**Comment by binarywang** [comment]
已实现，接口做了调整重构
