### ISSUE TITLE
JsonSyntaxException 微信手机号码解密报错

### ISSUE THREAD

**Issue by barey-cc** [binarywang/WxJava#1260]
![141572487898_ pic_hd](https://user-images.githubusercontent.com/4272244/67913246-5aaf1c80-fbc7-11e9-9ff0-c79f371c9d74.jpg)

每次应用启动后请求的前几次会报错

**Comment by barey-cc** [comment]
Handling error: JsonSyntaxException, java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by binarywang** [comment]
看置顶问题
