### ISSUE TITLE
能够考虑增加对客服消息的发送返回结果保留的方法？

### ISSUE THREAD

**Issue by moguangquan** [binarywang/WxJava#1261]
### 简要描述
目前调用客服消息返回的结果是boolean,我需要记录返回的微信结果，希望能支持

**Comment by binarywang** [comment]
请描述清楚问题，公众号模块还是小程序的？

**Comment by moguangquan** [comment]
不好意思，没描述清楚，公众号模块和小程序的都希望支持

**Comment by binarywang** [comment]
发送成功的返回信息是这个，你确定有使用价值吗？
```
{"errcode":0,"errmsg":"ok"}
```

**Comment by binarywang** [comment]
而发送失败时无返回值，会抛出异常，你可以在异常里获取原始报文。

**Comment by moguangquan** [comment]
![image](https://user-images.githubusercontent.com/5850355/68098898-5d2cb180-fefa-11e9-8b37-4581a829305e.png)
我看错误信息有返回一些微信异常信息的，我需要记录这些信息

**Comment by binarywang** [comment]
> ![image](https://user-images.githubusercontent.com/5850355/68098898-5d2cb180-fefa-11e9-8b37-4581a829305e.png)
> 我看错误信息有返回一些微信异常信息的，我需要记录这些信息

就像我上面说的，从异常里面获取错误信息。
