### ISSUE TITLE
工具包方法中一个注释都没有啊，文档也很少，新手一脸懵逼！ 

### ISSUE THREAD

**Issue by zz5253083** [binarywang/WxJava#1262]
工具包方法中一个注释都没有啊，文档也很少，新手一脸懵逼！

**Comment by zz5253083** [comment]
工具包方法中一个注释都没有啊，文档也很少，新手一脸懵逼！

**Comment by binarywang** [comment]
你是来搞笑的吗？怎么会一个注释都没有，文档大部分都有，你没仔细阅读首页说明吗？

**Comment by zz5253083** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 上午9:33
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;; 
抄送: "!="<1007070990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Wechat-Group/WxJava] 工具包方法中一个注释都没有啊，文档也很少，新手一脸懵逼！  (#1262)




你是来搞笑的吗？怎么会一个注释都没有，文档大部分都有，你没仔细阅读首页说明吗？

**Comment by zz5253083** [comment]
确实搞笑了，没下源码 ！。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Binary Wang"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 上午9:33
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;; 
抄送: "!="<1007070990@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Wechat-Group/WxJava] 工具包方法中一个注释都没有啊，文档也很少，新手一脸懵逼！  (#1262)




你是来搞笑的吗？怎么会一个注释都没有，文档大部分都有，你没仔细阅读首页说明吗？
