### ISSUE TITLE
是否支持转账给个人用户

### ISSUE THREAD

**Issue by chenglegit** [binarywang/WxJava#1263]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述

![image](https://user-images.githubusercontent.com/48047435/68193903-fc32d580-ffee-11e9-8733-459a7dd91c51.png)

目前下载的demo中只有，对于账户的转账，现在需要对个人用户转账，是否支持？

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
你要看微信支付官方是否支持，不知道你说的个人用户是指什么，你希望以什么方式转账，然后对照官方文档看一下。
