### ISSUE TITLE
是否考虑添加  分账相关API

### ISSUE THREAD

**Issue by flame7988** [binarywang/WxJava#1266]
### 简要描述
直连商户分账主要用于商户将交易成功的资金，按照一定的周期，分账给其他方，可以是合作伙伴、员工、用户或者其他分润方。
目前只找到了企业付款到零钱，但是不太符合多个分账方，而且有资金结算费率问题，能否添加分账相关API

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/allocation.php?chapter=26_1

**Comment by binarywang** [comment]
分账接口已经加了，另外请多留意关注公众号消息。

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1010
