### ISSUE TITLE
小程序多账号切换功能

### ISSUE THREAD

**Issue by mastcer** [binarywang/WxJava#1267]
### 简要描述
目前只有微信公众号模块的WxMpService接口提供账号切换（switchoverTo）方法，希望社区在其他接口中也提供账号切换的方法，因为项目开发中有多个小程序需要管理，同时微信支付模块也是需要多个切换

**Comment by binarywang** [comment]
后续可以考虑

**Comment by binarywang** [comment]
新版本即将支持
