### ISSUE TITLE
多公众号如何实现动态配置？

### ISSUE THREAD

**Issue by itfuyun** [binarywang/WxJava#1270]
目前看到多公众号是通过配置文件写上去，我想把公众号信息放到数据库，动态添加和修改，在此wxMpService如何更新公众号配置（动态添加一个公众号信息进去）？

**Comment by binarywang** [comment]
可以参考 `me.chanjar.weixin.mp.api.WxMpService#addConfigStorage`这个方法，随时增加配置；
`me.chanjar.weixin.mp.api.WxMpService#removeConfigStorage` 这是删除；
`me.chanjar.weixin.mp.api.WxMpService#getWxMpConfigStorage` 这个可以找到当前config，直接修改即可

**Comment by itfuyun** [comment]
ok，谢谢!
