### ISSUE TITLE
微信支付的对账下载有bug

### ISSUE THREAD

**Issue by itboyyjp** [binarywang/WxJava#1275]
### 简要描述
微信支付对账下载，报数组下标越界异常

### 模块版本情况
* 模块名: weixin-java-pay
* 版本号: 3.5.0

### 详细描述
如果微信对账下载接口  返回的结算类型是"普通结算对账单"的格式，但是代码里按“开通免充值券后的结算对账单”的类型去解析字符串，多了“订单金额”，“申请退款金额”，“费率备注”，导致异常

**Comment by binarywang** [comment]
能否给写具体的数据样例可以方便调试？谢谢

**Comment by itboyyjp** [comment]
# 测试数据
交易时间,公众账号ID,商户号,子商户号,设备号,微信订单号,商户订单号,用户标识,交易类型,交易状态,付款银行,货币种类,总金额,代金券或立减优惠金额,微信退款单号,商户退款单号,退款金额,代金券或立减优惠退款金额,退款类型,退款状态,商品名称,商户数据包,手续费,费率
`2014-11-10 16：33：45,`wx2421b1c4370ec43b,`10000100,`0,`1000,`1001690740201411100005734289,`1415640626,`085e9858e3ba5186aafcbaed1,`MICROPAY,`SUCCESS,`CFT,`CNY,`0.01,`0.0,`0,`0,`0,`0,`,`,`被扫支付测试,`订单额外描述,`0,`0.60%
`2014-11-10 16：46：14,`wx2421b1c4370ec43b,`10000100,`0,`1000,`1002780740201411100005729794,`1415635270,`085e9858e90ca40c0b5aee463,`MICROPAY,`SUCCESS,`CFT,`CNY,`0.01,`0.0,`0,`0,`0,`0,`,`,`被扫支付测试,`订单额外描述,`0,`0.60%
总交易单数,总交易额,总退款金额,总代金券或立减优惠退款金额,手续费总金额
`2,`0.02,`0.0,`0.0,`0

**Comment by binarywang** [comment]
建议楼主先使用`com.github.binarywang.wxpay.service.WxPayService#downloadRawBill(com.github.binarywang.wxpay.bean.request.WxPayDownloadBillRequest)` 这个方法，读取原始对账单内容，然后自行处理。至于支持更多格式，需要更多样例来调试，也非常欢迎楼主提供兼容性更强的代码并PR。

**Comment by binarywang** [comment]
3.6.4.B 版本已修复，欢迎使用
