### ISSUE TITLE
建议增加第三方平台接口：代小程序实现业务之订阅消息设置

### ISSUE THREAD

**Issue by heyucong** [binarywang/WxJava#1280]
### 简要描述
建议增加第三方平台接口：代小程序实现业务之订阅消息设置

获取当前帐号所设置的类目信息
本接口用于获取小程序订阅消息的模板库标题列表
获取模板标题下的关键词库
组合模板并添加到个人模板库
获取帐号下的模板列表
删除帐号下的某个模板

非常感谢...

### 官方文档地址
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/Intro.html

**Comment by binarywang** [comment]
3.6.3.B 已实现
