### ISSUE TITLE
自定义http请求工具

### ISSUE THREAD

**Issue by Targetnew** [binarywang/WxJava#1281]
### 简要描述
微信接口的http请求能否实现自定义的方式

### 详细
一般项目中都会有自己定义好的http请求工具,
目前内置的http请求类没法替换,就会导致项目运行后有两套http请求工具,
可否支持使用自定义的http请求工具,
不设置时默认加载内置的,设置后使用自定义的

**Comment by binarywang** [comment]
不知道你看过wiki没，建议先仔细阅读下。

**Comment by Targetnew** [comment]
我的意思是,比如我的项目里已经有一个CloseableHttpClient对象了,
现在没办法使用项目已有的对象,只能修改您的WxMpServiceHttpClientImpl里边CloseableHttpClient对象的参数设置

**Comment by binarywang** [comment]
> 我的意思是,比如我的项目里已经有一个CloseableHttpClient对象了,
> 现在没办法使用项目已有的对象,只能修改您的WxMpServiceHttpClientImpl里边CloseableHttpClient对象的参数设置

你有什么修改建议，建议直接提交PR代码吧

**Comment by CuriousRookie** [comment]
https://github.com/Wechat-Group/WxJava/blob/70f42e21cc642a61e954f1e2ff3743df21684cd6/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/impl/WxMpServiceHttpClientImpl.java#L47-L65
可以使用已有的CloseableHttpClient......实现ApacheHttpClientBuilder这个类，在build方法里返回已有的CloseableHttpClient。
设置WxMpServiceHttpClientImpl的时候使用自己的实现类，而不是默认的DefaultApacheHttpClientBuilder或ApacheHttpDnsClientBuilder。

**Comment by Targetnew** [comment]
> https://github.com/Wechat-Group/WxJava/blob/70f42e21cc642a61e954f1e2ff3743df21684cd6/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/impl/WxMpServiceHttpClientImpl.java#L47-L65
> 
> 
> 可以使用已有的CloseableHttpClient......实现ApacheHttpClientBuilder这个类，在build方法里返回已有的CloseableHttpClient。
> 设置WxMpServiceHttpClientImpl的时候使用自己的实现类，而不是默认的DefaultApacheHttpClientBuilder或ApacheHttpDnsClientBuilder。

get!
