### ISSUE TITLE
企业微信推送Markdown消息请支持表格格式

### ISSUE THREAD

**Issue by chiptbtptp** [binarywang/WxJava#1282]
目前已经支持图文、卡片等格式，但是还不支持表格格式，请问可否添加支持表格格式？

**Comment by binarywang** [comment]
可以考虑，这应该是新增加的

**Comment by binarywang** [comment]
楼主是说官方文档里支持是吗？请提供下具体的文档地址和说明

**Comment by binarywang** [comment]
https://work.weixin.qq.com/api/doc#90000/90135/90248  目前我只是在这里发现有markdown，你所说的支持表格格式，是什么意思？

**Comment by binarywang** [comment]
楼主表达不清，暂时关闭，如果确实有实现的需求，请先开issue。

**Comment by Lianghuajian** [comment]
他的意思应该是使用markdown语法在企业通知消息中显示表格，比如https://www.runoob.com/markdown/md-table.html  现在支持了吗，我试了一下现在好像不支持?

**Comment by binarywang** [comment]
> 他的意思应该是使用markdown语法在企业通知消息中显示表格，比如https://www.runoob.com/markdown/md-table.html 现在支持了吗，我试了一下现在好像不支持?

请仔细看文档：https://work.weixin.qq.com/api/doc/90000/90135/90248#10167/%E6%94%AF%E6%8C%81%E7%9A%84markdown%E8%AF%AD%E6%B3%95

官方只是支持子集，并不支持所有的。这个不是我们这个SDK能控制的
