### ISSUE TITLE
求助大佬，demo能否加入 jssdk认证的代码，谢谢！

### ISSUE THREAD

**Issue by wenchuanli** [binarywang/WxJava#1283]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
demo问题请到对应demo提出，谢谢
