### ISSUE TITLE
Redis能不能用集群方式的呢？

### ISSUE THREAD

**Issue by BerryLong** [binarywang/WxJava#1284]
Redis能不能用集群方式的呢？

**Comment by binarywang** [comment]
当然可以，自行实现即可

**Comment by BerryLong** [comment]
需要如何配置 直接引入的springboot包


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午3:18
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;"Berry"<1137107689@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] Redis能不能用集群方式的呢？ (#1284)




当然可以，自行实现即可
