### ISSUE TITLE
是否考虑添加小程序动态消息接口

### ISSUE THREAD

**Issue by TheoNie** [binarywang/WxJava#1290]
### 简要描述
目前查看源码，没有找到小程序动态消息的接口。

### 官方文档地址
**动态消息流程描述：**
https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/share/updatable-message.html
**动态消息后端接口（共两个接口）：**
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/updatable-message/updatableMessage.createActivityId.html
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/updatable-message/updatableMessage.setUpdatableMsg.html

**Comment by binarywang** [comment]
确实还没加，可以考虑接一下

**Comment by binarywang** [comment]
3.6.9.B测试版本已增加，欢迎使用
