### ISSUE TITLE
WxMaService.JSCODE_TO_SESSION_URL 获取openid的URL错误！！！

### ISSUE THREAD

**Issue by jiell** [binarywang/WxJava#1292]
### 简要描述
微信公众号授权获取回调code，使用code获取openid，一直提示
“【错误信息】:{"errcode":40029,"errmsg":"invalid code, hints: [ req_id: gEkfqoXIRa-GHwarA ]"”

### 模块版本情况
* WxJava 模块名: 3.5.0
* WxJava 版本号:3.5.0

### 详细描述
追踪源码和微信公众平台官网sdk，获取openid的接口应该是：
https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code
原文参考：
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_webpage_authorization.html

**Comment by binarywang** [comment]
WxMaService  这个不是小程序的吗？

**Comment by binarywang** [comment]
楼主可能自己搞混了，也没给答复，暂时关闭

**Comment by jiell** [comment]
好吧&nbsp; 我开发的H5



---原始邮件---
发件人: "Binary Wang"<notifications@github.com&gt;
发送时间: 2019年11月22日(星期五) 下午2:56
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送: "Fihx"<2363498880@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Wechat-Group/WxJava] WxMaService.JSCODE_TO_SESSION_URL 获取openid的URL错误！！！ (#1292)



WxMaService  这个不是小程序的吗？
