### ISSUE TITLE
企业外部联系人客户变更事件新增 ChangeType 常量

### ISSUE THREAD

**Issue by lswj** [binarywang/WxJava#1297]
### 简要描述

目前缺少 外部联系人免验证添加成员事件 ：add_half_external_contact，删除跟进成员事件：del_follow_user
### 官方文档地址
https://work.weixin.qq.com/api/doc#90000/90135/91442/%E5%A4%96%E9%83%A8%E8%81%94%E7%B3%BB%E4%BA%BA%E5%85%8D%E9%AA%8C%E8%AF%81%E6%B7%BB%E5%8A%A0%E6%88%90%E5%91%98%E4%BA%8B%E4%BB%B6

**Comment by binarywang** [comment]
欢迎直接提交PR

**Comment by binarywang** [comment]
欢迎直接提交PR

**Comment by binarywang** [comment]
3.6.1.B测试版本已添加，欢迎使用
