### ISSUE TITLE
WxMpConfigStorage.java接口中没有set方法，导致无法面向接口编程

### ISSUE THREAD

**Issue by songjiesdnu** [binarywang/WxJava#13]
WxMpConfigStorage.java中没有set方法，要使用的话必须在程序中使用具体的实现类，这样便无法面向接口编程，更换实现类的时候需要修改所有引用类型。
请问：不在WxMpConfigStorage.java中书写set方法是基于什么考虑吗？

**Comment by binarywang** [comment]
WxMpConfigStorage 仅是一个接口，赋值需要由其实现类完成set方法，具体可以参考me.chanjar.weixin.mp.api.WxMpInMemoryConfigStorage 这个实现类

**Comment by songjiesdnu** [comment]
我的意思是将set方法也卸载接口中，这样在编程的时候引用类型就可以是WxMpConfigStorage ，而不是具体的实现类

**Comment by binarywang** [comment]
基本明白你的意思，你的需求有点特别，不太建议你这么做，一般来说这种配置性质的信息在系统始化设置后就无需修改，除非你有即时修改配置使其生效的需求，这种情况下一般也是在你知道其实例化的类型的前提下完成的，你就可以进行强转实现。

**Comment by binarywang** [comment]
而且如果在接口中实现这些set方法，会造成其接口实现类也必要实现该set方法，而事实上实现类可能不需要这些set方法，完全可以通过spring注入实现相应属性的设值。所以如果你确实觉得需要接口来提供这些方法，你可以尝试继承该接口，实现你自己的定制接口即可
