### ISSUE TITLE
WxOpenConfigStorage中怎么控制不自动刷新ComponentAccessToken

### ISSUE THREAD

**Issue by niutd777** [binarywang/WxJava#1303]
WxOpenConfigStorage中怎么控制不自动刷新ComponentAccessToken，现在autoRefreshToken()默认值为true

 /*
       * 发生以下情况时尝试刷新access_token
       * 40001 获取access_token时AppSecret错误，或者access_token无效
       * 42001 access_token超时
       * 40014 不合法的access_token，请开发者认真比对access_token的有效性（如是否过期），或查看是否正在为恰当的公众号调用接口
       */
      if (error.getErrorCode() == 42001 || error.getErrorCode() == 40001 || error.getErrorCode() == 40014) {
        // 强制设置wxMpConfigStorage它的access token过期了，这样在下一次请求里就会刷新access token
        this.getWxOpenConfigStorage().expireComponentAccessToken();
        if (**this.getWxOpenConfigStorage().autoRefreshToken()**) {
          return this.post(uri, postData, accessTokenKey);
        }
      }

**Comment by binarywang** [comment]
这还真是个问题。@007gzs 有空可以看下呢

**Comment by 007gzs** [comment]
可以重写 config 中的 autoRefreshToken函数返回false可以不自动刷新 ComponentAccessToken，授权公众号的token原来是直接刷新的，刚提交了个PR，沿用三方的配置

**Comment by binarywang** [comment]
已修复
