### ISSUE TITLE
希望能够加入微信发票功能

### ISSUE THREAD

**Issue by TheoNie** [binarywang/WxJava#1305]
### 简要描述
目前发现源码中没有微信发票相关功能，这个对于需要开发票的场景来说还是很有用的。

### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/WeChat_Invoice/E_Invoice/Instruction.html

**Comment by binarywang** [comment]
这个功能看似用的人并不多，建议如果自己已经有接入需求，可自行先实现代码，并提交PR

**Comment by binarywang** [comment]
3.8.0正式版本已增加相关功能
