### ISSUE TITLE
希望第三方授权模式(第三方平台--服务商模式)，也尽快支持小程序消息订阅机制

### ISSUE THREAD

**Issue by angletym2014** [binarywang/WxJava#1306]
1. 微信2020年1月20日，就将停止旧版的小程序消息发送机制。麻烦尽快支持。

2. 微信相关官网文档地址为： https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/Sub_Template_Message_Setting.html

**Comment by binarywang** [comment]
重复 https://github.com/Wechat-Group/WxJava/issues/1280
关闭
