### ISSUE TITLE
微信小程序内容安全校验接口

### ISSUE THREAD

**Issue by wooowo** [binarywang/WxJava#1307]
3.6.0版本weixin-java-miniapp
security.mediaCheckAsync 返回对象 以及 相关消息推送的消息体和路由功能 可否完善下
security.msgSecCheck能否放开微信返回结果 而不是false 或 true 
security.imgSecCheck 能有直接处理http链接为入参的方法就更好了

**Comment by binarywang** [comment]
建议楼主直接提供PR，看样子你的需求其实很清楚，用代码实现更容易些吧

**Comment by binarywang** [comment]
楼主提到的第一个问题，准备修复，是之前实现的作者没有实现完整导致；
第二个没必要，你如果想获取其他信息，捕获异常即可。
第三个问题，可以加一个，虽然不是很有必要，但既然提出来了，可以尝试实现下

**Comment by binarywang** [comment]
3.6.3.B版本已完成相关工作
