### ISSUE TITLE
不建议往支付加功能

### ISSUE THREAD

**Issue by lly835** [binarywang/WxJava#131]
对一个公司来说，会把微信支付和支付宝支付放在一个项目里，而不是把微信开发和微信支付放一起

**Comment by binarywang** [comment]
首先感谢你提出这个想法，不过这个就是微信相关的工具包，所以就提供了微信相关的功能。至于你说的问题，那可能就是个别公司的习惯问题了，我们也没必要单独去拆分一个微信支付的项目出来了。

**Comment by binarywang** [comment]
不过确实可以考虑将微信支付相关接口抽取出来，独立为一个子项目，需要好好考虑下。

**Comment by lly835** [comment]
我负责公司的支付系统，对接第三方支付已经2年了，支付宝微信招行等等坑也踩得不少，我最近打算写一个支付的sdk，一起聊聊？

**Comment by binarywang** [comment]
暂时关闭，之后再考虑
