### ISSUE TITLE
WxAccessToken 缺少方法

### ISSUE THREAD

**Issue by xJoeWoo** [binarywang/WxJava#1313]
### 简要描述
想要对微信小程序配置类 `cn.binarywang.wx.miniapp.config.impl.WxMaRedisConfigImpl` 进行完善，使它可以根据数据库编号使用不同的 Redis 数据库，还有添加密码认证功能。

着手实现的时候发现 `updateAccessToken` 方法：
https://github.com/Wechat-Group/WxJava/blob/476b067392264098cfcb4c5c516555052290093c/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/config/impl/WxMaRedisConfigImpl.java#L131-L134

里面的 `accessToken.getAccessToken()` 和 `accessToken.getExpiresIn()` 报错，原因是 `me.chanjar.weixin.common.bean.WxAccessToken` 里面没有这两个方法：
https://github.com/Wechat-Group/WxJava/blob/70f42e21cc642a61e954f1e2ff3743df21684cd6/weixin-java-common/src/main/java/me/chanjar/weixin/common/bean/WxAccessToken.java#L14-L25

其它使用到 `WxAccessToken` 类的方法，都有类似错误。例如 `cn.binarywang.wx.miniapp.config.impl.WxMaDefaultConfigImpl`、`me.chanjar.weixin.mp.config.impl.WxMpDefaultConfigImpl`。
需要如何修复？

**Comment by binarywang** [comment]
报错，是指什么报错

**Comment by xJoeWoo** [comment]
`WxAccessToken` 里不存在这两个方法

![image](https://user-images.githubusercontent.com/3151930/70391149-f88ad800-1a0c-11ea-9653-cdb8545d7df7.png)

**Comment by xJoeWoo** [comment]
哦。。是 `lombok` 没生成出来的问题，自己疏忽了！
