### ISSUE TITLE
增加 微信支付退款失败时 throw exception由业务代码控制的开关

### ISSUE THREAD

**Issue by stategen** [binarywang/WxJava#1315]
@Override
  public WxPayRefundResult refund(WxPayRefundRequest request) throws WxPayException {
    request.checkAndSign(this.getConfig());

    String url = this.getPayBaseUrl() + "/secapi/pay/refund";
    if (this.getConfig().isUseSandboxEnv()) {
      url = this.getConfig().getPayBaseUrl() + "/sandboxnew/pay/refund";
    }

    String responseContent = this.post(url, request.toXML(), true);
    WxPayRefundResult result = WxPayRefundResult.fromXML(responseContent);
    //退款不成功时，希望将不成功的原因记录下来，但是以下代码先throw excetion,将导致不能
    //将微信返回结果/原因记录下来
    //result.checkResult(this, request.getSignType(), true);
    //应该在WxPayRefundRequest 添加属性 Boolean checkSuccess
     result.checkResult(this, request.getSignType(), request.getCheckSuccess());
     return result;
  }

**Comment by binarywang** [comment]
你自己捕获异常就可以得到对应出错信息

**Comment by stategen** [comment]
我的意思是，把微信返回的xmlString保存下来，以便运营分析

**Comment by stategen** [comment]
我明白了，WxPayException就有xmlString属性，谢谢
