### ISSUE TITLE
获取accesstoke的接口没有做trim

### ISSUE THREAD

**Issue by workcheng** [binarywang/WxJava#132]
获取accesstoken的接口没有做trim，导致请求的时候secret会带上空格，生产环境上secret配置运维人员带了空格，然后请求就报错，排查了很久

**Comment by binarywang** [comment]
这个如群里大伙讨论的那样，不算什么问题。不过你既然提出了，可以提供一个pull request吧，你调试发现的，所以就很容易知道该修改哪里吧

**Comment by workcheng** [comment]
嗯，后面有时间我会提交pr
