### ISSUE TITLE
小程序增加订阅消息模版相关接口

### ISSUE THREAD

**Issue by junetigerlee** [binarywang/WxJava#1320]
### 简要描述
大神们：

腾讯官方通知：
组合模板并添加至帐号下的个人模板库（请注意，小程序模板消息接口将于2020年1月10日下线，开发者可使用订阅消息功能）
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/template-message/templateMessage.addTemplate.html
### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
订阅消息：
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.addTemplate.html

**Comment by binarywang** [comment]
终于调试完了，6个接口居然有两个404

**Comment by binarywang** [comment]
3.6.2.B测试版本已添加，欢迎使用

**Comment by whhya** [comment]
接口404的问题,是官方的问题吧?

**Comment by binarywang** [comment]
> 接口404的问题,是官方的问题吧?

感觉是
