### ISSUE TITLE
微信广告接口报错 WxMarketingService.addUserAction 

### ISSUE THREAD

**Issue by zephyryi** [binarywang/WxJava#1324]
因为没有在http header里面设置 content-type: application/json，导致微信广告接口返回
{"errcode":900351002,"errmsg":"JSON string is malformed."}

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/commit/9c58930719fba624a278e530755b00a104233452 最新其他问题修复时已添加
