### ISSUE TITLE
现在企业微信已经全部升级了. agentId已经取消了

### ISSUE THREAD

**Issue by whoooami** [binarywang/WxJava#1329]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

agentId已经全部取消，管理组也取消。现在/cgi-bin/getToken接口以现在结构配置直接报40001.

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号:3.6.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
你在哪儿看到的相关说明？

**Comment by whoooami** [comment]
> 你在哪儿看到的相关说明？

我重新看了下。这里面主要是企业内部应用的实现。我看的是第三方服务商的开发。里面已经取消了agentId.

**Comment by binarywang** [comment]
第三方应用？也支持的

**Comment by yuankangli** [comment]
企业微信开发第三方应用没有agentId, 只有一个SuiteID, 并且是String类型

**Comment by soulmz** [comment]
@binarywang @yuanqixun 
<img width="732" alt="图片" src="https://user-images.githubusercontent.com/10662992/85938552-e9d02800-b940-11ea-85e0-33157f264639.png">

企业服务商  开发应用 https://open.work.weixin.qq.com/wwopen/common/readDocument/13245

**Comment by binarywang** [comment]
第三方应用请使用这个接口  ：`me.chanjar.weixin.cp.api.WxCpTpService`

**Comment by binarywang** [comment]
另外请不要在已关闭的issue下留言，建议新开issue，明确说明，如果必需引用的话，加入issue关联即可，谢谢合作
