### ISSUE TITLE
WxMaSubscribeServiceImpl.getPubTemplateTitleList方法中返回值json转换失败

### ISSUE THREAD

**Issue by whhya** [binarywang/WxJava#1331]
### 简要描述
WxMaSubscribeServiceImpl.getPubTemplateTitleList方法中返回值json转换失败
### 模块版本情况
* WxJava 模块名: miniapp
* WxJava 版本号:3.6.3.b

### 详细描述

![image](https://user-images.githubusercontent.com/28398139/71361147-0889e680-25cd-11ea-8b27-5953204ffb53.png)

**Comment by binarywang** [comment]
图片看不到，请尽量用文字描述

**Comment by binarywang** [comment]
问题已定位，修复代码已提交，请等待版本发布后验证，谢谢及时提出

**Comment by binarywang** [comment]
3.6.4.B 版本已修复，欢迎使用
