### ISSUE TITLE
如何能够使用多个第三方开放平台？

### ISSUE THREAD

**Issue by Fawkes-hub** [binarywang/WxJava#1333]
需要在业务中进行判断用户公众号可以选择绑定在哪一个第三方平台上，一套系统如何支持多个第三方平台？？

**Comment by Fawkes-hub** [comment]
`//存入多个第三方内容
    private Map<String, WxOpenComponentService> WxOpenComponentServiceMap = new HashMap<>();
    private Map<String, WxOpenConfigStorage> WxOpenConfigStorageMap = new HashMap<>();`
找到方法了，直接存到内存，每次通过传入不同APPID进行获取。
` //每个对象单独储存
            WxOpenComponentServiceMap.put(wxComponentOne.getAppid(), this.getWxOpenComponentService());
            WxOpenConfigStorageMap.put(wxComponentOne.getAppid(), this.getWxOpenConfigStorage());`

**Comment by Fawkes-hub** [comment]
当我真正尝试的时候，只是存储getWxOpenConfigStorage和getWxOpenComponentService并不能行，不知道正确的方法该怎么弄？

**Comment by binarywang** [comment]
#1399 重复问题，请在此issue中统一讨论
