### ISSUE TITLE
是否可以考虑加入微信小程序的订阅消息功能呀？

### ISSUE THREAD

**Issue by Stark-868** [binarywang/WxJava#1334]
微信小程序将于2020.1.10正式取消模板消息接口了，改用订阅消息，希望您有空可以跟进一下哟~
[https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html](官方文档)

**Comment by binarywang** [comment]
大哥，早就支持了，你多久没看日志了？

**Comment by binarywang** [comment]
注意关注微信公众号，及时接受版本更新日志

**Comment by Stark-868** [comment]
好的老哥 我错了 我这就关注
