### ISSUE TITLE
建议：API接口 中增加一些注释，并且变量名可以起的可以看懂 可以吗？

### ISSUE THREAD

**Issue by youngchen1987** [binarywang/WxJava#1336]
wxjava 是一个不错的组件，
但是使用过程中有些建议，希望作者可以看到
API接口 中增加一些注释，并且变量名可以起的可以看懂
  
不知道其他人是不是有这样的疑惑？

**Comment by binarywang** [comment]
请指出具体的问题，如果你有更好的命名，欢迎直接提供PR

**Comment by binarywang** [comment]
另外部分接口没加注释属于疏忽，欢迎直接指出来，一起完善

**Comment by youngchen1987** [comment]
![image](https://user-images.githubusercontent.com/11566474/71469533-6eac7e80-2804-11ea-8ba2-0d8a0d4badde.png)
像这样的

**Comment by youngchen1987** [comment]
好像WxMaTemplateService 类型这样service 下的方法的变量名都是var 这样的不同俗移动的变量吧？

**Comment by binarywang** [comment]
大哥，你没关联源码吧，至少关联javadoc也不是这样的。

**Comment by binarywang** [comment]
你的截图是反编译出来的，根本不是源码
