### ISSUE TITLE
微信公众号回复文本消息时，使用\r\n内容无法换行

### ISSUE THREAD

**Issue by 308299160** [binarywang/WxJava#1342]
版本号：v3.6.0
微信公众号回复文本消息时，使用\r\n，\n也试了，内容都无法换行

> TextBuilder responseMsgBuilder = WxMpXmlOutMessage.TEXT()
                .fromUser(myId)
                .toUser(openId);
String content = "hello\r\nworld";
 responseMsgBuilder.content(content).build();
String msg = message.toXml();
response.getWriter().write(new String(msg.getBytes(), "ISO-8859-1"));

最终在公众号里面显示出的消息是：hello\r\nworld
而不是
hello
world

**Comment by binarywang** [comment]
这不是sdk的问题，是微信公众号自身的问题
