### ISSUE TITLE
企业微信获取审批数据接口getapprovaldata即将不再维护

### ISSUE THREAD

**Issue by brooks-li** [binarywang/WxJava#1344]
### 简要描述
获取审批数据（旧）
提示：推荐使用新接口“批量获取审批单号”及“获取审批申请详情”，此接口后续将不再维护、逐步下线。
请求地址：https://qyapi.weixin.qq.com/cgi-bin/corp/getapprovaldata?

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/91530

跪求加上新的获取审批数据接口

**Comment by binarywang** [comment]
有空了实现下

**Comment by einsitang** [comment]
👍

**Comment by einsitang** [comment]
@brooks-li 需要测试的ak

**Comment by binarywang** [comment]
3.6.5.B测试版本已增加相应接口，欢迎使用
