### ISSUE TITLE
wx-java-mp 被拦截器拦截

### ISSUE THREAD

**Issue by Liwei6707** [binarywang/WxJava#1345]
wx-java-mp 在springsecurity中，无法正常运行，如何解决

**Comment by binarywang** [comment]
请描述清楚问题，你确定这两个有冲突？

**Comment by Liwei6707** [comment]
A项目中使用的security,B项目使用的wx-java，A引入B 的jar,

**Comment by Liwei6707** [comment]
A项目 是security,B项目是wx-java,A引入B jar，微信get方法正常，如图
![image](https://user-images.githubusercontent.com/36660930/71541179-fc68a500-298f-11ea-9687-b075ee1e24c8.png)


post方法会在WxMpXmlMessage inMessage = WxMpXmlMessage.fromXml(requestBody);方法出现错误，
![image](https://user-images.githubusercontent.com/36660930/71541218-7d27a100-2990-11ea-9c60-815d5748e16f.png)
，已验证，确实存在这个问题，A  B单独运行没有问题，

**Comment by Liwei6707** [comment]
没有研究wx-java的底层实现，不过A B 结合后确实存在问题

**Comment by binarywang** [comment]
大哥，是你xstream版本冲突导致的

**Comment by binarywang** [comment]
错误信息里很明显啊

**Comment by binarywang** [comment]
wiki里常见问题也提到过类似问题

**Comment by Liwei6707** [comment]
原来是使用了原本A的xstream,谢谢，常见问题里看不到版本的

**Comment by binarywang** [comment]
常见问题里有pom链接，你自己对比版本就知道了
