### ISSUE TITLE
请求更新三方平台-代小程序开发-代码管理-提交审核（开放平台）

### ISSUE THREAD

**Issue by zxfreedom** [binarywang/WxJava#1347]
### 简要描述
第三方平台-代小程序开发-代码管理-提交审核 请求参数新增version_desc字段

### 官方文档地址
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/code/submit_audit.html

**Comment by zxfreedom** [comment]
> ### 简要描述
> 
> 第三方平台-代小程序开发-代码管理-提交审核 请求参数新增version_desc字段
> ### 官方文档地址
> 
> https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/code/submit_audit.html

**Comment by binarywang** [comment]
3.6.5.B测试版本已添加，欢迎使用
