### ISSUE TITLE
WxPayMicropayRequest这个类里面少了一些字段

### ISSUE THREAD

**Issue by CaiNiaoYiZhi** [binarywang/WxJava#1352]
![image](https://user-images.githubusercontent.com/34234260/71655015-ce100e80-2d6f-11ea-9317-13b2920e9c9e.png)

device_info这个字段没有，其他的我没有仔细对

**Comment by binarywang** [comment]
经过对比，还差 `receipt` 这个参数

**Comment by binarywang** [comment]
3.6.7.B版本已添加缺少的参数，欢迎使用
