### ISSUE TITLE
WeixinPay 遇到 统一下单 调用接口时 请求阻塞 不执行也不返回

### ISSUE THREAD

**Issue by carr2014** [binarywang/WxJava#1357]
### 简要描述
微信支付统一下单接口:
com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl.java
createOrder()
---->
com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.java
post()方法中:httpClient.execute(httpPost) 73行代码;执行时阻塞;不返回数据

### 模块版本情况
* WxJava pay: 
* WxJava 3.6.0:

### 日志
没有日志输出,现象就是出现代码执行,不返回;假死;

**Comment by binarywang** [comment]
确定不是网络问题？

**Comment by binarywang** [comment]
应该是网络问题，楼主是否已解决？

**Comment by carr2014** [comment]
依赖的网络jar包版本问题,已解决啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月16日(星期四) 下午5:14
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;"40538732 "<459020799@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] WeixinPay 遇到 统一下单 调用接口时 请求阻塞 不执行也不返回 (#1357)




应该是网络问题，楼主是否已解决？
