### ISSUE TITLE
微信公众号,获取accessToken,在集群情况下,会不会每个服务都会重新去请求生成新的accessToken,导致一致重复请求

### ISSUE THREAD

**Issue by weiliangzhou** [binarywang/WxJava#1359]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by mr-xiaoyu** [comment]
用redis

**Comment by binarywang** [comment]
没错
