### ISSUE TITLE
WxMenuRule定义和微信文档不一致

### ISSUE THREAD

**Issue by hashmaparraylist** [binarywang/WxJava#136]
预期说是不一致，应该说是微信SB。

根据`创建个性化菜单的wiki`显示，用户标签id应该对应tag_id。

然而自定义菜单查询时，rule的用户标签id变成了group_id。

所以menuGet()接口获得的WxMpMenu的conditionalMenu里的tagId永远是null

**Comment by binarywang** [comment]
感谢楼主发现并提出这个问题，稍后核实下，争取在新版本发布前修复掉。

**Comment by huntwhat** [comment]
@binarywang 
这个问题，貌似在WxMpMenuService的menuGet的方法中依然还有。因为使用的是**WxMpMenu**.fromJson(resultContent); 而不是**WxMenu**.fromJson(resultContent);

**Comment by binarywang** [comment]
我粗略看了，它们好像是使用的同一个WxMenuRule吧，你确定是有问题么？

**Comment by flybirding** [comment]
请把我从这个组删除




发自网易邮箱大师
在2017年05月09日 18:29，Binary Wang 写道：

我粗略看了，它们好像是使用的同一个WxMenuRule吧，你确定是有问题么？

**Comment by binarywang** [comment]
@flybirding 你是订阅了吧，选择取消watch（unwatch）就行了，其他人无法操作

**Comment by huntwhat** [comment]
@binarywang 
修复的代码改动的是**WxMenuGsonAdapter**，这个是在WxGsonBuilder里注册的INSTANCE.registerTypeAdapter(**WxMenu**.class, new **WxMenuGsonAdapter**());

但是只对应了WxMenu类，而不是WxMpMenu类，这样在调用WxMpMenu.fromJson时，解析就不对了。

**Comment by binarywang** [comment]
@huntwhat 你可能没仔细看代码实现，WxMpMenu已改用注解实现，所以跟WxGsonBuilder没有关系

**Comment by binarywang** [comment]
@huntwhat 
我今天又重新研究了，确实是有问题， 已修复

**Comment by rjliulei** [comment]
这个问题还是有啊，个性化菜单创建后咋出来group_id了？！

**Comment by binarywang** [comment]
什么问题，能说明白些吗？如果是不同的问题，最好单独提出一个issue出来，谢谢
