### ISSUE TITLE
mp-3.6.4.B,使用WxMpXmlMessage.fromEncryptedXml();时验签失败

### ISSUE THREAD

**Issue by righteous-criminal** [binarywang/WxJava#1360]
解析加密报文时，此工具类种调用的SHA1加密方法需要四个参数，timestamp，nonce，token，encryptString，然后排序在加密后与微信发送的signature出现不一致的情况，如果不使用encryptString这个参数则验签成功

**Comment by binarywang** [comment]
没看明白啥意思

**Comment by binarywang** [comment]
相关代码存在很久了，如果确认有问题，请给个测试用例看下？

**Comment by righteous-criminal** [comment]
在加密通讯时，调用此方法里面有个加密消息签名校验，参数都是正常的，但是会校验失败






| |
...
|
|
zhangbin_0212@126.com
|
签名由网易邮箱大师定制
在2020年1月6日 18:07，Binary Wang<notifications@github.com> 写道：

没看明白啥意思

**Comment by binarywang** [comment]
还是没明白

**Comment by binarywang** [comment]
楼主如果有时间，麻烦详细描述下

**Comment by binarywang** [comment]
楼主还方便解释下不？

**Comment by righteous-criminal** [comment]
不好意思，最近忙的忘记看了，我组织一下语言，然后回复你


| |
...
|
|
zhangbin_0212@126.com
|
签名由网易邮箱大师定制
在2020年1月6日 18:07，Binary Wang<notifications@github.com> 写道：

没看明白啥意思

**Comment by righteous-criminal** [comment]
因为代码时间较长了，所以先说一下，微信公众号在后台接收消息的时候会接收到4个参数，nonce（随机数）， signature（加密串），timestamp（时间戳），xml报文，接收参数后需要“验签”操作，用到的方法就是SHA1加密算法，加密规则为微信设置的token，nonce，timestamp三个字段进行排序加密，然后与signature比较，如果相同则通过，不通过则返回错误。


调用此方法时：会报出“签名校验失败”，通过追踪源码得知：


此方法中调用了加密验签的方法


但是，用到了四个参数进行加密，多了cipherText加密报文这个参数，导致最后  “加密后的签名”  与  “微信传过来的签名”  不一致


如果我还没表述清楚的话，我也没办法了。。。我尽力了。。。

**Comment by binarywang** [comment]
经测试没有问题，不知道是不是你的使用方式有问题，建议写出你的详细代码，也就是对应的测试用例，谢谢

**Comment by binarywang** [comment]
暂时关闭
