### ISSUE TITLE
WxCpDepartmentServiceImpl 中的list(long id)方法写的不太好

### ISSUE THREAD

**Issue by terlanks** [binarywang/WxJava#1361]
### 简要描述
WxCpDepartmentService 的方法
public List<WxCpDepart> list(Long id) throws WxErrorException {
    String url = this.mainService.getWxCpConfigStorage().getApiUrl(DEPARTMENT_LIST);
    if (id != null) {
      url += "?id=" + id;
    }
使用一个long作为参数，虽然对这个参数做了判断不为空，支持微信API中的不加ID参数情况，但是一般来说很难真正穿一个null的long参数进来，一般IDE编译都会出错的。

建议改成Optional<Long> 更好～

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/90208

**Comment by binarywang** [comment]
为啥会真正难传？不太理解，没有就传null，会很难？
