### ISSUE TITLE
第三方开放平台-查询服务商的当月提审限额及加速审核接口

### ISSUE THREAD

**Issue by ningxz** [binarywang/WxJava#1363]
查询服务商的当月提审限额（quota）和加急次数

服务商可以调用该接口，查询当月平台分配的提审限额和剩余可提审次数，以及当月分配的审核加急次数和剩余加急次数。（所有旗下小程序共用该额度），接口地址: 
https://api.weixin.qq.com/wxa/queryquota?access_token=ACCESS_TOKEN

加急审核申请

有加急次数的第三方可以通过该接口，对已经提审的小程序进行加急操作，加急后的小程序预计2-12小时内审完。接口地址: 
https://api.weixin.qq.com/wxa/speedupaudit?access_token=ACCESS_TOKEN

**Comment by silloy** [comment]
WxOpenMaService # speedAudit
WxOpenMaService # queryQuota
是不是这两接口？

**Comment by binarywang** [comment]
确实已经有了，关闭

**Comment by binarywang** [comment]
#1199
