### ISSUE TITLE
公众号发送模板消息小程序路径是pagepath而不是path

### ISSUE THREAD

**Issue by lenvonsam** [binarywang/WxJava#1367]
### 简要描述
公众号发送模板消息小程序路径是pagepath而不是path

### 模块版本情况
* WxJava 模块名: WxMpTemplateMessage
* WxJava 版本号:3.6.0

### 详细描述
公众号发送模板消息小程序路径是pagepath而不是path
```java
mpService.getTemplateMsgService().sendTemplateMsg(tpltMessage)
```
WxMpTemplateMessage实例生成的json string中小程序路径的key是path而不是pagepath,导致用户从消息模板跳转到小程序永远是首页而不是指定页面，麻烦尽快解决，谢谢

**Comment by binarywang** [comment]
还有个参数，你注意下：
`me.chanjar.weixin.mp.bean.template.WxMpTemplateMessage.MiniProgram` 类里的：
```
    /**
     * 是否使用path，否则使用pagepath.
     * 加入此字段是基于微信官方接口变化多端的考虑
     */
    private boolean usePath = true;
```

**Comment by lenvonsam** [comment]
谢谢，由于个人的疏忽，少看了usePath这个参数，问题解决了，开心~~~
