### ISSUE TITLE
建议增加小程序自定义模板支持

### ISSUE THREAD

**Issue by gongshsh** [binarywang/WxJava#1373]
为了便于使用该工具的用户方便的导入样本数据，并快速开发搜索直达，建议增加自定义模板的相关内容。

### 官方文档地址
https://wsad.weixin.qq.com/wsad/zh_CN/htmledition/widget-docs-v3/html/index.html

**Comment by binarywang** [comment]
其实就只是  `导入抽样数据` 这一个接口吧

**Comment by binarywang** [comment]
https://wsad.weixin.qq.com/wsad/zh_CN/htmledition/widget-docs-v3/html/custom/quickstart/implement/import/index.html

**Comment by gongshsh** [comment]
> https://wsad.weixin.qq.com/wsad/zh_CN/htmledition/widget-docs-v3/html/custom/quickstart/implement/import/index.html

**Comment by gongshsh** [comment]
> 其实就只是 `导入抽样数据` 这一个接口吧

嗯嗯，基本上是的，还有消息同步的内容。

**Comment by binarywang** [comment]
3.7.5.B 测试版本已添加
