### ISSUE TITLE
分账功能-查询分账结果接口还未实现

### ISSUE THREAD

**Issue by zhongyu-ji** [binarywang/WxJava#1375]
### 简要描述
微信分账的查询分账结果接口始终不能用

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.6.0

### 详细描述
查询分账结果源码的实现是这样：if (true) throw new WxPayException("暂不支持，微信一直返回签名失败"); 这个一直没解决吗

**Comment by binarywang** [comment]
你可以尝试下，看是什么问题，如果你有账号的话，尝试下吧

**Comment by lixuankun** [comment]
ProfitSharingServiceImpl 这个类第79行
```
  @Override
  public ProfitSharingQueryResult profitSharingQuery(ProfitSharingQueryRequest request) throws WxPayException {
    if (true) throw new WxPayException("暂不支持，微信一直返回签名失败");
    request.checkAndSign(this.payService.getConfig());
    String url = this.payService.getPayBaseUrl() + "/pay/profitsharingquery";

    String responseContent = this.payService.post(url, request.toXML(), true);
    ProfitSharingQueryResult result = BaseWxPayResult.fromXML(responseContent, ProfitSharingQueryResult.class);
    result.checkResult(this.payService, request.getSignType(), true);
    return result;
  }
```
@binarywang

**Comment by zhongyu-ji** [comment]
@binarywang 
当初这个异常是怎么产生的，是不是签名类型的问题？支付是用的MD5，分账时没有改成HMAC-SHA256，分账的签名类型只能用这个（我现在账号还不够，没法试）

**Comment by binarywang** [comment]
异常是故意抛出的，因为原实现者没调试成功，我看刚才 @lixuankun  已经提供修复的PR了

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/1378 已修复

**Comment by zhongyu-ji** [comment]
新发布的3.6.6.B测试版，查询分账结果这里显示的还和原来一样，请看下什么问题

**Comment by binarywang** [comment]
> 新发布的3.6.6.B测试版，查询分账结果这里显示的还和原来一样，请看下什么问题

这个最新版本并没有包含这个提交，你可以关注下版本发布日志。
