### ISSUE TITLE
订阅消息中的模板管理功能，如取模板列表

### ISSUE THREAD

**Issue by Simbafa** [binarywang/WxJava#1383]
### 简要描述

> 小程序模板消息接口将于2020年1月10日下线，开发者可使用订阅消息功能

目前取模板消息下的模板列表的API还可用

订阅消息发送功能已实现，订阅消息下的模板管理功能还没有

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.getTemplateList.html

**Comment by binarywang** [comment]
请使用最新测试版本，里面有实现
