### ISSUE TITLE
微信支付付款码支付需支持分账

### ISSUE THREAD

**Issue by AbnerZhu** [binarywang/WxJava#1385]
### 简要描述
查看 3.6.0 版本， 目前仅在 WxPayUnifiedOrderRequest 统一下单中添加分账参数， 但是分账场景是支持统一下单、付款码支付和委托扣款的

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=24_3&index=3

**Comment by binarywang** [comment]
可以加上

**Comment by binarywang** [comment]
3.6.7.B版本已支持，欢迎使用
