### ISSUE TITLE
接口问题

### ISSUE THREAD

**Issue by slin1972** [binarywang/WxJava#1386]
我想问一下
https://api.weixin.qq.com/sns/oauth2/component/access_token
和
https://api.weixin.qq.com/sns/oauth2/access_token
这个接口有什么分别
第二个我在app调用微信登录
![image](https://user-images.githubusercontent.com/7867412/72667428-e9109d00-3a56-11ea-8f9b-90687b15d9f5.png)
上看到
![image](https://user-images.githubusercontent.com/7867412/72667457-08a7c580-3a57-11ea-8eb2-3183f8eb4c62.png)
因为微信不建议这个接口放在前端调用
![image](https://user-images.githubusercontent.com/7867412/72667463-152c1e00-3a57-11ea-8e5c-55424e9d613d.png)
所以 微信文档写的真他妈烂烂烂，不建议放在前端使用，时序图没有第三方应用服务器？

现在的问题是我在WxJava的源码里面只看到了
https://api.weixin.qq.com/sns/oauth2/component/access_token
所以想问一下这2者有什么区别

**Comment by binarywang** [comment]
两个接口都有实现，一个是三方平台里用的，一个是微信登录用的，你看两个地址的参数都不一样的

**Comment by slin1972** [comment]
没有
我在gitlab里面对项目全局搜索
![image](https://user-images.githubusercontent.com/7867412/72675826-febcab80-3ac4-11ea-842c-11973b1bcab0.png)
只有
https://api.weixin.qq.com/sns/oauth2/component/access_token
没有
https://api.weixin.qq.com/sns/oauth2/access_token

**Comment by binarywang** [comment]
你搜索的方式有问题，搜 `oauth2/access_token`

**Comment by slin1972** [comment]
微信登录的不应该放在 微信开放平台：weixin-java-open 里面吗

现在在 公众号（包括订阅号和服务号）：weixin-java-mp？

**Comment by binarywang** [comment]
> 微信登录的不应该放在 微信开放平台：weixin-java-open 里面吗
> 
> 现在在 公众号（包括订阅号和服务号）：weixin-java-mp？

历史遗留问题，这个接口实现比较早，当时还没有开放平台模块，以后考虑open里也放一份。

**Comment by liuweiGL** [comment]
大佬，啥时候更新试下 weixin-java-open，公众号的 oauth2 跟开放平台的 oauth2 支持的能力不一样，开放平台允许使用pc端快速登录。
官方文档：https://developers.weixin.qq.com/doc/oplatform/Website_App/WeChat_Login/Authorized_Interface_Calling_UnionID.html

<img width="729" height="564" alt="Image" src="https://github.com/user-attachments/assets/954d1662-2b13-4028-b5ec-4133dabaec22" />
