### ISSUE TITLE
小程序订阅消息发送总是报错43101

### ISSUE THREAD

**Issue by tianxiajiangshan** [binarywang/WxJava#1387]
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=29__21xslOfbw2jI4TT-7R3K6em3tEeUEdt8SVPrrYe8VrUWqc_nRrmZI1syYHOV2jCm-m-U8vigOY9YVyb0VeZKvX5yczDodMpIQz5NjfWiEjl6HMFfDxV4w0jZiG7rlHbUZIsiM3kMsqHhYyVAWZhAFAOKN
【请求参数】：{"touser":"o4mr30N15Mkp1bJAqCmGU4SOv8As","template_id":"qsWWqh5wHxIMwPXVcrk0x7ctBZ__79-aLRnZp4YbtTI","page":"pages/pinTuanDetail/pinTuanDetail?detailId=263&grouponId=5c262926040f4649a08d3bd66d78dd6f&memberId=148&enterpriseId=154","data":{"thing7":{"value":"沙龙"},"date5":{"value":"2020-01-18 16:18:49.0"},"thing4":{"value":"高峰Elvis"},"character_string10":{"value":"427578039669760"},"thing9":{"value":"请点击查看拼团详情，领取礼券到卡包！"}}}
【错误信息】：错误代码：43101, 错误信息：用户拒绝接受消息，如果用户之前曾经订阅过，则表示用户取消了订阅关系，微信原始报文：{"errcode":43101,"errmsg":"user refuse to accept the msg hint: [dRLzgA04114106]"}

**Comment by mr-xiaoyu** [comment]
这是用户拒绝了订阅消息接收，用户有没有同意订阅？

**Comment by binarywang** [comment]
看消息提示，应该很明确了吧，不知道楼主是否仔细阅读过官方文档？
