### ISSUE TITLE
开放平台模块微信授权事件接收加密字符串解密时如果参数不对可能会导致内存溢出 Java heap space

### ISSUE THREAD

**Issue by IronManCantFix** [binarywang/WxJava#1388]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号:3.4.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
在开放平台模块里的微信授权事件,如果参数不对有时候会导致内存溢出,jvm设置的最大内存已经6g了
代码使用的是demo的例子,如下
![image](https://user-images.githubusercontent.com/11511810/72786587-e8e7eb80-3c68-11ea-925e-61f320d3bdad.png)

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__
![image](https://user-images.githubusercontent.com/11511810/72786552-d8d00c00-3c68-11ea-9273-654ef27c37e8.png)

**Comment by binarywang** [comment]
请尽量按要求描述问题，谢谢
