### ISSUE TITLE
创建自定义菜单出了个异常

### ISSUE THREAD

**Issue by githubxqz** [binarywang/WxJava#139]
调用的接口:
wxMpService.getMenuService().menuCreate( String wxMenuJson);

java.lang.NoSuchMethodError: me.chanjar.weixin.mp.api.WxMpMenuService.menuCreate(Ljava/lang/String;)Ljava/lang/String;

请版主分析下问题,谢谢!!
依赖的mp jar包,2.5.0
weixin-java-common.jar 和weixin-java-mp.jar都存在了,正常不?

**Comment by binarywang** [comment]
这个很不正常，你检查运行时环境里有这个jar包吗？然后再检查下这个类有这个方法吗？

**Comment by githubxqz** [comment]
以下是依赖关系
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ driving-web-wechat ---
[INFO] com.jx.driving:driving-web-wechat:war:0.0.1-SNAPSHOT
[INFO] \- com.github.binarywang:weixin-java-mp:jar:2.5.0:compile
[INFO]    +- com.github.binarywang:weixin-java-common:jar:2.5.0:compile
[INFO]    \- com.github.binarywang:qrcode-utils:jar:1.0:compile

**Comment by binarywang** [comment]
你需要检查你自己的运行时环境，你发的这些信息都是通用的

**Comment by githubxqz** [comment]
问题以解决,新旧版本冲突了.
谢谢!!
