### ISSUE TITLE
有没有gradle的引入方式

### ISSUE THREAD

**Issue by MdcGIt** [binarywang/WxJava#1393]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
gradle的引用方式很简单，你自行查阅maven和它的关系就清楚了。

**Comment by binarywang** [comment]
gradle的引用方式很简单，你自行查阅maven和它的关系就清楚了。

**Comment by yasz** [comment]
不必查阅，在根目录下`gradle init`就可以转换
