### ISSUE TITLE
企业微信-客户联系接口

### ISSUE THREAD

**Issue by Dawn1iu** [binarywang/WxJava#1396]
请问是否有计划支持企业微信外部联系人（客户）管理相关API

`企业内的员工可以添加外企业的联系人进行工作沟通，外部联系人分为企业微信联系人和微信联系人两种类型。
配置了客户联系功能的成员所添加的外部联系人为企业客户。`

官方文档地址：
https://work.weixin.qq.com/api/doc/90000/90135/92109

**Comment by binarywang** [comment]
可以考虑

**Comment by wuji1mol** [comment]
这些接口应该是现在最常用的接口了，希望增加

**Comment by Gyv12345** [comment]
自己实现就行了

**Comment by binarywang** [comment]
3.7.3.B 版本已增加，欢迎使用新版本
