### ISSUE TITLE
spring boot2 引入 wx-java-mp-spring-boot-starter 3.60 后 private StorageType type = memory; 报错

### ISSUE THREAD

**Issue by zhiye** [binarywang/WxJava#1398]
我按照 下面地址配置

https://github.com/Wechat-Group/WxJava/tree/master/spring-boot-starters/wx-java-mp-spring-boot-starter

<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>wx-java-mp-spring-boot-starter</artifactId>
    <version>3.6.0</version>
</dependency>

并在项目中引入了

config	
properties
中文件，修正了文件中包位置
WxMpProperties.java中 第 52行报错

private StorageType type = memory;提示

Type mismatch: cannot convert from com.binarywang.spring.starter.wxjava.mp.properties.WxMpProperties.StorageType to com.zhiye.weixin.mp.properties.WxMpProperties.StorageType

我按springboot提示修改为

private com.binarywang.spring.starter.wxjava.mp.properties.WxMpProperties.StorageType type = memory;

还是无法启动

**Comment by binarywang** [comment]
你是自己copy代码搞混乱了吧
