### ISSUE TITLE
一个服务支撑多个三方平台

### ISSUE THREAD

**Issue by sayid** [binarywang/WxJava#1399]
目前本项目只能支撑一个三方平台，希望能提供多个三方平台的功能。目前我们重写了几个类，达到了此特性，还是希望能在框架中集成进去。

应该会有项目会需要此特性

**Comment by binarywang** [comment]
建议将你的实现方式提交PR上来以供参考

**Comment by binarywang** [comment]
暂时关闭

**Comment by gclsoft** [comment]
@sayid 怎么做到的?
@binarywang 现在修复了吗?
