### ISSUE TITLE
微信支付：企业红包。发送红包的返回结果中，没有签名，不需要进行签名检查。

### ISSUE THREAD

**Issue by hzy2009** [binarywang/WxJava#140]
参考以下xml，是发送红包后返回的xml，不带用sign。不需要进行签名检查，不用抛出不必要的异常。
<xml>
<return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[发放成功]]></return_msg>
<result_code><![CDATA[SUCCESS]]></result_code>
<err_code><![CDATA[SUCCESS]]></err_code>
<err_code_des><![CDATA[发放成功]]></err_code_des>
<mch_billno><![CDATA[131643710120170214S212S1]]></mch_billno>
<mch_id><![CDATA[1316437101]]></mch_id>
<wxappid><![CDATA[wx2840dda77e835ba0]]></wxappid>
<re_openid><![CDATA[oI8-IwCgppnBJzlXvHU4tODnbkwI]]></re_openid>
<total_amount>100</total_amount>
<send_listid><![CDATA[1000041701201702143000036640284]]></send_listid>
</xml>

**Comment by binarywang** [comment]
感谢发现并及时反馈该问题，稍后核实并修复
