### ISSUE TITLE
微信分账查询一直返回签名失败

### ISSUE THREAD

**Issue by zksite** [binarywang/WxJava#1401]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.6.0

### 详细描述
_关于profitSharingQuery一直返回签名错误的问题，是由于微信分账查询接口不需要appid参数，但是在调用profitSharingQuery接口时，方法里checkAndSign会把appid填上。

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
楼主是否看过源码？或者跑过单元测试？如何得出这个结论的

**Comment by binarywang** [comment]
发文格式不对，直接关闭
