### ISSUE TITLE
WxMpService 动态增加配置的两个问题

### ISSUE THREAD

**Issue by silloy** [binarywang/WxJava#1402]
源码 BaseWxMpServiceImpl
```
synchronized (this) {
      if (this.configStorageMap.containsKey(mpId)) {
        throw new RuntimeException("该公众号标识已存在，请更换其他标识！");
      }
      this.configStorageMap.put(mpId, configStorages);
    }
```
1. 如果我更新了配置，appid没有变化，但配置项更新了，我理解这个地方应该是更新的操作而不应该是抛出异常 @chuntaojun ，请问是不是这样
2. configStorageMap 只是一个本地的map，当我动态更新后，只是在本地更新了这个map，如果我部署有多个服务，其他服务就拿不到这个配置，虽然我做了redis持久化，但没有appid，其他服务无法获取相应的配置，有何优化方案 @chuntaojun @binarywang

**Comment by chuntaojun** [comment]
或许可以开一个spi，重新写下这个管理，用户可以覆盖修改，用户自定义持久化或者同步策略，第一个我看下代码

发自我的iPhone

在 2020年2月19日，00:54，S <notifications@github.com> 写道：

﻿

源码 BaseWxMpServiceImpl

synchronized (this) {
      if (this.configStorageMap.containsKey(mpId)) {
        throw new RuntimeException("该公众号标识已存在，请更换其他标识！");
      }
      this.configStorageMap.put(mpId, configStorages);
    }


  1.  如果我更新了配置，appid没有变化，但配置项更新了，我理解这个地方应该是更新的操作而不应该是抛出异常 @chuntaojun<https://github.com/chuntaojun> ，请问是不是这样
  2.  configStorageMap 只是一个本地的map，当我动态更新后，只是在本地更新了这个map，如果我部署有多个服务，其他服务就拿不到这个配置，虽然我做了redis持久化，但没有appid，其他服务无法获取响应的配置，有何优化方案 @chuntaojun<https://github.com/chuntaojun> @binarywang<https://github.com/binarywang>

**Comment by binarywang** [comment]
这两个问题是已经解决了吗？@silloy @chuntaojun

**Comment by silloy** [comment]
问题1 我改了，问题2好像还没有解决 @binarywang

**Comment by binarywang** [comment]
第二个问题确实不方便解决，场景过于复杂，暂时不考虑，如果有更好方案，欢迎直接提交PR
