### ISSUE TITLE
小程序订阅消息发送接口字段名toUser和templateId不正确

### ISSUE THREAD

**Issue by hrwhat** [binarywang/WxJava#1403]
### 简要描述
小程序订阅消息发送接口字段名toUser、templateId不正确，data数据结构不正确

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.6.0, 3.6.9.B

### 详细描述
官方文档是

属性 | 类型 | 默认值 | 必填 | 说明
-- | -- | -- | -- | --
touser | string |   | 是 | 接收者（用户）的 openid
template_id | string |   | 是 | 所需下发的订阅模板id
data | Object |   | 是 | 模板内容，格式形如 { "key1": { "value": any }, "key2": { "value": any } }

而实际发送的报文如下：
```json
 {
  "toUser": "openId",
  "templateId": "templateId",
  "page": "subPages/train/order-detail?id=null",
  "data": [
    {
      "name": "date1",
      "value": ""
    },
    {
      "name": "thing5",
      "value": "xxxxx"
    }
  ]
}
```

**Comment by silloy** [comment]
这个实际请求报文是山寨的吧😂，WxMaSubscribeMessage 里都没有miniprogram_state这个字段，而且我试用过这个接口，没有问题

**Comment by binarywang** [comment]
确实值得可疑，代码里并没有发现相关miniprogram_state相关代码，而且单元测试代码跑出来的请求完全没问题，不知道楼主是咋弄出来的？难道是别人写的代码？

**Comment by binarywang** [comment]
暂时忽略，楼主自己先弄清楚吧

**Comment by hrwhat** [comment]
`miniprogram_state`因为你们这个不支持，是我手工加上去的，有什么问题吗？订阅消息本身就支持这个参数，何必拿这个来说事呢？能正面回答下问题吗？

**Comment by binarywang** [comment]
> `miniprogram_state`因为你们这个不支持，是我手工加上去的，有什么问题吗？订阅消息本身就支持这个参数，何必拿这个来说事呢？能正面回答下问题吗？

其实你也就是改了代码，对吧，然后请发下你的测试代码；
另外请先参考下源码里的单元测试，是没有你说的问题，所以怀疑是你自己改代码改出了问题。

**Comment by binarywang** [comment]
另外关于 `miniprogram_state` 的相关官方文档请发一下，如果确实是缺失参数，可以加一下。

**Comment by hrwhat** [comment]
属性 | 类型 | 默认值 | 必填 | 说明
-- | -- | -- | -- | --
access_token | string |   | 是 | 接口调用凭证
touser | string |   | 是 | 接收者（用户）的 openid
template_id | string |   | 是 | 所需下发的订阅模板id
page | string |   | 否 | 点击模板卡片后的跳转页面，仅限本小程序内的页面。支持带参数,（示例index?foo=bar）。该字段不填则模板无跳转。
data | Object |   | 是 | 模板内容，格式形如 { "key1": { "value": any }, "key2": { "value": any } }
miniprogram_state | string |   | 否 | 跳转小程序类型：developer为开发版；trial为体验版；formal为正式版；默认为正式版
lang | string |   | 否 | 进入小程序查看”的语言类型，支持zh_CN(简体中文)、en_US(英文)、zh_HK(繁体中文)、zh_TW(繁体中文)，默认为zh_CN

**Comment by hrwhat** [comment]
问题找到了，因为转json的时候用到了adapter，我自己加了一个参数导致没找到adapter.
`mniprogram_state`还请麻烦加一下，测试的时候经常要用到体验版，谢谢

**Comment by binarywang** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html

刚看了官方文档，确实是有了，估计是最近新加的，建议新开issue，方便跟踪

**Comment by binarywang** [comment]
#1406 我已新建
