### ISSUE TITLE
BaseWxPayServiceImpl中createOrder的交易类型为JSAPI时签名方法写死为MD5

### ISSUE THREAD

**Issue by yushxzh** [binarywang/WxJava#1405]
### 简要描述
BaseWxPayServiceImpl中createOrder的交易类型为JSAPI时签名方法写死为MD5

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号: 3.6.0

### 详细描述
[ String signType = SignType.MD5;](https://github.com/Wechat-Group/WxJava/blob/13a3f58d1c45126938c29280e7eae3580ae751c1/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/BaseWxPayServiceImpl.java#L324)

### 相关issues
#888

**Comment by binarywang** [comment]
稍后修复

**Comment by binarywang** [comment]
最新正式版3.7.0已修复此问题
