### ISSUE TITLE
微信支付结果通知校验签名错误

### ISSUE THREAD

**Issue by zhouyuan1986** [binarywang/WxJava#1407]
微信支付结果通知格式不是固定的，目前测试发现有概率会带上sign_type字段。但是结果类WxPayOrderNotifyResult源码中并没有这个字段，导致计算签名的时候缺少了这个字段，也就校验失败。

**Comment by binarywang** [comment]
居然有这事，坑爹的

**Comment by binarywang** [comment]
我看了 `WxPayOrderNotifyResult`  源码，是有 `sign_type` 的，不知道我们看到的是不是同一份源码，能否确认下？

**Comment by zhouyuan1986** [comment]
> 我看了 `WxPayOrderNotifyResult` 源码，是有 `sign_type` 的，不知道我们看到的是不是同一份源码，能否确认下？

抱歉，没有提供版本信息，我这边依赖的是3.6.0版本，在这个类以及它的基类里都没找到sign_type字段。而且我看master分支上好像也没有。

**Comment by binarywang** [comment]
请查看develop分支代码

**Comment by binarywang** [comment]
#1330 已修复

**Comment by zhouyuan1986** [comment]
> #1330 已修复

好的，感谢
