### ISSUE TITLE
是否考虑在微信支付模块中新增多商户功能

### ISSUE THREAD

**Issue by jimson-yu** [binarywang/WxJava#1412]
场景，项目中会新增商户，但是不可能每次啊添加商家信息都去修改配置文件中的wx.pay下面的参数，是否可以做成支付接口商户参数都已手动传递，包括证书。之前的证书是硬盘路径或者项目路径，是否可以拓展成网络路径。

**Comment by binarywang** [comment]
证书路径是支持网络路径的。
所谓的配置文件是demo里给你的参考，你不一定需要用到配置文件。
另外关于商户参数，所有接口目前都是支持手动传入的；
而对于证书，如果你是多商户，建议每次调用接口时手动调用config相关方法改变证书参数，然后再调用下init相关方法，就可以，可能实现起来不是很优雅，但应该能部分解决你目前的问题。
