### ISSUE TITLE
行业设置，腾讯官方文档与实际不符，枚举无法干预

### ISSUE THREAD

**Issue by hzdjulytech** [binarywang/WxJava#1413]
### 简要描述
获取微信公众号所属行业，采用了枚举的方式，写死部分无法识别也无法修改，另外腾讯更新或者写法不一致后难以第一时间适应
如
		String json="{\"primary_industry\":{\"first_class\":\"IT科技\",\"second_class\":\"IT软件与服务\"},\"secondary_industry\":{\"first_class\":\"房地产\",\"second_class\":\"房地产|建筑\"}}";
枚举无法正确识别 导致 WxMpIndustryGsonAdapter 中报空指针

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 3.6.0

### 详细描述
 设置所属行业返回内容与腾讯官方文档说的不是一回事，容易出现无法识别情况，建议修改为可外部干预的，避免遇到问题无法修改

本例中 官方文档为  房地产--建筑   实际返回值为   房地产--房地产|建筑
40中每种都试太麻烦
建议在 findBySecondary 方法的末尾 添加 外部识别方法 由使用者自行 处理不能识别的情况

顺带说一句 pom.xml中的地址与当前不符

**Comment by binarywang** [comment]
感谢及时指出，很有可能最开始代码实现的时候没问题，可能后来改了数据内容格式导致现在出问题。

不过这个实现确实有待完善。

> 顺带说一句 pom.xml中的地址与当前不符

另外，这句话是什么意思，能否明确一下？

**Comment by binarywang** [comment]
最新正式版3.7.0版本已修复枚举解析问题

**Comment by binarywang** [comment]
楼主能否抽空验证下目前代码是否已解决你所说的问题？
