### ISSUE TITLE
企业微信获取配置了客户联系功能的成员接口被标记为过时

### ISSUE THREAD

**Issue by roguemaycry** [binarywang/WxJava#1414]
### 简要描述
https://work.weixin.qq.com/api/doc/90000/90135/92571
对应的me.chanjar.weixin.cp.api.WxCpExternalContactService#listFollowUser在新版被标记为过时
是什么原因呢，这个接口还有用啊
### 模块版本情况
* WxJava 模块名: cp
* WxJava 版本号: 3.6.9.b

**Comment by binarywang** [comment]
看了下版本历史，应该是前段时间官方文档把这个接口文档给移除了，导致误以为废弃。
不过现在确实文档又加回来了，那就把deprecated去掉就好了。
