### ISSUE TITLE
 通讯录管理secret

### ISSUE THREAD

**Issue by fufenghua** [binarywang/WxJava#1418]
企业微信获取 通讯录管理secret 以及使用  通讯录管理secret 管理企业微信部门和企业微信用户信息。
目前好像没有

**Comment by binarywang** [comment]
接口？请明确下你的问题

**Comment by fufenghua** [comment]
> 接口？请明确下你的问题

https://qyapi.weixin.qq.com/cgi-bin/department/create?access_token=ACCESS_TOKEN
在使用创建部门 更新部门 删除部门等接口的时候 使用的access_token仍然是应用secret获得的access_token，但这些操作实际上需要通讯录管理的secret获取的access_token

[原文是：使用通讯录管理接口，原则上需要使用 通讯录管理secret，也可以使用 应用secret。
但是使用应用secret只能进行“查询”、“邀请”等非写操作，而且只能操作应用可见范围内的通讯录。]

**Comment by binarywang** [comment]
这个其实涉及到多个应用的问题，你可以参考下demo，根据情况调用不同的应用的接口。

**Comment by binarywang** [comment]
把通讯录做为一个独立的应用即可
