### ISSUE TITLE
菜单反序列化成WxMenu对象时matchRule属性为空

### ISSUE THREAD

**Issue by yiyi910** [binarywang/WxJava#142]
WxMenuGsonAdapter的deserialize方法没有取matchrule字段

**Comment by zhuyanqing927** [comment]
这次对接个性化菜单的时候，查询所有菜单也发现了这个问题。。多谢

**Comment by binarywang** [comment]
me.chanjar.weixin.mp.bean.menu.WxMpMenu
你们用过这个类吗？是专为公众号创建的

**Comment by binarywang** [comment]
感觉你们可能用的是老版本吧？最新版本的实现已经发生了变化

**Comment by zhuyanqing927** [comment]
我在本地调用的是“获得自定义菜单”这个接口。


打印出的日志如下：
获得自定义菜单返回信息：{"menu":{"buttons":[{"type":"view","name":"默认菜单","key":null,"url":"http://www.vphonor.com/","mediaId":null,"subButtons":[]}],"rule":null,"menuId":"414364804"},"conditionalMenu":[{"buttons":[{"type":"view","name":"员工菜单","key":null,"url":"http://www.baidu.com/","mediaId":null,"subButtons":[]}],"rule":{"tagId":null,"sex":null,"country":null,"province":null,"city":null,"clientPlatformType":null,"language":null},"menuId":"414364813"}]}

我的个性化标签是通过tagId绑定的，貌似在rule里面的tagid没有看到具体的值

今天刚好在issue里面看到有人提到这个。。。



zhuyanqing927@126.com
 
发件人： Binary Wang
发送时间： 2017-02-19 17:46
收件人： Wechat-Group/weixin-java-tools
抄送： zhuyanqing927; Comment
主题： Re: [Wechat-Group/weixin-java-tools] 菜单反序列化成WxMenu对象时matchRule属性为空 (#142)
me.chanjar.weixin.mp.bean.menu.WxMpMenu
你们用过这个类吗？是专为公众号创建的

**Comment by zhuyanqing927** [comment]
用的是2.5.0呀



zhuyanqing927@126.com
 
发件人： Binary Wang
发送时间： 2017-02-19 17:55
收件人： Wechat-Group/weixin-java-tools
抄送： zhuyanqing927; Comment
主题： Re: [Wechat-Group/weixin-java-tools] 菜单反序列化成WxMenu对象时matchRule属性为空 (#142)
感觉你们可能用的是老版本吧？最新版本的实现已经发生了变化

**Comment by binarywang** [comment]
我今天特意跑过单元测试，没发现有问题啊，不知道你是如何调用的

**Comment by binarywang** [comment]
在反序列化时已经不再使用WxMenuGsonAdapter了

**Comment by yiyi910** [comment]
发布个性化菜单是调WxMpMenuService的menuCreate(String json)方法对吧

**Comment by binarywang** [comment]
@yiyi910 没错，你的问题到底是什么呢？既然是create，为啥又说到了反序列化的问题？

**Comment by yiyi910** [comment]
那之前调错了，调的是create(WxMenu menu)这个方法，WxMenu是通过fromJson(String json)构建的

**Comment by binarywang** [comment]
调那两个方法创建菜单都没有问题，关键是你要传对了参数

**Comment by yiyi910** [comment]
WxMenu.fromJson(String json)构建个性化菜单WxMenu对象时，matchRule属性为null，我json字符串是有matchrule的

**Comment by binarywang** [comment]
WxMenu属于企业号和公众号共用的menu类，在有个性花菜单的情况下不建议使用。你看下WxMpMenu这个类

**Comment by yiyi910** [comment]
你好, 刚升级到2.5,怎么发现二级菜单是个空集合呢?

**Comment by yiyi910** [comment]
[URL]:  https://api.weixin.qq.com/cgi-bin/menu/get
[PARAMS]: null
[RESPONSE]: {"menu":{"button":[{"type":"view","name":"市场行情","url":"http:\/\/www.baidu.com","sub_button":[]},{"name":"资产及投资","sub_button":[{"type":"view","name":"接收资产列表","url":"http:\/\/www.baidu.com","sub_button":[]},{"type":"view","name":"投资意向设置","url":"http:\/\/www.baidu.com","sub_button":[]},{"type":"view","name":"我的资产","url":"http:\/\/www.baidu.com","sub_button":[]},{"type":"view","name":"增值服务查询","url":"http:\/\/www.baidu.com","sub_button":[]},{"type":"view","name":"投资及交易进程","url":"http:\/\/www.baidu.com","sub_button":[]}]},{"type":"view","name":"我","url":"http:\/\/www.baidu.com","sub_button":[]}]}}
22:30:39.261 [main] INFO  com.vania.MenuTests - 获取-微信自定义菜单：
{"menu":{"button":[{"type":"view","name":"市场行情","url":"http://www.baidu.com","subButtons":[]},{"name":"资产及投资","subButtons":[]},{"type":"view","name":"我","url":"http://www.baidu.com","subButtons":[]}]}}

这是我的日志

**Comment by yiyi910** [comment]
@Test
	public void menuGet() {
		WxMpMenu wxMenu = null;
		// 设置菜单
		try {
			wxMenu = wxMpMenuService.menuGet();
			WxMpConditionalMenu menu = wxMenu.getMenu();
		} catch (WxErrorException e) {
			log.error("获取-微信自定义菜单失败.", e);
		}
		log.info("获取-微信自定义菜单：\n{}", wxMenu.toJson());
	}


这是我的case

**Comment by binarywang** [comment]
你最好对照下项目中的单元测试看下是哪儿的问题吧

**Comment by yiyi910** [comment]
我跑工程里WxMpMenuServiceImplTest类的testMenuGet   这个name为"菜单"的一级菜单subButtons确实为空集合.  附上日志:

**Comment by yiyi910** [comment]
Method public java.lang.Object[][] me.chanjar.weixin.mp.api.impl.WxMpMenuServiceImplTest.getMenu() has a @Test annotation but also a return value: ignoring it. Use <suite allow-return-values="true"> to fix this
[TestNG] Running:
  C:\Users\vania\AppData\Local\Temp\testng-eclipse--1642397105\testng-customsuite.xml

{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]}
00:41:44.230 [main] DEBUG m.c.w.m.api.impl.WxMpMenuServiceImpl - 开始创建菜单：{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]}
00:41:45.308 [main] DEBUG m.c.w.mp.api.impl.WxMpServiceImpl - 
[URL]:  https://api.weixin.qq.com/cgi-bin/menu/create
[PARAMS]: {"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]}
[RESPONSE]: {"errcode":0,"errmsg":"ok"}
00:41:45.308 [main] DEBUG m.c.w.m.api.impl.WxMpMenuServiceImpl - 创建菜单：{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]},结果：{"errcode":0,"errmsg":"ok"}
00:41:51.546 [main] DEBUG m.c.w.mp.api.impl.WxMpServiceImpl - 
[URL]:  https://api.weixin.qq.com/cgi-bin/menu/get
[PARAMS]: null
[RESPONSE]: {"menu":{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC","sub_button":[]},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER","sub_button":[]},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http:\/\/www.soso.com\/","sub_button":[]},{"type":"view","name":"视频","url":"http:\/\/v.qq.com\/","sub_button":[]},{"type":"click","name":"赞一下我们","key":"V1001_GOOD","sub_button":[]}]}]}}
{"menu":{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC","subButtons":[]},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER","subButtons":[]},{"name":"菜单","subButtons":[]}]}}
PASSED: testMenuCreate(WxMenu[
  buttons=[WxMenuButton[
  type=click
  name=今日歌曲
  key=V1001_TODAY_MUSIC
  subButtons=[]
], WxMenuButton[
  type=click
  name=歌手简介
  key=V1001_TODAY_SINGER
  subButtons=[]
], WxMenuButton[
  name=菜单
  subButtons=[WxMenuButton[
  type=view
  name=搜索
  url=http://www.soso.com/
  subButtons=[]
], WxMenuButton[
  type=view
  name=视频
  url=http://v.qq.com/
  subButtons=[]
], WxMenuButton[
  type=click
  name=赞一下我们
  key=V1001_GOOD
  subButtons=[]
]]
]]
])
PASSED: testMenuGet

===============================================
    Default test
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@6295d394: 34 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@78b1cc93: 12 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@7c417213: 4 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@3bd40a57: 3 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@5e4c8041: 3 ms

**Comment by yiyi910** [comment]
Method public java.lang.Object[][] me.chanjar.weixin.mp.api.impl.WxMpMenuServiceImplTest.getMenu() has a @Test annotation but also a return value: ignoring it. Use <suite allow-return-values="true"> to fix this
[TestNG] Running:
  C:\Users\vania\AppData\Local\Temp\testng-eclipse--1642397105\testng-customsuite.xml

{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]}
00:41:44.230 [main] DEBUG m.c.w.m.api.impl.WxMpMenuServiceImpl - 开始创建菜单：{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]}
00:41:45.308 [main] DEBUG m.c.w.mp.api.impl.WxMpServiceImpl - 
[URL]:  https://api.weixin.qq.com/cgi-bin/menu/create
[PARAMS]: {"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]}
[RESPONSE]: {"errcode":0,"errmsg":"ok"}
00:41:45.308 [main] DEBUG m.c.w.m.api.impl.WxMpMenuServiceImpl - 创建菜单：{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC"},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER"},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http://www.soso.com/"},{"type":"view","name":"视频","url":"http://v.qq.com/"},{"type":"click","name":"赞一下我们","key":"V1001_GOOD"}]}]},结果：{"errcode":0,"errmsg":"ok"}
00:41:51.546 [main] DEBUG m.c.w.mp.api.impl.WxMpServiceImpl - 
[URL]:  https://api.weixin.qq.com/cgi-bin/menu/get
[PARAMS]: null
[RESPONSE]: {"menu":{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC","sub_button":[]},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER","sub_button":[]},{"name":"菜单","sub_button":[{"type":"view","name":"搜索","url":"http:\/\/www.soso.com\/","sub_button":[]},{"type":"view","name":"视频","url":"http:\/\/v.qq.com\/","sub_button":[]},{"type":"click","name":"赞一下我们","key":"V1001_GOOD","sub_button":[]}]}]}}
{"menu":{"button":[{"type":"click","name":"今日歌曲","key":"V1001_TODAY_MUSIC","subButtons":[]},{"type":"click","name":"歌手简介","key":"V1001_TODAY_SINGER","subButtons":[]},{"name":"菜单","subButtons":[]}]}}
PASSED: testMenuCreate(WxMenu[
  buttons=[WxMenuButton[
  type=click
  name=今日歌曲
  key=V1001_TODAY_MUSIC
  subButtons=[]
], WxMenuButton[
  type=click
  name=歌手简介
  key=V1001_TODAY_SINGER
  subButtons=[]
], WxMenuButton[
  name=菜单
  subButtons=[WxMenuButton[
  type=view
  name=搜索
  url=http://www.soso.com/
  subButtons=[]
], WxMenuButton[
  type=view
  name=视频
  url=http://v.qq.com/
  subButtons=[]
], WxMenuButton[
  type=click
  name=赞一下我们
  key=V1001_GOOD
  subButtons=[]
]]
]]
])
PASSED: testMenuGet

===============================================
    Default test
    Tests run: 2, Failures: 0, Skips: 0
===============================================


===============================================
Default suite
Total tests run: 2, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@6295d394: 34 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@78b1cc93: 12 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@7c417213: 4 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@3bd40a57: 3 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@5e4c8041: 3 ms

**Comment by wangjia2016** [comment]
@yiyi910 
 这个name为"菜单"的一级菜单subButtons确实为空集合. 

我这也发现了这个问题，的确为空，不过我暂时还没用到个性化菜单


![qq 20170314092844](https://cloud.githubusercontent.com/assets/16084076/23881954/b11504f6-0898-11e7-9271-805e3d7e700d.png)

**Comment by binarywang** [comment]
感谢二位细心调试，我也试了下，确实是有问题，稍后修复下。
