### ISSUE TITLE
调用wxMpService.getUserService().userInfo　获取微信用户信息需要3S时间

### ISSUE THREAD

**Issue by springwarms** [binarywang/WxJava#1421]
调用wxMpService.getUserService().userInfo　获取微信用户信息需要3S时间　用微信工具是毫秒级别请问这是哪里有问题

**Comment by binarywang** [comment]
楼主是否跑过单元测试代码：`me.chanjar.weixin.mp.api.impl.WxMpUserServiceImplTest#testUserInfo`
测试结果确实是毫秒级别的

**Comment by binarywang** [comment]
没有响应，暂时关闭
