### ISSUE TITLE
开放平台WxOpenServiceAbstractImpl.Executor() synchronized严重影响系统吞吐量

### ISSUE THREAD

**Issue by ZTielong** [binarywang/WxJava#1424]
系统对微信的请求依赖本出口，微信接口响应慢，用户流量高峰时，系统锁等待导致线程池耗尽，应用雪崩。
protected synchronized <T, E> T execute(RequestExecutor<T, E> executor, String uri, E data) throws WxErrorException {
    try {
      T result = executor.execute(uri, data);
      this.log.debug("\n【请求地址】: {}\n【请求参数】：{}\n【响应数据】：{}", uri, data, result);
      return result;
    } catch (WxErrorException e) {
      WxError error = e.getError();
      if (error.getErrorCode() != 0) {
        this.log.error("\n【请求地址】: {}\n【请求参数】：{}\n【错误信息】：{}", uri, data, error);
        throw new WxErrorException(error, e);
      }
      return null;
    } catch (IOException e) {
      this.log.error("\n【请求地址】: {}\n【请求参数】：{}\n【异常信息】：{}", uri, data, e.getMessage());
      throw new RuntimeException(e);
    }
  }

**Comment by binarywang** [comment]
楼主有什么好的改进办法没？

**Comment by binarywang** [comment]
@007gzs 有什么想法没？

**Comment by binarywang** [comment]
3.7.5.B 测试版本已优化
