### ISSUE TITLE
cpoa bug

### ISSUE THREAD

**Issue by spafka** [binarywang/WxJava#1425]
### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名:  wxcp
* WxJava 版本号: 3.7.0

### 详细描述

WxCpApprovalDetail.java 
    /**
     * 审批流程信息，可能有多个审批节点
     */
    @SerializedName("sp_record")
    private WxCpApprovalRecord[] spRecord;

    /**
     * 抄送信息，可能有多个抄送节点
     */
    @SerializedName("notifyer")
    private WxCpOperator[] notifyer;

因为是多个节点，所以应该为数组或list，

@Data
public class ContentValue implements Serializable {

    private static final long serialVersionUID = -5607678965965065261L;

    private String text;

    @SerializedName("new_number")
    private Integer newNumber;

    @SerializedName("new_money")
    private Double newMoney;

newMoney 经测试可有小数点
### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by spafka** [comment]
newNumber 也有小数点 ，timestamp 竟然也有

**Comment by binarywang** [comment]
你这个标题里的cpoa ，不进来看还真不知道说的啥

**Comment by binarywang** [comment]
3.7.1.B版本已修复，欢迎试用
