### ISSUE TITLE
是否能增加小程序直播类相关接口？

### ISSUE THREAD

**Issue by kangbin0203** [binarywang/WxJava#1429]
官方文档地址：https://docs.qq.com/doc/DZHhzV0FiYXRQV01i

**Comment by binarywang** [comment]
看起来就两个接口，实现起来比较简单，而且你如果有账号而且比较紧急的话，可以自行实现，然后提交PR。否则可能得等一段时间了

**Comment by yjwang3300300** [comment]
相关代码已经提交PR了

**Comment by binarywang** [comment]
> 相关代码已经提交PR了

感谢提供的代码

**Comment by gguan** [comment]
解析返回的live_status为null，可否看一下是什么问题

**Comment by binarywang** [comment]
> 解析返回的live_status为null，可否看一下是什么问题

看文档里的接口响应示例里使用的是这个 live_satus，看样子是写错了

**Comment by yjwang3300300** [comment]
官方文档写的返回值（live_satus），可能微信开发小哥写错了。

**Comment by yjwang3300300** [comment]
> > 解析返回的live_status为null，可否看一下是什么问题
> 
> 看文档里的接口响应示例里使用的是这个 live_satus，看样子是写错了

官方文档写的返回值（live_satus），可能微信开发小哥写错了。

**Comment by yjwang3300300** [comment]
修复官方文档live_satus字段拼错问题，调整为live_status

**Comment by binarywang** [comment]
3.7.6.B 测试版本已添加相关接口；
字段问题单独issue处理
