### ISSUE TITLE
能否支持企业号独有的mpnews消息类型

### ISSUE THREAD

**Issue by sn7788** [binarywang/WxJava#143]
相关文档连接

[mpnews消息](http://qydev.weixin.qq.com/wiki/index.php?title=%E6%B6%88%E6%81%AF%E7%B1%BB%E5%9E%8B%E5%8F%8A%E6%95%B0%E6%8D%AE%E6%A0%BC%E5%BC%8F#mpnews.E6.B6.88.E6.81.AF)

**Comment by binarywang** [comment]
如果可以请帮忙实现下，因为目前做企业号的并不多，还是希望有相应开发环境的同学帮忙添加下相关功能了。

**Comment by binarywang** [comment]
正在实现中

**Comment by binarywang** [comment]
@sn7788  已完成，请等待下一版本发布即可使用。
