### ISSUE TITLE
请问一下redis,可以配置密码吗?

### ISSUE THREAD

**Issue by cathylogs** [binarywang/WxJava#1431]
请问一下redis,可以配置密码吗?

**Comment by binarywang** [comment]
当然可以，你自己配置即可

**Comment by cathylogs** [comment]
好像没有



---原始邮件---
发件人: "Binary Wang"<notifications@github.com&gt;
发送时间: 2020年3月12日(周四) 晚上6:16
收件人: "Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送: "都是夜归人"<972934564@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Wechat-Group/WxJava] 请问一下redis,可以配置密码吗? (#1431)




 
Closed #1431.

**Comment by binarywang** [comment]
自己配置
