### ISSUE TITLE
微信支付查询结果类缺少几个参数

### ISSUE THREAD

**Issue by threeMango** [binarywang/WxJava#1435]
### 简要描述
WxPayOrderQueryResult  下缺少 subOpenId
代理商模块

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_2

**Comment by binarywang** [comment]
谢谢及时反馈，已修复，等待发布新版本

**Comment by binarywang** [comment]
3.7.2.B版本已增加
