### ISSUE TITLE
偶尔出现DefaultApacheHttpClientBuilder.prepare()报OutOfMemoryError

### ISSUE THREAD

**Issue by tenonersoft** [binarywang/WxJava#144]
在调用 getOauth2buildAuthorizationUrl的时候报这个错误。望帮忙解决，谢谢
![image](https://cloud.githubusercontent.com/assets/23117482/23288569/66b82806-fa7f-11e6-9d8c-a2a44d28a99e.png)

**Comment by binarywang** [comment]
OutOfMemoryError  这种错误一般是你自己JVM虚拟机的设置问题吧

**Comment by tenonersoft** [comment]
@binarywang 不是呢。其他一切正常可访问可操作。就是需要微信登录（具体是执行getOauth2buildAuthorizationUrl的时候）才会出错

**Comment by bysunexus** [comment]
请保持 WxMpServiceImpl单例

**Comment by tenonersoft** [comment]
@kakotor WxMpServiceImpl需要单例吗？目前的确不是单例

**Comment by tenonersoft** [comment]
@kakotor @binarywang 感觉上和以下这个问题是同一个问题，也是在DefaultApacheHttpClientBuilder的prepare方法。 https://github.com/Wechat-Group/weixin-java-tools/issues/52
我用的版本是2.4.0。是不是升级了就解决了这个问题呢？目前生产环境在使用，比较着急。谢谢你们的帮助。

**Comment by binarywang** [comment]
确实如果不是单例的话，容易出问题，请先考虑下你的使用方式。#52 看样子应该是在2.3.0版本里已经加入了

**Comment by tenonersoft** [comment]
@binarywang 我已经改为单例了，先运行一段时间看有没有问题。谢谢你们的帮忙

**Comment by bysunexus** [comment]
WxMpServiceImpl 在初始化的时候会初始化httpclient的连接池以及一些其他的资源.从设计上看来WxMpServiceImpl 应该是保持单例的

**Comment by tenonersoft** [comment]
@kakotor 谢谢，已改为单例。目前运行正常。
