### ISSUE TITLE
OrderResult几个bean没有无参构造方法

### ISSUE THREAD

**Issue by jiffzuo** [binarywang/WxJava#1443]
#1372 # 简要描述
OrderResult几个bean没有无参构造方法，导致一些系列化工具无法转换

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.7.0

**Comment by binarywang** [comment]
跟#1372有啥关系？

**Comment by binarywang** [comment]
准备加上默认无参构造方法，不过这个跟#1372有啥关系

**Comment by binarywang** [comment]
3.7.3.B 版本已添加，欢迎使用新版本
