### ISSUE TITLE
付款码，支付字段receipt 不是必传，传类com.github.binarywang.wxpay.bean.request.WxPayMicropayRequest中字段上加了  @Required

### ISSUE THREAD

**Issue by ln0491** [binarywang/WxJava#1445]
电子发票入口开放标识 | receipt | 否 | String(8) | Y | Y，传入Y时，支付成功消息和支付详情页将出现开票入口。需要在微信支付商户平台或微信公众平台开通电子发票功能，传此字段才可生效

com.github.binarywang.wxpay.bean.request.WxPayMicropayRequest

 /**
   * <pre>
   * 字段名：电子发票入口开放标识	.
   * 变量名：receipt
   * 是否必填：否
   * 类型：String(8)
   * 示例值：Y
   * 描述：Y，传入Y时，支付成功消息和支付详情页将出现开票入口。需要在微信支付商户平台或微信公众平台开通电子发票功能，传此字段才可生效
   * </pre>
   **/
  @Required
  @XStreamAlias("receipt")
  private String receipt;
如果不传支付时会报
com.github.binarywang.wxpay.exception.WxPayException: 必填字段 [receipt] 必须提供值

将注解@Required去掉就OK，要么默认设置 为"N"

**Comment by binarywang** [comment]
稍后进行修复

**Comment by binarywang** [comment]
3.7.3.B 版本已修复，欢迎使用新版本
