### ISSUE TITLE
付款码支付没有将分账字段profitSharing加入签名参数

### ISSUE THREAD

**Issue by yzuzhanghui** [binarywang/WxJava#1452]
付款码支付请求WxPayMicropayRequest的storeMap方法没有将分账字段profitSharing包含在内

@XStreamAlias("profit_sharing")
  private String profitSharing;

  @Override
  protected void checkConstraints() {
    //do nothing
  }

  @Override
  protected void storeMap(Map<String, String> map) {
    map.put("version", version);
    map.put("body", body);
    map.put("detail", detail);
    map.put("attach", attach);
    map.put("out_trade_no", outTradeNo);
    map.put("total_fee", totalFee.toString());
    map.put("fee_type", feeType);
    map.put("spbill_create_ip", spbillCreateIp);
    map.put("goods_tag", goodsTag);
    map.put("limit_pay", limitPay);
    map.put("time_start", timeStart);
    map.put("time_expire", timeExpire);
    map.put("auth_code", authCode);
    map.put("scene_info", sceneInfo);
  }

**Comment by binarywang** [comment]
稍后加上

**Comment by binarywang** [comment]
其实这种简单的问题可以直接提交PR了

**Comment by binarywang** [comment]
3.7.3.B 版本已修复，欢迎使用新版本
