### ISSUE TITLE
员工管理JSON结构体存在较大差异

### ISSUE THREAD

**Issue by yoking-zhang** [binarywang/WxJava#1456]
员工管理JSON结构体存在较大差异
https://work.weixin.qq.com/api/doc/90000/90135/90194

错误属性：
extattr
丢失属性：
external_position， external_profile->external_corp_name

**Comment by binarywang** [comment]
看来是官方接口做了调整

**Comment by binarywang** [comment]
3.7.3.B 版本已修复，欢迎使用新版本
