### ISSUE TITLE
查询分账结果请求参数中 sub_appid 不需要

### ISSUE THREAD

**Issue by cooiky** [binarywang/WxJava#1463]
### 简要描述
ProfitSharingQueryRequest 中忽略了 appid，但对 sub_appid 没有进行忽略

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/allocation_sl.php?chapter=25_2&index=3

**Comment by binarywang** [comment]
稍后处理下

**Comment by binarywang** [comment]
3.7.4.B版本已修复
