### ISSUE TITLE
企业微信，员工信息同步，英文名称同步到别名去了

### ISSUE THREAD

**Issue by duan5623805** [binarywang/WxJava#1467]
企业微信，员工信息同步，英文名称是有值的，别名是null，同步过去之后，
在企业微信后台，看到别名有值，显示的是我设置的英文名称的值，
英文名称是未设置；
应该是同步的接口把两个字段搞反了。

**Comment by binarywang** [comment]
根据私下讨论情况，为官方接口定义问题，关闭此issue
