### ISSUE TITLE
企业号微信刷新 ticket 时候报错

### ISSUE THREAD

**Issue by liujiaxian** [binarywang/WxJava#1468]
![image](https://user-images.githubusercontent.com/15668976/77416596-ffdcc280-6dfe-11ea-8e26-da72c53f3477.png)

![image](https://user-images.githubusercontent.com/15668976/77416732-387c9c00-6dff-11ea-8602-ac71033517e3.png)

接收到请求消息，内容：{
  "allFieldsMap" : {
    "SuiteTicket" : "0QODnK5Iqol8gnTY9C0E8MQFHxCTg-jNBgXzrTNnlnui6tnQmUI9YeXBcPSp5_zC",
    "SuiteId" : "ww3adba528e6256ede",
    "InfoType" : "suite_ticket",
    "TimeStamp" : "1585046305"
  },
  "extAttrs" : {
    "items" : [ ]
  },
  "scanCodeInfo" : { },
  "sendPicsInfo" : {
    "picList" : [ ]
  },
  "sendLocationInfo" : { }
}

返回的内容 msgType 为 Null

**Comment by roguemaycry** [comment]
应该把xml转成map 取InfoType判断是否等于suite_ticket 推送ticket事件不传msgtype

**Comment by binarywang** [comment]
你这是demo里的代码，这个事件比较特殊，自己改代码即可

**Comment by binarywang** [comment]
按楼上所说，你自己获取allFieldsMap里的InfoType进行判断即可
