### ISSUE TITLE
为什么WxMpServiceImpl类中的executeInternal方法需要声明synchronized同步

### ISSUE THREAD

**Issue by liuluo129** [binarywang/WxJava#147]
这样多线程调用微信API的时候会被block住，影响发送速度

**Comment by binarywang** [comment]
https://github.com/chanjarster/weixin-java-tools/issues/323 
https://github.com/Wechat-Group/weixin-java-tools/issues/23
应该跟这两个问题属于同一问题，你先看看文中讨论是否能解决你的问题吧
