### ISSUE TITLE
企业微信 缺少客户联系「联系我」管理接口

### ISSUE THREAD

**Issue by yoking-zhang** [binarywang/WxJava#1474]
### 客户联系「联系我」管理
配置客户联系「联系我」方式: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/add_contact_way?access_token=ACCESS_TOKEN
获取企业已配置的「联系我」方式: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_contact_way?access_token=ACCESS_TOKEN
更新企业已配置的「联系我」方式: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/update_contact_way?access_token=ACCESS_TOKEN
删除企业已配置的「联系我」方式: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/del_contact_way?access_token=ACCESS_TOKEN
结束临时会话: https://qyapi.weixin.qq.com/cgi-bin/externalcontact/close_temp_chat?access_token=ACCESS_TOKEN

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/92572

**Comment by Liiaming** [comment]
如果发布了, 会有通知吗

**Comment by binarywang** [comment]
会的，请注意关注WxJava微信公众号及时查收相关版本发布情况

**Comment by einsitang** [comment]
有人开发吗，没有的话，我最近有空可以将帮忙写上这些接口，只是这类型接口真的有人用吗[疑问？]

**Comment by binarywang** [comment]
新发布版本即将支持
