### ISSUE TITLE
优化云数据库CRUD操作

### ISSUE THREAD

**Issue by skywsp** [binarywang/WxJava#1476]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
`
1、WxMaDefaultConfigImpl新增两个环境变量originalId（小程序原始ID），cloudEnv（云环境ID）
2、WxMaCloudServiceImpl优化了云数据库增删改查
`

### 官方文档地址
`
微信小程序云数据库api:
https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-sdk-api/database/Collection.html
`

**Comment by binarywang** [comment]
感谢提交的PR

**Comment by binarywang** [comment]
3.7.4.B版本已包含上述优化代码
