### ISSUE TITLE
WxMpCurrentAutoReplyInfo这个类怎么用？有没有相关的文档

### ISSUE THREAD

**Issue by TonyLiuYan** [binarywang/WxJava#1477]
WxMpCurrentAutoReplyInfo这个类怎么用？有没有相关的文档！谢谢！

**Comment by binarywang** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Getting_Rules_for_Auto_Replies.html

参考对应接口的官方文档即可
