### ISSUE TITLE
微信小店API封装

### ISSUE THREAD

**Issue by skywsp** [binarywang/WxJava#1479]
### 简要描述
微信公众平台本次更新增加了微信小店功能，微信小店基于微信支付，包括添加商品、商品管理、订单管理、货架管理、维权等功能。

开发者可以通过小店接口来实现快速开店，目前支持以下接口：

1、商品管理接口

开发者可通过商品管理接口，来增加商品、删除商品、修改商品信息、查询已有商品，并可通过接口对商品进行上下架等操作管理。

2、库存管理接口

开发者可通过库存管理接口，来为已有商品增加和减少库存，包括进行与自身系统或其他平台的库存同步。

3、邮费模板管理接口

对于部分邮费计算复杂的商品，开发者可通过邮费模板管理接口，来生成、修改、删除和查询支持复杂邮费计算的邮费模板。

4、分组管理接口

对已有商品，开发者可通过分组管理接口，来对商品进行分组管理。接口包括增加、删除、修改和查询分组。

5、货架管理接口

微信商户除了可以在公众平台网站中自定义货架外，也可通过接口来增加、删除、修改和查询货架。货架也是通过控件来组成的。开发者甚至可以将自己的页面作为货架，通过JS API来调起商品详情页。

6、订单管理接口

开发者可按订单状态和时间来获取订单，并对订单进行发货。

7、功能接口

目前功能接口暂时只支持上传图片接口一项。微信商户开发接口中所有需要用到图片的地方，都需先使用上传图片接口来预先获得图片的URL。

请点击下载微信小店接口文档：[下载](https://res.wx.qq.com/op_res/fHB4pH8ShJ6T2s3H5NN8QuVA0jgtXT4GSn1Qz7qBy6Sy-MNv31EHLEDhOcBIlyvd)

### 官方文档地址
`
https://developers.weixin.qq.com/doc/offiaccount/Instant_Stores/WeChat_Store_Interface.html
`

**Comment by binarywang** [comment]
期待楼主的代码

**Comment by wenhui-prudencemed** [comment]
微信使用小商店替换了微信小店，希望增加对微信小店的支持

**Comment by kelvenlaw** [comment]
请问会对微信小商店进行支持吗？期待中。。。。

**Comment by binarywang** [comment]
暂无可用账号，希望有相关账号权限的小伙伴能够丰衣足食，自己动手实现，并提交PR
