### ISSUE TITLE
企业微信第三方应用开发是否支持有限？

### ISSUE THREAD

**Issue by ToyDelusion** [binarywang/WxJava#1480]
# 目前使用cp工具包开发是否需要自定义如：常量池、handle路由、wxCpConfigStorage之类的？

### 官方文档地址
关于InfoType、ChangeType事件，主要参考企业微信的第三方应用开发回调事件：
https://open.work.weixin.qq.com/api/doc/90001/90143/92654

关于suiteId、suiteSecret：
https://work.weixin.qq.com/api/doc/10975#获取第三方应用凭证

**Comment by binarywang** [comment]
有专门的实现，注意看WxCpTpService相关类
