### ISSUE TITLE
40001 无限递归内存溢出

### ISSUE THREAD

**Issue by lehman-china** [binarywang/WxJava#1481]
### 简要描述
40001 无限递归内存溢出,  (密钥错误时40001)

### 模块版本情况
* WxJava 模块名:  weixin-java-mp
* WxJava 版本号: 3.7.0

### 详细描述
executeInternal 40001 时,调用 execute, execute又马上调用 executeInternal ;调用死循环了;
希望优化下, 42001,40001,40014 这几个错误码重试次数的限制;

代码如下:
protected <T, E> T executeInternal(RequestExecutor<T, E> executor, String uri, E data) throws WxErrorException {
    .......
      if (error.getErrorCode() == 42001 || error.getErrorCode() == 40001 || error.getErrorCode() == 40014) {
.....
        if (this.getWxMpConfigStorage().autoRefreshToken()) {
          return this.execute(executor, uri, data);
        }
      }
......
  }

  public <T, E> T execute(RequestExecutor<T, E> executor, String uri, E data) throws WxErrorException {
....
        return this.executeInternal(executor, uri, data);
.....

### 日志
无日志

**Comment by binarywang** [comment]
你有什么好的优化建议？

**Comment by binarywang** [comment]
我仔细看了下代码，如果AppSecret错误，那么程序在getAccessToken时就会直接抛出异常，不会走到下面的代码，可否再次确认下你的问题出现的场景？

**Comment by lehman-china** [comment]
哦  这边是远程获取 accessToken. 才造成这个问题.   是我自己的问题.
