### ISSUE TITLE
异常包装

### ISSUE THREAD

**Issue by yuexiang1988** [binarywang/WxJava#1482]
WxMaServiceImpl#execute方法内捕获executeInternal方法抛出的WxErrorException异常，然后抛出RuntimeException("微信服务端异常，超出重试次数")，这样拿不到调用微信返回的错误码。业务有需要根据微信返回码做逻辑处理的。可以把返回码暴露给外层吗

**Comment by binarywang** [comment]
服务器端异常返回码就是-1，你看代码就可以知道了。
不过也可以考虑把微信的原始返回通过WxErrorException的形式抛出来。

**Comment by binarywang** [comment]
3.7.5.B 测试版本已优化
