### ISSUE TITLE
企业微信接口，获取审批申请详情（getApprovalDetail）报错

### ISSUE THREAD

**Issue by sandyisone** [binarywang/WxJava#1484]
### 简要描述
企业微信接口，获取审批申请详情（getApprovalDetail）报错

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 3.7.0

### 详细描述
 最新企业微信调用获取审批申请详情接口，微信返回值WxCpApprovalDetailResult.info中字段：spRecord（审批流程信息，可能有多个审批节点）、notifyer（抄送信息，可能有多个抄送节点）已经变为为List类型，故会报错。

最新文档示例：
{
    "errcode": 0,
    "errmsg": "ok",
    "info": {
        "sp_no": "201909270002",
        "sp_name": "全字段",
        "sp_status": 1,
        "template_id": "Bs5KJ2NT4ncf4ZygaE8MB3779yUW8nsMaJd3mmE9v",
        "apply_time": 1569584428,
        "applyer": {
            "userid": "WuJunJie",
            "partyid": "2"
        },
        "sp_record": [{
            "sp_status": 1,
            "approverattr": 1,
            "details": [{
                    "approver": {
                        "userid": "WuJunJie"
                    },
                    "speech": "",
                    "sp_status": 1,
                    "sptime": 0,
                    "media_id": []
                },
                {
                    "approver": {
                        "userid": "WangXiaoMing"
                    },
                    "speech": "",
                    "sp_status": 1,
                    "sptime": 0,
                    "media_id": []
                }
            ]
        }],
        "notifyer": [{
            "userid": "LiuXiaoGang"
        }],
        "apply_data": {
            "contents": [{
                "control": "Text",
                "id": "Text-15111111111",
                "title": [{
                    "text": "文本控件",
                    "lang": "zh_CN"
                }],
                "value": {
                    "text": "文本填写的内容",
                    "tips": [],
                    "members": [],
                    "departments": [],
                    "files": [],
                    "children": [],
                    "stat_field": []
                }
            }]
        },
        "comments": [{
            "commentUserInfo": {
                "userid": "WuJunJie"
            },
            "commenttime": 1569584111,
            "commentcontent": "这是备注信息",
            "commentid": "6741314136717778040",
            "media_id": [
                "WWCISP_Xa1dXIyC9VC2vGTXyBjUXh4GQ31G-a7jilEjFjkYBfncSJv0kM1cZAIXULWbbtosVqA7hprZIUkl4GP0DYZKDrIay9vCzeQelmmHiczwfn80v51EtuNouzBhUBTWo9oQIIzsSftjaVmd4EC_dj5-rayfDl6yIIRdoUs1V_Gz6Pi3yH37ELOgLNAPYUSJpA6V190Xunl7b0s5K5XC9c7eX5vlJek38rB_a2K-kMFMiM1mHDqnltoPa_NT9QynXuHi"
            ]
        }]
    }
}

### 日志
获取审批数据异常java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 245

**Comment by binarywang** [comment]
#1425 已修复，请使用最新测试版本
