### ISSUE TITLE
对于普遍存在 Illegal key size 异常， 建议更换bcprov-jdk15on库代替原生加解密

### ISSUE THREAD

**Issue by shuaisheng** [binarywang/WxJava#1492]

**Comment by binarywang** [comment]
欢迎直接提供PR代码

**Comment by Kylelkh** [comment]
@shuaisheng 我了解到的解决方案有两种：
1.设置设置key的长度为16个字母和数字的字符串（128 Bit/8=16字符）就不报错了。
2.替换jdk jar包
请问，这个问题是如何解决的呢?不知道你提到的方式是否有更优雅？
