### ISSUE TITLE
微信消息发送添加评论关闭开启功能

### ISSUE THREAD

**Issue by kevinBobo** [binarywang/WxJava#1497]
微信官方的图文消息有评论开启和只允许粉丝评论的开关,但是sdk里面的设置里面没有找到呢?

### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Batch_Sends_and_Originality_Checks.html#2

**Comment by binarywang** [comment]
你搜索过源码没？这个早就支持的了

**Comment by kevinBobo** [comment]
你好,这是最新源码的群发文章实体的截图,确实是没有的,我搜了一下好想有个返回类里面有这两个属性


--- 图片已删除 by binrywang----

**Comment by kevinBobo** [comment]
/**
   * <pre>
   * 群发图文消息article.
   * 1. thumbMediaId  (必填) 图文消息缩略图的media_id，可以在基础支持-上传多媒体文件接口中获得
   * 2. author          图文消息的作者
   * 3. title           (必填) 图文消息的标题
   * 4. contentSourceUrl 在图文消息页面点击“阅读原文”后的页面链接
   * 5. content (必填)  图文消息页面的内容，支持HTML标签
   * 6. digest          图文消息的描述
   * 7, showCoverPic  是否显示封面，true为显示，false为不显示
   * </pre>
   *
   * @author chanjarster
   */
  @Data
  public static class WxMpMassNewsArticle {
    /**
     * (必填) 图文消息缩略图的media_id，可以在基础支持-上传多媒体文件接口中获得.
     */
    private String thumbMediaId;
    /**
     * 图文消息的作者.
     */
    private String author;
    /**
     * (必填) 图文消息的标题.
     */
    private String title;
    /**
     * 在图文消息页面点击“阅读原文”后的页面链接.
     */
    private String contentSourceUrl;
    /**
     * (必填) 图文消息页面的内容，支持HTML标签.
     */
    private String content;
    /**
     * 图文消息的描述.
     */
    private String digest;
    /**
     * 是否显示封面，true为显示，false为不显示.
     */
    private boolean showCoverPic;

    @Override
    public String toString() {
      return WxMpGsonBuilder.create().toJson(this);
    }
  }

**Comment by binarywang** [comment]
那你其实标题写错了，目前代码里群发的跟普通发送的消息不一样，这个我看怎么优化统一下

**Comment by kevinBobo** [comment]
哦,可能描述的不太正确,不好意思
目前我自己添加了一下字段,打了个私包用
希望下个版本可以加上这两个字段

**Comment by binarywang** [comment]
3.7.7.B版本已添加
