### ISSUE TITLE
微信文档客服添加改了，框架相应的实体没有进行改变

### ISSUE THREAD

**Issue by wchCoding** [binarywang/WxJava#150]
WxMpKfAccountRequest这个类里面的属性要改，改成password
对应文档位置：https://mp.weixin.qq.com/wiki/18/749901f4e123170fb8a4d447ae6040ba.html#.E6.B7.BB.E5.8A.A0.E5.AE.A2.E6.9C.8D.E8.B4.A6.E5.8F.B7

**Comment by binarywang** [comment]
@wchCoding 你看的是老文档，新文档在这里 https://mp.weixin.qq.com/wiki

**Comment by binarywang** [comment]
具体位置是在这里  https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1458044813&token=&lang=zh_CN
