### ISSUE TITLE
企业微信素材下载异常：Prefix string too short

### ISSUE THREAD

**Issue by BeHappyWsz** [binarywang/WxJava#1500]
**问题：**
企业微信素材下载：安卓机上传的可下载、苹果机上传的下载异常。
**使用版本：**weixin-java-cp-3.3.0
1. 调用接口
`File file = wxCpService.getMediaService().download(mediaId);`
2. 打断点走到：`ApacheMediaDownloadRequestExecutor.execute()`；
在获取fileName时：是根据**Content-disposition**添加的。
安卓机上传正常获取的为：**时间戳.silk**；
苹果机上传后获取的是**.amr**，再次处理后变成""，然后创建文件时长度小于3异常了。
3. 之前一直正常，最近才发现这个问题。是不是企业微信才区分了机型呢？

**Comment by binarywang** [comment]
按你的描述可能是做了调整，欢迎直接提供修复的PR代码

**Comment by binarywang** [comment]
关闭的有些早，还没发布新版本呢

**Comment by binarywang** [comment]
3.7.7.B版本已修复
