### ISSUE TITLE
weixin-java-open 创建开放平台帐号问题

### ISSUE THREAD

**Issue by zzx42** [binarywang/WxJava#1501]
### 简要描述
__简单概括描述下你所遇到的问题。__
微信开放平台帐号管理时应该使用小程序或公众号的access_token,不应该使用商务商token

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号:3.7

### 详细描述
__尽量详细描述。
接口: wchatOpenService.getWxOpenComponentService().createOpenAccount(appId);
微信文档:https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/api/account/create.html
微信开放平台帐号管理时应该使用小程序或公众号的access_token,不应该使用商务商token

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

创建接口:https://api.weixin.qq.com/cgi-bin/open/create
access_token	string (**此处应该使用用户 access_token**)
appid	授权公众号/小程序的 appid
返回错误代码：48001, 错误信息：api unauthorized hints: [ciEBe24ce-LzmPdA!]，微信原始报文：{"errcode":48001,"errmsg":"api unauthorized hints: [ciEBe24ce-LzmPdA!]"}

**Comment by binarywang** [comment]
请规范下你的发帖格式和内容，谢谢合作

**Comment by binarywang** [comment]
问题描述不清楚，暂时关闭

商务商 是什么鬼

**Comment by binarywang** [comment]
请新开issue描述清楚问题，感谢配合
