### ISSUE TITLE
WxOpenMaService没找到订阅消息

### ISSUE THREAD

**Issue by xiongkk** [binarywang/WxJava#1502]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
不好意思，新手刚接触。
小程序订阅消息模版相关接口在WxOpenMaService里面没找到
只在WxMaService里面存在，第三方平台getWxMaServiceByAppid好像就没法用那些接口了。
求教咋弄哩。。。
目前用的版本3.7.0

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Mini_Programs/subscribe_template/add_template.html

**Comment by mr-xiaoyu** [comment]
weixin-java-miniapp模块下WxMaSubscribeService

**Comment by xiongkk** [comment]
就不能直接在第三方平台调吗？用weixin-java-miniapp模块下WxMaSubscribeService的话是不是一定要有app secret？

> weixin-java-miniapp模块下WxMaSubscribeService

**Comment by binarywang** [comment]
你没看到 `WxOpenMaService` 跟 `WxMaService` 是继承关系么？

**Comment by xiongkk** [comment]
> 你没看到 `WxOpenMaService` 跟 `WxMaService` 是继承关系么？

哦哦，感谢！
