### ISSUE TITLE
switchover 校验mpid

### ISSUE THREAD

**Issue by Htuotuo** [binarywang/WxJava#1505]
校验mpId时提示WxMpRedisServiceImpl未实现toString方法[异常图片](https://imgchr.com/i/GjhOyj)

**Comment by binarywang** [comment]
看截图，应该是你debug时evaluate出现的问题，正常程序跑不会出问题。
至于为什么报错，需要你提供详细错误信息，从截图看不出问题来，因为错误信息并不全。

**Comment by binarywang** [comment]
没找到WxMpRedisServiceImpl这个类，你自己写的吧？
