### ISSUE TITLE
无法创建MpnewsArticle

### ISSUE THREAD

**Issue by Mrxun-JN** [binarywang/WxJava#1507]
创建该对象时提示错误
Error:(36, 35) java: 无法将类 me.chanjar.weixin.cp.bean.article.MpnewsArticle中的构造器 MpnewsArticle应用到给定类型;
  需要: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String
  找到: 没有参数
  原因: 实际参数列表和形式参数列表长度不同

**Comment by binarywang** [comment]
你代码如何写的？

**Comment by binarywang** [comment]
3.7.7.B版本已添加相关构造方法

**Comment by Mrxun-JN** [comment]
现在已经可以正常使用了，感谢: )
