### ISSUE TITLE
企业微信群变更事件

### ISSUE THREAD

**Issue by yoking-zhang** [binarywang/WxJava#1520]
能否在https://github.com/Wechat-Group/WxJava/blob/develop/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/bean/WxCpXmlMessage.java类中加入ChatId用于处理企业微信群变更事件？

### 官方文档地址
https://work.weixin.qq.com/api/doc/90000/90135/92130#%E5%AE%A2%E6%88%B7%E7%BE%A4%E5%8F%98%E6%9B%B4%E4%BA%8B%E4%BB%B6

**Comment by binarywang** [comment]
没问题，建议自己可以直接提交PR。

另外，你可以先通过allFieldsMap 这个字段来获取该值。

**Comment by binarywang** [comment]
3.7.7.B版本已添加

**Comment by yoking-zhang** [comment]
能否mvn delpoy下3.7.7.B版本？

**Comment by binarywang** [comment]
早发布了的，发完我才回复信息的

**Comment by yoking-zhang** [comment]
https://oss.sonatype.org/#nexus-search;gav~com.github.binarywang~wx-java, 能看到的最大版本号，也只有3.7.6.B

**Comment by binarywang** [comment]
现在有了吧
