### ISSUE TITLE
WxMaExpressPath.PathItem为私有内部类，外部访问不到~

### ISSUE THREAD

**Issue by stefanlee91418** [binarywang/WxJava#1524]
### 简要描述
如题

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.7.4B

### 详细描述
`       for (WxMaExpressPath.PathItem pathItem : wxMaExpressPath.getPathItemList()) {

        }
`

**Comment by binarywang** [comment]
确实是有问题，稍后修复
