### ISSUE TITLE
登录授权的应用的appid、secret和公众号的appid、secret如何做区分

### ISSUE THREAD

**Issue by zhuenbang** [binarywang/WxJava#1525]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
WxMpDefaultConfigImpl 中设置
appid、secret 
如果我项目中既有登录授权又有公众号开发，如何做区分

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
自己创建多个实例即可
