### ISSUE TITLE
jar文件和source文件对不上

### ISSUE THREAD

**Issue by midoll3** [binarywang/WxJava#1526]
#647 # 简要描述

### 模块版本情况
* WxJava 模块名: miniapp
* WxJava 版本号:3.7

![image](https://user-images.githubusercontent.com/31194732/79938012-fbeba100-848d-11ea-99ab-3feabfc9deca.png)

**Comment by midoll3** [comment]
获取accesstoken时老是出问题，所以想debug，但是发现源码和打包后的class对不上

**Comment by binarywang** [comment]
看不到图片，麻烦尽量贴文字，谢谢。

另外源码和class对不上，是不是你版本不一致，你说的对不上具体是指什么？

**Comment by binarywang** [comment]
看到图片了，你所谓的对不上是拿反编译的跟实际的源码对比，怎么可能能对的上？
