### ISSUE TITLE
希望加入微信小程序OCR身份证识别和银行卡识别接口支持

### ISSUE THREAD

**Issue by ma365782283** [binarywang/WxJava#1527]
### 简要描述
身份证识别这块需求还是蛮大的，希望下来可以支持到

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/ocr/ocr.bankcard.html
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/ocr/ocr.idcard.html

**Comment by einsitang** [comment]
> ### 简要描述
> 身份证识别这块需求还是蛮大的，希望下来可以支持到
> 
> ### 官方文档地址
> https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/ocr/ocr.bankcard.html
> https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/ocr/ocr.idcard.html

mp包下有一个WxMpOcrService,里面包含OCR的接口

**Comment by binarywang** [comment]
既然是小程序也可以使用，可以考虑抽取成公共的方法，保证两边都可以使用

**Comment by binarywang** [comment]
不太好实现，暂时放弃

**Comment by binarywang** [comment]
3.8.4.B版本已增加，欢迎使用
