### ISSUE TITLE
微信退款是否考虑支持单品退款

### ISSUE THREAD

**Issue by mayorKuo** [binarywang/WxJava#1529]
看了退款代码，目前只支持普通退款，考虑增加申请退款API（支持单品）接口吗？

### 官方文档地址
普通退款接口：https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_4
支持单品退款接口：https://pay.weixin.qq.com/wiki/doc/api/danpin.php?chapter=9_103&index=3

**Comment by binarywang** [comment]
请给出具体文档地址，而不是接口地址

**Comment by mayorKuo** [comment]
> 请给出具体文档地址，而不是接口地址
普通退款接口：https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_4
支持单品退款接口：https://pay.weixin.qq.com/wiki/doc/api/danpin.php?chapter=9_103&index=3
原提问中也已更新

**Comment by wangjia2016** [comment]
单品退款指的是一个订单多个商品的部分退款吗?

**Comment by mayorKuo** [comment]
> 单品退款指的是一个订单多个商品的部分退款吗?

这接口是针对微信单品营销的优惠商品退款，比普通的退款接口可以多传单品优惠的商品明细

**Comment by binarywang** [comment]
3.8.2.B版本已支持，欢迎试用
