### ISSUE TITLE
汇率查询的接口

### ISSUE THREAD

**Issue by liuzhihai520** [binarywang/WxJava#1532]
查询汇率

官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/app/app_jw.php?chapter=9_15&index=12

**Comment by binarywang** [comment]
确实还没实现，可以考虑加上

**Comment by liuzhihai520** [comment]
多谢  手动抱拳

**Comment by binarywang** [comment]
3.8.0版本已增加
