### ISSUE TITLE
第三方微信平台  refresh_token  为空

### ISSUE THREAD

**Issue by zacat** [binarywang/WxJava#1533]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名:   weixin-java-open
* WxJava 版本号:   3.7.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
 
【请求地址】: https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token=32_qPf1JcPIs-yWx_1CabTEam1l9NwVZsZpF6QkOXfbtgTSS4uNk8z82TRsDb41Bh8nOmWJAiVBxw7WhgNsoKj-9Q1ulmRRhKHwO0Jkv2Am76nc6IMN-u0gWv6Ly2pfs-ptB7pcl5ZP-s3_eEvzWDEdADACJK
【请求参数】：{"component_appid":"xxxxxxxx","authorizer_appid":"xxxxxx","authorizer_refresh_token":null}
【错误信息】：错误代码：61023, 错误信息：refresh_token is invalid hint: [Oto2JA02774731]，微信原始报文：{"errcode":61023,"errmsg":"refresh_token is invalid hint: [Oto2JA02774731]"}

**Comment by binarywang** [comment]
请规范下issue内容。
另外请提供相应代码内容，以供排查问题。
