### ISSUE TITLE
WxCryptUtil.decrypt OutOfMemoryError

### ISSUE THREAD

**Issue by hjjoe1213123** [binarywang/WxJava#1537]
### 简要描述
__简单概括描述下你所遇到的问题。__
这个位置在IDEA默认VM情况下容易出现内存溢出，需要优化此处
### 模块版本情况
* WxJava 模块名: weixin-java-common
* WxJava 版本号:3.7.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__
2020-04-29 10:05:19.425 ERROR 9404 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space] with root cause

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332) ~[na:1.8.0_172]
	at java.lang.StringCoding.safeTrim(StringCoding.java:89) ~[na:1.8.0_172]
	at java.lang.StringCoding.decode(StringCoding.java:230) ~[na:1.8.0_172]
	at java.lang.String.<init>(String.java:463) ~[na:1.8.0_172]
	at java.lang.String.<init>(String.java:515) ~[na:1.8.0_172]
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:267) ~[weixin-java-common-3.7.0.jar:na]
	at me.chanjar.weixin.common.util.crypto.WxCryptUtil.decrypt(WxCryptUtil.java:229) ~[weixin-java-common-3.7.0.jar:na]
	at me.chanjar.weixin.mp.bean.message.WxMpXmlMessage.fromEncryptedXml(WxMpXmlMessage.java:672) ~[weixin-java-mp-3.7.0.jar:na]

**Comment by binarywang** [comment]
能否给出更多的错误信息，比如具体的报文内容是什么，什么情况下会导致，你的代码是怎么写的？
你说的容易出现，是怎么判断的，目前并没有其他人遇到过此问题。

**Comment by hjjoe1213123** [comment]
WxCryptUtil.java 这个类如下代码：
将一个长度为861313209 的byte数组转换成String，而且两次，并且下面那次还不用，只要服务器设定的堆内存稍微小一点点此溢出必现，特别是高并发情况下尤为明显

    String xmlContent;
    String fromAppid;
    try {
      // 去除补位字符
      byte[] bytes = PKCS7Encoder.decode(original);

      // 分离16位随机字符串,网络字节序和AppId
      byte[] networkOrder = Arrays.copyOfRange(bytes, 16, 20);

      int **xmlLength** = bytesNetworkOrder2Number(networkOrder);

      xmlContent = **new String**(Arrays.copyOfRange(bytes, 20, 20 + xmlLength), CHARSET);
      fromAppid = **new String**(Arrays.copyOfRange(bytes, 20 + xmlLength, bytes.length), CHARSET);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }

    // appid不相同的情况 暂时忽略这段判断
//    if (!fromAppid.equals(this.appidOrCorpid)) {
//      throw new RuntimeException("AppID不正确，请核实！");
//    }

**Comment by binarywang** [comment]
你有什么推荐的可以改善的好方法，欢迎直接提交PR

**Comment by binarywang** [comment]
鉴于此种情况是由于服务器设置堆内存过小导致，并不具有普遍性，而目前没有针对堆内存过小的可行优化方案，建议自行更改相关配置即可。

**Comment by sunyu1990** [comment]
普遍性问题

**Comment by turborz** [comment]
这种情况一般可能出现在测试微信消息处理的时候出现，出现的原因是消息体是自己手动加密生成的，生成的加密字符串有误，在解密的时候就有可能出现这种情况。具体出错代码为WxCryptUtil.java的decrypt方法。

```java

  /**
   * 对密文进行解密.
   *
   * @param cipherText 需要解密的密文
   * @return 解密得到的明文
   */
  public String decrypt(String cipherText) {
    byte[] original;
    try {
      // 设置解密模式为AES的CBC模式
      Cipher cipher = Cipher.getInstance("AES/CBC/NoPadding");
      SecretKeySpec keySpec = new SecretKeySpec(this.aesKey, "AES");
      IvParameterSpec iv = new IvParameterSpec(Arrays.copyOfRange(this.aesKey, 0, 16));
      cipher.init(Cipher.DECRYPT_MODE, keySpec, iv);

      // 使用BASE64对密文进行解码
      byte[] encrypted = Base64.decodeBase64(cipherText);

      // 解密
      original = cipher.doFinal(encrypted);
    } catch (Exception e) {
      throw new WxRuntimeException(e);
    }

    String xmlContent;
    String fromAppid;
    try {
      // 去除补位字符
      byte[] bytes = PKCS7Encoder.decode(original);

      // 分离16位随机字符串,网络字节序和AppId
      byte[] networkOrder = Arrays.copyOfRange(bytes, 16, 20);

      int xmlLength = bytesNetworkOrder2Number(networkOrder);

      xmlContent = new String(Arrays.copyOfRange(bytes, 20, 20 + xmlLength), CHARSET);
      fromAppid = new String(Arrays.copyOfRange(bytes, 20 + xmlLength, bytes.length), CHARSET);
    } catch (Exception e) {
      throw new WxRuntimeException(e);
    }
```

其中有一行是根据加密算法获取长度的代码：
```java
int xmlLength = bytesNetworkOrder2Number(networkOrder);
```
如果手动密文生成时，格式不正确，也就是第16个字节到20个字节位置并不能长度，可能会得到一个很大数字。（毕竟大概率字节位置的值不是0）
也就会使其下面一行代码：
```java
 xmlContent = new String(Arrays.copyOfRange(bytes, 20, 20 + xmlLength), CHARSET);
```
构建一个非常大的字符串，需要很大的内存空间，进而产生OutOfMemoryError  java Heap space的错误。

所以，代码本身并不存在bug，其原因是自己手动生成密文环节存在问题。可使用微信的请求密文自行测试。
