### ISSUE TITLE
您好 微信公众号模块的一个错误响应信息错了

### ISSUE THREAD

**Issue by KangTantan** [binarywang/WxJava#1539]
https://github.com/Wechat-Group/WxJava/blob/23c1b0b0df621cf29ed57a92ae5fa287ff749f0f/weixin-java-common/src/main/java/me/chanjar/weixin/common/error/WxMpErrorMsgEnum.java#L91

40017 应为 不合法的按钮类型

**Comment by binarywang** [comment]
欢迎直接提交PR，谢谢指出

**Comment by KangTantan** [comment]
> 欢迎直接提交PR，谢谢指出

啊 不好意思 我这边克隆github的项目经常clone不下来... 没有提交PR 看您已经改了 😜
