### ISSUE TITLE
缺少set方法

### ISSUE THREAD

**Issue by 18940818955** [binarywang/WxJava#154]
me.chanjar.weixin.mp.api.WxMpInMemoryConfigStorage这个类里面的cardApiTicket属性没有set方法，cardApiTicketExpiresTime这个属性没有set/get方法，请问这是有什么深意吗？

**Comment by binarywang** [comment]
我看了下代码，cardApiTicket有另外一个update的方法来更新其值，所以set方法没用，而cardApiTicketExpiresTime的值也是在这个update方法和其他方法里进行更改的，整体来说都是在这个类里使用，所以无需暴漏出去，set和get方法就都是多余的了

**Comment by 18940818955** [comment]
我现在已经有了cardApiTicket和cardApiTicketExpiresTime(时间戳)了，如果有set方法的话，我只需要set两次就可以了。
而用update，我无法计算出expiresInSeconds具体是多少，所以update这个方法好像不适合我这里。

**Comment by 18940818955** [comment]
`
 Long expiresInSeconds = app.getCardApiTicketExpiresTime() - System.currentTimeMillis();
    config.updateCardApiTicket(app.getCardApiTicket(), (int) (expiresInSeconds / 1000L + 200));
`
这是我实际的代码，其中app是用来保存微信appId、secret、accessToken……cardApiTicket和cardApiTicketExpiresTime的bean。
于是如果要是用update的话代码就只能这么写了。。好感人

**Comment by binarywang** [comment]
不是相关类里已经有相关方法了吗？你还需要自己去写？

**Comment by 18940818955** [comment]
我这的需求是两个应用，他们之间都需要调用微信接口。
而我想把token同步，避免重复获取token，所以就将token等信息提取出一个bean，放到数据库里，并且用redis作了缓存。
所以每次都要取到token/jsApiTicket/cardApiTicket，然后往WxMpInMemoryConfigStorage里面set值。
不知道我这样做是否正确？

**Comment by binarywang** [comment]
你的应用场景就不应该再使用WxMpInMemoryConfigStorage这个类了，类名里的InMemory就已经说明这是一个基于内存的配置，只适合一般的应用场景，而你的情形则应该自己实现一个WxMpConfigStorage的实现类

**Comment by binarywang** [comment]
考虑了下，还是将相应getter和setter方法加上了，以便根据需求使用吧

**Comment by 18940818955** [comment]
我用自己写的configStorage继承的inMemory，然后重写了判断是否过期的方法，好像叫isAccessTokenExpire，您看这样可行吗

**Comment by binarywang** [comment]
你根据自己的需要判断就可以了
