### ISSUE TITLE
WxDeviceBindDeviceResult 里的 Device类私有, 无法访问

### ISSUE THREAD

**Issue by russleung44** [binarywang/WxJava#1540]
### 简要描述
WxDeviceBindDeviceResult.Device 无法访问

### 模块版本情况
* WxJava 模块名: 微信公众号
* WxJava 版本号: 3.7.0

### 详细描述
接入WxMpDeviceService , 调用 getBindDevice 获取设备列表 , 返回类里的 Device 是私有的 , 无法访问

![Snipaste_2020-05-01_14-08-51](https://user-images.githubusercontent.com/56534185/80786176-5b942b80-8bb5-11ea-83a3-b59b94f64f39.png)

**Comment by binarywang** [comment]
确实是不应该，定义有问题
