### ISSUE TITLE
多公众号高并发时,事件问题

### ISSUE THREAD

**Issue by shandianex1** [binarywang/WxJava#1545]
现在接收公众号事件是以appid路径判断切换wpservice 但是处理事件的时候并没有传入appid 只是默认以当前wpservice  当高并发时 会不会这样判断不准确？
![微信并发](https://user-images.githubusercontent.com/12183412/81148317-a5628480-8fae-11ea-8191-c5f121c7aea3.png)

**Comment by binarywang** [comment]
按照你的代码写法，appid不是你自己指定到微信配置的地址里的吗？它怎么会不传，肯定有值的吧！

**Comment by shandianex1** [comment]
事件里那个handle没传啊 只是封装的传的当前wxservice

**Comment by binarywang** [comment]
你没看到有个switchover方法调用了？

**Comment by shandianex1** [comment]
是调用了 事件传过来然后switch当前wxservice 如果高并发会不会switch错

**Comment by binarywang** [comment]
麻烦自己看下方法是怎么实现的呗？源码都是公开，可以看到的，看完你就明白了

**Comment by binarywang** [comment]
另外请顺便学习下ThreadLocal相关技术
