### ISSUE TITLE
WxOpenInRedisConfigStorage初始化报错

### ISSUE THREAD

**Issue by zacat** [binarywang/WxJava#1546]
### 简要描述
__简单概括描述下你所遇到的问题。__
WxOpenInRedisConfigStorage inRedisConfigStorage = new WxOpenInRedisConfigStorage(pool, "zoeyun:" + clientId);

### 模块版本情况
* WxJava 模块名:  weixin-java-open
* WxJava 版本号:  3.7.0

### 详细描述
WxOpenInRedisConfigStorage inRedisConfigStorage = new WxOpenInRedisConfigStorage(pool, "zoeyun:" + clientId);
对象构造时因继承自，WxOpenInMemoryConfigStorage 对象，WxOpenInMemoryConfigStorage 对象初始化时
  private Lock componentAccessTokenLock = getLockByKey("componentAccessTokenLock");
执行getLockByKey方法，但在WxOpenInRedisConfigStorage 对象中，未初始化完成，此时redisOps对象值为空，导致Null报错。

**Comment by binarywang** [comment]
3.7.9.B版本已修复
