### ISSUE TITLE
RedisTemplateWxRedisOps 不过期设置问题

### ISSUE THREAD

**Issue by zacat** [binarywang/WxJava#1548]
### 简要描述

ERR invalid expire time in SETEX

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 3.7.8.B

### 详细描述
    在RedisTemplateWxRedisOps的SetValue中，设置0，Key永不过期，Redis报错，错误提示：ERR invalid expire time in SETEX
其中到期时间不能小于等于0， 所以报错。

如需永不过期，目前修改如下可用：
  @Override
  public void setValue(String key, String value, int expire, TimeUnit timeUnit) {
    if (expire < 0) {
      redisTemplate.opsForValue().set(key, value);
    } else {
      redisTemplate.opsForValue().set(key, value, expire, timeUnit);
    }
  }

![image](https://user-images.githubusercontent.com/20654293/81243627-f459f980-9042-11ea-9909-45ed62d773c0.png)

修改setAuthorizerRefreshToken时长为-1
  @Override
  public void setAuthorizerRefreshToken(String appId, String authorizerRefreshToken) {
    redisOps.setValue(this.getKey(this.authorizerRefreshTokenKey, appId), authorizerRefreshToken, -1, TimeUnit.SECONDS);
  }

![image](https://user-images.githubusercontent.com/20654293/81244075-fa9ca580-9043-11ea-8950-28296a34ef1c.png)

**Comment by binarywang** [comment]
3.7.9.B版本已修复
