### ISSUE TITLE
WxMpServiceImpl中this.wxMpConfigStorage能否改成getWxMpConfigStorage()

### ISSUE THREAD

**Issue by ylmotol7** [binarywang/WxJava#155]
请问WxMpServiceImpl中this.wxMpConfigStorage能否改成getWxMpConfigStorage()？
目前WxMpServiceImpl直接使用this.wxMpConfigStorage来获取配置信息，如果改成getWxMpConfigStorage()，再配合ThreadLocal应该可以很容易实现多公众号功能。
不知这样改之后，请问是否有问题？

**Comment by binarywang** [comment]
改应该是没问题，你这种实现多公众号的思路我还真没考虑过，我之前实现过支持多公众号的Demo，只不过不够灵活。如果可以，能否将你的代码以一个简单的Demo展示出来，供其他有需要的朋友参考一下？

**Comment by ylmotol7** [comment]
我稍后改的试下然后贴出来

**Comment by ylmotol7** [comment]
我fork之后的代码地址https://github.com/ylmotol7/weixin-java-mp-demo
WxMpServiceImpl里面有改动，一并上传到了，名为WxMpServiceImpl.java.bak
也请你帮忙审查下，看这么改动会不会在并发的时候对原始逻辑有影响。
因只有一个公众号，遂测试了一个号，多个号的在WxMpConfigHolder添加。
也可以从数据库中加载，该demo只是简单demo

**Comment by binarywang** [comment]
已看明白你的实现思路，非常棒！

**Comment by gaozhenzhen** [comment]
为什么我的这句一直报错呢（空指针）？WxMpXmlMessage inMessage = WxMpXmlMessage.fromXml(requestBody);

**Comment by prettydog** [comment]
能实现从数据库加载吗？

**Comment by binarywang** [comment]
@hokagecode 
有其他问题请新开issue，另外请尽量描述清楚你的问题吧
