### ISSUE TITLE
无法创建 TaskCardButton 类

### ISSUE THREAD

**Issue by Mrxun-JN** [binarywang/WxJava#1550]
使用版本 3.7.8.B 
代码如下
List<TaskCardButton> buttons = new ArrayList<>();
        TaskCardButton button1 = new TaskCardButton();//该处会提示
        button1.setKey("yes");
        button1.setName("同意");
        button1.setReplaceName("同意杀题");
        button1.setColor("blue");
        button1.setBold(true);

提示错误
 java: 无法将类 me.chanjar.weixin.cp.bean.taskcard.TaskCardButton中的构造器 TaskCardButton应用到给定类型;
  需要: java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.Boolean
  找到: 没有参数
  原因: 实际参数列表和形式参数列表长度不同

**Comment by Mrxun-JN** [comment]
应该和上次 MpnewsArticle 类一样

**Comment by binarywang** [comment]
你先使用builder方法吧，之前确实是考虑欠妥

**Comment by Mrxun-JN** [comment]
好的，感谢

**Comment by binarywang** [comment]
3.7.9.B版本已优化
