### ISSUE TITLE
java9及以上版本禁用非法反射问题

### ISSUE THREAD

**Issue by duanhongyi** [binarywang/WxJava#1551]
java9及以上版本使用报错：

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/Users/duanhongyi/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

相关讨论在：https://github.com/x-stream/xstream/issues/101 

将来是否有计划替换掉xstream？

**Comment by binarywang** [comment]
大概看了下，只是有warning而已，目前没有计划要替换掉。
当然非常欢迎你能提供成熟的替换实现。

**Comment by duanhongyi** [comment]
我简单修改了一下，在我的项目里测试没有警告了。 #1553
@binarywang

**Comment by binarywang** [comment]
#1558

**Comment by binarywang** [comment]
3.7.9.B版本已优化
