### ISSUE TITLE
java.lang.IllegalStateException: Connection pool shut down

### ISSUE THREAD

**Issue by farawayll** [binarywang/WxJava#1557]
### 简要描述
订单服务，根据各个物流节点状态，发送给用户公众号模板消息，间歇性的出现java.lang.IllegalStateException: Connection pool shut down异常。

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.6.0

### 详细描述
发送模式：通过小程序的openid来发送公众号模板消息。
wxMaService.getMsgService().sendUniformMsg(wxMaUniformMessage);

![image](https://user-images.githubusercontent.com/38970336/81631689-fead3680-943a-11ea-8bc6-45d626921e65.png)

### 日志
日志https://paste.ubuntu.com/p/Y65f8cXRyQ/

**Comment by binarywang** [comment]
#1523 重复

**Comment by zhangsean** [comment]
我也遇到这个问题，WxPay v4.7.5.B 模块第一次调用支付接口正常，再次请求就`Connection pool shut down`。
排查发现是`wxPayService.getConfig()`缓存了`apiV3HttpClient`，第一次请求微信接口成功后调用`httpClient.close();`关闭了连接，下次请求直接`getApiV3HttpClient`获得的连接就是`shutdown`的状态。而调用前没有判断如果连接已关闭就马上重连，所以多次请求时就触发了错误`Connection pool shut down`。
临时解决办法是在每次调用前将缓存的连接置空，强制走初始化连接的流程即可。
```java
// 临时修正Connection pool shut down错误
wxPayService.getConfig().setApiV3HttpClient(null);
TransferService transferService = wxPayService.getTransferService();
...
TransferBillsResult billsResult = transferService.transferBills(req);
```
@binarywang 请大佬指正，在模块里优化这个逻辑。

**Comment by binarywang** [comment]
都不是同一块代码，麻烦新的问题新提交issue，不要在这么古老且没有关系的的帖子里跟随了
