### ISSUE TITLE
微信会员卡基本信息更新需要自定义使用入口跳转小程序，自定义营销入口跳转小程序等设置

### ISSUE THREAD

**Issue by yeafee** [binarywang/WxJava#1559]
### 简要描述
微信会员卡创建有自定义使用入口、自定义营销入口跳转小程序，而会员卡基本信息更新没有自定义使用入口跳转小程序，自定义营销入口跳转小程序等。会员更新也需要更新小程序跳转设置。

### 官方文档地址
custom_app_brand_pass,promotion_app_brand_user_name等关键字
![微信截图_20200512114714](https://user-images.githubusercontent.com/531538/81636404-5f8e3c00-9446-11ea-9a78-3b5e45511765.png)

__https://developers.weixin.qq.com/doc/offiaccount/Cards_and_Offer/Coupons-Mini_Program_Start_Up.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%86%85%E9%A2%86%E5%8F%96%E5%8D%A1%E5%88%B8。__

**Comment by binarywang** [comment]
建议楼主可以直接提交PR，快速修复问题

**Comment by binarywang** [comment]
完全没看懂这些的都是啥，官方文档连示例都不给完整些！

字段名 | 字段描述 | 字段示例
-- | -- | --
custom_app_brand_user_name | 自定义使用入口跳转小程序的user_name，格式为原始id+@app | gh_86a091e50ad4@app
custom_app_brand_pass | 自定义使用入口小程序页面地址 | API/cardPage
center_app_brand_user_name | 小程序的user_name | gh_86a091e50ad4@app
center_app_brand_pass | 自定义居中使用入口小程序页面地址 | API/cardPage
promotion_app_brand_user_name | 小程序的user_name | gh_86a091e50ad4@app
promotion_app_brand_pass | 自定义营销入口小程序页面地址 | API/cardPage
activate_app_brand_user_name | 小程序的user_name, | gh_86a091e50ad4@app
activate_app_brand_pass | 激活小程序页面地址 | API/cardPage
custom_field1、custom_field2 custom_field3 | 会员卡顶部的信息类目字段，包含以下两个字段 |  
app_brand_user_name | 自定义信息类目小程序user_name，格式为原始id+@app | gh_86a091e50ad4@app
app_brand_pass | 自定义信息类目小程序的页面路径 | API/cardPage
custom_cell1、custom_cell2 | 会员卡自定义入口，包含以下两个字段 |  
app_brand_user_name | 自定义入口小程序user_name，格式为原始id+@app | gh_86a091e50ad4@app
app_brand_pass | 自定义入口小程序的页面路径 | API/cardPage
bonus_app_brand_user_name | 积分信息类目对应的小程序 user_name，格式为原始id+@app | gh_86a091e50ad4@app
bonus_app_brand_pass | 积分入口小程序的页面路径 | API/cardPage
balance_app_brand_user_name | 余额信息类目对应的小程序 user_name，格式为原始id+@app | gh_86a091e50ad4@app
balance_app_brand_pass | 余额入口小程序的页面路径 | API/cardPage
