### ISSUE TITLE
对spring boot的支持

### ISSUE THREAD

**Issue by unlimitedsola** [binarywang/WxJava#156]
以下是几点提议
1. 提供带有`@ConfigurationProperties`注解的`WxMpConfigStorage`实现
2. 为 *spring-boot* 提供自动配置，请参考：http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html
3. 发布时加入`/META-INF/spring-configuration-metadata.json`，这样在IDE中设置`application.yml`或`application.properties`时可以有更好的代码补全
![example](https://cdn.pbrd.co/images/I70gbEWLW.png)
参考http://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor

**Comment by binarywang** [comment]
建议不错，但是你可能没理解我们这个项目的定位，只是提供SDK，不依赖具体的框架，如果想实现这些，可以在demo里去实现。

**Comment by unlimitedsola** [comment]
我自己做了一个项目，但没有发布到maven仓库的经验
https://github.com/SolaKun/wechat-spring-boot-auto-configuration

**Comment by binarywang** [comment]
为什么要发布到maven上？除非有需要吧，你这个看起来好像只是个演示的demo？

**Comment by binarywang** [comment]
另外给你个建议，提交代码就尽量不要把ide的配置文件，比如.idea文件夹和.iml文件也搞上去了，看起来不够整洁

**Comment by unlimitedsola** [comment]
1. 不是一个demo，是一个库，wechat-sample-app里演示了如何使用这个库
2. .idea文件夹里的内容是根据.ignore插件生成的，具体可以看https://github.com/SolaKun/wechat-spring-boot-auto-configuration/blob/master/.gitignore
.ignore插件是根据idea官方的一篇文章作参考
https://intellij-support.jetbrains.com/hc/en-us/articles/206544839
文章里讲到哪些文件可以放到vcs上

**Comment by binarywang** [comment]
好吧，我没仔细看，可能还是个人习惯吧，个人还是不习惯将IDE的配置放上去，毕竟用处不是很大，其他人又可能不会使用你所使用的IDE。

**Comment by binarywang** [comment]
你把Readme补充下吧好让别人能知道你的项目是做什么的，然后我在这边项目首页给你做个链接，好让其他人也能看到你的项目。

**Comment by unlimitedsola** [comment]
OK， 我花时间完善下后再来回复
