### ISSUE TITLE
微信卡包领卡后更新错误WxMpMemberCardUpdateMessage.java 兼容留下的多个add_bonus引起报错

### ISSUE THREAD

**Issue by yeafee** [binarywang/WxJava#1564]
### 简要描述
__WxMpMemberCardUpdateMessage.java 多个 @SerializedName("add_bonus")引起会员卡领卡后更新报错。__

### 模块版本情况
* WxJava 模块名: weixin-java-mp 
* WxJava 版本号: 3.7.7.B~3.7.9.B

### 详细描述
__多个“add_bouns”引起微信卡包领卡后更新会员卡错误。 查看代码是因为历史遗留的拼写错误，原作者考虑兼容才保留同时存在多个add_bouns。__

>  private Integer bonus;
    /**
     *本次积分变动值，传负数代表减少，错误单词，只是为了保持兼容
     */
    @Deprecated
    @SerializedName("add_bonus")
    private Integer addBounus;
    /**
      * 本次积分变动值，传负数代表减少
      */
    @SerializedName("add_bonus")
     private Integer addBonus;

### 日志

> class me.chanjar.weixin.mp.bean.membercard.WxMpMemberCardUpdateMessage declares multiple JSON fields named add_bonus

![weixin-java-mp-error](https://user-images.githubusercontent.com/531538/82121900-f8181980-97c2-11ea-9dd7-ef57e924b6c5.png)

**Comment by binarywang** [comment]
这还真是个问题，稍后修复

**Comment by binarywang** [comment]
还没发布呢，关闭的有点早
