### ISSUE TITLE
POJO字段对应微信接口返回JSON字段问题

### ISSUE THREAD

**Issue by prosaically** [binarywang/WxJava#1567]
使用微信授权用户信息接口来举例：
这是微信返回的JSON数据：
```
{
    "subscribe": 1, 
    "openid": "o6_bmjrPTlm6_2sgVt7hMZOPfL2M", 
    "nickname": "Band", 
    "sex": 1, 
    "language": "zh_CN", 
    "city": "广州", 
    "province": "广东", 
    "country": "中国", 
    "headimgurl":"http://thirdwx.qlogo.cn/mmopen/g3MonUZtNHkdmzicIlibx6iaFqAc56vxLSUfpb6n5WKSYVY0ChQKkiaJSgQ1dZuTOgvLLrhJbERQQ4eMsv84eavHiaiceqxibJxCfHe/0",
    "subscribe_time": 1382694957,
    "unionid": " o6_bmasdasdsad6_2sgVt7hMZOPfL"
    "remark": "",
    "groupid": 0,
    "tagid_list":[128,2],
    "subscribe_scene": "ADD_SCENE_QR_CODE",
    "qr_scene": 98765,
    "qr_scene_str": ""
}
```
这是WxJava实体类的字段：
```
public class WxMpUser implements Serializable {
  private Boolean subscribe;
  private String openId;
  private String nickname;
  private String sexDesc;
  private Integer sex;
  private String language;
  private String city;
  private String province;
  private String country;
  private String headImgUrl;
  private Long subscribeTime;
  private String unionId;
  private String remark;
  private Integer groupId;
  private Long[] tagIds;
  private String[] privileges;
  private String subscribeScene;
  private String qrScene;
  private String qrSceneStr;
}
```

微信JSON返回的字段名是下划线命名，Java的命名风格是驼峰命名。将JSON字段转成Java POJO时，不应该出现不规则例外。

**比如：**
微信返回JSON的字段“openid”，转成Java时应该也是“openid”。但是在WxJava的实体对象确是“openId”，还有如“headimgurl”等。

**问题突显如下：**

1. 如某公司的系统原来的数据结构是依据微信接口返回的字段名来设计的，此时如果要使用WxJava，就是会出现数据结构对应的问题。修改数据库表结构是不太现实的，PO对应的也是数据库，所以PO也不能修改。些时就成了这样：
```
  // WxJava实体类
  WxMpUser wxMpUser = new WxMpUser();
  // 使用者系统实体类
  EguThirdPartyUserEo user = new EguThirdPartyUserEo();
  user.setOpenid(wxMpUser.getOpenId());
  user.setUnionid(wxMpUser.getUnionId());
  user.setHeadimgurl(wxMpUser.getHeadImgUrl());
  // .....
```
2. 从以上衍生出来的问题还有反射、JSON序列化、反序列化的问题。JSON注解能解决映射问题，但是如果POJO是用逆向工程生成的时候就没法解决。

**优化方式建议：**

1. 接口提供原始微信数据返回的方法
```
  // 返回把微信接口返回的数据包装
  public WxMpUser userInfo(String openid);
  // 返回微信接口返回的数据
  public String userInfo(String openid)
```
2. 完善WxJava的实体类，但是这会造成工作量太大，前后兼容问题。

_以上仅是个人建议，希望该项目越来越好。_

**Comment by binarywang** [comment]
楼主你的问题已基本明白，我们都知道微信官方接口很多都不规范，而目前我们的代码是从规范性角度考虑做的实现，这样也可以带动使用WxJava的项目进行规范化，形成一个良性的生态，使得用户可以较少去关注微信官方自己定义的不规范的命名。

不过你如果想自己适配返回结果，可以自己使用post或get方法重新实现所有接口，很方便，但不建议，长远考虑，还是规范化比较好。

**Comment by zhuocwang** [comment]
遇到同样的问题，希望能把微信接口原始数据返回。

对于微信接口的相关字段名，因为有不同项目组，甚至使用的语言都不一样，这种情况下，我们为了方便，都是直接使用微信接口命名的字段名减少沟通成本，现有的这些实体类，我都还需要转换回去，要不就直接POST，GET了 @binarywang

**Comment by binarywang** [comment]
> 遇到同样的问题，希望能把微信接口原始数据返回。
> 
> 对于微信接口的相关字段名，因为有不同项目组，甚至使用的语言都不一样，这种情况下，我们为了方便，都是直接使用微信接口命名的字段名减少沟通成本，现有的这些实体类，我都还需要转换回去，要不就直接POST，GET了 @binarywang

正如我在楼上说的，你们的情况可以使用现有的post和get方法去实现
