### ISSUE TITLE
企业微信上传文件方法header body内容似乎出错

### ISSUE THREAD

**Issue by siTsang546** [binarywang/WxJava#1569]
### 简要描述
举例**WxCpMediaService.uploadImg(File file),**
报错日志
{"errcode":44001,"errmsg":"empty media data, hint: [1589873107_51_8063f87e8a6fee21a606494a1eab5049]
所有的upload方法都出错

### 模块版本情况
* WxJava : weixin-java-cp
* WxJava 版本号: 3.7.0

### 详细描述
```java
    @PostMapping("/upload")
    public String upload(@RequestParam("file") MultipartFile multipartFile) throws IOException {
        String originalFilename = multipartFile.getOriginalFilename();
        File tempFile = File.createTempFile(originalFilename.substring(0, originalFilename.lastIndexOf("."))
                , originalFilename.substring(originalFilename.lastIndexOf(".")));


        WxCpService cpService = WxCpConfiguration.getCpService(1000006);
        WxCpMediaService mediaService = cpService.getMediaService();

        //FileInputStream fis = new FileInputStream(tempFile);

        try {
            WxMediaUploadResult upload = mediaService.upload(WxConsts.MediaFileType.IMAGE, tempFile);
            //WxMediaUploadResult upload = mediaService.upload(WxConsts.MediaFileType.IMAGE, "image",fis);

            return upload.toString();
        } catch (WxErrorException e) {
            e.printStackTrace();
        }finally {
            //fis.close();
           tempFile.delete();
        }
        return "非法请求";
    }
```

**Comment by binarywang** [comment]
按说这个问题已经修复了的，https://github.com/Wechat-Group/WxJava/issues/209
楼主可以确认下

**Comment by siTsang546** [comment]
首先，感谢你百忙中还能回复我的反馈。
此行代码在我引入的依赖中的确已经被删除，但是这个报错的确存在，不知道我上面的用法是否有误。
在我的项目中，不止该一个方法报此错误


upload(String, String, InputStream)upload(String, File)uploadImg(File)

这三个方法的引用都报此错误。


最后，再次感谢你的回复。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 下午4:29
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;" "<1005996526@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 企业微信上传文件方法header body内容似乎出错 (#1569)





 
按说这个问题已经修复了的，#209
 楼主可以确认下

**Comment by binarywang** [comment]
你是否跑过 `me.chanjar.weixin.cp.api.impl.WxCpMediaServiceImplTest` 里的测试代码，我刚试了没有问题的

**Comment by siTsang546** [comment]
跑了一下没有问题，
想问一下是否和依赖导入有关。或者我获取WxCpService及WxCpMediaService有什么问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月19日(星期二) 晚上6:11
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;" "<1005996526@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 企业微信上传文件方法header body内容似乎出错 (#1569)





 
你是否跑过 me.chanjar.weixin.cp.api.impl.WxCpMediaServiceImplTest 里的测试代码，我刚试了没有问题的

**Comment by binarywang** [comment]
你可以自己检查下

> 跑了一下没有问题， 想问一下是否和依赖导入有关。或者我获取WxCpService及WxCpMediaService有什么问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月19日(星期二) 晚上6:11 收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;; 抄送:&nbsp;" "<1005996526@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 企业微信上传文件方法header body内容似乎出错 (#1569) 你是否跑过 me.chanjar.weixin.cp.api.impl.WxCpMediaServiceImplTest 里的测试代码，我刚试了没有问题的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by siTsang546** [comment]
问题已经解决，最后感谢你的帮忙。错误出自我的代码，临时文件创建出来的是错误文件所以无法上传。不好意思麻烦你了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 上午10:27
收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;;
抄送:&nbsp;" "<1005996526@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/WxJava] 企业微信上传文件方法header body内容似乎出错 (#1569)





 
你可以自己检查下
  
跑了一下没有问题， 想问一下是否和依赖导入有关。或者我获取WxCpService及WxCpMediaService有什么问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Binary Wang"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月19日(星期二) 晚上6:11 收件人:&nbsp;"Wechat-Group/WxJava"<WxJava@noreply.github.com&gt;; 抄送:&nbsp;" "<1005996526@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Wechat-Group/WxJava] 企业微信上传文件方法header body内容似乎出错 (#1569) 你是否跑过 me.chanjar.weixin.cp.api.impl.WxCpMediaServiceImplTest 里的测试代码，我刚试了没有问题的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
