### ISSUE TITLE
mp包中的WxMpTemplateIndustryEnum反序列化bug

### ISSUE THREAD

**Issue by windysea** [binarywang/WxJava#1571]
WxMpTemplateIndustryEnum 枚举反序列化时，使用WxMpIndustryGsonAdapter
通过convertFromJson 返回WxMpTemplateIndustryEnum时通过WxMpTemplateIndustryEnum.findBySecondary(secondClass)方法中的equals(secondClass)返回枚举，而反序列化的adapter中却通过截取字符串返回secondClass
if (secondClass.contains("|")) {
      secondClass = secondClass.split("\\|")[1];
    }

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1413  楼主是否看过这里，并跑下对应的单元测试看看？

**Comment by binarywang** [comment]
目前在当前基础上对代码进行了尽可能的优化，以减少由于官方文档跟实际接口不一致情况导致的问题。当然如果以后官方接口还要继续做调整，无法完全兼顾的话，再考虑做彻底的改造。
