### ISSUE TITLE
APP支付随机串nonceStr不对

### ISSUE THREAD

**Issue by a529783903** [binarywang/WxJava#1572]
APP支付二次确认调起微信支付，nonceStr的随机串不能使用新生成的随机串，需要使用微信返回值的随机串，
BaseWxPayServiceImpl.java第280行；

调用支付使用的noncestr这个参数必须和商家服务器调用统一下单接口返回的那个noncestr一致

**Comment by binarywang** [comment]
欢迎直接提交PR。
另外，你说的280行现在已经不一样了，不知道是哪个版本的

**Comment by binarywang** [comment]
其实官方文档并没有强调这一点，这部分代码已经存在多年，相信很多人都在用，没发现问题。
不过为了避免以后微信文档和接口可能会发生变化而无法及时响应，对这部分代码做相应调整也不是不可以。
