### ISSUE TITLE
什么时候支持一下支付宝啊

### ISSUE THREAD

**Issue by danielesk** [binarywang/WxJava#1579]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述

什么时候支持一下支付宝啊

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__

**Comment by binarywang** [comment]
这里是微信专场，不考虑支付宝，谢谢

**Comment by binarywang** [comment]
况且支付宝的sdk据说已经可以直接使用，无需额外支持
