### ISSUE TITLE
WxCpUser  Gender gender 为null的情况 会报错！

### ISSUE THREAD

**Issue by smalltalkhyb** [binarywang/WxJava#1580]
WxCpUser  Gender   是     
    MALE("男", "1"),
    FEMALE("女", "2");

但是企业微信返回的是   "gender":"0" 返回null

**Comment by binarywang** [comment]
确实是有问题，估计之前是没有0的值，后来新加上的

**Comment by binarywang** [comment]
https://work.weixin.qq.com/api/doc/10982 从这个页面就可以看出，之前的值：性别。1表示男性，2表示女性
