### ISSUE TITLE
3.6升级3.8后报类找不到了

### ISSUE THREAD

**Issue by sayid** [binarywang/WxJava#1589]
升级后me.chanjar.weixin.mp.bean.material.WxMpMaterialNews.WxMpMaterialNewsArticle找不到了
### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:3.8

是用法有变吗

**Comment by binarywang** [comment]
请直接看代码，或者看版本升级日志，就知道什么时候发生了重构优化

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1497  具体请看此issue相关代码变更
