### ISSUE TITLE
开放平台获取公众号getAuthorizerAccessToken()方法疑问？版本号： 3.8.0

### ISSUE THREAD

**Issue by liyang-liuna** [binarywang/WxJava#1590]
me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl#getAuthorizerAccessToken()

这个方法在获取/刷新公众号AuthorizerAccessToken后，WxOpenConfigStorage 类仅更新了 AuthorizerAccessToken。没有更新 AuthorizerRefreshToken。这样的话，会不会导致 AuthorizerRefreshToken 无效，导致下次在更新获取 AuthorizerAccessToken时 失败？

**Comment by binarywang** [comment]
@007gzs 如果有时间可以帮忙看下

**Comment by einsitang** [comment]
的确会存在该问题，在ISSUE#1474的基础上补充代码(PR#1677)
