### ISSUE TITLE
企业微信会话存档API

### ISSUE THREAD

**Issue by daur** [binarywang/WxJava#1596]
企业微信会话存档，现在已经为大部分金融标签企业开放。对外的接口，只有通过 JAVA jni 或 C dll 接入，网上有 PHP 版本的 API，应该也是包了 C dll 的。

WxJava 有计划在后面上企业微信会话存档相关功能的 API 么？

**Comment by daur** [comment]
附上文档地址 https://work.weixin.qq.com/api/doc/90000/90135/91360

**Comment by binarywang** [comment]
没权限看到相关文档，希望有权限的小伙伴能够提供相应实现的PR

**Comment by zhaoyuanlu** [comment]
会话存档企业微信，接口是封装好了的。企业微信你的redis存储accessToken没有用agentId区分不同的token，使用起来是有问题的吧。

**Comment by binarywang** [comment]
> 会话存档企业微信，接口是封装好了的。企业微信你的redis存储accessToken没有用agentId区分不同的token，使用起来是有问题的吧。

看了几个接口，好像并没有实现

**Comment by binarywang** [comment]
> 没权限看到相关文档，希望有权限的小伙伴能够提供相应实现的PR

现在貌似开放了文档，希望有权限开发的可以帮忙实现一下代码
