### ISSUE TITLE
微信支付商家券

### ISSUE THREAD

**Issue by joey-happy** [binarywang/WxJava#1597]
### 简要描述
微信支付商家券

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/marketing/busifavor/chapter1_1.shtml

https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/marketing/busifavor/chapter3_1.shtml

**Comment by joey-happy** [comment]
![image](https://user-images.githubusercontent.com/16012082/83479247-9d710400-a4ca-11ea-81b6-7952820b7fa8.png)
https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_3
微信接口升级了 旧的api已经不推荐了

麻烦问您一下  新接口有计划支持吗？

**Comment by binarywang** [comment]
可以考虑
