### ISSUE TITLE
开放平台部分接口token问题

### ISSUE THREAD

**Issue by asiachen** [binarywang/WxJava#1604]
1.第三方开放平台，创建开放平台帐号并绑定公众号/小程序
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/api/account/create.html
文档中说access_token 是指授权公共号或小程序的access_token，
但是请求代码中拿的是第三方的componentAccessToken，
![image](https://user-images.githubusercontent.com/23091777/83754085-f6dd5c80-a69d-11ea-9e56-a9286749e9f4.png)
![image](https://user-images.githubusercontent.com/23091777/83754160-170d1b80-a69e-11ea-93f3-ad90aef039fa.png)
![image](https://user-images.githubusercontent.com/23091777/83754274-4885e700-a69e-11ea-90ac-87878f5f2b81.png)
![image](https://user-images.githubusercontent.com/23091777/83754299-53d91280-a69e-11ea-8a69-f46495cd2914.png)

**Comment by binarywang** [comment]
@007gzs 有空可以看下

**Comment by 007gzs** [comment]
代公众号执行的话 用getMpServiceByAppid获取到的结果执行

**Comment by 007gzs** [comment]
文档里我没看到actoken是公众号的，是因为手机和电脑内容不一样么

**Comment by 007gzs** [comment]
刚看了下，这个函数是 @leeis 在 #900 中增加的，确认下是微信接口改了还是当时写错了

**Comment by asiachen** [comment]
![image](https://user-images.githubusercontent.com/23091777/83844633-eed2fa80-a739-11ea-8d19-fb315f7e69a4.png)
这些接口的access_token都需要修改

**Comment by binarywang** [comment]
既然确实有问题，就准备修复下，如果楼主方便的话，欢迎直接提供PR

**Comment by asiachen** [comment]
我已经修复了  具体怎么提交？

**Comment by asiachen** [comment]
@binarywang @007gzs  非常好改  要不5分钟就能解决了，就把里面的方法放到小程序类中就ok了

**Comment by binarywang** [comment]
> @binarywang @007gzs 非常好改 要不5分钟就能解决了，就把里面的方法放到小程序类中就ok了

参考首页代码贡献指南，谢谢

**Comment by whhya** [comment]
请问在3.8.5.b中是否已经修改 @binarywang @asiachen @007gzs

**Comment by binarywang** [comment]
> 我已经修复了 具体怎么提交？



> 请问在3.8.5.b中是否已经修改 @binarywang @asiachen @007gzs

如果知道怎么改的话，欢迎直接提交PR，以便尽早发布修复版本

**Comment by whhya** [comment]
> > 我已经修复了 具体怎么提交？
> 
> > 请问在3.8.5.b中是否已经修改 @binarywang @asiachen @007gzs
> 
> 如果知道怎么改的话，欢迎直接提交PR，以便尽早发布修复版本

已发起合并请求,麻烦发布修复版本

**Comment by binarywang** [comment]
已合并，等待过几天发布新版本
