### ISSUE TITLE
小程序sdk，getAccessToken 方法报acquire timeouted

### ISSUE THREAD

**Issue by jia19831215** [binarywang/WxJava#1614]
### 简要描述
今天getAccessToken方法报acquire timeouted，头一次遇到，线上生产环境，之后重启web服务才恢复正常，实际调用的是jsCode解析。

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.6.0

### 日志
![image](https://user-images.githubusercontent.com/9972994/84258050-e1a67900-ab48-11ea-9806-b3b9dc52308d.png)

服务代码：
@Override
    public WeChatUserLoginVO createSession(@Validated WeChatCreateSessionRequest request) {
        WeChatUserLoginVO weChatUserLoginVO = new WeChatUserLoginVO();
        String systemCode = (String) RequestBag.getValue(StaticVar.HeaderKeyNames.SYSTEM_CODE);
        WeChatAppInfo appInfo = WxMaServiceContainer.getWeChatConfigs().get(systemCode);

        if (appInfo == null) {
            throw new BusinessException("没有找到对应的 AppInfo", 6000);
        }
        WxMaJscode2SessionResult result;
        try {
            result = WxMaServiceContainer.getMaService(appInfo.getAppId()).jsCode2SessionInfo(request.getJscode());
        } catch (WxErrorException ce) {
            switch (ce.getError().getErrorCode()) {
                case -1:
                    throw new BusinessException("微信接口系统繁忙", 6001);
                case 40029:
                    throw new BusinessException("JsCode 无效", 6002);
                case 45011:
                    throw new BusinessException("频率限制，每个用户每分钟100次", 6003);
                default:
                    throw new SystemException(MessageFormat.format("请求微信接口异常：[{0}] {1}", String.valueOf(ce.getError().getErrorCode()), ce.getError().getErrorMsg()));
            }
        } catch (RuntimeException ce) {
            if (ce.getCause() instanceof SocketTimeoutException) {
                throw new SystemException("调用微信超时", 6004);
            } else {
                throw ce;
            }
        }

**Comment by binarywang** [comment]
你这个提示应该是lock异常
