### ISSUE TITLE
h5公众号授权经常行报错{"errcode":40029,"errmsg":"invalid code, hints: [ req_id: UdICunNre-o_pNZa ]"}

### ISSUE THREAD

**Issue by qichaoran** [binarywang/WxJava#1626]
以下代码，查了下说是code重复请求。但是code是微信回调的，没法重新生成吧，也没看到重新生成的api
public  String getAccessToken(String code,String appId){
        String accessToken="";
        WxMpService wxMpService =wechatService.getWxOpenComponentService().getWxMpServiceByAppid(appId);
        try {
            WxMpOAuth2AccessToken wxMpOAuth2AccessToken = wxMpService.oauth2getAccessToken(code);
            accessToken=wxMpOAuth2AccessToken.getAccessToken();
        } catch (WxErrorException ex){
            log.error("进入通过网页授权code 换取access token方法getAccessToken发生异常！[{}]",ex.getError());
        }
        return accessToken;
    }

**Comment by einsitang** [comment]
我想应该是你客户端重复提交了code，你应该查看一下每次请求的log，看下是否存在相同的重复请求，如果是微服务调用的话，看下有没有可能是类似网络抖动的重试机制引起的

**Comment by qichaoran** [comment]
> 
> 
> 我想应该是你客户端重复提交了code，你应该查看一下每次请求的log，看下是否存在相同的重复请求，如果是微服务调用的话，看下有没有可能是类似网络抖动的重试机制引起的

有道理，应该也是这个问题，根据code缓存用户信息到本地重复使用看看

**Comment by qichaoran** [comment]
> 
> 
> 我想应该是你客户端重复提交了code，你应该查看一下每次请求的log，看下是否存在相同的重复请求，如果是微服务调用的话，看下有没有可能是类似网络抖动的重试机制引起的

在最终向微信服务器发出去的请求里面，不存在相同的code重复请求。//但是，除了出现这个40029错误返回，还有出现Connection reset，感觉有可能是服务器的网络/防火墙有问题，先联系运维排查看看，谢谢你的回复
