### ISSUE TITLE
微信小程序  获取直播间列表接口 缺少拉取房间总数

### ISSUE THREAD

**Issue by qsfjing** [binarywang/WxJava#1629]
* WxJava 模块名: miniapp
* WxJava 版本号: 3.8.0
WxMaGetLiveInfo getLiveInfo(Integer start, Integer limit) throws WxErrorException
查询接口返回total看接口文档上 感觉应该是返回正在观看直播的人数 应该不是房间的总数
有待认证 麻烦看一下 辛苦了

**Comment by binarywang** [comment]
啥情况，咋关闭了？
