### ISSUE TITLE
微信小程序 直播功能接口 （创建直播、商品等）

### ISSUE THREAD

**Issue by qsfjing** [binarywang/WxJava#1630]
希望尽快增加一下 直播相关接口的完善 辛苦了

**Comment by binarywang** [comment]
请给出具体文档地址

**Comment by qsfjing** [comment]
创建直播间：
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/studio-api.html#1
直播商品相关：
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/commodity-api.html

**Comment by binarywang** [comment]
新版本已支持
