### ISSUE TITLE
建议升级到JDK8

### ISSUE THREAD

**Issue by miemieYaho** [binarywang/WxJava#1631]
### 简要描述
j7已经太陈旧了:
为了支持j7已经有许多依赖包的版本只能维持在低版本
比如:
- jedis在miniapp下只能用2.x的版本(JedisPool不再继承自Pool<Jedis>),
- spring-data-redis也用不了高版本(2.3.0下的接口使用到的api有过调整,RedisTemplateSimpleDistributedLock#83行使用的set方法已经把返回值从void调整为Boolean,导致runtime报错完全不可用)
- 等等......

**Comment by binarywang** [comment]
这个后面可以考虑

**Comment by binarywang** [comment]
本次大版本考虑升级为JDK8
