### ISSUE TITLE
微信支付通知验签失败

### ISSUE THREAD

**Issue by jdev2412** [binarywang/WxJava#1633]
### 简要描述
 微信支付通知验签失败
### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.8.0

### 详细描述
全局配置签名方式为HMAC-SHA256,在通知验证签名环节，微信通知数据signType为空，默认采用MD5验证签名，导致验签失败

**Comment by binarywang** [comment]
parseOrderNotifyResult 现在有一个带signType的重载方法，建议使用这个

**Comment by binarywang** [comment]
请使用最新版本
