### ISSUE TITLE
加载支付p12证书提示密码错误

### ISSUE THREAD

**Issue by 86jkuncle** [binarywang/WxJava#1635]
### 简要描述
加载支付p12证书提示密码错误

### 模块版本情况
* WxJava 模块名: WxPayConfig
* WxJava 版本号: 3.8.0

### 详细描述
证书密码默认就是商户号,从来没有改过,但是在使用这个接口 https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers 支付时,在加载支付证书的时候,总是提示密码错误

**Comment by binarywang** [comment]
重新生成下证书再试试吧

**Comment by 86jkuncle** [comment]
@binarywang 我把证书重新生成就没有这个问题了,但是我发现请求报文里面的check_name是FORCE_CHECK，能不能改成NO_CHECK呢，现在的返回信息是　返回代码：SUCCESS，返回信息：支付失败，结果代码：FAIL，错误代码：NAME_MISMATCH，错误详情：真实姓名不一致.

**Comment by 86jkuncle** [comment]
已经解决了,是我传参的问题,谢谢了
