### ISSUE TITLE
集成支付模块的时候WxPayService没法创建bean

### ISSUE THREAD

**Issue by tuituji111** [binarywang/WxJava#1636]
### 简要描述
集成支付模块的时候WxPayService没法创建bean
### 模块版本情况
* WxJava 模块名: wxpay
* WxJava 版本号:3.8.0

### 详细描述
集成支付模块的时候WxPayService没法创建bean

### 日志
Parameter 1 of constructor in com.github.niefy.modules.generator.controller.UserprizeController required a bean of type 'com.github.binarywang.wxpay.service.WxPayService' that could not be found.

**Comment by binarywang** [comment]
请参考demo代码，你的问题是属于spring基础问题

**Comment by zhangshaojun890911** [comment]
你好，我也遇到这个问题了，请问怎么解决的
