### ISSUE TITLE
微信支付sdk没有图片上传的接口

### ISSUE THREAD

**Issue by asiachen** [binarywang/WxJava#1639]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/applyment4sub/chapter3_1.shtml

https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/tool/chapter3_1.shtml

这些接口，是那个模块下？  还是再微信支付下用v3接口自己实现？

**Comment by binarywang** [comment]
v3的接口比较新，还没来得及实现
