### ISSUE TITLE
能否支持刷卡支付API

### ISSUE THREAD

**Issue by shanShanKate** [binarywang/WxJava#164]
接口API地址
https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1#

3ks

**Comment by shanShanKate** [comment]
不好意思  看到补充了相关API  但是好像项目里还未补充

**Comment by binarywang** [comment]
没错，还没来得及实现。#101

**Comment by shanShanKate** [comment]
谢谢回复 希望尽快补充到项目  3ks

**Comment by binarywang** [comment]
请关注#101 即可
