### ISSUE TITLE
JedisDistributedLock 编译错误

### ISSUE THREAD

**Issue by timmyz** [binarywang/WxJava#1640]
https://github.com/Wechat-Group/WxJava/blob/86f3c42cfcc85df5c03665027ac9f0a0ef2b30ca/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/locks/JedisDistributedLock.java#L22

参考 jedis-lock 的源码，没有这样一个 string 参数的构造方法
https://github.com/abelaska/jedis-lock/blob/master/src/main/java/com/github/jedis/lock/JedisLock.java

**Comment by binarywang** [comment]
编译不通过的话，打包就不可能成功的。你先核对下版本吧

**Comment by timmyz** [comment]
> 编译不通过的话，打包就不可能成功的。你先核对下版本吧

发现了，原来 github 上的源码跟 maven 仓上的不一致，汗，打扰了

**Comment by binarywang** [comment]
不一致很正常，如果一致，说明这个项目很久没更新了，基本就很危险了
