### ISSUE TITLE
企业微信OA申请（/cgi-bin/oa/applyevent）接口

### ISSUE THREAD

**Issue by dfish01** [binarywang/WxJava#1641]
我看3.8.0 分支里面的配置了链接但是没有实现相关逻辑。
![image](https://user-images.githubusercontent.com/28617683/85526458-9c03a900-b63c-11ea-86a5-fbf1b1bf20fd.png)

**Comment by binarywang** [comment]
欢迎直接提供实现代码，提交PR即可

**Comment by binarywang** [comment]
文档地址：https://work.weixin.qq.com/api/doc/90000/90135/91853

**Comment by binarywang** [comment]
3.8.6.B版本已增加该接口，欢迎使用
