### ISSUE TITLE
微信分账结果查询bug修复

### ISSUE THREAD

**Issue by shellk** [binarywang/WxJava#1642]
# 对于微信分账结果查询接口总是报错问题修复
# 因在请求参数中多了appId字段。

## 修复方式
##需要设置appId为null
`
@Override
  public ProfitSharingQueryResult profitSharingQuery(ProfitSharingQueryRequest request) throws WxPayException {
    this.payService.getConfig().setAppId(null);    
    request.checkAndSign(this.payService.getConfig());
    String url = this.payService.getPayBaseUrl() + "/pay/profitsharingquery";
    String responseContent = this.payService.post(url, request.toXML(), true);
    ProfitSharingQueryResult result = BaseWxPayResult.fromXML(responseContent, ProfitSharingQueryResult.class);
    result.formatReceivers();
    result.checkResult(this.payService, request.getSignType(), true);
    return result;
  }
`

**Comment by binarywang** [comment]
欢迎直接提交PR

**Comment by binarywang** [comment]
这个问题曾经修复过，请参考：
https://github.com/Wechat-Group/WxJava/pull/1378/files

请确认你所使用sdk版本号，也许你的问题可能是因为自己request里指定了appid导致的。

**Comment by binarywang** [comment]
无响应，暂时关闭
