### ISSUE TITLE
小程序直播商品库功能的API有吗？

### ISSUE THREAD

**Issue by wangpanke** [binarywang/WxJava#1645]
小程序直播】直播商品管理接口
官方API地址：https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/commodity-api.html

**Comment by wangpanke** [comment]
小程序直播商品库功能的API有吗？

**Comment by binarywang** [comment]
还没支持，如果可以欢迎实现代码后提交PR，如果有相关接口权限的话实现起来应该不难

**Comment by lipengjun92** [comment]
我们项目迫切需要这个，我准备这几天开发，然后提交pr

**Comment by binarywang** [comment]
最新测试版本已添加
