### ISSUE TITLE
企业微信 服务商第三方应用开发，路由的配置没有支持。

### ISSUE THREAD

**Issue by soulmz** [binarywang/WxJava#1646]
WxCpTpService 类实现了，但是相关的 *MessageRoute 、*MessageInterceptor 等都没有。

### 模块版本情况
* WxJava 模块名:  wx-java-cp
* WxJava 版本号:  3.8.0

CpTp 相关的功能，并没有实现完整的开发示例。

相关的开发方式，可能需要增加实现。

https://github.com/Wechat-Group/WxJava/issues/1480

**Comment by yangdehong** [comment]
问一下，WxCpTpService这个可以直接用注解注入吗。不能的话要怎么用

**Comment by binarywang** [comment]
> 问一下，WxCpTpService这个可以直接用注解注入吗。不能的话要怎么用

自己new实例

**Comment by binarywang** [comment]
3.9.3.B已重构，添加相关支持
