### ISSUE TITLE
3.8为什么增加了这么多强依赖包

### ISSUE THREAD

**Issue by jqncc** [binarywang/WxJava#1654]
升级到3.8 jodd-http, jackson-databind,joda-time这几个包怎么成强依赖了??这些包都用的不多,为什么不能可选,容易跟原项目选型冲突.

**Comment by binarywang** [comment]
这几个应该是微信支付模块引入的吧，因为加入v3接口支持的原因。之前简化了一部分，但是暂时没找到更合适的替代，如果可以，欢迎直接提供更好的实现以及PR，当然我们后期还会持续优化的。

**Comment by binarywang** [comment]
后续优化，如果楼主有兴趣，欢迎随时提交PR
