### ISSUE TITLE
文档过期

### ISSUE THREAD

**Issue by justinyoureyes** [binarywang/WxJava#1655]
有时间的话可以吧文档更新一下有的过期了

**Comment by binarywang** [comment]
请指出具体的文档，另外如果发现过期，可以直接在上面修改即可，人人都可以修改的

**Comment by justinyoureyes** [comment]
好的谢谢!发图文消息那部分有些类最新版本已经没有了

**Comment by binarywang** [comment]
> 好的谢谢!发图文消息那部分有些类最新版本已经没有了

其实可以参考对应的单元测试，最直观了。一般对应文档里会注明单元测试地址的，如果没有，请指出
