### ISSUE TITLE
获取用户信息的时候有些数据获取不到

### ISSUE THREAD

**Issue by NeverBefore** [binarywang/WxJava#1657]
WxMpOAuth2AccessToken accessToken = this.wxMpService.oauth2getAccessToken(code);
        WxMpUser wxMpUser = this.wxMpService.getUserService()
                .userInfo(accessToken.getOpenId());

        String openId = wxMpUser.getOpenId();
        String nickname = wxMpUser.getNickname();
        Integer sex = wxMpUser.getSex();
        String headImgUrl = wxMpUser.getHeadImgUrl();
        String province = wxMpUser.getProvince();
        String city = wxMpUser.getCity();
        String country = wxMpUser.getCountry();
        String unionId = accessToken.getUnionId();

返回结果
{
  "code": 0,
  "msg": "success",
  "data": {
    "country": "null",
    "unionId": "o-LC9uM6Fq9jKHGTJKwx5LPvXo3A",
    "headImgUrl": "null",
    "province": "null",
    "city": "null",
    "openId": "ogrdYt68Ymm3s5NN0SPMES1XMb-0",
    "sex": null,
    "nickname": "null"
  }
}
有的账号可以拿到信息，有的拿不到

**Comment by binarywang** [comment]
这是官方接口的问题，人家不提供的话你确实是没法获取的
