### ISSUE TITLE
微信小程序直播同步直播间微信要求必须使用https，请修改

### ISSUE THREAD

**Issue by xuweihuang623** [binarywang/WxJava#1658]
错误代码：43003, 错误信息：require https hints: [1jBdqy2Pe-Eaayfa!]，微信原始报文：{"errcode":43003,"errmsg":"require https hints: [1jBdqy2Pe-Eaayfa!]"}
微信小程序同步直播间的时候要求必须使用https，而程序中使用的http，现在请求微信强制返回报错

# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，尤其是常见问题部分。完成内容后，请务必移除包括本句在内的无用内容，以免影响阅读，否则直接关闭，谢谢合作~
# 另外如果确认属于bug，而且已明确如何修复，请参考贡献指南直接提交PR，省的浪费时间在这里描述问题，非常感谢配合

### 简要描述
__简单概括描述下你所遇到的问题。__

### 模块版本情况
* WxJava 模块名: 
* WxJava 版本号:

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__

### 日志
__将日志放在 [pastebin](https://paste.ubuntu.com/) 或者其他地方，并将其url地址贴在这里__

**Comment by binarywang** [comment]
最新版本已修复

**Comment by xuweihuang623** [comment]
啥时候能发布？

**Comment by binarywang** [comment]
即将发布，请关注WxJava公众号信息
