### ISSUE TITLE
微信支付的相关接口

### ISSUE THREAD

**Issue by githubxqz** [binarywang/WxJava#166]
WxMpPayService payService = wxMpService.getPayService();
版主，现在我想写个支付网关，包含微信app支付和微信公众号支付，
问下目前所实现的支付接口是否只是适合公众号支付？？

**Comment by binarywang** [comment]
目前开发版本已经将支付单独独立出来了，跟公众号无关，本来很多接口是适合各种场景的。

**Comment by githubxqz** [comment]
好的，谢谢
