### ISSUE TITLE
小程序发送订阅消息，请求参数格式不一致

### ISSUE THREAD

**Issue by 1677612666** [binarywang/WxJava#1665]
### 简要描述
小程序发送订阅消息的data参数与官方类型不一致

### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号: 3.8.0

### 详细描述
public class WxMaSubscribeMessage implements Serializable {
    ....
    private List<WxMaSubscribeMessage.Data> data;

官方data参数是Object

**Comment by binarywang** [comment]
请不要只看表面现象，就以为有问题，你是否真正运行过代码，发现确实有问题？

请仔细看源码实现，这个结构是方便开发而定义的。

**Comment by 1677612666** [comment]
有没有文档可以参考，不清楚怎么赋值进去，谢谢！

**Comment by 1677612666** [comment]
> 请不要只看表面现象，就以为有问题，你是否真正运行过代码，发现确实有问题？
> 
> 请仔细看源码实现，这个结构是方便开发而定义的。

之前赋值过一次出错了。有没有可以参考的文档，不清楚怎么赋值进去，谢谢！

**Comment by binarywang** [comment]
> > 请不要只看表面现象，就以为有问题，你是否真正运行过代码，发现确实有问题？
> > 请仔细看源码实现，这个结构是方便开发而定义的。
> 
> 之前赋值过一次出错了。有没有可以参考的文档，不清楚怎么赋值进去，谢谢！

调用set方法，给需要的字段赋值，不知道字段什么意思，可以看javadoc或者微信官方文档，很容易找到对应关系
