### ISSUE TITLE
微信支付-电商收付通

### ISSUE THREAD

**Issue by UncleDrewGo** [binarywang/WxJava#1667]
微信推出的新功能  ，电商收付通。
作者得空，可以将这部分功能集成进去。

微信文档地址
https://pay.weixin.qq.com/index.php/public/public_tools/index/toolkit/toolkit_details/3001

**Comment by ZenCoderWu** [comment]
+1
最近准备接入这个，希望作者可以安排

现在准备fork，然后自己按照框架先接入吧

**Comment by ZenCoderWu** [comment]
> > +1
> > 最近准备接入这个，希望作者可以安排
> > 
> > 现在准备fork，然后自己按照框架先接入吧
> 
看了下开发分支，好像已经在弄了，那我再等等吧 哈哈

**Comment by binarywang** [comment]
> > > +1
> > > 最近准备接入这个，希望作者可以安排
> > > 现在准备fork，然后自己按照框架先接入吧
> 
> 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈

并没有啊，你怎么判断的？你来接吧

**Comment by ZenCoderWu** [comment]
> > > > +1
> > > > 最近准备接入这个，希望作者可以安排
> > > > 现在准备fork，然后自己按照框架先接入吧
> > 
> > 
> > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> 
> 并没有啊，你怎么判断的？你来接吧

开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
也可以使用测试版
```
<dependency>
  <groupId>com.github.binarywang</groupId>
  <artifactId>weixin-java-pay</artifactId>
  <version>3.8.8.B</version>
</dependency>
```

**Comment by binarywang** [comment]
> > > > > +1
> > > > > 最近准备接入这个，希望作者可以安排
> > > > > 现在准备fork，然后自己按照框架先接入吧
> > > 
> > > 
> > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > 
> > 
> > 并没有啊，你怎么判断的？你来接吧
> 
> 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> 也可以使用测试版
> 
> ```
> <dependency>
>   <groupId>com.github.binarywang</groupId>
>   <artifactId>weixin-java-pay</artifactId>
>   <version>3.8.8.B</version>
> </dependency>
> ```
你想说啥？这只是发布的测试版，跟这个功能有啥关系

**Comment by ZenCoderWu** [comment]
> > > > > > +1
> > > > > > 最近准备接入这个，希望作者可以安排
> > > > > > 现在准备fork，然后自己按照框架先接入吧
> > > > 
> > > > 
> > > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > > 
> > > 
> > > 并没有啊，你怎么判断的？你来接吧
> > 
> > 
> > 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> > 也可以使用测试版
> > ```
> > <dependency>
> >   <groupId>com.github.binarywang</groupId>
> >   <artifactId>weixin-java-pay</artifactId>
> >   <version>3.8.8.B</version>
> > </dependency>
> > ```
> 
> 你想说啥？这只是发布的测试版，跟这个功能有啥关系

尴尬

**Comment by binarywang** [comment]
> > > > > +1
> > > > > 最近准备接入这个，希望作者可以安排
> > > > > 现在准备fork，然后自己按照框架先接入吧
> > > 
> > > 
> > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > 
> > 
> > 并没有啊，你怎么判断的？你来接吧
> 
> 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> 也可以使用测试版
> 
> ```
> <dependency>
>   <groupId>com.github.binarywang</groupId>
>   <artifactId>weixin-java-pay</artifactId>
>   <version>3.8.8.B</version>
> </dependency>
> ```

如果是想贡献代码，参考代码贡献指南，自己新建分支，然后编写代码，测试没问题后，提交PR即可

**Comment by ZenCoderWu** [comment]
> > > > > > +1
> > > > > > 最近准备接入这个，希望作者可以安排
> > > > > > 现在准备fork，然后自己按照框架先接入吧
> > > > 
> > > > 
> > > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > > 
> > > 
> > > 并没有啊，你怎么判断的？你来接吧
> > 
> > 
> > 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> > 也可以使用测试版
> > ```
> > <dependency>
> >   <groupId>com.github.binarywang</groupId>
> >   <artifactId>weixin-java-pay</artifactId>
> >   <version>3.8.8.B</version>
> > </dependency>
> > ```
> 
> 你想说啥？这只是发布的测试版，跟这个功能有啥关系

看到了已经在弄进件了呀，支付这块还没有哦。。。。

**Comment by ZenCoderWu** [comment]
> > > > > > +1
> > > > > > 最近准备接入这个，希望作者可以安排
> > > > > > 现在准备fork，然后自己按照框架先接入吧
> > > > 
> > > > 
> > > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > > 
> > > 
> > > 并没有啊，你怎么判断的？你来接吧
> > 
> > 
> > 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> > 也可以使用测试版
> > ```
> > <dependency>
> >   <groupId>com.github.binarywang</groupId>
> >   <artifactId>weixin-java-pay</artifactId>
> >   <version>3.8.8.B</version>
> > </dependency>
> > ```
> 
> 如果是想贡献代码，参考代码贡献指南，自己新建分支，然后编写代码，测试没问题后，提交PR即可

收到

**Comment by binarywang** [comment]
> > > > > > > +1
> > > > > > > 最近准备接入这个，希望作者可以安排
> > > > > > > 现在准备fork，然后自己按照框架先接入吧
> > > > > 
> > > > > 
> > > > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > > > 
> > > > 
> > > > 并没有啊，你怎么判断的？你来接吧
> > > 
> > > 
> > > 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> > > 也可以使用测试版
> > > ```
> > > <dependency>
> > >   <groupId>com.github.binarywang</groupId>
> > >   <artifactId>weixin-java-pay</artifactId>
> > >   <version>3.8.8.B</version>
> > > </dependency>
> > > ```
> > 
> > 
> > 你想说啥？这只是发布的测试版，跟这个功能有啥关系
> 
> 看到了已经在弄进件了呀，支付这块还没有哦。。。。

进件有很多种，你不会是看见有进件的字样，就以为在开发了吧？你需要看对应的接口是不是一样，不能只看部分汉字

**Comment by ZenCoderWu** [comment]
> > > > > > > > +1
> > > > > > > > 最近准备接入这个，希望作者可以安排
> > > > > > > > 现在准备fork，然后自己按照框架先接入吧
> > > > > > 
> > > > > > 
> > > > > > 看了下开发分支，好像已经在弄了，那我再等等吧 哈哈
> > > > > 
> > > > > 
> > > > > 并没有啊，你怎么判断的？你来接吧
> > > > 
> > > > 
> > > > 开发分支->https://github.com/Wechat-Group/WxJava/tree/develop
> > > > 也可以使用测试版
> > > > ```
> > > > <dependency>
> > > >   <groupId>com.github.binarywang</groupId>
> > > >   <artifactId>weixin-java-pay</artifactId>
> > > >   <version>3.8.8.B</version>
> > > > </dependency>
> > > > ```
> > > 
> > > 
> > > 你想说啥？这只是发布的测试版，跟这个功能有啥关系
> > 
> > 
> > 看到了已经在弄进件了呀，支付这块还没有哦。。。。
> 
> 进件有很多种，你不会是看见有进件的字样，就以为在开发了吧？你需要看对应的接口是不是一样，不能只看部分汉字

嗯，可能脑袋瓦特了

**Comment by ZenCoderWu** [comment]
@binarywang 已经在开发了

**Comment by binarywang** [comment]
> @binarywang 已经在开发了

期待你的代码，争取赶上新版本发布

**Comment by binarywang** [comment]
@githubwyj  已经有人提交代码了，不是你吧？ #1718

**Comment by ZenCoderWu** [comment]
> @githubwyj 已经有人提交代码了，不是你吧？ #1718

尴尬，我在等个测试号，这边还在申请
[我的提交历史](https://github.com/githubwyj/WxJava/commit/fc61838335aff05a6973476f6134fbda9b59286d)

**Comment by binarywang** [comment]
> > @githubwyj 已经有人提交代码了，不是你吧？ #1718
> 
> 尴尬，我在等个测试号，这边还在申请
> [我的提交历史](https://github.com/githubwyj/WxJava/commit/fc61838335aff05a6973476f6134fbda9b59286d)
那你可以基于目前最新版本进行开发

**Comment by ZenCoderWu** [comment]
> > > @githubwyj 已经有人提交代码了，不是你吧？ #1718
> > 
> > 
> > 尴尬，我在等个测试号，这边还在申请
> > [我的提交历史](https://github.com/githubwyj/WxJava/commit/fc61838335aff05a6973476f6134fbda9b59286d)
> > 那你可以基于目前最新版本进行开发

嗯好
