### ISSUE TITLE
企业微信多个agent存储到redis的key没有隔离

### ISSUE THREAD

**Issue by winter0245** [binarywang/WxJava#1669]
企业微信多个agent存储到redis的key没有隔离，使用了固定的key，会导致后续发到各应用的消息失败

### 模块版本情况
* WxJava 模块名: weixin\-java\-cp
* WxJava 版本号: 3.5.0

### 详细描述
企业微信多个agent存储到redis的key没有隔离，使用了固定的key，会导致后续发到各应用的消息失败
参看代码 WxCpRedisConfigImpl类，最新版本依然存在这个问题

**Comment by zhaoyuanlu** [comment]
这个自己继承一下base类，加到key的后缀里面就行了。还有不是每一个agent都有id的，企微自带的应用是没有的。

**Comment by winter0245** [comment]
> 这个自己继承一下base类，加到key的后缀里面就行了。还有不是每一个agent都有id的，企微自带的应用是没有的。

嗯，目前也是这么做的
