### ISSUE TITLE
小程序订阅消息的数据格式不对

### ISSUE THREAD

**Issue by AaronFeng2014** [binarywang/WxJava#1670]
官方数据结构中，data节点不是list
# 目前的格式
{
    "toUser":"userInfoDto.getOpenid()",
    "templateId":"QAFvV1AEE4_r99NJYylxLGkEsrSVLVm7KXWKifous14",
    "page":null,
    "data":[
        {
            "name":"hah",
            "value":"ttt"
        },
        {
            "name":"hah",
            "value":"ttt"
        },
        {
            "name":"hah",
            "value":"ttt"
        }
    ],
    "miniprogramState":"formal",
    "lang":"zh_CN"
}

#微信官方格式
{
  "touser": "OPENID",
  "template_id": "TEMPLATE_ID",
  "page": "index",
  "data": {
      "name01": {
          "value": "某某"
      },
      "amount01": {
          "value": "￥100"
      },
      "thing01": {
          "value": "广州至北京"
      } ,
      "date01": {
          "value": "2018-01-01"
      }
  }
}

**Comment by binarywang** [comment]
你确定使用正确？请参考单元测试实现，不要以自己认为可行的方式生成json

**Comment by binarywang** [comment]
楼主使用错误，请仔细核实
