### ISSUE TITLE
公众号的配置信息持久化的问题

### ISSUE THREAD

**Issue by vic-miao** [binarywang/WxJava#1672]
如果是多个公众号的话，那配置信息怎么持久化呢，默认的保存在内存中在集群环境下肯定不行啊，有啥好方法啊各位大佬

**Comment by gentryhuang** [comment]
可以把多个公众号的配置信息写在配置文件中，或者交给配置中心管理。项目启动即加载到内存中，至于切换公众号的配置，作者已经实现了。

**Comment by binarywang** [comment]
sdk里本身提供了redis的存储实现
