### ISSUE TITLE
微信小程序多账号支持

### ISSUE THREAD

**Issue by gentryhuang** [binarywang/WxJava#1673]
网页授权支持多个公众号功能，目前小程序好像仅支持一个账号，能否支持多个账号的功能？目前我所了解的方案是通过继承WxMaServiceImpl类，实现支持切换多账号功能。

**Comment by flyfeifei66** [comment]
同问，目前我们是自己new多个WxMaService实现的。

**Comment by binarywang** [comment]
重复 #1267

**Comment by binarywang** [comment]
新版本即将支持
