### ISSUE TITLE
希望添加境外普通商户版本的报关接口

### ISSUE THREAD

**Issue by lmhfq** [binarywang/WxJava#1678]
项目中用了wxjava微信支付相关的包，但是其实用到报关相关接口的时候发现没有该功能，希望能加入

**Comment by binarywang** [comment]
请给出具体文档地址

**Comment by lmhfq** [comment]
https://pay.weixin.qq.com/wiki/doc/api/external/index.html

**Comment by binarywang** [comment]
其实文档地址应该是这个：
https://pay.weixin.qq.com/wiki/doc/api/external/declarecustom.php?chapter=18_1

**Comment by lmhfq** [comment]
对，我发的是入口地址
