### ISSUE TITLE
1. 公司：[上海极吼吼](https://www.hohofast.com/)

### ISSUE THREAD

**Issue by zpp0318** [binarywang/WxJava#1680]
1. 公司：[上海极吼吼](https://www.hohofast.com/)

2. 使用的模块：`weixin-java-miniapp`

3. 使用的版本：`3.8.0`

4. 小程序：极吼吼手机上门回收换新

5. 项目进度：已上线

_Originally posted by @hb0730 in https://github.com/Wechat-Group/WxJava/issues/729#issuecomment-648486797_

**Comment by binarywang** [comment]
这是干啥呢？

**Comment by zpp0318** [comment]
想参考一下你当初接开放方平台的代码 就瞎点呢




| |
邹盼
|
|
邮箱：zpp0318@163.com
|

签名由 网易邮箱大师 定制

在2020年07月23日 17:21，Binary Wang 写道：

Closed #1680.
