### ISSUE TITLE
微信公众号对话能力（原导购助手）接口

### ISSUE THREAD

**Issue by daur** [binarywang/WxJava#1686]
### 简要描述
微信公众号，以公众号客服身份和粉丝会话，并衍生相关的一系列功能，如客服分配，公众号粉丝会话相关等等

### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/Shopping_Guide/guide.html#%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D

**Comment by binarywang** [comment]
正在准备实现部分接口

**Comment by binarywang** [comment]
接口太多，有需要的接口，请单独提出并跟踪实现
