### ISSUE TITLE
消息路由异步时，hander中无法获取appid

### ISSUE THREAD

**Issue by feihua666** [binarywang/WxJava#1687]
在消息路由配置异步执行时，由于是新开的线程执行，因为当前appid绑定在了WxMpConfigStorageHolder中，使用的线程变量，这样异步执行就获取不到了
```

        futures.add(
          this.executorService.submit(new Runnable() {
            @Override
            public void run() {
wxMpService.switchoverTo(appid); ----------------------------是不是加在这里可以
              rule.service(wxMessage, context, mpService, WxMpMessageRouter.this.sessionManager, WxMpMessageRouter.this.exceptionHandler);
            }
          })
        );
```

**Comment by binarywang** [comment]
不知楼主是否注意到`me.chanjar.weixin.mp.api.WxMpMessageRouter#route(java.lang.String, me.chanjar.weixin.mp.bean.message.WxMpXmlMessage, java.util.Map<java.lang.String,java.lang.Object>)` 该方法的引用关系，已经做过相应处理，不知道你的问题怎么产生的

**Comment by rabbitlhf** [comment]
楼主怎么解决的？

**Comment by nadirvishun** [comment]
@binarywang  个人目前是把`appid`放到`context`中传递过去，但这样有个问题是在`handler`方法中并没有个参数标识这个是异步的还是同步的，导致无法确认应不应该调用`WxMpConfigStorageHolder.remove()`方法，因为如果是异步则需要调用，以免内存泄漏，而同步则不能调用，因为后续可能其它的同步路由还用到。
建议在楼主演示的代码`rule.service(xxx)`方法中增加一个`boolean`型的参数来标识此次调用是否异步，并一直传递到`handler`中。或者是有什么其它的方式吗？
