### ISSUE TITLE
打包后缺少 WxRedisOps

### ISSUE THREAD

**Issue by lwQin** [binarywang/WxJava#1695]
### 简要描述
找不到 WxRedisOps 类

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 3.8.7.B

### 详细描述
开发模式运行时正常的，打成 jar 后运行报找不到 WxRedisOps 类
 
### 日志
 [日志](https://paste.ubuntu.com/p/65JmfJzm8Z/)

**Comment by binarywang** [comment]
是你自己依赖版本问题，可能试图引用两个版本，但实际加载了旧版本
