### ISSUE TITLE
小程序模板消息已过时，希望更新相关订阅消息功能

### ISSUE THREAD

**Issue by ShawnJim** [binarywang/WxJava#1696]
![image](https://user-images.githubusercontent.com/32192263/89162516-c6834300-d5a6-11ea-98d5-3327262ab6f0.png)

**Comment by binarywang** [comment]
早都添加了，你在使用很老的版本吗？

**Comment by ShawnJim** [comment]
- 在开发文档中找到订阅消息接口为如下文档实现：
  一次性订阅消息接口
 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1500374289_66bvB；

- 没有找到如下微信文档接口的API:
https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html

![image](https://user-images.githubusercontent.com/32192263/89164591-df412800-d5a9-11ea-9d7f-95349061d19a.png)

**Comment by ShawnJim** [comment]
有更新的话能指出一下相关接口吗，感谢~

**Comment by binarywang** [comment]
> 有更新的话能指出一下相关接口吗，感谢~

你从mp里当然找不到miniapp相关的接口了

**Comment by binarywang** [comment]
http://binary.ac.cn/weixin-java-miniapp-javadoc/cn/binarywang/wx/miniapp/api/WxMaSubscribeService.html  看这里

**Comment by ShawnJim** [comment]
@binarywang  收到，感谢回复~
