### ISSUE TITLE
企业微信提前审批申请

### ISSUE THREAD

**Issue by chensp0668** [binarywang/WxJava#1697]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
企业微信提前审批申请功能
https://work.weixin.qq.com/api/doc/90000/90135/91853

### 官方文档地址
__请提供所需功能对应的微信官方文档地址以便进行确认。__
https://work.weixin.qq.com/api/doc/90000/90135/91853

**Comment by binarywang** [comment]
#1641 已实现
