### ISSUE TITLE
能增加门店管理接口的Api吗

### ISSUE THREAD

**Issue by maoqinlin** [binarywang/WxJava#17]
希望楼主增加门店管理接口API.

**Comment by binarywang** [comment]
@maoqinlin 可以，但是如果能够提供测试帐号就更好了，要不代码写出来无法验证就不太好了

**Comment by binarywang** [comment]
@maoqinlin  你有时间帮忙添加么？

**Comment by binarywang** [comment]
@maoqinlin  最近添加了一个创建门店的接口，如果有时间你可以帮忙测试下

**Comment by binarywang** [comment]
Done
