### ISSUE TITLE
自定义菜单加入对小程序的支持

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#170]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141013&token=&lang=zh_CN

```
              {
                 "type":"miniprogram",
                 "name":"wxa",
                 "url":"http://mp.weixin.qq.com",
                 "appid":"wx286b93c14bbf93aa",
                 "pagepath":"pages/lunar/index.html",
             },
```

**Comment by binarywang** [comment]
参数 | 是否必须 | 说明
---|---|---
button | 是 | 一级菜单数组，个数应为1~3个
sub_button | 否 | 二级菜单数组，个数应为1~5个
type | 是 | 菜单的响应动作类型，view表示网页类型，click表示点击类型，miniprogram表示小程序类型
name | 是 | 菜单标题，不超过16个字节，子菜单不超过60个字节
key | click等点击类型必须 | 菜单KEY值，用于消息接口推送，不超过128字节
url | view、miniprogram类型必须 | 网页链接，用户点击菜单可打开链接，不超过1024字节。type为miniprogram时，不支持小程序的老版本客户端将打开本url。
media_id | media_id类型和view_limited类型必须 | 调用新增永久素材接口返回的合法media_id
appid | miniprogram类型必须 | 小程序的appid
pagepath | miniprogram类型必须 | 小程序的页面路径

**Comment by binarywang** [comment]
已实现

**Comment by pecdew** [comment]
me.chanjar.weixin.common.util.json.WxMenuGsonAdapter的代码没有处理！

**Comment by binarywang** [comment]
@pecdew  WxMenuGsonAdapter 这个已经不再使用了，现在使用的是注解的方式，你是测试发现问题了么？还只是看了代码？

**Comment by binarywang** [comment]
不好意思，确实是有问题，这个地方代码有点乱，稍后整理修复下
