### ISSUE TITLE
WxMaLiveService的请求路径都写死了http

### ISSUE THREAD

**Issue by huihui-hb** [binarywang/WxJava#1705]
WxMaLiveService的请求路径都写死了http，但是现在微信要https，不然不让提交，求更新。
我先用CP顶一下。

**Comment by binarywang** [comment]
用新版本

**Comment by huihui-hb** [comment]
> 用新版本

已经是新版本了3.80。
另外我发现我这个里面没有WxCpService。！！
这是我第一次使用wxjava

**Comment by binarywang** [comment]
我说的是最新的测试版本，首页可以看到，另外这个WxMaLiveService是小程序里的，怎么可能包含企业微信cp的东西？

**Comment by huihui-hb** [comment]
> 我说的是最新的测试版本，首页可以看到，另外这个WxMaLiveService是小程序里的，怎么可能包含企业微信cp的东西？
铁子秀啊！上了测试版解决了。。。
