### ISSUE TITLE
创建开放平台帐号管理接口，access_token传值错误

### ISSUE THREAD

**Issue by lov3smu** [binarywang/WxJava#1707]
### 简要描述
微信开放平台帐号管理相关接口，access_token传参错误，程序中使用了component_access_token，实际应为授权的微信公众号或小程序的access_token

### 模块版本情况
* WxJava 模块名: weixin-java-open
* WxJava 版本号: 3.6.0

### 详细描述
me.chanjar.weixin.open.api.impl.WxOpenComponentServiceImpl:134 行，参数名为access_token时应取公众号的access_token否则为开放平台的access_token

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/pull/1676  你的问题应该这里已经修复了

**Comment by lov3smu** [comment]
> #1676 你的问题应该这里已经修复了

我看下，谢谢

**Comment by ancoka** [comment]
确认过了，这个BUG确实没有修复
