### ISSUE TITLE
企业付款到零钱接口

### ISSUE THREAD

**Issue by antian369** [binarywang/WxJava#1709]
### 简要描述

现在微信企业付款好像已经没有发送个人红包的功能了，新增了企业付款到零钱相关的接口。

### 官方文档地址

https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2

**Comment by binarywang** [comment]
这个接口不早就有了吗？

http://binary.ac.cn/weixin-java-pay-javadoc/com/github/binarywang/wxpay/service/EntPayService.html#entPay-com.github.binarywang.wxpay.bean.entpay.EntPayRequest-

**Comment by antian369** [comment]
不好意思，没看到第一个就是。。大概是脑子短路了，抱歉！
