### ISSUE TITLE
wxMpService.getMaterialService().materialNewsBatchGet报错Connection pool shut down

### ISSUE THREAD

**Issue by bozer666** [binarywang/WxJava#1712]
### 简要描述
__简单概括描述下你所遇到的问题。__
wxMpService.getMaterialService().materialNewsBatchGet报错Connection pool shut down
集群两台机器一台有问题,重启恢复正常

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 3.8.7.B

### 详细描述
//获取图文消息列表数据
WxMpMaterialNewsBatchGetResult result = wxMpService.getMaterialService().materialNewsBatchGet(offset, pageSize);
获取图文消息列表时报错Connection pool shut down,重启就好了,过段时间又异常,自己写的代码里面没有关闭连接池

### 日志
```
java.lang.IllegalStateException: Connection pool shut down
```

**Comment by binarywang** [comment]
和已有问题重复，请参考之前问题#1523
