### ISSUE TITLE
从 3.8.8.B升级到 3.8.9.B，微信小程序，启动时报错WxMaService。

### ISSUE THREAD

**Issue by Angle-bo** [binarywang/WxJava#1714]
### 简要描述
WxJava 3.8.9.B 测试版 ，小程序服务启动报错

### 模块版本情况
* WxJava 模块名: MA
* WxJava 版本号: 3.8.9.B

### 详细描述
从 3.8.8.B升级到 3.8.9.B，微信小程序，启动时报错WxMaService。

### 日志
__https://paste.ubuntu.com/p/TnVp3mhTCQ/__

**Comment by binarywang** [comment]
稍后修复，谢谢及时试用并指出

**Comment by needou** [comment]
我操 我找这个问题找了一个晚上
