### ISSUE TITLE
Native扫码支付模式支持模式一

### ISSUE THREAD

**Issue by jingshenbusi6530** [binarywang/WxJava#1719]
### 简要描述
在使用Native扫码支付时，发现WxPayNativeOrderResult这个类中只有一个codeUrl属性，即仅支持了模式二，[模式一不支持](https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_4)

### 官方文档地址
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_4

**Comment by binarywang** [comment]
看了下，其实模式一和模式二本质都是返回一个codeUrl，只是内容不同，代码层面好像不太好区分模式一和二，如果你有好的办法，欢迎直接提供PR代码
