### ISSUE TITLE
企业微信群机器人

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#1720]
https://work.weixin.qq.com/help?doc_id=13376

**Comment by it-noob** [comment]
WxCpDefaultConfigImpl 实现类中 webhookKey 的属性里，没有设置 key 的方法。

**Comment by binarywang** [comment]
> WxCpDefaultConfigImpl 实现类中 webhookKey 的属性里，没有设置 key 的方法。

使用最新版，已加上

**Comment by webott** [comment]
可以参考 rotdogmes.cn 功能不少
