### ISSUE TITLE
添加微信支付分免确认模式

### ISSUE THREAD

**Issue by farawayll** [binarywang/WxJava#1725]
目前WxJava中暂时没有相关支持

**Comment by binarywang** [comment]
请给出相关文档地址

**Comment by farawayll** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter2_3.shtml

**Comment by spvycf** [comment]
你可以本地升级到测试版本3.9.5.B先行体验，如果有什么问题，可以在此回复。
https://mp.weixin.qq.com/s/6fEKjGYE4g8c6LAlhrzYEg
