### ISSUE TITLE
WxMpMenu中属性名sub_buttons, 公众号接口是sub_button

### ISSUE THREAD

**Issue by neoliao** [binarywang/WxJava#173]
menu/get这个接口拿不到sub_buttons上的数据，得到的http response原始数据是有的，但是转成JAVA bean就没了

**Comment by binarywang** [comment]
不太明白你说的sub_buttons是哪里的代码，是指这里吗？
```
  @SerializedName("sub_button")
  private List<WxMenuButton> subButtons = new ArrayList<>();
```

**Comment by neoliao** [comment]
是的，就是Java Bean里面拿不到subButtons数据，里面是null，我现在是引用了并修改了源码，直接拿的json来处理

**Comment by binarywang** [comment]
请问你是如何获取的？建议参考下单元测试里的代码，对比一下

**Comment by binarywang** [comment]
没有进一步反馈信息，暂时关闭
