### ISSUE TITLE
问一个很玄学的问题

### ISSUE THREAD

**Issue by chenchengwangS** [binarywang/WxJava#1732]
这是我后端发送的消息模版，里面有一个ur
![消息模版bug](https://user-images.githubusercontent.com/48645534/91510058-85185600-e90e-11ea-9225-2f330f9ea141.png)
可以看到，url里面有一个id，但是当公众号收到这个消息模版的时候，点击跳转到这个url时，
![消息模版1](https://user-images.githubusercontent.com/48645534/91510133-c3157a00-e90e-11ea-82b1-ae64bf16f111.png)
这个messageid有几率为空，但是退出页面，重新点击消息模版后，messageid就有值，整个过程都是一个概率事件，若是出现messageid为空，退出页面，重新点击消息模版，messageid就会有值。

**Comment by chenchengwangS** [comment]
微信公众号的开发

**Comment by chenchengwangS** [comment]
我明白这可能非常大几率不是框架的问题，但是我实在找不到解决方案，应付这样的概率事件

**Comment by chenchengwangS** [comment]
![消息模版2](https://user-images.githubusercontent.com/48645534/91510833-c3167980-e910-11ea-8ec6-f2b13a7bba61.png)

**Comment by binarywang** [comment]
把url地址打印出来看看

**Comment by chenchengwangS** [comment]
> 把url地址打印出来看看

url地址应该是固定的吧？为什么第一次点击的时候没有id（概率出现），第二次点击的时候id就有了

**Comment by binarywang** [comment]
你需要首先确认下url对不对，如果没问题，那可能是微信那边出了bug

**Comment by chenchengwangS** [comment]
> 你需要首先确认下url对不对，如果没问题，那可能是微信那边出了bug

好的谢谢，我打印一下，下次出现的时候关注下这个问题
