### ISSUE TITLE
微信对礼品卡的一系列操作能跟卡券一样封装成api?

### ISSUE THREAD

**Issue by MicroCreativity** [binarywang/WxJava#1735]
### 简要描述
微信对礼品卡的一系列操作能跟卡券一样封装成api?

### 官方文档地址
https://developers.weixin.qq.com/doc/offiaccount/Cards_and_Offer/gift_card.html

**Comment by binarywang** [comment]
本质上也属于卡券接口，建议自己实现还未实现而自己需要的接口，然后提交PR

**Comment by MicroCreativity** [comment]
> > 本质上也属于卡券接口，建议自己实现还未实现而自己需要的接口，然后提交PR
> 
> 好的，还有个事啊，能不能每次升级的时候向下兼容，我是18年版本的，想升级到最新版各种报错，不太敢升级

**Comment by binarywang** [comment]
> > 本质上也属于卡券接口，建议自己实现还未实现而自己需要的接口，然后提交PR
> 
> 好的，还有个事啊，能不能每次升级的时候向下兼容，我是18年版本的，想升级到最新版各种报错，不太敢升级

抱歉，我们会尽量保证兼容，但这样会导致大量垃圾代码，一般过一段时间就会清理掉这些垃圾代码，所以会导致不兼容，请自行根据版本更新日志调整代码，一般来说都是很容易修复的
