### ISSUE TITLE
JedisLock暴露核心配置

### ISSUE THREAD

**Issue by ianjiang** [binarywang/WxJava#1740]
### 简要描述
JedisLock的核心参数都是默认值：
- expireMsecs 60000 ms
- timeoutMsecs 10000 ms

这两个参数，在生产上使用时间太长了，可以考虑将这两个参数暴露出来吗？

这个可能造成服务端的慢请求
![image](https://user-images.githubusercontent.com/1629800/92213447-23d02400-eec6-11ea-8062-f05b6d4f95c7.png)

**Comment by binarywang** [comment]
jedis-lock的实现仅供参考，你可以自行实现一个新的，以满足你的特殊需求

**Comment by ianjiang** [comment]
好的。
