### ISSUE TITLE
企业微信回调消息重复校验bug

### ISSUE THREAD

**Issue by kkkangke** [binarywang/WxJava#1745]
### 简要描述
企业微信回调消息重复校验的参数不太合理，会导致不同的回调被丢弃

### 模块版本情况
* WxJava 模块名:  weixin-java-cp
* WxJava 版本号:  3.6.0

### 详细描述
![A 7F{QF 0)QVO)JQ26{BD)M](https://user-images.githubusercontent.com/37659298/92550538-47141e00-f28e-11ea-91bf-2249a19dbd13.png)
![$ZF~{IBLR@3ZJL306 AY TY](https://user-images.githubusercontent.com/37659298/92550544-4c716880-f28e-11ea-8c5c-c043a57dc4f4.png)
![image](https://user-images.githubusercontent.com/37659298/92550609-788ce980-f28e-11ea-9365-12a8bffc492c.png)

如图，企业微信的两条回调，在同一秒，同一个人，但是回调的内容不一样。后面一个回调会被丢弃，将会影响业务，请问可不可以自己配置不做消息重复校验，或者修改重复校验的逻辑

**Comment by binarywang** [comment]
你是可以自定义消息重复校验的实现类的

**Comment by kkkangke** [comment]
是重写WxCpMessageRouter类的route方法吗？

**Comment by binarywang** [comment]
> 是重写WxCpMessageRouter类的route方法吗？

不用重写啊，router有对应的set方法

**Comment by kkkangke** [comment]
> > 是重写WxCpMessageRouter类的route方法吗？
> 
> 不用重写啊，router有对应的set方法

那是自己实现WxMessageDuplicateChecker接口的isDuplicate方法，然后用WxCpMessageRouter的setMessageDuplicateChecker方法set进去吗？

**Comment by binarywang** [comment]
> > > 是重写WxCpMessageRouter类的route方法吗？
> > 
> > 
> > 不用重写啊，router有对应的set方法
> 
> 那是自己实现WxMessageDuplicateChecker接口的isDuplicate方法，然后用WxCpMessageRouter的setMessageDuplicateChecker方法set进去吗？

就是这个意思

**Comment by kkkangke** [comment]
> > > > 是重写WxCpMessageRouter类的route方法吗？
> > > 
> > > 
> > > 不用重写啊，router有对应的set方法
> > 
> > 
> > 那是自己实现WxMessageDuplicateChecker接口的isDuplicate方法，然后用WxCpMessageRouter的setMessageDuplicateChecker方法set进去吗？
> 
> 就是这个意思

好的，多谢啦

**Comment by nadirvishun** [comment]
> > > 是重写WxCpMessageRouter类的route方法吗？
> > 
> > 
> > 不用重写啊，router有对应的set方法
> 
> 那是自己实现WxMessageDuplicateChecker接口的isDuplicate方法，然后用WxCpMessageRouter的setMessageDuplicateChecker方法set进去吗？

不是很懂，此时的`messageId`都已经确定了，再怎么改`isDuplicate`也没什么用了吧？
我刚看到这个，此前提了个同样的[issue](https://github.com/Wechat-Group/WxJava/issues/3088)
