### ISSUE TITLE
企业微信第三方应用缺少授权配置接口

### ISSUE THREAD

**Issue by ShunqinChen** [binarywang/WxJava#1746]
### 简要描述
1. 企业微信第三方应用,通过第三方网站授权时,需要优先进行授权设置,否则会提示redirect_uri不匹配
2. 查阅了WxCpApiPathConsts暂无此接口对应路径
3. 查阅了WxCpTpService.java及其默认实现BaseWxCpTpServiceImpl,目前只发现了getPreAuthUrl(String redirectUri,String state)方法中获取了预授权码,但是还需要通过预授权码进行授权设置才能使得预授权码对应的授权生效
4. 建议把获取预授权码和设置授权配置的方法单独封装成接口.

### 官方文档地址
https://work.weixin.qq.com/api/doc/90001/90143/90602

**Comment by ShunqinChen** [comment]
已验证过上述内容,通过手动post调用执行,再进行授权成功

**Comment by binarywang** [comment]
建议直接提交PR代码，既然你都已经验证成功了是吧？

**Comment by ShunqinChen** [comment]
谨慎的先问问作者看看是不是在哪漏了,晚点试试提PR

**Comment by binarywang** [comment]
> 谨慎的先问问作者看看是不是在哪漏了,晚点试试提PR

其实我也无法判断，没做过这部分的开发。你可以先把代码提交上来，供他人试用，如果真有问题再修复也不迟。

**Comment by ShunqinChen** [comment]
我也是碰壁了才知道, 看到了官方的回答才做了测试,结果是可以. 
https://developers.weixin.qq.com/community/develop/doc/0002ec92f58cf8e45d89042035b000

**Comment by binarywang** [comment]
楼主是否有计划提交PR代码？
