### ISSUE TITLE
支付分回调通知PayScoreNotifyData缺少参数回调摘要summary

### ISSUE THREAD

**Issue by wanice** [binarywang/WxJava#1747]

**Comment by binarywang** [comment]
下次记得贴上官方文档地址

**Comment by wanice** [comment]
好的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Binary Wang <notifications@github.com&gt;
发送时间: 2020年9月12日 10:09
收件人: Wechat-Group/WxJava <WxJava@noreply.github.com&gt;
抄送: wanice <1009615268@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wechat-Group/WxJava] 支付分回调通知PayScoreNotifyData缺少参数回调摘要summary (#1747)





 
下次记得贴上官方文档地址

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter4_2.shtml

**Comment by wanice** [comment]
还有这个




https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter4_2.shtml

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Binary Wang <notifications@github.com&gt;
发送时间: 2020年9月12日 10:14
收件人: Wechat-Group/WxJava <WxJava@noreply.github.com&gt;
抄送: wanice <1009615268@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wechat-Group/WxJava] 支付分回调通知PayScoreNotifyData缺少参数回调摘要summary (#1747)





 
https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/payscore/chapter4_2.shtml
