### ISSUE TITLE
WxMaLiveInfo 请添加closeReplay 字段以支持小程序直播开启回访

### ISSUE THREAD

**Issue by Yangcjcjlu** [binarywang/WxJava#1753]
# 提问前，请确保阅读过项目首页说明以及wiki开发文档相关内容，完成内容后，请务必移除包括本句在内的无用内容，以免影响他人阅读，否则直接关闭，谢谢合作~

### 简要描述
微信支付官方文档支持服务端传参closeReplay关闭与开启回放

### 官方文档地址
https://developers.weixin.qq.com/miniprogram/dev/framework/liveplayer/studio-api.html

**Comment by binarywang** [comment]
欢迎直接提交PR，这个很简单吧
