### ISSUE TITLE
第三方平台的错误码，能否补充中文提示

### ISSUE THREAD

**Issue by mashining1988111** [binarywang/WxJava#1755]
第三方平台的错误码描述，与全局错误码描述不同，能否针对具体接口使用具体的错误描述，比如快速创建小程序的错误码，都有中文描述，
![image](https://user-images.githubusercontent.com/12853767/92869275-3b169080-f435-11ea-9c14-847ee175d32d.png)
而全局错误码中
![image](https://user-images.githubusercontent.com/12853767/92869491-744f0080-f435-11ea-92f1-a88e5c9a7913.png)
![image](https://user-images.githubusercontent.com/12853767/92869523-7dd86880-f435-11ea-92ee-6aca962977f9.png)
![image](https://user-images.githubusercontent.com/12853767/92869580-8a5cc100-f435-11ea-82bf-410064de4e8d.png)
这里只是简单举几个例子,第三方平台的接口和错误码挺多的，我们做的第三方平台的使用者都是外部用户使用，直接提示英文不太友好，请小伙伴百忙之中优化一下错误码，多谢

**Comment by binarywang** [comment]
如果楼主有空，欢迎直接提交PR，毕竟不是个小的工作量，你可以先添加用户比较关心的一些，一点点来

**Comment by binarywang** [comment]
已补充部分小程序相关的错误码，如果有遗漏，请及时指出，或者自行提交PR，感谢使用。
