### ISSUE TITLE
企业微信增加会议室管理接口

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#1760]
https://work.weixin.qq.com/api/doc/90000/90135/92793

**Comment by ljccccccccccc** [comment]
大佬，您好。付费群满了。
我在Issues里看到cp模块有增加会议室管理的接口，但在代码里没有看到相关的接口，能否指导一下会议室管理的接口在哪里？

**Comment by binarywang** [comment]
qq付费群官方已取消，我也无能为力，你可以加入微信群。

另外按和接口因为没有人需求，暂时没有实现，你如果需要，欢迎参考现有代码自行编码实现并调试，没有问题后可以提交PR上来供大家参考使用
