### ISSUE TITLE
WxJava目前支持企业微信服务商开发吗

### ISSUE THREAD

**Issue by Michael-TY** [binarywang/WxJava#1769]
你好，请问 WxJava支持企业微信服务商开发吗？，我看文档介绍只有企业微信开发，没有涉及微服务商第三方开发的相关说明，还是说我看错地方了
https://work.weixin.qq.com/api/doc/90001/90142/90594

**Comment by binarywang** [comment]
是支持的，第三方应用，接口类：`WxCpTpService`
