### ISSUE TITLE
V2.5.0 获取用户OpenID列表的API风格问题

### ISSUE THREAD

**Issue by huaxia0624** [binarywang/WxJava#177]
WxMpUserList 中：getNextOpenId();
WxMpUserBlacklistGetResult 中：getNextOpenid();

OpenID 一个大写，一个小写。

**Comment by binarywang** [comment]
openid 的问题确实有点让人头疼，以后统一使用openid，因为openid作为微信专有的变量名，不应该被当作两个单词对待
