### ISSUE TITLE
企业微信第一步验证URL报错

### ISSUE THREAD

**Issue by JKD128KKK** [binarywang/WxJava#1770]
### 简要描述
企业微信验证URL的请求不通过,报错nested exception is java.lang.NoSuchMethodError

### 模块版本情况
* WxJava 模块名: weixin-java-cp
* WxJava 版本号: 3.9.0

### 详细描述
__尽量详细描述。请不要使用截图，尽量使用文字描述，代码直接贴上来，日志则请附在后面所示区域。__
![image](https://user-images.githubusercontent.com/39514394/93694268-43a94e00-fb3c-11ea-9b5e-f7603a6074c4.png)

### 日志
https://paste.ubuntu.com/p/pxVXBBVsZH/

**Comment by JKD128KKK** [comment]
![image](https://user-images.githubusercontent.com/39514394/93694314-badee200-fb3c-11ea-841a-8fbe4a6b6beb.png)

**Comment by binarywang** [comment]
大哥，无此方法，说明你对应引用的jar包版本不对，具体是哪个不对，看下就知道了

**Comment by binarywang** [comment]
wiki常见问题里有解决办法
