### ISSUE TITLE
Jodd发布了5.2.0,是不是考虑更新一下依赖

### ISSUE THREAD

**Issue by murainwood** [binarywang/WxJava#1771]
Jodd最近发布了5.2.0版本,但是目前依赖还是5.1.6
建议更新一下依赖的版本呢?

**Comment by binarywang** [comment]
这种依赖问题，你自己指定新版本即可

**Comment by murainwood** [comment]
不是这个问题,而是会有一些类冲突. 比如说, 一些类的package变了, 还有一些常量直接在新版本中被删了. 
比如说StringPool.UTF_8  这种

**Comment by binarywang** [comment]
> 不是这个问题,而是会有一些类冲突. 比如说, 一些类的package变了, 还有一些常量直接在新版本中被删了.
> 比如说StringPool.UTF_8 这种

如果是这种问题建议还是不要使用新版本了，毕竟改造起来也是个问题

**Comment by murainwood** [comment]
我check了一下,要修改的点并不多. 不过5.1.X和5.2, 一些API的变化确实蛮烦人的. 某种程度上说, 建议放弃对Jodd的依赖.  这个库虽然简单优美,奈何版本升级太随心所欲

**Comment by murainwood** [comment]
> > 不是这个问题,而是会有一些类冲突. 比如说, 一些类的package变了, 还有一些常量直接在新版本中被删了.
> > 比如说StringPool.UTF_8 这种
> 
> 如果是这种问题建议还是不要使用新版本了，毕竟改造起来也是个问题

确实是这样, Jodd 5.2,在项目中,我也懒得更新了

**Comment by binarywang** [comment]
最新 develop 代码已尝试更新了对应版本，不过去掉了 `StringPool.UTF_8`的引用，应该没有其他问题。

**Comment by murainwood** [comment]
> 最新 develop 代码已尝试更新了对应版本，不过去掉了 `StringPool.UTF_8`的引用，应该没有其他问题。

嗯，我发现也只有这个地方，还好。。不然太折腾了~~
