### ISSUE TITLE
建议给WxMpMessageRouter增加一个新的构造器

### ISSUE THREAD

**Issue by cnickd** [binarywang/WxJava#1773]
WxMpMessageRouter` 共有如下几个关键参数，建议增加一个包含所有参数的构造器。

`
    private ExecutorService executorService;

    private WxMessageDuplicateChecker messageDuplicateChecker;

    private WxSessionManager sessionManager;

    private WxErrorExceptionHandler exceptionHandler;
`

**Comment by binarywang** [comment]
记得是有对应setter方法，可以先使用
