### ISSUE TITLE
企业微信审批需要区分`系统审批`和`自建应用审批`

### ISSUE THREAD

**Issue by nadirvishun** [binarywang/WxJava#1774]
### 简要描述
- 首先是回调，两者的`EventType`有区别，系统审批的是`sys_approval_change`，自建应用审批的是`open_approval_change`，但目前类库中所有的实现都是系统审批，但在`WxCpConsts`中却定义了自建应用审批的常量`OPEN_APPROVAL_CHANGE`，在使用时如果不注意会有误导。
- 然后是回调通知返回字段，目前类库只实现了系统审批的返回字段，而且还不全，缺少了`SpRecord`(审批流程信息),`Notifyer`(抄送信息)，`Comments`(审批申请备注信息)，而自建应用的回调通知字段也叫`ApprovalInfo`，但内容和系统审核的完全不一致，目前未发现任何实现。
- 自建应用缺少`查询自建应用审批单当前状态`接口

### 官方文档地址
- [系统审批回调](https://work.weixin.qq.com/api/doc/90000/90135/91815)
- [自建应用回调和缺失接口](https://work.weixin.qq.com/api/doc/90000/90135/90269)

**Comment by binarywang** [comment]
欢迎直接提供PR

**Comment by binarywang** [comment]
接口单独添加，新建issue: https://github.com/Wechat-Group/WxJava/issues/1783

**Comment by binarywang** [comment]
通知内容字段过于复杂，目前可以通过`allFieldsMap`自行提取，如果你有更好的实现方法，欢迎提供
