### ISSUE TITLE
请求添加redis哨兵配置支持

### ISSUE THREAD

**Issue by Dream2Land** [binarywang/WxJava#1778]
### 简要描述
目前redis配置地址是单ip版，我看了源代码也没有哨兵和集群（也许vip可以解决）的配置支持。

### 官方文档地址
https://github.com/xetorthio/jedis

**Comment by binarywang** [comment]
本项目中的redis实现是最简单的示例，仅供参考，考虑到本项目的sdk属性并不想引入过多依赖。
如果你自己有需要可以自行实现，也可以提交PR，供其他人参考

**Comment by Dream2Land** [comment]
> 本项目中的redis实现是最简单的示例，仅供参考，考虑到本项目的sdk属性并不想引入过多依赖。
> 如果你自己有需要可以自行实现，也可以提交PR，供其他人参考

我提的这个和host配置的issue都是由于我们没法使用，但是考虑到你们确定需求到发布可能赶不及，我已经找到源代码位置并且打算自己实现，可无奈的是3.9.0release版本竟然有bug跑不起来，java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V，调查发现是spring-data-redis版本冲突问题，common里版本1.8，mp和starter里2.3.3。除非直接用你的demo的3.9.1.B,我把版本升上去又会有其他错误，自己改是没戏了。

**Comment by Dream2Land** [comment]
> > 本项目中的redis实现是最简单的示例，仅供参考，考虑到本项目的sdk属性并不想引入过多依赖。
> > 如果你自己有需要可以自行实现，也可以提交PR，供其他人参考
> 
> 我提的这个和host配置的issue都是由于我们没法使用，但是考虑到你们确定需求到发布可能赶不及，我已经找到源代码位置并且打算自己实现，可无奈的是3.9.0release版本竟然有bug跑不起来，java.lang.NoSuchMethodError: org.springframework.data.redis.connection.RedisConnection.set([B[B)V，调查发现是spring-data-redis版本冲突问题，common里版本1.8，mp和starter里2.3.3。除非直接用你的demo的3.9.1.B,我把版本升上去又会有其他错误，自己改是没戏了。

最后还是用了3.9.3.B（3.9.0有bug），自己修改了mp starter,暂时支持hosts和Redis sentinel

**Comment by binarywang** [comment]
欢迎将你的代码提交PR上来，可以供其他人参考

**Comment by Dream2Land** [comment]
> 欢迎将你的代码提交PR上来，可以供其他人参考

github这个我流程我不太熟悉，我好像拿的3.9.0的release改的，我怕搞岔了。还有别的方式吗？我可以发源代码过来

**Comment by binarywang** [comment]
> > 欢迎将你的代码提交PR上来，可以供其他人参考
> 
> github这个我流程我不太熟悉，我好像拿的3.9.0的release改的，我怕搞岔了。还有别的方式吗？我可以发源代码过来

参考贡献指南即可，不用怕搞错了，尽管提交PR就好，我这边还会检查审核的。最重要的是在develop分支上操作，

**Comment by timmyz** [comment]
> ### 简要描述
> 目前redis配置地址是单ip版，我看了源代码也没有哨兵和集群（也许vip可以解决）的配置支持。
> 
> ### 官方文档地址
> https://github.com/xetorthio/jedis

jedis 是支持哨兵模式的，你可以看下 JedisSentinelPool 这个类
所以主动为 WxMaConfig 注入一个 jedisPool 就可以实现，其实是透明的，上层应用不需要知道底层 redis 的架构是哨兵还是单机模式。
供参考
