### ISSUE TITLE
请求把api host地址配置纳入配置文件

### ISSUE THREAD

**Issue by Dream2Land** [binarywang/WxJava#1779]
### 简要描述
请求把api host地址配置纳入配置文件，目前放在各个组件的config，dns类中。
我们目前是内网代理地址，没法使用原地址。不属于开通端口的情况。

### 官方文档地址
无

**Comment by binarywang** [comment]
请说清楚是哪个模块，目前部分模块是实现了的

**Comment by Dream2Land** [comment]
> 请说清楚是哪个模块，目前部分模块是实现了的

部分实现了吗？我看都是java config的方式呀。反正mp没有。

**Comment by binarywang** [comment]
请稍微详细描述下你的需求，可能是我有误解

**Comment by Dream2Land** [comment]
> 请稍微详细描述下你的需求，可能是我有误解

wx-mp中WxMpHostConfig里有三个微信的host地址配置
public static final String API_DEFAULT_HOST_URL = "https://api.weixin.qq.com";
  public static final String MP_DEFAULT_HOST_URL = "https://mp.weixin.qq.com";
  public static final String OPEN_DEFAULT_HOST_URL = "https://open.weixin.qq.com";

我想在配置文件里配置这三个参数，因为我们用的是代理地址，内网。有什么解决方案？

**Comment by binarywang** [comment]
那我没理解错，你看到过这个方法没：`me.chanjar.weixin.mp.config.WxMpConfigStorage#setHostConfig`

**Comment by Dream2Land** [comment]
> 那我没理解错，你看到过这个方法没：`me.chanjar.weixin.mp.config.WxMpConfigStorage#setHostConfig`

恩，我刚才又翻了好几遍源码，看到了，那是不是我注入WxMpConfigStorage然后set就可以了？
另外，我想问我不在文件配置默认redis，然后自己实现redispool的bean就可以？我看WxMpStorageAutoConfiguration里有从applicationContext读取的动作。
