### ISSUE TITLE
实现代金券接口

### ISSUE THREAD

**Issue by joytom0591** [binarywang/WxJava#178]
文档相关地址:
https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_2

**Comment by binarywang** [comment]
业务流程 | 接口 | 是否需要证书 | 功能说明
-- | -- | -- | --
发放和查询流程1 | 发放代金券 | 是 | 商户给用户发放代金券
发放和查询流程2|查询代金券批次信息 | 否 | 查询代金券批次信息
发放和查询流程3|查询代金券信息 | 否 | 查询代金券信息

**Comment by binarywang** [comment]
2.7.6.BETA测试版本已支持
