### ISSUE TITLE
企业微信创建用户，添加自定义属性，序列化时，忽略了type和name，导致自定义属性未添加上！

### ISSUE THREAD

**Issue by fordCheng** [binarywang/WxJava#1780]
https://github.com/Wechat-Group/WxJava/blob/35d7c3eee0738cb72914822d4bcae9bb3c1ec2dd/weixin-java-cp/src/main/java/me/chanjar/weixin/cp/util/json/WxCpUserGsonAdapter.java#L292

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/WxJava/issues/1738  早已修复
