### ISSUE TITLE
多小程序使用redis配置，accessToken问题

### ISSUE THREAD

**Issue by shijiuyan** [binarywang/WxJava#1787]
### 模块版本情况
* WxJava 模块名: weixin-java-miniapp
* WxJava 版本号:3.9.0

### 详细描述
多小程序使用redis配置，获取token时，源码中的redis key固定为accessToken，导致获取的token始终是一个小程序的

**Comment by binarywang** [comment]
不建议使用`WxMaRedisConfigImpl`，还有其他实现，你可以参考下

**Comment by shijiuyan** [comment]
看过了，因为我这边多个服务都会用到，所以需要放在redis里，其他的实现我也看过了满足不了我们的需求
