### ISSUE TITLE
统一下单有一个新的H5支付的类型未添加

### ISSUE THREAD

**Issue by mengyou658** [binarywang/WxJava#179]
详情 https://pay.weixin.qq.com/wiki/doc/api/wap.php?chapter=15_5
交易类型trade_type=MWEB
返回参数名："mweb_url"

**Comment by binarywang** [comment]
你提供的文档里好像没看到这个MWEB吧？能否提供准确的文档？

**Comment by wangjia2016** [comment]
@mengyou658 的确没找到这个mweb_url 这个交易类型

**Comment by rollbor** [comment]
官方文档 :https://pay.weixin.qq.com/wiki/doc/api/wap.php?chapter=15_4

**# 重新修改一下:** 根据官方介绍 ，H5支付已经不接受申请了，大家别走弯路了

**Comment by wangjia2016** [comment]
好神奇，才统一下单的参数列表里面没有这个，在接口说明里面才有。
MWEB
![image](https://cloud.githubusercontent.com/assets/16084076/25038072/466a52f0-212f-11e7-8172-1c274c94b9e0.png)

**Comment by binarywang** [comment]
据 @fangheng 所说，H5支付已不支持，因此此问题没必要讨论了

**Comment by binarywang** [comment]
![image](https://cloud.githubusercontent.com/assets/1343140/25742449/1be292ec-31c2-11e7-8b3a-5bc62f174590.png)
@fangheng 所提供图片，以供参考
