### ISSUE TITLE
org.xml.sax.SAXNotSupportedException: not supported setting property http://xml.org/sax/properties/lexical-handler

### ISSUE THREAD

**Issue by alwaysacc** [binarywang/WxJava#1790]
### 详细描述
引入 compile group: 'com.github.binarywang', name: 'weixin-java-mp', version: '3.9.0'
在tomcat9  里无法启动
### 日志
https://paste.ubuntu.com/p/MJXh2r4ZyK/

**Comment by alwaysacc** [comment]
3.7版本可以启动

**Comment by binarywang** [comment]
你的问题可以参考 https://blog.csdn.net/u010907329/article/details/50374058
