### ISSUE TITLE
WxCpRedissonConfigImpl不支持redisOps参数的public构造导致无法使用redistemplate模式

### ISSUE THREAD

**Issue by Dream2Land** [binarywang/WxJava#1792]
# 简要描述
WxCpRedissonConfigImpl不支持redisOps参数的public构造导致无法使用redistemplate模式

### 模块版本情况
* WxJava 模块名: wx-java-cp
* WxJava 版本号:3.9.3.B

### 详细描述
WxCpRedissonConfigImpl.java
中将
private WxCpRedissonConfigImpl(@NonNull WxRedisOps redisOps, String keyPrefix) {
    this.redisOps = redisOps;
    this.keyPrefix = keyPrefix;
  }
设为私有构造函数，导致无法使用redistemplate模式传入redisOps，wx-mp则是支持的

### 日志
无

**Comment by binarywang** [comment]
欢迎直接提交PR

**Comment by Dream2Land** [comment]
> 欢迎直接提交PR
关键不知道他设为私有的原因，我怕有影响

**Comment by braydenwong** [comment]
这个私有的构造方法目前看是给内部的另一个public构造方法调用的，按道理，应该要设为public。 @binarywang @Dream2Land

**Comment by binarywang** [comment]
没错，private改为public按说不会有什么影响，可见范围变大了而已
