### ISSUE TITLE
weixin-java-pay:3.8.0引入的jodd http是用jdk8版本的。在jdk7环境中无法启动。

### ISSUE THREAD

**Issue by dnovelty** [binarywang/WxJava#1794]
### 简要描述
weixin-java-pay:3.8.0版本描述说适用于jdk7环境下。但是由于其引用的jodd http 5.1.4版本是jdk8编译的。导致weixin-java-pay在jdk7环境下无法启动。

### 模块版本情况
* WxJava 模块名: weixin-java-pay
* WxJava 版本号:3.8.0

### 详细描述
weixin-java-pay:3.8.0版本描述说适用于jdk7环境下。但是由于其引用的jodd http 5.14版本是jdk8编译的。导致weixin-java-pay在jdk7环境下无法启动。

**Comment by binarywang** [comment]
你可以自行降低jodd-http版本

**Comment by dnovelty** [comment]
> 你可以自行降低jodd-http版本

已降。谢谢！
