### ISSUE TITLE
java.lang.IllegalArgumentException: class cn.binarywang.wx.miniapp.config.impl.WxMaRedisConfigImpl declares multiple JSON fields named accessTokenLock

### ISSUE THREAD

**Issue by wangjia2016** [binarywang/WxJava#1795]
# 简要描述
__WxMaRedisConfigImpl declares multiple JSON fields named accessTokenLock

### 模块版本情况
* WxJava 模块名: weixin-java-mp
* WxJava 版本号: 3.9.4.B

### 详细描述
Caused by: java.lang.IllegalArgumentException: class cn.binarywang.wx.miniapp.config.impl.WxMaRedisConfigImpl declares multiple JSON fields named accessTokenLock

我看源码里面都没这个accessTokenLock 还是报这个错 
![image](https://user-images.githubusercontent.com/16084076/95014857-4fd4f580-067c-11eb-8a26-e8fe1200196e.png)

### 日志
https://paste.ubuntu.com/p/Rp7XVFksGS/

**Comment by binarywang** [comment]
你没看到还有个父类吗？

**Comment by binarywang** [comment]
经过测试，demo没问题，你的问题是由于key为空导致的guava试图调用toString报错
