### ISSUE TITLE
调用 WxMaLiveGoodsService.updateGoods 和 addGoods 报错 提交商品微信返回 错误代码：300003

### ISSUE THREAD

**Issue by Yangcjcjlu** [binarywang/WxJava#1798]
# 简要描述
调用 WxMaLiveGoodsService.updateGoods 和 addGoods 报错
提交商品微信返回 错误代码：300003, 错误信息：price input invalid rid: 5f83f88f-59db4314-7ecd8048，微信原始报文：{"errmsg":"price input invalid rid: 5f83f88f-59db4314-7ecd8048","errcode":300003}

### 模块版本情况
* WxJava 模块名: miniapp.WxMaLiveInfo
* WxJava 版本号:3.9.0

### 详细描述
暂时怀疑是不是WxMaLiveInfo中price 和 price2用了string的类型造成的，但是其他有项目也有用，其中两个price都是调用BigDecimal 转string 的

参数如下 "priceType":2,"price":"0.00","price2":"68.80"

**Comment by Yangcjcjlu** [comment]
这个应该和微信的检查有关系，测试过了，如果price不是0，就不会有这个报错了

**Comment by binarywang** [comment]
欢迎直接提供PR代码，修复此问题

**Comment by binarywang** [comment]
@lipengjun92 如果有时间麻烦帮忙看下，我看之前的测试代码都是通过的，对吧
