### ISSUE TITLE
请问有没有支持公众号第三方平台的计划

### ISSUE THREAD

**Issue by dracupid** [binarywang/WxJava#18]
希望本项目能够添加公众号第三方平台的相关功能SDK。不知道开发组有没有这方面的打算。

**Comment by binarywang** [comment]
@dracupid  欢迎加入开发组，如果有意向的话

**Comment by greatpie** [comment]
希望能够封装一下微信开放平台SDK，感觉这方面的开源代码质量都不高

**Comment by binarywang** [comment]
光是300块钱的认证费就是个不小的门槛，只能是希望有开通相关账号的人帮忙做了

**Comment by leiorixsoft** [comment]
@binarywang 如果你真的要做第三方平台相关功能的SDK，300块钱的认证费我可以帮忙解决。有意向的话在开发群里@相思鸟谢工

**Comment by haoqicherish** [comment]
目前好像还没有第三方开放平台封装比较好的

**Comment by M-AKK** [comment]
没有移动应用登录的SDK吗，其实感觉第三方的平台的登录授权和公众号差不多，希望先做一下

**Comment by binarywang** [comment]
#368

**Comment by binarywang** [comment]
测试版本2.8.7.BETA已实现
