### ISSUE TITLE
【建议】封装一下从http请求获取支付通知内容，例如WxPayOrderNotifyResult.fromHttpRequest

### ISSUE THREAD

**Issue by blankzust** [binarywang/WxJava#180]
微信支付在发送统一订单请求且用户成功付款后会发送请求到notify_url定义的地方，但是weixin java tools就提供了将xml格式的字符串转换成WxPayOrderNotifyResult的方法：`WxPayOrderNotifyResult.fromXml`
而微信服务器发送的通知请求中的参数是放在inputStream里面的，所以开发者需要自行获取请求中附带的inputStream且将字节内容解析成字符串，然后再调用`WxPayOrderNotifyResult.fromXml`
这样有点麻烦，而且像我这样的菜鸟都不知道参数包含在流中的。
实例代码例如：
```
/**

     * 获取付款通知请求中的内容
     * @param request
     *          付款通知请求
     * @return
     */
    public static WxPayOrderNotifyResult getStrFromHttpServletRequest(HttpServletRequest request) throws IOException {
        InputStream in = null;
        List<Byte> bytes = Lists.newArrayList();
        StringBuffer xmlStr = new StringBuffer();
        try {
            in = new BufferedInputStream(request.getInputStream());
            byte[] b = new byte[1024];
            for(int n ; (n = in.read(b))!=-1 ; ){
                xmlStr.append(new String(b,0,n, "UTF-8"));
            }
        } catch (IOException e) {
            e.printStackTrace();
            throw e;
        } finally {
            if(in != null) {
                in.close();
            }
        }

        return WxPayOrderNotifyResult.fromXml(xmlStr.toString());
    }
```

**Comment by xusheng1987** [comment]
@RequestBody String result即可

如下：
WxPayOrderNotifyResult payResult = wxPayService.getOrderNotifyResult(result);

**Comment by aimilin6688** [comment]
将输入流转成字符串都有现成的方法，可以使用[Apache IO](http://commons.apache.org/proper/commons-io/javadocs/api-release/index.html) 包中的 IOUtils 工具类转换，一般项目都会引入[Apache IO](http://commons.apache.org/proper/commons-io/javadocs/api-release/index.html)工具包，里面有很多操作IO的方法，很是方便！

以下代码就是使用IO工具包实现的！
`String xmlResult = IOUtils.toString(request.getInputStream(), request.getCharacterEncoding());
WxPayOrderNotifyResult result = wxMpPayService.getOrderNotifyResult(xmlResult);`

**Comment by blankzust** [comment]
噢噢，原来如此，谢谢了
