### ISSUE TITLE
怎么自行设置维护accessToken   现在调用任何一个微信接口 都会自动去获取一个新的accessToken  这边不需要这个自动刷新accessToken的特性 

### ISSUE THREAD

**Issue by 617450941** [binarywang/WxJava#1800]
怎么自行设置维护accessToken   现在调用任何一个微信接口 都会自动去获取一个新的accessToken  这边不需要这个自动刷新accessToken的特性

**Comment by binarywang** [comment]
请自行实现`WxMpConfigStorage`接口，具体看已有实现的源码

**Comment by 617450941** [comment]
再哪里看已实现的代码

**Comment by binarywang** [comment]
> 再哪里看已实现的代码

我给出的接口，看它的实现类
