### ISSUE TITLE
请问，weixin-java-miniapp的3.9.0版本，去掉了cn.binarywang.wx.miniapp.bean.WxMaTemplateMessage这个类了吗？？？它的替代类是哪个？？

### ISSUE THREAD

**Issue by liangsongliu** [binarywang/WxJava#1801]
请问，weixin-java-miniapp的3.9.0版本，去掉了cn.binarywang.wx.miniapp.bean.WxMaTemplateMessage这个类了吗？？？它的替代类是哪个？？

**Comment by binarywang** [comment]
模版消息接口早都下线了已经，难道你还在使用？

**Comment by liangsongliu** [comment]
> 模版消息接口早都下线了已经，难道你还在使用？

有项目在用，结果更新新版本的时候报错了

**Comment by binarywang** [comment]
> > 模版消息接口早都下线了已经，难道你还在使用？
> 
> 有项目在用，结果更新新版本的时候报错了

去掉相关代码即可

**Comment by liangsongliu** [comment]
> > > 模版消息接口早都下线了已经，难道你还在使用？
> > 
> > 
> > 有项目在用，结果更新新版本的时候报错了
> 
> 去掉相关代码即可

如果去掉后，消息模板该怎么用啊？？

**Comment by binarywang** [comment]
> > > > 模版消息接口早都下线了已经，难道你还在使用？
> > > 
> > > 
> > > 有项目在用，结果更新新版本的时候报错了
> > 
> > 
> > 去掉相关代码即可
> 
> 如果去掉后，消息模板该怎么用啊？？

订阅消息，注意看下官方的公告

**Comment by liangsongliu** [comment]
> > > > > 模版消息接口早都下线了已经，难道你还在使用？
> > > > 
> > > > 
> > > > 有项目在用，结果更新新版本的时候报错了
> > > 
> > > 
> > > 去掉相关代码即可
> > 
> > 
> > 如果去掉后，消息模板该怎么用啊？？
> 
> 订阅消息，注意看下官方的公告

好的，谢谢！
