### ISSUE TITLE
使用wx-java-pay-spring-boot-starter做企业付款时，如何启用沙箱？

### ISSUE THREAD

**Issue by mostcool** [binarywang/WxJava#1802]
使用wx-java-pay-spring-boot-starter做企业付款时，如何启用沙箱？
WxPayProperties没看到相关的配置项。
WxPayAutoConfiguration里也不能设置useSandboxEnv。
请问如何配置？

**Comment by binarywang** [comment]
starter模块适用于快速接入常用功能。
你的需求比较特殊，建议参考demo项目，自定义相关配置。

**Comment by mostcool** [comment]
> starter模块适用于快速接入常用功能。
> 你的需求比较特殊，建议参考demo项目，自定义相关配置。

但是我看EntPayServiceImpl源码，里面并未实现沙箱功能吧？

**Comment by binarywang** [comment]
> 但是我看EntPayServiceImpl源码，里面并未实现沙箱功能吧？

沙箱操作统一在 `BaseWxPayServiceImpl` 入口实现，仔细看下源码就清楚了，也就是这个方法 `com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl#getPayBaseUrl`

**Comment by mostcool** [comment]
> > 但是我看EntPayServiceImpl源码，里面并未实现沙箱功能吧？
> 
> 沙箱操作统一在 `BaseWxPayServiceImpl` 入口实现，仔细看下源码就清楚了，也就是这个方法 `com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl#getPayBaseUrl`

看到了。刚没注意到。谢谢。
