### ISSUE TITLE
第三方平台代公众号实现复用微信公众号资料快速注册小程序接口

### ISSUE THREAD

**Issue by hywr** [binarywang/WxJava#1805]
### 简要描述
 如题，希望添加相关接口

### 官方文档地址
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/Official_Accounts/fast_registration_of_mini_program.html

*注意，如果要测试此接口，请先发布第三方平台，否则微信会先报-1错误，再报ticket无效错误。*

### 其他
本人暂时自己接入了此接口，如不嫌弃可使用合并附件中代码。
[weixin-java-open.zip](https://github.com/Wechat-Group/WxJava/files/5384570/weixin-java-open.zip)

**Comment by lmhfq** [comment]
直接提PR

**Comment by binarywang** [comment]
没错，直接提PR吧

**Comment by hywr** [comment]
> 直接提PR

> 没错，直接提PR吧

ok,已提

**Comment by hywr** [comment]
已提pr
