### ISSUE TITLE
请问企业微信支持教育版吗

### ISSUE THREAD

**Issue by cccy0** [binarywang/WxJava#1807]
教育版包含了一些家校沟通等功能, 而且通过Oauth2获取的用户信息里面的字段也不一致
![image](https://user-images.githubusercontent.com/29329157/96289409-97159b80-1017-11eb-964c-4ed42096426d.png)

**Comment by binarywang** [comment]
没听说过，不过应该很少人使用，建议自己实现，非常欢迎将实现后的代码提交PR上来
