### ISSUE TITLE
企业微信增加两个接口：“获取企业群发消息发送结果” 和 “离职成员的群再分配”

### ISSUE THREAD

**Issue by ll-2019** [binarywang/WxJava#1809]
调用这一套api 目前开发过程发现少了以下两个需要用到的接口.希望能添加以下两接口的功能哦.谢谢.

获取企业群发消息发送结果
请求地址:https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get_group_msg_result?access_token=ACCESS_TOKEN

离职成员的群再分配
请求地址：https://qyapi.weixin.qq.com/cgi-bin/externalcontact/groupchat/transfer?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
这两个接口看起来并不复杂，如果比较紧急，建议自行实现，然后提交PR。

**Comment by binarywang** [comment]
请楼主给出文档地址，而不是实际的接口地址，方便查阅实现

**Comment by jiuzhuaxiong** [comment]
给个任务，我能参与测试吗？

**Comment by binarywang** [comment]
> 给个任务，我能参与测试吗？

代码还没开发呢。开发测试随时欢迎参与的

**Comment by binarywang** [comment]
楼主仍未提供必要信息，暂时关闭
