### ISSUE TITLE
【建议】把WxMpInRedisConfigStorage里面3个lock修改成基于redis的分布式锁

### ISSUE THREAD

**Issue by yiyi910** [binarywang/WxJava#181]
public WxMpInRedisConfigStorage()  {
		 this.accessTokenLock = new ReentrantLock();
		 this.jsapiTicketLock = new ReentrantLock();
		 this.cardApiTicketLock = new ReentrantLock();
		}

**Comment by lly835** [comment]
看最新的代码，已去掉锁机制，用Jedis直接操作

**Comment by xusheng1987** [comment]
没有去掉锁机制啊

**Comment by ylmotol7** [comment]
基于redis的锁？不合理吧？能扩展就扩展

**Comment by binarywang** [comment]
暂不考虑，redis的配置本来只是仅供参考，如有需要自行实现即可
