### ISSUE TITLE
用户通过公众号发送关键字，系统根据关键字回复信息，点击信息，可以打开小程序如何实现？

### ISSUE THREAD

**Issue by lssprogress** [binarywang/WxJava#1810]
客户使用公众号发送关键字，系统根据关键字回复信息，点击信息，可以打开小程序，这个需求能实现吗？ 返回的WxMpXmlOutMessage 是什么类型，怎么组装呢？

**Comment by binarywang** [comment]
请先参考官方文档：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html
这里写的才可以实现。

建议使用客服消息接口（即返回之前调用接口发送），是支持小程序卡片的，具体看：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html#7

**Comment by lssprogress** [comment]
> 请先参考官方文档：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Passive_user_reply_message.html
> 这里写的才可以实现。
> 
> 建议使用客服消息接口（即返回之前调用接口发送），是支持小程序卡片的，具体看：https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html#7

好的，我试一下，谢谢
