### ISSUE TITLE
native交易类型，扫描生成的短链接微信回调签名验证失败

### ISSUE THREAD

**Issue by ldp0218** [binarywang/WxJava#1814]
没有返回sign_type，默认为MD5，需要指定签名类型
![image](https://user-images.githubusercontent.com/15208335/96672292-77bf9b00-1396-11eb-9df5-50493cdb7251.png)

**Comment by ldp0218** [comment]
是否也需要重载一个方法

**Comment by binarywang** [comment]
> 是否也需要重载一个方法

可以的，欢迎直接提交PR代码

**Comment by binarywang** [comment]
同样的还有 `parseRefundNotifyResult` 方法

**Comment by ldp0218** [comment]
抱歉未关注消息，感谢已提交！
