### ISSUE TITLE
WxMpInRedisConfigStorage里几个token存入了redis但是get的时候没从redis取

### ISSUE THREAD

**Issue by yiyi910** [binarywang/WxJava#182]

**Comment by xusheng1987** [comment]
已提交pr
https://github.com/Wechat-Group/weixin-java-tools/pull/183/commits/68fbb2ee3e63209195df471470de6ac7774fce78

**Comment by binarywang** [comment]
#183

**Comment by lly835** [comment]
我试了下，之前的代码是可以存入到redis的，@yiyi910，有两个access_token,缓存的是这个https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140183&token=&lang=zh_CN
