### ISSUE TITLE
IdleConnectionMonitorThread似乎没地方会调用shutdown()方法，导致Thread一直开着

### ISSUE THREAD

**Issue by crazycode** [binarywang/WxJava#187]
以下代码按样例编写，因为使用的是
```
WxMpServiceImpl wxMpService = new WxMpServiceImpl();
wxMpService.setWxMpConfigStorage(getWxMpConfigStorage());
```
代码中会调用WxMpServiceImpl.initHttpClient()方法，导致产生大量的IdleConnectionMonitorThread线程start，但代码中是一个while (!this.shutdown)循环，但没有地方调用shutdown()方法设置this.shutdown为true，所以这些线程都不能关闭，最后导致出现OutOfMemoryError。

IdleConnectionMonitorThread代码如下：
```
  public static class IdleConnectionMonitorThread extends Thread {
    private final HttpClientConnectionManager connMgr;
    private final int idleConnTimeout;
    private final int checkWaitTime;
    private volatile boolean shutdown;

    public IdleConnectionMonitorThread(HttpClientConnectionManager connMgr, int idleConnTimeout, int checkWaitTime) {
      super("IdleConnectionMonitorThread");
      this.connMgr = connMgr;
      this.idleConnTimeout = idleConnTimeout;
      this.checkWaitTime = checkWaitTime;
    }

    @Override
    public void run() {
      try {
        while (!this.shutdown) {
          synchronized (this) {
            wait(this.checkWaitTime);
            this.connMgr.closeExpiredConnections();
            this.connMgr.closeIdleConnections(this.idleConnTimeout,
              TimeUnit.MILLISECONDS);
          }
        }
      } catch (InterruptedException ignore) {
      }
    }

    public void trigger() {
      synchronized (this) {
        notifyAll();
      }
    }

    public void shutdown() {
      this.shutdown = true;
      synchronized (this) {
        notifyAll();
      }
    }
  }
```

异常信息如下：
```
OutOfMemoryError occurred : unable to create new native thread

play.exceptions.JavaExecutionException: unable to create new native thread
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:485)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:467)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:436)
        at play.mvc.ActionInvoker.handleBefores(ActionInvoker.java:299)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:144)
        at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:714)
        at me.chanjar.weixin.common.util.http.DefaultApacheHttpClientBuilder.prepare(DefaultApacheHttpClientBuilder.java:212)
        at me.chanjar.weixin.common.util.http.DefaultApacheHttpClientBuilder.build(DefaultApacheHttpClientBuilder.java:246)
        at me.chanjar.weixin.mp.api.impl.WxMpServiceImpl.initHttpClient(WxMpServiceImpl.java:438)
        at me.chanjar.weixin.mp.api.impl.WxMpServiceImpl.setWxMpConfigStorage(WxMpServiceImpl.java:449)
        ... 5 more
```

**Comment by crazycode** [comment]
@binarywang 是否是我使用方式上有问题？感觉DefaultApacheHttpClientBuilder没有成为单例。

**Comment by binarywang** [comment]
你应该保证WxMpServiceImpl为单例，一般都是这么使用的，使用spring进行注入使用。

**Comment by binarywang** [comment]
另外你那里出现OutOfMemoryError ，是否是JVM设置内存过小导致？

**Comment by binarywang** [comment]
还有你检查下你使用的版本，是否为最新的？

**Comment by crazycode** [comment]
我使用的是2.6.0，jvm堆min和max都是1500M，JDK8最新版本。

我们系统微信配置是用户自己添加的，所以我们的情况是有很多个config store和service，做单例有点麻烦。

我就想知道，这个shutdown()方法，什么时候调用？目前使用jstack打印出来的就是有上千个这样的Thread：
```
Thread 5861: (state = BLOCKED)
 - java.lang.Object.wait(long) @bci=0 (Compiled frame; information may be imprecise)
 - me.chanjar.weixin.common.util.http.DefaultApacheHttpClientBuilder$IdleConnectionMonitorThread.run() @bci=17, line=269 (Compiled frame)
```

**Comment by crazycode** [comment]
最近刚迁移到v2.x，之前用weixin-java-tools 1.x没有这个问题。

**Comment by crazycode** [comment]
如果建议 WxMpServiceImpl 作为单例使用，最好在文档中说明一下，因为 1.x 没这个要求，而且wiki中的例子也不是写成单例的。

**Comment by binarywang** [comment]
感觉也有可能是因为idleConnTimeout的值的原因，有可能你的请求过多，导致在短时间很多线程没能及时关闭，你是否可以自己去修改对应值尝试看看？如果可以，下一步将此属性变成可配置的。

**Comment by binarywang** [comment]
@kakotor 你有时间也帮忙看下吧

**Comment by crazycode** [comment]
@binarywang 看过代码，这个线程启动后，如果没把shutdown设置为true，那这个线程会永远在运行的。
所以就想知道，这个shutdown()方法，什么时候调用？如果用单例的话，那就不要加shutdown()方法了。

**Comment by binarywang** [comment]
确实我也没看到什么地方主动调用shutdown()，等@kakotor 来解释下，这部分代码主要他写的，比较熟些。

**Comment by crazycode** [comment]
阅读了me.chanjar.weixin.cp.api.WxCpServiceImpl#setWxCpConfigStorage后，想到一个临时解决的方案，我们代码中ConfigStorage是单例，所以在初始化 ConfigStorage 时，加入以下代码：
`wxCpConfigStorage.setApacheHttpClientBuilder( DefaultApacheHttpClientBuilder.get());`

明天再观察一下是否还会出现大量线程，也请确认一下这个问题，谢谢。

**Comment by crazycode** [comment]
其实只要做一下 DefaultApacheHttpClientBuilder 的单例化就可以了，测试了一下没出问题，也请 @kakotor @binarywang 确认一下这样解决是否可行？

**Comment by bysunexus** [comment]
考虑到可配置和后向兼容的问题DefaultApacheHttpClientBuilder并没有做单例处理，还是建议WxMpServiceImpl保存单例使用。
如果DefaultApacheHttpClientBuilder这个类不满足建议自己实现一下ApacheHttpClientBuilder接口扩展

**Comment by bysunexus** [comment]
@crazycode 
建议参考一下https://github.com/wechat-group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95
`Wx**InMemoryConfigStorage config = new Wx**InMemoryConfigStorage();
config.setHttpProxyHost(..);//设置代理地址,没有可以无需设置
config.setHttpProxyPort(..);//设置代理端口,没有可以无需设置
config.setHttpProxyUsername(..);//设置代理用户名,没有可以无需设置
config.setHttpProxyPassword(..);//设置代理密码,没有可以无需设置

DefaultApacheHttpClientBuilder clientBuilder = DefaultApacheHttpClientBuilder.get();
clientBuilder.setConnectionRequestTimeout(..)//从连接池获取链接的超时时间(单位ms)
clientBuilder.setConnectionTimeout(..)//建立链接的超时时间(单位ms)
clientBuilder.setSoTimeout(..)//连接池socket超时时间(单位ms)
clientBuilder.setIdleConnTimeout(..)//空闲链接的超时时间(单位ms)
clientBuilder.setCheckWaitTime(..)//空闲链接的检测周期(单位ms)
clientBuilder.setMaxConnPerHost(..)//每路最大连接数
clientBuilder.setMaxTotalConn(..)//连接池最大连接数
clientBuilder.setUserAgent(..)//HttpClient请求时使用的User Agent
config.setApacheHttpClientBuilder(clientBuilder); //设置自定义的ApacheHttpClientBuilder`

在不同的config中配置相同的clientBuilder而不是使用WxMpServiceImpl 的默认创建 这样应该可以解决你的问题

**Comment by crazycode** [comment]
谢谢，我这边这样解决的，不过建议在文档中说明一下这个问题，如果Service不是单例的话会有问题。

**Comment by githubbinlinghai** [comment]
我弱弱的问一下，我是多个公众号保存在数据库中怎么单列化，哪个IdleConnectionMonitorThread很多啊

**Comment by blade254353074** [comment]
...没用单例，线程都把我的服务器的最大线程顶满了

**Comment by binarywang** [comment]
@blade254353074 你每次请求接口都是新new了一个service么？

**Comment by binarywang** [comment]
@githubbinlinghai 这种情况下，至少也得保证每个公众号对应的service是单例的

**Comment by binarywang** [comment]
楼上各位出现问题的，请参考@kakotor的解决办法。

**Comment by blade254353074** [comment]
@binarywang 对。。。不过发现问题以后就改好了
