### ISSUE TITLE
WxMessageDuplicateChecker 这个当微信那边触发很多的时候，这个线程就很多

### ISSUE THREAD

**Issue by githubbinlinghai** [binarywang/WxJava#191]
这个线程有时候会很多，导致tomcat后期不能创建新线程，怎么破，有没有方法取消

**Comment by MichealJou** [comment]
我也遇见到这个问题

**Comment by binarywang** [comment]
这个问题需要研究一下，虽然我还没遇到过

**Comment by bobbyguo** [comment]
@githubbinlinghai  @MichealJou  代码中是不是创建了多个router？

**Comment by binarywang** [comment]
有可能是多个service实例导致的，建议使用单例方式创建使用对应的service

**Comment by jink2005** [comment]
我同样遇到这一问题，只要接入消息相应，一天左右内存就被用光，提示native线程无法创建。只要把消息移到另一个服务器，另一个服务器就出问题，这边服务器就能稳定运行。目前用的是3.3.0版本

**Comment by jink2005** [comment]
> 有可能是多个service实例导致的，建议使用单例方式创建使用对应的service

我已经把每个公众号对应的router都放在router中，采用单例方式创建了，service也是一样，还是不行。
消息处理的代码：

>public WxMpXmlOutMessage route(WxMpXmlMessage message, WechatAccount wechatAccount) {
        try {
            WxMpMessageRouter wxMpMessageRouter = getWxMpMessageRouter(wechatAccount);
            if (null != wxMpMessageRouter) {
                return wxMpMessageRouter.route(message);
            }
        } catch (Exception e) {
            this.logger.error(e.getMessage(), e);
        }
        return null;
    }

获取router的代码：


>private WxMpMessageRouter getWxMpMessageRouter(WechatAccount wechatAccount) {
        WxMpMessageRouter wxMpMessageRouter = null;
        if (null != wechatAccount) {
            wxMpMessageRouter = wxWxMpMessageRouterMap.get(wechatAccount.getId().toString());
            if (null == wxMpMessageRouter) {
                // 未创建过，则开始申请锁，并创建
                synchronized (createWxMpMessageRouterLock) {
                    // 获得锁后，先检查是不是被其他获得过锁的线程创建过
                    wxMpMessageRouter = wxWxMpMessageRouterMap.get(wechatAccount.getId().toString());
                    if (null == wxMpMessageRouter) { // 仍然不存在则创建
                        WxMpService wxMpService = WechatUtil.getWxMpService(wechatAccount);
                        if (null != wxMpService) {
                            wxMpMessageRouter = new WxMpMessageRouter(wxMpService);
                            // 记录所有事件的日志
                            wxMpMessageRouter.rule().handler(new LogHandler().setWechatAccountId(wechatAccount.getId())).next();
                            // 接收客服会话管理事件``

**Comment by jink2005** [comment]
> > 有可能是多个service实例导致的，建议使用单例方式创建使用对应的service
> 
> 我已经把每个公众号对应的router都放在router中，采用单例方式创建了，service也是一样，还是不行。
> 消息处理的代码：


用上面这方法，运行几天了，内存利用挺高，但是没有崩溃了。
