### ISSUE TITLE
可以改用Okhttp么?

### ISSUE THREAD

**Issue by dylanleung** [binarywang/WxJava#192]
减少包依赖.同时提高性能.

**Comment by binarywang** [comment]
这个玩意好像是常用于android开发吧，对于服务器端开发，可能还是不太合适吧

**Comment by dylanleung** [comment]
服务端开发也使用.基本上就是替代httpclient 的产物.同时还附带优秀的数据流处理okio

**Comment by binarywang** [comment]
ok，可以考虑下

**Comment by crskyp** [comment]
我来考虑，集成okhttp框架

**Comment by crskyp** [comment]
关注下#199 ，如果okhttp的用法有问题，请反馈

**Comment by dracupid** [comment]
@crskyp Executor 的 executeOkhttp 方法中，获取Response的body不应该用`response.body().toString()`，这返回的是类似于`okhttp3.internal.http.RealResponseBody@5d394252`，应该使用response.body().string()

**Comment by crskyp** [comment]
收到，我处理

**Comment by strongme** [comment]
难道不考虑下unirest么，也是挺厉害的一个

**Comment by crskyp** [comment]
@strongme  unirest你们在使用吗，使用的用户多不多

**Comment by crskyp** [comment]
#207 @dracupid  okhttp错误用法已修改：body().toString()修改为body().string()

**Comment by strongme** [comment]
@crskyp 目前是所有http类请求全部都在使用unirest，链式请求，一气呵成 
```java
Unirest.post("http://httpbin.org/post")
  .queryString("name", "Mark")
  .field("last", "Polo")
  .asJson()
```

**Comment by crskyp** [comment]
可以考虑

**Comment by opendever** [comment]
[unirest-java](https://github.com/Mashape/unirest-java)不就是httpclient的封装么，httpclient有的问题一样存在。
还是支持用Okhttp。

**Comment by crskyp** [comment]
考虑到unirest-java封装的httpclient，暂不考虑支持unirest-java

**Comment by crskyp** [comment]
集成jodd-http、okhttp基本完成

**Comment by izee** [comment]
httpclient有什么问题啊，学习学习
