### ISSUE TITLE
是否在考虑提供小程序的接口支持

### ISSUE THREAD

**Issue by mgcnrx11** [binarywang/WxJava#193]
小程序有一些新的接口入code 换取 session_key。用于登陆换取加解密的key。

还有有了一套新的加密数据解密算法https://mp.weixin.qq.com/debug/wxadoc/dev/api/signature.html

这些新功能的开发计划是？

若要实现会否新增一个子项目的形式如weixin-java-miniapp

**Comment by binarywang** [comment]
目前还没有计划，不过如有可能，欢迎大家提供相应代码

**Comment by mgcnrx11** [comment]
我新建一个weixin-java-mina试试，但只能是基于目前碰到的需求写API，碰不到的有空再说

**Comment by binarywang** [comment]
期待你的代码，非常感谢！

**Comment by binarywang** [comment]
已提交小程序相关实现代码
