### ISSUE TITLE
企业号中的 WxCpMessage转json时丢失safe属性

### ISSUE THREAD

**Issue by QweikChris** [binarywang/WxJava#196]
应该是WxCpMessageGsonAdapter中忽略了safe 属性
缺少以下代码
if (StringUtils.isNotBlank(message.getSafe())) {
      messageJson.addProperty("safe", message.getSafe());
 }

**Comment by binarywang** [comment]
http://git.oschina.net/binary/weixin-java-tools/issues/1
你的问题应该是跟这个一样的吧

**Comment by binarywang** [comment]
已修复
