### ISSUE TITLE
日志URL取值问题

### ISSUE THREAD

**Issue by yiyi910** [binarywang/WxJava#200]
WxMpServiceImpl.java第403行和第408行打日志URL参数可否把取ur的值l换成取uriWithAccessToken；实际执行的请求地址为uriWithAccessToken，输出url的值容易让人误解没有传access_token参数

**Comment by binarywang** [comment]
虽然问题不是很大，不过还是改下，也无妨

**Comment by yiyi910** [comment]
谢谢，一个建议！希望工具更加完美！！！



yiyi910
 
发件人： Binary Wang
发送时间： 2017-04-28 10:30
收件人： Wechat-Group/weixin-java-tools
抄送： yiyi910; Author
主题： Re: [Wechat-Group/weixin-java-tools] 日志URL取值问题 (#200)
虽然问题不是很大，不过还是改下，也无妨

**Comment by binarywang** [comment]
感谢你提出的建议，希望以后多多提出类似的优化改进意见
