### ISSUE TITLE
增加企业微信第三方应用接口的支持

### ISSUE THREAD

**Issue by mog0202** [binarywang/WxJava#203]

**Comment by binarywang** [comment]
可否提供相关文档地址？

**Comment by mog0202** [comment]
saas套件官网地址：
https://qy.weixin.qq.com/app

saas套件接口文档地址：
http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%94%E7%94%A8%E6%8E%88%E6%9D%83

http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AE%A1%E7%90%86%E5%90%8E%E5%8F%B0%E5%8D%95%E7%82%B9%E7%99%BB%E5%BD%95

**Comment by binarywang** [comment]
https://qyapi.weixin.qq.com/cgi-bin/service/get_provider_token

也就是说只有这一个接口吗？

**Comment by mog0202** [comment]
不是。。。有很多接口。

http://qydev.weixin.qq.com/wiki/index.php?title=第三方应用接口说明

http://qydev.weixin.qq.com/wiki/index.php?title=第三方回调协议

**Comment by binarywang** [comment]
那还挺多的呢，有空弄一下吧，这个有点体力活的嫌疑

**Comment by mog0202** [comment]
还有下面两个

http://qydev.weixin.qq.com/wiki/index.php?title=成员登录授权
http://qydev.weixin.qq.com/wiki/index.php?title=单点登录授权

**Comment by mog0202** [comment]
难点是现在的的corp_id都是配置文件中配置的，而这个是每次调用的时候，需要从app测传递过来，也就是第三方服务商接口的access_token的取得方式和企业号api的不一样，如果不改的话，现在的api都没有办法利用。

**Comment by binarywang** [comment]
那你考虑下看如何使实现好些，你也可以直接提交代码吧

**Comment by mog0202** [comment]
恩，我回头有时间了，把我实现的代码pull request一分，你看看

**Comment by binarywang** [comment]
ok，非常感谢~

**Comment by binarywang** [comment]
@mog0202 有啥进展没？

**Comment by binarywang** [comment]
附上企业微信里的文档地址： https://work.weixin.qq.com/api/doc#10975

**Comment by mog0202** [comment]
非常抱歉，最近工作比较忙，身体也不太好，所以一直没有时间写！

**Comment by binarywang** [comment]
@mog0202 没事，工作和身体为重，多多保重身体~

**Comment by binarywang** [comment]
新开了 #493 此issue暂时关闭
