### ISSUE TITLE
建议取消weixin-java-pay对logback的依赖

### ISSUE THREAD

**Issue by izee** [binarywang/WxJava#204]
我的项目用的log4j，但是引用weixin-java-pay包后，新增了两个包（logback-core，logback-classic），把我日志环境搞得一团糟。

**Comment by binarywang** [comment]
这确实是个问题，不应该包含logback的相关类，后期会处理掉的，多谢提醒。

**Comment by binarywang** [comment]
不过在新版本发布之前，你可以先可以在pom里exclude掉logback的依赖就行，如果没用到qrcode相关接口功能的话，应该完全不受影响。

**Comment by izee** [comment]
@binarywang 好的，谢谢。
