### ISSUE TITLE
实现获取仿真测试系统的验签密钥的API

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#206]
参考文档 ： https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1

**Comment by izee** [comment]
测试了一下，使用getsignkey获取的沙箱密钥，还是会报错，腾讯的接口真他妈坑爹

**Comment by binarywang** [comment]
果真如此？那太坑爹了，怪不得大家都是用真实的一分一分钱的测试

**Comment by binarywang** [comment]
不管怎样，先把这接口实现了
