### ISSUE TITLE
调用【上传临时素材文件】接口返回 44001 多媒体文件为空

### ISSUE THREAD

**Issue by lhshin** [binarywang/WxJava#209]
经我验证在代码：
me.chanjar.weixin.common.util.http.MediaUploadRequestExecutor.java中
_HttpEntity entity = MultipartEntityBuilder
              .create()
              .addBinaryBody("media", file)
              .setMode(HttpMultipartMode.RFC6532)
              .build();
      httpPost.setEntity(entity);
      httpPost.setHeader("Content-Type", _ContentType.MULTIPART_FORM_DATA.toString());__
**最后设置的contentType导致，去掉此设置即可。**
[参考：](http://stackoverflow.com/questions/29355989/apache-httpclient-post-upload-file-wont-work-with-multipartentitybuilder-upload)
_Try removing this line

httppost.setHeader("Content-Type", "multipart/form-data");
Updated

as expected the application is sending invalid Content-Type header

[org.apache.http.headers] http-outgoing-5 >> Content-Type: multipart/form-data
Please do not set Content-Type manually and let HttpClient generate it for you based on properties of the HttpEntity enclosed in the request_

**Comment by binarywang** [comment]
这个已经修复，请使用最新测试版即可。reopen it 以便更多人看到
