### ISSUE TITLE
微信推送用户核销卡券事件：WxMpXmlMessage中似乎缺失消息数据

### ISSUE THREAD

**Issue by huaxia0624** [binarywang/WxJava#213]
Bean】：me.chanjar.weixin.mp.bean.message.WxMpXmlMessage
【事件】：user_consume_card（官网文档中，微信卡券>>卡券事件推送>>2.5 核销事件推送）
【问题】：没有以下Key的Get方法
1、ConsumeSource：核销来源。支持开发者统计API核销（FROM_API）、公众平台核销（FROM_MP）、卡券商户助手核销（FROM_MOBILE_HELPER）（核销员微信号）
2、LocationName：门店名称，当前卡券核销的门店名称（只有通过自助核销和买单核销时才会出现该字段）
3、StaffOpenId：核销该卡券核销员的openid（只有通过卡券商户助手核销时才会出现）
4、VerifyCode：自助核销时，用户输入的验证码
5、RemarkAmount：自助核销时，用户输入的备注金额
6、OuterStr：开发者发起核销时传入的自定义参数，用于进行核销渠道统计

**Comment by binarywang** [comment]
除了OuterStr已有同名属性存在，其他即将添加
