### ISSUE TITLE
无法对useSandboxForWxPay进行配置

### ISSUE THREAD

**Issue by izee** [binarywang/WxJava#224]
WxPayConfig没有实现Sandbox选项的set方法

**Comment by binarywang** [comment]
可以考虑加上，不过你也可以参考demo里面的实现，是使用了继承的方式覆盖对应方法来完成的。

**Comment by binarywang** [comment]
不是demo，我说错了，是单元测试里的代码，com.github.binarywang.wxpay.testbase.XmlWxPayConfig
