### ISSUE TITLE
WxMpServiceImpl.getAccessToken极端情况下WxMpInRedisConfigStorage的bug

### ISSUE THREAD

**Issue by ivancxj** [binarywang/WxJava#229]
[https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/impl/WxMpServiceImpl.java#L80](url)
获取accessToken逻辑是先判断是否过期,未过期再去获取token
当WxMpConfigStorage用WxMpInRedisConfigStorage时,
极端情况下,存在的可能bug是:
**在判断是否过期的时候是未过期,但是获取token的时候瞬间刚好过期了**
```java
// 比如此时未过期
if (this.getWxMpConfigStorage().isAccessTokenExpired()) {
   ...
}
...
// 返回的时候刚好过期了,返回是null
return this.getWxMpConfigStorage().getAccessToken();
```
此逻辑用WxMpInMemoryConfigStorage是没问题的
但是用WxMpInRedisConfigStorage会出现问题
同理getJsapiTicket也同样会出现这个情况!

**Comment by binarywang** [comment]
这个几率确实有，不过在execute方法中有重试机制，三次重试的，这样可以保证最终能够获取到有效的token吧

**Comment by ivancxj** [comment]
通过accessToken获取jsapiTicket时,accessToken如果错误是有三次重试
但是如果accessToken正确,jsapiTicket已经在缓存里, 调用createJsapiSignature计算signature是直接本地sha1没有什么重试机制的!

解决方案非常简单,大家也容易能想到,我只是做个简单说明
是不是可以把 isJsapiTicketExpired() 返回一个对象Token,包含两个属性,一个是是否过期expired,一个是未过期的token值value
把下面(伪代码)
```java
boolean isJsapiTicketExpired();
```
```java
if (this.getWxMpConfigStorage().isJsapiTicketExpired()) {
  ...
}
...
return this.getWxMpConfigStorage().getJsapiTicket();
```
修改成
```java
Token isJsapiTicketExpired();
```

```java
Token token = this.getWxMpConfigStorage().isJsapiTicketExpired();
if (token.isExpired()) {
  ...
  token.setValue(xxxxx);
}

return token.getValue();
```
当然方法名可以调整下

**Comment by binarywang** [comment]
感谢提出建议，抽空考虑下

**Comment by izee** [comment]
Expired判断可以略小于实际过期时限，以实现在真正过期前提前刷新，以时间差来增加accessToken的可用性，代码逻辑上就不需要什么改动

**Comment by ivancxj** [comment]
@izee 是的,这样也可以

**Comment by ivancxj** [comment]
```java
   /**
     * 防止判断时未过期,但是获取时又过期
     * 所以如果缓存时间小于2s,也认为是过期
     */
    @Override
    public boolean isAccessTokenExpired() {
        return jedis.ttl(ACCESS_TOKEN_KEY.concat(appId)) < 2;
    }
```

**Comment by izee** [comment]
比较严谨的做法是，把过期检测和自动刷新，封装到getAccessToken()内部，以保证getAccessToken()方法始终返回一个可用的accessToken

**Comment by binarywang** [comment]
@ivancxj WxMpInRedisConfigStorage类已按你的方法做了调整，非常感谢~
