### ISSUE TITLE
验签bug

### ISSUE THREAD

**Issue by VesperHan** [binarywang/WxJava#230]
demo验签错误
没有按字典排序就进行sha1

**Comment by binarywang** [comment]
能否明示下？是哪个demo？单元测试里的demo，还是某个demo项目？

**Comment by VesperHan** [comment]
weixin-java-mp-demo 2.6.0最新的应该
还有一个问题,用户第一次关注之后,怎么样能一次推送三条信息?

**Comment by binarywang** [comment]
以后如果是关于Demo的疑问或问题，最好在对应项目下提出issue吧

**Comment by binarywang** [comment]
一次关注属于一个事件，只能使用被动方式回复一条消息，其他的消息可以使用客服接口发送，属于主动消息

**Comment by binarywang** [comment]
demo问题请到对应项目下讨论，先关闭此issue

**Comment by binarywang** [comment]
已看过源代码，排序肯定是有的，这逻辑都已经用了好几年呢，是没有问题的，大家都在用。
