### ISSUE TITLE
支付api，好像没有免密支付

### ISSUE THREAD

**Issue by oyhk** [binarywang/WxJava#231]
支付api，好像没有免密支付。如果有的话告诉我下，谢谢啦。

**Comment by binarywang** [comment]
免密支付是什么鬼？官方有提供该接口吗？

**Comment by binarywang** [comment]
感觉像是客户端的设置，跟服务器端接口无关

**Comment by oyhk** [comment]
就是微信支付的 “委托代扣”

**Comment by binarywang** [comment]
有相关文档么，https://pay.weixin.qq.com/wiki/doc/api/tools/pap.php?chapter=18_1 是这里吗？我看文档都已经不存在，估计废弃了吧
