### ISSUE TITLE
获取企业成员基本信息的接口没有

### ISSUE THREAD

**Issue by jibaojie** [binarywang/WxJava#233]
WxCpService接口中oauth2getUserInfo获取到的只有UserId和DeviceId，没有吧成员票据user_ticket返回，无法根据user_ticket获取成员详情，不能拿到用户的头像，等其他信息

**Comment by jibaojie** [comment]
找到

**Comment by x1aoj1ang** [comment]
@jibaojie hi，您好，遇到同样的问题，但是没找到这个接口。。。而且在源代码里面搜了下“user_ticket”这个关键字也是没找到（只找到这个issue），请问具体在哪里找到的呢，多谢~

**Comment by x1aoj1ang** [comment]
@jibaojie 没事啦，拿到userid后用的getUserService接口也能达到效果,多谢~

**Comment by softboy99** [comment]
现在是不是不能获取成员基本信息了，官方是否封掉了？
