### ISSUE TITLE
access_token不刷新问题

### ISSUE THREAD

**Issue by VesperHan** [binarywang/WxJava#235]
工程A
 自定义接口 /getToken
public @ResponseBody String getToken(){
     return wxService.getAccessToken();
}
工程B
调用该接口的时候,返回access_token, 但是超时过期之后返回的token没有刷新,麻烦楼主分析下
意思是过两个小时了,但是token没刷新

**Comment by binarywang** [comment]
这种情况，你需要考虑token共享的问题，不能使用默认的实现了，建议存入redis等缓存中

**Comment by VesperHan** [comment]
wxmp启动 然后我的另外一个工程启动,直接调用getAccessToken拿到的就是过期的,怎么这么快,刚启动新拿到的token瞬间过期了,,楼主的api是我的token主控器,也没有强制刷新,感觉这个token这么难控制

**Comment by binarywang** [comment]
同一个问题提问的地方太多了，暂时关闭
