### ISSUE TITLE
getAccessToken四种方法区分和使用问题

### ISSUE THREAD

**Issue by VesperHan** [binarywang/WxJava#237]
我在weixin-mp-sdk所在工程开发一个方便其他工程请求token的接口
private WeixinService wxService;
@RequestMapping  /getToken
public @responsebody String getToken(){
      return **wxService.getAccessToken()**;
}

其他工程通过这个接口可以得到token,但是在使用时就告诉我token无效了,我也很无奈这是为什么
错误代码：40001，说明：invalid credential, access_token is invalid or not latest hint

**问题1:**我对外开发发送token的接口方法是不是调错了?
sdk所在工程没有问题,他token发送给其他工程拿到就是过期的.是我调用的这个接口不对么?
        new WxMpService().getAccessToken();
        new WxMpConfigStorage().getAccessToken();
        new WxMpInRedisConfigStorage().getAccessToken();
        new WxMpInMemoryConfigStorage().getAccessToken();
上面这四个,我应该使用哪个方法可以把mp-sdk保存的token发送给其他工程提供使用?不会导致拿到token就是过期的?

具体操作步骤:
1. mp-sdk工程启动
2.其他工程调用sdk工程的 getToken接口实际返回wxService.getAccessToken();
3.其他工程拿到token 发送模板消息使用提示无效
----
验证:
此时如果真的是无效了,那我在mp-sdk工程进行一次用户信息查询,sdk内部发现过期是不是应该更新token,如果token真的过期的,应该会自动刷新并存储新access_token是吧?

此时: 信息查询成功,说明此时sdk工程调动微信接口用到的token不是过期的
即使有变化, wxService.getAccessToken();
应该存放新的token是吧(看代码是这样)

现在:其他工程 再次调用 mp-sdk工程的token请求接口, **得到的token和之前的一样,token没有变化**

排查问题:
排查不出来,看不到mp-sdk给微信发送的接口请求使用的具体token是什么
wxService.getAccessToken();依旧是原来旧的token

存redius?如果我调用wxService.getAccessToken();拿到token存redius,可是我现在的环境即使拿到token了,也是过期的,没意义啊,sdk已经有了完成的刷新验证机制,可是我想用给的token就是提示无效

楼主:mp-sdk真心好用,但是一个token问题我已经感觉我解决不了了,token就是无效,没有其他地方会影响token了,麻烦楼主看我打了这么详细,帮忙分析一下,有没有解决方法,或者我哪里姿势不对?

**Comment by VesperHan** [comment]
补充:
WxMpService get AccessToken
WeixinSercice getAccessToken
获取token方式是否一样,
如果先调用WxMpService get AccessToken  后调用WxMpService get AccessToken token是否一样
相反调用也是一样?

**Comment by binarywang** [comment]
涉及到多个工程共享token的问题，请借助于第三方存储，比如redis，可以参考WxMpInRedisConfigStorage

**Comment by izee** [comment]
WxMpService.getAccessToken()得到的token，在极端情况下可能会返回刚刚过期的token，概率极低，在调试阶段概率更低
建议选把token拿到微信在线调试页测试一下，以最权威的方式验证token的有效性，这样可以初步判断是token的问题，还是调用端代码逻辑错误

**Comment by nickwongwong** [comment]
mp-sdk有自动刷新access_token的行为，这会可能会导致中控token的接口返回的token不是最新的
