### ISSUE TITLE
消息排重失败

### ISSUE THREAD

**Issue by 18940818955** [binarywang/WxJava#239]
WxMessageInMemoryDuplicateChecker里面的msgId2Timestamp第一次放进去key/value之后，第二次进去没有值。

**Comment by binarywang** [comment]
请问你是如何使用的，是在默认实现情况下发现的问题吗？

**Comment by rememberber** [comment]
今天遇到了这个需求，看了一下源码好像是有问题，等我抽空优化一下，而且大概看了一下，这个还是in memory的，这样对于分布式或者多机负载的情况会有问题

**Comment by rememberber** [comment]
**我们的思路大致是这样：**
```java
// 事件排重
// 关注和扫码事件排除重复提交缓存Key
// 事件类型消息推荐使用FromUserName + event + CreateTime 排重
String SSEDSKey = new StringBuilder().append(RedisCacheConstant.SubscribeAndScanExcludeDuplicateSubmissions)
		.append(RedisCacheConstant.KeySeparator).append(wxMessage.getFromUser()).append(wxMessage.getEvent()).append(wxMessage.getCreateTime()).toString();

if (redisCacheService.isExistsKey(SSEDSKey)) {
    return null;
} else {
    redisCacheService.setValueByString(SSEDSKey, StringUtils.EMPTY);
    redisCacheService.setExpireByKey(SSEDSKey, 30);
}
```

**Comment by 18940818955** [comment]
也不是分布式系统啊，后来我用redis setnx方式实现了，就是有点low

**Comment by 18940818955** [comment]
`/**
   * 检测是否是重复消息
   */
  Boolean isDuplicateMessage(WxMpXmlMessage wxMessage) {
    String messageId;
    if (wxMessage.getMsgId() == null) {
      messageId = wxMessage.getCreateTime()
              + "-" + wxMessage.getFromUser()
              + "-" + (wxMessage.getEventKey() == null ? "" : wxMessage.getEventKey())
              + "-" + (wxMessage.getEvent() == null ? "" : wxMessage.getEvent());
    } else {
      messageId = String.valueOf(wxMessage.getMsgId());
    }
    return (Boolean) redisTemplate.execute((RedisCallback<Boolean>) redisConnection -> {
      Boolean aBoolean = redisConnection.setNX(messageId.getBytes(), String.valueOf(System.currentTimeMillis()).getBytes());
      if (aBoolean)
        redisConnection.expire(messageId.getBytes(), 10);
      return aBoolean;
    });
  }`

这是我的写法

**Comment by binarywang** [comment]
其实这个就是内存的实现，适合于单机，如果用在集群环境确实需要重新实现新的类。
