### ISSUE TITLE
请求添加摇一摇周边的相关接口

### ISSUE THREAD

**Issue by rememberber** [binarywang/WxJava#240]
### 请求添加摇一摇周边的接口： ###

感谢您的开源工具包，我们已经应用于生产，
最近需要摇一摇周边相关的业务，
所以恳请您添加摇一摇周边相关接口，
比如：

**获取设备及用户信息**
接口说明
获取设备信息，包括UUID、major、minor，以及距离、openID等信息。
接口调用说明
http请求方式: POST（请使用https协议）https://api.weixin.qq.com/shakearound/user/getshakeinfo?access_token=ACCESS_TOKENPOST数据格式：json
POST数据例子：
````
{
   "ticket":”6ab3d8465166598a5f4e8c1b44f44645”,
   "need_poi":1
}
````
正常时的返回JSON数据包示例：
````
{
   "data": {
       "page_id ": 14211,
       "beacon_info": {
           "distance": 55.00620700469034,
           "major": 10001,
           "minor": 19007,
           "uuid": "FDA50693-A4E2-4FB1-AFCF-C6EB07647825"
       },
       "openid": "oVDmXjp7y8aG2AlBuRpMZTb1-cmA",
       " poi_id":1234
   },
   "errcode": 0,
   "errmsg": "success."
}
````

**再次感谢，并期待……**

**Comment by binarywang** [comment]
可以，下次最好提供下原始文档的地址吧，便于参考。

**Comment by binarywang** [comment]
这个接口的地址是这个吧 https://mp.weixin.qq.com/wiki?action=doc&id=mp1443447963

**Comment by binarywang** [comment]
还以为只需要添加一个接口，仔细一看好像不止这一个，接口还挺多

**Comment by rememberber** [comment]
是的，不过我们好像又用不到了，当时我继承了你的代码自己写了这个接口，我有时间看看有权限的话也可以修改一下，然后push，或者申请merge

**Comment by binarywang** [comment]
@rememberber 不需要权限的，任何人都可以贡献代码，你只需要进行pull request即可，参考下代码贡献指南吧，很简单的。
https://github.com/Wechat-Group/weixin-java-tools/blob/master/contribution.md

**Comment by binarywang** [comment]
https://github.com/chanjarster/weixin-java-tools/pull/343 @rememberber 你能否将这个关掉，谢谢了

**Comment by binarywang** [comment]
@rememberber  我的意思是让你把你在chanjarster上提交的那个PR关掉

**Comment by rememberber** [comment]
没太弄明白怎么关闭，现在已经关闭了是吗？

发送自 Windows 10 版邮件应用

发件人: Binary Wang
发送时间: 2017年6月10日 17:33
收件人: Wechat-Group/weixin-java-tools
抄送: Bob; Mention
主题: Re: [Wechat-Group/weixin-java-tools] 请求添加摇一摇周边的相关接口 (#240)

@rememberber 我的意思是让你把你在chanjarster上提交的那个PR关掉

**Comment by binarywang** [comment]
我说的是这个，https://github.com/chanjarster/weixin-java-tools/pull/343 ， 当前这个已经关闭了，我有权限关闭，但是chanjarster的我没权限，他本人也没时间管理，那么目前就只能你自己操作了。

**Comment by rememberber** [comment]
前几天做的一个批量推送工具，
请求加入wechat-group，
或者帮忙推广，
非常感谢！
https://github.com/rememberber/WePush


发送自 Windows 10 版邮件应用

发件人: Binary Wang
发送时间: 2017年6月13日 10:16
收件人: Wechat-Group/weixin-java-tools
抄送: Bob; Mention
主题: Re: [Wechat-Group/weixin-java-tools] 请求添加摇一摇周边的相关接口 (#240)

我说的是这个，https://github.com/chanjarster/weixin-java-tools/pull/343，当前这个已经关闭了，我有权限关闭，但是chanjarster的我没权限，他本人也没时间管理，那么目前就只能你自己操作了。
