### ISSUE TITLE
WxCpService.userList（）获取不到WxCpUser中的tel

### ISSUE THREAD

**Issue by Ianlyly** [binarywang/WxJava#246]
原因 微信api返回的字段为"telephone"  与tel 不一致
修改WxCpUserGsonAdapter中user.setTel(GsonHelper.getString(o, "tel"));为user.setTel(GsonHelper.getString(o, "telephone"));即可

**Comment by binarywang** [comment]
能方便提供文档地址吗？我在如下文档上没有看到相关说明，http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AE%A1%E7%90%86%E6%88%90%E5%91%98

**Comment by binarywang** [comment]
获取部门成员(详情)

请求说明
Https请求方式: GET

https://qyapi.weixin.qq.com/cgi-bin/user/list?access_token=ACCESS_TOKEN&department_id=DEPARTMENT_ID&fetch_child=FETCH_CHILD&status=STATUS

参数说明
参数	必须	说明
access_token	是	调用接口凭证
department_id	是	获取的部门id
fetch_child	否	1/0：是否递归获取子部门下面的成员
status	否	0获取全部成员，1获取已关注成员列表，2获取禁用成员列表，4获取未关注成员列表。status可叠加,未填写则默认为4
权限说明
管理组须拥有指定部门的查看权限。

返回结果
{
   "errcode": 0,
   "errmsg": "ok",
   "userlist": [
           {
                  "userid": "zhangsan",
                  "name": "李四",
                  "department": [1, 2],
                  "position": "后台工程师",
                  "mobile": "15913215421",
                  "gender": "1",
                  "email": "zhangsan@gzdev.com",
                  "weixinid": "lisifordev",  
                  "avatar":           "http://wx.qlogo.cn/mmopen/ajNVdqHZLLA3WJ6DSZUfiakYe37PKnQhBIeOQBO4czqrnZDS79FH5Wm5m4X69TBicnHFlhiafvDwklOpZeXYQQ2icg/0",
                  "status": 1,
                  "extattr": {"attrs":[{"name":"爱好","value":"旅游"},{"name":"卡号","value":"1234567234"}]}
           }
     ]
}
参数	说明
errcode	返回码
errmsg	对返回码的文本描述内容
userlist	成员列表
userid	成员UserID。对应管理端的帐号
name	成员名称
department	成员所属部门id列表
position	职位信息
mobile	手机号码。第三方不可获取
gender	性别。0表示未定义，1表示男性，2表示女性
email	邮箱。第三方不可获取
weixinid	微信号
avatar	头像url。注：如果要获取小图将url最后的"/0"改成"/64"即可
status	关注状态: 1=已关注，2=已冻结，4=未关注
extattr	扩展属性。第三方不可获取

**Comment by binarywang** [comment]
经过测试，比文档中多了几个属性：
```
{
  "userid": "CeShi",
  "name": "测试",
  "department": [
    2
  ],
  "position": "",
  "mobile": "17091088234",
  "gender": "0",
  "email": "",
  "avatar": "http://shp.qpic.cn/bizmp/Jvns9oYmmI4tCAJfnMWfEicX3D7SgLcd9m0IKQECKHEgrd3aHgEwpbA/",
  "status": 1,
  "enable": 1,
  "isleader": 0,
  "extattr": {
    "attrs": [
      
    ]
  },
  "hide_mobile": 0,
  "english_name": "",
  "telephone": ""
}
```

**Comment by binarywang** [comment]
经过对比，将移除weixinid、tel，增加telephone, english_name, hide_mobile三个字段。
