### ISSUE TITLE
开发诡异的40029错误invalid code错误 443 failed to respond错误的

### ISSUE THREAD

**Issue by henning01** [binarywang/WxJava#248]
用的2.5的mp jar包  调用WxMpOAuth2AccessToken  accessToken= wxMpService.oauth2getAccessToken(code);
 微信偶尔 会返回 40029 错误invalid code 或者   错误 443 failed to respond错误

![image](https://user-images.githubusercontent.com/17242272/26967173-dab4e318-4d2f-11e7-841f-7cc9ffb8a738.png)   调用的时候增加了   
 解决方式 参考  http://blog.csdn.net/achenyuan/article/details/72956292

**Comment by binarywang** [comment]
看了你所转发的文章，其实问题原因就是https请求证书验证的问题是吧
