### ISSUE TITLE
建议keypath可以使用jar包里面资源

### ISSUE THREAD

**Issue by niusibao** [binarywang/WxJava#251]
要不然证书只能放在spring boot生成的jar包外面

**Comment by binarywang** [comment]
我感觉像证书这类的东西，是不是一般都放在服务器上，由运维人员管理的，你打到jar包里，会不会有安全隐患？

**Comment by binarywang** [comment]
不管怎样，也许有这个需求吧，代码现在已做了支持，即支持以“classpath:”开始的路径。
