### ISSUE TITLE
添加图文消息留言管理接口的支持

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#252]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1494572718_WzHIY

新地址：
https://developers.weixin.qq.com/doc/offiaccount/Comments_management/Image_Comments_Management_Interface.html

**Comment by binarywang** [comment]
2.1 打开已群发文章评论（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/open?access_token=ACCESS_TOKEN

2.2 关闭已群发文章评论（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/close?access_token=ACCESS_TOKEN

2.3 查看指定文章的评论数据（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/list?access_token=ACCESS_TOKEN


2.4 将评论标记精选（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/markelect?access_token=ACCESS_TOKEN

2.5 将评论取消精选
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/unmarkelect?access_token=ACCESS_TOKEN

2.6 删除评论（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/delete?access_token=ACCESS_TOKEN

2.7 回复评论（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/reply/add?access_token=ACCESS_TOKEN

2.8 删除回复（新增接口）
接口调用请求说明
https 请求方式: POST
https://api.weixin.qq.com/cgi-bin/comment/reply/delete?access_token=ACCESS_TOKEN

**Comment by AaricChenLegacy** [comment]
你好  请问此功能计划在哪个版本发布

**Comment by binarywang** [comment]
@AaricChen 等有时间了再实现，因为接口比较多，你如果有某个比较紧急的接口，可以提出来单独先实现下。

**Comment by chaclus** [comment]
@binarywang 嗨，用户留言管理是没有添加吗？为什么看您添加了又removed呢？在api中也没见service实现

**Comment by binarywang** [comment]
removed 只是对应的标签。这个issue一直没关闭，就说明还没实现完毕，只是实现了一部分

**Comment by AaricChenLegacy** [comment]
你好，这个功能已经快一年了，请问大概在什么时候可以开放，谢谢

**Comment by binarywang** [comment]
接口太多，使用的人也不多，所以一直没弄，希望需要相应接口的帮忙实现一下，当然如果你觉得急需这些接口，不要再等待了，自己动手实现然后提交PR吧，毕竟等待有可能是无限期的。

**Comment by jovinlee** [comment]
求支持

**Comment by binarywang** [comment]
接口比较多，如果你比较急着使用，欢迎自己动手提交PR @jovinlee

**Comment by hanjianchun** [comment]
@binarywang 您好，使用Api推送图文消息并开启了评论，在微信后台可以看到评论数量但是显示不出评论内容，您知道是什么原因吗？

**Comment by binarywang** [comment]
> @binarywang 您好，使用Api推送图文消息并开启了评论，在微信后台可以看到评论数量但是显示不出评论内容，您知道是什么原因吗？

不清楚了

**Comment by binarywang** [comment]
3.6.9.B测试版本已增加剩下的接口，欢迎使用
