### ISSUE TITLE
企业号对未关注人员发送消息没有处理

### ISSUE THREAD

**Issue by jibaojie** [binarywang/WxJava#253]
对未关注人员发送消息没有抛异常，返回为void，希望修正

**Comment by binarywang** [comment]
https://work.weixin.qq.com/api/doc#10167
http://qydev.weixin.qq.com/wiki/index.php?title=%E5%8F%91%E9%80%81%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E
对照企业微信和微信企业号的文档看了下，“如果部分接收人无权限或不存在，发送仍然执行，但会返回无效的部分”

**Comment by binarywang** [comment]
解决办法：修改me.chanjar.weixin.cp.api.impl.AbstractWxCpServiceImpl#messageSend方法，增加返回值WxCpMessageSendResult，客户端可以通过WxCpMessageSendResult来判断对应消息发送结果，根据自己需要进行处理。

**Comment by jibaojie** [comment]
OK，谢谢
