### ISSUE TITLE
关于服务商模式下统一下单接口增加sub_openid字段

### ISSUE THREAD

**Issue by leiorixsoft** [binarywang/WxJava#255]
文档地址：https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_1
现在代码里:WxPayUnifiedOrderRequest中的openid是服务商appid下对应的openid，不是sub_appid下对应的openid，而服务商模式下要求参数sub_openid没有给值，所以微信返回openid和appid不匹配的错误码。

**Comment by binarywang** [comment]
2.7.1.BETA测试版本  已修复

**Comment by Hard-bitten** [comment]
@binarywang  这里的问题依旧存在啊  虽然增加了sub_openid 但是我们没有办法得到服务商appid对应的openid  所以也没有办法完成支付

**Comment by binarywang** [comment]
谢谢提出这个问题，准备将相关判断逻辑去掉 @Hard-bitten
