### ISSUE TITLE
2.7版本的底层微信接口请求混乱

### ISSUE THREAD

**Issue by dylanleung** [binarywang/WxJava#258]
mp 模块默认使用httpClient .要是改用okHttp 就要在引入时加入 
```
 <exclusions>
        <exclusion>
          <groupId>org.apache.httpcomponents</groupId>
          <artifactId>*</artifactId>
        </exclusion>
 </exclusions>

```
再引入okHttp的包
.
Pay模块只能使用了jodd.
同时使用mp 模块和Pay模块时要单独引入jodd模块.不然会出错.

个人建议.把底层请求模式统一.
同时修改pom的依赖关系.把调用包的选择交给用户.  添加说明文档

**Comment by binarywang** [comment]
感谢提出，pay模块的问题已经发现并修复了。
后期会考虑统一起来，还是准备默认使用httpclient，其他框架如果想使用，可以单独指定

**Comment by binarywang** [comment]
wiki已添加，https://github.com/Wechat-Group/weixin-java-tools/wiki/http%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%89%E7%94%A8%E8%AF%B4%E6%98%8E

如有不完善的地方，欢迎帮忙补充。
