### ISSUE TITLE
关于微信公众号httpclient线程的问题

### ISSUE THREAD

**Issue by shijiuyan** [binarywang/WxJava#261]
在WxMpServiceImpl里每次setWxMpConfigStorage时都会创建一个线程，我现在有几十个公众号需要动态去setWxMpConfigStorage，这样会导致程序启动大量的线程，这个该如何避免？

**Comment by binarywang** [comment]
请保证WxMpServiceImpl是单例的

**Comment by shijiuyan** [comment]
我现在WxMpServiceImpl是单例的，setWxMpConfigStorage的时候会调用initHttpClient()启动线程

**Comment by shijiuyan** [comment]
@binarywang 我现在WxMpServiceImpl就是单例的，现在是调用setWxMpConfigStorage的时候会执行initHttpClient()启动线程

**Comment by bysunexus** [comment]
建议自己初始化一个ApacheHttpClientBuilder的实例，将这个实例设置到WxMpConfigStorage中。
所有的WxMpConfigStorage设置的都是同一个ApacheHttpClientBuilder的实例。
如果WxMpConfigStorage中没有持有ApacheHttpClientBuilder的实例的话，每次设置的时候时都会初始化的。

FYI

[代码](https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/impl/WxMpServiceApacheHttpClientImpl.java#L45)

**Comment by shijiuyan** [comment]
好的，谢谢
