### ISSUE TITLE
是不是应该在WxCpConfigStorage中加入一个通讯录密码

### ISSUE THREAD

**Issue by smallgoldstone** [binarywang/WxJava#264]
在企业微信中管理通讯录需要用通讯录同步，这个密码与应用的密码不一样。

**Comment by binarywang** [comment]
只是加入这个密码就行了吗？其他代码难道不需要更改？

**Comment by firesh** [comment]
可以通过维护2个WxCpService实例来解决，其中一个专门来处理通讯录接口。
一个WxCpService，搞不定的，因为token不一样、权限不一样。

**Comment by binarywang** [comment]
就是说相当于多企业号应用了，跟多公众号的是一个原理。

**Comment by cherry-yang-workspace** [comment]
可以用工厂模式创建多个wxCpService实例
