### ISSUE TITLE
在使用统一下单的时候，调用基类的fromXML 出现java.lang.ClassCastException

### ISSUE THREAD

**Issue by IdoFree** [binarywang/WxJava#267]
com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderResult cannot be cast to com.github.binarywang.wxpay.bean.result.WxPayBaseResult

 public static <T extends WxPayBaseResult> T fromXML(String xmlString, Class<T> clz) {
    XStream xstream = XStreamInitializer.getInstance();
    xstream.processAnnotations(clz);
    T result =  (T) xstream.fromXML(xmlString);
    result.setXmlString(xmlString);
    return result;
  }

**Comment by binarywang** [comment]
请问你是如何调用的代码？

**Comment by IdoFree** [comment]
代码是从你的demo中copy过来的，还没修改

**Comment by binarywang** [comment]
能否明确说明下调用步骤？我自己测试没发现什么问题。
如果是demo的问题的话，能否到demo下面讨论问题，多谢了~
