### ISSUE TITLE
weixin-java-cp WxCpUserServiceImpl 删除用户的接口有问题

### ISSUE THREAD

**Issue by axiu90** [binarywang/WxJava#268]
单个用户删除之后，还会再发一遍批量删除的请求
@Override
  public void delete(String... userIds) throws WxErrorException {
    if (userIds.length == 1) {
      this.deleteOne(userIds[0]);
    }

    String url = "https://qyapi.weixin.qq.com/cgi-bin/user/batchdelete";
    JsonObject jsonObject = new JsonObject();
    JsonArray jsonArray = new JsonArray();
    for (String userid : userIds) {
      jsonArray.add(new JsonPrimitive(userid));
    }
    jsonObject.add("useridlist", jsonArray);
    this.mainService.post(url, jsonObject.toString());
  }

**Comment by binarywang** [comment]
感谢及时提出此问题，稍后进行修复

**Comment by binarywang** [comment]
2.7.4.BETA版本已修复
