### ISSUE TITLE
WxMpServiceOkHttpImpl 的实现有问题.和commons-lang3 的版本说明.

### ISSUE THREAD

**Issue by dylanleung** [binarywang/WxJava#269]
使用okHttp 的实现调用.无法上传临时素材和永久素材图片.微信返回'{"errcode":41005,"errmsg":"media data missing"}'.
目前我只能切换会httpClient 调用.

**Comment by binarywang** [comment]
@crskyp 帮忙看下okhttp的实现是不是有什么不完善的地方？

**Comment by crskyp** [comment]
收到

**Comment by crskyp** [comment]
是否可以提供下具体运行的代码

**Comment by binarywang** [comment]
@crskyp 跑下单元测试就可以看到问题了，没事我在看了，正好有点时间

**Comment by crskyp** [comment]
@binarywang 谢谢群主，我晚上才有时间

**Comment by binarywang** [comment]
已找到原因并修复

**Comment by crskyp** [comment]
群主威武

**Comment by binarywang** [comment]
@dylanleung  `commons-lang3 的版本说明` 标题中提到的这个是什么意思？

**Comment by binarywang** [comment]
2.7.4.BETA版本已修复
