### ISSUE TITLE
CP里NewArticle和MpnewsArticle对象不能序列化

### ISSUE THREAD

**Issue by caocharlie** [binarywang/WxJava#270]
由于me.chanjar.weixin.cp.bean.article.NewArticle和MpnewsArticle没有实现Serilizable接口。
所以在通过MQ的生产者将WxCpMessage加入消息队列后会出现不能序列化的异常。

**Comment by binarywang** [comment]
可以，稍后做支持。

**Comment by binarywang** [comment]
2.7.4.BETA版本已修改

**Comment by caocharlie** [comment]
3Q。响应及修改很是及时啊。赞一个！
