### ISSUE TITLE
关于H5支付，提个疑问，不是bug

### ISSUE THREAD

**Issue by 565444118** [binarywang/WxJava#272]
我看官方文档H5支付的统一下单接口中的参数 场景信息（scene_info ）是必传项，为什么WxPayUnifiedOrderRequest这实体类中却没有这个属性字段？

**Comment by binarywang** [comment]
看来这个参数是H5支付独有的（且必须提供的，其它支付方式也是后来才加的，感觉是偷偷加的），稍后加一下

**Comment by binarywang** [comment]
2.7.5.BETA测试版本已添加
