### ISSUE TITLE
关于统一下单的问题

### ISSUE THREAD

**Issue by liuzhihai520** [binarywang/WxJava#277]
今天在测试调用统一下单接口的时候，我再把参数填写完毕执行POST的时候。始终提示我缺少参数。看打印的日志如下：
<nonce__str>1499853099495</nonce__str>
<sign>E7E5E43D7AE4E412462039CE3F3C41C8</sign>
<body>口令红包-红包</body>
<detail>口令红包-红包</detail>
<out__trade__no>20170712175130715355469</out__trade__no>
<total__fee>100</total__fee>
<spbill__create__ip>127.0.0.1</spbill__create__ip>
<notify__url>http://127.0.0.1:8080/123</notify__url>
<trade__type>JSAPI</trade__type>

name  下划线为__不知道是否有问题？正常应该是_?

**Comment by binarywang** [comment]
测试了下并未发现双下划线问题，你用的是哪里的代码？

**Comment by liuzhihai520** [comment]
就是maven上同步下来的。然后调用的您的支付接口。版本是2.7.0

**Comment by binarywang** [comment]
你看下这个类 `me.chanjar.weixin.common.util.xml.XStreamInitializer`
里面专门有处理的，不知道你怎么调用的代码导致的问题

**Comment by liuzhihai520** [comment]
![image](https://user-images.githubusercontent.com/2859095/28115589-1f8b9046-6738-11e7-97cf-f660378764ef.png)
就这一段。然后就是配置。应该和配置没多大关系。有点费解。

**Comment by binarywang** [comment]
那看看你的xstream版本是不是有问题

**Comment by liuzhihai520** [comment]
我找到问题了。我pom。xml里面有一个以前的cp版本的jar没去掉。去掉就可以了。

**Comment by binarywang** [comment]
醉了，好吧
