### ISSUE TITLE
2.5.0的grooy调用导致metaspace oom

### ISSUE THREAD

**Issue by sunwuxiang** [binarywang/WxJava#278]
2.5.0的grooy调用导致metaspace oom，是不是每次转账调groovy加载的class，一直不会卸载呢？

**Comment by binarywang** [comment]
2.5.0 有点老，建议升级版本

**Comment by sunwuxiang** [comment]
是否可以确定是2.5.0的groovy引起的？如果不是我们可能要排查其他原因

**Comment by binarywang** [comment]
不明白你为什么提到groovy？

**Comment by binarywang** [comment]
2.5.0的版本号你是指的你使用的groovy的版本号？

**Comment by sunwuxiang** [comment]
meta oom的时候，打出来的堆栈就是正在调用AssertionSupport.groovy的线程栈，所以才会怀疑和groovy有关，怀疑是不是CallSiteGenerator的compilePogoMethod方法加载的类会持续堆积

**Comment by sunwuxiang** [comment]
2.5.0是weixin-java-tools的版本号，groovy的版本号是2.4.6

**Comment by binarywang** [comment]
以前的版本可能引用其他类库间接引用到groovy，不甚合理，后期版本已经移除，目前最新正式版本是2.7.0，建议升级。

**Comment by sunwuxiang** [comment]
好的
