### ISSUE TITLE
统一下单接口参数对象WxPayUnifiedOrderRequest 缺少fingerprint属性

### ISSUE THREAD

**Issue by 565444118** [binarywang/WxJava#279]
如题。WxPayUnifiedOrderRequest 现在没有浏览器指纹指引属性字段fingerprint。
参见微信相关文档：https://pay.weixin.qq.com/wiki/doc/api/H5.php?chapter=15_7&index=6

**Comment by binarywang** [comment]
2.7.6.BETA测试版本已支持
