### ISSUE TITLE
生成200万个二维码，每个只能扫一次就会失效

### ISSUE THREAD

**Issue by lqm627** [binarywang/WxJava#28]
具体的需求是：用户通过扫二维码，已关注的用户直接跳转到活动页面，未关注的用户会先跳转到关注页面，关注后也同样跳转到活动页面，是扫码后直接跳转页面！！！好像目前微信只能做到扫码后推送链接消息，再点击链接消息才能跳转到页面！！！还有被扫的二维码要求被扫了一次后就不能再使用！！！要200万个！！！我看了微信的带参永久二维码接口，最多只能10万个！！！并且同一个scene_id的情况下生成的二维码是一样的，我们需要的二维码是都不一样的！！！就算我只生成10万个不同scene_id的永久带参二维码（实际还是要200万个的），那我就要设置10万个不同的scene_id，并且每个scene_id还要写两种情况的事件拦截，一个是已关注的情况下，另一个是未关注的情况下，所以最后是要拦截20万个扫码事件。不可能真的这样去写20万个消息路由去拦截这10万个不同scene_id的扫码事件吧？各位有什么好的解决方法啊？@binarywang

**Comment by binarywang** [comment]
首先，扫码后直接跳转链接，微信没有提供这种场景，所以你可以放弃这种想法了。
其次，关注和非关注的问题，你可以写个公用的方法处理，分别在关注和扫码事件里处理，你只需要分别在对应的handler里调用共用方法就可以，根据具体的scene_id去做判断，相信你本地应该做相应的存储了吧？
再者，永久二维码，每个公众号就是只有那10万个，是没办法的，微信规定的。

**Comment by lqm627** [comment]
那个消息路由的拦截是根据    eventKey去拦截的，未关注的情况：       .rule()
                .async(false)
                .msgType(WxConsts.XML_MSG_EVENT).event(WxConsts.EVT_SUBSCRIBE).eventKey("qrscene_car")
                .handler(demo2)
              .end()
已关注的情况：          .rule()
            .async(false)
            .msgType(WxConsts.XML_MSG_EVENT).event(WxConsts.EVT_SCAN).eventKey("car")
            .handler(demo3)
          .end()
这样我不还是要写好多个handler去拦截吗？还有我提到的那个二维码扫码一次就失效的效果如何去实现？@binarywang

**Comment by binarywang** [comment]
你不会把eventKey的判断放到handler里进行吗？

**Comment by binarywang** [comment]
扫码一次就失效，你可以在你的程序里控制吧？

**Comment by lqm627** [comment]
那就是我在用户第一次扫描后插一条记录到数据库，再扫的时候判断是否有这一条记录，没有就推链接消息，有就推文本信息告诉它二维码失效吧？其实二维码一直都可以扫，只是判断后不给他链接消息推送而已吧？

**Comment by lqm627** [comment]
好吧，我写习惯了，没认真去看源码，好像是可以把eventKey值放到hander拦截器里面再去取出来判断，再根据取出来的eventKey去数据库查询是否有这个eventKey值

**Comment by binarywang** [comment]
没错，如果问题解决了，就关掉吧
