### ISSUE TITLE
微信生成临时二维码

### ISSUE THREAD

**Issue by mmx1960** [binarywang/WxJava#288]
现在只支持int类型得场景值，能否也支持string类值的场景值

**Comment by binarywang** [comment]
可以，这个居然存在很久了，没其他人发现

**Comment by binarywang** [comment]
怀疑是不是微信接口文档后来悄悄加上的？

**Comment by mmx1960** [comment]
不清楚，不过临时二维码很少用到，估计别人没发现。。。

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/pull/289 有人提供了新的接口

**Comment by binarywang** [comment]
临时测试版本2.7.7.BETA 已实现
