### ISSUE TITLE
我可以贡献我的第一次PR么,关于OkHttp的使用和JSApi的bug

### ISSUE THREAD

**Issue by dylanleung** [binarywang/WxJava#293]
在实际使用中发觉发送消息和处理素材图文上下传文件二进制特别慢.
根据官方文档说OkHttp performs best when you create a single 和我以前使用的经验.
修改为OkHttpClient 直接替代ConnectionPool,  OkHttpClient 底层会自动管理连接池而且效率性能特好(连接池默认5条,往后可以在ConfigStorage 添加设置连接池数量).
同时修改了文件的下载方法.直接使用OkHttp 底层 Okio 写入的方式(高性能且简单)

getJsapiTicket 这个接口里面的lock 实际调用为空.ReentrantLock 这个共享锁应该一个类只能有一个实例.

**Comment by dylanleung** [comment]
代码跑过测试用例(部分测试代码没实现没测试).准备直接更新上项目使用了.

**Comment by binarywang** [comment]
多谢
