### ISSUE TITLE
WxMessageInMemoryDuplicateChecker

### ISSUE THREAD

**Issue by tomsean** [binarywang/WxJava#299]
![20170801162136](https://user-images.githubusercontent.com/5907239/28815914-88f75c66-76d5-11e7-8016-a84fb316d711.png)
TIMED_WAITING
消息排重--线程TIMED_WAITING

**Comment by binarywang** [comment]
这个是正常的，本来这个线程就是在后台一直启动着的

**Comment by tomsean** [comment]
多个微信公众平台得时候，或是使用spring去构建得时候会造成线程一直增加，然后崩掉

**Comment by binarywang** [comment]
多个时候就不应该用这个InMemory的了，你需要自己实现一个

**Comment by jink2005** [comment]
>nested exception is java.lang.OutOfMemoryError: unable to create new native thread
 at me.chanjar.weixin.common.api.WxMessageInMemoryDuplicateChecker.checkBackgroundProcessStarted(WxMessageInMemoryDuplicateChecker.java:84) ~[weixin-java-common-3.3.0.jar:?]

是不是wxMpMessageRouter也应该是单例，否则就会创建有很多个checkBackgroundProcessStarted后台线程吧？

**Comment by binarywang** [comment]
当然了
