### ISSUE TITLE
微信多媒体文件没有后缀名时下载失败

### ISSUE THREAD

**Issue by xiaohe27** [binarywang/WxJava#300]
对于用户发给企业微信的语音消息，在下载时得到的是一个没有后缀名的文件，文件名默认是“voice”。
这导致了wxCpService.mediaDownload(media_id) 这个默认的下载多媒体文件的接口抛出异常。

在[ApacheMediaDownloadRequestExecutor.java](https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/http/apache/ApacheMediaDownloadRequestExecutor.java)
文件中
 
      String fileName = getFileName(response);
      if (StringUtils.isBlank(fileName)) {
        return null;
      }

      String[] nameAndExt = fileName.split("\\.");
      return FileUtils.createTmpFile(inputStream, nameAndExt[0], nameAndExt[1], super.tmpDirFile);

会抛出ArrayIndexOfBoundsException

**Comment by xiaohe27** [comment]
@binarywang

**Comment by binarywang** [comment]
看起来确实是个问题，稍后修复下

**Comment by binarywang** [comment]
临时测试版本2.7.8.BETA已修复
