### ISSUE TITLE
是否支持多个小程序关联

### ISSUE THREAD

**Issue by zhoumh1988** [binarywang/WxJava#303]
在同一个项目下关联多个小程序appid，如何实现？

**Comment by binarywang** [comment]
你可以参考公众号的相关demo实现，自己尝试下

**Comment by einsitang** [comment]
@zhoumh1988 使用factory类输入不同的配置，然后输出不同的service实例代表不同的小程序

**Comment by binarywang** [comment]
没有进一步反馈，暂时关闭

**Comment by gclsoft** [comment]
@forfuns factory类输入不同的配置这个要怎么实现, 有例子吗?
