### ISSUE TITLE
WxMpGetSelfMenuInfoResult 无法正常解析为javabean

### ISSUE THREAD

**Issue by jacky8466** [binarywang/WxJava#304]
运行 weixin-java-mp-demo时：
下面是微信返回的自定义菜单数据：
【请求地址】: https://api.weixin.qq.com/cgi-bin/get_current_selfmenu_info?access_token=*******
【请求参数】：null
【响应数据】：{"is_menu_open":1,"selfmenu_info":{"button":[{"type":"text","name":"关于我们","value":"安徽沃谷生态农业科技有限公司，全心致力于现代农业，生态农品。“梦雅果儿”，本着“取料原产地，全程最新鲜，极致优服务”品牌核心，全面布局新鲜水果连锁经营进社区的目标规划，全力打造“美味，营养，新鲜”的品牌形象。"}]}}
可是浏览器里报错(也就是解析成javabean时报错)：
 Could not write content: No serializer found for class me.chanjar.weixin.mp.bean.menu.WxMpSelfMenuInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: me.chanjar.weixin.mp.bean.menu.WxMpGetSelfMenuInfoResult["selfMenuInfo"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class me.chanjar.weixin.mp.bean.menu.WxMpSelfMenuInfo and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: me.chanjar.weixin.mp.bean.menu.WxMpGetSelfMenuInfoResult["selfMenuInfo"]

我又把这些代码放到我自己的项目中：解析数据丢失，返回的只有：{
    "isMenuOpen": 1,
    "selfMenuInfo": {}
}
我使用的是fastJson，后来多次尝试，加上GsonHttpMessageConverter，放在第一位，返回才算正常：
<mvc:message-converters register-defaults="false">
			<ref bean="gsonConverter" />
			<ref bean="fastJsonMessageConverter" />
			<ref bean="stringHttpMessageConverter" />
		</mvc:message-converters>

java bean解析限制太多了

**Comment by binarywang** [comment]
这个默认使用的是gson的，所以你用fastjson是不行的

**Comment by jacky8466** [comment]
我看了源码，javabean上的注解使用的是gson，这样做的话，别人想把返回的结果解析成json格式的话，只能使用gson了，别无他法，除非再做一次属性拷贝，我希望能提供一个直接返回json格式的接口或者选择使用gson还是fastjson或者jackson让开发者自己选择 @binarywang

**Comment by binarywang** [comment]
关于json的选择这个问题我们考虑过，没有完美的解决方案，总得选择一种方案，一直用的就是gson，而且gson本来也只是内部使用，是为了方便微信接口的调用。至于外部使用，自己可以单独想办法。
或者你有好的方案提供出来也行。

**Comment by binarywang** [comment]
暂时关闭
