### ISSUE TITLE
是否应该使用注解风格的消息路由机制？

### ISSUE THREAD

**Issue by darknesstm** [binarywang/WxJava#306]
当前的编码方式的消息路由方式，个人感觉不够简单和友好，是否可以参考spring-amqp的风格

增加一个 @WeixinMessageListener ，用于指定当前方法处理的 消息类型 和限定条件，优先级顺序。

另外目前多个WxMpService之间是否无法复用 httpclient？

**Comment by bysunexus** [comment]
httpclient可以复用,请参考[https://github.com/wechat-group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95](https://github.com/wechat-group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95)

**Comment by binarywang** [comment]
@darknesstm 如果方便的话提供下你的实现代码吧，你说的注解方式还真不了解。

**Comment by darknesstm** [comment]
@binarywang 目前刚开始准备在一个新项目中使用这个库，等我开发一段时间后，提供一些参考代码吧

**Comment by binarywang** [comment]
@darknesstm 期待你的代码

**Comment by darknesstm** [comment]
不好意思，最终实现的时候还是简单对微信接口进行了包装而已，处理消息部分使用了简单的责任链方式来处理，因为是分布式系统，不适合使用内存方式定义的路由规则等
对于token的处理，采用数据库进行持久化，需要的时候检查时间，临近时间再进行更新
