### ISSUE TITLE
微信对账文件的下载和解析有问题

### ISSUE THREAD

**Issue by EddyChen** [binarywang/WxJava#308]
在程序包中看到有 wxPayBillBaseResult  但是调用对账单下载接口时 解析的列数据会错位！
SUCCESS REFUND ALL 不同的类型 微信返回的对账单数据列不同

**Comment by DDLeEHi** [comment]
能否把你错位信息贴出来，方便我们找出问题？

**Comment by binarywang** [comment]
也有可能是版本问题，不是最新的吗？

**Comment by EddyChen** [comment]
不好意思，是我的问题，确切的说是微信的问题，是沙箱环境下的数据有问题，微信测试沙箱提供的数据没有对齐，而且数据列和文档的列说明也不符合。

**Comment by EddyChen** [comment]
不过，现在的结果解析是针对 ALL 这种情况的吧？SUCCESS 和 REFUND 的数据按照这种情况 在第14列数据之后会有问题吧？
以下是微信文档中的数据文件列说明

当日所有订单 ALL
交易时间,公众账号ID,商户号,子商户号,设备号,微信订单号,商户订单号,用户标识,交易类型,交易状态,付款银行,货币种类,总金额,代金券或立减优惠金额,微信退款单号,商户退款单号,退款金额,代金券或立减优惠退款金额，退款类型，退款状态,商品名称,商户数据包,手续费,费率

当日成功支付的订单 SUCCESS 
交易时间,公众账号ID,商户号,子商户号,设备号,微信订单号,商户订单号,用户标识,交易类型,交易状态,付款银行,货币种类,总金额,代金券或立减优惠金额,商品名称,商户数据包,手续费,费率

当日退款的订单 REFUND
交易时间,公众账号ID,商户号,子商户号,设备号,微信订单号,商户订单号,用户标识,交易类型,交易状态,付款银行,货币种类,总金额,代金券或立减优惠金额,退款申请时间,退款成功时间,微信退款单号,商户退款单号,退款金额,代金券或立减优惠退款金额,退款类型,退款状态,商品名称,商户数据包,手续费,费率

**Comment by EddyChen** [comment]
还有个问题 现在的数据解析好像没有考虑请求微信的返回数据是 GZIP 的情况？ 全部都是按照流数据处理的？

**Comment by DDLeEHi** [comment]
我当初是这么想的，把ALL的数据全部导出来，你再要REFUND或者SUCCESS数据自己再去拆，这个看自己业务需要，至于GZIP，可以提个PR

**Comment by binarywang** [comment]
已新建issue ：https://github.com/Wechat-Group/weixin-java-tools/issues/321
关闭此issue
