### ISSUE TITLE
支持【企业微信通讯录变更】的事件推送

### ISSUE THREAD

**Issue by lhshin** [binarywang/WxJava#309]
企业微信的sdk没有处理 企业微信那边推送过来的人员变更事件
现在在本地系统修改用户的电话号码不会更新到企业微信上面了 只能用户自己改 这时候本地系统需要更新这个信息的话 必须要接收企业微信服务器那边通讯录变更事件 但是我看了下 好像sdk里面没有这方面的处理 
WxCpXmlMessage里面没有相关的字段信息

**Comment by binarywang** [comment]
后期补一下

**Comment by binarywang** [comment]
文档地址：https://work.weixin.qq.com/api/doc#10427/通讯录变更事件

**Comment by einsitang** [comment]
好像与事件相关的cp都没有

**Comment by mywsat** [comment]
模仿微信开放平台 完成了redis的实现。怎么push?给个链接教程

**Comment by binarywang** [comment]
什么redis？跟这个有关系么？想提交代码，请参考首页的贡献指南链接

**Comment by webcreazy** [comment]
WxConsts类中没有通讯录变更事件的类型如change_contact
文档：https://work.weixin.qq.com/api/doc#12974/%E6%96%B0%E5%A2%9E%E6%88%90%E5%91%98%E4%BA%8B%E4%BB%B6

**Comment by binarywang** [comment]
确实还没有，都没支持

**Comment by binarywang** [comment]
3.1.7.BETA测试版本已添加
