### ISSUE TITLE
二维码生成接口是否可以支持QR_STR_SCENE使用字符串生成临时二维码？

### ISSUE THREAD

**Issue by tastypinenut** [binarywang/WxJava#311]
微信文档中支持QR_STR_SCENE为临时的字符串参数，生成临时二维码，但接口中只有通过int类型，对使用场景有限制，建议增加使用以字符串为场景值的临时二维码生成接口
文档详见：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1443433542

**Comment by binarywang** [comment]
已实现 https://github.com/Wechat-Group/weixin-java-tools/pull/289

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/issues/288

**Comment by binarywang** [comment]
临时测试版本2.7.7.BETA 已实现
