### ISSUE TITLE
缺少 删除群发 的功能

### ISSUE THREAD

**Issue by semihawk** [binarywang/WxJava#312]
缺少微信公众号文档
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21
中 删除群发 这个接口API的功能
https://api.weixin.qq.com/cgi-bin/message/mass/delete?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
之后加一下

**Comment by binarywang** [comment]
测试版本2.7.9.BETA已添加

**Comment by fish008eb** [comment]
Integer msgId 已经发现会超过最大值

**Comment by binarywang** [comment]
楼上的你好，新问题请单独提，便于跟踪，不要提在已经关闭的里面，谢谢
