### ISSUE TITLE
WxMpService类能否开放接口，让外部可以设置具体的service？

### ISSUE THREAD

**Issue by guqun** [binarywang/WxJava#318]
如题，目前只有get，没有set，有了set接口后便于sdk没有发布的情况下，开发者可以实现自己的service，并set到WxMpService。

**Comment by binarywang** [comment]
你可以使用get或post方法，这个在wiki里有说明

**Comment by guqun** [comment]
看了wiki，如果有set方法覆盖原来的service，这样子在使用时候，可以跟你的sdk没有什么区别。也便于代码维护。

**Comment by binarywang** [comment]
那我明白你的意思了，可以加上

**Comment by binarywang** [comment]
测试版本2.7.9.BETA已添加
