### ISSUE TITLE
实现用户黑名单管理接口

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#32]
参考文档 http://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1471422259_pJMWA&token=&lang=zh_CN

**Comment by kareanyi** [comment]
....这个的文档上面好几个错误 = =

**Comment by binarywang** [comment]
比如呢？你要开始实现了吗？

**Comment by kareanyi** [comment]
咩有啊。中秋看下能不能搞

**Comment by kareanyi** [comment]
@binarywang pushed in develop branch

**Comment by kareanyi** [comment]
done
