### ISSUE TITLE
微信支付下载对账单接口增加对GZIP格式的支持

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#321]
文档地址：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_6

**Comment by binarywang** [comment]
同时可以考虑实现 https://github.com/Wechat-Group/weixin-java-tools/issues/308#issuecomment-321481752所提内容

**Comment by bysunexus** [comment]
建议：一般对账单都是在定时任务中跑的，其实这个接口返回流即可。对于解析可以放手或者提供utils。

**Comment by binarywang** [comment]
其实就是多做了些活，可以更方便开发者使用，省得去考虑各种处理了。

**Comment by binarywang** [comment]
2.9.2.BETA版本已添加支持
