### ISSUE TITLE
Bean序列化不全

### ISSUE THREAD

**Issue by ningtime** [binarywang/WxJava#322]
当前weixin-java-mp 2.7.0版本对Bean的序列化不彻底，有些做了序列化有些没有，希望补全一下。
 
   me.chanjar.weixin.mp.bean.*包中Bean

另外：
生成临时二维码接口：希望修改为long 类型，int类型长度不足，官网提供sceneId为32位非0整型，有时先手机号等较长整型不满足

@param sceneId       场景值ID，临时二维码时为32位非0整型
WxMpQrCodeTicket qrCodeCreateTmpTicket(int sceneId, Integer expireSeconds) throws WxErrorException;

**Comment by binarywang** [comment]
非常感谢提出宝贵建议，不过以后最好是每个问题单独提出issue，方便针对性的进行处理

**Comment by binarywang** [comment]
@ningtime 序列化的问题已补充完成，另外关于sceneId字段的问题，java的int类型即为32位整型，完全满足要求，没必要使用long。

**Comment by binarywang** [comment]
2.8.0已修复
