### ISSUE TITLE
减少Thread.sleep()的使用

### ISSUE THREAD

**Issue by nickwongwong** [binarywang/WxJava#323]
https://github.com/Wechat-Group/weixin-java-tools/blob/2b019f15cb8116e63166aef8bc42e0c88dcf5f15/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/impl/AbstractWxMpServiceImpl.java#L265
在大量请求下，Thread.sleep()可能会对线程池造成阻塞，占用大量的线程资源

**Comment by binarywang** [comment]
那你有什么好的方法没？

**Comment by nickwongwong** [comment]
actor模型，不过可能要对整体架构进行修改

**Comment by binarywang** [comment]
@nickwongwong 能否提供具体的实现思路，或者提交个PR看看？

**Comment by nickwongwong** [comment]
不好意思呀，最近加班比较多，感觉这个属于优化，后面有时间再想想

**Comment by starofys** [comment]
@binarywang 个人认为 ，在多次失败后，可以将对应的url加入一个失败的集合中，这个集合有一定的时效性，在下次请求时，可以只尝试请求1次或者根据前后时间差选择不请求，直接抛出异常

**Comment by binarywang** [comment]
@microxdd 好主意，才注意到，谢谢。
