### ISSUE TITLE
发送红包方法 2.7签名验证有问题，换成2.6就没有问题了

### ISSUE THREAD

**Issue by ty4cheung** [binarywang/WxJava#326]
这个方法失败了  payService.sendRedpack(request);

**Comment by binarywang** [comment]
你确定吗？2.7.0和2.6.0代码是一样的

**Comment by binarywang** [comment]
之前签名有问题，#140 已经修复过了

**Comment by binarywang** [comment]
@tylerchueng  如果你确认有问题，请再次回复吧，暂时关闭此Issue。
