### ISSUE TITLE
小程序微信支付支持吗？

### ISSUE THREAD

**Issue by fanxl12** [binarywang/WxJava#328]
如题，小程序微信支付支持吗？要怎么使用

**Comment by binarywang** [comment]
请查阅小程序支付官方文档，对应的接口都已经提供

**Comment by fanxl12** [comment]
@binarywang Ok，这边我已经实现了，我看微信支付默认配置了appId，统一下单接口，我看可以传配置过去，如果我默认配置的是小程序的appId，我公众号也需要微信支付，那公众号appId是不是可以传过去调用统一下单支付啊？

**Comment by binarywang** [comment]
可以传的，如果你传了，就会使用你传的参数
