### ISSUE TITLE
关于命名方式的一致性。

### ISSUE THREAD

**Issue by axeon** [binarywang/WxJava#329]
看demo的时候发现，小程序的命名和pay的命名方式完全不同。
appid=>appId，类似这种的不少。
建议一致化成后者appId，这样整个风格一致，写程序的时候会减少很多麻烦。

**Comment by binarywang** [comment]
这个以前统一做过检查，有的属于历史遗留原因，更改会引起版本不兼容，有的属于微信本身自己的命名问题不便于修改。你如果发现比较明显的不一致问题，请直接提交PR吧
