### ISSUE TITLE
调用WxCpXmlMessage.fromEncryptedXml生成的WxCpXmlMessage中的各项目值都是null

### ISSUE THREAD

**Issue by lottepie** [binarywang/WxJava#33]
企业号产生event（比如创建会话）回调的时候，程序中调用WxCpXmlMessage.fromEncryptedXml生成的WxCpXmlMessage中的各项目值都是null，貌似XML转bean的时候发生了异常

**Comment by binarywang** [comment]
@lottepie  问题解决了吗？你这个问题跟企业号会话是否支持有关系吗？

**Comment by lottepie** [comment]
有关系，企业会话的回调XML的格式与现在的WxCpXmlMessage有很大出入，所以转换bean的时候xstream报错了。现在是仿照WxCpXmlMessage写了一个企业会话用的bean去操作，并又改写了路由部分代码使其支持企业会话消息的分发，目前暂时能用，但是还没有严格测试。希望以后会官方支持企业会话回调。

**Comment by binarywang** [comment]
这个项目目前是要靠大家维护的，所以如果你觉得你的代码可以帮助到他人，可以提交上来吧
