### ISSUE TITLE
这个库没有封装开发平台的接口吗？

### ISSUE THREAD

**Issue by acom0828** [binarywang/WxJava#330]
这个库没有封装开发平台的接口吗？

**Comment by binarywang** [comment]
你说是开放平台的第三方平台吗？还没有实现，同#18

**Comment by acom0828** [comment]
getAccessToken那边用了Lock 如果高并发下会导致延迟、效率低吗

**Comment by binarywang** [comment]
会有影响，但是安全性也要兼顾，要不然不加锁会导致接口调用次数很快超限。
顺便提示下，如果是新问题请新开issue，要不显得很乱，这个就先关闭了。
