### ISSUE TITLE
关于Json，使用alibaba的fastjson是不是更好？

### ISSUE THREAD

**Issue by zhouwd** [binarywang/WxJava#331]
如题。我读代码的时候，发现项目中用的是gson。请教两者的优劣？

**Comment by bysunexus** [comment]
优劣的评判点，不只是速度。还有对规范的实现、扩展性、代码质量、社区等等。速度的适用也是相对的，如果你没有每天几百几千万的访问量，计较这些有些多余。

**Comment by zhouwd** [comment]
我也只是想听听项目组的意见。毕竟，客观准确的比较，确实没有。

**Comment by binarywang** [comment]
这个问题就不要纠结了，主要是历史问题，最早开始就用的gson，如果一开始用的fastjson，那也没问题，差别不大，该有的功能都能有。
