### ISSUE TITLE
springboot开发，微信服务器读取不到authGet返回的echostr的问题

### ISSUE THREAD

**Issue by musoon** [binarywang/WxJava#332]
用springboot开发，在微信公众账号后台配置服务器配置，get验证时，微信读取不到authGet方法返回的echostr。

 @GetMapping(produces = "text/plain;charset=utf-8")
 public String authGet(...) {
       //xxx
       //这个方式，微信服务器读取不了。在微信公众账号后台提交配置时一直提示“token验证失败”
       return echostr;
}

改为这样：
public void authGet(..., HttpServletResponse resp) {
      //xxx
      try {
            //这个方式就配置提交成功了。
            resp.getWriter().write(echostr);
      } catch (Exception e) {
            //xxx
      }
}

不知其他同学有无遇到这个问题？
怀疑是微信服务器不认return回去的这个response是它当前请求所产生的response？

**Comment by HikariShine** [comment]
请在方法或者类型上加上注解@ResponseBody注解
SpringMvc返回值如果没有@ResponseBody注解，会作为视图文件名解析，找不到对应视图会报错
加上@ResponseBody注解后，直接把返回的String最为响应返回给请求端。

**Comment by binarywang** [comment]
楼上说的很对，另外有专门的spring boot实现的demo，可以去参考。

**Comment by gaelthas** [comment]
这个解决方法有效
