### ISSUE TITLE
消息验重问题

### ISSUE THREAD

**Issue by zhouwei517** [binarywang/WxJava#333]
WxMpMessageRouter的isMsgDuplicated方法。使用msgId来验重是不正确的。这个msgId可能重复，会造成部分人员收不到回信（我们在测试的时候15个人一块语音，这个ID重复了，15个人一块喊语音，有5-6人收不到）。暂时的解决方案是加了FromUser和CreateTime。请官方关注一下。另外WxCpMessageRouter可能会有同样的问题。最后，感谢开源。

**Comment by binarywang** [comment]
看来真是个问题，需要修复下，感谢及时提出此问题

**Comment by imtiaotiao** [comment]
这个bug修复了吗？我看2.8.0里面用的还是msgId

**Comment by binarywang** [comment]
确实还没修复，因为这个问题是在2.8.0发布之后发现的

**Comment by binarywang** [comment]
测试版本2.8.7.BETA已修复
