### ISSUE TITLE
WxMpInRedisConfigStorage多线程复用jedis，导致异常

### ISSUE THREAD

**Issue by nickwongwong** [binarywang/WxJava#335]
https://github.com/Wechat-Group/weixin-java-tools/blob/2b019f15cb8116e63166aef8bc42e0c88dcf5f15/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/WxMpInRedisConfigStorage.java#L19-L24
https://github.com/Wechat-Group/weixin-java-tools/blob/2b019f15cb8116e63166aef8bc42e0c88dcf5f15/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/WxMpInRedisConfigStorage.java#L87-L89
jedis对象是非线程安全的，多次使用导致异常的出现
建议改写成jedisPool连接池的方式
晚点提个PR

**Comment by binarywang** [comment]
2.8.1.BETA版本已修复
