### ISSUE TITLE
WxMpServiceOkHttpImpl初始化报错，java.lang.NoClassDefFoundError: okhttp3/Authenticator

### ISSUE THREAD

**Issue by 1ibo** [binarywang/WxJava#337]
ERROR o.s.web.context.ContextLoader - Context initialization failed
java.lang.NoClassDefFoundError: okhttp3/Authenticator

**Comment by binarywang** [comment]
请注意阅读 https://github.com/Wechat-Group/weixin-java-tools/wiki/http%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%89%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by 1ibo** [comment]
好的，谢谢
