### ISSUE TITLE
2.8.0正式版，commons-lang3 版本问题

### ISSUE THREAD

**Issue by BruceMaa** [binarywang/WxJava#338]
### 目前解决方法

> 在项目parent中指定`commons-lang3`的版本号

```
<dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <version>3.5</version>
</dependency>
```

**Comment by binarywang** [comment]
没看明白，但按我的感觉，应该是版本号冲突问题，我们项目本身依赖的就是3.5版本。你自己项目自己处理下就可以了

**Comment by bysunexus** [comment]
在你的pom中强制指定一下commons-lang3的版本
`<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.5</version>
            </dependency>
        </dependencies>
    </dependencyManagement>`
或者找到冲突的依赖排除掉

**Comment by BruceMaa** [comment]
抱歉，找到了原因。
是我公司公共的`parent`中指定了`commons-lang3`的版本为`3.3.2`，所以我的项目必须要重新指定一下版本。
