### ISSUE TITLE
高并发情况下，获取AccessToken的问题

### ISSUE THREAD

**Issue by shijiuyan** [binarywang/WxJava#339]
在高并发情况下获取AccessToken时出现会出现大量的connectionpooltimeoutexception：Timeout waiting for connection from pool

**Comment by bysunexus** [comment]
如果用的 apache httpclient请参考下面的文章
https://github.com/wechat-group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95
适当修改连接池的配置参数  适当缩短超时时间,并加大连接数
