### ISSUE TITLE
将来是否会支持企业号会话功能

### ISSUE THREAD

**Issue by lottepie** [binarywang/WxJava#34]
现在好像不支持企业号会话功能吧，将来是否会支持企业号会话功能？

**Comment by binarywang** [comment]
@lottepie 如另一issue里所说，如果可以，希望你能够帮忙添加相关实现，感谢了

**Comment by binarywang** [comment]
#33 有关联

**Comment by binarywang** [comment]
接口文档地址：http://qydev.weixin.qq.com/wiki/index.php?title=%E4%BC%81%E4%B8%9A%E4%BC%9A%E8%AF%9D%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E

**Comment by binarywang** [comment]
经过查阅相关资料，得知企业会话功能已经关闭，企业微信中业务此功能。因此不会作支持。
```
微信企业号的企业会话和企业客服服务现已进行如下调整：

1.停止开启企业会话和企业客服服务，开启入口将于12月23日关闭，其它功能不受影响。企业号（注册主体为团队类型的除外）可以开启企业微信的会话服务；

2.已开启和已授权的企业使用不受影响，但关闭后将不能再次开启或授权；
 
3.可通过【企业微信】进行企业号消息的沟通，企业微信是专注企业内部沟通的独立APP。
时间: 2016年12月26日 作者: 桃花源 分类: 应用
```
参考地址如下：http://qydev.weixin.qq.com/qa/index.php?qa=29543&qa_1=%E4%B8%BA%E4%BD%95%E6%88%91%E7%9A%84%E6%9C%8D%E5%8A%A1%E4%B8%AD%E5%BF%83%E6%B2%A1%E6%9C%89%E4%BC%81%E4%B8%9A%E4%BC%9A%E8%AF%9D%EF%BC%9F
