### ISSUE TITLE
没有修改永久微信素材信息的接口吗

### ISSUE THREAD

**Issue by victorzhgx** [binarywang/WxJava#340]
还有就是在WxMaterialFileBatchGetNewsItem，get不到音频和视频的url，只有图片的

**Comment by binarywang** [comment]
谢谢提出问题，不过能否不同的问题分开issue提出呢？
这样便于针对性跟踪。
先回答标题上的问题，接口方法是这个：`me.chanjar.weixin.mp.api.WxMpMaterialService#materialNewsUpdate`

**Comment by binarywang** [comment]
正文里的问题：是因为视频和音频不提供url，仔细阅读下官方文档吧

**Comment by victorzhgx** [comment]
@binarywang 您好，十分抱歉，我第一次在这个上面提出问题，有些着急，没有注意规则，下次我会注意。十分感谢您的解答。me.chanjar.weixin.mp.api.WxMpMaterialService#materialNewsUpdate 我看这个接口是修改图文素材的，我的意思是修改图片、音频、视频的信息的接口，比如说修改他们的名称、标题、简介。这个接口也可以用吗？

**Comment by binarywang** [comment]
具体这个接口能干什么，建议你针对性的去看对应的微信官方文档，那里面都写得很清楚，能改什么，传什么参数。

**Comment by victorzhgx** [comment]
好的

**Comment by binarywang** [comment]
如果官方没有提供的接口我们也没办法生造一个出来。

**Comment by victorzhgx** [comment]
好的，多谢指导
