### ISSUE TITLE
WxMediaUploadResult  BUG

### ISSUE THREAD

**Issue by gggitpl** [binarywang/WxJava#341]
`WxMediaUploadResult

public String toString() {
     return ToStringBuilder.reflectionToString(this, ToStringStyle.JSON_STYLE);
}`

java.lang.NoSuchFieldError: JSON_STYLE

**Comment by binarywang** [comment]
是你的项目中类库冲突导致的，请使用不低于本sdk中声明的commons-lang3的版本，如果不知道如何做，先了解下maven的运行机制

**Comment by gggitpl** [comment]
谢谢

**Comment by binarywang** [comment]
下一步准备将这种代码移除替换掉，以免引起新手的误解
