### ISSUE TITLE
使用永久图片素材的mediaid创建图文，报错40007不合法的mediaid

### ISSUE THREAD

**Issue by victorzhgx** [binarywang/WxJava#346]
使用上传永久图片素材后返回的mediaid创建图文消息，却说mediaid不合法。我看官方文档上面说的是mediaid必须是永久素材的mediaid没错啊。me.chanjar.weixin.mp.api.materialFileUpload;调用的是这个接口。我把type改为thumb也不对，求大神指教

**Comment by binarywang** [comment]
网上有很多人遇到这个坑，你多试试他们提供的方案吧，太多了。

**Comment by victorzhgx** [comment]
有点说用临时mediaid，有的说用http://file.api.weixin.qq.com/cgi-bin/media/upload?access_token=ACCESS_TOKEN&type=TYPE这个接口，都试了 不好使

**Comment by binarywang** [comment]
楼主问题解决了吗？

**Comment by victorzhgx** [comment]
解决了

**Comment by EmanuelGi** [comment]
踩坑者留：material/xxx的请求都是针对永久素材，media/xxx的请求都是针对临时素材，两者不能混用。如果其他步骤都没问题，就确认一下自己是不是请求错了（比如说向永久素材的接口发送临时素材的mediaid来请求）
