### ISSUE TITLE
WxErrorException 能不能继承RuntimeException

### ISSUE THREAD

**Issue by zhihuihu** [binarywang/WxJava#347]
在业务代码中，抛出Excption这样异常，导致事物不回滚

如果要处理这个异常，会改比较多的代码

**Comment by binarywang** [comment]
这种异常本身设计时就要求调用者进行处理，因此改成Runtime的不合理。
至于你的问题，事务回滚本身也是可以控制的，哪种异常回滚，哪种不回滚，都是可以自定义添加的。

**Comment by zhihuihu** [comment]
但是只有继承RuntimeException的异常才能进行回滚，
我自己去捕获处理吧，本来想直接全局处理了的，感觉这个异常也是运行时的异常呀，调用接口失败，，感觉是Runtime的话后面处理更方便点

**Comment by binarywang** [comment]
你第一句话所说的只是spring的默认设置吧，并不是不能改的吧

**Comment by binarywang** [comment]
你如果非要这么纠结的话，可以自己把这个类抽出来改成继承RuntimeException，进行同名覆盖

**Comment by zhihuihu** [comment]
哈哈哈，这是不错的解决方案，先就自己抽出来了，

你封装的工具类让开发简单了太多了，感谢感谢，近期正准备重构微信这边代码，所以在做整体的规划

**Comment by bysunexus** [comment]
这个应该捕获之后转换为你们的业务异常再抛出
sdk并不关心具体的业务
而业务应该关心sdk的返回和异常

**Comment by zhihuihu** [comment]
嗯，已做处理，封装成自己的业务异常了，这样规范一点
