### ISSUE TITLE
miniapp高并发情况下非常严重的性能问题

### ISSUE THREAD

**Issue by axeon** [binarywang/WxJava#349]
cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl的executeInternal方法使用synchronized关键字导致极其严重的性能问题。
通过jmc观察，大并发下导致海量线程block在此处，造成非常严重的不可用。
建议去除synchronized关键字，同时优化getAccessToken(false)，尽量不要有锁，token可用后台进程维护。

**Comment by binarywang** [comment]
这个问题确实存在，mp模块就已经存在此问题，但是对于普通程序来说安全性更重要些，而你这种高并发的情况下也比较少见，需要考虑性能，可能需要自己单独做处理。
不知道你有什么好的修改建议，能够兼顾到两者，如果可以的话提交个PR吧

**Comment by axeon** [comment]
我们现在的做法是直接去掉synchronized关键字了，但是不太明白加synchronized的用意在哪里？
这样去掉之后会有什么潜在问题？

**Comment by binarywang** [comment]
主要原因应该是为了解决当token过期的那个时刻如果同时有多个线程请求会导致获取token的接口被大量调用，从而导致接口次数超限的问题

**Comment by axeon** [comment]
getToken已经加锁了，没有必要在executeInternal方法上再加同步。
另外，建议用户自行实现服务刷token，这样把getToken里的锁也给去掉

**Comment by binarywang** [comment]
为了安全起见，你先本地修改测试下看看有没有其他问题吧，如果没问题你再把代码提交上来吧，非常感谢

**Comment by binarywang** [comment]
#384
