### ISSUE TITLE
建议添加网站第三方登录接口qrconnect

### ISSUE THREAD

**Issue by yelochick** [binarywang/WxJava#35]
原有的oauth2buildAuthorizationUrl生成的https://open.weixin.qq.com/connect/oauth2/authorize，只能在微信端打开，浏览器是打不开的。建议添加一接口生成https://open.weixin.qq.com/connect/qrconnect的Url。

**Comment by binarywang** [comment]
请提供文档地址，方便实现者设计接口，当然如果楼主能够帮忙实现，就更好了

**Comment by yelochick** [comment]
文档地址：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN

**Comment by binarywang** [comment]
@fk75768893  接口已添加，请使用2.1.1版本进行测试使用，具体用法，参考相关javadoc以及单元测试方法：me.chanjar.weixin.mp.api.impl.WxMpServiceImplTest.testBuildQrConnectUrl()

**Comment by yelochick** [comment]
感谢
