### ISSUE TITLE
退款通知回调时，wxService.parseRefundNotifyResult抛出Illegal key size or default parameters异常

### ISSUE THREAD

**Issue by tenonersoft** [binarywang/WxJava#357]
退款通知回调时，wxService.parseRefundNotifyResult抛出Illegal key size or default parameters异常
具体为 cipher.init(Cipher.DECRYPT_MODE, key);时报错
/**

从xml字符串创建bean对象

@Param xmlString xml字符串

@Param mchKey 商户密钥
*/
public static WxPayRefundNotifyResult fromXML(String xmlString, String mchKey) throws WxPayException {
WxPayRefundNotifyResult result = WxPayBaseResult.fromXML(xmlString, WxPayRefundNotifyResult.class);
String reqInfoString = result.getReqInfoString();
try {
Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");

final MessageDigest md5 = MessageDigest.getInstance("MD5");
md5.update(mchKey.getBytes());
final String keyMd5String = new BigInteger(1, md5.digest()).toString(16).toLowerCase();
SecretKeySpec key = new SecretKeySpec(keyMd5String.getBytes(), "AES");
cipher.init(Cipher.DECRYPT_MODE, key);//这一句出错
result.setReqInfo(ReqInfo.fromXML(new String(cipher.doFinal(Base64.decodeBase64(reqInfoString)))));
} catch (Exception e) {
throw new WxPayException("解密退款通知加密信息时出错", e);
}

return result;
}
使用的2.8.3.BETA版本

**Comment by binarywang** [comment]
请参考下常见问题区的问题：https://github.com/Wechat-Group/weixin-java-tools/wiki

**Comment by bysunexus** [comment]
给你的jdk 打jce补丁

**Comment by tenonersoft** [comment]
感谢，刚刚找到了解决方法，之前没注意到常见问题区里有这个，具体是这个问题：
因为某些国家的进口管制限制，Java发布的运行环境包中的加解密有一定的限制。比如默认不允许256位密钥的AES加解密，解决方法就是修改策略文件。
 
 官方网站提供了JCE无限制权限策略文件的下载：

  JDK6的下载地址：
  http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html

  JDK7的下载地址：
  http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

  JDK8的下载地址：
  http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

在相应的jdk或jre目录下的lib/security目录下覆盖原来的文件
