### ISSUE TITLE
微信网页授权为snsapi_userinfo时，WxMpUser类中缺失字段：privilege

### ISSUE THREAD

**Issue by xieyushi** [binarywang/WxJava#358]
微信网页授权为snsapi_userinfo时，WxMpUser类中缺失字段：privilege
该字段为用户特权信息，是json 数组格式，如微信沃卡用户为（chinaunicom）
但是目前我没有用到这个特权信息的东西。所以不太清楚这个json数组的格式，期待大神进一步的完善。

**Comment by binarywang** [comment]
感谢提出此疑问，
看了下官方文档 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842 里的描述，格式如下：
```
"privilege":[ "PRIVILEGE1" "PRIVILEGE2"     ],  
```
但这个格式都貌似写错了，而且好像支持的意义不大，不是特别紧急的问题，以后有机会再做个支持了

**Comment by binarywang** [comment]
2.9.2.BETA版本已添加
