### ISSUE TITLE
小程序请求有时会出现 Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by ghs0223** [binarywang/WxJava#359]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at com.google.gson.Gson.fromJson(Gson.java:773)
	at cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:23)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:41)

**Comment by binarywang** [comment]
看起来像是json格式有问题，调试看看微信请求返回内容是什么

**Comment by ghs0223** [comment]
![image](https://user-images.githubusercontent.com/12592014/32164777-76721e98-bd9b-11e7-8a18-1530cccc8f49.png)  如果不报错，返回的数据是正常的。如果报错，无法调试返回的字符串啊！
这是解密出的问题吗？
难道是小程序的session_key生成了新的，旧的会无效？然而新的session_key 解密也报错啊。想不通。。。

**Comment by binarywang** [comment]
确实是很奇葩的问题

**Comment by binarywang** [comment]
不知道你是什么情况下导致报错的？

**Comment by binarywang** [comment]
没有进一步沟通，暂时关闭

**Comment by jinriyang** [comment]
我也遇到这个问题了，是WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr)这个方法返回值是乱码，传入的参数没问题
![wechatimg47](https://user-images.githubusercontent.com/28684043/38724125-d32b363a-3f35-11e8-8629-edb5aba23e21.jpeg)

![1523606661417](https://user-images.githubusercontent.com/28684043/38724151-e9cb4fa6-3f35-11e8-96e0-8c643e921668.jpg)

**Comment by jinriyang** [comment]
@binarywang

**Comment by Tigerioo** [comment]
刚才也遇到这个问题, 手机解密的时候JSON解析失败.
```
is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $] with root cause

java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.2.jar!/:na]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[gson-2.8.2.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:888) ~[gson-2.8.2.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:853) ~[gson-2.8.2.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:802) ~[gson-2.8.2.jar!/:na]
        at com.google.gson.Gson.fromJson(Gson.java:774) ~[gson-2.8.2.jar!/:na]
        at cn.binarywang.wx.miniapp.bean.WxMaPhoneNumberInfo.fromJson(WxMaPhoneNumberInfo.java:22) ~[weixin-java-miniapp-3.0.0.jar!/:na]
```

**Comment by guoyangyang** [comment]
手机解密时也遇到了同样的问题

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:888) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:853) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:802) ~[gson-2.8.2.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:774) ~[gson-2.8.2.jar:na]
	at cn.binarywang.wx.miniapp.bean.WxMaPhoneNumberInfo.fromJson(WxMaPhoneNumberInfo.java:22) ~[weixin-java-miniapp-3.0.0.jar:na]
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getPhoneNoInfo(WxMaUserServiceImpl.java:35) ~[weixin-java-miniapp-3.0.0.jar:na]

**Comment by yiyi910** [comment]
不会看wiki？？？
https://github.com/Wechat-Group/weixin-java-tools/wiki/%E5%8A%A0%E8%A7%A3%E5%AF%86%E7%9A%84%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E5%8A%9E%E6%B3%95



yiyi910
 
发件人： Yang
发送时间： 2018-04-19 13:51
收件人： Wechat-Group/weixin-java-tools
抄送： Subscribed
主题： Re: [Wechat-Group/weixin-java-tools] 小程序解密用户信息是，经常会出现com.google.gson.JsonSyntaxException: java.lang.IllegalStateException (#359)
手机解密时也遇到了同样的问题
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $ at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.2.jar:na] at com.google.gson.Gson.fromJson(Gson.java:888) ~[gson-2.8.2.jar:na] at com.google.gson.Gson.fromJson(Gson.java:853) ~[gson-2.8.2.jar:na] at com.google.gson.Gson.fromJson(Gson.java:802) ~[gson-2.8.2.jar:na] at com.google.gson.Gson.fromJson(Gson.java:774) ~[gson-2.8.2.jar:na] at cn.binarywang.wx.miniapp.bean.WxMaPhoneNumberInfo.fromJson(WxMaPhoneNumberInfo.java:22) ~[weixin-java-miniapp-3.0.0.jar:na] at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getPhoneNoInfo(WxMaUserServiceImpl.java:35) ~[weixin-java-miniapp-3.0.0.jar:na]

**Comment by guoyangyang** [comment]
@yiyi910 

感谢您的回复。
首先您分享的wiki标题和我遇到的问题并不相同。
第二即使按照您分享的方法依然没有解决我目前遇到的问题。

**Comment by binarywang** [comment]
这个issue已经关闭了，如果确实遇到无法解决的问题，请尽量新开issue讨论吧，谢谢各位了

**Comment by binarywang** [comment]
鉴于这可能确实是个问题，暂时打开，有空再研究下

**Comment by binarywang** [comment]
https://www.cnblogs.com/guansixu/articles/6484872.html 楼上遇到问题的各位请参考此文，不知是否有帮助

**Comment by guoyangyang** [comment]
@binarywang 感谢回复。我这边遇到的问题和你分享的文章相似。

回头翻了一下小程序开发手册，发现开发过程中忽略了下面这段注意事项。
![getphonenumber](https://user-images.githubusercontent.com/6446776/39290510-652140ee-4962-11e8-8ef8-a222a7686471.png)

修改了调用wx.login顺序后，问题解决。

**Comment by binarywang** [comment]
好像很多人遇到这个问题，先打开，便于新来的人看到

**Comment by zmber** [comment]
没看到有效信息

**Comment by binarywang** [comment]
其他人看了后都解决，难道你的问题比较特殊，或者不是同一个问题？

**Comment by 7400108** [comment]
我是用你的WxMaCryptUtils.decrypt(String sessionKey, String encryptedData, String ivStr) 来解密群id的 偶尔一次出现乱码不知道是什么问题 打印sessionKey没有问题  求大神解决

**Comment by hyede** [comment]
我这边也是WxMaCryptUtils.decrypt(String sessionKey, String encryptedData, String ivStr) 来解密用户信息时的 偶尔一次出现乱码不知道是什么问题 ？

**Comment by binarywang** [comment]
仔细看下上面提到的解决办法，确实无用吗？

**Comment by hyede** [comment]
你上面是有提到2点 1. "由于wx.getUserInfo()返回值中encryptData和encryptedData参数名称过于相似，导致我用错变量，"  可是前端说 他确实调用的encryptedData 参数 。2  调用wx.login顺序后 这个前端也说 是有先调用login 后面再去请示解密  我也看了  确实按顺序调用  。。 但是后面还是偶尔会出现 ，所以现在还是没搞懂问题出现在哪

**Comment by binbinmm** [comment]
我也是遇到同样的问题  偶尔会出现

**Comment by wanjun123** [comment]
WxMaCryptUtils.decrypt解密后乱码    导致 gson转换失败，没看到解决方案啊

**Comment by gongshsh** [comment]
Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ 怎么解决的？

**Comment by cainiao00x** [comment]
> @binarywang 感谢回复。我这边遇到的问题和你分享的文章相似。
> 
> 回头翻了一下小程序开发手册，发现开发过程中忽略了下面这段注意事项。
> ![getphonenumber](https://user-images.githubusercontent.com/6446776/39290510-652140ee-4962-11e8-8ef8-a222a7686471.png)
> 
> 修改了调用wx.login顺序后，问题解决。

我的应该就是这个问题，谢谢

**Comment by syzpig** [comment]
请问您解决了吗

**Comment by binarywang** [comment]
> 请问您解决了吗

你在问谁？
请先阅读上面的解决办法，然后确实解决不了，并且不是同一个问题的话，请新开issue，说清楚你的问题

**Comment by dddd-dot** [comment]
> 请问您解决了吗

我今天也遇到了，后来改成先login，再js获取getUserInfo，就可以了。叫前端改改这块的逻辑试试
```
bindGetUserInfo: function (e) {
    var that = this
        wx.login({
          success: function (json) {
            var code = json.code;
            wx.getUserInfo({
              success: function (res) {
                var arr = JSON.parse(res.rawData)
                var nickname = arr.nickName
                wx.request({
                  url: "http:/xxx/api/account/login",
                  method: "POST",
                  data: {
                    code: code,
                    encryptedData: res.encryptedData,
                    ivStr: res.iv
                  },
                  header: {
                    "Content-Type": "application/x-www-form-urlencoded"
                  },
                  success: function (json) {
                    console.log('json ', json.data)
                    wx.showToast({
                      title: json.data.msg,
                    })
                  },
                  fail: function (err) {
                    console.log(err)
                  }
              })
          }
        })
      }
    })
  },
```

**Comment by 892499216** [comment]
我使用自己注册的开发者账号获取userInfo时是正常的,但是使用公司的账号解密userInfo就是乱码,是全部都是乱码

**Comment by hackeryutu** [comment]
> 我使用自己注册的开发者账号获取userInfo时是正常的,但是使用公司的账号解密userInfo就是乱码,是全部都是乱码

一样。

没有刷新用户态过也会乱码。

**Comment by 94zhaoyueran** [comment]
![图片](https://user-images.githubusercontent.com/29116990/63904926-22635480-ca45-11e9-8039-9fa558c11c1c.png)

我也是偶尔遇到这样得问题，不是必发生。所以狠难却准定位。
和前端确认了 encryptData和encryptedData参数名称过于相似 和 调用wx.login顺序。都正常

**Comment by aabbccaaa** [comment]
我们也需要了相同的问题，问题解决是因为小程序的session_key 失效导致无法解密出jason字串。解决的办法是每次走手机号授权和微信资料授权时，小程序段先请求login，把code拿到同一个接口里去解密出最新的session_key。这样处理了以后。就没再遇到相同的问题了。

**Comment by weiqilong** [comment]
WxMaCryptUtils里面的解密用的时AES/CBC/NoPadding，但是官方文档要求的是“对称解密使用的算法为 AES-128-CBC，数据采用PKCS#7填充”，所以我遇到了解密出来的东西乱码

**Comment by weiqilong** [comment]
微信官方文档要求PKCS#7解密，但是WxMaCryptUtils里面的解密用的是AES/CBC/NoPadding

**Comment by weiqilong** [comment]
问题解决了，前端需要先判断一下session是否过期，如果过期就login，然后获取code，就不会出现乱码了

**Comment by korawudev** [comment]
解密手机号的时候，遇到了相同的问题，原因是用固定的 session_key + encryptedData+ iv 解密，但是encryptedData 或者 iv 可能是一次性的，解密完之后就不能再用了

**Comment by spiritelf** [comment]
getPhoneNumber(e){//微信授权手机号登陆
    let that=this;
    let token = wx.getStorageSync('token');
    let code=null;
    wx.showLoading({
      title: '加载中',
    })
    if (token) {
      that.setFid()
      return false;
    }else{

      util.login().then((res) => {
        code = res.code;
        
        if (e.detail.encryptedData) {
          //用户按了允许授权按钮
          user.loginByWeixinMobile(e.detail,code).then(res => {
            let userInfo = wx.getStorageSync('userInfo');
            that.setData({
              userInfo: userInfo.userInfo
            });
            app.globalData.userInfo = userInfo.userInfo;
            app.globalData.token = res.data.openid;
            that.setFid()
          }).catch((err) => {
            console.log(err)
          });
        } else {
          
        }
        
      })

      
    } 
  }











/**
 * 
 * 获取微信手机号授权登陆
 */
function loginByWeixinMobile(userData,code) {
  //let code = null;
  return new Promise(function (resolve, reject) {
    //登录远程服务器
    let params={};
    params.code=code;
    params.encryptedData = userData.encryptedData;
    params.iv = userData.iv;
    util.request(api.AuthLoginByWeixinMobile, params, 'POST').then(res => {
      if (res.errno === 0) { 
        //存储用户信息
        wx.setStorageSync('userInfo', res.data.userVo);
        wx.setStorageSync('token', res.data.token);
        wx.setStorageSync('isReal', res.data.userVo.isReal); 
        wx.setStorageSync('uId', res.data.userVo.userId); 
        if (wx.getStorageSync('userId')){
          wx.removeStorageSync('userId'); 
        }  
        resolve(res);
      } else {
        util.showErrorToast(res.errmsg)
        reject(res); 
      }
    }).catch((err) => {
      reject(err);
    });
  });
}



页面不操作，等待几分钟，点击登录获取手机号就会出现以上错误。


还是说点 微信手机号授权按钮之前就要调用wx.login???

**Comment by luzhaoren** [comment]
确认下前后端传递的参数有没有做UrlEncode/UrlDecode，因为encryptedData里会包含特殊字符在传递参数时被转义，可能服务器端实际拿到的参数encryptedData并不是前端实际获取到的值，导致SDK调用微信相应接口时无法解密而报错，只要保证前端实际获取到的encryptedData和服务器端调用SDK时传入的encryptedData一致就不会报错的，SDK中方法并无问题；建议让前后台都打印下日志，看下服务端最终使用的参数值是否还是前端获取到的原始值呢。

重要：有朋友反映按照以上描述处理后还是会偶尔出现这个解密问题，那么可能就是前后端没有协同好了，忽略了每次调用wx.login时微信都会刷新sessionkey，可能造成后台使用了旧的/过期的sessionkey去解密而失败，一般开发小程序时有一个原则，前端只要调用wx.login就必须通知后台使用最新的code刷新sessionkey！所以正确的做法应该是：
1. 前端调用wx.checkSession，检查session是否过期
2. 如果session过期，则前端调用wx.login并通知后台使用auth.code2Session刷新sessionkey
3. 前端调用wx.getShareInfo，获取微信返回的encryptedData和iv
4. 前端调用后台接口，后台使用encryptedData解密用户信息

PS：wx.request对GET/POST传递字符串参数时会自动做encodeURIComponent，SpringBoot某些场景下form表单参数是会自动做UrlDecode的...

![注意事项官方说明](https://user-images.githubusercontent.com/13306598/87409602-bd323680-c5f7-11ea-8242-d9e562d871f5.png)
![](https://user-images.githubusercontent.com/13306598/87410135-7ee94700-c5f8-11ea-957a-27a4bcb5a4ac.png)

[wx.request官方API文档](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html)
[获取用户信息](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/user-info/wx.getUserInfo.html)
[获取用户手机号码](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)
[服务端解密开放数据](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/signature.html#%E5%8A%A0%E5%AF%86%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%AF%86%E7%AE%97%E6%B3%95)

**Comment by makehkx** [comment]
> 确认下前后端传递的参数有没有做UrlEncode/UrlDecode，因为encryptedData里会包含特殊字符在传递参数时被转义，可能服务器端实际拿到的参数encryptedData并不是前端实际获取到的值，导致SDK调用微信相应接口时无法解密而报错，只要保证前端实际获取到的encryptedData和服务器端调用SDK时传入的encryptedData一致就不会报错的，SDK中方法并无问题；建议让前后台都打印下日志，看下服务端最终使用的参数值是否还是前端获取到的原始值呢。PS：SpringBoot某些场景下form表单参数是会自动做UrlDecode的...

多谢大佬，就是特殊字符被转义了

**Comment by 93Laer** [comment]
> > 确认下前后端传递的参数有没有做UrlEncode/UrlDecode，因为encryptedData里会包含特殊字符在传递参数时被转义，可能服务器端实际拿到的参数encryptedData并不是前端实际获取到的值，导致SDK调用微信相应接口时无法解密而报错，只要保证前端实际获取到的encryptedData和服务器端调用SDK时传入的encryptedData一致就不会报错的，SDK中方法并无问题；建议让前后台都打印下日志，看下服务端最终使用的参数值是否还是前端获取到的原始值呢。PS：SpringBoot某些场景下form表单参数是会自动做UrlDecode的...
> 
> 多谢大佬，就是特殊字符被转义了

多谢大佬，我懂了

**Comment by SwpuEsine** [comment]
> wx

我也遇到了你的问题,是因为时间戳他定义的是字符串,但是小程序返回的是long的时间戳,这样逆向解析就报错了,里面用个gson这个框架 不支持这样转换.偶尔就会报错

**Comment by binarywang** [comment]
> > wx
> 
> 我也遇到了你的问题,是因为时间戳他定义的是字符串,但是小程序返回的是long的时间戳,这样逆向解析就报错了,里面用个gson这个框架 不支持这样转换.偶尔就会报错

你的问题跟楼上的都不一样，请单独提出，或者你觉得代码有问题，可以直接提PR

**Comment by qmdx** [comment]
提醒！！ 默认 demo 比较坑人使用 get 方法，会出现楼上说的 url 编码导致不可用问题，使用 post 方法问题解决

**Comment by binarywang** [comment]
> 提醒！！ 默认 demo 比较坑人使用 get 方法，会出现楼上说的 url 编码导致不可用问题，使用 post 方法问题解决

默认demo是指啥？

**Comment by longzhiwuing** [comment]
调用方式如下：
String decryptInfo = WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr);
WxMaPhoneNumberInfo wxMaPhoneNumberInfo = WxMaPhoneNumberInfo.fromJson(decryptInfo);

报错信息：
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: invalid number or unquoted string near v�v�6�6t7�%��1�u
>A��V��G��I��Ӷ�ǟ
	at com.google.gson.Streams.parse(Streams.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:514)
	at com.google.gson.Gson.fromJson(Gson.java:484)
	at com.google.gson.Gson.fromJson(Gson.java:434)
	at com.google.gson.Gson.fromJson(Gson.java:406)


感觉问题跟这个很相似，但是问题错误提示却不太一样，也是调用WxMaCryptUtils.decrypt后，返回的json字符串是乱码，导致反序列化对象的时候报错。但提示的是“invalid number or unquoted string near...”好像又和你们提示的信息不太一样，有人遇到过么

**Comment by RmanzzZ** [comment]
> 调用方式如下：
> String decryptInfo = WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr);
> WxMaPhoneNumberInfo wxMaPhoneNumberInfo = WxMaPhoneNumberInfo.fromJson(decryptInfo);
> 
> 报错信息：
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: invalid number or unquoted string near �v�v��6��6t7�%��1��u
> 
> > A���V��G��I���Ӷ�ǟ�
> > at com.google.gson.Streams.parse(Streams.java:51)
> > at com.google.gson.Gson.fromJson(Gson.java:514)
> > at com.google.gson.Gson.fromJson(Gson.java:484)
> > at com.google.gson.Gson.fromJson(Gson.java:434)
> > at com.google.gson.Gson.fromJson(Gson.java:406)
> 
> 感觉问题跟这个很相似，但是问题错误提示却不太一样，也是调用WxMaCryptUtils.decrypt后，返回的json字符串是乱码，导致反序列化对象的时候报错。但提示的是“invalid number or unquoted string near...”好像又和你们提示的信息不太一样，有人遇到过么

同样问题 求助 请问解决了吗 wx: rmanzzz 酬谢

**Comment by tianyahaijiaowxp** [comment]
怎么这个问题感觉都没有特别明确的回答啊
下面代码报错
WxMaPhoneNumberInfo phoneNoInfo = this.wxMaService.getUserService().getPhoneNoInfo(session.getSessionKey(), encryptedData, iv);
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

都没有个实质的回答

**Comment by RmanzzZ** [comment]
> 怎么这个问题感觉都没有特别明确的回答啊
> 下面代码报错
> WxMaPhoneNumberInfo phoneNoInfo = this.wxMaService.getUserService().getPhoneNoInfo(session.getSessionKey(), encryptedData, iv);
> java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 
> 都没有个实质的回答

已解决 还是顺序的问题
![image](https://user-images.githubusercontent.com/57282996/98883762-b5ad6c00-24c9-11eb-9ef8-baaf49ca2f0a.png)

**Comment by jiaoqianjin** [comment]
> 我也遇到这个问题了，是WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr)这个方法返回值是乱码，传入的参数没问题
> ![wechatimg47](https://user-images.githubusercontent.com/28684043/38724125-d32b363a-3f35-11e8-8629-edb5aba23e21.jpeg)
> 
> ![1523606661417](https://user-images.githubusercontent.com/28684043/38724151-e9cb4fa6-3f35-11e8-96e0-8c643e921668.jpg)
您好，请问这个问题您当时是怎么解决的，我现在也遇到了传入参数没问题，返回参数乱码

**Comment by weiqilong** [comment]
原因是前端的authcode码失效了
---原始邮件---
发件人:&quot;jiaoqianjin&quot;<notifications@github.com&gt;
发送时间:2021年1月30日 星期六 上午11:43
收件人:&quot;Wechat-Group/WxJava&quot;<WxJava@noreply.github.com&gt;
抄送:&quot;小熊羔子&quot;<398581645@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;
主题:Re: [Wechat-Group/WxJava] 小程序请求有时会出现 Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $ (#359)



我也遇到这个问题了，是WxMaCryptUtils.decrypt(sessionKey,&nbsp;encryptedData,&nbsp;ivStr)这个方法返回值是乱码，传入的参数没问题



您好，请问这个问题您当时是怎么解决的，我现在也遇到了传入参数没问题，返回参数乱码

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by sav7ng** [comment]
@weiqilong 可以爬一下楼，问题解决方案都在上面，可以一步一步排查。

**Comment by KaimingLuo** [comment]
> 确认下前后端传递的参数有没有做UrlEncode/UrlDecode，因为encryptedData里会包含特殊字符在传递参数时被转义，可能服务器端实际拿到的参数encryptedData并不是前端实际获取到的值，导致SDK调用微信相应接口时无法解密而报错，只要保证前端实际获取到的encryptedData和服务器端调用SDK时传入的encryptedData一致就不会报错的，SDK中方法并无问题；建议让前后台都打印下日志，看下服务端最终使用的参数值是否还是前端获取到的原始值呢。
> 
> 重要：有朋友反映按照以上描述处理后还是会偶尔出现这个解密问题，那么可能就是前后端没有协同好了，忽略了每次调用wx.login时微信都会刷新sessionkey，可能造成后台使用了旧的/过期的sessionkey去解密而失败，一般开发小程序时有一个原则，前端只要调用wx.login就必须通知后台使用最新的code刷新sessionkey！所以正确的做法应该是：
> 
> 1. 前端调用wx.checkSession，检查session是否过期
> 2. 如果session过期，则前端调用wx.login并通知后台使用auth.code2Session刷新sessionkey
> 3. 前端调用wx.getShareInfo，获取微信返回的encryptedData和iv
> 4. 前端调用后台接口，后台使用encryptedData解密用户信息
> 
> PS：wx.request对GET/POST传递字符串参数时会自动做encodeURIComponent，SpringBoot某些场景下form表单参数是会自动做UrlDecode的...
> 
> ![注意事项官方说明](https://user-images.githubusercontent.com/13306598/87409602-bd323680-c5f7-11ea-8242-d9e562d871f5.png)
> ![](https://user-images.githubusercontent.com/13306598/87410135-7ee94700-c5f8-11ea-957a-27a4bcb5a4ac.png)
> 
> [wx.request官方API文档](https://developers.weixin.qq.com/miniprogram/dev/api/network/request/wx.request.html)
> [获取用户信息](https://developers.weixin.qq.com/miniprogram/dev/api/open-api/user-info/wx.getUserInfo.html)
> [获取用户手机号码](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)
> [服务端解密开放数据](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/signature.html#%E5%8A%A0%E5%AF%86%E6%95%B0%E6%8D%AE%E8%A7%A3%E5%AF%86%E7%AE%97%E6%B3%95)

我也遇到偶尔解密失败的问题，看完大佬们的回答，调查后发现是顺序问题。前端先调用了getUserInfo，再调用wx.login，拿着旧的加密信息和新的session去解密了。。
不过，现在直接从session中拿openid、unionid，用户信息用getUserProfile拿明文，不用再去解密了0.0？

**Comment by HeyChiang** [comment]
> 解密手机号的时候，遇到了相同的问题，原因是用固定的 session_key + encryptedData+ iv 解密，但是encryptedData 或者 iv 可能是一次性的，解密完之后就不能再用了

我亲自测试了， session_key + encryptedData+ iv 可以重复使用postman拿到手机号码，并不是你说的一次性。

**Comment by lailiangfeng** [comment]
![image](https://user-images.githubusercontent.com/35624280/130049146-7ce2b172-aa3c-408a-874a-36d6d3dbe32d.png)

**Comment by q127981** [comment]
![image](https://user-images.githubusercontent.com/31874319/139566338-1478e260-035b-4ee8-8e28-039d2eb66088.png)
简单粗暴的一个解决方法，既然拿到的sessionKey是过期的，那么就再拿一次

**Comment by IllusionOops** [comment]
前端获取到用户手机号信息，然后打印，接着使用postman调用后端接口，由后端进行用户手机号信息解密。   
偶尔会出现这种情况：成功、失败交替进行；大部分情况：多次失败，偶尔成功。      
这个错误到底是什么原因？      
我现在是测试阶段，仅仅通过前端打印数据，然后通过postman发起post请求进行接口调用，完全不存在前端重复调用登录接口导致sessionkey失效问题，也没有调用其他接口。 
当出现失败报错的时候，我使用文本对比工具对比过前端打印的数据和后端打印的数据，完全一致！！！

每个人的回答我都看了，但是依然没懂这个错误到底是什么原因···能否告知下

**Comment by liuguofeng-java** [comment]
打卡,也遇到这个问题

**Comment by liuguofeng-java** [comment]
找到问题了先调用login在调用getphonenumber

![image](https://user-images.githubusercontent.com/59218624/151666346-ffbd2167-6b74-4a2d-933a-b32546ec91bb.png)

**Comment by longtimeGo** [comment]
我这边遇到了线下可以获取到用户信息，到线上就报错，错误信息提示中如下列：

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
        at com.google.gson.Gson.fromJson(Gson.java:888)
        at com.google.gson.Gson.fromJson(Gson.java:853)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at com.google.gson.Gson.fromJson(Gson.java:774)
        at cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:29)
        at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:38)

代码层面：(getPhoneNoInfo不报错，getUserInfo会报上述的错)
wxPhoneInfo = wxMaService.getUserService().getPhoneNoInfo(sessionKey, request.getMobileEncryptedData(), request.getMobileIvStr());
wxUserInfo = wxMaService.getUserService().getUserInfo(sessionKey, request.getUserInfoEncryptedData(), request.getUserInfoIvStr());

**Comment by wgsdiv** [comment]
> 一次

code只能使用一次吧

**Comment by wgsdiv** [comment]
> ![image](https://user-images.githubusercontent.com/31874319/139566338-1478e260-035b-4ee8-8e28-039d2eb66088.png) 简单粗暴的一个解决方法，既然拿到的sessionKey是过期的，那么就再拿一次

code只能使用一次吧
