### ISSUE TITLE
java.text.SimpleDateFormat 线程安全问题

### ISSUE THREAD

**Issue by xuyang2** [binarywang/WxJava#36]
java.text.SimpleDateFormat 内部是有状态的，并非线程安全。

[SimpleDateFormat javadoc](http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html)

> ## Synchronization
> 
> Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.

org.apache.commons.lang3.time.FastDateFormat 才是线程安全的。

[FastDateFormat javadoc](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/FastDateFormat.html)

> FastDateFormat is a fast and thread-safe version of SimpleDateFormat.
> Since FastDateFormat is thread safe, you can use a static member instance:
> `private static final FastDateFormat DATE_FORMATTER = FastDateFormat.getDateTimeInstance(FastDateFormat.LONG, FastDateFormat.SHORT);`
> This class can be used as a direct replacement to SimpleDateFormat in most formatting and parsing situations. This class is especially useful in multi-threaded server environments. SimpleDateFormat is not thread-safe in any JDK version, nor will it be as Sun have closed the bug/RFE.

**Comment by binarywang** [comment]
没太明白，你发这个是想指出哪部分代码已经有潜在的问题了么？

**Comment by xuyang2** [comment]
这里有线程安全问题：

```
/**
 * 微信API的Service
 */
public interface WxMpService {

  SimpleDateFormat SIMPLE_DATE_FORMAT = new SimpleDateFormat("yyyy-MM-dd");
```

**Comment by binarywang** [comment]
我仔细考虑下了，这个地方确实是可能有问题的，因为是静态共享的，所以才可能在多线程高并发环境下，使用其parse或format方法时有线程问题

**Comment by binarywang** [comment]
感谢提出这个问题，我们将彻查代码，修复可能有问题的地方

**Comment by binarywang** [comment]
已修复，代码提交到develop分支
