### ISSUE TITLE
WxPayService.createOrder在使用jsapi类型时会签名错误

### ISSUE THREAD

**Issue by wensimin** [binarywang/WxJava#360]
签名时使用WxPayMpOrderResult对象作为签名参数，调用BeanUtils.xmlBean2Map后会生成空Map导致签名错误

**Comment by binarywang** [comment]
请使用最新测试版本，此问题已修复

**Comment by gtyang** [comment]
我用了 2.9.4.BETA，还是会出现签名错误的问题

**Comment by binarywang** [comment]
你这么说很笼统，建议自己调试下看看到底是什么问题导致的
