### ISSUE TITLE
okhttp实现的二维码下载代码有问题

### ISSUE THREAD

**Issue by javadevelopuser** [binarywang/WxJava#362]
参考链接样例：https://github.com/Wechat-Group/weixin-java-tools/wiki/MP_%E4%BA%8C%E7%BB%B4%E7%A0%81%E7%AE%A1%E7%90%86
和WxMpQrCodeServiceImplTest测试类进行试运行，不能正常生成二维码图片，而且图片格式和wiki说明也不一致。

**Comment by binarywang** [comment]
那个图片是临时文件，你调用方法后需要自己再保存一份，程序退出后会删除掉的，你也不能指望使用临时文件夹里的文件吧？

**Comment by javadevelopuser** [comment]
我有测试移动到其他文件夹，发现复制过去的是一个0大小的文件。

**Comment by binarywang** [comment]
经过测试，发现单元测试目前用的是okhttp的实现，代码有问题，而实际默认使用的apache httpclient 不存在此问题，okhttp的实现稍后修复下。

**Comment by javadevelopuser** [comment]
非常感谢！

**Comment by binarywang** [comment]
2.8.6.BETA已修复
