### ISSUE TITLE
WxMpInRedisConfigStorage 注入jedis 问题

### ISSUE THREAD

**Issue by Daily1116** [binarywang/WxJava#364]
在spring boot 中，我创建Jedis代码如下：
    @Bean
    public JedisPool jedisPool(){
        JedisPoolConfig config = new JedisPoolConfig();
        config.setMaxTotal(redisProperties.getMaxactive());
        config.setMaxIdle(redisProperties.getMaxidle());
        config.setMinIdle(redisProperties.getMinidle());
        config.setMaxWaitMillis(redisProperties.getMaxwait());
        return new JedisPool(config, redisProperties.getIp(), redisProperties.getPort(), redisProperties.getTimeout(), redisProperties.getPassword());
    }

    @Bean
    public Jedis getJedis(){
        return jedisPool().getResource();
    }
然后将这个Jedis注入WxMpInRedisConfigStorage 中，使用一段时间会报错redis.clients.jedis.exceptions.JedisConnectionException: Unexpected end of stream.怀疑是jedis使用了没有归还，这里建议注入StringRedisTemplate，这个使用了会自动释放链接的。
作者给个方案呗

**Comment by 007gzs** [comment]
@Autowired
JedisPool jedisPool;

    @Override
    public synchronized void updateAccessToken(String accessToken, int expiresInSeconds) {
        try(Jedis jedis = jedisPool.getResource()){
            jedis.setex(ACCESS_TOKEN_KEY.concat(appId), expiresInSeconds - 200, accessToken);
        }
    }

**Comment by Daily1116** [comment]
@007gzs
 也是要改源码的，源码只有Jedis变量，我已经改源码注入StringRedisTemplate这个了

**Comment by binarywang** [comment]
这个redis的实现本来就只是个参考，你们应该自己去实现符合自己实际需求的实现。当然如果你们觉得你们的代码对其他人也会有帮助，欢迎在原有代码基础上进行改造，然后贡献出来～

**Comment by binarywang** [comment]
还有你说的那个template类是属于依赖具体框架即spring的东西，不适合集成在我们的SDK中，如果可以把你的代码贡献一份到Demo中吧

**Comment by 007gzs** [comment]
我是自己写了个WxMpInRedisConfigStorage，因为我项目中有对jedis的封装，缓存统一管理的。
不过我看开发分支里已经修改成JedisPool了

**Comment by thefirstwind** [comment]
其实使用原来的 WxMpConfigStorage就可以实现集群应用+redis单点。
实现方案如下：
1 使用原有的 WxMpConfigStorage
2 在spring的 application.property中 session的类型， 改成spring.session.store-type=redis。
3 设置默认的redis参数

我现在粉丝15w人，每日pv 20w左右，用起来没啥问题。
