### ISSUE TITLE
个性化菜单group_id问题

### ISSUE THREAD

**Issue by dapeng-beijing** [binarywang/WxJava#365]
创建个性化菜单时传入的参数为tag_id，但是查询个性化菜单时微信返回的参数名为group_id。
实际测试2.8.5BETA版本还是未将此参数封装到WxMenuRule对象中。
下面为2.8.5BETA版本中源码
```
/**
   * 变态的微信接口，反序列化时这里反人类的使用和序列化时不一样的名字
   */
  @SerializedName(value = "tag_id", alternate = "group_id")
  private String tagId;
```

**Comment by binarywang** [comment]
请问你是如何测试的，能否简单描述下？

**Comment by dapeng-beijing** [comment]
调用下面方法
WxMpMenu wxMenu = manufactureWechatService.getMenuService().menuGet();
控制台中微信返回的参数有："matchrule":{"group_id":"102"}
但是WxMpMenu中WxMpConditionalMenu里的WxMenuRule里所有字段都为空（即未将group_id封装进去） @binarywang

**Comment by binarywang** [comment]
`me.chanjar.weixin.mp.api.impl.WxMpMenuServiceImplTest#testMenuGet_AfterCreateConditionalMenu`
我刚运行了此单元测试，tagId是有值的。

**Comment by dapeng-beijing** [comment]
将我们项目里
`                    <dependency>
				<groupId>com.google.code.gson</groupId>
				<artifactId>gson</artifactId>
				<version>${gson.version}</version>
			</dependency>`
依赖版本由2.2.4改为2.8.0成功解决问题，感谢帮助 @binarywang
