### ISSUE TITLE
小程序发送模板消息时在获取getAccessToken时报api.weixin.qq.com:443 failed to respond

### ISSUE THREAD

**Issue by af826** [binarywang/WxJava#366]
@binarywang java.lang.RuntimeException: org.apache.http.NoHttpResponseException: api.weixin.qq.com:443 failed to respond
        at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.getAccessToken(WxMaServiceImpl.java:112)
        at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.executeInternal(WxMaServiceImpl.java:186)
        at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.execute(WxMaServiceImpl.java:154)
        at cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.post(WxMaServiceImpl.java:144)
        at cn.binarywang.wx.miniapp.api.impl.WxMaMsgServiceImpl.sendTemplateMsg(WxMaMsgServiceImpl.java:31)

**Comment by af826** [comment]
@binarywang

**Comment by binarywang** [comment]
偶尔的问题，还是一直有的问题？

**Comment by af826** [comment]
一直有，可以重复复现，是不是获取微信accessToken时出现问题还是其他的

我参照WxMaInMemoryConfig 实现了个redis版本的目前没有出现问题，还在观察，看了您的源码写的非常好 @binarywang

**Comment by af826** [comment]
是不是没有写过期时间的过
`        WxMaInMemoryConfig config = new WxMaInMemoryConfig();
        config.setAppid("wxf8619761c69338f6"); // 设置微信公众号的appid
        config.setSecret("b68b5e72f61f7e6c8c9eadbf65edefa9"); // 设置微信公众号的app corpSecret
       
        WxMaService wxMaService =new WxMaServiceImpl();
        wxMaService.setWxMaConfig(config);
        WxMaMsgService wxMaMsgService= new WxMaMsgServiceImpl(wxMaService);

        WxMaTemplateMessage wxMaTemplateMessage=WxMaTemplateMessage.newBuilder().
                templateId(templateId).
                data(dataList).
                toUser(openId).
                formId(formId).
                page("/pages/index/index").
//                emphasisKeyword(emphasisKeyword+".DATA").
                build();
        try {
            wxMaMsgService.sendTemplateMsg(wxMaTemplateMessage);`

**Comment by af826** [comment]
还是会出现，请教是什么问题

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/issues/276 请参考下这个issue中提到的办法

**Comment by af826** [comment]
好的谢谢
