### ISSUE TITLE
WxMpInRedisConfigStorage存在bug，可能会导致循环获取access_token

### ISSUE THREAD

**Issue by imtiaotiao** [binarywang/WxJava#369]
WxMpInRedisConfigStorage集成自WxMpInMemoryConfigStorage，且没有重写getAccessTokenLock、getJsapiTicketLock等方法，故使用的是ReentrantLock。
也就是说，对于单实例来说，可以通过重入锁实现临界资源的保护，但在部署多个业务实例的情况下，不能保证对临界资源的访问的原子性，完全有可能出现如下情况：

    1. A实例访问redis获知access_token已过期，故向微信服务器获取新的access_token；
    2. 此时，B实例访问redis获取access_token，发现已过期，也会向微信服务器获取新的access_token；
    3. 悲剧的是可能B会先于A将获取到的access_token，此时A的可能已经失效，这样接下来又会去申请新的；
    4. 这就出现了不同实例同时获取access_token的情况，循环获取，极端情况下就是部分实例一直拿到无效的access_token并刷新；
    (虽然微信方保证了access_token在切换时，5分钟内新老access_token均有效，但毕竟会出现问题)
建议这里使用Redis实现分布式锁，以保证临界资源访问的原子性。另外，启动1个专门用于刷新access_token/jsapi_ticket/cardapi_ticket的线程，利用access_token等切换时5分钟内均有效的原则，发现已过期时，通知此线程进行刷新，并使用分布式锁，防止多个实例都刷新。而业务线程无需等待，直接调用接口即可。

**Comment by binarywang** [comment]
这个redis的实现仅是一个demo，欢迎提供更完善的实现代码供别人参考

**Comment by thefirstwind** [comment]
其实使用原来的 WxMpConfigStorage就可以实现集群。
实现方案如下：
1 使用原有的 WxMpConfigStorage
2 在spring的 application.property中 session的类型， 改成spring.session.store-type=redis。 
3 设置默认的redis参数
（框架是spring-boot）
就可以搞定了。

**Comment by imtiaotiao** [comment]
@thefirstwind 第一，此bug无关乎session的问题；第二，即使是session，请你真正实践了再发表，spring session实现需要将生成的session id(不能自定义哦)放在cookies或者header中，或者其他存储介质中，总之需要告知客户端。但这里的场景，微信服务器肯定不会存储生成的session id，能使用的只有fromUser，所以直接不能直接使用spring session。

**Comment by thefirstwind** [comment]
我们现在用户量15w，每日有17w的pv，就是用这套方案，不间断的运行已经快2年了。

至于您这边，为什么产生这样的bug，可能是WxMpInRedisConfigStorage 的内部实现方式。
我之前也尝试过 使用 WxMpInRedisConfigStorage 来实现，造成大量的  Broken Pipe。
也就另辟蹊径。
通过 WxMpConfigStorage + spring.session=redis 来托管 每台服务器的 session到同一台redis服务器上。
所以也不用考虑不同服务器上 的session或者 生成 access_token不一致的问题。

另外，至于存储session id，这个也根本没有纠结，session 的时间设置成 1小时，过期就失效。
 在用户再次进入页面的时候 从新发布session。

而access_token，是存在 session里面的，页面访问的时候先判断session里面是否有 access_token，没有就从新授权 ，只要保证 session的过期时间 小于 access_token 即可。

**Comment by imtiaotiao** [comment]
@thefirstwind 如果你这里的session指的是微信内页面访问用户的session，那是没有问题的，我以为你讲的从微信服务器转发消息的Session，类似于本项目的WxSession。我目前是采取了Redis分布式锁，另开线程刷新的策略，对于你上面的解决方案，有一些小疑问，可否加个好友，交流下？你讲的access_token存到session中，那access_token是由谁去做的刷新？session过期后重新授权，这里的授权是重新获取access_token吗？会不会存在同时多个用户session过期(或新用户还没session)时访问，此时是如何处理？是否存在一个单独的服务器刷新access_token，其他服务器只是从这台服务器这里取(或者共享在redis中)呢？

**Comment by thefirstwind** [comment]
access_token 是通过java后台，调用微信的 jsapiticket 发行的，当判断 session.getAttribute("access_token") 为空的时候（即过期或者第一次访问），从新 获取 jsapiticket 发行新的 access_token 同时就完成了从新授权的目的 ，否者直接去session里面存的 access_token 。
没有用单独的服务器来主动刷新access_token ，都是根据用户的行为来 被动刷新。
每个页面设置 一个类似路由的js方法，都要调取上面说的那个 access_token 的后台接口。

对了，因为微信授权 这个很多人的做法是通过的页面跳转 来做的。 很蛋疼， 所以 改写成了 ajax请求，不用页面跳转。想对来说更便捷

**Comment by thefirstwind** [comment]
/**
	 * 返回页面格式的Callback结果
	 * 
	 * @param params
	 * @param request
	 * @param model
	 * @return
	 */
	@RequestMapping("/callback")
	public String  callback(@RequestParam Map<String, String> params, HttpServletRequest request, RedirectAttributes redirectAttrs) {
		/////////// 页面参数配置 start //////////////////////////////////
		OauthBean ob = oservice.getOauthBean(params);
		
		WxMpOAuth2AccessToken accessToken = null;
		WxMpUser wxMpUser = null;
		String openid = "";
		try {
			if(session.getAttribute("openid") ==null){
				accessToken = wxMpService.oauth2getAccessToken(ob.getCode());
				openid = accessToken.getOpenId();
				session.setAttribute("openid", openid);
				session.setAttribute("accessToken", accessToken.getAccessToken());
				log.debug("callback2 : {}", openid);
				log.debug("callback2 : params{}", params);
				UpdShareInfo(params, openid);
				try{
					wxMpUser = wxMpService.oauth2getUserInfo(accessToken, "zh_CN");
				}catch(WxErrorException e){
					log.error("wxMpService.oauth2getUserInfo error | uopid {}", openid+" errorMsg:"+e.getMessage() );
				}
			}else{
				openid = session.getAttribute("openid").toString();
				log.debug("callback2 : {}", session.getAttribute("openid").toString());
				UpdShareInfo(params, openid);
			}
		} catch (WxErrorException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		try {
			updUserInfo(openid);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		StringBuilder redirectUrl = new StringBuilder();
		Set<String> keys = params.keySet();
		if (keys.size() > 0) {
			if(params.get("p").toString().contains("?")){
				redirectUrl.append(params.get("p").toString() + "&");
			}else{
				redirectUrl.append(params.get("p").toString() + "?");
			}
		}
		for (String key : keys.stream().sorted().collect(Collectors.toList())) {
			if("p".equals(key)) continue;
			if("state".equals(key)) continue;
			if("code".equals(key)) continue;
			redirectUrl.append(key);
			redirectUrl.append("=");
			redirectUrl.append(params.get(key));
			redirectUrl.append("&");
		}
		if (redirectUrl.lastIndexOf("&") == redirectUrl.length() - 1) {
			redirectUrl.setLength(redirectUrl.length() - 1);
		}
		return "redirect:" + redirectUrl.toString();

	}
	
	@RequestMapping("/getjsapi")
	@ResponseBody
	public Map<String,Object>getjsapi (@RequestParam Map<String, String> params, HttpServletRequest request){
		log.debug(">>>>>>>>>>>params:{}", params);
		Map<String,Object> result = new HashMap<String,Object>();
		try{
			log.debug("xxxxxxxxx: getAccessToken : {}", wxMpService.getAccessToken());
			
			if(session.getAttribute("openid") != null){
				String jsapiTicket =wxMpService.getJsapiTicket();
				WxJsapiSignature wxJsapiSignature = wxMpService.createJsapiSignature(params.get("p").toString());
				
				result.put("jsapiTicket", jsapiTicket);
				result.put("jsapiSignature", wxJsapiSignature.getSignature());
				result.put("jsapiNoncestr", wxJsapiSignature.getNonceStr());
				result.put("jsapiTimestamp", wxJsapiSignature.getTimestamp());
				
				result.put("appid", session.getAttribute("appid").toString());
				result.put("openid", session.getAttribute("openid").toString());
				result.put("accessToken", session.getAttribute("accessToken").toString());
				result.put("wxcode",null);

			}else{
				// 如果相同页面并且已经授权过
				String state = UUID.randomUUID().toString();
				StringBuilder redirectUrl = new StringBuilder();
				String url = params.get("p").toString();
				url = url.replaceAll("^(http://)?[^/]*", "");
				log.debug(">>>>>>>>>>> url : |{}|", url);
				redirectUrl.append(domain + addrCallback + "?p=" + url);
				if (redirectUrl.lastIndexOf("&") == redirectUrl.length() - 1) {
					redirectUrl.setLength(redirectUrl.length() - 1);
				}
				String snsapiLogin = wxMpService.oauth2buildAuthorizationUrl(redirectUrl.toString(), WxConsts.OAUTH2_SCOPE_USER_INFO, state);
				log.debug("snsapiLogin:{}", snsapiLogin);
				result.put("snsapiLogin", snsapiLogin);
			}
			session.setAttribute("page", params.get("p").toString());
		}catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return result;
	}

**Comment by thefirstwind** [comment]
js代码段

$.ajax({
	type: "GET",
	url: '/getjsapi?p=' + encodeURIComponent(location.href),
	contentType: 'text/html',
	success: function(data) {
		if (data.snsapiLogin){
			location.href = data.snsapiLogin;
		}else{
			console.log(data);
			wxConfig(data.appid,data.jsapiTimestamp,data.jsapiNoncestr,data.jsapiSignature);
		}
	},
	error: function(xhr) {
		$.toast('授权失败.', 5000);
		console.log("ajax error")
	},
	complete: function(xhr) {
		console.log("complete");
	}
});

**Comment by thefirstwind** [comment]
至于redis的配置，无非就是托管 spring 的默认 session 存储方式，
在application.properties 中设置

spring.session.store-type=redis  （也可以是JDBC）
server.session.timeout=3600  （1小时）

**Comment by thefirstwind** [comment]
至于redis的分布式锁，我还不知道怎么弄，脑细胞不够用，直接买的 现成的 aliyun redis服务。

**Comment by thefirstwind** [comment]
wechat: thefirstwind  随时欢迎

**Comment by imtiaotiao** [comment]
@thefirstwind 表示感谢。我明白了，你说的是access_token是oauth2 access_token，仅仅用于网页授权时使用，而不是微信公众号的全局唯一接口调用凭据access_token。
![image](https://user-images.githubusercontent.com/7044912/33701906-feff5856-db5b-11e7-9bf5-d7a44da14c7d.png)如果你是用的默认的WxMpConfigStorage，即WxMpInMemoryConfigStorage实现类，那么access_token(这里指的全局唯一接口调用凭证)和jsapiTicket等都在内存中，那这两个值是如何在不同服务器间共享呢？

**Comment by imtiaotiao** [comment]
@thefirstwind 你讲的集群方案仅仅是前端业务系统(从微信网页授权之后业务)的实现方案，并没有解决全局唯一调用接口凭证(普通access_token)的集群。我不知道你后端的服务器是几台，我们假设场景，你有2台服务器，那么两台服务器都会存储jsapi_ticket，而这个值是通过普通access_token来获取的，从你的代码来看，你是从wxService中直接取的，如果普通access_token和jsapi_ticket是存储在内存中，默认方案是自动刷新，那么会造成两台服务器的值不一致，因此从这里来看并没有实现WxMpConfigStorage的集群。如果你那边真的是很多服务器同时在对接一个公众号，我感觉是有问题的。
如图是获取普通access_token的实现：
![image](https://user-images.githubusercontent.com/7044912/33702473-b30e7bd6-db5e-11e7-91e4-e8f0d431c511.png)


交流后，我发现兄弟你对我提出的bug，所指的意思理解有些偏差。WxMpInRedisConfigStorage实现的是将普通的access_token和jsapi_ticket等值存储在redis中，不同的业务服务器可以共享这部分数据，作者demo的问题是数据共享，但锁机制使用的内存锁，可能会出现不同服务器同时刷新access_token的问题。

最后对于你说的，微信授权用ajax来实现的，看你的代码并没有啊，callback过来之后，还是redirect到接下来的页面啊，哪里体现了ajax啊？难道说的是getjsapi接口？这个用于微信页面js-sdk的权限验证就仁者见仁智者见智，前后端分离的用ajax，用模板的用spring interceptor，都是可以的。

**Comment by thefirstwind** [comment]
>> 那么access_token(这里指的全局唯一接口调用凭证)和jsapiTicket等都在内存中，那这两个值是如何在不同服务器间共享呢


不同服务器间共享 就是通过 spring session 的实现方式来做的， 把spring-session 连到同一台redis 就解决这个问题了。相当于 多个 服务器共享 内存，而这个内存就是同一台redis。
所以我觉得  作者 写 WxMpInRedisConfigStorage 也是多余，反而造成了很多的bug。实现起来问题多多。

**Comment by thefirstwind** [comment]
后台接口服务器 5-8台浮动， html服务器 4台， redis服务器1台， 定期后台服务器 1台。
而后台和html服务器都是通过 负载均衡 分流。绑定在 2个域名上 www.domain.com  api.domain.com 这样。

**Comment by imtiaotiao** [comment]
你的代码里面session保存了oauth2 access_token和open_id，哪里保存了普通access_token(这里指的全局唯一接口调用凭证)和jsapiTicket？别逗我好伐……你共享的open_id和oauth2 access_token。加你微信了

**Comment by rjliulei** [comment]
我想知道有下文了么。。

**Comment by imtiaotiao** [comment]
@rjliulei Then we become friends

**Comment by JimmyLincole** [comment]
调整下 `WxMpInRedisConfigStorage.java` 文件

``` java
@Override
public boolean isAccessTokenExpired() {
  try (Jedis jedis = this.jedisPool.getResource()) {
    return jedis.ttl(accessTokenKey) < 2 && 
           jedis.setnx("xxx", "yyy") == 1;
  }
}

@Override
public synchronized void updateAccessToken(String accessToken, int expiresInSeconds) {
  try (Jedis jedis = this.jedisPool.getResource()) {
    jedis.setex(this.accessTokenKey, expiresInSeconds - 200, accessToken);
    jedis.del("xxx");
  }
}
```

没验证过，不知道这样能否解决问题 [呲牙][呲牙]

**Comment by williamtsang88** [comment]
> @rjliulei Then we become friends

本来我不信github是全球最大的同性交友网站，现在我信了。
