### ISSUE TITLE
1.3.4版本中对httpclient的增强导致timeout,wxcp的测试用例无法通过

### ISSUE THREAD

**Issue by terlanks** [binarywang/WxJava#37]
ApacheHttpClientBuilder 新httpclient增强部分导致所有WxCPService 中的调用api服务失败，恢复使用原代码如下是能正常跑通的：
@Override
    public void setWxConfigStorage(WxConfigStorage wxConfigProvider) {
        this.wxConfigStorage = wxConfigProvider;

```
    String http_proxy_host = wxConfigStorage.getHttp_proxy_host();
    int http_proxy_port = wxConfigStorage.getHttp_proxy_port();
    String http_proxy_username = wxConfigStorage.getHttp_proxy_username();
    String http_proxy_password = wxConfigStorage.getHttp_proxy_password();

    if (StringUtils.isNotBlank(http_proxy_host)) {
        // 使用代理服务器
        if (StringUtils.isNotBlank(http_proxy_username)) {
            // 需要用户认证的代理服务器
            CredentialsProvider credsProvider = new BasicCredentialsProvider();
            credsProvider.setCredentials(new AuthScope(http_proxy_host, http_proxy_port),
                    new UsernamePasswordCredentials(http_proxy_username, http_proxy_password));
            httpClient = HttpClients.custom().setDefaultCredentialsProvider(credsProvider).build();
        } else {
            // 无需用户认证的代理服务器
            httpClient = HttpClients.createDefault();
        }
        httpProxy = new HttpHost(http_proxy_host, http_proxy_port);
    } else {
        httpClient = HttpClients.createDefault();
    }
}
```

但是总感觉还是不太稳定，因为老版本的httpclient在我一个国外的服务器上执行execute GET request就会timeout

**Comment by binarywang** [comment]
目前在mp中还没发现有问题，你用最新的版本试试看有问题没？

**Comment by bysunexus** [comment]
可以实现me.chanjar.weixin.common.util.http.ApacheHttpClientBuilder这个接口来控制httpclient的参数
或者自定义me.chanjar.weixin.common.util.http.DefaultApacheHttpHttpClientBuilder的属性注入到
me.chanjar.weixin.cp.api.WxCpConfigStorage的实现类中以修改DefaultApacheHttpHttpClientBuilder中默认的超时时间设置

这个pr提交的主要目的是为了将更多的httpclient可控参数暴露出来可以设置,默认的属性设置可能不适用于全部情况.

**Comment by binarywang** [comment]
@terlanks  我这才明白确实是跟代理有关系的，我已经做了相关的修复，可以使用2.1.2的临时版本，或者可以等下一个正式版发布

**Comment by binarywang** [comment]
@terlanks   你看下是不是跟代理设置有关系，可以使用2.1.2的临时版本测试下

**Comment by terlanks** [comment]
Ok,我试一下

发自我的 iPhone

在 2016年9月14日，下午1:39，Binary Wang <notifications@github.com<mailto:notifications@github.com>> 写道：

@terlankshttps://github.com/terlanks 我这才明白确实是跟代理有关系的，我已经做了相关的修复，可以使用2.1.2的临时版本，或者可以等下一个正式版发布

―

**Comment by binarywang** [comment]
@terlanks 现在是否还有问题？

**Comment by terlanks** [comment]
这周都在外面出差，一直没时间测试，周一在办公室看了下好像没找到你说的那个版本诶？

发自我的 iPhone

在 2016年9月21日，下午9:20，Binary Wang <notifications@github.com<mailto:notifications@github.com>> 写道：

@terlankshttps://github.com/terlanks 现在是否还有问题？

―

**Comment by binarywang** [comment]
现在最新版是2.1.5你也可以试下，你可能group id没改过来，注意仔细看下项目首页的说明

**Comment by terlanks** [comment]
OK了
