### ISSUE TITLE
WxMpServiceOkHttpImpl/WxCpServiceOkHttpImpl实现使用socks5代理，跟其他实现不一致

### ISSUE THREAD

**Issue by imtiaotiao** [binarywang/WxJava#370]
![image](https://user-images.githubusercontent.com/7044912/32594697-f3fb6576-c567-11e7-8b7d-3c9d8ac40365.png)
这里为什么使用sock5，Apache HTTPclient和jodd都是http，为什么okhttp使用sock5，差点掉坑里……

**Comment by binarywang** [comment]
这个应该属于笔误，感谢及时发现指正

**Comment by binarywang** [comment]
测试版本2.8.7.BETA已修复
