### ISSUE TITLE
WxMpDeviceServiceImpl 构造器修饰符

### ISSUE THREAD

**Issue by keysir** [binarywang/WxJava#373]
WxMpDeviceServiceImpl(WxMpService wxMpService) {
    this.wxMpService = wxMpService;
  }
不好意思 换这里解释下 所有的ServiceImpl 都是public 修饰符这个不是 ；

重新实现WxMpService的原因是日志级别，给未关注的用户发模版消息保存就会不停出现 日志错误 "errcode":43004,"  还有就是不用初始化太多用不到的Service; 这些是个人原因啦

**Comment by binarywang** [comment]
不知道你看的哪个版本，我看最新代码已经加上了public
