### ISSUE TITLE
微信支付签名好像有问题

### ISSUE THREAD

**Issue by hhxx1994** [binarywang/WxJava#374]
@Data
@Builder
public class WxPayMpOrderResult {
  private String appId;
  private String timeStamp;
  private String nonceStr;
  /**
   * 由于package为java保留关键字，因此改为packageValue
   */
  @XStreamAlias("package")
  private String packageValue;
  private String signType;
  private String paySign;
}

**Comment by hhxx1994** [comment]
BeanUtils中只加密package字段
public static Map<String, String> xmlBean2Map(Object bean) {
    Map<String, String> result = Maps.newHashMap();
    List<Field> fields = new ArrayList<>( Arrays.asList(bean.getClass().getDeclaredFields()));
    fields.addAll(Arrays.asList(bean.getClass().getSuperclass().getDeclaredFields()));
    for (Field field : fields) {
      try {
        boolean isAccessible = field.isAccessible();
        field.setAccessible(true);
        if (field.get(bean) == null) {
          field.setAccessible(isAccessible);
          continue;
        }

        if (field.isAnnotationPresent(XStreamAlias.class)) {
          result.put(field.getAnnotation(XStreamAlias.class).value(),
            field.get(bean).toString());
        }

        field.setAccessible(isAccessible);
      } catch (SecurityException | IllegalArgumentException
        | IllegalAccessException e) {
        e.printStackTrace();
      }

    }

    return result;
  }

**Comment by binarywang** [comment]
请使用最新的测试版本，这个问题做过修复
