### ISSUE TITLE
生成二维码失败返回还是jpg而不是json结果

### ISSUE THREAD

**Issue by wxq888333** [binarywang/WxJava#375]
cn.binarywang.wx.miniapp.util.http.QrCodeRequestExecutor 
51行
ContentType.APPLICATION_JSON.getMimeType().equals(contentTypeHeader[0].getValue())
ContentType.APPLICATION_JSON.getMimeType() 结果为"application/json",
而当生成二维码失败contentTypeHeader[0].getValue()结果为"application/json:UTF-8",
导致条件不成立，生成错误的jpg图片

**Comment by wxq888333** [comment]
当前版本为2.8.1

**Comment by binarywang** [comment]
这个修复过，请使用最新测试版本
