### ISSUE TITLE
多个agentId问题,开发企业微信,有多个应用,多个agentId和Secret如何解决

### ISSUE THREAD

**Issue by jueyue** [binarywang/WxJava#382]
多个agentId问题,开发企业微信,有多个应用,多个agentId和Secret如何解决
看配置文件有很多,打算自己改了,官方有啥解决方案不

**Comment by binarywang** [comment]
参考多公众号的实现

**Comment by jueyue** [comment]
@binarywang 看了看,那样太麻烦了,其实只是多个token而已,没必要我每个类都搞一遍吧,主要我告诉你是那个id,你判断下就可以了啊,感觉你们可以优化下
