### ISSUE TITLE
微信支付查询代金券信息返回coupon_state字段应为 string 类型

### ISSUE THREAD

**Issue by tobereborn** [binarywang/WxJava#383]
你好：
如题，类com.github.binarywang.wxpay.bean.coupon.WxPayCouponInfoQueryResult 
的couponState 应设置成String类型.

官方接口定义如下：
https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_5&index=6

谢谢

**Comment by binarywang** [comment]
感谢及时提出此问题

**Comment by binarywang** [comment]
2.8.9.BETA 已修复
