### ISSUE TITLE
如何获取okhttpclient

### ISSUE THREAD

**Issue by cena009** [binarywang/WxJava#386]
WxMpService wxMpService = new WxMpServiceOkHttpImpl();
想获取wxmpService里的okhttpclient，如果new okhttpclient的话，线程里有两个okhttpclient线程池了

**Comment by bysunexus** [comment]
okhttpclient不是特别了解,但是需要注意的是不应该获取weixin-java-tools中的okhttpclient实例
应该是如何设置weixin-java-tools中的weixin-java-tools实例
如果okhttpclient有线程池也根据router规划的话那么weixin-java-tools中的okhttpclient实例的线程池配置和router规划并不一定会适用于你的其他的http请求
好的做法是将你自定义的okhttpclient设置到weixin-java-tools中

**Comment by cena009** [comment]
请教自定义的okhttpclient设置到weixin-java-tools中

**Comment by cena009** [comment]
请问如何自定义的okhttpclient设置到weixin-java-tools中,能否像DefaultApacheHttpClientBuilder一样提供一个buider设置okhttp

**Comment by binarywang** [comment]
这个因为我们都没有具体的使用需求，没法提供实现，你可以自己根据实际需要实现一个。
