### ISSUE TITLE
微信网页授权{"errcode":40163,"errmsg":"code been used, hints: [ req_id: plAv90053th21 ]"}

### ISSUE THREAD

**Issue by wen-sr** [binarywang/WxJava#388]
WxMpOAuth2AccessToken wxMpOAuth2AccessToken = null;
        try {
                wxMpOAuth2AccessToken = wxMpService.oauth2getAccessToken(code);
        } catch (WxErrorException e) {
            e.printStackTrace();
       ｝
请问执行这行代码时报这个错是怎么回事有人知道吗？

**Comment by muzi1994** [comment]
微信授权后，微信会多次重定向到回调链接

**Comment by wen-sr** [comment]
没搞懂，有处理办法吗？

**Comment by muzi1994** [comment]
我的项目之前打的是jar文件运行部署的，后来我将项目打成war，用tomcat部署就解决了，就不会重复接收到微信多次重定向
