### ISSUE TITLE
请问大神 微信如何实现点击链接返回客服消息？

### ISSUE THREAD

**Issue by eratel** [binarywang/WxJava#390]
微信实现点击链接返回客服消息

**Comment by binarywang** [comment]
首先你的说法有问题，“返回客服消息“”是什么鬼？
我猜测你的意思可能是想点击链接就接入在线客服，这是无法实现的，你可以使用菜单实现，或者当用户发生某种交互，比如发送了某个关键字，自动接入客服。

**Comment by eratel** [comment]
是的  他们的需求有问题

**Comment by eratel** [comment]
已经解决问题了  谢谢
