### ISSUE TITLE
关于API文档更新.

### ISSUE THREAD

**Issue by PepperYan** [binarywang/WxJava#393]
API文档能否以版本划分, 例如WxConst包下的事件常量调整以后, 老版本的事件常量跟文档对不上.

**Comment by binarywang** [comment]
可以增加相应api文档说明，不过大家都是做开发的，直接看对应源码即可

**Comment by binarywang** [comment]
或者参考在线javadoc：https://binarywang.github.io/weixin-java-common-javadoc/me/chanjar/weixin/common/api/WxConsts.html
