### ISSUE TITLE
服务号发送模板消息时携带小程序时出现异常

### ISSUE THREAD

**Issue by af826** [binarywang/WxJava#396]
{"errcode":40165,"errmsg":"invalid weapp pagepath hint: [Qb_msa0613ge30]
我的

pagePath 写的是pages/index/index
难道是小程序没有发布的问题吗
@binarywang

**Comment by binarywang** [comment]
应该是，必须是发布的小程序才可以用

**Comment by af826** [comment]
验证是这样
