### ISSUE TITLE
使用微信开放平台SDK获取Menu错误

### ISSUE THREAD

**Issue by mywsat** [binarywang/WxJava#397]
`wxOpenService.getWxOpenComponentService().getWxMpServiceByAppid(appId).getMenuService().getSelfMenuInfo()`
请求获取token参数：{"component_appid":"wx906b1a6284a946bf","authorizer_appid":"wxb6fa6ca657bfcc0c","authorizer_refresh_token":null} ，
authorizer_refresh_token为空，无法获得token

**Comment by 007gzs** [comment]
wxb6fa6ca657bfcc0c 这个公众号执行过扫码授权么？或者是用新的SDK后执行过扫码授权么？authorizer_refresh_token是在扫码授权时保存的

**Comment by mywsat** [comment]
不好意思，我明白了。授权必须要本地保存。失效后要重新申请

**Comment by 007gzs** [comment]
授权时要储存，我DEMO里应该是存在REDIS里，没做过期时间，所以要在SDK中授权一次，正式使用时最好储存在自己的MYSQL中.


authorizer_refresh_token | 接口调用凭据刷新令牌（在授权的公众号具备API权限时，才有此返回值），刷新令牌主要用于第三方平台获取和刷新已授权用户的access_token，只会在授权时刻提供，请妥善保存。 一旦丢失，只能让用户重新授权，才能再次拿到新的刷新令牌

**Comment by mywsat** [comment]
是否考虑做的定时任务，来实现刷新令牌？
