### ISSUE TITLE
big Bug

### ISSUE THREAD

**Issue by Mr-han** [binarywang/WxJava#405]
![image](https://user-images.githubusercontent.com/9997847/34093264-40053722-e402-11e7-9152-91d5b4a5e3b5.png)
me.chanjar.weixin.common.util.BeanUtils.xmlBean2Map 这个方法：没有注解 不放进map 里面有问题，尽快修改。

**Comment by Mr-han** [comment]
![image](https://user-images.githubusercontent.com/9997847/34093371-c4778d02-e402-11e7-955c-a352ac9941c0.png)
这个类 只有 package。

**Comment by Mr-han** [comment]
WxPayServiceAbstractImpl.createOrder  签名会出现问题。问题比较大。。。。。。。。

**Comment by binarywang** [comment]
你看的代码有点老，这个问题早修复了
https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/BeanUtils.java
