### ISSUE TITLE
获取授权方的帐号基本信息 返回对象

### ISSUE THREAD

**Issue by DrunkLife** [binarywang/WxJava#407]
2.9.2.BETA测试版 代码中 me.chanjar.weixin.open.bean.auth.WxOpenAuthorizerInfo.MiniProgramInfo里面 miniProgramInfo和Network中的requestDomain、wsRequestDomain、uploadDomain、downloadDomain 字段腾讯返回的是大写开头  ，visitStatus 腾讯返回的是visit_status，Network 类实际腾讯返回的还有一个BizDomain字段（在文档中没有体现出来，不知道啥意思）

me.chanjar.weixin.open.bean.auth.WxOpenAuthorizerInfo.MiniProgramInfo 代码如下：
@Data
	public class MiniProgramInfo {

		@SerializedName("visit_status")
		private Integer visitStatus;
		/**
		 * 小程序已设置的各个服务器域名
		 */
		private Network network;
		private List<Category> categories;

		@Data
		public class Category {
			private String first;
			private String second;
		}

		@Data
		public class Network {
			@SerializedName("RequestDomain")
			private List<String> requestDomain;
			@SerializedName("WsRequestDomain")
			private List<String> wsRequestDomain;
			@SerializedName("UploadDomain")
			private List<String> uploadDomain;
			@SerializedName("DownloadDomain")
			private List<String> downloadDomain;
			@SerializedName("BizDomain")
			private List<String> bizDomain;
		}
	}

me.chanjar.weixin.open.util.json.WxOpenAuthorizerInfoGsonAdapter中的
WxOpenAuthorizerInfo.MiniProgramInfo miniProgramInfo = WxOpenGsonBuilder.create()
				.fromJson(jsonObject.get("miniProgramInfo"), new TypeToken<WxOpenAuthorizerInfo.MiniProgramInfo>() {
				}.getType());
改成：
WxOpenAuthorizerInfo.MiniProgramInfo miniProgramInfo = WxOpenGsonBuilder.create()
				.fromJson(jsonObject.get("MiniProgramInfo"), new TypeToken<WxOpenAuthorizerInfo.MiniProgramInfo>() {
				}.getType());

**Comment by binarywang** [comment]
方便的话你可以自己提交代码，其实很简单的

**Comment by binarywang** [comment]
这次我就先代劳了，下次尽量自己提交吧，非常感谢你及时提出问题

**Comment by DrunkLife** [comment]
谢谢，空了研究研究怎么弄
