### ISSUE TITLE
您好，我下载2.9.0项目后,打开weixin-java-mp，发现有部分文档是不全的

### ISSUE THREAD

**Issue by sunny12308** [binarywang/WxJava#408]
2.9.0版本，WxMpMassOpenIdsMessage文件缺少了很多方法，导致打开weixin-java-mp项目，报错。请检查一下。

同样的2.9.0版本，我在maven库上，下载jar包发现WxMpMassOpenIdsMessage里面方法是全的。

还有其他文件存在类似问题

**Comment by binarywang** [comment]
源码需要依赖lombok进行编译。
如果你不是为了自己修改源码，直接使用maven引用即可，可以参考对应demo。

**Comment by sunny12308** [comment]
哦，好的，谢谢
