### ISSUE TITLE
weixin-java-open【代小程序之微信登陆】

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#410]
code 换取 session_key

第三方平台开发者的服务器使用登录凭证 code 以及第三方平台的component_access_token 获取 session_key 和 openid。

请求方式:
https://api.weixin.qq.com/sns/component/jscode2session?appid=APPID&js_code=JSCODE&grant_type=authorization_code&component_appid=COMPONENT_APPID&component_access_token=ACCESS_TOKEN

参数说明：

参数	             是否必须	    说明
appid	                是	小程序的AppID
js_code	                是	登录时获取的 code
grant_type	        是	填authorization_code
component_appid	        是	第三方平台appid
component_access_token	是	第三方平台的component_access_token

**Comment by 007gzs** [comment]
https://github.com/Wechat-Group/weixin-java-tools/pull/420 已增加

**Comment by binarywang** [comment]
2.9.4.BETA版本已实现
