### ISSUE TITLE
开放平台模块 微信卡券相关方法有问题

### ISSUE THREAD

**Issue by mywsat** [binarywang/WxJava#412]
类目：WxOpenInRedisConfigStorage
方法 updateCardApiTicket 
注意方法的参数名，和类的变量名冲突。没有加入this关键字导致cardApiTicket错误
方法 expireCardApiTicket getCardApiTicket（这2个方法其中之一，我忘了是哪个）
this.cardApiTicket 写错成this.jsapiTicketKey

**Comment by binarywang** [comment]
这个确实是不应该出现的问题，我抽空核查下代码

**Comment by binarywang** [comment]
另外这个redis的实现仅供参考，建议自己根据自己需要实现。

**Comment by binarywang** [comment]
2.9.3.BETA版本已修复
