### ISSUE TITLE
WxMpInMemoryConfigStorage 需要实现序列化

### ISSUE THREAD

**Issue by ningtimes** [binarywang/WxJava#415]
WxMpInMemoryConfigStorage 需要实现序列化

public class WxMpInMemoryConfigStorage implements WxMpConfigStorage,java.io.Serializable{

……
}

**Comment by binarywang** [comment]
为什么需要序列化？如果需要你自己可以去继承实现该类，然后进行实现。

**Comment by binarywang** [comment]
建议自己去继承自定义实现，内部有不少大对象，不便于实现序列化
