### ISSUE TITLE
2.9.3beta bcprov-jdk16会与新的bcprov-jdk15on 冲突，建议用bcprov-jdk15on 

### ISSUE THREAD

**Issue by TeakSen** [binarywang/WxJava#418]
2.9.3beta bcprov-jdk16会与新的bcprov-jdk15on 冲突，建议用bcprov-jdk15on

**Comment by binarywang** [comment]
看得有点晕，也就是说是你自己项目jar包冲突的问题了？

**Comment by binarywang** [comment]
`http://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk16`
`http://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on`

刚才对比了下，确实应该使用bcprov-jdk15on，会比较新一些

**Comment by binarywang** [comment]
经过研究发现，只使用bcprov-jdk15on这一个是有问题的，还需要借助其他包，还不如bcprov-jdk16省心

**Comment by binarywang** [comment]
如果是你自己项目jar冲突问题，你可以自己根据情况增删jar包
