### ISSUE TITLE
WxMpServiceAbstractImpl打印的错误日志无法屏蔽

### ISSUE THREAD

**Issue by Raysor** [binarywang/WxJava#419]
WxMpServiceAbstractImpl#executeInternal时报错，抛出了异常，但又记录error log。
log用的this.getClass()获取的，导致categoryName是项目业务上的package，无法直接屏蔽。

**Comment by binarywang** [comment]
没看明白，能否说明下你希望改成什么样子吗？

**Comment by binarywang** [comment]
暂时关闭，如有问题请进一步沟通
