### ISSUE TITLE
spring boot 1.5.9中 isAnyEmpty方法找不到

### ISSUE THREAD

**Issue by china-coder** [binarywang/WxJava#421]
spring boot 1.5.9 release版本中 isAnyEmpty方法找不到，

**Comment by binarywang** [comment]
这跟sping boot没关系，看名字应该是commons-lang3里的StringUtils的方法，自己核对下版本

**Comment by china-coder** [comment]
嗯嗯，是这样的，1.5.9中的lang3版本有点低
