### ISSUE TITLE
微信公众号：调用获取带参数二维码或获取用户基本信息接口，偶尔会发生请求挂起状态

### ISSUE THREAD

**Issue by JYFengGo** [binarywang/WxJava#422]
调用获取带参数二维码或获取用户基本信息接口，偶尔会发生请求挂起状态，本人所在公司的生产环境有7台服务器，刚开始部署时，发现报证书问题，然后导入了微信的证书就没问题了，接着，发生了七台服务器中某一台机器的获取带参数二维码或获取用户基本信息接口发现挂起来，但授权那些接口就没问题，挂着请求，其他用户访问不了，又没有错误日志打印，这个请求挂起状态是随机发生的，七台随机有一辆台会这样，但重启了服务器就没问题，纳闷，找不到原因。。。在本地开发和测试环境测试是没问题，上到生产环境遇到这样的问题。不清楚授权、获取accesstoken接口会不会出现这样的问题。。。

**Comment by binarywang** [comment]
很神奇的问题，目前找到原因了吗？

**Comment by binarywang** [comment]
没有进一步的消息，暂时关闭
