### ISSUE TITLE
小程序客服消息新增图文链接消息和卡片类型

### ISSUE THREAD

**Issue by Yuanwe** [binarywang/WxJava#425]
小程序客服消息目前新增了图文链接消息，望更新
https://www.w3cschool.cn/weixinapp/weixinapp-api-custommsg-conversation.html
官方没找到文档，图文链接消息接口参数如下
{

    "touser": "OPENID",
    "msgtype": "link",
    "link": {
          "title": "Happy Day",
          "description": "Is Really A Happy Day",
          "url": "URL",
          "thumb_url": "THUMB_URL"
    }
}

**Comment by kareanyi** [comment]
官方文档地址如下
https://mp.weixin.qq.com/debug/wxadoc/dev/api/custommsg/receive.html#%E8%BF%9B%E5%85%A5%E4%BC%9A%E8%AF%9D%E4%BA%8B%E4%BB%B6
除了楼上的图文链接消息，现在还多了一个小程序卡片

**Comment by binarywang** [comment]
文档地址应该是这个：https://mp.weixin.qq.com/debug/wxadoc/dev/api/custommsg/conversation.html

**Comment by binarywang** [comment]
2.9.6.BETA测试版本已添加支持
