### ISSUE TITLE
下载媒体文件实现上有点小瑕疵

### ISSUE THREAD

**Issue by w41ter** [binarywang/WxJava#427]
https://github.com/Wechat-Group/weixin-java-tools/blob/c482443f8b6ee564efbe3fc5b2ea919b3412ec64/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/http/jodd/JoddHttpMediaDownloadRequestExecutor.java#L61

`createTmpFile` 内部是没有为后缀加上 . 的策略的，`FilenameUtils.getExtension` 只会返回不包含点的后缀，比如".speex"只返回"speex"，那么最后生成的文件名就会类似于：`prefix + random number + suffix with out dot`，比如 "a.speex" 会生成"a123speex"。

正好用到了一个根据后缀判断文件 MINE 类型的三方服务，才发现了这个问题。

**Comment by w41ter** [comment]
不知道加上给自定义文件名的支持怎么样？

**Comment by binarywang** [comment]
感谢提出此问题，请问你说的自定义文件名是什么意思？
另外，这里的文件其实只是一个临时文件，系统重启或者jvm退出后会被自动清理掉，因此建议不要直接使用，可以自行另存再使用。

**Comment by w41ter** [comment]
@binarywang 原来这些文件会被自动清理掉，那就没必要有什么自定义文件名了，感谢大大解答。

**Comment by binarywang** [comment]
不过我还是顺便把.加上了

**Comment by binarywang** [comment]
另外，`me.chanjar.weixin.common.util.fs.FileUtils#createTmpFile(java.io.InputStream, java.lang.String, java.lang.String, java.io.File)` 我看了此方法，点号的添加逻辑是有的啊，不知道你说了半天，是不是说错了地方？

**Comment by w41ter** [comment]
@binarywang  不好意思哈，是 OkHttp 的实现里，放错了链接。
    
https://github.com/Wechat-Group/weixin-java-tools/blob/696ffdc094119ec5ec15293091e0d56914f12197/weixin-java-common/src/main/java/me/chanjar/weixin/common/util/http/okhttp/OkHttpMediaDownloadRequestExecutor.java#L59

此处用了 File.createTmpFile ，我想应该是手误？

**Comment by binarywang** [comment]
收到，有空顺手就修复了
