### ISSUE TITLE
weixin-java-miniapp 2.9.0版本中WxMaMessage少了MsgType属性

### ISSUE THREAD

**Issue by foreach03** [binarywang/WxJava#429]
https://mp.weixin.qq.com/debug/wxadoc/dev/api/custommsg/receive.html#%E6%8E%A5%E6%94%B6%E6%B6%88%E6%81%AF%E5%92%8C%E4%BA%8B%E4%BB%B6
在进入客服会话时会产生
{
    "ToUserName": "toUser",
    "FromUserName": "fromUser",
    "CreateTime": 1482048670,
    "MsgType": "event",
    "Event": "user_enter_tempsession",
    "SessionFrom": "sessionFrom"
}
而在WxMaMessage对应的属性为MsgDataFormat

**Comment by binarywang** [comment]
2.9.5.BETA版本已添加
