### ISSUE TITLE
获取小程序二维码接口47001

### ISSUE THREAD

**Issue by geckhan** [binarywang/WxJava#444]
我debug到QrCodeRequestExecutor里发现， content-type 为text/plain; chars et=ISO-8859-1 并且对象（AbstractWxMaQrcodeWrapper ticket）没有json化  
不知道是我用法有问题还是微信更新了？请原作者回复

**Comment by binarywang** [comment]
最新测试版已修复

**Comment by geckhan** [comment]
赞 ~ 麻烦提供一下版本号

**Comment by binarywang** [comment]
已在项目首页列出，请前往查看

**Comment by geckhan** [comment]
好的 多谢~~

**Comment by rchlz** [comment]
似乎在2.9.0中这个bug还是存在的？

**Comment by binarywang** [comment]
说的是测试版，楼上的兄弟

**Comment by china-qd** [comment]
我开了一个新的问题：https://github.com/Wechat-Group/weixin-java-tools/issues/508
