### ISSUE TITLE
多个公众号支持，请求建议

### ISSUE THREAD

**Issue by gary-dgc** [binarywang/WxJava#445]
多个公众号，使用同一个后台提供服务，发现WxMpMessageRouter中初始化了WxMpService，为了在运行期可以获得正确的WxMpInMemoryConfigStorage，计划使用ThreadLocal在WxMpService中保存公众号的配置信息，但是发现RouterRule是支持async的，这样就无法使用ThreadLocal了。
哪位遇过类似问题，给些建议！
PS:不打算每个公众号一个Router，那样有些浪费

**Comment by Tockey007** [comment]
我目前也有这方面需求，不知楼上的哥们实现了吗？

**Comment by shengxiluo20** [comment]
可以看一下这个,主要的实现逻辑是实现mpservice多例 ,   https://github.com/shengxiluo20/wechat_mulit

**Comment by izerui** [comment]
我重新实现了一套基于企业微信的starter。 可以参考这个思路来搞，只需要一个单例service 即可。

https://github.com/izerui/work-weixin-spring-boot
