### ISSUE TITLE
增加对 境外商户专用报关接口 的支持

### ISSUE THREAD

**Issue by zhoujiongbin** [binarywang/WxJava#447]
希望增加对 报关借口 的支持

**Comment by binarywang** [comment]
文档地址？

**Comment by zhoujiongbin** [comment]
@binarywang 文档地址：
https://pay.weixin.qq.com/wiki/doc/api/external/declarecustom.php?chapter=18_1

**Comment by binarywang** [comment]
你要是不贴这个文档地址，真心不知道是什么东西。
境外服务商，这个很少有人用吧，你能否仿照目前代码提供个实现？
否则我们其他人没账号的，即使实现了也没法调试的。

**Comment by zhoujiongbin** [comment]
相对其他场景,这个报关的场景是比较少的，大多还是会用第三方支付来实现。我到时提交一下代码。

**Comment by binarywang** [comment]
那就期待你的PR了，多谢~

**Comment by binarywang** [comment]
不知道楼主有啥进展了?

**Comment by binarywang** [comment]
暂时关闭，如果楼主有兴趣提交PR，请随时提交，多谢了

**Comment by binarywang** [comment]
重复 #1678
