### ISSUE TITLE
企业付款到余额签名问题

### ISSUE THREAD

**Issue by li-dapeng** [binarywang/WxJava#448]
WxPayConfig设置了signType时，wxPayService.entPay接口会报SING_ERROR，签名错误，需要修改WxEntPayRequest的isIgnoreSignType为true。

**Comment by binarywang** [comment]
多谢及时提出此问题，抽空做个验证

**Comment by binarywang** [comment]
此问题已修复，使用2.9.6.BETA版本即可

**Comment by binarywang** [comment]
请注意，方法有所调整，使用方法 请参考`weixin-java-pay/src/test/java/com/github/binarywang/wxpay/service/impl/EntPayServiceImplTest.java` 单元测试文件
