### ISSUE TITLE
当支付成功或失败后没有给微信系统发送信息的接口

### ISSUE THREAD

**Issue by sunronsoft** [binarywang/WxJava#45]
支付成功或失败后，没有相关的方法给微信（财付通）系统发送成功或失败的信息，导致连续接收5次回调的信息。

//给财付通系统发送成功信息，财付通系统收到此结果后不再进行后续通知
resHandler.sendToCFT("success");

//给财付通系统发送失败信息，财付通系统收到此结果后不再进行后续通知
resHandler.sendToCFT("fail");

**Comment by binarywang** [comment]
@sunronsoft  感谢提出这个问题，不过不好意思，对支付不太了解，请问你是在使用什么接口，什么操作情况下出现的此问题，如有可能提供下详细的可以用来修复的代码，多谢~

**Comment by buyijiuyang** [comment]
支付成功或者失败后，直接在回调地址里面返回SUCCESS 或者 fail就好，没必要写一个方法

**Comment by binarywang** [comment]
@sunronsoft 请问楼上是否能解决你的问题？如果解决了就关闭issue吧
