### ISSUE TITLE
使用WxMpMaterialService上传语音(超过40s)成功，android播放正常，但在IOS端播放全是杂音

### ISSUE THREAD

**Issue by coverxiaoeye** [binarywang/WxJava#454]
问题描述：
首先通过WxMpMaterialService在后台java中将语音文件（长度超过40s）上传到微信，上传成功。
然后在前端H5页面根据mediaId首先下载得到localId，然后通过localId播放该语音。
经过测试发现”Android播放正常，但在IOS端播放全是杂音”。

具体代码示例如下：
上传语音:
File file=new File("E:\\voice\\test.amr");
WxMediaUploadResult res = wxMpService.getMaterialService().mediaUpload(WxConsts.MediaFileType.VOICE,file);
System.out.println(res.toString());
前端下载语音：
wx.downloadVoice({
      serverId: voice.serverId,
      success: function (res) {
         voice.localId = res.localId;
      }
    });
前端播放语音：
wx.playVoice({
      localId: voice.localId
});

**Comment by binarywang** [comment]
据别人说是ios不支持amr文件导致的，仅供参考
