### ISSUE TITLE
2.9版本的weixin-java-cp要用什么版本的weixin-java-common?

### ISSUE THREAD

**Issue by chrisjianghp** [binarywang/WxJava#455]
2.9版本的me.chanjar.weixin.cp.api.impl.WxCpServiceApacheHttpClientImpl调用的WxError的getErrorCode方法，但是2.9版本的common里面的WxError类并没有这个方法

是要用之前的版本吗？

**Comment by binarywang** [comment]
使用了lombok，先了解下这个东西吧

**Comment by chrisjianghp** [comment]
已解决，感谢
