### ISSUE TITLE
企业号部门管理获取部门列表接口支持不够完善

### ISSUE THREAD

**Issue by xaasu** [binarywang/WxJava#456]
https://qyapi.weixin.qq.com/cgi-bin/department/list?access_token=ACCESS_TOKEN&id=ID

WxCpDepartmentService.listAll();获得是所有部门

**Comment by binarywang** [comment]
请看官方文档，http://qydev.weixin.qq.com/wiki/index.php?title=%E7%AE%A1%E7%90%86%E9%83%A8%E9%97%A8
官方没提供的接口，我们也无法实现

**Comment by xaasu** [comment]
@binarywang  官方api是可以传参数id的，获取部门及其子部门接口，但您这边提供的关于部门查询的只有一个listAll()接口，所以我觉得有必要添加一个根据id查询部门及其子部门的接口

**Comment by binarywang** [comment]
那可能是之前没有这个参数，没注意，以后可以加一下

**Comment by binarywang** [comment]
2.9.9.BETA版本已优化
