### ISSUE TITLE
公众号 jssdk 支付

### ISSUE THREAD

**Issue by wangchen1206** [binarywang/WxJava#461]
我测试了 发现
case TradeType.JSAPI: {
String signType = SignType.MD5;
WxPayMpOrderResult payResult = WxPayMpOrderResult.builder()
.appId(unifiedOrderResult.getAppid())
.timeStamp(timestamp)
.nonceStr(nonceStr)
.packageValue("prepay_id=" + prepayId)
.signType(signType)
.build();

    **payResult.setPaySign(
      SignUtils.createSign(
        payResult,
        signType,
        this.getConfig().getMchKey(),
        false)**
    );
这段代码 生成sign Object转换为Map的时候 只剩下一个参数 package 了 这里导致签名不正确

**Comment by binarywang** [comment]
不知道你用的什么版本，请使用最新测试版看是否还存在问题

**Comment by wangchen1206** [comment]
用的 2.9.0 版本

**Comment by wangchen1206** [comment]
应该是最新的版本了吧

**Comment by binarywang** [comment]
那是最新正式版，但还有最新测试版
