### ISSUE TITLE
生产小程序码报错

### ISSUE THREAD

**Issue by shuangzhi** [binarywang/WxJava#464]
【请求地址】: https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=xxx
【请求参数】：WxMaWxcodeLimit(scene=15274970226, page=pages/recommend/recommend, width=430, autoColor=true, lineColor=null)
【错误信息】：{"errcode":47001,"errmsg":"data format error hint: [JgToTA03064530]"}

**Comment by binarywang** [comment]
这个错误早就修复了，请查阅其他人发的issue，使用最新测试版本即可
