### ISSUE TITLE
用mybatis的mapper文件实现数据库存储token？

### ISSUE THREAD

**Issue by braydenwong** [binarywang/WxJava#467]
继承了WxMpInMemoryConfigStorage后，无法使用autowire注入dao啊，我的mybatis是用mapper文件实现dao接口的，要怎么做比较好呢？只能用原始JDBC的方式吗？或者有没比较好的数据库实现？

**Comment by cashlifei** [comment]
我采用的是SpringMVC，文件配置基本的，用@PostConstruct在项目初始化后通过DAO进行数据库方式的持久化。你这种方式可能会报空指针错误。

**Comment by binarywang** [comment]
无法使用autowired的问题，请参考demo。
另外不建议使用数据库存储token，建议使用redis

**Comment by gclsoft** [comment]
@binarywang   
redis数据丢失了怎么办? 重启linux导致redis数据少了很多

**Comment by 1160817999** [comment]
@gclsoft  知道为什么建议使用redis持久化吗？

**Comment by binarywang** [comment]
> 少了

redis里的数据你也可以设置持久化到硬盘

**Comment by binarywang** [comment]
> @binarywang redis数据丢失了怎么办? 重启linux导致redis数据少了很多

redis里的数据你也可以设置持久化到硬盘

**Comment by binarywang** [comment]
> @gclsoft 知道为什么建议使用redis持久化吗？

性能比数据库要好
