### ISSUE TITLE
公众号支付

### ISSUE THREAD

**Issue by wanghao0807** [binarywang/WxJava#469]
用了最新测试版2.9.6.BETA，还是一样的错误，提示签名验证失败（只要使用了红包等优惠折扣方式）
![image](https://user-images.githubusercontent.com/18650761/36524518-387a5a56-17e1-11e8-8c45-a8184156622c.png)

**Comment by binarywang** [comment]
这代码看着象是你自己写的吧？

**Comment by wanghao0807** [comment]
照着慕课网上的课程写的啊

发自我的 iPhone

**Comment by wanghao0807** [comment]
之前都没问题，就是最近有个微信支付到店红包，只要使用这个红包就有问题，不使用这个红包也没问题

发自我的 iPhone

**Comment by binarywang** [comment]
那跟最新测试版2.9.6.BETA有什么关系？

**Comment by wanghao0807** [comment]
是你上次让我用最新测试版试试看啊，你把之前那个关了

发自我的 iPhone

**Comment by binarywang** [comment]
我的意思是，我看你的代码异常堆栈里的最终类并不是我们这个sdk里的代码，所以我要问你你的代码跟最新版有关系吗？或者说你是复制代码出来的？

**Comment by binarywang** [comment]
楼主，你的问题解决了吗？如果有问题，请下次再提问时尽量描述清楚，谢谢

**Comment by binarywang** [comment]
还有，不知道你为什么提到慕课网的东西，跟我们这个sdk有关系？能否提供下你所参照的课程地址？
