### ISSUE TITLE
上传多媒体文件时临时文件清理问题

### ISSUE THREAD

**Issue by xiaoshua** [binarywang/WxJava#471]
我们在接入weixin-java-mp后, 发现线上机器的tmp目录越来越大, 最终导致空间不够用. 经过排查, 是由于我们上传多媒体文件时产生的临时文件没有及时清理造成的, 对应代码方法: me.chanjar.weixin.mp.api.impl.WxMpMaterialServiceImpl#mediaUpload(java.lang.String, java.lang.String, java.io.InputStream), WxMpMaterialServiceImpl第38行. 在这边, 根据inputStream生成的tmpFile在使用完之后没有及时删除. 文件夹列表截图如下:
![image](https://user-images.githubusercontent.com/5337068/36627424-717b29c8-197d-11e8-892a-3fd8fe7f658c.png)
作者能否考虑优化一下, 谢谢!

**Comment by binarywang** [comment]
这个我记得在关闭虚拟机会自动清理吧，如果长时间没重启，那你们得考虑在系统层面所设置了，比如定期清理比较早的临时文件。

**Comment by xiaoshua** [comment]
嗯, 在关闭虚拟机的时候是会自动清理的. 在正常的情况下, 我们的虚拟机只要稳定, 没有出现意外是不会重启的. 正常的业务迭代上线也只是相当于重启java进程. 如果代码上不做清理的话, 那我们也只能写脚本定时清理了 - -

**Comment by binarywang** [comment]
我又仔细看了下，你这个问题是上传时候发生的情况，有必要做个处理，就是上传完后立即删除临时文件，因为确实没有存储的必要。

**Comment by binarywang** [comment]
2.9.8.BETA版本已修复

**Comment by xiaoshua** [comment]
非常感谢, 等正式版发布我们就马上升级.

**Comment by zhaojp0411** [comment]
为什么 4.3.8.B 版本还出现这个问题
