### ISSUE TITLE
WxMpKfAccountRequest 没有构造函数

### ISSUE THREAD

**Issue by vancalcode** [binarywang/WxJava#473]
希望增加构造函数如下，方便作为 requestParam 参数调用。
public WxMpKfAccountRequest(String kfAccount, String nickName, String inviteWx) {
    this.kfAccount = kfAccount;
    this.nickName = nickName;
    this.inviteWx = inviteWx;
  }

**Comment by binarywang** [comment]
不建议使用构造方法构造，现在所有的bean类都已经支持builder方法构造

**Comment by binarywang** [comment]
按如下方式使用即可：
```
WxMpKfAccountRequest.builder().inviteWx(...).kfAccount(...).nickName(...).build();
```
