### ISSUE TITLE
2.8.0版本死锁问题

### ISSUE THREAD

**Issue by nullsz** [binarywang/WxJava#475]
WxMpServiceAbstractImpl中的executeInternal方法使用了synchronized ， WxMpServiceApacheHttpClientImpl中的getAccessToken中使用了Lock accessTokenLock = new ReentrantLock()；会发生死锁的问题，可以将synchronized去掉！

Found one Java-level deadlock:
=============================
"http-nio-8080-exec-201":
  waiting for ownable synchronizer 0x00000000943395d0, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "http-nio-8080-exec-10"
"http-nio-8080-exec-10":
  waiting to lock monitor 0x00007f92e40b3208 (object 0x00000000943393a0, a me.chanjar.weixin.mp.api.impl.WxMpServiceImpl),
  which is held by "http-nio-8080-exec-4"
"http-nio-8080-exec-4":
  waiting for ownable synchronizer 0x00000000943395d0, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "http-nio-8080-exec-10"

**Comment by binarywang** [comment]
新版本早已去掉
