### ISSUE TITLE
修复公众号模板消息发送时pagepath问题

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#479]
https://mp.weixin.qq.com/wiki?action=doc&id=mp1433751277&t=0.8724972468714212#5
官方接口文档中的参数名称错误（文档中为 pagepath，实际应为 path）

**Comment by binarywang** [comment]
2.9.8.BETA版本已修复

**Comment by vekbug** [comment]
https://mp.weixin.qq.com/wiki?action=doc&id=mp1433751277&t=0.8724972468714212#5
现在模板消息中小程序的 pagepath 得问题已经修正了，默认是不是要改成 pagepath 啊

**Comment by binarywang** [comment]
你这个看的不知道是哪一年的代码，很老了，你看下现在的代码是什么？

**Comment by oubeichen** [comment]
https://github.com/Wechat-Group/WxJava/blob/06085f0a1ac53ef66f9cc6e23a638d807063a967/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/bean/template/WxMpTemplateMessage.java#L86

我看了默认 usePath 是 True，而现在应该是用 pagepath，这个参数应该默认是 False 才好。

**Comment by binarywang** [comment]
> https://github.com/Wechat-Group/WxJava/blob/06085f0a1ac53ef66f9cc6e23a638d807063a967/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/bean/template/WxMpTemplateMessage.java#L86
> 
> 我看了默认 usePath 是 True，而现在应该是用 pagepath，这个参数应该默认是 False 才好。

那你自己手动赋值就可以了，这个微信变来变去真不好说哪天又变了
