### ISSUE TITLE
me.chanjar.weixin.mp.api.WxMpInMemoryConfigStorage#accessTokenLock空指针问题

### ISSUE THREAD

**Issue by 627535195** [binarywang/WxJava#485]
XStream在做xml反序列化时，如果xml中没有对应属性的话，会将bean中已经有的属性设置成null。
所以me.chanjar.weixin.mp.api.WxMpInMemoryConfigStorage#accessTokenLock此处的锁会是空的。
处理办法：me.chanjar.weixin.common.util.xml.XStreamInitializer#getInstance 在该方法初始化Xstream时，加入PureJavaReflectionProvider
![image](https://user-images.githubusercontent.com/18624394/37146640-4d20c458-22ff-11e8-84c2-f416c93faed5.png)

**Comment by binarywang** [comment]
#487 已修复

**Comment by binarywang** [comment]
2.9.8.BETA版本已修复
