### ISSUE TITLE
[Miniapp] 现在 jscode2session 不会返回 expires_in 字段了

### ISSUE THREAD

**Issue by blade254353074** [binarywang/WxJava#490]
![image](https://user-images.githubusercontent.com/9346008/37238286-d992f640-245d-11e8-8e8e-22abbc6d9724.png)

**Comment by binarywang** [comment]
谢谢及时指出，具体文档地址： https://mp.weixin.qq.com/debug/wxadoc/dev/api/api-login.html#wxloginobject

**Comment by binarywang** [comment]
2.9.8.BETA版本已修复
