### ISSUE TITLE
@Autowired  出错

### ISSUE THREAD

**Issue by namezhouyu** [binarywang/WxJava#492]
.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'cn.binarywang.wx.miniapp.api.WxMaService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

**Comment by binarywang** [comment]
请参考demo，并学习下spring相关基础知识
