### ISSUE TITLE
企业微信增加第三方应用开发接口的支持

### ISSUE THREAD

**Issue by mywsat** [binarywang/WxJava#493]
https://work.weixin.qq.com/api/doc#90001/90142/90594

**Comment by binarywang** [comment]
这个跟 #203 感觉是同一个问题

**Comment by mog0202** [comment]
和 #203 确实是一样的，希望有时间和精力的人搞下这块。

**Comment by kellysupeng** [comment]
期待企业微信第三方开放接口支持

**Comment by eanfs** [comment]
期待企业微信第三方开放接口支持

**Comment by binarywang** [comment]
3.4.1.B测试版本 已支持，欢迎各位试用
