### ISSUE TITLE
weixin-java-open-demo全网发布测试用例不通过

### ISSUE THREAD

**Issue by TonyLuo** [binarywang/WxJava#494]
尝试了两次全网发布，结果如下：
第一次：返回Api文本消息和发送事件消息失败
第二次：返回普通文本消息和发送事件消息失败

名称	状态
[组件ticket正确接收]	成功
[生成预授权码]	成功
[获取授权code]	成功
[授权]	成功
[返回Api文本消息]	失败
[返回普通文本消息]	成功
[发送事件消息]	失败
[取消授权]	成功

名称	状态
[组件ticket正确接收]	成功
[生成预授权码]	成功
[获取授权code]	成功
[授权]	成功
[返回Api文本消息]	成功
[返回普通文本消息]	失败
[发送事件消息]	失败
[取消授权]	成功

**Comment by binarywang** [comment]
demo问题最好到对应项目下提出吧，谢谢了

**Comment by TonyLuo** [comment]
我也想到对应的demo项目下提问题，但weixin-java-open-demo这个项目没有issue这个tab

**Comment by binarywang** [comment]
刚刚打开了，不知道之前为啥没开放

**Comment by 007gzs** [comment]
这个你把你自己的appid加到demo里，然后发送下消息和事件测试下返回,
`StringUtils.equalsAnyIgnoreCase(appId, "wxd101a85aa106f53e", "wx570bc396a51b8ff8", "你的appid")) `
