### ISSUE TITLE
公众号发模版消息一直报invalid ip，加了白名单也没用，curl测试是没问题的

### ISSUE THREAD

**Issue by xuyu** [binarywang/WxJava#495]
问题描述：

使用weixin-java-mp发送模版消息在本机和青云的测试机上都是没问题的，但是在客户的服务器上就一直报invalid ip，然后根据返回的错误信息里的ip地址加了白名单也还是报这个错。但在命令行用curl测试获取AccessToken和发模版消息都是没问题的，用HttpClient也了个Demo程序获取AccessToken然后调用发送模版消息接口也是没问题的，用了库里面的getTemplateMsgService().sendTemplateMsg就一直报这个错。

PS. 2.9.0 2.9.8.BETA 都试过，默认的ApacheHttpClientImpl和OkHttp也都试过

**Comment by binarywang** [comment]
现在好了吗？
你这属于配置问题，跟我们sdk没关系，所以换版本没什么区别

**Comment by xuyu** [comment]
先感谢回复。

最后发现确实是客户填错了公众号参数。
