### ISSUE TITLE
有没有搭建手册第一次学习，感谢

### ISSUE THREAD

**Issue by thewordofw** [binarywang/WxJava#496]

**Comment by SnailMann** [comment]
同求？有没有对应的API文档或则使用文档？

**Comment by binarywang** [comment]
注意看首页说明，有demo，也有文档

**Comment by SnailMann** [comment]
谢谢Binary的回复，我个人认为现有文档对初入微信平台开发的小伙伴，还是带有一定的门槛，希望大佬如果有时间的话，可能整理出更为系统性的文档。问一下，请问有相关的技术群吗？方便提问

**Comment by thewordofw** [comment]
谢谢，赞赞赞赞赞赞

**Comment by thewordofw** [comment]
谢谢，赞赞赞赞赞赞

**Comment by binarywang** [comment]
@SnailMann 首页有说明，请仔细阅读下

**Comment by binarywang** [comment]
@SnailMann 技术群请看首页说明，文档如果觉得那里不够清楚，可以帮忙维护添加完善下，非常感谢~
