### ISSUE TITLE
实现新版客服的各个接口

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#5]
接口文档地址 http://mp.weixin.qq.com/wiki/18/749901f4e123170fb8a4d447ae6040ba.html

**Comment by binarywang** [comment]
正在实现中

**Comment by binarywang** [comment]
客服管理的6个接口已完成

**Comment by kareanyi** [comment]
cool~

**Comment by binarywang** [comment]
会话管理的接口也已实现

**Comment by binarywang** [comment]
还有最后一个获取聊天记录的接口即将实现

**Comment by binarywang** [comment]
聊天记录的接口已实现，至此新版客服的所有接口已全部实现完成

**Comment by chenweiyj** [comment]
新版客服接口没有相关文档和示例，我找不到如何使用

**Comment by chenweiyj** [comment]
@binarywang

**Comment by binarywang** [comment]
抱歉，目前wiki上暂时没有编写相关文档，代码使用示例可以去查看对应类的单元测试

**Comment by chenweiyj** [comment]
@binarywang 哪个包下面是相关的类能指明一下吗？

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/blob/develop/weixin-java-mp/src/test/java/me/chanjar/weixin/mp/api/impl/WxMpKefuServiceImplTest.java
