### ISSUE TITLE
在创建菜单的接口传json生成子菜单的sub_button无法使用，改成subButtons可以

### ISSUE THREAD

**Issue by JohnsonYuYHao** [binarywang/WxJava#501]
menuCreate(@RequestBody WxMenu menu) ，这是demo中的接口， 出现错误的参数：
 
@SerializedName("sub_button")
  private List<WxMenuButton> subButtons = new ArrayList<>();

案例：
无法生效json：  
     "name":"服务指南",
           "sub_button":[
           {    
               "type":"view",
               "name":"课程安排",
               "url":"” }]
可以生效json：

      "name":"服务指南",
           "subButtons":[
           {    
               "type":"view",
               "name":"课程安排",
               "url":"” }]

**Comment by binarywang** [comment]
你的问题属于对应demo的问题，涉及到对应demo使用的json解析框架的使用问题，自己注意就可以了
