### ISSUE TITLE
从token中心走缓存获取token，重写WxMpServiceApacheHttpClientImpl下getAccessToken方法，token不断获取导致失效

### ISSUE THREAD

**Issue by mylifeonmars** [binarywang/WxJava#502]
org.apache.http.conn.ConnectTimeoutException: Connect to api.weixin.qq.com:443 [api.weixin.qq.com/101.226.212.27, api.weixin.qq.com/101.227.162.120] failed: Connection timed out

具体该怎么实现？
WxMpInMemoryConfigStorage与WxMpInRedisConfigStorage的具体使用方法，会对上述问题有帮助吗

**Comment by binarywang** [comment]
你这个问题需要修改超时时间设置，具体参考wiki首页相关内容
