### ISSUE TITLE
提醒一下：微信官方获取头像的路径有调整了

### ISSUE THREAD

**Issue by libran7** [binarywang/WxJava#506]
微信官方说明：https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11518160281tmq6P&version=&lang=zh_CN

**Comment by 007gzs** [comment]
返回格式没变，只是内容里域名变了，业务层重新请求就可以

**Comment by binarywang** [comment]
确实，自己留意即可
