### ISSUE TITLE
建议新增电子发票模块

### ISSUE THREAD

**Issue by wishflyer** [binarywang/WxJava#507]
微信公众号已新增如下新模块（电子发票）
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=21512641124u4O1R

建议新增相应模块的内容，谢谢~

**Comment by binarywang** [comment]
接口还不少，希望有正在使用需求的人帮忙实现下

**Comment by lapDog** [comment]
oh...man,有新接口用了嘛?

**Comment by binarywang** [comment]
没

**Comment by heyucong** [comment]
这个好，使用电子发票的越来越多了。。。

**Comment by lapDog** [comment]
@heyucong 在3.2基础上我已经实现了部分电子发票功能。科科科，看你貌似是同行啊。。

**Comment by binarywang** [comment]
自己实现了，可以提交PR啊

**Comment by heyucong** [comment]
@lapDog 感谢感谢，自己收过不少电子票，也有客户有这样的要求，毕竟电子票是潮流，可以减少社会成本，以前要靠快递寄，现在只需要在完成消费后申请电子票即可自己打印。。。

**Comment by binarywang** [comment]
> @heyucong 在3.2基础上我已经实现了部分电子发票功能。科科科，看你貌似是同行啊。。

@lapDog  如果可以，可否提交你的代码上来？非常期待
