### ISSUE TITLE
@Data注解，影响到了请求的数据

### ISSUE THREAD

**Issue by china-qd** [binarywang/WxJava#508]
比如下面这个类，在请求接口里entity使用了AbstractWxMaQrcodeWrapper#toString，但是加上了@Data，序列化就不再是JSON了，请求也就出现了错误47001
`@Data
@EqualsAndHashCode(callSuper = false)
public class WxMaWxcodeLimit extends AbstractWxMaQrcodeWrapper`

见下面的commit:
使用lombok的@Data注解简化miniapp模块的所有bean类
e007a13df6aa6578ff4b4529f8573a64a7f4b319

**Comment by china-qd** [comment]
建议用@Setter @Getter取代@Data，影响范围，所有使用toString序列化为请求内容的实体

**Comment by binarywang** [comment]
感谢提出建议，不过相关问题早已修复，转换json使用新方法，不再依赖toString方法

**Comment by china-qd** [comment]
https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/util/http/QrCodeRequestExecutor.java
43行
httpPost.setEntity(new StringEntity(ticket.toString()));

**Comment by binarywang** [comment]
不要看master分支，那是比较老的代码
