### ISSUE TITLE
网页授权的两种scope能否添加枚举常量

### ISSUE THREAD

**Issue by AaricChenLegacy** [binarywang/WxJava#509]
```
public interface WxMpService {
    String oauth2buildAuthorizationUrl(String redirectURI, String scope, String state);
}
```

这里的接口的第二个参数能否改为枚举类型 
  **snsapi_base**
  **snsapi_userinfo**

**Comment by binarywang** [comment]
现在是有常量类的`me.chanjar.weixin.common.api.WxConsts.OAuth2Scope`，改枚举就没觉得有必要了，毕竟最开始是这么设计的，影响范围过大
