### ISSUE TITLE
不能自动回复消息

### ISSUE THREAD

**Issue by shuhan-happy** [binarywang/WxJava#510]
这个是我配置的router信息
router.rule().async(false).msgType(WxConsts.XmlMsgType.TEXT).handler(testHandler).end();
只要在配置了.async(false)的时候，给公众号发送消息才会收到回复。请问下不加这个为什么收不到，是权限问题，还是我代码问题呢。

还有一个问题就是，用户发送一条信息，我能同时回复一张图片和一个文字么？

**Comment by binarywang** [comment]
1. 先理解async的含义，是设置是否异步执行的意思；
2. 同步回复只有一个，但是你可以通过客服消息或者模版消息回复更多的

**Comment by braydenwong** [comment]
@binarywang 其实我也想知道异步执行的运用场景，因为好像只有设置成async(false)的时候公众号才会回复用户。

**Comment by binarywang** [comment]
async是异步的意思，async(false)就是非异步的意思，即同步，就是直接给你回复消息的意思，异步就是通过单开独立线程进行其他操作，详细可以阅读源码了解更深入内容。

**Comment by binarywang** [comment]
最常见的场景，比如就是你可以记录日志（可能会比较耗时，比如如果存到数据库里的话），或者通知其他系统进行出处理等，而不至于阻塞当前线程

**Comment by aixiaotan** [comment]
关闭
