### ISSUE TITLE
当增加miniapp时运行正常，增加pay支付模块后出现以下错误

### ISSUE THREAD

**Issue by Doubletreelin** [binarywang/WxJava#511]
Description:

Parameter 0 of method wxMaService in com.bani.cloud.api.config.WxMaConfiguration required a bean of type 'cn.binarywang.wx.miniapp.config.WxMaConfig' that could not be found.

Action:

Consider defining a bean of type 'cn.binarywang.wx.miniapp.config.WxMaConfig' in your configuration.

**Comment by binarywang** [comment]
是你自己使用demo出现的问题，应该是config名字冲突，你需要自己修改一下，避免冲突

**Comment by Doubletreelin** [comment]
Ok，解决了，thanks
