### ISSUE TITLE
小程序新增获取微信用户绑定手机号信息的解密方法

### ISSUE THREAD

**Issue by rogerluoz** [binarywang/WxJava#515]
文档地址：https://mp.weixin.qq.com/debug/wxadoc/dev/api/getPhoneNumber.html
希望增加谢谢！

**Comment by binarywang** [comment]
看文档并不是后端接口，无法添加。你是否仔细阅读了文档？

**Comment by binarywang** [comment]
要么你的意思是想通过后端代码，解析加密数据？这可以通过自己调用相应方法即可解决。

**Comment by rogerluoz** [comment]
恩是的，我现在是直接调用解密方法实现了，不过我觉得可以增加一个像WxMaUserService.getUserInfo() 方法那样可以直接调用就更方便了。

**Comment by binarywang** [comment]
那可以加一个吧，你可以把你的方法贡献出来吧，既然你做好了的

**Comment by binarywang** [comment]
3.0.0版本已添加相关方法
