### ISSUE TITLE
建议新增公众平台的 WiFi 门店管理的相关接口

### ISSUE THREAD

**Issue by ymsmile** [binarywang/WxJava#516]
我是后台开发的初学者，非常感谢这个库，感谢你们的分享。

到今天，我艰难的完成了开放平台的微信授权功能，历时10天，可以说是步履维艰。

我的终极目标是实现微信连 WiFi 的功能，我看了一遍 api 后发现没有 WiFi 门店管理的相关接口。遂建议加上此功能。

**Comment by binarywang** [comment]
最好发下文档地址，后续如果有空可以添加

**Comment by ymsmile** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444894090
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444894115
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457435331

**Comment by binarywang** [comment]
- 获取Wi-Fi门店列表 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444894115
- 查询门店Wi-Fi信息 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457435331
- 修改门店网络信息 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457435413
- 清空门店网络及设备 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457435430
- 添加密码型设备 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444894120
- 添加portal型设备 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457443857
- 查询设备 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457443871
- 删除设备 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1457443872
- 获取物料二维码 https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444894125

**Comment by ymsmile** [comment]
大法好~感谢！

**Comment by binarywang** [comment]
还没做完呢，只做了一个接口，还有很多

**Comment by binarywang** [comment]
@ymsmile  还有哪些接口，请补充下，除了上面列的

**Comment by ymsmile** [comment]
@binarywang 我们的业务只用到了我列的那几个接口，其他的没用到。现在没在搞后台的了，写App去了，逃：（

**Comment by binarywang** [comment]
其他接口暂不实现，因为没多少人在用
