### ISSUE TITLE
DefaultApacheHttpClientBuilder.java 这个在实际生产环境中会导致大量的thread导致机器使用完线程死机

### ISSUE THREAD

**Issue by hacken2006** [binarywang/WxJava#52]
这是亲身经历。
prepare() 这个方法写的有问题，不停的加载创建thread，建议 构建方法中的配置等用静态提到构造函数中，我就这样解决的。

还有一个 路由的问题，路由方法也是 大量创建了thread，导致 thread只增加 不消除，我就直接把 thread取消了，就是那个  check duplicate 的吧，忘记了，如果不行 就用 线程池去做，不然不能用在生产环境中。很快机器就死

**Comment by binarywang** [comment]
@hacken2006 非常感谢提出这个问题，我们开发组会核实并想办法修复此问题的，如果有可能，你也可以加入，帮忙共同完善代码。

**Comment by hacken2006** [comment]
我的问题已经按上面的方式解决，这是前面几位出现宕机的根本原因，不是简单的sockettime问题

**Comment by binarywang** [comment]
@hacken2006  仔细看了下代码，没太看明白你的意思，请明示一下？觉得出现“不停的加载创建thread”的问题，或许跟你使用的方式有关系，你是如何使用相关接口代码的？

**Comment by bysunexus** [comment]
@hacken2006  麻烦问下在项目中me.chanjar.weixin.mp.api.impl.WxMpServiceImpl这个类是保持单例了么

**Comment by hacken2006** [comment]
多个应用 共用TOKEN,不可能单例

**Comment by binarywang** [comment]
@hacken2006  多个应用共用token是什么意思，保持单例会有什么问题，能否稍微展开说明一下？

**Comment by bysunexus** [comment]
@hacken2006 看了一下代码确实会有问题 我提交pr将prepare()方法修改到构造中执行
感谢反馈问题

如果有时间您也可以提交pr一起来维护本项目

**Comment by bysunexus** [comment]
prepare()方法修改到构造中将会导致,set到本类的属性失效.
现在将prepare调整为同步执行
