### ISSUE TITLE
微信支付 WxPayOrderNotifyResult 缺少 version 参数

### ISSUE THREAD

**Issue by wustrive2008** [binarywang/WxJava#521]
微信支付 WxPayOrderNotifyResult中缺少version参数，现在在WxPayUnifiedOrderRequest中有其他没有，开启营销功能时导致其他功能签名错误，如支付通知，查询等 版本3.0.0

**Comment by binarywang** [comment]
看了你的描述，感觉有点矛盾，到底是哪里有问题？https://pay.weixin.qq.com/wiki/doc/api/danpin.php?chapter=9_203&index=4 我看了文档，支付通知好像并没有version参数，难道是文档写错了？

**Comment by binarywang** [comment]
@wustrive2008 能否帮忙再次确认下？

**Comment by wustrive2008** [comment]
@binarywang 当使用代金券付款时，回调通知里有version:
`2018-04-27 14:59:59.223 [http-nio-8090-exec-3] DEBUG c.g.b.w.s.impl.WxPayServiceImpl - 微信支付异步通知请求参数：<xml>
<appid><![CDATA[wxc64778f27a34b755]]></appid>
<attach><![CDATA[0f3f1b3ff14b470da551f793e6e7cc6e]]></attach>
<bank_type><![CDATA[ICBC_CREDIT]]></bank_type>
<cash_fee><![CDATA[1]]></cash_fee>
<device_info><![CDATA[WEB]]></device_info>
<fee_type><![CDATA[CNY]]></fee_type>
<is_subscribe><![CDATA[Y]]></is_subscribe>
<mch_id><![CDATA[1405764302]]></mch_id>
<nonce_str><![CDATA[1524812391682]]></nonce_str>
<openid><![CDATA[oUWI8w1MkrmyK-mtAtNJTugVy4MM]]></openid>
<out_trade_no><![CDATA[18042714595159648623]]></out_trade_no>
<promotion_detail><![CDATA[{"promotion_detail":[{"promotion_id":"3173393261","name":"耳机满2.01减2","scope":"SINGLE","type":"DISCOUNT","amount":200,"activity_id":"6890525","wxpay_contribute":0,"merchant_contribute":200,"other_contribute":0,"goods_detail":[{"goods_id":"00515223730484091","quantity":1,"price":201,"discount_amount":200}]}]}]]></promotion_detail>
<result_code><![CDATA[SUCCESS]]></result_code>
<return_code><![CDATA[SUCCESS]]></return_code>
<sign><![CDATA[19799EDDE7DAA162A5FAC9E1201210C8]]></sign>
<time_end><![CDATA[20180427145959]]></time_end>
<total_fee>201</total_fee>
<trade_type><![CDATA[JSAPI]]></trade_type>
<transaction_id><![CDATA[4200000112201804276762108620]]></transaction_id>
<version><![CDATA[1.0]]></version>
</xml>`

错误信息：
2018-04-27 15:06:20.469 [http-nio-8090-exec-3] ERROR c.g.b.w.s.impl.WxPayServiceImpl - 参数格式校验错误！
com.github.binarywang.wxpay.exception.WxPayException: 参数格式校验错误！

**Comment by binarywang** [comment]
那就确实是官方文档有问题，稍后修复下

**Comment by binarywang** [comment]
3.0.6.BETA测试版本已修复
