### ISSUE TITLE
WxMpInRedisConfigStorage该如何使用？

### ISSUE THREAD

**Issue by aifuxun3** [binarywang/WxJava#522]
你好！请问我最近想使用集群环境，需要用到redis来操作，WxMpInRedisConfigStorage该如何使用，目前貌似文档查不到。

**Comment by binarywang** [comment]
暂时没有文档，实例化时补充必须参数即可

**Comment by aifuxun3** [comment]
请问使用WxMpInRedisConfigStorage,除了AppId，Secret，Token，还需要初始化哪些？

**Comment by aifuxun3** [comment]
WxMpInRedisConfigStorage也没支持集群的

**Comment by binarywang** [comment]
根据自己需要实现你所需要的实现类，这个redis的实现也仅是提供一个参考
