### ISSUE TITLE
请问我引入WxMaService失败的原因是什么

### ISSUE THREAD

**Issue by alexcdever** [binarywang/WxJava#524]
我使用gradle引入jar包的，如图：
![image](https://user-images.githubusercontent.com/14200813/38462411-72e23bd6-3b19-11e8-8286-6fd227ba02a7.png)
而在我自己的service实现类里autowired小程序的WxMaService时候代码没报错，如图：
![image](https://user-images.githubusercontent.com/14200813/38462423-a87e5202-3b19-11e8-9b0c-b7975bc7ac5d.png)
![image](https://user-images.githubusercontent.com/14200813/38462429-b82482d0-3b19-11e8-8877-089df2fef581.png)
然而在启动的时候报错了,如图：
![image](https://user-images.githubusercontent.com/14200813/38462452-07a0891c-3b1a-11e8-9ad1-4c9440c7bcce.png)
![image](https://user-images.githubusercontent.com/14200813/38462458-39e564ec-3b1a-11e8-87ee-dde27abf9325.png)

目前我怀疑是jar包引入不成功，因为yml文件里的配置的样式表明配置项解析不出来，如图:
![image](https://user-images.githubusercontent.com/14200813/38462495-a1026670-3b1a-11e8-9b9a-8fa3bc7af32d.png)
但是这里也说明的确是引入jar包了，如图：
![image](https://user-images.githubusercontent.com/14200813/38462500-c60195a4-3b1a-11e8-8363-bf63638ad67a.png)

所以请路过的大佬打救一下。。

**Comment by binarywang** [comment]
请参考demo，先将对应的bean加载到spring容器内，才可以使用autowired注解，这属于spring基础

**Comment by alexcdever** [comment]
之前只想着怎么用，没留意配置文件里的配置项是要自己手动获取。。
