### ISSUE TITLE
请问如何多点运行?

### ISSUE THREAD

**Issue by slin1972** [binarywang/WxJava#526]
如果我原本有一个服务 用来获取 accessToken 和 jsApiTicket  , 我如果将 weixin-java-tools 从微信获取accessToken 和 jsApiTicket 切换到 这个服务上, 且每次使用token都去获取,  不根据expire判断

**Comment by binarywang** [comment]
你可以实现自己的WxMpConfigStorage接口实现类，具体可以根据自己需要实现对应代码

**Comment by binarywang** [comment]
暂时关闭，如有问题进一步回复即可
