### ISSUE TITLE
EntPayBankRequest 缺少默认构造函数

### ISSUE THREAD

**Issue by leohsu91** [binarywang/WxJava#529]
kotlin下：
![image](https://user-images.githubusercontent.com/8965956/38487075-920c04f8-3c11-11e8-9311-c18e9708207a.png)

java下：
![image](https://user-images.githubusercontent.com/8965956/38487302-3f030fe4-3c12-11e8-9706-93356120ada6.png)

请增加@NoArgsConstructor 注解出个包吧

**Comment by leohsu91** [comment]
另外，EntPayBankResult 中cmmsAmount的数据类型应该是Int

**Comment by binarywang** [comment]
可以，谢谢指出

**Comment by binarywang** [comment]
3.0.1.BETA版本已添加
