### ISSUE TITLE
申请退款接口结果类 缺少单个代金券相关参数

### ISSUE THREAD

**Issue by aimilin6688** [binarywang/WxJava#530]
微信文档：[https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_4](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_4)
![_20180410121257](https://user-images.githubusercontent.com/3804814/38535896-a4d09f16-3cb8-11e8-9d12-5cb2ce18d1a6.png)

其中参数类型coupon_refund_fee_$n 这种类型的参数

**Comment by binarywang** [comment]
抽空核实下

**Comment by binarywang** [comment]
我看你发的地址是“申请退款”，
对应的类应该是`com.github.binarywang.wxpay.bean.result.WxPayRefundResult`

**Comment by binarywang** [comment]
3.0.3.BETA版本已添加
