### ISSUE TITLE
小程序 接收消息事件 WxMaMessage

### ISSUE THREAD

**Issue by dirtyman** [binarywang/WxJava#531]
关于小程序接收用户发过来的消息实体 WxMaMessage 现在不支持小程序卡片消息呢？Title，AppId，PagePath，ThumbUrl，ThumbMediaId 没有这几个字段

**Comment by binarywang** [comment]
请提供下对应文档地址

**Comment by binarywang** [comment]
文档地址：https://developers.weixin.qq.com/miniprogram/dev/api/custommsg/receive.html#小程序卡片消息

**Comment by binarywang** [comment]
3.0.3.BETA版本已添加
