### ISSUE TITLE
微信AI开放接口

### ISSUE THREAD

**Issue by haois** [binarywang/WxJava#532]
请问现在有实现这个功能吗
AI开放接口
微信AI开放接口介绍
微信AI接口由微信智聆语音团队、微信翻译团队与公众平台联合推出的AI开放接口，首期开放语音转文字、文本翻译接口，为开发者AI赋能。

语音转文字接口

提供中文普通话、英文语音转文字服务。

文本翻译接口

提供英汉、汉英文本翻译服务。

目标用户
公众号、小程序以及微信开放平台注册的APP。

使用样例
微信语音转文字

微信翻译

微信面对面翻译小程序

**Comment by binarywang** [comment]
没有，请提供相应文档地址，以后如有可能添加一下

**Comment by haois** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=21516712282KzWVE
在微信开发文档下的语义理解-AI开放接口
感谢您的开源

**Comment by binarywang** [comment]
调试了下这几个接口，感觉真的很垃圾，都在想有没有做的必要，文档写的烂不说，简单的几句话都识别不了，还好意思叫AI接口，醉了

**Comment by binarywang** [comment]
3.0.9.BETA测试版本已增加
