### ISSUE TITLE
微信刷卡支付请求类缺少字段

### ISSUE THREAD

**Issue by ZLQing** [binarywang/WxJava#533]
微信刷卡支付请求类中缺少字段
![image](https://user-images.githubusercontent.com/16550233/38609374-7746f75e-3db0-11e8-8fde-91b200c6209e.png)

请求类：
com.github.binarywang.wxpay.bean.request.WxPayMicropayRequest
微信刷卡支付文档地址：
https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=9_10&index=1

**Comment by binarywang** [comment]
抽空核实下

**Comment by binarywang** [comment]
核实发现，不仅少了这两个字段，还有一个scene_info

**Comment by binarywang** [comment]
3.0.2.BETA版本已增加
