### ISSUE TITLE
公众号发送模版消息中的小程序pagepath问题

### ISSUE THREAD

**Issue by jimmyking** [binarywang/WxJava#534]
#479 需要改回去。
微信已经修复了这个问题，参数与文档一致了。目前3.0版本的参数是path
文档：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277

**Comment by binarywang** [comment]
就是已经变回pagepath了？

**Comment by jimmyking** [comment]
是的。

**Comment by jundingzhou** [comment]
是的, 目前开发遇到这个问题, path的话跳转不到指定页面了, 必须用pagepath. 现在WxMpTemplateMessage 包了一层,在里面重写WxMpTemplateMessageGsonAdapter解决目前的问题.

**Comment by binarywang** [comment]
真够蛋疼

**Comment by binarywang** [comment]
3.0.2.BETA版本已修复

**Comment by binarywang** [comment]
据说现在又改回path了？谁能帮忙验证下？
