### ISSUE TITLE
小程序 发送客服消息 WxMaKefuMessage Gson 序列化Unicode转义字符

### ISSUE THREAD

**Issue by jundingzhou** [binarywang/WxJava#539]
小程序回复客服消息时调用 WxMaKefuMessage  toJSon 方法 会把 = 号等一些字符转义为Unicode转义字符. 比如 回复 link 类型消息时, 
`{"touser":" xxx","msgtype":"link","link":{"title":"abc","description":"abc","url":"https://mp.weixin.qq.com/mp/profile_ext?action\u003dhome\u0026__biz\u003dMzIyNDE5NDY3MA\u003d\u003d\u0026scene\u003d124","thumb_url":""}}`
消息发送出去不会抛异常, 但是小程序接收不到任何消息

toJson 
return new GsonBuilder().disableHtmlEscaping().create();

**Comment by jundingzhou** [comment]
微信的问题

**Comment by scott-z** [comment]
我也碰到这个问题了. 为什么这个issue关闭了呢? 
请问怎么解决的?

**Comment by jundingzhou** [comment]
经测试, 虽然带Unicode字符, 但是发送过去的url还是生效的. 后来排查是url的问题,  微信不让发公众号的链接.
