### ISSUE TITLE
微信weixin-java-mp发送图片消息

### ISSUE THREAD

**Issue by weizhenzhao** [binarywang/WxJava#543]
Hi Dear

I use the following code 
`
if ("media".equals(engineResb.getContentType())) {
			// if content type is media
			return new ImageBuilder().build("Bv9TIgsHKbiwiUyMbUt7i-e5GZFMp5XIJCtJKHTJIqgq0nvGSfPZ2t74R5zcpEWL", wxMessage, weixinService);
		}
 `

to send the picture message to the user
and I saw the console logs
`<xml>
  <ToUserName><![CDATA[oc6Yh1vEdgELl94vmEoA0g88NlRs]]></ToUserName>
  <FromUserName><![CDATA[gh_016f28ec8bb5]]></FromUserName>
  <CreateTime>1523954650</CreateTime>
  <MsgType><![CDATA[image]]></MsgType>
  <Image><MediaId><![CDATA[Bv9TIgsHKbiwiUyMbUt7i-e5GZFMp5XIJCtJKHTJIqgq0nvGSfPZ2t74R5zcpEWL]]></MediaId></Image>
</xml>`
I think that means the picture message has been sent successfully.
But I didn't receive the picture in my wechat.
Can you help me?

**Comment by binarywang** [comment]
能提供console的完整日志内容吗？光看你所说的，看不出来是发送成功了。
另外为啥不直接说中文呢？

**Comment by weizhenzhao** [comment]
Haha 
sorry 因为主要是对欧美开发，主要是习惯了在github上面写英文，昨天发送成功了。是改成用的kefuMessage来发送图片消息，同步的消息昨天就是没成功
`

WxMpKefuMessage message = WxMpKefuMessage.IMAGE().toUser(wxMessage.getFromUser())
					.mediaId(engineResb.getContent()).build();
			try {
				wxMpService.getKefuService().sendKefuMessage(message);
				return new TextBuilder().build("please have a look at the above picture", wxMessage, weixinService);
			} catch (WxErrorException e) {
				logger.info("sending image message error :" + e.getMessage());
				return new TextBuilder().build("this function will be available soon", wxMessage, weixinService);
			}


`

写成上面这样就发送成功啦

**Comment by binarywang** [comment]
那看来就是没问题了
