### ISSUE TITLE
企业付款银行卡参数字符编码问题

### ISSUE THREAD

**Issue by LemonCoo1** [binarywang/WxJava#544]
用源码测试是没有问题的，用maven引用的测试微信接口返回参数存在非UTF-8的字符，传的参数是一样的

**Comment by binarywang** [comment]
请问找到问题原因了吗？如qq群里沟通，确实是版本搞错了吧？

**Comment by LemonCoo1** [comment]
@binarywang  问题找到了不好意思，是jvm的编码导致的
