### ISSUE TITLE
token获取问题

### ISSUE THREAD

**Issue by dengqiangloveju** [binarywang/WxJava#545]
getAccessToken(boolean forceRefresh) 下面有三个实现方法，到底怎么看用的哪一个噢。另外token怎么存到自己的数据库中嘞？

**Comment by binarywang** [comment]
目前没有提供存储数据库的实现，因为实用性不强，建议参考redis的那个实现

**Comment by binarywang** [comment]
而且实际开发过程中，你并不用关心使用哪个方法获取token，对应的接口都已经封装好了，你只需调你想要的方法即可
