### ISSUE TITLE
多公众号或小程序的问题

### ISSUE THREAD

**Issue by bjzhaosq** [binarywang/WxJava#546]
您好，感谢分享，翻看了您多条回复，看到一个springmvc的多公众号demo，请问有没有springboot 多公众号或多小程序的demo，如果没有，能否告知如何用springboot写多号码的思路，非常感谢。

**Comment by binarywang** [comment]
spring boot的实现本质上也是用的spring mvc，除了外面的application，你完全可以认为是一样的，思路很简单，就是为每一个公众号建一套配置、一个service实例。

**Comment by bjzhaosq** [comment]
感谢回答，我能理解为在springboot 里面 ，其实我也为每一个小程序建立一个Properties去配置里面的值，为每一个小程序建立一个service实例，每一个实例里面实现
![image](https://user-images.githubusercontent.com/12652627/39028725-c18cbb6a-448a-11e8-93cd-fd8f3ad6e27f.png)
然后在Wx1Configuration里面再注入Bean
![image](https://user-images.githubusercontent.com/12652627/39028754-f0f98cf2-448a-11e8-961a-fb437f790dca.png)
最后经过测试
![image](https://user-images.githubusercontent.com/12652627/39028784-1d0b55c8-448b-11e8-8fbb-bceb808fc331.png)
里面分别会建立不同的实例对象和各自的小程序配置，但是我总觉得怪怪的。。

请问我这么写可以吗？

**Comment by binarywang** [comment]
这种方式适合于业务不同的少量公众号，如果太多就不太合适

**Comment by bjzhaosq** [comment]
非常感谢您的回答。
