### ISSUE TITLE
WxPayCouponInfoQueryResult字段错误

### ISSUE THREAD

**Issue by IamUv** [binarywang/WxJava#549]
coupon_mininum 应该是 coupon_minimum

**Comment by binarywang** [comment]
稍后修复下

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_5&index=6
你确定是错误的吗？我看文档里写的就是这个coupon_mininum，虽然mininum的拼写是错误的，但是如果是微信写错了，你能怎么办？

**Comment by binarywang** [comment]
或者说你实际使用中发现文档跟实际接口返回不一致？

**Comment by binarywang** [comment]
联系不到楼主，暂时关闭，如有问题进一步回复即可
