### ISSUE TITLE
企业微信中textcard缺少btntext字段

### ISSUE THREAD

**Issue by shuaizai88** [binarywang/WxJava#551]
企业微信中textcard缺少btntext字段，已经在群里给您说过了，顺便感谢有这么个神器

**Comment by binarywang** [comment]
最好是附上文档地址吧，多谢及时提出

**Comment by binarywang** [comment]
文档地址：https://work.weixin.qq.com/api/doc#10167/文本卡片消息

**Comment by binarywang** [comment]
3.0.3.BETA版本已添加
