### ISSUE TITLE
现金红包接口生成的签名数据没有按a-z排序，导致微信一致提示签名错误

### ISSUE THREAD

**Issue by qlfy17** [binarywang/WxJava#553]
http://scrm-1254239166.cossh.myqcloud.com/scrm/20180422/0ae3a5d10f554ad190fa8c9affda74ae.png
如图，
java tools生成的请求数据和微信官方签名数据一模一样，包括sign的值。但仔细比对发现，xml的字段顺序有问题。java tools的顺序没有按a-z进行排序，因此猜想是否是这个原因造成的。

另外，网上也有个帖子说这个字段顺序不排序会报签名错误的。链接为https://blog.csdn.net/hotlinhao/article/details/51262592

希望官方检查一下排序问题，谢谢

**Comment by binarywang** [comment]
因为没有相关权限，暂时无法验证，但如果你确实验证是相关问题引起的，请提供下修复代码，谢谢了

**Comment by binarywang** [comment]
我自己验证过，如果少了total_num，会报签名错误，但加上后只会报“你的商户号未开通该产品权限，请联系管理员到产品中心开通。开通路径：产品中心-产品大全-现金红包-申请开通”，所以无法判定你说的问题是否存在

**Comment by binarywang** [comment]
楼主有空帮忙确认下？

**Comment by qlfy17** [comment]
你好，由于产品着急上线，我还没进一步研究是什么原因，目前采用了另外一个开源的叫weixin-pay的sdk先实现的。后面有时间了再研究下。非常谢谢你的回复

**Comment by binarywang** [comment]
暂时关闭，如有问题进一步回复即可

**Comment by alangong114** [comment]
算法中，BeanToXMl中多加了sign_type 导致的 ，参数中，不需要这个参数

**Comment by alangong114** [comment]
在WxPaySendRedpackRequest 中忽略，
![image](https://user-images.githubusercontent.com/4981060/50382163-414e6180-06d4-11e9-9251-b9757fddb4f9.png) 这块赋值为true

**Comment by binarywang** [comment]
这个早就修复了，你咋翻这么老的issue看？而且问题出现原因并不是楼主所说的那样。
#726

**Comment by alangong114** [comment]
> 这个早就修复了，你咋翻这么老的问题？而且问问出现原因并不是楼主所说的那样。
> [＃726](https://github.com/Wechat-Group/WxJava/issues/726)

不好意思，没有看到，碰巧用3.1版本，做现金红包功能时发现，正好翻到这个帖子，找了几个小时，找到sign_type这块，我看这块后续没有回复直接close，以为还没有修复。

**Comment by binarywang** [comment]
好吧，有的时候升级下版本就能解决问题的，可以省不少时间的
