### ISSUE TITLE
weixin-java-mp导入eclipse报错，很多对象没有getter和setter方法？

### ISSUE THREAD

**Issue by IgnorantFool** [binarywang/WxJava#554]
不好意思，这可能是个小白问题，但是翻了一边ISSUES和WIKI，没有说到这个东西，麻饭有时间帮忙回答一下，非常感谢。
![image](https://user-images.githubusercontent.com/11766299/39095173-e372c96e-466e-11e8-9fdb-946d8f60c163.png)

**Comment by binarywang** [comment]
注意阅读首页说明，先学习下lombok相关知识

**Comment by IgnorantFool** [comment]
好的，谢谢。
