### ISSUE TITLE
微信支付服务商模式支付验证签名失败

### ISSUE THREAD

**Issue by TonyLuo** [binarywang/WxJava#555]
我是以服务商模式发起的支付，统一下单什么都成功了，但是一到调起支付的时候就验证签名失败。
问题应该是出在BaseWxPayServiceImpl.java里的再次加密的代码里。服务商模式应该是用subAppId去加密，而不是用appid去加密。
```
WxPayMpOrderResult payResult = WxPayMpOrderResult.builder().appId(unifiedOrderResult.getAppid()).timeStamp(timestamp).nonceStr(nonceStr).packageValue("prepay_id=" + prepayId).signType(signType).build();
                payResult.setPaySign(SignUtils.createSign(payResult, signType, this.getConfig().getMchKey(), false));
                return payResult;

```
参考：
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_sl_api.php?chapter=7_7&index=3
![image](https://user-images.githubusercontent.com/3250305/39175190-440607c8-47dc-11e8-85c2-1e294cae8f32.png)

 https://segmentfault.com/q/1010000011493630

**Comment by binarywang** [comment]
3.0.6.BETA测试版本已修复

**Comment by TonyLuo** [comment]
这个问题没有解决，还是有同样的签名问题。要先把 payResult的签名清空，然后再重新签名才行。
payResult.setPaySign(null);

```

        payResult.setPaySign(null);
        payResult.setPaySign(
            SignUtils.createSign(payResult, WxPayConstants.SignType.MD5, wxPayProviderService.getConfig().getMchKey(), false)
        );
```

**Comment by binarywang** [comment]
谢谢及时验证，不好意思，是我的疏忽，没有账号没能仔细测试

**Comment by binarywang** [comment]
下次建议可以直接提交PR代码修改吧，毕竟你是问题发现者，更清楚自己的问题

**Comment by binarywang** [comment]
@TonyLuo 看了下你的代码，没看明白，你新设的appid是子商户号的appid吗？

**Comment by TonyLuo** [comment]
我这个是临时解决的方法，是在所有结果都出来后再补救的做法。
在签名前加上这句就行。
     ```
   payResult.setPaySign(null);
    payResult.setPaySign(
            SignUtils.createSign(payResult, WxPayConstants.SignType.MD5, wxPayProviderService.getConfig().getMchKey(), false)
        );

 ```

**Comment by TonyLuo** [comment]
payResult 已经有签名了，不清空签名的话会把签名带到下一个签名结果里。
先清空一下，再重新签名。
        **payResult.setPaySign(null);**
  **payResult.setPaySign(SignUtils.createSign(payResult, signType, this.getConfig().getMchKey(), false));**

```
case TradeType.JSAPI: {
        String signType = SignType.MD5;
        String appid = unifiedOrderResult.getAppid();
        if (StringUtils.isNotEmpty(this.getConfig().getSubAppId())) {
          appid = this.getConfig().getSubAppId();
        }

        WxPayMpOrderResult payResult = WxPayMpOrderResult.builder()
          .appId(appid)
          .timeStamp(timestamp)
          .nonceStr(nonceStr)
          .packageValue("prepay_id=" + prepayId)
          .signType(signType)
          .build();

        payResult.setPaySign(null);

        payResult.setPaySign(SignUtils.createSign(payResult, signType, this.getConfig().getMchKey(), false));
        return (T) payResult;
      }

```

**Comment by binarywang** [comment]
我能理解你在方法外面使用payResult.setPaySign(null)的用意，但是在方法内部，这句不显得多余吗？该对象是使用WxPayMpOrderResult的build方法刚刚构建的，paySign值还是null的

**Comment by TonyLuo** [comment]
那就奇怪了，最新的3.0.6.BETA测试发现不在方法外面重新签名，还是会报签名错误

**Comment by TonyLuo** [comment]
好吧，我的子商户号的appid有多个，动态传进去的，不是hardcode的在配置文件里，所以还是有问题。
是我的业务逻辑必须在外面再处理一次。
建议考虑支持动态传配置appid

**Comment by binarywang** [comment]
确实代码还可以更灵活些，稍后考虑下，也欢迎你随时提供代码。
