### ISSUE TITLE
日志中应该隐藏secret信息

### ISSUE THREAD

**Issue by wongoo** [binarywang/WxJava#556]
如下，请求有异常时会将所有请求信息都打印到日志中，大家查看错误日志时都能看到appid和secret， 能不能将secret的内容变为星号？

`【请求参数】：js_code=001tZveq0SMoiq1AEXeq0ECJeq0tZveZ&secret=5681022fa1643845392367ea88888888&grant_type=authorization_code&appid=wxe156d4848d999999
【异常信息】：api.weixin.qq.com:443 failed to respond,level:ERROR,location:cn.binarywang.wx.miniapp.api.impl.WxMaServiceImpl.exe
`

**Comment by binarywang** [comment]
后续可以提供一个参数，配置是否需要在日志中对部分数据进行脱敏

**Comment by binarywang** [comment]
这个不太好处理，不过还是尽力处理下了

**Comment by binarywang** [comment]
3.0.5.BETA测试版本已增加相应处理
