### ISSUE TITLE
springboot框架，请问EntPayService怎么引入才好？

### ISSUE THREAD

**Issue by stchin** [binarywang/WxJava#557]
我看例子直接用@Resource，结果启动就报错了。说找不到实现类。
EntPayService的实现类是jar里面的，不能加@Service，所以没有扫描到，后面就报错了。

采用直接new的方式，结果配置文件取不到。
WxPayService wxPayService = new WxPayServiceImpl();
wxPayService.setConfig(new WxPayConfig());
new EntPayServiceImpl(wxPayService)

有没有更加简洁优雅的调用方式？

**Comment by binarywang** [comment]
请学习下spring基础知识
