### ISSUE TITLE
XStream 会导致jvm内存问题

### ISSUE THREAD

**Issue by mhcxp** [binarywang/WxJava#558]
对象序列化, xml反序列化重复初始化xstream对象
[具体见](http://qa.blog.163.com/blog/static/19014700220130283018863/)

**Comment by binarywang** [comment]
请问你是在使用sdk时发现有问题吗？据我观察并没有发现代码里有反复重复生成xstream对象的情况

**Comment by binarywang** [comment]
联系不到楼主，暂时关闭，如有问题进一步回复即可

**Comment by mhcxp** [comment]
代码中fromXML, toXML使用如下代码重复初始化XStream
`XStream xstream = XStreamInitializer.getInstance();`

**Comment by binarywang** [comment]
这并不算是重复初始化吧，只是多次调用，是给不同的消息用的，并没有重复调用，都是在初始化里一次性完成的

**Comment by mhcxp** [comment]
看下XStreamInitializer#getInstance, 每次调用都会new;
```
public class XStreamInitializer {

  public static XStream getInstance() {
    XStream xstream = new XStream(.......
```

> XStream官方有一段话：The XStream instance is thread-safe. That is, once the XStream instance has been created and configured, it may be shared across multiple threads allowing objects to be serialized/deserialized concurrently.即XStream是线程安全的，不需要重复初始化xstream对象，每一种类型实例化一个对象即可

**Comment by binarywang** [comment]
你可能没理解我的意思。的确是每次调用会new一个，但是每个xstream对象是对应不同的需求的。
你这样吧，如果你觉得哪段代码有问题，能否提交个PR我们再来讨论？
