### ISSUE TITLE
开放平台绑定多个公众平台，如何再获取每个公众平台对应的用户openId

### ISSUE THREAD

**Issue by fejjsong** [binarywang/WxJava#561]
我一个开放平台绑定了多个公众平台，对于unionId来说是唯一的，但我要实现每个公众号给用户发客服消息，就要获取该公众号对用户的openId，请问如何获取比较好？

**Comment by zhaochunqi** [comment]
我觉得你需要的可能是这个`wxOpenService.getWxOpenComponentService().getWxMpServiceByAppid(appId)`

**Comment by binarywang** [comment]
楼主，问题是否已解决？

**Comment by fejjsong** [comment]
已解决，可以通过开放平台的开发第三方应用解决。
