### ISSUE TITLE
有发送一次性订阅模版消息的接口吗

### ISSUE THREAD

**Issue by Dying5566** [binarywang/WxJava#564]
有发送一次性订阅模版消息的接口吗

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/pull/436 有加过的

**Comment by Dying5566** [comment]
哦哦，我看到了。但是content和color怎么只有一组值，我看微信文档里content是一个value和color的list才对

**Comment by binarywang** [comment]
没明白你的意思，你看的是这个文档吗？https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1500374289_66bvB

**Comment by binarywang** [comment]
联系不到楼主，暂时关闭，如有问题进一步回复即可
