### ISSUE TITLE
payBank接口在linux报错：用户真实姓名存在非UTF8字符

### ISSUE THREAD

**Issue by stchin** [binarywang/WxJava#566]
`result = new EntPayServiceImpl(wxPayService).payBank(EntPayBankRequest.builder()
                    .bankCode("1003")
                    .amount(21)
                    .encBankNo("卡号")
                    .encTrueName("张三丰")
                    .partnerTradeNo("asdfadssf")
                    .description("测试打款" + r)
                    .build());`

**这个代码在windows上运行正常。到了linux之后，报错：用户真实姓名存在非UTF8字符。**

所有参数都是写死在代码里面的，不存在其他干扰因素。

请问可能是什么原因？麻烦提供点思路：）

**Comment by a784511652** [comment]
去掉汉字也会报错吗？

**Comment by LemonCoo1** [comment]
@stchin    这个是tomcat编码导致的  建议你看看tomcat运行环境的编码是什么格式Charset.defaultCharset().name()，我之前遇到过这个问题tomcat启动会吧jvm编码设置成GBK，所以在tomcat启动是加上编码参数就可以了  -Dfile.encoding=UTF-8

**Comment by stchin** [comment]
感谢楼上的两位，我稍后试一下。

**Comment by binarywang** [comment]
楼主问题解决了吗？

**Comment by binarywang** [comment]
联系不到楼主，暂时关闭，如有消息请进一步回复即可

**Comment by joe434200** [comment]
我也想问 ~ 这个问题最后如何解决的 @stchin @binarywang
