### ISSUE TITLE
微信支付部分涉及到子服务商的接口报错（缺少子服务商id参数）

### ISSUE THREAD

**Issue by rain7564** [binarywang/WxJava#569]
微信支付部分涉及到子服务商的接口报错（缺少子服务商id参数），比如：
```
WxPayOrderQueryResult queryOrder(String transactionId, String outTradeNo) throws WxPayException;
WxPayOrderCloseResult closeOrder(String outTradeNo) throws WxPayException;
WxPayRefundQueryResult refundQuery(String transactionId, String outTradeNo, String outRefundNo, String refundId) throws WxPayException;
```
上面那些接口，若是服务商版，sub_mch_id（子商户号）都是必填项，直接调用会报错。

另外，下载对账单的接口也有类似的问题，如下接口：
```
WxPayBillResult downloadBill(String billDate, String billType, String tarType, String deviceInfo) throws WxPayException;
```
下载指定的子商户号对账单时，子商户号也是必填项。

文档参考：
[查询订单](https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_2)
[关闭订单](https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_3)
[查询退款](https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_5)
[下载对账单](https://pay.weixin.qq.com/wiki/doc/api/jsapi_sl.php?chapter=9_6)

**Comment by binarywang** [comment]
你是否尝试过在`com.github.binarywang.wxpay.config.WxPayConfig`配置类中指定对应的子商户号？

**Comment by rain7564** [comment]
如果有多个子商户号，那就需要动态设置到request中，而写在配置文件中只能应付单个子商户的情况。

**Comment by binarywang** [comment]
多个子商户的话确实会不方便，那其实问题就是需要提供一个可以指定各个请求参数的重载方法就可以了。

**Comment by binarywang** [comment]
准备增加四个重载方法，参数为对应的请求request对象，这样可以方便指定各个参数

**Comment by binarywang** [comment]
3.0.5.BETA测试版本已增加相应方法
