### ISSUE TITLE
公众号卡券接口完善

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#57]
检查接口，是否有未实现的接口，参考文档 http://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141229&token=&lang=zh_CN

**Comment by binarywang** [comment]
仔细看了下，目前已实现的仅是核销卡券中的部分接口。
而缺少的接口还比较多，主要涉及到创建卡券、投放卡券、管理卡券等

**Comment by zhouwd** [comment]
请问群主。我看会员卡的创建，官方走的是卡券的card/create接口。但是我看代码中，有WxMpMemberCardService。请问，将来会把会员卡的创建放到哪个service里面呢？

**Comment by binarywang** [comment]
现有的就先不动了，卡券相关的还是统一放到卡券的类中。

**Comment by piaofudeyu** [comment]
现在微信增加了 礼品卡的功能，看来又要增加功能了

**Comment by binarywang** [comment]
陆续实现了不少接口的已经，可能还有少量未实现，本issuer暂时关闭，还有未实现的接口，请单独开issue方便跟踪。
