### ISSUE TITLE
企业支付接口 签名不应该加入sign_type

### ISSUE THREAD

**Issue by manorsuperman** [binarywang/WxJava#570]
WxEntPayResult entPay(WxEntPayRequest request) throws WxPayException;
接口存在bug,不应该把sign_type也打包到request去签名。
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_2 官方文档中
企业付款接口https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
的请求各个字段没有sign_type字段。经过个人测试,
<err_code><![CDATA[SIGN_ERROR]]></err_code>
<err_code_des><![CDATA[签名错误]]></err_code_des>。然后把sign_type去掉后，签名，然后转换xml发送就可以成功。
现在有一个疑问就是没有sign_type,那么官方是怎么分辨这个签名是用的哪一种方式？

**Comment by binarywang** [comment]
看你提供的类名，感觉是老版本的，你是否使用新版本进行过测试？

**Comment by manorsuperman** [comment]
对，我用的2.9.0,看到wiki支付那里面用的这个，3.0.0没有问题。谢谢
