### ISSUE TITLE
小程序WxMaServiceImpl能否提供多种http框架实现方式

### ISSUE THREAD

**Issue by Yuhuiyang-Dev** [binarywang/WxJava#571]
小程序WxMaServiceImpl能否提供多种http框架实现方式。
提供跟公众号一样提供 WxMpServiceBaseImpl 抽象实现，让别可以扩展具体的实现，比如WxMpServiceOkHttpImpl

**Comment by binarywang** [comment]
可以考虑

**Comment by owenwong** [comment]
我也觉得应该这样，有好几个用户遇到类似情况了吧，让出现此问题的用户单独去配置超时时间或者其他使用其他解决方案，感觉不是很好。

**Comment by larrykoo711** [comment]
HTTP 推荐使用 OkHttp 实现，Okio 也是非常好的 input 和 output 处理工具类

**Comment by myoss** [comment]
能否重构下代码，实现 BaseWxMpServiceImpl 类似的功能，需要使用 `OkHttp`，多谢 @binarywang

**Comment by binarywang** [comment]
抽空考虑下，用一种新的方式实现

**Comment by binarywang** [comment]
3.8.2.B版本已支持，欢迎试用
