### ISSUE TITLE
如何获得accessToken？

### ISSUE THREAD

**Issue by stchin** [binarywang/WxJava#572]
由于我们原来的程序维护一个token，WJT维护一个，导致二者冲突。
我想把原来的直接调用WJT的accessToken，这样就可以统一使用一个accessToken了。

请问如何获得？

**Comment by binarywang** [comment]
参考已有实现，自己实现对应的WxMpConfigStorage 实现类，来管理accessToken

**Comment by binarywang** [comment]
暂时关闭，如有问题进一步回复即可

**Comment by peng051410** [comment]
如果不想使用WJT获取的accessToken要怎么处理？@binarywang

**Comment by peng051410** [comment]
直接继承WxMpServiceHttpClientImpl这个类并重写getAccessToken的方法，并返回null了，这样可以不？

**Comment by binarywang** [comment]
可以，实现自己想修改的方法即可

**Comment by peng051410** [comment]
@binarywang 谢谢！
