### ISSUE TITLE
如何自定义回复消息

### ISSUE THREAD

**Issue by lzwzzy** [binarywang/WxJava#574]
bi'ru比如![image](https://user-images.githubusercontent.com/23731957/39630217-4baf5008-4fe1-11e8-95a2-84735bf63436.png)

**Comment by binarywang** [comment]
其实很简单，仿照`me.chanjar.weixin.mp.builder.outxml`包下面的类自己去实现，当然如果你觉得是很常用的消息，可以在实现之后提交PR代码，分享出来供其他人使用。

**Comment by binarywang** [comment]
暂时关闭，如有问题进一步回复即可
