### ISSUE TITLE
支持redis lettuce客户端

### ISSUE THREAD

**Issue by dragontree101** [binarywang/WxJava#575]
现在实现 WxMpConfigStorage 的redis 使用的是jedis客户端
因为springboot2 默认的jedis客户端改成了 lettuce ，希望能够支持 lettuce 的redis客户端

谢谢

**Comment by binarywang** [comment]
这个你完全可以自己写一个的，那个jedis的实现其实也只是仅供参考，可能并不是适合各种场景

**Comment by dragontree101** [comment]
多谢！
