### ISSUE TITLE
WJT-SDK如何接受外部的access_token

### ISSUE THREAD

**Issue by dragontree101** [binarywang/WxJava#576]
多个程序都使用了WJT-SDK, 但是都使用的WxMpInMemoryConfigStorage模式，

这样的话，  就是由各个程序维护access token， 这样会导致刷新access token次数很多，所以想通过一个中控程序来统一控制access_token的获取和分发，如果这样的话， 如何使得一个程序在使用WJT-SDK的同时，来接受从外部得到的access_token？  

如果没有使用WJT-SDK， 可以通过拼接access_token参数，但是使用了WJT-SDK的项目，好像没发现如何接受外部的access_token。

使用的版本是3.0.0版本。

谢谢！

**Comment by binarywang** [comment]
你需要自己实现一个可以自己控制token的ConfigStorage类

**Comment by dragontree101** [comment]
自己实现是可以的， 多谢了， 不过这种场景，官方实现了更加好， 
因为现在微服务的架构， 都同时使用WJT-SDK，但是共用一个中控所分发access_token，而不是所有的服务都需要配置appid等其他参数，设计更加合理。 希望官方可以进行完善。

**Comment by binarywang** [comment]
因为你的场景我并不清楚，也没具体尝试过，所以最好是由你自己实现一个，然后提交PR上来，可以供其他人参考，毕竟这个开源的sdk也是需要靠大家一起共同努力不断完善的
