### ISSUE TITLE
开放平台如何动态配置componentAppId,componentSecret

### ISSUE THREAD

**Issue by linuxxx** [binarywang/WxJava#577]
我的场景如下, 开放平台使用完我需要重新创建, 这个时候如何动态的配置componentAppId,componentSecret? 而不是写死在配置文件里面, 以便达到不重启就换开放平台的能力?

**Comment by 007gzs** [comment]
`
        WxOpenService wxOpenService = new WxOpenServiceImpl();
        WxOpenInRedisConfigStorage inRedisConfigStorage = new WxOpenInRedisConfigStorage(getJedisPool());
        inRedisConfigStorage.setComponentAppId(componentAppId);
        inRedisConfigStorage.setComponentAppSecret(componentSecret);
        inRedisConfigStorage.setComponentToken(componentToken);
        inRedisConfigStorage.setComponentAesKey(componentAesKey);
        wxOpenService.setWxOpenConfigStorage(inRedisConfigStorage);`
