### ISSUE TITLE
这个项目的依赖可以进一步简化

### ISSUE THREAD

**Issue by xusheng1987** [binarywang/WxJava#58]
fluent-hc和jodd-http我看了下项目里没用到，可以去除，guava仅在一个地方用到了Lists.newArrayList，此处可以用jdk的List代替，至于joor，不知道能不能用jdk自身的反射代替

**Comment by binarywang** [comment]
感谢仔细分析，确实有些属于历史遗留问题，有些属于个人爱好加入的，我们再仔细排查一下，去掉一些不必要的jar包依赖

**Comment by belerweb** [comment]
我也发现了，支持去掉

**Comment by binarywang** [comment]
guava 作为一个比较有用且常用的类库，以后代码重构可能会用到比较多，暂时保留。

**Comment by jobmission** [comment]
guava 依赖较多，可否再优化，包括jedis依赖，无法排除掉。
@binarywang

**Comment by binarywang** [comment]
> guava 依赖较多，可否再优化，包括jedis依赖，无法排除掉。 @binarywang

欢迎自己提供好的优化方案，直接PR即可
