### ISSUE TITLE
WxOpenInRedisConfigStorage中的针对redis的操作，连接回收问题

### ISSUE THREAD

**Issue by fejjsong** [binarywang/WxJava#580]
看到对redis的操作结束后，都没有调用jedis.close();方法，连接不用回收吗？

**Comment by charmingoh** [comment]
Java 7 之后支持 `try-with-resources` 的写法，请看：http://ifeve.com/java-7%E4%B8%AD%E7%9A%84try-with-resources/

```Java
try (Jedis jedis = jedisPool.getResource()) {
    return jedis.get(componentVerifyTicketKey);
}
```

这样写会自动执行 jedis.close()

**Comment by binarywang** [comment]
楼主你的问题是这个吗？这个确实不应该质疑啊，除非你一直在使用JAVA6之前的版本？

**Comment by fejjsong** [comment]
对不起，忽略了这个问题，继承了AutoCloseable接口，谢谢提醒，close吧。
