### ISSUE TITLE
增加微信公众号错误信息工具类

### ISSUE THREAD

**Issue by 15838028035** [binarywang/WxJava#581]
没有自定义异常工具类型，返回微信提示的错误信息

**Comment by binarywang** [comment]
请明确下你的问题

**Comment by 15838028035** [comment]
例如微信返回异常信息{"erro_code":"2000","msg":"is  not valid media"} ,   想封装成友好的提示异常信息
例如:{"erro_code":"2000","msg":"mediaID无效"}, 封装这种类型的工具，自定义异常

**Comment by 15838028035** [comment]
@binarywang  是否可以封装了类型的异常工具

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433747234  是指这里面的信息吗？

**Comment by 15838028035** [comment]
是的

发自我的 iPhone

**Comment by binarywang** [comment]
可以考虑加一下

**Comment by binarywang** [comment]
3.0.6.BETA测试版本已增加
