### ISSUE TITLE
微信企业号的邀请成员接口

### ISSUE THREAD

**Issue by putjie** [binarywang/WxJava#583]
成员邀请的接口可以怎么实现
![yaoqing](https://user-images.githubusercontent.com/14882234/39862039-1e96439a-5475-11e8-8d67-30247933c642.png)

![image](https://user-images.githubusercontent.com/14882234/39862176-8fac86ca-5475-11e8-9ff0-d70851ab1929.png)

**Comment by binarywang** [comment]
请尽量把文档地址贴出来，方便直接查阅，谢谢

**Comment by putjie** [comment]
批量邀请成员
https://work.weixin.qq.com/api/doc#12543
新增人员接口新增字段
https://work.weixin.qq.com/api/doc#10018

**Comment by binarywang** [comment]
3.0.6.BETA测试版本已增加
