### ISSUE TITLE
企业付款到银行卡 签名失败

### ISSUE THREAD

**Issue by manorsuperman** [binarywang/WxJava#584]
```
<dependency>
  <groupId>com.github.binarywang</groupId>
  <artifactId>weixin-java-pay</artifactId>
  <version>3.0.0</version>
</dependency>
```
EntPayBankRequest 把 sign_type 把sign_type 打包进去 导致 
EntPayBankResult ret = entpay.payBank(request); 调用 返回签名错误

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/issues/570 跟这个问题是类似的？

**Comment by manorsuperman** [comment]
是的，我看 EntPayRequest 这个类有重写
```
  @Override
  protected boolean ignoreSignType() {
    return true;
  }
```
而 EntPayBankRequest  这个类里面没有，应该就是这个原因吧

**Comment by binarywang** [comment]
那确实是个问题，需要修复一下

**Comment by binarywang** [comment]
3.0.6.BETA测试版本已修复

**Comment by binarywang** [comment]
3.0.7.BETA测试版本已修复
