### ISSUE TITLE
WxPayConfig增加支持byte数组方式设置证书

### ISSUE THREAD

**Issue by jrrx** [binarywang/WxJava#586]
需求原因，证书不再磁盘目录上，但是能拿到证书的content，因此提出此需求.
---------------------------
目前设置方式:
WxPayConfig payConfig = new WxPayConfig();
payConfig.setKeyPath(String path);

期望增加方式:
WxPayConfig payConfig = new WxPayConfig();
payConfig.setKeyContent(byte[] p12cert);

加载的时候使用如下方式即可加载: 
ByteArrayInputStream instream = new ByteArrayInputStream(p12cert);
store.load(instream, key.toCharArray());

**Comment by binarywang** [comment]
目前来说你完全可以把这个byte数组存到临时文件里，然后再来使用。

**Comment by jrrx** [comment]
嗯，先放入临时文件，也是可以的。

**Comment by binarywang** [comment]
3.0.6.BETA测试版本已支持

**Comment by jrrx** [comment]
赞一个，后续测试一下，我会反馈。
