### ISSUE TITLE
公众号微信支付页面跳转问题

### ISSUE THREAD

**Issue by duanlinfei** [binarywang/WxJava#588]
公众号微信支付成功后,通过location.href跳转页面，有时候无法跳转，请问有好的处理方式吗？
if(res.err_msg == "get_brand_wcpay_request:ok" ) {
    location.href = url + "?v=" + Math.random();
}

**Comment by binarywang** [comment]
涉及到前端问题，不做深入讨论，请网上自行搜索相关解决方案
