### ISSUE TITLE
开放平台调用getWxMpServiceByAppid怎么修改HttpClient配置

### ISSUE THREAD

**Issue by uriboyka** [binarywang/WxJava#593]
`wecService.getWxOpenComponentService().getWxMpServiceByAppid(appId).getTemplateMsgService().sendTemplateMsg(message)`
发送模板消息时，偶尔会抛如下异常，想修改下HttpClient试下
`java.lang.RuntimeException: org.apache.http.NoHttpResponseException: api.weixin.qq.com:443 failed to respond`

**Comment by binarywang** [comment]
楼主是否阅读过此[文档](https://github.com/Wechat-Group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95)？

**Comment by uriboyka** [comment]
看过了，但是我继承`WxOpenServiceImpl`的`init()`方法里用的是`WxOpenInRedisConfigStorage`，该对象没有`setApacheHttpClientBuilder`方法

---

目前解决办法是，用的是3.0.0的源码自己修改了DefaultApacheHttpClientBuilder默认参数，编译后安装到本地使用

**Comment by binarywang** [comment]
既然用的自定义的redis的实现`WxOpenInRedisConfigStorage`，那你可以参考它实现一个即可，没必要自己改其他源码进行编译。

**Comment by uriboyka** [comment]
好的，谢谢！主要也是想急于验证`java.lang.RuntimeException: org.apache.http.NoHttpResponseException`这个错误，改了就没再报这个错了，等有时间按你说的改回来。

**Comment by 007gzs** [comment]
开放平台当时我写ConfigStorage的时候确实没加`getApacheHttpClientBuilder`和代理部分 `WxOpenInnerConfigStorage`里这些直接返回空了。。
