### ISSUE TITLE
weixin-java-tools3.0，公众号weixin.mp.api.WxMpMessageRouterRule.java调用WxMpXmlMessage方法报错

### ISSUE THREAD

**Issue by tuvy** [binarywang/WxJava#594]
WxMpMessageRouterRule中的test方法，wxMessage.getFromUser()、wxMessage.getEventKey()、wxMessage.getContent()在 WxMpXmlMessage中并没有这些方法，其它类中也有类似的错误。

**Comment by binarywang** [comment]
楼主，请注意看首页说明，需要引用lombok
