### ISSUE TITLE
WxPayException(String customErrorMsg, Throwable tr)中的customErrorMsg没有get方法

### ISSUE THREAD

**Issue by fbchen** [binarywang/WxJava#595]
WxPayException(String customErrorMsg, Throwable tr)中的customErrorMsg只有传入参数，没有get方法获取

**Comment by fbchen** [comment]
/**
   * 错误代码
   */
String errCode
也没有setter方法，假如我需要创建一个WxPayException，是没有办法自定义错误代码和错误消息的。

**Comment by binarywang** [comment]
可以加一下

**Comment by binarywang** [comment]
3.0.7.BETA测试版本已增加

**Comment by fbchen** [comment]
Thank you
