### ISSUE TITLE
企业支付 queryEntPay 签名失败

### ISSUE THREAD

**Issue by manorsuperman** [binarywang/WxJava#596]
EntPayQueryRequest  打包时加入了sign_type,不应该加入。
企业支付的那些接口 好像都有这个问题 #584

**Comment by binarywang** [comment]
这个测试版已经修复了，可以看下日志

**Comment by manorsuperman** [comment]
https://github.com/Wechat-Group/weixin-java-tools/blob/2d84939be098eb9e8f55ac34411f9320c762fbcc/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/entpay/EntPayQueryRequest.java#L23
我看EntPayQueryRequest 并没有修改啊？没有添上ignoreSignType

**Comment by binarywang** [comment]
我说的是测试版，你要看develop分支

**Comment by binarywang** [comment]
是我看错了，测试版的这个确实还没加，稍后加上

**Comment by binarywang** [comment]
3.0.7.BETA测试版本已修复
