### ISSUE TITLE
希望支持微信开放平台

### ISSUE THREAD

**Issue by o624366705** [binarywang/WxJava#6]
增加多公众号管理，替子公众号授权，代替子公众号实现业务的功能

**Comment by buyijiuyang** [comment]
开放平台一般不都为了unionID吗？如果是子公众号可以自身直接实现。没必要用的开放平台。如果是第三方的软件可以考虑这个功能实现

**Comment by binarywang** [comment]
楼主说的可能第三方平台，开放平台的概念很宽泛，包含很多
