### ISSUE TITLE
springboot项目如何初始化呢？  有木有demo例子~

### ISSUE THREAD

**Issue by 475cheng** [binarywang/WxJava#600]

**Comment by zhangshity** [comment]
Repository里有springboot的例子。

**Comment by 475cheng** [comment]
没懂~~    Repository是指 这个项目 Repository包？？ 还是Repository类   ？？  还是 另一个git项目？

**Comment by xwsg** [comment]
@475132489 https://github.com/binarywang/weixin-java-mp-demo-springboot

**Comment by binarywang** [comment]
楼主是否有仔细阅读该项目首页说明？
