### ISSUE TITLE
第三方平台代替小程序实现登录功能

### ISSUE THREAD

**Issue by whhya** [binarywang/WxJava#602]
微信官方文档中必须要传第三方平台的 component_access_token
为什么代码中少了component_access_token=ACCESS_TOKEN ?  看了半天文档中就是找不到
官方文档:https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1492585163_FtTNA&token=&lang=zh_CN

**Comment by 007gzs** [comment]
component_access_token请求中统一添加的
https://github.com/Wechat-Group/weixin-java-tools/blob/2d84939be098eb9e8f55ac34411f9320c762fbcc/weixin-java-open/src/main/java/me/chanjar/weixin/open/api/impl/WxOpenComponentServiceImpl.java#L112-L122

**Comment by 007gzs** [comment]
直接调用 WxOpenComponentService.miniappJscode2Session 就可以了
