### ISSUE TITLE
只要我注入WxCpService，就无法写入log4j2日志

### ISSUE THREAD

**Issue by jinangchao** [binarywang/WxJava#604]
项目之前全部用common-logging调用log4j2写日志，发现整合后无法写日志，将jcl-over-slf4j-1.7.24.jar移除后正常，但是凡是注入WxCpService的类，在该类里面写日志都发现无法写入，将WxCpService注释掉，就可以写入log4j2日志。
有什么好的办法解决吗？亦或是有哪个步骤错了吗？

**Comment by binarywang** [comment]
本sdk使用的是slf4j，至于如何整合log4j2，网上有很多方案，自行搜索即可
