### ISSUE TITLE
为什么我导入项目后项目很多地方报错【方法找不到。。。】

### ISSUE THREAD

**Issue by zhangweiingasdfas** [binarywang/WxJava#606]

**Comment by bysunexus** [comment]
1.请先使用 google 或者 bing查找你的问题
2.来这里提问请将你的问题描述清楚

**Comment by binarywang** [comment]
这问题问的确实太不够水平，建议先仔细阅读下项目首页所有说明，
另外据我初步判断，极有可能是没装lombok插件导致的。
还有新手不建议导项目，先去看看demo，正如项目首页中所说。
