### ISSUE TITLE
WxError   返回的结果错误。

### ISSUE THREAD

**Issue by tomsean** [binarywang/WxJava#607]
{"errcode":40164,"errmsg":"invalid ip 183.16.199.206, not in whitelist hint: [l8OyaA0242sha2]"}
 public static WxError fromJson(String json, WxType type) {
WxError wxError = (WxError)WxGsonBuilder.create().fromJson(json, WxError.class);
}
 

WxError wxError = (WxError)WxGsonBuilder.create().fromJson(json, WxError.class);  返回的结果错误。

**Comment by binarywang** [comment]
这错误内容难道还不够明确？？？？

**Comment by tomsean** [comment]
微信返回的结果没有问题，但是，解析成WxError的时候出现问题，wxError.errorCode  等于0。应该是反序列化出现问题

**Comment by binarywang** [comment]
你确定你的调用方法没问题？

**Comment by binarywang** [comment]
`me.chanjar.weixin.common.error.WxError#fromJson(java.lang.String)`

**Comment by tomsean** [comment]
![image](https://user-images.githubusercontent.com/5907239/40640122-4467597a-6347-11e8-9c4b-bdadef26e2d0.png)

**Comment by binarywang** [comment]
看不出来你是如何使用的，你跑下源码里提供的单元测试看看？

![default](https://user-images.githubusercontent.com/1343140/40760861-53197acc-64cb-11e8-908f-f20a76430b7f.PNG)

**Comment by binarywang** [comment]
楼主能否帮忙再次确认下？

**Comment by tomsean** [comment]
单元测试没问题

**Comment by binarywang** [comment]
那问题出在哪里？

**Comment by tomsean** [comment]
依然错误，但是跟踪不到原因

**Comment by binarywang** [comment]
暂时关闭，目前没发现问题，楼主如果找到原因，请随时指出
