### ISSUE TITLE
支付结果通知后，看代码应该还需要自己判断是否成功，wiki里面没有加

### ISSUE THREAD

**Issue by nexvx** [binarywang/WxJava#610]
com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl#parseOrderNotifyResult
com.github.binarywang.wxpay.bean.result.BaseWxPayResult#checkResult

https://github.com/Wechat-Group/weixin-java-tools/wiki/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98

还是在wiki里面说一下比较好，以免直接抄了不校验

**Comment by binarywang** [comment]
wiki可以自行修改，欢迎随时完善
