### ISSUE TITLE
微信公众号 获取用户基本信息缺少字段

### ISSUE THREAD

**Issue by JiweiHe** [binarywang/WxJava#612]
微信公众号 获取用户基本信息 时 接收实体缺少**subscribe_scene** 字段

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839

https://api.weixin.qq.com/cgi-bin/user/info?access_token=ACCESS_TOKEN&openid=OPENID&lang=zh_CN

**Comment by binarywang** [comment]
这个测试版本已经加上了。
另外，提问问题前请先看下测试版本即develop分支是否已经实现或修复。
