### ISSUE TITLE
微信支付SignUtils类的createSign方法使用StringBuilder不用考虑线程安全吗？

### ISSUE THREAD

**Issue by jiang-jian-jian** [binarywang/WxJava#613]
public static String createSign(Map<String, String> params, String signType, String signKey, boolean ignoreSignType) {
    SortedMap<String, String> sortedMap = new TreeMap<>(params);

    StringBuilder toSign = new StringBuilder();
    for (String key : sortedMap.keySet()) {
      String value = params.get(key);
      boolean shouldSign = false;
      if (ignoreSignType && "sign_type".equals(key)) {
        shouldSign = false;
      } else if (StringUtils.isNotEmpty(value)
        && !Lists.newArrayList("sign", "key", "xmlString", "xmlDoc", "couponList").contains(key)) {
        shouldSign = true;
      }

      if (shouldSign) {
        toSign.append(key).append("=").append(value).append("&");
      }
    }

    toSign.append("key=").append(signKey);
    if (SignType.HMAC_SHA256.equals(signType)) {
      return createHmacSha256Sign(toSign.toString(), signKey);
    } else {
      return DigestUtils.md5Hex(toSign.toString()).toUpperCase();
    }
  }

**Comment by binarywang** [comment]
StringBuilder toSign = new StringBuilder(); 这个变量是个本地变量，何来的线程安全问题？

**Comment by jiang-jian-jian** [comment]
看错了。微信支付的http请求支持连接池吗？

**Comment by binarywang** [comment]
暂不支持，后期可以考虑加一下
