### ISSUE TITLE
上传图文素材时总是提示不合法的media_id,我明明是通过上传临时缩略图素材接口获得的id

### ISSUE THREAD

**Issue by ghost** [binarywang/WxJava#614]
【请求地址】: https://api.weixin.qq.com/cgi-bin/material/add_news?access_token=10_eMZzb-Ru2WkmwEpcowAbHR-Wmdfnz-u8NBDyRBWqufrt0IuS2IZQRk6v_Saba0TrO0okkJNrqHAKQLszPYnyFey6dLdX4T9ckYAFmw8bUQXGVIscY3d1do5ZE6KrPvKkh3rf-5znIz-OT9u_MAGiAIAGUA
【请求参数】：{"articles":[{"thumb_media_id":"QDCgm73dG3BzZ3h3o2RtlKrQ2XzcCPTCH5HVfQBeFVEBl2wUMdUde_vTsqjfS32u","title":"hello","content":"tt","author":"admin","content_source_url":"dfdfdf","digest":"rr","show_cover_pic":"1"}]}
【错误信息】：{"errcode":40007,"errmsg":"invalid media_id hint: [nDubTA05541499]"}

**Comment by binarywang** [comment]
你拿临时素材的id往永久图文素材里放？

**Comment by ghost** [comment]
```java
mpMaterialNewsArticleSingle.setThumbMediaId(thumbMediaId);
```
在这里需要的是缩略图的ID，而缩略图不是只能作为临时素材吗

**Comment by binarywang** [comment]
缩略图不能作为永久素材吗？建议仔细阅读下官方文档

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1444738729  都写得很清楚的

**Comment by gaozhanpeng999** [comment]
原因找到了，上传图文素材的接口和上传图文消息接口弄错了……

**Comment by binarywang** [comment]
没回错消息吧，难道跟楼主是同一个人？

**Comment by gaozhanpeng999** [comment]
是同一个，2333




发自网易邮箱大师


在2018年06月11日 18:10，Binary Wang<notifications@github.com> 写道：

没回错消息吧，难道跟楼主是同一个人？
