### ISSUE TITLE
统一下单接口错误[支付]

### ISSUE THREAD

**Issue by DR-YangLong** [binarywang/WxJava#618]
`java.lang.ClassCastException: com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderResult cannot be cast to com.github.binarywang.wxpay.bean.result.BaseWxPayResult`

**Comment by DR-YangLong** [comment]
解决方法：
me.chanjar.weixin.common.util.xml.XStreamInitializer类中，将xstream使用的类加载器设置为上下文加载器，getInstance方法中进行设置：
   xstream.setClassLoader(Thread.currentThread().getContextClassLoader());
   return xstream;

**Comment by 007gzs** [comment]
你是不是把sdk代码放本地了？

**Comment by binarywang** [comment]
我记得这个问题修复过 https://github.com/Wechat-Group/weixin-java-tools/issues/352

**Comment by DR-YangLong** [comment]
不依赖jar而是引入源码的方式确实会报错，最好还是设置下，这样都不会有错

**Comment by binarywang** [comment]
楼主看过我上面发的么？

**Comment by DR-YangLong** [comment]
看了

**Comment by binarywang** [comment]
那不清楚你为啥还有这个疑问？难道你用的是很老的版本？
