### ISSUE TITLE
跳转小程序参数错误[公众号模版消息]

### ISSUE THREAD

**Issue by GitHubMrChen** [binarywang/WxJava#621]
模版消息官方文档https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277
"miniprogram":{
     "appid":"xiaochengxuappid12345",
     "pagepath":"index?foo=bar"
}
路径参数为pagepath，weixin-java-mp模块参数为path，致无法正确跳转；
注：pagepath缺省默认跳转小程序首页，但无法跳转对应页面，且无法传参
感谢博主开源本SDK方便Java从业者快速构建微信服务！！！

**Comment by binarywang** [comment]
这个测试版已经修复
