### ISSUE TITLE
群发接口缺少clientmsgid

### ISSUE THREAD

**Issue by tzraeq** [binarywang/WxJava#623]
微信官方文档增加了一项，“使用 clientmsgid 参数，避免重复推送”，目前3.0.0应该是没有的吧，希望能够增加这个参数。

**Comment by binarywang** [comment]
建议将文档附上，以便核对，谢谢。
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21

**Comment by binarywang** [comment]
更新日志里看到了：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1418702138 
2017年4月21日 群发接口新增 clientmsgid 参数，开发者调用群发接口时可以主动设置，避免重复推送。

**Comment by binarywang** [comment]
另外还有：
```
2017年5月2日  删除群发接口新增 article_idx 参数，开发者可以指定删除多图文中的某一篇。并新增返回码 40060，代表指定的 article_idx 不合法。
群发接口每分钟限制请求60次，超过限制的请求会被拒绝。
```

**Comment by binarywang** [comment]
3.0.9.BETA测试版本已增加

**Comment by tzraeq** [comment]
大神你太有效率了，给你点赞
