### ISSUE TITLE
怎么改为使用OKHttp或JODD_HTTP? 默认是使用APACHE_HTTP

### ISSUE THREAD

**Issue by gclsoft** [binarywang/WxJava#625]
![image](https://user-images.githubusercontent.com/1269898/41265525-4d26a316-6e25-11e8-9547-837792b50aa5.png)
我直接这样改会把APACHE_HTTP 改为OK_HTTP报找不到okhttp的错误

**Comment by binarywang** [comment]
注意看wiki说明，想用okhttp你需要加入对应jar依赖

**Comment by binarywang** [comment]
https://github.com/Wechat-Group/weixin-java-tools/wiki/http%E6%A1%86%E6%9E%B6%E7%9A%84%E9%80%89%E7%94%A8%E8%AF%B4%E6%98%8E
