### ISSUE TITLE
API调用上限

### ISSUE THREAD

**Issue by gaozhanpeng999** [binarywang/WxJava#626]
maven（weixin-java-mp）依赖从2.3.4升级到3.0.0后，经常出现api调用达到上限，其实就是刷新access_token达到上限了，有遇到类似问题的朋友么

**Comment by cherry-yang-workspace** [comment]
可以检查下accessToken是否没有缓存起来

**Comment by gaozhanpeng999** [comment]
这个工具已经提供了内存缓存，不需要手动缓存（如果没有配置redis）

**Comment by gaozhanpeng999** [comment]
不是刷新access_token达到上限，而是上传图文消息api达到上限，“新注册帐号各接口调用频率限制如下“上传图文消息接口最多10”
