### ISSUE TITLE
微信支付沙箱环境URL错误

### ISSUE THREAD

**Issue by abcfy2** [binarywang/WxJava#627]
参见微信支付沙箱环境[文档](https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=21_2#3)

微信支付沙箱环境的URL prefix是`/sandbox/`，而不是`/sandboxnew/`，旧的代码会返回502，待会我会递交一个PR修复这个问题

**Comment by abcfy2** [comment]
好像不能简单的这么改，微信支付沙箱用的是/sandbox，而刷卡仿真用的却是/sandboxnew。

微信的开发文档绝对是我见过的最烂的开发文档

**Comment by binarywang** [comment]
我去，居然没发现这个问题，主要是之前这个环境一直没法用

**Comment by abcfy2** [comment]
现在可以用了，我在本地修改代码build之后推送到maven local，这个接口就正常了，修改`weixin-java-pay/src/main/java/com/github/binarywang/wxpay/service/impl/BaseWxPayServiceImpl.java`第81行，

```java
      return PAY_BASE_URL + "/sandbox";
```

之后在本地测试就过了。但是我只测试了微信支付，所以不确定这个影响会不会干扰到其他sandbox接口，需要系统测试一下。微信居然沙箱环境用的prefix都不统一，真是醉了。而且微信支付沙箱环境文档的那个配图和底下的文字描述根本不相符。

微信的开发文档确实稀烂，官方还没有SDK，开发接入非常麻烦，和支付宝的开发体验差远了。

**Comment by abcfy2** [comment]
按照这个issue: https://github.com/overtrue/wechat/issues/665

似乎`/sandboxnew`才是对的，但是需要签名，这里可能得在sdk改一下，否则返回如下内容:

```xml
【响应数据】：<xml>
  <return_code><![CDATA[FAIL]]></return_code>
  <return_msg><![CDATA[沙箱验证签名失败，请确认沙箱签名key是否正确（通过getsignkey调用生成）]]></return_msg>
</xml>
```

**Comment by wangtao** [comment]
我看的文档是  https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_1

图文都是  sandboxnew

**Comment by abcfy2** [comment]
微信自己的文档就很凌乱，很多文档都不更新，文档中有一大堆死链也没人修复。

之前沙箱环境的URL是对的，但是按照微信文档，必须先getsignkey，建议在sdk处理下这个。可以参考我上面贴出来的issue链接

**Comment by binarywang** [comment]
那其实也问题不大，本身沙箱环境就是建议先调用getsignkey来生成signkey，然后再来调用的。这个接口我们也提供了，需要使用者自己手动去掉用即可
