### ISSUE TITLE
 关于WxPayMpOrderResult 的package属性转换为packageValue的问题

### ISSUE THREAD

**Issue by wangtao** [binarywang/WxJava#630]
在WxPayMpOrderResult里， packageValue 字段用XStreamAlias标注了别名，然而有些情况这个类会通过spring mvc返回时,会通过jackson json转换,希望把json的alias标注也加上,谢谢

`public class WxPayMpOrderResult {
  /**
   * 由于package为java保留关键字，因此改为packageValue.
   */
  @XStreamAlias("package")
private String packageValue;`

**Comment by binarywang** [comment]
这会导致sdk引入过多的外部jar依赖，如果你jackson要求这样，那gson、fastjson等其他是不是也得加入？
你完全可以在理解自己的需求的基础上多一步转换即可，没必要依赖这个类的原始名称。

**Comment by wangtao** [comment]
了解了，那我在前端转换一下
