### ISSUE TITLE
微信支付配置

### ISSUE THREAD

**Issue by MicroLord** [binarywang/WxJava#632]
目前微信支付有微信移动支付和微信公众号支付，两种支付的appid和mch_id是不一样的，如何共存？

**Comment by binarywang** [comment]
分别创建不同的config和service实例

**Comment by MicroLord** [comment]
@binarywang 感谢您的回复，如何创建不同的service实例？方便贴一段demo吗？WxPayService这个实例尝试了下，只存在了一个！

**Comment by MicroLord** [comment]
@binarywang 已解决，谢谢
