### ISSUE TITLE
createWxaCodeUnlimit报错

### ISSUE THREAD

**Issue by tomsean** [binarywang/WxJava#633]
java.lang.NoSuchMethodError: cn.binarywang.wx.miniapp.api.WxMaQrcodeService.createWxaCodeUnlimit(Ljava/lang/String;Ljava/lang/String;IZLcn/binarywang/wx/miniapp/bean/WxMaCodeLineColor;Z)Ljava/io/File;

**Comment by binarywang** [comment]
不清楚你的使用场景，建议自己分析下自己的代码，必要时再阅读下源码
