### ISSUE TITLE
小程序解析用户信息时第一次gson报错

### ISSUE THREAD

**Issue by f497196689** [binarywang/WxJava#634]
![image](https://user-images.githubusercontent.com/15325854/41657217-3e2dae76-74c5-11e8-8d1d-fd7c85454f8d.png)
如图中报错信息，第一次请求时报该错误，第二次就好了，麻烦作者看下，多谢！

**Comment by f497196689** [comment]
![image](https://user-images.githubusercontent.com/15325854/41657294-7de14942-74c5-11e8-8317-358f79d3f1b6.png)

**Comment by binarywang** [comment]
看下https://github.com/Wechat-Group/weixin-java-tools/issues/359 这个，看是否有帮助

**Comment by zmber** [comment]
怎么解决的呢？我也是这个问题

**Comment by binarywang** [comment]
上面不是说了，参考下 #359 吗？

**Comment by f497196689** [comment]
对，参考一下 #359

**Comment by SYZ-Coder** [comment]
请问，解决了吗

**Comment by binarywang** [comment]
> 请问，解决了吗

请参考 #359 ，请不要在已关闭的issue里回复，你这相当于在挖尸
