### ISSUE TITLE
建议 Javadoc 不要使用 pre 标签

### ISSUE THREAD

**Issue by ghost** [binarywang/WxJava#637]
如下，用 pre 定义的标签在有的 IDE 中不能显示
&lt;pre&gt; 自定义菜单创建接口 &lt;/pre&gt;

**Comment by binarywang** [comment]
那你建议用什么？

**Comment by ghost** [comment]
就用最简单的格式，段落用 p，分行用 br，列表 ul/li，基本就够了吧。

**Comment by binarywang** [comment]
那你觉得如果有一段演示代码，加上你说的那一堆标签会不会很别扭？你有没有想过是不是有可能是你的那个IDE有问题，连pre标签支持都有问题？
