### ISSUE TITLE
模版消息的部分接口待完善

### ISSUE THREAD

**Issue by Allenkearn** [binarywang/WxJava#64]
目前模版消息模块缺少的接口如下：
1 设置所属行业
2 获取设置的行业信息
3 获得模板ID
4 获取模板列表
5 删除模板

接口地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277&token=&lang=zh_CN

**Comment by binarywang** [comment]
http://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277&token=&lang=zh_CN

你上面的地址为啥是https的，打不开

**Comment by xiaoCong2014** [comment]
https那条链接能在我这打开：
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277&token=&lang=zh_CN

**Comment by binarywang** [comment]
有点神奇了，我换了台电脑，还是一样的，提示“发生错误，请点击返回首页”

**Comment by binarywang** [comment]
关闭掉，因为和 #63  重复了
