### ISSUE TITLE
创建客服账号失败

### ISSUE THREAD

**Issue by lazycathome** [binarywang/WxJava#641]
创建客服账号传输的request消息体对不上了，现在需要传输password，但是sdk中还是invite_wx

**Comment by binarywang** [comment]
请给出接口变动的依据，比如文档地址。

**Comment by binarywang** [comment]
楼主呢？能否给个答复？

**Comment by lazycathome** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140547
参考这里

**Comment by lazycathome** [comment]
经过测试测试账号不需要创建客服账号，能直接发送客服消息

**Comment by binarywang** [comment]
你这个文档地址跟这个 ，看起来不一致，我也是无语了。https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1458044813 而且之前改过一次，把password去掉了，难道现在又加了回来？
