### ISSUE TITLE
请问关于公众号通知事件推送消息里事件类型为 merchant_order的支持 

### ISSUE THREAD

**Issue by wangtao** [binarywang/WxJava#642]
是微信小店的订单接口

6.1	订单付款通知
在用户在微信中付款成功后，微信服务器会将订单付款通知推送到开发者在公众平台网站中设置的回调URL（在开发模式中设置）中，如未设置回调URL，则获取不到该事件推送。

事件推送的内容如下：

`
<xml>
<ToUserName><![CDATA[weixin_media1]]></ToUserName>
<FromUserName><![CDATA[oDF3iYyVlek46AyTBbMRVV8VZVlI]]></FromUserName>
<CreateTime>1398144192</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[merchant_order]]></Event>
<OrderId><![CDATA[test_order_id]]></OrderId>
<OrderStatus>2</OrderStatus>
<ProductId><![CDATA[test_product_id]]></ProductId>
<SkuInfo><![CDATA[10001:1000012;10002:100021]]></SkuInfo>
</xml>
`

目前不支持这类消息对么？  请问有支持计划么？  谢谢

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421141217

**Comment by binarywang** [comment]
可以添加支持

**Comment by binarywang** [comment]
3.1.1.BETA测试版本已支持

**Comment by wangtao** [comment]
十分感谢
