### ISSUE TITLE
修改HttpClient链接参数配置

### ISSUE THREAD

**Issue by ywj070101526** [binarywang/WxJava#644]
无法修改httpClinet默认设置
Wx**ConfigStorage中无setApacheHttpClientBuilder()方法

**Comment by binarywang** [comment]
你确定看过具体的实现类吗？没有对应方法？

**Comment by ywj070101526** [comment]
![1529910651 1](https://user-images.githubusercontent.com/5977737/41885571-2193e4dc-792b-11e8-9011-ce8ed04013a4.jpg)
我看过源码，没有找到对应方法

**Comment by bysunexus** [comment]
参考
https://github.com/Wechat-Group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95

**Comment by binarywang** [comment]
那只能说是开放平台的这个实现原作者在实现时考虑欠佳，没有添加，其他是加了的，你完全可以自己在其基础上在实现一个。

**Comment by binarywang** [comment]
3.1.1.BETA测试版本已修复
