### ISSUE TITLE
自动回复客服消息时，无法换行

### ISSUE THREAD

**Issue by lazycathome** [binarywang/WxJava#645]

**Comment by binarywang** [comment]
楼主能否先回复下你提出的另外一个问题？
另外你这个问题你确认自己尝试过各种方法吗？

**Comment by lazycathome** [comment]
我发现是gson在tojson的时候对`\n`转义成`\\n`了，微信就识别成`\n`字符串了；我采用的是自己把`\\`替换成`\`了，然后直接调用post接口发送完成的，没有调用wxMpService.getKefuService().sendKefuMessage()方法

**Comment by binarywang** [comment]
那可能是个问题，抽空研究下

**Comment by binarywang** [comment]
这个我通过跑单元测试，并没发现你说的问题，你是否运行过单元测试？`me.chanjar.weixin.mp.api.impl.WxMpKefuServiceImplTest#testSendKefuMessage`

**Comment by AaronFeng2014** [comment]
哈哈， 我也发现了这个问题了，一会可以，一会不可以

**Comment by binarywang** [comment]
@AaronFeng2014 是么，没有什么规律吗？

**Comment by binarywang** [comment]
诡异问题，暂时忽略

**Comment by Penghaiku** [comment]
电脑端配置
![image](https://user-images.githubusercontent.com/46412151/79032973-04fe8780-7bdd-11ea-81ab-2c93637d9bfd.png)

将你要回复的文本复制到 word ，然后编辑好，比如换行操作，如下所示

使用公众号插件 （壹伴）等等，设置自动回复超链接的时候好用一些，其他的不太行

回复效果
手机页面
![image](https://user-images.githubusercontent.com/46412151/79032969-0039d380-7bdd-11ea-93ff-3e3f5dd2cfce.png)


由上图可知，word中的回车代表换行，可在手机中正常显示

这是我一次巧合发现的，大家还可以试试使用markdown格式写一些回复，渲染的话应该是一样的

可以关注我的公众号测试一下，哈哈！！！
