### ISSUE TITLE
微信申请退款接口组装退款代金券空指针

### ISSUE THREAD

**Issue by begin-zero** [binarywang/WxJava#646]
![image](https://user-images.githubusercontent.com/20488236/41863614-e6e6ef74-78d9-11e8-9016-5b0686859050.png)
![image](https://user-images.githubusercontent.com/20488236/41863675-1b77d55a-78da-11e8-86d7-916c90454314.png)
第一张图是退款接口已经返回数据了，但是退款申请失败了，接着下一步组装代金券的时候就空指针了，
this.getCouponRefundCount()是null的

**Comment by begin-zero** [comment]
this.getCouponRefundCount()是null的

**Comment by binarywang** [comment]
可否直接提供下修复代码，在develop分支提交PR即可，非常感谢

**Comment by binarywang** [comment]
看来楼主不方便，我已抽空提交了修复代码

**Comment by binarywang** [comment]
3.1.1.BETA测试版本已修复
