### ISSUE TITLE
有没有 wx.getShareInfo  encryptedData 的解密算法？

### ISSUE THREAD

**Issue by zhongminsheng** [binarywang/WxJava#648]
我使用  WxMaCryptUtils.decrypt  这个能解密，但是结果是乱码：
{
  "result" : "\u000F��d\"`[h�`�PXb�\b��r��m1\n�\u0018\u0000��ĕn&N�;\u0016�Ʋ�\u0007��p}O�/\u0005\u0013\u001BX��ew\u001A�}\u0014����L|GsSݜ���q��\u0014�\u0003�\u000F\u0019��\u0010gi�_\u001E��Z�X�\u0000*�\t\u0019\u000B�3\u000FJΈ"
}

**Comment by binarywang** [comment]
解密算法应该是一致的，看你得到的数据并非完全乱码，至少是个json串的形式，有可能只是字符编码的问题，你可以再调试看看

**Comment by whoooami** [comment]
b2Ѳ"���A���֮4cz2�o9g��*�Z�����,u$��rG�&]�#e(Gd�On��e�u[�Iy�5m�>��W�H$L�N
�;Ah��P��<o�'�.��5)\
���ؑ�
<img width="670" alt="WX20201111-180104@2x" src="https://user-images.githubusercontent.com/2926551/98798376-c9fd5480-2448-11eb-8b74-f692ee17cc7b.png">
我这边也是乱码。。。
