### ISSUE TITLE
pay模块可以增加代扣相关接口吗？

### ISSUE THREAD

**Issue by coullin** [binarywang/WxJava#650]
一直在用这个工具，非常不错，最近公司准备接入微信服务商模式，网上搜了一圈没发现相关开源的工具可用，官方直接就说没有demo，不知道这个功能能否考虑加进去呢？

**Comment by binarywang** [comment]
你是说服务商模式，还是说代扣？

**Comment by binarywang** [comment]
代扣的话，应该是跟 #590 是同一个问题吧？

**Comment by coullin** [comment]
服务商模式可以帮合作商家发起代扣，发起支付，退款等

**Comment by binarywang** [comment]
那说到底其实跟服务商模式还是没关系，没有服务商，其它接口一样是有的

**Comment by binarywang** [comment]
另外服务商版的代扣接口文档在哪里？

**Comment by binarywang** [comment]
没有进一步响应，暂时关闭
