### ISSUE TITLE
群发消息的通知事件建议增加原创校验结果的部分

### ISSUE THREAD

**Issue by tzraeq** [binarywang/WxJava#651]
如题，建议增加原创校验结果的部分，该元素为CopyrightCheckResult
文档地址为，https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1481187827_i0l21

**Comment by binarywang** [comment]
这基本属于体力活了，内容还不少，抽空看下

**Comment by tzraeq** [comment]
如果可以，可以我来做，没问题的，我给你提交RP

**Comment by binarywang** [comment]
那再好不过了，非常期待

**Comment by binarywang** [comment]
这个我曾经尝试过，最后放弃了，涉及到xstream转换，比较恶心。

**Comment by binarywang** [comment]
看来楼主没时间，我刚给WxMpXmlMessage增加了allFieldsMap属性， 用于存放所有xml属性和值，这样方便提取微信服务器发送过来的所有消息数据。

**Comment by binarywang** [comment]
3.2.4.B测试版本 已添加allFieldsMap，欢迎测试使用
