### ISSUE TITLE
weixin-java-mp-deom这个项目是怎么进入不同的Handler的

### ISSUE THREAD

**Issue by 1002679811** [binarywang/WxJava#655]
当我点击菜单栏的click事件会进入MenuHandler  当我发送文本信息会进入MsgHandler  当我发送地图信息会进入LocationHandler，但我找不到哪个地方判断他们进入不同的Handler进行处理的，不解决这里无法扩展呀，请各位能帮下我

**Comment by binarywang** [comment]
看router代码，另外不知道你说的是哪个demo，demo有很多，建议去对应demo下面提问问题，更有针对性
