### ISSUE TITLE
wxService.getUserService().getUserInfo获取不到unionid

### ISSUE THREAD

**Issue by nsspw** [binarywang/WxJava#657]
其他信息都能获取到，为什么unionid获取不到，谢谢

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140839 是否仔细阅读过此文档？

**Comment by nsspw** [comment]
好的，感谢提醒

**Comment by nsspw** [comment]
“只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段。”
