### ISSUE TITLE
小程序需要增加上报用户数据后台接口

### ISSUE THREAD

**Issue by 0xbillw** [binarywang/WxJava#659]
例如：[上报用户数据后台接口setUserStorage](https://developers.weixin.qq.com/minigame/dev/document/open-api/data/setUserStorage.html)是需要POST调用：
`POST https://api.weixin.qq.com/wxa/set_user_storage?access_token=ACCESS_TOKEN&signature=SIGNATURE&openid=OPENID&sig_method=SIG_METHOD`
中openid是要加在url查询参数上这个好处理，但是signature我想库应该有现成的支持吧。可是我看代码并没有找到，我想应该是有的:)

**Comment by binarywang** [comment]
目前可以参考`com.github.binarywang.wxpay.util.SignUtils#createHmacSha256Sign`实现，微信支付模块里的代码

**Comment by 0xbillw** [comment]
谢谢回复！其实我觉得像这种微信API属于安全协议层能不能封装在内部，对外只需要关注业务参数，就像淘宝API的SDK一样？

**Comment by binarywang** [comment]
是可以的，只不过之前很少有人用到这个接口，所以就没实现，以后也许会加上。只是目前建议你可以先按上面说的自己实现。

**Comment by binarywang** [comment]
3.1.2.BETA版本已增加，欢迎帮忙验证
