### ISSUE TITLE
XXE防范

### ISSUE THREAD

**Issue by weifengzh** [binarywang/WxJava#660]
收到了微信的一个风险提醒：
您的系统在接受微信支付XML格式的商户回调通知（支付成功通知、退款成功通知、委托代扣签约/解约/扣款通知、车主解约通知）时，如未正确地进行安全设置或编码，将会引入有较大安全隐患的XML 外部实体注入漏洞(XML External Entity Injection，简称 XXE)。
请贵司研发人员务必参考微信支付安全实践指引：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5
其中：
【JAVA】
DocumentBuilderFactory dbf =DocumentBuilderFactory.newInstance();
dbf.setExpandEntityReferences(false);

这个对我们使用parseOrderNotifyResult等方法需要进行相关的处理吗？

**Comment by binarywang** [comment]
解析方式不一样，没有这种问题

**Comment by binarywang** [comment]
我们sdk里使用的是xstream1.4.9版本，没有这个问题，请放心使用
