### ISSUE TITLE
微信支付申请退款结果封装 WxPayRefundResult 缺少字段 coupon_refund_fee

### ISSUE THREAD

**Issue by luqil** [binarywang/WxJava#663]
com.github.binarywang.wxpay.bean.result.WxPayRefundResult
根据微信官方API查看 缺少字段 coupon_refund_fee
已检查目前的develop 分支 同样缺少该字段

**Comment by binarywang** [comment]
这不是一个字段，是有可能有多个的，格式为coupon_refund_fee_x，麻烦再仔细看下文档？

**Comment by luqil** [comment]
关于这个字段我仔细看文档了，应该是缺少该字段。
摘录官方文档：

现金支付币种 | cash_fee_type | 否 | String(16) | CNY
现金退款金额 | cash_refund_fee | 否 | Int | 100
代金券类型 | coupon_type_$n | 否 | String(8) | CASH
代金券退款总金额 | coupon_refund_fee | 否 | Int | 100
代金券类型 | coupon_type_$n | 否 | String(8) | CASH
**代金券退款总金额 | coupon_refund_fee | 否 | Int | 100**
单个代金券退款金额 | coupon_refund_fee_$n | 否 | Int | 100
退款代金券使用数量 | coupon_refund_count | 否 | Int | 1
退款代金券ID | coupon_refund_id_$n | 否 | String(20) | 10000

请看加粗字段：
**代金券退款总金额 | coupon_refund_fee | 否 | Int | 100**

该字段为缺少字段，这个是总金额。不是多个的封装。

在支付成功的封装中WxPayOrderNotifyResult，包含的类似字段coupon_fee 代金卷总额
在退款结果反馈中WxPayRefundResult，缺失了该字段coupon_refund_fee 代金券退款总金额
多个是单个退款代金卷信息，而不是总额。
我用的解决方案是统计了以下单张的退款代金卷金额，计算总额信息。

**Comment by binarywang** [comment]
好吧，这个我怀疑有可能是后期加上的，最初应该是没有吧，下次提问题最好把文档地址贴一下，方便核对，谢谢及时提出。

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_4

**Comment by luqil** [comment]
好的

**Comment by binarywang** [comment]
3.1.2.BETA版本已增加
