### ISSUE TITLE
请问关于XML解析存在的安全问题指引有规避吗？

### ISSUE THREAD

**Issue by liuzhihai520** [binarywang/WxJava#664]
微信安全提示连接：https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=23_5

**Comment by binarywang** [comment]
先看下#660，另外提问前建议先看下是否已有人询问过相关问题。

**Comment by liuzhihai520** [comment]
你好，我查看了。关于#660的相关问题描述，确实重复了，之后会仔细提问。但我检查依赖包，发现xstream版本为1.4.9，并非1.4.10，这个版本解析方式不一样的话，应该也没问题吧？

**Comment by binarywang** [comment]
1.4.9也没问题，已经修复相关问题了。具体可以看其公告：http://x-stream.github.io/news.html
