### ISSUE TITLE
微信支付的沙箱环境能否使用？

### ISSUE THREAD

**Issue by abcfy2** [binarywang/WxJava#668]
我发现这个沙箱环境真是坑爹，只说要调用getSignKey，我发现已经实现这个接口了，调用这个之后就不知道怎么用了，正常请求一直报错:

```
<return_msg><![CDATA[沙箱验证签名失败，请确认沙箱签名key是否正确（通过getsignkey调用生成）]]></return_msg>
```

我看了下源码，是否并没有对沙箱环境这个signkey做特殊处理？只是实现了getSignKey接口而已？是否可以把这个逻辑封装进去呢？在`WxPayConfig`中设置了`setUseSandboxEnv(true)`之后能否自动处理沙箱环境？

或者在目前的条件下，应该怎么自己处理这个逻辑呢？我遍寻了下微信支付的文档，也没提这个沙箱环境怎么用的，getsignkey之后怎么放入请求中？

**Comment by binarywang** [comment]
按照逻辑，应该是你使用沙箱环境前，先要自己手动调用getSignKey生成key，然后把这个key配置到配置文件里，目前setUseSandboxEnv 这个只是用来控制请求接口地址的。
总不能每次调用接口都生成一次key吧？那个生成key的接口不知道是否有次数限制，所以最好的办法就是按我之前所说。

**Comment by abcfy2** [comment]
我的考虑是本地使用了一个静态缓存。

Groovy Code:
```groovy
    private static String SANDBOX_SIGN_KEY
    private static final WxPayConfig WX_PAY_CONFIG

    static {
        WX_PAY_CONFIG = new WxPayConfig()
        WX_PAY_CONFIG.setNotifyUrl(NOTIFY_URL)
        WX_PAY_CONFIG.setAppId(APPID)
        WX_PAY_CONFIG.setKeyPath(KEY_PATH)
        WX_PAY_CONFIG.setMchId(MCH_ID)
        WX_PAY_CONFIG.setMchKey(MCH_KEY)
        WX_PAY_CONFIG.setTradeType(TRADE_TYPE)
        WX_PAY_CONFIG.setUseSandboxEnv(USE_SANDBOX_ENV)
        WX_PAY_CONFIG.setSignType(WxPayConstants.SignType.HMAC_SHA256)
    }

    private static <T extends BaseWxPayResult> T withRequest(Closure<T> closure) {
        WxPayService wxPayService = new WxPayServiceImpl()
        wxPayService.setConfig(WX_PAY_CONFIG)

        if (WX_PAY_CONFIG.isUseSandboxEnv) {
            if (!SANDBOX_SIGN_KEY) {
                SANDBOX_SIGN_KEY = wxPayService.getSignKey()
            }

            WX_PAY_CONFIG.setMchKey(SANDBOX_SIGN_KEY)
            wxPayService.setConfig(WX_PAY_CONFIG)
        }

        closure.call(wxPayService)
    }
```

但是这么写的话发现还是会报同样的错误

**Comment by binarywang** [comment]
我记得之前确实沙箱环境确实是没法用的，现在不清楚了，你如果发现走不通，建议还是放弃吧，直接走正式的接口吧

**Comment by abcfy2** [comment]
好吧，这玩意确实没有使用文档

**Comment by abcfy2** [comment]
阿西吧，总算搞清楚了，无意中看了下微信支付的官方sdk: https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=11_1

才发现如果启用了沙箱环境，那么`SignType`只能是`MD5`，靠。微信支付的sdk源码它就这么写的(在`src/main/java/com/github/wxpay/sdk/WXPay.java`源码文件中，其中一行就有这个判断)。这个玩意居然在整片官方文档找不到一句话的描述，醉了。

然而更麻烦的还在后面，微信支付的沙箱环境不能随便填金额，使用上比正式环境还麻烦，你必须在`微信支付商户接入验收助手`这个公众号申请你的验收case，写入验收金额作为use case。一分不能多，一分不能少，否则报错: `沙箱支付金额(1)无效，请检查需要验收的case`。微信的接入配置本身就麻烦的要死，很多地方都要超级管理员权限，开发者哪有这玩意……

忍不住再吐槽一下，从未见过微信这么烂的开发环境，文档乱的一P，前后不搭，文档缺失。连个沙箱环境的限制都这么多，比正式环境使用还麻烦，要你何用？

**Comment by itcuihao** [comment]
哈哈哈，我也遇到这个了，昨天被坑了一天，一直以为签名错误。

**Comment by 247989011** [comment]
【公众号支付】沙箱验收用例
若商户接入的支付方式为“公众号支付”，则需要通过公众号支付对应的全部用例。其中有7个必选，1个可选。
 
【必选】公众号支付 支付成功用例集  ▽
用例1【公众-正常】订单金额1.01元，用户支付成功 
用例2【公众-正常】订单金额1.02元（含0.01元充值代金券，0.02元免充值代金券），用户支付成功 
▽ 【必选】公众号支付 支付异常用例集  ▽
用例3【公众-异常】订单金额1.3元，用户支付成功，商户未收到微信支付结果通知 
用例4【公众-异常】订单金额1.31元，用户支付失败，商户未收到微信支付结果通知 
用例5【公众-异常】订单金额1.32元，用户支付成功，微信支付重复通知商户 
用例6【公众-异常】订单金额1.33元，用户支付成功，微信支付通知签名非法 
用例7【公众-异常】订单金额1.34元，用户支付成功，微信支付通知关键信息不一致 
▽ 【可选】公众号支付 可选用例集  ▽
用例8【公众-对账】订单金额1.79元，支付成功，通知失败，对账不平

**Comment by huskyui** [comment]
> 阿西吧，总算搞清楚了，无意中看了下微信支付的官方sdk: https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=11_1
> 
> 才发现如果启用了沙箱环境，那么`SignType`只能是`MD5`，靠。微信支付的sdk源码它就这么写的(在`src/main/java/com/github/wxpay/sdk/WXPay.java`源码文件中，其中一行就有这个判断)。这个玩意居然在整片官方文档找不到一句话的描述，醉了。
> 
> 然而更麻烦的还在后面，微信支付的沙箱环境不能随便填金额，使用上比正式环境还麻烦，你必须在`微信支付商户接入验收助手`这个公众号申请你的验收case，写入验收金额作为use case。一分不能多，一分不能少，否则报错: `沙箱支付金额(1)无效，请检查需要验收的case`。微信的接入配置本身就麻烦的要死，很多地方都要超级管理员权限，开发者哪有这玩意……
> 
> 忍不住再吐槽一下，从未见过微信这么烂的开发环境，文档乱的一P，前后不搭，文档缺失。连个沙箱环境的限制都这么多，比正式环境使用还麻烦，要你何用？

看了这个，那我就不用了

**Comment by idlesysman** [comment]
获取沙箱密钥需要真实的密钥签名

**Comment by xiaokuang95** [comment]
可以用一个类继承WxPayServiceImpl 里面写一个init方法加上注解@PostConstruct,在声明bean @Bean(initMethod = "init"),这样每次启动项目会调用一次沙箱环境的接口获取key `@PostConstruct
  public void init() throws WxPayException {
    WxPayConfig config = getConfig();
    boolean useSandboxEnv = config.isUseSandboxEnv();
    if (useSandboxEnv) {
      String sandboxSignKey = getSandboxSignKey();
      config.setMchKey(sandboxSignKey);
      setConfig(config);
    }
  }`
