### ISSUE TITLE
Security framework of XStream not initialized, XStream is probably vulnerable.

### ISSUE THREAD

**Issue by xiongmingwu** [binarywang/WxJava#670]
如题，微信推送的component_verify_ticket消息解析提示如下信息(红色标注)：

![image](https://user-images.githubusercontent.com/31282628/42427099-3e5c6344-835f-11e8-8d99-23a761478acf.png)

maven信息如下:
```
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-open</artifactId>
    <version>3.1.0</version>
</dependency>
```

**Comment by binarywang** [comment]
这是因为你自己使用了XStream 1.4.10 出现的警告吧。目前看问题不大，如果你自己不放心，可以自行增加相关设置，网上有解决方案。
