### ISSUE TITLE
开放平台

### ISSUE THREAD

**Issue by 475cheng** [binarywang/WxJava#671]
微信公众号的weixin-java-mp 里可以实现消息回复，群发，素材上传， 但是在weixin-java-open 开放平台中我也想实现公众号的消息回复，群发，素材上传等功能，目前 还没有代码支持吧？

**Comment by 475cheng** [comment]
开发平台的微信功能代码实现都需要自己写吗？

**Comment by lurongze** [comment]
有的，具体查看群主的demo.类似这样
WxMpService wxMpService = wxOpenService.getWxOpenComponentService().getWxMpServiceByAppid(appId);

**Comment by 475cheng** [comment]
我下载了weixin-java-open-demo但是pom中没有引用weixin-java-mp，如果我想消息回复，群发，素材上传是不是这俩要联合起来使用
<artifactId>weixin-java-open</artifactId>和<artifactId>weixin-java-mp</artifactId>

**Comment by binarywang** [comment]
仔细分析下代码模块依赖关系，没有明确引用就一定没有吗？本身open模块就已经依赖了mp

**Comment by 475cheng** [comment]
好的，open确实依赖了mp， 我在仔细看看，现在确定用weixin-java-open-demo开发 微信开放平台是可行的。
