### ISSUE TITLE
小程序中未包含jssdk相关后台支持？

### ISSUE THREAD

**Issue by HuNanPengdake** [binarywang/WxJava#672]
根据官方文档中的关于web-view组件提到的，小程序网页中也是支持部分jssdk接口的，但是同样需要后台支持提供wx.config的参数内容，但是weixin-java-miniapp包内没有相关方法，请问该如何操作？

**Comment by HuNanPengdake** [comment]
这个是关于web-view的地址：https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html

**Comment by binarywang** [comment]
还没在小程序里用过jssdk，能否明确一下需要实现具体哪个接口？比如mp里的哪个？

**Comment by HuNanPengdake** [comment]
作者你好，我不是特指哪一个js-sdk的接口，而是我们weixin-java-tools的小程序模块没有对jd-sdk这块提供支持，或者是否需要考虑把js-sdk模块单独抽离，作为框架我想这个也是有必要的，虽然目前来说微信自身也不提倡在小程序中使用网页实现某些接口功能。这个issue只是一个建议，不是描述某个问题。

**Comment by binarywang** [comment]
这个建议不错，可以考虑抽离

**Comment by binarywang** [comment]
仔细看了下，其实涉及jsapi的就三个接口，没必要抽取出来一个单独的模块，就直接在小程序模块里实现相关接口了

**Comment by binarywang** [comment]
3.1.5.BETA测试版本已添加
