### ISSUE TITLE
微信支付--一直报签名错误

### ISSUE THREAD

**Issue by endlesslove123** [binarywang/WxJava#673]
微信支付一直报签名错误，找了各种解决办法都不行

**Comment by XieGuanLing** [comment]
可以参考https://my.oschina.net/desert/blog/760567
重新生成证书

**Comment by binarywang** [comment]
楼主参考楼上所提供文章尝试一下看看，如果问题解决了及时给个答复，谢谢二位了

**Comment by endlesslove123** [comment]
已经解决了，谢谢各位的帮助，是商户号参数不对
