### ISSUE TITLE
需要暴露HttpClient的 ClientConnectionPoolManager 线程池设置参数

### ISSUE THREAD

**Issue by XieGuanLing** [binarywang/WxJava#676]
ClientConnectionPoolManager maintains a maximum limit of connection on a per route basis and in total. Per default this implementation will create no more than than 2 concurrent connections per given route and no more 20 connections in total. For many real-world applications these limits may prove too constraining, especially if they use HTTP as a transport protocol for their services. Connection limits, however, can be adjusted using ConnPoolControl methods.

**Comment by binarywang** [comment]
有什么好的实现代码吗？欢迎提供PR

**Comment by binarywang** [comment]
楼主表意不清楚，猜测这个[wiki](https://github.com/Wechat-Group/weixin-java-tools/wiki/HttpClient%E7%9B%B8%E5%85%B3%E5%8F%82%E6%95%B0%E7%9A%84%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95)已经能够满足你的需求
