### ISSUE TITLE
微信申请退款接口composeRefundCoupons问题

### ISSUE THREAD

**Issue by bongq417** [binarywang/WxJava#682]
https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=9_4
微信文档明确数不一定会返回coupon_refund_count字段，但是代码里没有判空，导致NPE.

jar包版本3.1.0
![image](https://user-images.githubusercontent.com/3860164/42943271-d9816aa8-8b94-11e8-81cb-f772145de3d6.png)
<img width="591" alt="wx20180719-205037 2x" src="https://user-images.githubusercontent.com/3860164/42943501-79ee96d2-8b95-11e8-813e-0f6fa30dd066.png">

**Comment by bongq417** [comment]
@binarywang

**Comment by binarywang** [comment]
这还真是个问题，如果可以，建议提交个PR，谢谢及时发现并指出此问题。

**Comment by binarywang** [comment]
才发现你提出的这个问题已经修复了， #646，下次问问题麻烦看下最新代码吧
