### ISSUE TITLE
获取体验小程序的体验二维码接口（wxa/get_qrcode）缺少path参数

### ISSUE THREAD

**Issue by lidongzhangg** [binarywang/WxJava#686]
微信文档地址：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489140610_Uavc4&token=&lang=zh_CN

![image](https://user-images.githubusercontent.com/11748156/43201337-c8757a14-904a-11e8-9273-3a829c861056.png)
如下代码：
https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-miniapp/src/main/java/cn/binarywang/wx/miniapp/api/impl/WxMaServiceImpl.java
![image](https://user-images.githubusercontent.com/11748156/43201418-0250377e-904b-11e8-9f26-a40a63c18ad8.png)

**Comment by binarywang** [comment]
谢谢及时指出，估计是后来接口有变动。
另外下次发帖请尽量贴上文档地址，而不仅仅是截图。

**Comment by binarywang** [comment]
@charmingoh

**Comment by lidongzhangg** [comment]
好的，文档地址已经贴上 @binarywang

**Comment by binarywang** [comment]
3.1.5.BETA测试版本已添加相关参数
