### ISSUE TITLE
WxMpXmlMessage扩展方法

### ISSUE THREAD

**Issue by cherry-yang-workspace** [binarywang/WxJava#687]
请问下对于推送的消息中相关的字段，在WxMpXmlMessage中没有该字段，如何扩展，直接继承是有问题的。
比如：卡券审核不通过，会推送一个card_not_pass_check事件，这个里面有一个参数 RefuseReason ，但现在的WxMpXmlMessage中是没有这个参数的，应该如何扩展呢？

**Comment by binarywang** [comment]
目前没有想到比较好的办法，建议在WxMpXmlMessage添加相关参数及其对应处理代码，然后提交PR代码

**Comment by gzlboy** [comment]
过了3年了。。。请问现在有办法扩展吗？WxMpXmlMessage缺不少属性

**Comment by binarywang** [comment]
早已经扩展，看最新源码，使用里面的map字段自己读取
