### ISSUE TITLE
微信企业付款到零钱接口因其返回结果变化解析xml有问题

### ISSUE THREAD

**Issue by keren-lee** [binarywang/WxJava#688]
吐槽一下微信的接口，有点返人类，企业付款到用户零钱接口返回的mchid没有下滑线分开mch_id，导致解析XML失败，BaseWxPayResult里面的这个参数为mch_id。

**Comment by binarywang** [comment]
这个可以修复一下，不过目前影响不大，毕竟mch_id是跟你传入的那个同名参数值是一样的。
