### ISSUE TITLE
微信支付退款Bug，定位类BaseWxPayServiceImpl

### ISSUE THREAD

**Issue by luqil** [binarywang/WxJava#693]
微信支付退款失败时程序出现空指针。
定位位置: com.github.binarywang.wxpay.service.impl.BaseWxPayServiceImpl 第94行。
退款错误：errCode="ERROR",errCodeDes=“订单已全额退款” 时，Coupon信息为空值，造成调用第94行时出现空指针。
 @Override
  public WxPayRefundResult refund(WxPayRefundRequest request) throws WxPayException {
    request.checkAndSign(this.getConfig());

    String url = this.getPayBaseUrl() + "/secapi/pay/refund";
    String responseContent = this.post(url, request.toXML(), true);
    WxPayRefundResult result = BaseWxPayResult.fromXML(responseContent, WxPayRefundResult.class);
    result.composeRefundCoupons();
    result.checkResult(this, request.getSignType(), true);
    return result;
  }

解决方案：应判断errCode结果，抛出指定异常，而非空指针。

**Comment by binarywang** [comment]
#646 此问题早已修复，另外请注意观看其他人发的issue，以及develop分支的代码
