### ISSUE TITLE
企业微信缺少OA数据接口

### ISSUE THREAD

**Issue by webcreazy** [binarywang/WxJava#698]
企业微信缺少OA数据接口

官方文档：https://work.weixin.qq.com/api/doc#12423
目前有：
1、获取打卡规则
请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/checkin/getcheckinoption?access_token=ACCESS_TOKEN

2、获取打卡数据
请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/checkin/getcheckindata?access_token=ACCESS_TOKEN

3、获取审批数据
通过本接口来获取公司一段时间内的审批记录。一次拉取调用最多拉取10000个审批记录，可以通过多次拉取的方式来满足需求，但调用频率不可超过600次/分。

请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/corp/getapprovaldata?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
最新接口文档地址：https://work.weixin.qq.com/api/doc#90000/90135/90261

**Comment by einsitang** [comment]
进行中

**Comment by chenqi940727** [comment]
> 进行中

大佬，大概什么时间能发布出来呢

**Comment by einsitang** [comment]
@chenqi940727 抱歉，接口其实从设计到编码已经完成了，不过没有相关的账号信息以及最近有点忙，耽搁了，你可以联系我提供一下企业微信的信息方便我完成测试，尽早合并代码吗？

**Comment by binarywang** [comment]
> @chenqi940727 抱歉，接口其实从设计到编码已经完成了，不过没有相关的账号信息以及最近有点忙，耽搁了，你可以联系我提供一下企业微信的信息方便我完成测试，尽早合并代码吗？

你先把代码提交了吧，我抽空帮你找账号测试下

**Comment by einsitang** [comment]
> > @chenqi940727 抱歉，接口其实从设计到编码已经完成了，不过没有相关的账号信息以及最近有点忙，耽搁了，你可以联系我提供一下企业微信的信息方便我完成测试，尽早合并代码吗？
> 
> 你先把代码提交了吧，我抽空帮你找账号测试下

PR：https://github.com/Wechat-Group/WxJava/pull/1013#issue-272263873

**Comment by chenqi940727** [comment]
> @chenqi940727 抱歉，接口其实从设计到编码已经完成了，不过没有相关的账号信息以及最近有点忙，耽搁了，你可以联系我提供一下企业微信的信息方便我完成测试，尽早合并代码吗？

我这边还没开始开发，也没有正式的账号，只有个简单的测试账号

**Comment by binarywang** [comment]
3.3.9.B测试版本已增加
