### ISSUE TITLE
统一下单接口为何不返回timestamp?

### ISSUE THREAD

**Issue by gitkmw** [binarywang/WxJava#702]
`@PostMapping("/unifiedOrder")
    public WxPayUnifiedOrderResult unifiedOrder(@RequestBody WxPayUnifiedOrderRequest request) throws WxPayException {
        return this.wxService.unifiedOrder(request);
    }`
在WxPayUnifiedOrderResult对象中为何不新增返回一个timestamp?

**Comment by binarywang** [comment]
这个方法是微信原装方法，没做特殊处理。可以参考下另外一个封装好的方法createOrder
