### ISSUE TITLE
微信开放平台缺少代小程序实现业务接口

### ISSUE THREAD

**Issue by HuNanPengdake** [binarywang/WxJava#703]
开放平台中，代小程序实现业务的功能，目前只实现了授权相关的功能，如成员管理、代码管理、模板库管理、基础信息设置等功能都没有实现。

官网文档连接：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489144594_DhNoV&token=&lang=

**Comment by binarywang** [comment]
#759 已实现了大部分接口
