### ISSUE TITLE
企业微信 应用管理 缺少接口

### ISSUE THREAD

**Issue by webcreazy** [binarywang/WxJava#707]
文档：
https://work.weixin.qq.com/api/doc#10087

只实现了获取应用接口

缺少
设置应用
请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/agent/set?access_token=ACCESS_TOKEN

获取应用列表
请求方式：GET（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/agent/list?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
3.1.7.BETA测试版本已添加
