### ISSUE TITLE
企业微信 素材管理 缺少两个接口

### ISSUE THREAD

**Issue by webcreazy** [binarywang/WxJava#708]
获取高清语音素材

可以使用本接口获取从JSSDK的uploadVoice接口上传的临时语音素材，格式为speex，16K采样率。该音频比上文的临时素材获取接口（格式为amr，8K采样率）更加清晰，适合用作语音识别等对音质要求较高的业务。
请求方式：GET（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/media/get/jssdk?access_token=ACCESS_TOKEN&media_id=MEDIA_ID

上传图片

    上传图片得到图片URL，该URL永久有效
    返回的图片URL，仅能用于图文消息（mpnews）正文中的图片展示；若用于非企业微信域名下的页面，图片将被屏蔽。
    每个企业每天最多可上传100张图片

请求方式：POST（HTTPS）
请求地址：https://qyapi.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
3.2.0版本已添加上传图片接口

**Comment by binarywang** [comment]
获取高清语音素材
 文档地址：https://work.weixin.qq.com/api/doc#90000/90135/90255

**Comment by binarywang** [comment]
3.2.8.B测试版本已增加获取高清语音素材接口，欢迎试用
