### ISSUE TITLE
企业微信 WxCpUser 类匹配问题

### ISSUE THREAD

**Issue by webcreazy** [binarywang/WxJava#709]
文档地址：https://work.weixin.qq.com/api/doc#10018

在企业微信通讯录管理，成员管理中

创建成员、更新成员中
头像字段是 avatar_mediaid 需要用素材管理上传返回的mediaid

读取成员、获取部门成员详情中
头像字段是 avatar 图片的URL

看到cp bean 源码中 WxCpUser 只有 avatar  这个要怎么处理

**Comment by webcreazy** [comment]
1、重新定义多个只有几个字段不同的类，
2、还是定义一个包含所有字段的，
3、还是定义一个只包含通用属性的类，然后继承子类添加不同的属性？

**Comment by binarywang** [comment]
在原类里定义即可，没必要这么麻烦。

**Comment by binarywang** [comment]
3.1.6.BETA 版本已添加
