### ISSUE TITLE
支付回调校验签名失败

### ISSUE THREAD

**Issue by huhuixin** [binarywang/WxJava#712]
发现当用户使用微信支付的时候,如果使用了优惠券就会签名校验失败

WxPayOrderNotifyResult result = payService.parseOrderNotifyResult(xmlData);
SignUtils.checkSign(result, wxPayConfig.getSignType(), wxPayConfig.getMchKey()) 会返回false

使用的版本是3.0.0

**Comment by huhuixin** [comment]
继续追踪了一下,发现用户使用优惠券的时候,微信支付返回了coupon_id_$ 和 coupon_fee_$ 字段,但是并没有返回 coupon_type_$ , 而在封装返回值的时候在 com.github.binarywang.wxpay.bean.notify.WxPayOrderNotifyCoupon 类中发现 这三个字段是绑定的,这时候去createSign的时候 map里多出了一个 支付回调xml里并不存在的 coupon_fee_$ 造成了签名校验失败

**Comment by binarywang** [comment]
你看最新版是否还有此问题？

**Comment by binarywang** [comment]
楼主 还方便不？

**Comment by binarywang** [comment]
没有反馈，暂时关闭，如有问题直接回复即可
