### ISSUE TITLE
微信支付 创建订单报异常 CannotResolveClassException

### ISSUE THREAD

**Issue by kdstarter** [binarywang/WxJava#714]
JDK8，使用 Maven 导入 weixin-java-pay 3.1.0，创建订单本地 Mac 正常，
`WxPayUnifiedOrderResult signResult = wxPayService().createOrder(orderRequest);`,

然而部署到 Ubuntu 服务器上时一直报异常
`com.thoughtworks.xstream.mapper.CannotResolveClassException: com.github.binarywang.wxpay.bean.result.WxPayUnifiedOrderResult`

**Comment by binarywang** [comment]
仔细阅读下方法的注释吧，你这个返回值用得不对

**Comment by kdstarter** [comment]
@binarywang 它异常报的是哪个，我就换成对应的返回类型，也是同样的 CannotResolveClassException。
更奇怪的是我本地开发一直是对的。

**Comment by binarywang** [comment]
那看来是classloader问题，你需要自己排查下了

**Comment by kdstarter** [comment]
@binarywang 目前确认了是Tomcat7 环境问题，
本地使用 Tomcat 9 + idea explored war 或 Tomcat server.xml 里配置 `<Context path="/" docBase="IdeaProjects/target_folder" />` 方式，正常；
然而本地换成 Tomcat 7  + server.xml 里配置就报同样的异常了。

**Comment by kdstarter** [comment]
终于解决了，是 slf4j-jdk14-1.5.6.jar 和 logback-classic-1.0.7.jar 冲突了。
因为项目一直启动正常，没注意到Tomcat的启动异常。

![image](https://user-images.githubusercontent.com/1996554/44326305-cb1fc100-a48d-11e8-9593-6ef4136893d9.png)

**Comment by binarywang** [comment]
这看起来是个无关的信息似的

**Comment by kdstarter** [comment]
将Tomcat 7升级到 Tomcat 9，再解决这个包冲突问题，就解决了
