### ISSUE TITLE
如何支持多个订阅号？

### ISSUE THREAD

**Issue by nullsz** [binarywang/WxJava#72]
如何支持多个订阅号？使用springboot

**Comment by binarywang** [comment]
参考demo，有一个用spring mvc实现的https://github.com/wechat-group/weixin-mp-multi-demo ，你自己仿照做就行了

**Comment by nullsz** [comment]
@binarywang 这个demo不是我想要的 我要支持的公众很多，这个demo针对每个公众号都要有一个config , service controller... 我的初步想法是封装一个WxMpConfigStorageManage 和 WxMpServiceManage  里面包含多个公众号的配置，由appid来关联，controller我可以写一个或 多个 ， 你觉得这种方式怎么样？

**Comment by binarywang** [comment]
你可以使用动态代理生成那些东西，不过感觉你的需求可能借助于第三方平台实现会更好些，建议你去看看相关文档吧

**Comment by nullsz** [comment]
@binarywang  谢谢你了，第三方平台考虑过，但是和公司业务差距太大！
