### ISSUE TITLE
获取JSAPI时报错，请问这是版本问题吗？

### ISSUE THREAD

**Issue by Jayns** [binarywang/WxJava#720]
java.lang.NoSuchMethodError: org.apache.commons.codec.digest.DigestUtils.sha1Hex(Ljava/lang/String;)
我目前用的是commons-codec-1.5  里面没有sha1Hex方法

**Comment by Jayns** [comment]
//这个方法已经过期
String sha1 = DigestUtils.shaHex(bytes);
//使用这个方法
String sha1 = DigestUtils.sha1Hex(bytes);

**Comment by binarywang** [comment]
明显是jar版本问题
