### ISSUE TITLE
wxmpservice 无法注入

### ISSUE THREAD

**Issue by tianyw0** [binarywang/WxJava#721]
环境：
tomcat web 项目

代码
```
package com.taobao.controller.pay.wx.controller; 

import me.chanjar.weixin.mp.api.WxMpService;

....
@Autowired
    protected WxMpService wxMpService;
```

配置
```
<context:component-scan base-package="com.taobao." />
```

报错信息
2018-08-20 17:35:04 [ERROR] - org.springframework.web.servlet.DispatcherServlet -FrameworkServlet.java(492) -Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'coreServiceImpl': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: protected me.chanjar.weixin.mp.api.WxMpService com.taobao.service.pay.service.impl.CoreServiceImpl.wxMpService; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMpService' defined in class path resource [com/taobao/controller/pay/wx/config/MainConfiguration.class]: Instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public me.chanjar.weixin.mp.api.WxMpService com.taobao.controller.pay.wx.config.MainConfiguration.wxMpService()] threw exception; nested exception is java.lang.NoSuchFieldError: INSTANCE

**Comment by binarywang** [comment]
建议去参考demo做法

**Comment by tianyw0** [comment]
注：demo 做法是指 本项目readme 中提到的参考demo 
[demo项目](https://github.com/Wechat-Group/weixin-java-tools/blob/master/demo.md)

**Comment by tianyw0** [comment]
参考 demo项目之后 改了，配置文件成
```
<!--扫描web相关的bean-->
    <context:component-scan base-package="com.taobao.controller">
        <context:exclude-filter type="annotation"
                                expression="org.springframework.stereotype.Controller" />
    </context:component-scan>
```

仍然报错（下面报错信息 为方便查看  人为加入了回车）
```
2018-08-20 21:57:37 [ERROR] - org.springframework.web.servlet.DispatcherServlet -FrameworkServlet.java(492) -Context initialization failed


org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'wxMpService' defined in class path resource [com/taobao/controller/pay/wx/config/MainConfiguration.class]: Instantiation of bean failed; 

nested exception is org.springframework.beans.factory.BeanDefinitionStoreException: Factory method [public me.chanjar.weixin.mp.api.WxMpService com.taobao.controller.pay.wx.config.MainConfiguration.wxMpService()] threw exception; 

nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.apache.http.impl.conn.ManagedHttpClientConnectionFactory
```

似乎是因为这个类 引起的 org.apache.http.impl.conn.ManagedHttpClientConnectionFactory ？

请大神再帮忙看看  不胜感激
@binarywang
