### ISSUE TITLE
springboot2.0.4的兼容问题

### ISSUE THREAD

**Issue by mohuangNPC** [binarywang/WxJava#723]
您好，这个sdk开发工具某些包不适用于springboot2.0.4应该如何解决

**Comment by binarywang** [comment]
不知道你指的什么？能否具体些

**Comment by binarywang** [comment]
楼主可以先看下这个新的demo： https://github.com/binarywang/weixin-java-cp-demo-springboot2.0
有问题可以随时交流，不过请尽量说清楚具体些
