### ISSUE TITLE
微信支付jsapi MD5签名验证失败

### ISSUE THREAD

**Issue by gitSuper** [binarywang/WxJava#724]
使用weiixn-java-pay  3.1.0版本
在签名StringUtils 中
  if (SignType.HMAC_SHA256.equals(signType)) {
      return createHmacSha256Sign(toSign.toString(), signKey);
    } else {
      return DigestUtils.md5Hex(toSign.toString()).toUpperCase();
    }

其中MD5的 采用了 md5Hex  加密 最终与微信端加密结果不符  改成MD5 方式 验证通过

**Comment by binarywang** [comment]
没明白你的意思，请问你所谓的MD5 方式代码是如何写的？

**Comment by binarywang** [comment]
楼主能否详细解释下？

**Comment by orangeyts** [comment]
public static String md5Hex(final String data) {
        return Hex.encodeHexString(md5(data));
 }
是不是说直接 md5就可以了，不需要搞成16进制的字符串，我这里统一签名正确，但是小程序发起支付，就报 **支付验证签名失败**

**Comment by binarywang** [comment]
字节数组要转换成字符串，不用16进制字符串，那要怎么做？

**Comment by binarywang** [comment]
楼主无法联系到，暂时忽略，如果有问题请直接回复即可
