### ISSUE TITLE
现金红包接口签名错误

### ISSUE THREAD

**Issue by linguohui** [binarywang/WxJava#726]
V3.1.0 调用发送现金红包接口提示签名错误，经排查发现是signType不用参与签名。
接口
WxPayService
WxPaySendRedpackResult sendRedpack(WxPaySendRedpackRequest request) throws WxPayException;

解决办法
WxPaySendRedpackRequest覆写ignoreSignType方法
protected boolean ignoreSignType() {
    return true;
  }

**Comment by binarywang** [comment]
3.1.6.BETA 版本已修复
