### ISSUE TITLE
客服发送图文消息疑问？

### ISSUE THREAD

**Issue by lgl48128244** [binarywang/WxJava#728]
客服发送图文消息时，图文里面的描述字段description的字体大小和颜色怎么改？默认是灰色的
[https://images.gitee.com/uploads/images/2018/0824/101014_07c5b476_581610.png](url)
[https://images.gitee.com/uploads/images/2018/0824/101051_23c5725c_581610.png](url)

**Comment by lgl48128244** [comment]
[https://images.gitee.com/uploads/images/2018/0824/101014_07c5b476_581610.png](url)
[https://images.gitee.com/uploads/images/2018/0824/101051_23c5725c_581610.png](url)

**Comment by binarywang** [comment]
请查阅相关文档，应该是没有对应设置的，所以无法实现

**Comment by lgl48128244** [comment]
@binarywang 关键是其它公司的公众号可以实现，你可以关注下荔枝微课的公众号看下自动回复里有一条图文消息，里面的描述字段（description）字体与颜色。

**Comment by binarywang** [comment]
至少接口发送的图文消息是没法改的，你看官方文档就知道了，没有对应参数。有可能你说的那个公众号跟腾讯有些私下约定的接口参数可用，也说不定。

**Comment by lgl48128244** [comment]
@binarywang 非常感谢！
