### ISSUE TITLE
缺少客服输入状态接口

### ISSUE THREAD

**Issue by shoubaozi** [binarywang/WxJava#730]

**Comment by binarywang** [comment]
咋又关闭了？我看这个接口估计是新加的，确实还没实现

**Comment by shoubaozi** [comment]
关注这个项目一年了，最近自己在写一个公众号，才开始研究，边看你源码，边看微信官方文档 ，发现这个功能用户体验特别好。但是对这个项目不是非常熟悉，不敢确认是还没来得及实现这个接口，还是我没找到。。。。 所以关闭了  （第一次用issues功能，本来想删除的 ，但是没找到，我重新开启吧）

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140547 文档地址重新贴上来以便参考

**Comment by binarywang** [comment]
3.1.9.B版本已增加
