### ISSUE TITLE
微信开放平台-获取小程序体验者列表

### ISSUE THREAD

**Issue by xiongmingwu** [binarywang/WxJava#737]
我看了最新版的源代码 3.1.6.BETA，没有发现实现该接口！是否会实现？

接口文档如下：
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489140588_nVUgx&token=&lang=zh_CN

![image](https://user-images.githubusercontent.com/31282628/44841900-09c82f00-ac77-11e8-82e9-d1e4cb81d2ca.png)

**Comment by binarywang** [comment]
可以考虑加上

**Comment by xiongmingwu** [comment]
好的 谢谢！有大致的时间节点吗？

**Comment by binarywang** [comment]
这个说不好，如果比较急，建议可以自行实现然后提交PR，看起来这个接口挺简单的。

**Comment by binarywang** [comment]
这个 #703 也提到过
