### ISSUE TITLE
建议修改WxCpMessage 中agentId的数据类型

### ISSUE THREAD

**Issue by terlanks** [binarywang/WxJava#74]
最新的企业微信已经推出，经测试，cp框架依然可用，但是这次微信对一些字段的类型做了check，原来agentId在转json中使用String型是不会出异常的，现在却会因为使用了“agentid”而抛出invalid input的错误，建议修改。已测试改成int过后，并不影响原有调用sendmessage的功能。

**Comment by binarywang** [comment]
感谢提出这个问题，建议提交一个PR，多谢了~
当然如果没有兴趣或没时间做提交，请尽量提供涉及到的文件，后期有能力帮忙修改的会帮忙操作~
