### ISSUE TITLE
建议添加docker支持，很流行

### ISSUE THREAD

**Issue by 15838028035** [binarywang/WxJava#740]
建议添加docker支持，很流行

**Comment by binarywang** [comment]
没明白你说的支持是什么意思，我们这是个SDK，感觉不着边际似的

**Comment by 15838028035** [comment]
使用docker进行项目构建

**Comment by binarywang** [comment]
那你期待SDK里能做什么？

**Comment by 15838028035** [comment]
使用docker构建项目，你先了解一下docker吧

**Comment by binarywang** [comment]
我知道docker是什么？能否举个例子，如果可以，提交点PR代码吧？

**Comment by binarywang** [comment]
楼主方便答复下吗？
如果你说一个 springboot 项目或者普通web项目使用 docker 去构建，虽然没做过，但我觉得实现起来也许并不会太复杂，但你说要让sdk使用docker构建，我就搞不懂了，sdk也就只是发布成jar包，放在maven仓库里，供实际的项目去引用，感觉跟docker完全搭不上边呢。
所以如果可以，麻烦给个实例吧，非常感谢，想学习下。

**Comment by binarywang** [comment]
https://github.com/binarywang/weixin-java-mp-demo-springboot/pull/19 我猜测楼主所说的支持是这里所加入的吧，跟sdk没关系

**Comment by 15838028035** [comment]
没关系

发自我的 iPhone
