### ISSUE TITLE
关于公众号模块对session管理的体验以及建议

### ISSUE THREAD

**Issue by VirensCn** [binarywang/WxJava#741]
使用了公众号，因为项目是集群，所以缓存这块是使用的redis。在使用WxMpMessageRouter里面的WxSessionManager的时候就出现了问题。你这个里面没有提供基于Redis实习的session管理器，Redis也不需要使用复杂的InternalSessionManager来管理session。只管取和存就是了。

WxMpMessageRouter 类当中对任意消息进行路由的时候并不是根据formUser获取到session后给消息处理器使用session，而是直接把WxSessionManager给了处理器，让自行获取。但是在处理完成之后偏偏又去调用sessionEndAccess来结束formUser对应的session。

同样就是sessionEndAccess这个方法，在结束session访问的过程是直接将sessionManager强转InternalSessionManager获取消息。而sessionManager这个变量只提供了set方法，并且参数是WxSessionManager 的实现类，没有提供get方法。导致自行覆写sessionEndAccess方法来实现redis的session管理时，根本没法拿到sessionManager。如果不覆写也会因为sessionManager强转InternalSessionManager异常。除非自定义的sessionManager既实现了WxSessionManager 也实现了InternalSessionManager。

但是前文说了根本用不到InternalSessionManager里面的复杂session管理，毕竟都不需要自己去用线程管理session是否有效。

////////////////、》。。。。。。。。。。。。

建议：
1、不要单独启用线程去管理session，而是在获取session的时候直接去判断session时候有效。有效就返回，无效改新建就新建，该返回null就返回null。
2、WxMpMessageRouter.sessionManager 提供get方法，以便覆写sessionEndAccess的时候自行去处理
3、在消息路由的时候建议不要直接给WxSessionManager ，而是只给对应formUser的session。而且可以在消息路由之前根据formUser获取到session后给处理器，在处理完成之后将session提交到WxSessionManager 中，实现刷新缓存

**Comment by binarywang** [comment]
欢迎直接提供PR，本身session也没怎么用，看你研究的也挺深入的，非常期待你的代码。

**Comment by ningxz** [comment]
@VirensCn 欢迎大神提 PR 很多使用者应该都会遇到该问题, 希望大家一起完善它
@binarywang 该项目服务了很多开发者，感谢！

**Comment by VirensCn** [comment]
> @VirensCn 欢迎大神提 PR 很多使用者应该都会遇到该问题, 希望大家一起完善它
> @binarywang 该项目服务了很多开发者，感谢！

这项目我报错..... 缺 get set 方法。

**Comment by binarywang** [comment]
先了解下lombok

**Comment by binarywang** [comment]
楼主有没有新的进展？

**Comment by binarywang** [comment]
暂时关闭，楼主如果有兴趣完善，请直接提供PR，谢谢
