### ISSUE TITLE
退款回调时对mchkey做md5加密时，当加密结果首位是0的情况下，会出现加密结果是31位的情况

### ISSUE THREAD

**Issue by w435044190** [binarywang/WxJava#742]
退款回调时WxPayRefundNotifyResult 类对mchkey做md5加密时，当加密结果首位是0的情况下，会出现加密结果是31位的情况
比如对“37381208bbce2acddc69e6aa2c6597d8”字符串加密，获得加密结果是149ee4840bbaf838affca6d31d25ee1，实际结果是0149ee4840bbaf838affca6d31d25ee1

**Comment by binarywang** [comment]
这个用最新测试版，已经修复了
