### ISSUE TITLE
WxMaConfiguration作用

### ISSUE THREAD

**Issue by mozengxiong** [binarywang/WxJava#743]
WxMaConfiguration是什么作用呢？怎么使用

**Comment by mozengxiong** [comment]
public WxMaMessageRouter router(WxMaService service) {
        final WxMaMessageRouter router = new WxMaMessageRouter(service);
        router
                .rule().handler(logHandler).next()
                .rule().async(false).content("模板").handler(templateMsgHandler).end()
                .rule().async(false).content("文本").handler(textHandler).end()
                .rule().async(false).content("图片").handler(picHandler).end()
                .rule().async(false).content("二维码").handler(qrcodeHandler).end();
        return router;
    }

这段代码什么作用呢

**Comment by binarywang** [comment]
qq群里已经讨论过了，这里不再答复
