### ISSUE TITLE
企业微信消息推送

### ISSUE THREAD

**Issue by 13872341960** [binarywang/WxJava#749]
我是新手不好意思啊，有个问题想请教一下，就是关于推送模板标题那里，微信规则是，标题那里，不管是什么类型的手机，标题部分最多只显示两行，这个行数可以认为修改吗

**Comment by binarywang** [comment]
仔细阅读文档，如果文档里没有相关参数，那就是不能改，否则怎么能改？

**Comment by binarywang** [comment]
看你的内容提到了推送模版，有点懵，这是个什么鬼？
能否用标准下你的用语呢？
我看了一圈文档，猜测你说的有可能是 文本卡片消息，对不对？
别告诉我不是企业微信，而是公众号里的模版消息？
