### ISSUE TITLE
小程序SDK依赖lombok不能识别版本号

### ISSUE THREAD

**Issue by daimengying** [binarywang/WxJava#750]
在miniapp项目中pom的lombok未识别到版本号，导致WxMaJscode2SessionResult类上的Date和EqualsAndHashCode注解不能使用

**Comment by binarywang** [comment]
没看明白你的意思，你确定真正理解lombok的工作原理吗？

**Comment by daimengying** [comment]
lombok里@Date注解会在编译时为属性添加get set方法，但是因为小程序SDK中添加的lombok依赖没有用指定版本而是springboot默认版本，所以并没有找到该版本的lombok，导致WxMaJscode2SessionResult类以及其他类使用到lombok的注解全都报错，其实是因为并没有引入到这个包，但在编译时是正常的，所以并不影响客户端使用。主要是在看SDK源码的时候看到一堆红的就想改。

**Comment by binarywang** [comment]
版本号是在父pom文件里指定的，这涉及到maven的相关工作机制

**Comment by binarywang** [comment]
楼主搞明白了没？先暂时关闭了，有问题请直接回复即可
