### ISSUE TITLE
微信支付申请退款接口

### ISSUE THREAD

**Issue by wlff** [binarywang/WxJava#753]
楼主，  退款接口最近是不是做过更新， 添加了退款代金券？
==========================================
/**
   * 退款代金券使用数量.
   */
  @XStreamAlias("coupon_refund_count")
  private Integer couponRefundCount;

 /**
   * 组装生成退款代金券信息.
   */
  public void composeRefundCoupons() {
    List<WxPayRefundCouponInfo> coupons = Lists.newArrayList();
    for (int i = 0; i < this.getCouponRefundCount(); i++) {
      coupons.add(
        new WxPayRefundCouponInfo(
          this.getXmlValue("xml/coupon_refund_id_" + i),
          this.getXmlValueAsInt("xml/coupon_refund_fee_" + i),
          this.getXmlValue("xml/coupon_type_" + i)
        )
      );
    }
    this.setRefundCoupons(coupons);
  }
=============================================
WxPayRefundResult类中couponRefundCount这个字段是新增的吗,  如果微信返回的结果里没有这个值的话,   默认值为Null,   
"for (int i = 0; i < this.getCouponRefundCount(); i++) {"   这块貌似会报空指针

**Comment by wlff** [comment]
是不是该给这个字段加个初始值0

**Comment by binarywang** [comment]
这个已经修复过了，请使用最新的BETA版本

**Comment by wlff** [comment]
<dependency>
            <groupId>com.github.binarywang</groupId>
            <artifactId>weixin-java-pay</artifactId>
            <version>3.1.0</version>
        </dependency>
我是直接在pom.xml里加的依赖， 请问最新的beta版本还是3.1.0吗

**Comment by wlff** [comment]
感谢楼主， 找到了， 已解决
