### ISSUE TITLE
微信支付申请退款接口可能需要移除参数

### ISSUE THREAD

**Issue by TeamFushigi** [binarywang/WxJava#755]
对照了下， 现在微信官方的退款申请中，已经没有op_user_id 字段
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=9_4

> <xml>

   <appid>wx2421b1c4370ec43b</appid>
   <mch_id>10000100</mch_id>
   <nonce_str>6cefdb308e1e2e8aabd48cf79e546a02</nonce_str> 
   <out_refund_no>1415701182</out_refund_no>
   <out_trade_no>1415757673</out_trade_no>
   <refund_fee>1</refund_fee>
   <total_fee>1</total_fee>
   <transaction_id></transaction_id>
   <sign>FE56DD4AA85C0EECA82C35595A69E153</sign>
</xml>

目前的请求为
<xml>
  <appid>-</appid>
  <mch_id>-</mch_id>
  <nonce_str>-</nonce_str>
  <sign>-</sign>
  <out_trade_no>-</out_trade_no>
  <out_refund_no>-</out_refund_no>
  <total_fee>-</total_fee>
  <refund_fee>-</refund_fee>
  <op_user_id>-</op_user_id>
  <notify_url>-</notify_url>
</xml>

结果会导致微信返回签名错误

**Comment by binarywang** [comment]
确定是问题吗？

**Comment by hhzhi** [comment]
遇到同样的问题。退款提示签名错误， 微信官方退款接口没有 op_user_id 字段。代码给了默认的 OpUserId

public void checkAndSign(WxPayConfig config) throws WxPayException {
        if (StringUtils.isBlank(this.getOpUserId())) {
            this.setOpUserId(config.getMchId());
        }

        super.checkAndSign(config);
    }

**Comment by hhzhi** [comment]
https://developers.weixin.qq.com/community/develop/doc/000ae67212ceb8932f3a5401156c00

**Comment by hhzhi** [comment]
https://developers.weixin.qq.com/community/develop/doc/000ae67212ceb8932f3a5401156c00

官方已明确删除  op_user_id
