### ISSUE TITLE
支付验证签名失败

### ISSUE THREAD

**Issue by yidaimiyaokang2lou** [binarywang/WxJava#756]
小程序二次签名都过了，已经调起扫码界面，但扫码之后提示“支付验证签名失败”
![1536580412097](https://user-images.githubusercontent.com/19790108/45296005-36abfa00-b533-11e8-8b87-69cacfbb25e7.jpg)

![image](https://user-images.githubusercontent.com/19790108/45296111-91455600-b533-11e8-999c-cfb8bb274db1.png)

请问大大不能用微信开发者工具进行测试吗？
 统一下单调我本机的可以吗？http://localhost:8080/wechat/pay/unifiedOrder,

**Comment by yidaimiyaokang2lou** [comment]
由于缺少package，和时间戳，我在java后台二次验签后拼了一下，这样可以吗？
    WxPayUnifiedOrderResult r = this.wxService.unifiedOrder(request);
    r.setPkg("prepay_id="+r.getPrepayId());
    r.setTimeStamp("1484901595");

**Comment by binarywang** [comment]
小程序的话可以参考官方提供的wx-js-utils，无需调用后台接口
