### ISSUE TITLE
统一下单成功后验签失败

### ISSUE THREAD

**Issue by ruikom** [binarywang/WxJava#757]
![a82ig km15w 46 _g yu](https://user-images.githubusercontent.com/21167281/45400744-f60dc700-b67f-11e8-8b8b-31aba2870fe1.png)

我在使用时发现这里影响了验签，正常情况下等于true&&false，所以统一下单后没法正常验签
weixin-java-pay
3.1.0

**Comment by binarywang** [comment]
没看明白你的意思，如果true&&false，那不是应该不会报验签错误吗？

**Comment by ruikom** [comment]
不好意思，我知道问题出在哪里了，谢谢
