### ISSUE TITLE
小程序解密用户手机号码异常

### ISSUE THREAD

**Issue by Flying17** [binarywang/WxJava#758]
WxMaCryptUtils.decrypt(sessionKey, encryptedData, ivStr)；
这个解密出来的是乱码，导致gson解析异常，报错如下：
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by binarywang** [comment]
这是个常见问题，请参考：https://github.com/Wechat-Group/weixin-java-tools/issues/359

**Comment by Flying17** [comment]
thx，原来我解密之前再次login了，导致sessionkey失效了，但是这个sessionkey不是每次刷新都会变，导致我有时可以有时不可以，导致我排除了sessionkey的锅

**Comment by SYZ-Coder** [comment]
> thx，原来我解密之前再次login了，导致sessionkey失效了，但是这个sessionkey不是每次刷新都会变，导致我有时可以有时不可以，导致我排除了sessionkey的锅

您好，你解密之前再次调用了login.?请问您不是先调用login,获取sessionKey，然后去解密的吗？我这也是偶尔解不出来

**Comment by IllusionOops** [comment]
我直接把前端获取到的参数打印，然后使用postman调用后端接口，进行解密用户手机号信息。偶尔会出现成功、失败交替进行；大部分时间，都是失败，然后偶尔成功。    这个错误到底是什么原因？  我现在是测试阶段，并未进入到开发阶段。所以通过postman进行接口调用，完全不存在重复登录导致sessionkey失效问题。    每个人的回答我都看了，但是依然没懂这个错误到底是什么原因？
