### ISSUE TITLE
小程序缺少 统一服务消息接口

### ISSUE THREAD

**Issue by wapmnw** [binarywang/WxJava#760]
小程序缺少 **统一服务消息接口**

官方文档：https://developers.weixin.qq.com/miniprogram/dev/api/open-api/uniform-message/sendUniformMessage.html

1、下发小程序和公众号统一的服务消息
请求方式：POST（HTTPS）
请求地址：https://api.weixin.qq.com/cgi-bin/message/wxopen/template/uniform_send?access_token=ACCESS_TOKEN

**Comment by binarywang** [comment]
3.2.0版本已添加
