### ISSUE TITLE
企业微信WxCpJedisConfigStorage不能指定DB

### ISSUE THREAD

**Issue by frank8g2g3** [binarywang/WxJava#762]
3.1版本 WxCpJedisConfigStorage 类的构造方法，没有jedispool直接传入的方法，也没指定的db的入参，@gaigeshen 
![image](https://user-images.githubusercontent.com/12781273/45735540-c714c980-bc1a-11e8-921c-7822c3455f88.png)

**Comment by gaigeshen** [comment]
See #763

**Comment by binarywang** [comment]
3.2.0版本已添加
