### ISSUE TITLE
企业微信好像没有套件设置

### ISSUE THREAD

**Issue by frank8g2g3** [binarywang/WxJava#765]
实际情况中很多应用都是以套件进行开发，但我查看了一下微信开发工具并没有套件这一块

**Comment by binarywang** [comment]
不清楚你说的套件是个什么东西，建议简单解释下，或者贴一下相关文档。

**Comment by frank8g2g3** [comment]
第三方应用的开发，像第三方服务商已经开发好，企业只需安装即可以用的这种。第三方服务商可能开发了几个应用，合在一起叫xxx套件，某公司安装此套件，他可以只安装他想要的应用。可能这种开发，应该很少用你们这个吧，微信文档 https://work.weixin.qq.com/api/doc#10968，附图
![image](https://user-images.githubusercontent.com/12781273/45856416-f1839580-bd86-11e8-98b7-0b50b890aad1.png)
![image](https://user-images.githubusercontent.com/12781273/45856441-17109f00-bd87-11e8-9b72-f00f9886f755.png)

@binarywang

**Comment by binarywang** [comment]
其实不就是https://github.com/Wechat-Group/weixin-java-tools/issues/493 这里提到的吗，那就重复了，目前没计划做这个，用的人实在是太少了。

**Comment by frank8g2g3** [comment]
好吧，没注意看到这个问题
