### ISSUE TITLE
如何检测公众号是否绑定过第三方平台？

### ISSUE THREAD

**Issue by lgl48128244** [binarywang/WxJava#767]
当用户登录后怎么去获取此用户注册过的公众号绑定过的第三方平台？
样例： https://www.jianshu.com/p/9bb51c8a2cfb

**Comment by lgl48128244** [comment]
感谢 @binarywang @007gzs 支持，问题解决。https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN
序号为9的标题内容：当公众号对第三方平台进行授权、取消授权、更新授权后，微信服务器会向第三方平台方的授权事件接收URL（创建第三方平台时填写）推送相关通知。微信会回调换取ticket接口，可获取相应授权标识信息。

**Comment by binarywang** [comment]
那不应关闭吗？怎么又开启了？
