### ISSUE TITLE
WxMaCodeExtConfig 类缺少对 TabBar 属性字段

### ISSUE THREAD

**Issue by ningxz** [binarywang/WxJava#769]
如题，作者是否可以在 WxMaCodeExtConfig 类里添加 tabBar 属性

**Comment by binarywang** [comment]
可以，应该是漏了

**Comment by binarywang** [comment]
3.2.0版本已添加

**Comment by ningxz** [comment]
> 3.2.0版本已添加

请问 3.2.0 的版本什么时候发布呀

**Comment by ningxz** [comment]
> > 3.2.0版本已添加
> 
> 请问 3.2.0 的版本什么时候发布呀

看到已经发布了

**Comment by binarywang** [comment]
是已经发布了，你没看到？

**Comment by ningxz** [comment]
> 是已经发布了，你没看到？

看到了
