### ISSUE TITLE
微信沙箱退款通知一直不成功

### ISSUE THREAD

**Issue by wlff** [binarywang/WxJava#771]
退款方法：  BaseWxPayServiceImpl.refund(WxPayRefundRequest)
  @Override
  public WxPayRefundResult refund(WxPayRefundRequest request) throws WxPayException {
    request.checkAndSign(this.getConfig());

    String url = this.getPayBaseUrl() + "/secapi/pay/refund";
    String responseContent = this.post(url, request.toXML(), true);
    WxPayRefundResult result = BaseWxPayResult.fromXML(responseContent, WxPayRefundResult.class);
    result.composeRefundCoupons();
    result.checkResult(this, request.getSignType(), true);
    return result;
  }

问题描述：
 楼主， 最近我在公司测试环境引入微信沙箱， 支付通知是可以收到的， 但是通款通知貌似一直不成功。百度查了下， 沙箱退款的请求地址如下： https://api.mch.weixin.qq.com/sandboxnew/pay/refund， 而不是直接在“/secapi/pay/refund”前面添加“sandboxnew”,  这块想找楼主确认下， 谢谢了。

**Comment by binarywang** [comment]
居然有此事，你所看到的文档在哪里？

**Comment by binarywang** [comment]
如果真如你所说，我估计reverseOrder这个接口地址应该也是类似的

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=23_1  看官方文档，完全没提到这回事，真是够坑爹的

**Comment by wlff** [comment]
CSDN上找到的一篇博文： https://blog.csdn.net/towtotow/article/details/79374452;
还有待验证， 但是我看Linux日志， 确实是没看到过退款通知过来。方法里面写死了，
我没法改沙箱退款的url。

**Comment by binarywang** [comment]
其实验证也很简单，一个办法就是下载源码，修改对应实现，跑下相应的单元测试；另外如果不想改源码，直接继承那个实现类，在里面修改对应方法也是可以的。

**Comment by wlff** [comment]
好的， 我试试

**Comment by binarywang** [comment]
经过测试加不加secapi，接口响应没有区别，也就是都是可以的，没有问题。不过不排除官方在看到本条issue后自己做的调整，不管怎样，现在没问题了。

另外你所说的退款通知是指什么？跟这个接口也没关系吧？

**Comment by wlff** [comment]
我做的是小程序的支付，正式环境向微信发送退款请求时会设置notify_url, 退款成功的话会调用notify_url指向的接口，也就是退款通知。用沙箱的话，我2种也试过了，返回的结果是一样的，但是都没通知，可能沙箱退款和沙箱支付不一样，沙箱退款确实没有通知吧，我再尝试几次，看看sandboxnew/pay/refund能不能收到通知

**Comment by binarywang** [comment]
能否收到异步回调通知，跟你调用什么接口没关系，当然前提是接口要已经调用成功了，关键是要看对方会不会发，以及你的回调地址是否外网可访问。
