### ISSUE TITLE
如何便捷的自定义HttpClientBuilder

### ISSUE THREAD

**Issue by fankun** [binarywang/WxJava#773]
整个工具能不能多增加扩展点 如：DefaultApacheHttpClientBuilder 类HttpClientBuilder 我想加点拦截器都不能很容易加上。可以多借鉴springboot customizer的相关设计.spring 的restTemplate设计思想还是非常不多的。希望您能够借鉴！

**Comment by binarywang** [comment]
@kakotor 有空也可以关注下

**Comment by binarywang** [comment]
暂时关闭，如果楼主有兴趣，直接提交PR即可
