### ISSUE TITLE
源码导入jdk7不能用

### ISSUE THREAD

**Issue by classyex** [binarywang/WxJava#775]
readme说最低支持jdk7的，但是我把源码导入myeclise的时候报错。是由于引用到一个jdk8的类。
`The type java.util.function.Predicate cannot be resolved. It is indirectly referenced from required .class files`

**Comment by binarywang** [comment]
你确定该类是本项目源码里用到的吗？

**Comment by binarywang** [comment]
你确定该类是本项目源码里用到的吗？

**Comment by classyex** [comment]
在这个项目里面并没有找到java.util.function.Predicate这个类的引用。我是新开的一个工作空间，里面只导入这个项目的源码，还配置了lombok，使用jdk7，其他的没有什么特别的。准备换一个jdk8试试。
是发布版本3.2.0那里下的源码

**Comment by binarywang** [comment]
经过确认是某些单元测试引用的assertj本身是依赖jdk8的，对非测试的源码没有影响，可以放心使用。

**Comment by classyex** [comment]
谢谢。了解。我换到jdk8源码就不报错了，在jdk7的项目引用发布的包也没问题
