### ISSUE TITLE
建议WxMpMenuService里面增加 String menuCreate(WxMpMenu menu)

### ISSUE THREAD

**Issue by wangjia2016** [binarywang/WxJava#777]
WxMpMenuService里面应该使用WxMpMenu 而不是WxMenu

目前只有 String menuCreate(WxMenu menu) throws WxErrorException;

建议增加 String menuCreate(WxMpMenu menu) throws WxErrorException;

目前看来 WxMenu WxMpMenu 两者还是有差别

**Comment by wangjia2016** [comment]
WxMenu 这个里面的 matchRule R是大写，微信文档里面是小写

**Comment by binarywang** [comment]
可以，期待你的代码

**Comment by thefirstwind** [comment]
指的是个性化菜单吗？

**Comment by binarywang** [comment]
不止，都包含

**Comment by binarywang** [comment]
仔细看了下，没必要，WxMpMenu只是获取菜单时候反序列化才用到的，对于反人类的微信接口定义来说，实在没必要保持一致了，也没法保持一致。
