### ISSUE TITLE
org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyToFile(Ljava/io/InputStream;Ljava/io/File;)V 	at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1287) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)

### ISSUE THREAD

**Issue by yang-mr** [binarywang/WxJava#780]
org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyToFile(Ljava/io/InputStream;Ljava/io/File;)V
	at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1287)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:961)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:877)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:966)

**Comment by binarywang** [comment]
方法没找到，自己检查下相应jar版本

**Comment by yang-mr** [comment]
是按照你 demo里的 jar版本的

**Comment by ChixianGen** [comment]
遇到了同样的问题，已解决，jar包换成 2.6的
`<dependency>
		    <groupId>commons-io</groupId>
		    <artifactId>commons-io</artifactId>
		    <version>2.6</version>
		</dependency>`

**Comment by binarywang** [comment]
楼主再仔细检查下，我是说报错的那个方法所在的类对应的jar包，不要理解错了
