### ISSUE TITLE
第三方平台每次推送拿到的component_verify_ticket值都一样？

### ISSUE THREAD

**Issue by lgl48128244** [binarywang/WxJava#782]
每十分钟推送的component_verify_ticket值都一样？

> 消息解密后内容为：
WxOpenXmlMessage(appId=wxb6242b3c9850af80, createTime=1538965574, infoType=component_verify_ticket, componentVerifyTicket=ticket@@@_E0msknX0nuNr0_AjHrpHZaanrrm0fRWBcA02ZabLMy6HWj_BypszayaOscxn1XmgTorb7Nqb97of7PEW1MP_Q, authorizerAppid=null, authorizationCode=null, authorizationCodeExpiredTime=null, preAuthCode=null) 
2018-10-08 10:26:14 INFO com.wwdx.controller.rest.OpenNotifyController:48 - 
消息解密后内容为：
WxOpenXmlMessage(appId=wxb6242b3c9850af80, createTime=1538965574, infoType=component_verify_ticket, componentVerifyTicket=ticket@@@_E0msknX0nuNr0_AjHrpHZaanrrm0fRWBcA02ZabLMy6HWj_BypszayaOscxn1XmgTorb7Nqb97of7PEW1MP_Q, authorizerAppid=null, authorizationCode=null, authorizationCodeExpiredTime=null, preAuthCode=null) 
2018-10-08 10:26:14 INFO com.wwdx.controller.rest.OpenNotifyController:60 - 
组装回复信息：success
2018-10-08 10:26:14 INFO com.wwdx.controller.rest.OpenNotifyController:60 - 
组装回复信息：success
2018-10-08 10:37:04 INFO com.wwdx.controller.rest.OpenNotifyController:48 - 
消息解密后内容为：
WxOpenXmlMessage(appId=wxb6242b3c9850af80, createTime=1538966224, infoType=component_verify_ticket, componentVerifyTicket=ticket@@@_E0msknX0nuNr0_AjHrpHZaanrrm0fRWBcA02ZabLMy6HWj_BypszayaOscxn1XmgTorb7Nqb97of7PEW1MP_Q, authorizerAppid=null, authorizationCode=null, authorizationCodeExpiredTime=null, preAuthCode=null) 
2018-10-08 10:37:04 INFO com.wwdx.controller.rest.OpenNotifyController:60 - 
组装回复信息：success
2018-10-08 10:46:20 INFO com.wwdx.controller.rest.OpenNotifyController:48 - 
消息解密后内容为：
WxOpenXmlMessage(appId=wxb6242b3c9850af80, createTime=1538966780, infoType=component_verify_ticket, componentVerifyTicket=ticket@@@_E0msknX0nuNr0_AjHrpHZaanrrm0fRWBcA02ZabLMy6HWj_BypszayaOscxn1XmgTorb7Nqb97of7PEW1MP_Q, authorizerAppid=null, authorizationCode=null, authorizationCodeExpiredTime=null, preAuthCode=null) 
2018-10-08 10:46:20 INFO com.wwdx.controller.rest.OpenNotifyController:48 - 
消息解密后内容为：
WxOpenXmlMessage(appId=wxb6242b3c9850af80, createTime=1538966780, infoType=component_verify_ticket, componentVerifyTicket=ticket@@@_E0msknX0nuNr0_AjHrpHZaanrrm0fRWBcA02ZabLMy6HWj_BypszayaOscxn1XmgTorb7Nqb97of7PEW1MP_Q, authorizerAppid=null, authorizationCode=null, authorizationCodeExpiredTime=null, preAuthCode=null)

**Comment by 007gzs** [comment]
这个没注意过，可以正常使用么?
