### ISSUE TITLE
企业微信模块增加群聊API支持

### ISSUE THREAD

**Issue by Svenshen** [binarywang/WxJava#783]
什么时候能对CP模块增加群聊API支持？

**Comment by binarywang** [comment]
请给出对应文档地址

**Comment by Svenshen** [comment]
https://work.weixin.qq.com/api/doc#13308

> 请给出对应文档地址

https://work.weixin.qq.com/api/doc#13308

**Comment by binarywang** [comment]
3.3.0已增加

**Comment by zjazj** [comment]
https://work.weixin.qq.com/api/doc#90000/90135/90248  企业微信模块向群推送消息API 支持

**Comment by binarywang** [comment]
@zjazj 有问题请新开issue，谢谢合作~
