### ISSUE TITLE
微信企业付款接口规则变更

### ISSUE THREAD

**Issue by nickwongwong** [binarywang/WxJava#785]
![image](https://user-images.githubusercontent.com/16626084/46664425-94476b00-cbf3-11e8-98b0-ac86349c84b8.png)
只在商户小程序接收到了变更通知，修改了部分的参数
新版文档地址
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/index.php/public/cms/content_detail?platformType=0&lang=zh&id=86200 公告地址
