### ISSUE TITLE
微信高并发 Timeout waiting for connection from pool

### ISSUE THREAD

**Issue by MemoryL7** [binarywang/WxJava#786]
weixin-java-mp.version : 2.9.0

**Comment by MemoryL7** [comment]
最后通过该方法发送的请求，要怎么设置相关参数？
private WxMpOAuth2AccessToken getOAuth2AccessToken(String url) throws WxErrorException {
        try {
            RequestExecutor<String, String> executor = SimpleGetRequestExecutor.create(this);
            String responseText = (String)executor.execute(url, (Object)null);
            return WxMpOAuth2AccessToken.fromJson(responseText);
        } catch (IOException var4) {
            throw new RuntimeException(var4);
        }
    }

**Comment by MemoryL7** [comment]
通过在WeixinService中init()方法里设置
DefaultApacheHttpClientBuilder 相关参数

**Comment by binarywang** [comment]
你的问题是什么，能否重新组织下？是两个吗？那标题里的那个是什么？

**Comment by thefirstwind** [comment]
并发量多少？

**Comment by ftong2010** [comment]
你的问题我也遇到了，比如在发送模板消息的时候，如果有20万用户，那会通过并发的方式来发送。默认的connection pool size是50,算上延迟，并发线程在60~70时就会遇到拿不到connection的问题.

你可以在configStorage里传入DefaultApacheHttpClientBuilder这个builder啊。你不是已经回答了自己的问题....

**Comment by binarywang** [comment]
表达不清晰，暂时关闭
