### ISSUE TITLE
微信支付退款回调 解析后有乱码

### ISSUE THREAD

**Issue by blokwap** [binarywang/WxJava#791]
微信支付退款异步通知解析后的对象：WxPayRefundNotifyResult（"refundRecvAccout":"\u93C0\uE219\u7CAF\u9422\u3126\u57DB\u95C6\u5815\u6336","refundAccount":"REFUND_SOURCE_RECHARGE_FUNDS","refundRequestSource":"API"})

【微信支付】退款异步通知, wxPayRefundNotifyResult={"refundRecvAccout":"鏀粯鐢ㄦ埛闆堕挶",）
经过weChatPayService.parseRefundNotifyResult 处理后 变成乱码

**Comment by binarywang** [comment]
跑了下单元测试`com.github.binarywang.wxpay.bean.notify.WxPayRefundNotifyResultTest`，没发现问题，不知道你的问题是如何产生的

**Comment by blokwap** [comment]
我也用微信返回的参数单独跑单元测试，没有出现问题，是unicode字符串，但是用实际手机环境跑流程，就解析出来乱码，请帮忙能给出一些解决问题的思路

**Comment by blokwap** [comment]
是我自己的问题，加了转码操作解决了
String refundRecvAccount = new String(wxPayRefundNotifyResult.getReqInfo().getRefundRecvAccout().getBytes("GBK"), "UTF-8");
