### ISSUE TITLE
缺少了 微信回调消息处理的类型 小程序审核结果 weapp_audit_success ，weapp_audit_fail

### ISSUE THREAD

**Issue by soulmz** [binarywang/WxJava#792]
![image](https://user-images.githubusercontent.com/10662992/46903340-037bd280-cf06-11e8-9a0c-2a3757e1805c.png)

补充文档地址 ：

6、获取审核结果

https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1489140610_Uavc4&token=&lang=zh_CN

**Comment by soulmz** [comment]
开放平台的代理小程序业务。

**Comment by binarywang** [comment]
最好是发下文档地址，而不是图片

**Comment by soulmz** [comment]
@binarywang  已补充。

**Comment by yuanqixun** [comment]
这个早就已经有的了。

**Comment by soulmz** [comment]
@yuanqixun 我没看到. 我使用的是3.2.0的 weixin-java-open 这个

**Comment by yuanqixun** [comment]
用开发快照版，3.2.0没有合并。

**Comment by soulmz** [comment]
@yuanqixun 了解。谢谢

@binarywang 大佬一般发布正式版的周期是一个月一次吗？

**Comment by binarywang** [comment]
正式版一般两到三个月发布一次，测试版视情况发布，可能1到2周。

**Comment by binarywang** [comment]
3.2.1.B测试版本已包含相关代码
