### ISSUE TITLE
使用weixin-java-pay统一下单时抛出异常java.lang.NoClassDefFoundError: me/chanjar/weixin/common/exception/WxErrorException

### ISSUE THREAD

**Issue by li5454yong** [binarywang/WxJava#793]
如题，单独使用weixin-java-pay时统一下单正常，在引入 weixin-java-common模块后再调用统一下单时抛出异常java.lang.NoClassDefFoundError: me/chanjar/weixin/common/exception/WxErrorException；
查看weixin-java-common包下的内容，发现不存在exception包，WxErrorException存在于error包下。
两个模块使用的都是3.2版本，不知道是不是版本问题

**Comment by binarywang** [comment]
你确定版本确实是一致的吗？仔细检查下运行时环境吧

**Comment by li5454yong** [comment]
是的，可以确定，都是3.2，目前已经改回3.0是没问题的
