### ISSUE TITLE
关于小程序获取访问数据接口返回异常

### ISSUE THREAD

**Issue by xjar-s** [binarywang/WxJava#796]
通过api获取日访问数据如下代码
```
  List<WxMaVisitTrend> list = service.getAnalysisService().getDailyVisitTrend(time,time);
for (WxMaVisitTrend wxMaVisitTrend : list){
}
```
微信端返回是有数据的 如下：
`【请求地址】: https://api.weixin.qq.com/datacube/getweanalysisappiddailyvisittrend?access_token=14_eLQE18k9Hc7TUmLMmk0-FKiPfz3toO0PIiaNh0P25nQtPxG1MoVDj7-gloECEAgV171GBhPl5VMosccAJ80pk-Ejhu5cUuyjwTuc2qZWuLfhfnzWkXc-dyuamrT6evtp-vyBzjjN-eWM3_zlHFDfAHALJH
【请求参数】：{"begin_date":"20181015","end_date":"20181015"}
【响应数据】：{"list":[{"ref_date":"20181015","session_cnt":7,"visit_pv":36,"visit_uv":3,"visit_uv_new":0,"stay_time_uv":492.3333,"stay_time_session":211,"visit_depth":2.4286}]}
`
但是 for循环list的时候 实体类却所有的属性值都是null，如下图所示：
![image](https://user-images.githubusercontent.com/35762289/46996266-a58dfb80-d14e-11e8-8a6a-0e7064dce98c.png)

**Comment by binarywang** [comment]
@charmingoh

**Comment by xjar-s** [comment]
> @charmingoh
请问这个要放到下一个版本处理吗？

**Comment by binarywang** [comment]
可能charming大神没时间关注，你如果有空可以自行提交PR，要不然就只能等着了

**Comment by binarywang** [comment]
楼主，我跑过单元测试`cn.binarywang.wx.miniapp.api.impl.WxMaAnalysisServiceImplTest#testGetDailyVisitTrend`，
没发现同样问题，你再确认下？

**Comment by FxSunshine** [comment]
模仿您测试方法写依旧是各个属性值都是为空
代码：

>  final WxMaAnalysisService wxMaAnalysisService = service.getAnalysisService();
>  Date twoDaysAgo = DateUtils.addDays(new Date(), -2);
>  List<WxMaVisitTrend> trends =  wxMaAnalysisService.getDailyVisitTrend(twoDaysAgo, twoDaysAgo);

> 【响应数据】：{"list":[{"ref_date":"20181031","session_cnt":25,"visit_pv":173,"visit_uv":9,"visit_uv_new":5,"stay_time_uv":202.4444,"stay_time_session":72.88,"visit_depth":2.48}]}

版本号： <weixin-java-tools.version>3.2.0</weixin-java-tools.version>

**Comment by xjar-s** [comment]
> 楼主，我跑过单元测试`cn.binarywang.wx.miniapp.api.impl.WxMaAnalysisServiceImplTest#testGetDailyVisitTrend`，
> 没发现同样问题，你再确认下？

模仿您测试方法写依旧是各个属性值都是为空
代码：

> final WxMaAnalysisService wxMaAnalysisService = service.getAnalysisService();
> Date twoDaysAgo = DateUtils.addDays(new Date(), -2);
> List trends = wxMaAnalysisService.getDailyVisitTrend(twoDaysAgo, twoDaysAgo);

> 【响应数据】：{"list":[{"ref_date":"20181031","session_cnt":25,"visit_pv":173,"visit_uv":9,"visit_uv_new":5,"stay_time_uv":202.4444,"stay_time_session":72.88,"visit_depth":2.48}]}

版本号： <weixin-java-tools.version>3.2.0</weixin-java-tools.version>

**Comment by binarywang** [comment]
有没有直接跑下单元测试看看？跟你的代码到底有什么不同？可能是其他什么地方干扰了？

**Comment by xjar-s** [comment]
还是不行哦 完全按照您的测试代码来写，然后我们没有其他的逻辑

**Comment by binarywang** [comment]
我是说你直接跑单元测试代码，看有没有问题，而不是按照单元测试代码写，不是一个概念，你需要仔细调试对比下。

**Comment by binarywang** [comment]
针对你的响应我做了模拟，输出完全没问题：
```
[WxMaVisitTrend(refDate=20181031, sessionCnt=25, visitPv=173, visitUv=9, visitUvNew=5, stayTimeUv=202.4444, stayTimeSession=72.88, visitDepth=2.48)]
```

**Comment by binarywang** [comment]
请问楼主有没有最新进展？

**Comment by binarywang** [comment]
暂时关闭，无法联系到楼主

**Comment by binarywang** [comment]
楼主有空可以在关注下此问题，看你又提交了新问题。
