### ISSUE TITLE
缺少获取小程序(线上版本)二维码接口

### ISSUE THREAD

**Issue by ningxz** [binarywang/WxJava#798]
接口文档: https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/qr-code.html

1. getWXACode
获取小程序码，适用于需要的码数量较少的业务场景。通过该接口生成的小程序码，永久有效，有数量限制:
POST https://api.weixin.qq.com/wxa/getwxacode?access_token=ACCESS_TOKEN

2. getWXACodeUnlimit
获取小程序码，适用于需要的码数量极多的业务场景。通过该接口生成的小程序码，永久有效，数量暂无限制:
POST https://api.weixin.qq.com/wxa/getwxacodeunlimit?access_token=ACCESS_TOKEN

3. createWXAQRCode
获取小程序二维码，适用于需要的码数量较少的业务场景。通过该接口生成的小程序码，永久有效，有数量限制:
POST https://api.weixin.qq.com/cgi-bin/wxaapp/createwxaqrcode?access_token=ACCESS_TOKEN

### 使用场景:
第三方平台发布小程序后，需要获取线上版本小程序二维码

**Comment by binarywang** [comment]
这三个接口早都有了吧，你确定看过代码么？`cn.binarywang.wx.miniapp.api.WxMaQrcodeService`

**Comment by ningxz** [comment]
@binarywang 看到了，不好意思，是我查找的方式有问题，麻烦关闭这个issue
