### ISSUE TITLE
调用获取accessToken服务无信任的证书，这个是哪里的错误 

### ISSUE THREAD

**Issue by 7th-tech** [binarywang/WxJava#799]
![default](https://user-images.githubusercontent.com/3904632/47075767-ca0dd480-d22f-11e8-9022-0cafabbdf084.png)

**Comment by binarywang** [comment]
感觉是你的jvm运行环境的问题，自己搜索下相关关键字找下解决办法吧

**Comment by binarywang** [comment]
比如可以试试这个：https://blog.csdn.net/youngmean/article/details/2755975

**Comment by 7th-tech** [comment]
谢谢，是这个问题
