### ISSUE TITLE
https问题PKIX path building failed

### ISSUE THREAD

**Issue by sloooda** [binarywang/WxJava#8]
在使用普通模式发送消息时，只设置了corpid、corpsecret、agentid三个参数：
WxCpInMemoryConfigStorage config = new WxCpInMemoryConfigStorage();
        config.setCorpId("...");      // 设置微信企业号的appid
        config.setCorpSecret("...");  // 设置微信企业号的app corpSecret
        config.setAgentId("0");     // 设置微信企业号应用ID
报错：
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at me.chanjar.weixin.cp.api.WxCpServiceImpl.getAccessToken(WxCpServiceImpl.java:128)

**Comment by chairmanview** [comment]
JCE无限制权限策略文件替换了吗？参下：
http://qydev.weixin.qq.com/wiki/index.php?title=%E5%8A%A0%E8%A7%A3%E5%AF%86%E5%BA%93%E4%B8%8B%E8%BD%BD%E4%B8%8E%E8%BF%94%E5%9B%9E%E7%A0%81

**Comment by binarywang** [comment]
@sloooda 问题解决了吗？

**Comment by binarywang** [comment]
长期不回复，暂时关闭

**Comment by izyh** [comment]
请问这个问题解决了吗？我替换了JCE无限制权限策略文件后还是不行。

**Comment by binarywang** [comment]
@izyh 你用的是最新版本吗？

**Comment by chanjarster** [comment]
@izyh  这个问题可能是微信的https证书不在JDK自带的证书库里，试试看用这个项目解决：

https://github.com/escline/InstallCert

**Comment by goodluck028** [comment]
我试了网上的几种方法都不行，干脆重装了jdk，然后就好了。

**Comment by nadirvishun** [comment]
同遇到此问题，重装jdk仍然不管用。个人感觉主要原因就是企业微信所用证书更换了，而java并不认识此证书。
试过的方法：
- 直接谷歌浏览器访问`https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=ID&corpsecret=SECRET`，然后浏览器中下载证书（导出dre和base64格式都不行），导入后仍不管用。
-  @chanjarster 提供的库下载的证书导入后可正常使用，唯一需要注意的是此库检测的jre路径可能是单独安装的jre路径`D:\Java\jre1.8.0_202\lib\security`，但我这边在idea中用的是jdk下的jre路径`D:\Java\jdk1.8.0_202\jre\lib\security`，所以如果不行，两个位置都装一下试试。

还有就是推荐查看证书的工具：[KeyStore Explorer](https://keystore-explorer.org/)，省的用命令行看了，还可以按照安装时间排序什么的。

--------
我个人情况来说，上面的方法虽然可行，但是经常是一开始报错，多次测试后才会持续一段时间不报错，重打开电脑又会报错，但在其它电脑上没有问题，这台电脑原先动过证书方面的，怀疑电脑证书有问题，感觉如果上述方法也不行，重装系统才是最终解决方法。

--------
目前升级了Win10，大版本升级，从`1909`升级到了`20H2`，正常了。。。。

**Comment by xusir13** [comment]
我也出找个问题了。怎么解决
