### ISSUE TITLE
menuCreat()可能存在的问题

### ISSUE THREAD

**Issue by laohezi** [binarywang/WxJava#80]
在实现类中的menuCreate(String agentId, WxMenu menu)方法中agentid 应该是传进来的agentId,而不是
+ this.configStorage.getAgentId();吧

 @Override
  public void menuCreate(WxMenu menu) throws WxErrorException {
    menuCreate(this.configStorage.getAgentId(), menu);
  }

  @Override
  public void menuCreate(String agentId, WxMenu menu) throws WxErrorException {
    String url = "https://qyapi.weixin.qq.com/cgi-bin/menu/create?agentid="
 # **+ this.configStorage.getAgentId();**
    post(url, menu.toJson());
  }

**Comment by binarywang** [comment]
看着像是有问题的，如果有时间你可以帮忙提交个PR上来。

**Comment by binarywang** [comment]
已修复
