### ISSUE TITLE
建议增加微信支付错误码的常量定义

### ISSUE THREAD

**Issue by nickwongwong** [binarywang/WxJava#800]
提高开发效率
例如：
https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3
![image](https://user-images.githubusercontent.com/16626084/47076761-1528e700-d232-11e8-97b5-5f4714b44a8e.png)

**Comment by binarywang** [comment]
感觉没有必要，基本微信支付的接口有返回错误代码的同时也会有错误描述，一目了然。

**Comment by nickwongwong** [comment]
![image](https://user-images.githubusercontent.com/16626084/47084796-3ea03d80-d247-11e8-8f9c-cf875ef2de5c.png)
这些magic value应该设置为常量合适吧

**Comment by binarywang** [comment]
这些常量已经有定义，请查阅相关类

**Comment by binarywang** [comment]
而且你自己的代码可以自己去写对应常量，只是一些常量而已

**Comment by binarywang** [comment]
另外你如果觉得有必要的话，可以整理下相关代码，自行提交PR，非常欢迎

**Comment by nickwongwong** [comment]
WxPayReportRequest.java确实有常量，不过错误码缺得不少；统一整理下，可能会方便大家使用吧
![image](https://user-images.githubusercontent.com/16626084/47086902-44008680-d24d-11e8-979a-28b84db3cbbd.png)
![image](https://user-images.githubusercontent.com/16626084/47087003-80cc7d80-d24d-11e8-85af-da5c82598620.png)
![image](https://user-images.githubusercontent.com/16626084/47087039-95a91100-d24d-11e8-9992-7e21ce1d7aed.png)

**Comment by binarywang** [comment]
3.2.5.B测试版本已增加
