### ISSUE TITLE
微信支付将于2018年11月1日起对普通服务商交易账单中个别字段进行优化更新

### ISSUE THREAD

**Issue by junetigerlee** [binarywang/WxJava#801]
大神好:

![image](https://user-images.githubusercontent.com/5466169/47128160-bd868c00-d2c2-11e8-9844-43af2eb2c58d.png)
ps:
 <weixin-java-pay.version>3.1.0</weixin-java-pay.version>
用的这个版本，请问哪个版本解决，什么时候可以更新？

**Comment by binarywang** [comment]
能否把你贴的图片里的文字和链接一并发出来，以供参考

**Comment by binarywang** [comment]
楼主能否把文档地址发下？

**Comment by binarywang** [comment]
楼主发完issue就失踪了么？
我只能照图片手动输入文字找到文档地址了。
http://kf.qq.com/faq/180925NRz6Jb180925e6jMRV.html

**Comment by binarywang** [comment]
3.2.5.B测试版本已优化调整
