### ISSUE TITLE
服务商现金红包是否缺少msgappid入参

### ISSUE THREAD

**Issue by wlff** [binarywang/WxJava#804]
楼主， 退款请求WxPaySendRedpackRequest这个类中是否缺少msgappid这个参数， 我查看官方文档，
服务商现金红包的入参里面msgappid是必填的， 我跑demo， 不传的话也会报错：
     <return_msg>参数错误:授理模式下msgappid字段必填,并且最长32字符.</return_msg>

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/tools/cash_coupon_sl.php?chapter=13_4&index=3  文档地址，有空核对下缺少的字段

**Comment by wlff** [comment]
我看的是这个文档， 其它字段都有， 只缺msgappid

**Comment by wlff** [comment]
不知道这次为啥没邮件通知， 不好意思， 最近没登账号， 更新已经看到了， 这个Issue应该可以关了。

**Comment by wlff** [comment]
最近没登账号， 更新已看到， 多谢了。

**Comment by binarywang** [comment]
不急着关闭，还没发布新版本，你怎么验证？

**Comment by binarywang** [comment]
还不用急着关闭，还没发布新版本，你怎么验证？

**Comment by wlff** [comment]
额，好吧， 我目前是自己写了个类继承它， 把这个变量加上了，  但是在开通条件这块卡住了(商户入驻90天， 连续交易30天才能开通现金红包功能)，  所以需要等一段时间才能验证。

**Comment by binarywang** [comment]
3.2.2.B版本已增加，请帮忙验证

**Comment by wlff** [comment]
已验证， 红包发送没问题。
