### ISSUE TITLE
springcloud 使用zuul的时候会超时

### ISSUE THREAD

**Issue by fufenghua** [binarywang/WxJava#814]
在springcloud的项目里面集成wx-pay，每次只要wx-pay里面的方法去访问微信的接口的时候，zuul就立马报错timeout  哪怕已经设置20s的超时。请问有谁遇到过这样的情况吗？

**Comment by binarywang** [comment]
估计是你自己网络环境的问题？不使用zuul会出现同样问题吗？

**Comment by fufenghua** [comment]
不是网络问题 ，估计也不是这个项目的问题，是hystrix超时了，我不清楚具体的原因是什么，我现在暂时是把hystrix的超时关了，zuul就不会再提示timeout了。
这个超时很奇怪，因为明明请求都没有超过2秒的，集成咱们这个jar的那个service都请求成功了，返回微信的正确响应了，没有任何问题，时间都在2秒内。但在这之前，zuul就先报timeout了。

**Comment by binarywang** [comment]
暂时关闭，如楼主有进一步研究结果，请直接回复即可
