### ISSUE TITLE
这个可以实现动态配置么

### ISSUE THREAD

**Issue by 82253452** [binarywang/WxJava#815]
如果我又N多个小程序，业务不是很复杂，但是需要动态配置，这个可以提供出一个单独的模块么

**Comment by constanine** [comment]
给个建议,你可以自己配置多个config实现类的bean的map(以业务名称为key,config为值)缓存,然后先从缓存里去config的bean在去创建services实例就好了啊

**Comment by binarywang** [comment]
请参考对应demo，这只是个sdk
