### ISSUE TITLE
查询企业付款接口的查询结果EntPayQueryResult缺少payment_time信息

### ISSUE THREAD

**Issue by SunshineTech** [binarywang/WxJava#821]
查询企业付款接口的查询结果文档里有payment_time，但EntPayResult类里没有payment_time相关信息

文档如下：https://pay.weixin.qq.com/wiki/doc/api/tools/mch_pay.php?chapter=14_3

**Comment by binarywang** [comment]
你确定是没有的吗？
`https://github.com/Wechat-Group/weixin-java-tools/blob/master/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/entpay/EntPayResult.java`

**Comment by SunshineTech** [comment]
不好意思，是EntPayQueryResult里没有

**Comment by SunshineTech** [comment]
查询企业付款接口的查询结果类是EntPayQueryResult，这个类里没有payment_time信息。

**Comment by binarywang** [comment]
那可以加上，估计也是后来加上的属性

**Comment by SunshineTech** [comment]
嗯，就是提醒你一下，在下个版本中加上。

**Comment by binarywang** [comment]
那先不用关闭，还没加上，加上后再关闭了

**Comment by binarywang** [comment]
才发现这个跟#785 相关。

**Comment by binarywang** [comment]
3.2.3.B测试版本已增加
