### ISSUE TITLE
企业付款API时，报错，不知道是证书错误还是？

### ISSUE THREAD

**Issue by nfudd** [binarywang/WxJava#822]
nested exception is java.lang.NoSuchFieldError: INSTANCE] with root cause
java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:144)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.initSSLContext(WxPayServiceApacheHttpImpl.java:127)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.createHttpClientBuilder(WxPayServiceApacheHttpImpl.java:94)
	at com.github.binarywang.wxpay.service.impl.WxPayServiceApacheHttpImpl.post(WxPayServiceApacheHttpImpl.java:62)
	at com.github.binarywang.wxpay.service.impl.EntPayServiceImpl.entPay(EntPayServiceImpl.java:57)

代码如下：

     @RequestMapping(value = "/pay", method = RequestMethod.POST)
         public EntPayResult transferPay(HttpServletRequest request) {
            try {
            String openId = "oCTmH5AQIK9NCwxGA-eAHjUsIBzI";
            WxPayConfig wxPayConfig = new WxPayConfig();
            wxPayConfig.setAppId(APP_ID);
            wxPayConfig.setMchId(MCH_ID);
            wxPayConfig.setMchKey(API_SECRET);
            wxPayConfig.setKeyPath(ConfigUtil.getProperty("wxpay.keyPath"));
            WxPayService wxPayService = new WxPayServiceImpl();
            wxPayService.setConfig(wxPayConfig);
            EntPayRequest entPayRequest=new EntPayRequest();
            entPayRequest.setPartnerTradeNo(PayUtil.getTradeNo());
            entPayRequest.setOpenid(openId);
            entPayRequest.setCheckName("NO_CHECK");
            entPayRequest.setAmount(1);
            entPayRequest.setDescription("测试转账到个人");
            entPayRequest.setSpbillCreateIp(PayUtil.getLocalIp(request));
            EntPayResult entPayResult = wxPayService.getEntPayService().entPay(entPayRequest);
            logger.info("================支付结果=========================="+entPayResult);
            return entPayResult;
        } catch (WxPayException e) {
            logger.info("================支付异常=========================="+e.getReturnMsg());
            return null;
        }
    }

**Comment by binarywang** [comment]
NoSuchFieldError  这是个常见错误，看下wiki里相关文档

**Comment by nfudd** [comment]
> NoSuchFieldError 这是个常见错误，看下wiki里相关文档
   
     <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.5</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.1.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>4.3.2</version>
        </dependency>

这是我的版本，应该不算过低吧，还是有错

**Comment by binarywang** [comment]
明显很低，你没仔细核对下吗？
最简单的办法是检查对应的类，看有没有对应的属性。
