### ISSUE TITLE
小程序微信运动 wx.getWeRunData(Object object) 好像没封装？

### ISSUE THREAD

**Issue by qinkangdeid** [binarywang/WxJava#835]
小程序微信运动 wx.getWeRunData(Object object) 好像没封装？

**Comment by binarywang** [comment]
你是说对应的加密数据的解析？其实有对应方法，可以直接使用

**Comment by binarywang** [comment]
文档地址：https://developers.weixin.qq.com/miniprogram/dev/api/open-api/werun/wx.getWeRunData.html

**Comment by qinkangdeid** [comment]
好的 谢谢

**Comment by qinkangdeid** [comment]
好的 谢谢

**Comment by binarywang** [comment]
3.2.4.B测试版本已增加相应的方法
