### ISSUE TITLE
退款时有两个商户，配置读证书时，只生效一个

### ISSUE THREAD

**Issue by UsernameUntaken** [binarywang/WxJava#838]
场景：微信支付平台    1、在公众号网页端商城下单支付-对应公众号商户
                                     2、在APP端下单-对应app商户

           也就是说 我的订单资金去向有两个 商户  对应配置的商户id和证书路径都会不一样

前面用@Bean去构建配置对象，在判断类型的时候获取到配置对象，重新配置对应的是公众号的商户信息还是app的商户信息，但是出现一个问题就是，重启服务后退款，第一次的商户退款类型可以成功，第二次不同的商户类型退款无法成功，比如 重启服务器之后 我执行的app退款可以成功退款，但是接着执行微信公众号退款就不可以了。后台日志报错是证书的问题。

误打误撞的解决方法是  不用自动注入获取配置对象了。那样就可以

`//	@Autowired
//	private WxPayConfig wxPayConfig;
	private WxPayConfig wxPayConfig;

private void wxpayWxConf() {
		wxPayConfig = new WxPayConfig();
		wxPayConfig.setAppId(propertyConfig.getAppId());
		wxPayConfig.setMchId(propertyConfig.getMerchantNumber());
		wxPayConfig.setMchKey(propertyConfig.getMerchantKey());
		wxPayConfig.setKeyPath(propertyConfig.getKeyPath());
		wxPayService.setConfig(wxPayConfig);
	}

	private void wxpayAppConf() {
		wxPayConfig = new WxPayConfig();
		wxPayConfig.setAppId(propertyConfig.getOpenAppId());
		wxPayConfig.setMchId(propertyConfig.getOpenMchId());
		wxPayConfig.setMchKey(propertyConfig.getOpenMchKey());
		wxPayConfig.setKeyPath(propertyConfig.getOpenKeyPath());
		wxPayService.setConfig(wxPayConfig);
	}

`

**Comment by UsernameUntaken** [comment]
但是原因还不清楚，求解

**Comment by binarywang** [comment]
没看懂你描述的，不过你需要注意别把配置搞混了，要完全独立开来。

**Comment by binarywang** [comment]
没有进一步有用信息，暂时关闭
