### ISSUE TITLE
消息加密参数

### ISSUE THREAD

**Issue by fuqiangdong01** [binarywang/WxJava#84]
首先，在处理微信通知消息时，报了这个错误：`WARN RootController:186 - 加密消息签名校验失败`
发现微信的 signature是用token,timestamp和noncestr三个参数计算的，与其文档里的说明并不一致。而我们的WxCryptUtl.decrypt方法内，是按照文档里实现的。

**Comment by binarywang** [comment]
不太明白你的意思，“发现微信的 signature是用token,timestamp和noncestr三个参数计算的，与其文档里的说明并不一致” 这句话怎么理解？

**Comment by binarywang** [comment]
我感觉你应该是概念上有所混淆导致这个问题，WxCryptUtil是消息加密用的，而signature是校验消息来源的，不是一个东西

**Comment by fuqiangdong01** [comment]
` 
try {

      WxMpXmlMessage xmlMessage = WxMpXmlMessage.fromEncryptedXml(message, wxMpService.getWxMpConfigStorage(),timestamp, nonce, signature);

      if (WxConsts.XML_MSG_DEVICE_EVENT.equals(xmlMessage.getMsgType())) {

        if (LOG.isDebugEnabled()) {
          LOG.debug("device event");
        }

        String openId = xmlMessage.getFromUser();
        String deviceId = xmlMessage.getDeviceId();
        rentalService.bindDevice(deviceId, openId);

      }
    } catch (Exception e) {

      LOG.warn(e.getMessage());

    }
`
我是这样调用的。报错：
`WARN RootController:186 - 加密消息签名校验失败`
debug时，发现SHA1.gen(new String[]{this.token, timeStamp, nonce,cipherText})计算的结果与signature不一致，若只用前三个参数计算token,timeStamp,nonce计算，则与微信的signature一致。

**Comment by binarywang** [comment]
你确实是搞错了，signature那个是验证消息是否是微信服务器发送过来用的。建议你参考下demo中的实现方法，具体看首页中提供的几个demo即可，或者看wiki中的相关内容

**Comment by fuqiangdong01** [comment]
是的，是我搞错了。这个位置，我应该使用msg_signature。在向微信测试号的请求里，并没有msg_signature这个参数。哭
