### ISSUE TITLE
WxMpService单例问题

### ISSUE THREAD

**Issue by dante1234** [binarywang/WxJava#840]
`WxMpService wxService = new WxMpServiceImpl();// 实际项目中请注意要保持单例，不要在每次请求时构造实例，具体可以参考demo项目`

如果有多个公众号配置，可以怎么处理这个？建议是不要不断new  WxMpServiceImpl

**Comment by binarywang** [comment]
请参考Demo

**Comment by dante1234** [comment]
哦 看到了  多个公众号的demo  

想在请教下 如果动态的公众号配置 是不是不建议去new这个对象

**Comment by binarywang** [comment]
就参考demo的做法就可以，其实就是每个公众号有一套配置和service等东西
