### ISSUE TITLE
移动应用扫码登录的sdkTicket没有实现嘛

### ISSUE THREAD

**Issue by MrIronMan** [binarywang/WxJava#844]
文档地址：https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=215238808828h4XN&token=&lang=zh_CN

摘自微信文档：
SDK扫码登录签名算法

获取Ticket

生成签名之前必须先获取对应的sdk_ticket。

sdk_ticket是用于生成签名的临时票据。正常情况下，sdk_ticket的有效期为7200秒，通过access_token来获取。由于获取sdk_ticket的api调用次数非常有限，频繁刷新sdk_ticket会导致api调用受限，影响自身业务，开发者需在自己的服务存储与更新sdk_ticket。

1.参考以下文档，使用APP的Appid和AppSecret获取access_token获取access_token,：

https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140183

2.用第一步拿到的access_token 采用http GET方式请求获得sdk_ticket：

https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=ACCESS_TOKEN&type=2

**Comment by binarywang** [comment]
可以实现一个通用的方法，其中type作为变量可以传入

**Comment by binarywang** [comment]
3.2.5.B测试版本已增加相关方法，欢迎测试使用

**Comment by MrIronMan** [comment]
thank you
