### ISSUE TITLE
使用mediaId下载图片报错

### ISSUE THREAD

**Issue by laoliu13** [binarywang/WxJava#846]
下载报错
java.lang.NoClassDefFoundError: org/apache/commons/io/FilenameUtils
这是不是哪个jar包版本错误啊
commons-io已经是2.6版本

**Comment by binarywang** [comment]
请看下wiki里的常见问题

**Comment by pcjun** [comment]
那可能是我httpclient框架使用错误
可能用jodd_http或者ok_http不会有
我试试

**Comment by laoliu13** [comment]
> 请看下wiki里的常见问题

那可能是我httpclient框架使用错误
可能用jodd_http或者ok_http不会有
我试试

**Comment by binarywang** [comment]
跟你用哪个框架没关系，要仔细分析报错原因
