### ISSUE TITLE
codeCommit  方法报错 找不到GSON

### ISSUE THREAD

**Issue by 82253452** [binarywang/WxJava#847]
环境： 3.2.0
报错：
java.lang.NoSuchFieldError: GSON
	at me.chanjar.weixin.open.api.impl.WxOpenMaServiceImpl.codeCommit(WxOpenMaServiceImpl.java:202) ~[weixin-java-open-3.2.0.jar!/:na]
	at com.f4w.controller.BusiAppController.pushWeapp(BusiAppController.java:77) ~[classes!/:1.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]】
分析：
 String response = this.post("https://api.weixin.qq.com/wxa/commit", GSON.toJson(params));
这个GSON.toJson 这个GSON是哪里来的？？？

**Comment by binarywang** [comment]
你看不到源码？

**Comment by 82253452** [comment]
分析中贴的就是源码，但是并没有找到关于GSON的引用，在idea中也无法跳转

**Comment by 82253452** [comment]
> 你看不到源码？

源码里面好像没有吧  是我少添加东西了么

**Comment by binarywang** [comment]
没看到有继承关系么？

**Comment by 82253452** [comment]
继承关系有啊 但是没看到这个类在哪呢？麻烦能回答的具体点么

**Comment by 82253452** [comment]
/**
 * @author <a href="https://github.com/007gzs">007</a>
 * <pre>
 *     增加开放平台代小程序管理服务能力
 *     说明：这里让这个服务公开便于调用者模拟本地测试服务
 * </pre>
 * @author yqx
 * @date 2018-09-12
 */
public class WxOpenMaServiceImpl extends WxMaServiceImpl implements WxOpenMaService {
  private WxOpenComponentService wxOpenComponentService;
  private WxMaConfig wxMaConfig;
  private String appId;

  public WxOpenMaServiceImpl(WxOpenComponentService wxOpenComponentService, String appId, WxMaConfig wxMaConfig) {
    this.wxOpenComponentService = wxOpenComponentService;
    this.appId = appId;
    this.wxMaConfig = wxMaConfig;
    initHttp();
  }

源码我都帮您粘贴出来了，您指的是在WxMaServiceImpl 这个里面么

**Comment by 82253452** [comment]
public class WxMaServiceImpl implements WxMaService, RequestHttp<CloseableHttpClient, HttpHost> {
    private final Logger log = LoggerFactory.getLogger(this.getClass());
    private CloseableHttpClient httpClient;
    private HttpHost httpProxy;
    private WxMaConfig wxMaConfig;
    private WxMaMsgService kefuService = new WxMaMsgServiceImpl(this);
    private WxMaMediaService materialService = new WxMaMediaServiceImpl(this);
    private WxMaUserService userService = new WxMaUserServiceImpl(this);
    private WxMaQrcodeService qrCodeService = new WxMaQrcodeServiceImpl(this);
    private WxMaTemplateService templateService = new WxMaTemplateServiceImpl(this);
    private WxMaAnalysisService analysisService = new WxMaAnalysisServiceImpl(this);
    private WxMaCodeService codeService = new WxMaCodeServiceImpl(this);
    private WxMaSettingService settingService = new WxMaSettingServiceImpl(this);
    private int retrySleepMillis = 1000;
    private int maxRetryTimes = 5;
这是我的源码里面WxMaServiceImpl 的源码，并没有有关GSON的引用，
现在我的版本是3.2.4B
