### ISSUE TITLE
多个公众号 商户号

### ISSUE THREAD

**Issue by fufenghua** [binarywang/WxJava#849]

**Comment by binarywang** [comment]
你想说什么

**Comment by fufenghua** [comment]
不好意思啊   发错了，我以为没法出去呢。。。
我本来是想问现在公众号是可以配置多个的，但是支付好像只能配置一个appid，是包里面就那样实现的，我即便改了config里面的appid为List<String>也没用，不能用一个商户号关联多个appid
然后我查询了一下以前的issues  好像是推荐多个appid  就写多个配置 多个wxPayService

**Comment by binarywang** [comment]
你可以仿照mp的多公众号支持的demo，也可以在传参数的时候指定对应appid

**Comment by izerui** [comment]
可以参考我重新实现的starter，基于企业微信的多租户实现：

https://github.com/izerui/work-weixin-spring-boot
