### ISSUE TITLE
重复调用

### ISSUE THREAD

**Issue by besehen** [binarywang/WxJava#850]
wxMpService.post();   方法存在五次调用问题。

**Comment by binarywang** [comment]
请明确一下

**Comment by 393229227** [comment]
> 请明确一下

调用模板消息的时候发了五次，然后直接调用post的时候也是发了五次，外部调用并无循环调用

**Comment by binarywang** [comment]
请观察下你自己的程序输出日志，看是否是程序本身发出的五次，另外如果觉得自己代码写的没问题，可以贴上代码来瞧一瞧

**Comment by 393229227** [comment]
已发QQ群

**Comment by binarywang** [comment]
失联了？qq群里也没下文了？
请尽量在此描述你的问题吧，既然已经在此开始了。

**Comment by 393229227** [comment]
> 失联了？qq群里也没下文了？
> 请尽量在此描述你的问题吧，既然已经在此开始了。

已经找到问题，由于tomcat配置问题，导致多次扫描webapps 造成定时任务多次执行。
谢谢
