### ISSUE TITLE
开放平台 /api/get_authorizer_info 请求错误

### ISSUE THREAD

**Issue by beierzsj** [binarywang/WxJava#851]
【请求地址】: https://api.weixin.qq.com/cgi-bin/component/api_get_authorizer_info?component_access_token=15_gJbCCo00ujM60FgFVXmMw5W4fExPa9-Az9zuPvLq7-w7QqyYQp-8nAV5SCKfPIuEjt5ppYT8v4F-Ih1kTWEdG40B3U5rHf0zmQ-B4pmhbdv5O0J2rb7I77UrYcNcOh1P6VxylTzBIgoNH6J3UPEeAHANIX
【请求参数】：{"component_appid":"wxead3a9f168e586dd","authorizer_appid":"wxfa2d6c5fd816223e"}
【错误信息】：{"errcode":61003,"errmsg":"component is not authorized by this account hint: [JWXnAA02851976]"}

**Comment by 007gzs** [comment]
确认下是否已经取消授权
