### ISSUE TITLE
Library source does not match the bytecode for class

### ISSUE THREAD

**Issue by fuuqiu** [binarywang/WxJava#852]
IDEA查看源码时提示：Library source does not match the bytecode for class的问题分析
通过Maven查看依赖的源码时，通常是Maven自动下载JAR包附属的source包，但是会出现一个问题，由于使用lombok插件会造成编写的Java文件和编译后的class上有差别，所以IDEA打开时看到的是Maven打包时用的源码，而IDEA会自动匹配与.class反编译后的源代码，造成不匹配的提示。

解决方法其实可以说是没有。

**Comment by binarywang** [comment]
其实可以忽略，何必要想着解决呢

**Comment by fuuqiu** [comment]
主要是源码的注释也没有了

**Comment by binarywang** [comment]
源码里有的东西依然会有吧，不知道你说的什么意思
