### ISSUE TITLE
小程序获取二维码增加byte[]类型的返回方法

### ISSUE THREAD

**Issue by shoubaozi** [binarywang/WxJava#853]
关注该项目一年多了，使用该项目开发了四五个小程序序和一个公众号。
目前我在使用3.2版本 使用过程中我有一些困惑。

1.	是否可以自定义一个关于锁的接口或抽象类， 让用户去实现指定的方法.目前自定义锁需要用户实现java.util.concurrent.locks.Lock。lock需要实现的方法很多，且好像不是所有方法都被使用到，例如我公司的分布式锁实现java.util.concurrent.locks.Lock#newCondition，lockInterruptibly 方法很困难，而且内部调用没有用到。	
2.	关于获取AccessToken是否可以增加一种定时任务获取的方式。在用户配置的时候可选，这样就不必要每次都判断是否过期了
3.	小程序获取二维码是否增加byte[] 和InputStream类型的返回，对于一些系统需把图片存储到cdn上，没有必要本地缓存一份，而且对于大量生成的情况，性能不是很好，（这块的源码我没有全部阅读）.现在我只能再把该功能实现一次，以便于返回byte[]

**Comment by binarywang** [comment]
想法不错，欢迎直接提供PR，可以针对性讨论

**Comment by binarywang** [comment]
既然楼主没时间，我就先提供三个返回byte数组的方法。其他问题再议，建议单独开issue。

**Comment by binarywang** [comment]
3.2.8.B测试版本已增加相关方法，欢迎试用

**Comment by shoubaozi** [comment]
年前准备双十一，然后准备离职，才有时间过来 看看， 之前在京东一直用这个 了， 现在不在京东了，公司业务用不上 这个了，可能暂时没条件，也没环境  去测试 使用了， 辛苦  班纳瑞
