### ISSUE TITLE
weixin-java-miniapp 中access_token 多项目会有些问题，有没有可以直接使用的方案？

### ISSUE THREAD

**Issue by qiankun30** [binarywang/WxJava#854]
weixin-java-miniapp 中access_token 多项目会有些问题，有没有可以直接能使用的方案？ 也看了https://github.com/Wechat-Group/weixin-java-tools/issues/797 中说的WxMpInRedisConfigStorage 好些还需要自己实现

**Comment by binarywang** [comment]
那个不能直接用吗？还需要实现什么？

**Comment by qiankun30** [comment]
分布式时 access_token  有问题啊

**Comment by binarywang** [comment]
使用redis就是为了解决这个问题，你仔细看过源码没？测试下看看了吗？或者你使用的方式不对
