### ISSUE TITLE
会员卡有效期问题

### ISSUE THREAD

**Issue by geutopia** [binarywang/WxJava#856]
dateInfo.getEndTimestamp()  这个是秒,   System.currentTimeMillis() 这个是毫秒

    if (dateInfoType == DateInfoType.DATE_TYPE_FIX_TIME_RANGE && (dateInfo.getBeginTimestamp() < System.currentTimeMillis() || dateInfo.getEndTimestamp() < System.currentTimeMillis() || dateInfo.getBeginTimestamp() > dateInfo.getEndTimestamp())) {
      return WxMpCardCreateResult.failure("会员卡基本信息的使用日期为:" + dateInfoType.getDescription() + "，beginTimestamp和endTimestamp的值不合法，请检查");
    }

**Comment by binarywang** [comment]
3.2.6.B测试版本已修复
