### ISSUE TITLE
建议添加微信小程序敏感文本检测接口

### ISSUE THREAD

**Issue by fengqiangboy** [binarywang/WxJava#857]
看了小程序的接口，有敏感图片检测，建议添加敏感文本检测
接口如下：
、、、
https://developers.weixin.qq.com/miniprogram/dev/api/open-api/sec-check/msgSecCheck.html
、、、

**Comment by binarywang** [comment]
这个貌似加过了

**Comment by fengqiangboy** [comment]
> 这个貌似加过了

貌似只有图片检测

`WxMaService`的`boolean imgSecCheck(File file) throws WxErrorException;`

**Comment by binarywang** [comment]
哦，好吧，没看清

**Comment by binarywang** [comment]
3.2.6.B测试版本已增加
