### ISSUE TITLE
批量添加卡券接口后推送的事件被消息排重误判为重复消息

### ISSUE THREAD

**Issue by zhangsd** [binarywang/WxJava#858]
发现使用批量添加卡券接口后推送的事件被消息排重误判为重复消息
查看源码使用的排重方法为官网推荐的消息排重规则（FromUserName + CreateTime），但在使用批量添加卡券接口添加多张卡券后，官方推送的消息FromUserName + CreateTime相同，不符合重复消息，微信官方推荐的方法存在问题

**Comment by zhangsd** [comment]
![card-push](https://user-images.githubusercontent.com/3297167/49003456-ed1b9480-f19c-11e8-890f-00439d61cd13.jpeg)

**Comment by binarywang** [comment]
你有什么推荐的解决办法吗？

**Comment by CuriousRookie** [comment]
> 你有什么推荐的解决办法吗？

按照图里显示的，加一个UserCardCode？

**Comment by binarywang** [comment]
这确实是个问题，你可以自定义实现一个 `me.chanjar.weixin.common.api.WxMessageDuplicateChecker`

**Comment by binarywang** [comment]
3.5.3.B 版本 已修复，欢迎试用
