### ISSUE TITLE
支付SDK报错

### ISSUE THREAD

**Issue by pylxyhome** [binarywang/WxJava#859]
支付SDK报错：java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/thoughtworks/xstream/security/NullPermission
me.chanjar.weixin.common.util.xml.XStreamInitializer的以下两方法根据就找不到 xstream.addPermission(NullPermission.NULL); xstream.addPermission(PrimitiveTypePermission.PRIMITIVES);

**Comment by binarywang** [comment]
麻烦瞅一眼wiki里的常见问题
