### ISSUE TITLE
请问，发放代金券时，接口返回return_code为SUCCESS，但err_code为INVALID_REQUEST是怎么回事

### ISSUE THREAD

**Issue by imhtang** [binarywang/WxJava#860]
你好，如题，BaseWxPayServiceImplTest.testSendCoupon()测试发放代金券时，接口返回代码：SUCCESS，返回信息：，结果代码：FAIL，错误代码：INVALID_REQUEST，错误详情：268645892，
`<result_code><![CDATA[FAIL]]></result_code><err_code><![CDATA[INVALID_REQUEST]]></err_code><err_code_des><![CDATA[268645892]]></err_code_des>`
，因而得不到代金券id，查询的代金券批次的时候查询到发放数量已增加，请问这是是怎么回事`

**Comment by binarywang** [comment]
这个你得问微信官方了，错误码官方文档也没查到吗？
