### ISSUE TITLE
weixin-java-pay关于checkResult

### ISSUE THREAD

**Issue by cuiwei2016** [binarywang/WxJava#861]
你好，现在weixin-java-pay封装的微信支付的接口都默认将checkResult参数checkSuccess设置为了true，能否提供不校验checkSuccess的方法呢？

**Comment by cuiwei2016** [comment]
如果checkSuccess为true的话，抛出WxPayException，无法从响应结果对象中获取响应字段值。

**Comment by binarywang** [comment]
你没仔细看吧，这个异常类里包含所有信息的
