### ISSUE TITLE
微信下单对账单，最后一行统计数据String值问题

### ISSUE THREAD

**Issue by ArronSeven** [binarywang/WxJava#862]
微信下单对账单，返回`WxPayBillResult`实例，最后的统计数据的String 值，都会多一个空格。`"totalRecord":"28 ","totalFee":"0.79 ","totalRefundFee":"0.00 ","totalCouponFee":"0.00 ","totalPoundageFee":"0.00000 "`

**Comment by binarywang** [comment]
这个稍后修复下

**Comment by binarywang** [comment]
3.2.7.B测试版本已修复
