### ISSUE TITLE
企业号接口 me.chanjar.weixin.cp.api.WxCpUserService 类的部门参数需改为 Long 类型

### ISSUE THREAD

**Issue by meetljm** [binarywang/WxJava#863]
如题，测试版本 3.2.5.B me.chanjar.weixin.cp.bean.WxCpDepart 的部门ID已经是Long类型，但是 me.chanjar.weixin.cp.api.WxCpUserService 类的方法部门参数还是Integer，希望下个版本修复这个问题。

**Comment by binarywang** [comment]
可以

**Comment by binarywang** [comment]
3.2.7.B测试版本已修复
