### ISSUE TITLE
微信支付异步通知处理上的问题

### ISSUE THREAD

**Issue by luoyb** [binarywang/WxJava#865]
`@Override
  public WxPayOrderNotifyResult parseOrderNotifyResult(String xmlData) throws WxPayException {
    try {
      log.debug("微信支付异步通知请求参数：{}", xmlData);
      WxPayOrderNotifyResult result = WxPayOrderNotifyResult.fromXML(xmlData);
      log.debug("微信支付异步通知请求解析后的对象：{}", result);
      result.checkResult(this, this.getConfig().getSignType(), false);
      return result;
    } catch (WxPayException e) {
      log.error(e.getMessage(), e);
      throw e;
    } catch (Exception e) {
      log.error(e.getMessage(), e);
      throw new WxPayException("发生异常，" + e.getMessage(), e);
    }
  }`

作者大神为何不把result.checkResult(this, this.getConfig().getSignType(), false)中的false开放出来呢？

**Comment by binarywang** [comment]
你觉得不想检查的话，可以自己改变方法内容的，这里默认只是要给大家提供一个通用的方法

**Comment by luoyb** [comment]
我的意思是把result.checkResult(this, this.getConfig().getSignType(), false)中的false改为参数，而不是写死，这样我们就可以选择是否要框架判断业务状态是否正常的逻辑

**Comment by binarywang** [comment]
这个本来就是参数啊，你可以自己改的

**Comment by binarywang** [comment]
parseOrderNotifyResult 这个方法里面本来主要内容就是解析微信支付回调通知内容，大部分人不需要关心是否需要检查状态，就没必要给他提供个参数。
如果你觉得有必要，可以把方法里面主要的几句代码拿出来，自己在做对应处理就好了。
