### ISSUE TITLE
微信支付代金券查询接口

### ISSUE THREAD

**Issue by wustrive2008** [binarywang/WxJava#868]
返回字段 coupon_mininum  微信实际返回字段是 coupon_minimum （微信实际返回字段名称与文档不一致）
给微信反馈过，至今未修改

**Comment by binarywang** [comment]
看来这是真的了，之前有人反馈过，https://github.com/Wechat-Group/weixin-java-tools/issues/549

**Comment by wustrive2008** [comment]
如果能让微信支付团队改一下最好了，他们好像只提供了邮件的反馈方式，并且回复太慢了

**Comment by binarywang** [comment]
https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_4  楼主能否帮忙顺便确认下这个接口里的coupon_mininumn 也是拼错了？

**Comment by binarywang** [comment]
3.2.7.B测试版本已修复

**Comment by wustrive2008** [comment]
> https://pay.weixin.qq.com/wiki/doc/api/tools/sp_coupon.php?chapter=12_4 楼主能否帮忙顺便确认下这个接口里的coupon_mininumn 也是拼错了？

已确认，此接口返回字段coupon_mininumn和文档一致

**Comment by binarywang** [comment]
好吧，多谢了，真是够恶心的微信接口
