### ISSUE TITLE
下载临时素材接口(无法获取到文件名)异常被吃掉了

### ISSUE THREAD

**Issue by shirenchuang** [binarywang/WxJava#869]
下载临时素材接口：
WxMpConfiguration.getMpServices().get(appid).getMaterialService().mediaDownload(mediaId);

输入的mediaId如果存在的话 能够正常的下载
如果随意输入的mediaId；这个时候返回了null；

debug看下 返回的异常信息
me.chanjar.weixin.common.error.WxErrorException: 错误: Code=0, Msg=无法获取到文件名

code = 0  导致异常没有抛出来；
是否考虑往外面抛出来?

**Comment by binarywang** [comment]
是个问题，可以修复下

**Comment by binarywang** [comment]
3.2.9.B测试版本 已修复

**Comment by Binaryang-one** [comment]
binarywang 你好

**Comment by Binaryang-one** [comment]
我使用这个下载临时素材的方法总是提示错误编码99999，找不到文件名之类的

**Comment by binarywang** [comment]
> 我使用这个下载临时素材的方法总是提示错误编码99999，找不到文件名之类的

不相关的问题，请新开issue。而且你的描述太简单，我也没有头绪
