### ISSUE TITLE
将weixin-java-cp模块嵌入spring boot中，打包成war包后，tomcat 启动报错

### ISSUE THREAD

**Issue by Benyour** [binarywang/WxJava#871]
经过反复确认，在spring boot项目中，引入weixin-java-cp模块，打包成war包发布到tomcat中时，tomcat启动会报错！！！

**Comment by gaigeshen** [comment]
请把错误的内容贴出来以便我们查看

**Comment by Benyour** [comment]
我在spring boot的项目中，引入了企业微信开发的模块：
![image](https://user-images.githubusercontent.com/25098471/49786090-8df17e80-fd5d-11e8-90c5-be04fd6eb74e.png)
然后，maven 打包项目成war包以后，放到tomcat中启动时，报如下错误：
![image](https://user-images.githubusercontent.com/25098471/49786194-e9237100-fd5d-11e8-9a25-d0454fa78c26.png)

**Comment by Benyour** [comment]
顺便提一下，我仅仅是引入了该模块，任何相关的微信代码也还没开始写呢

**Comment by gaigeshen** [comment]
检查下你本地仓库的weixin-java-cp模块的jar包有没有下载完毕，可以尝试先删除，然后alt+f5（eclipse）刷新项目试试

**Comment by Benyour** [comment]
赞，👍，非常感谢！
