### ISSUE TITLE
initSSLContext中使用的StringUtils.removeFirst已经废弃，调用报错

### ISSUE THREAD

**Issue by zhangdo1** [binarywang/WxJava#872]
initSSLContext中使用的StringUtils.removeFirst已经废弃，调用报错

**Comment by binarywang** [comment]
是你自己项目里的jar包版本问题吧，请使用本sdk所依赖的对应版本

**Comment by zhangdo1** [comment]
我看模块里面没有指定具体的版本号呢
<dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>

**Comment by binarywang** [comment]
看父pom，而且按说高版本只是标记为过期，但并不会影响使用的，不知道你所说的调用报错是什么意思

**Comment by zhangdo1** [comment]
"message": "Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.removeFirst
我们项目中pom没有指定这个lang3的包

**Comment by zhangdo1** [comment]
场景是调用了refund接口

**Comment by binarywang** [comment]
那是你的对应jar版本过低导致的

**Comment by binarywang** [comment]
注意看下wiki里的常见问题！

**Comment by zhangdo1** [comment]
谢谢，能否告知是哪个jar的版本低

**Comment by zhangdo1** [comment]
我看推荐的lang3是3.5，我试试，谢谢了
