### ISSUE TITLE
当请求订单号不存在时，获取返回值抛出nullPointer异常

### ISSUE THREAD

**Issue by zhaoyunqi** [binarywang/WxJava#873]
如果微信服务器返回“订单不存在”时，refund 里result.composeRefundCoupons()方法获取不到代金券信息，抛出异常。

**Comment by zhaoyunqi** [comment]
![e186c021896f2a59ed88165a707b5b4](https://user-images.githubusercontent.com/40378937/49851010-aa072580-fe1a-11e8-9b40-ed2a9b58bd33.png)

**Comment by binarywang** [comment]
你用的是老版本吧，这个早修复了

**Comment by zhaoyunqi** [comment]
我这里是3.1。现在改成3.2试试

**Comment by zhaoyunqi** [comment]
3。2修复了。谢谢
