### ISSUE TITLE
授权方refresh_token和access_token过期问题

### ISSUE THREAD

**Issue by jiangbin5118** [binarywang/WxJava#874]
授权公众号的refresh_token和access_token都过期时，怎么在获取refresh_token或者只能重新授权，谢谢

**Comment by jiangbin5118** [comment]
第三方平台

**Comment by gaigeshen** [comment]
这个范畴不是SDK的职责，需使用者进行业务设计。另外：

_接口调用凭据刷新令牌（在授权的公众号具备API权限时，才有此返回值），刷新令牌主要用于第三方平台获取和刷新已授权用户的access_token，只会在授权时刻提供，请妥善保存。 一旦丢失，只能让用户重新授权，才能再次拿到新的刷新令牌_

根据文档描述，刷新令牌没有有效期

**Comment by jiangbin5118** [comment]
明白了，谢谢了
