### ISSUE TITLE
请问cp的地理位置问题

### ISSUE THREAD

**Issue by yy598162719** [binarywang/WxJava#875]
应用api接收参数明明开了接收地列位置，可是用户点击菜单的时候，用户的位置信息为null怎么回事

**Comment by binarywang** [comment]
位置信息上报是单独的事件，仔细看下文档

**Comment by yy598162719** [comment]
如果是用户点击了地理位置选择器，上报了位置信息，这个后台可以接收到。
可是我后台怎么通过用户进入该应用的时候获得了该用户的地理位置呢。
"sendLocationInfo" : { }  这个是null

**Comment by binarywang** [comment]
你还是没仔细看文档，有两种事件，一种是你说的地理位置选择器选择事件，另一个是上报地理位置事件，不同事件对应的消息结构是不一样的

**Comment by binarywang** [comment]
楼主搞明白了没？也没个信了

**Comment by yy598162719** [comment]
不好意思，搞明白了。原来是我的账号没有打开允许企业微信获取位置，所以一直没看到，不好意思
