### ISSUE TITLE
小程序getUserInfo Gson失败(用户名包含表情）

### ISSUE THREAD

**Issue by martinbob1992** [binarywang/WxJava#876]
1) 当小程序用户的昵称中间有表情符号时，getUserInfo方法gson序列化失败
rawData={"nickName":"lisa??????哈哈","gender":0, ......省略无关紧要的其他信息

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

2) 当小程序第一次获取用户信息的时候getUserInfo也会导致gson失败
重现步骤：当用户第一次关注这个小程序，并同意授权的时候IllegalStateException，不动任何代码，再点一次授权就成功了，（已经确认不是 #359 问题，不改动任何东西后续的授权是成功的）

**Comment by nanusl** [comment]
我也遇到了同样的问题..
`Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 96 common frames omitted
`

**Comment by gaigeshen** [comment]
看报错的大意，是期待一个对象但实际是字符串，所以无法转换成对象。
先确认是否是特殊字符造成的。

我这边试了下，特殊字符是可以的，比如说：
```
String txt = "{\"nickName\": \"؞\uE110杰克\"}";
WxMaUserInfo info = WxMaUserInfo.fromJson(txt);
System.out.println(info);
```
将会正确打印：
WxMaUserInfo(openId=null, nickName=؞杰克, gender=null, language=null, city=null, province=null, country=null, avatarUrl=null, unionId=null, watermark=null)

将你报错的时候的所有参数内容发出来看下，原始字符串内容是什么样的，报错的位置是哪里

**Comment by martinbob1992** [comment]
@gaigeshen 
![image](https://user-images.githubusercontent.com/20534996/50319197-fd573300-0500-11e9-9067-7d88618f7fb8.png)
![image](https://user-images.githubusercontent.com/20534996/50319314-b3228180-0501-11e9-911f-58a34dc41b77.png)

**Comment by gaigeshen** [comment]
把你的 encryptedData 和 iv 和 sessionKey 发出来 我测试下

**Comment by martinbob1992** [comment]
encryptedData: BY6VOgcWbwGcyrunK0ECWI8rnDsT69DucZ+M78tc1aL9aM/3bEAHFYd4fu7kRjWhD4YfjObw44T9vUqKyHIjbKs6hvtEasZZEIW35x4a91xVgN48ZqZ7MTQqUlP13kDUlkuwYh+/8g8yceu4kNbjowYrhihx+SV7CfjKCveJ7TSepr5Z7aLv1o+rfeelfOwn++WN/YoQsuZ6S3L4fWlWe5DAAUnFUI6cJvxxCohVzbrVXhyH2AqQdSjH2WnMYFeaGFIbcoxMznlk7oEwFn+hBj63dyT/swdYQfEdzuyCBmKXy8d6l1RKVX6Y65coTD8kIlbr+FKsqYrXVUIUBSwehqYuOdhYWZ9Bntl5DWU1oqzAPCnMn2cAIoQpQPKP7IGSxMOvCNAMhVXbE7BvnWuVuGF+AM5tXAa9IVUhcMImGwLQqm4iV5uBd+5OcFObh3A4VJk9iBCBWSkBHa/rV9CVoY0bFv2F9/2Hv82++Ybl274=
iv: TarMFjnzHVxy8pdS93wQbw==
sessionKey: 7MG7jbTToVVRWRXVA885rg==

在设置微信用户名称的时候只要使用表情符号，就一定解析失败

**Comment by gaigeshen** [comment]
看样子是解密的问题， @binarywang

**Comment by bjchen2** [comment]
nested exception is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $] with root cause
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at com.google.gson.Gson.fromJson(Gson.java:813)
	at cn.binarywang.wx.miniapp.bean.WxMaUserInfo.fromJson(WxMaUserInfo.java:27)
	at cn.binarywang.wx.miniapp.api.impl.WxMaUserServiceImpl.getUserInfo(WxMaUserServiceImpl.java:41)

好像的确是WxMaCryptUtils.decrypt出了问题

**Comment by kictto** [comment]
同样遇到了这个问题

**Comment by cgz1211** [comment]
不包含表情也时不时会出现这个问题。

**Comment by binarywang** [comment]
不是表情问题的，请参考#359，不要在这里回复无关问题了，谢谢各位合作

**Comment by binarywang** [comment]
这种包含emoji特殊字符导致解密出问题的情况，目前暂时无解，参考过网上其他代码，一样解析有问题。有空再研究下。

**Comment by liyangzhou** [comment]
> 这种包含emoji特殊字符导致解密出问题的情况，目前暂时无解，参考过网上其他代码，一样解析有问题。有空再研究下。

这个问题目前有解决方案没？

**Comment by binarywang** [comment]
> > 这种包含emoji特殊字符导致解密出问题的情况，目前暂时无解，参考过网上其他代码，一样解析有问题。有空再研究下。
> 
> 这个问题目前有解决方案没？

没，欢迎研究一下

**Comment by binarywang** [comment]
很久没人反映这个问题，估计是官方修复了，因此暂时关闭
