### ISSUE TITLE
微信支付createOrder方法支持小程序支付

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#878]
文档地址：https://pay.weixin.qq.com/wiki/doc/api/wxa/wxa_api.php?chapter=7_7&index=5

**Comment by gaigeshen** [comment]
weixin-java-pay模块应该已经实现了吧，走的也是统一下单接口

**Comment by binarywang** [comment]
这个说的是createOrder方法返回值的问题，现在没有提供对应小程序的结果实现类

**Comment by binarywang** [comment]
又仔细看了下，小程序支付的TradeType为JSAPI，无需单独实现。

**Comment by MisterBowie** [comment]
使用WxPayMpOrderResult,
