### ISSUE TITLE
微信开放平台授权服务号，处理微信消息推送出现:该公众号提供的服务出现故障，请稍后再试

### ISSUE THREAD

**Issue by gmtgo** [binarywang/WxJava#879]
微信开放平台授权服务号，处理微信消息推送出现:该公众号提供的服务出现故障，请稍后再试
消息已经处理成功，并且已经返回空字符串（测试过直接返回success也不行）。
已确认服务号只授权一个开放平台，并且已经关闭开发者配置。

**Comment by gmtgo** [comment]
已解决，
使用这个输出即可
`
        // 回复微信(默认回复空字符串)
        response.getOutputStream().print(out);
`

**Comment by sxz1314** [comment]
您好，我按照您的方法试了，还是该公众号提供的服务出现故障，请稍后再试

**Comment by chenguoqiangabc** [comment]
确认一下返回值是否正常返回success

**Comment by gmtgo** [comment]
> 您好，我按照您的方法试了，还是该公众号提供的服务出现故障，请稍后再试

确认一下返回值是否正常返回success
