### ISSUE TITLE
WxMpXmlMessage.formXml()报错

### ISSUE THREAD

**Issue by shirenchuang** [binarywang/WxJava#886]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.thoughtworks.xstream.io.StreamException: Cannot create XmlPullParser] with root cause
org.xmlpull.v1.XmlPullParserException: caused by: org.xmlpull.v1.XmlPullParserException: resource not found: /META-INF/services/org.xmlpull.v1.XmlPullParserFactory make sure that parser implementing XmlPull API is available

百度之后 导入了xmlpull.jar 包才可以使用
但是我发布到测试环境 就又报这个异常了

**Comment by binarywang** [comment]
你这种错误网上可以搜下

**Comment by shirenchuang** [comment]
我知道 问题我解决了
但是我觉得 你的SDK既然使用了这中解析方式  为啥还需要我们自己去导包

**Comment by binarywang** [comment]
你这种问题我没遇到过，其他人也没提到过，所以只可能是你自己环境的问题了。
既然解决了，为什么不分享下解决过程呢，也许其他人看到也能有所帮助

**Comment by binarywang** [comment]
xmlpull 这个jar包是xstream本身就依赖的，至于你的项目为什么没有，要看你做了什么特殊配置把它给排除出去了

**Comment by BARERM** [comment]
遇到同样问题：
我用的是springboot 2.1.6，不清楚具体哪一步排除掉了这个包。

**Comment by binarywang** [comment]
> 遇到同样问题：
> 我用的是springboot 2.1.6，不清楚具体哪一步排除掉了这个包。

仔细分析下你的pom文件
