### ISSUE TITLE
公众号模块获取用户信息偶尔死循环

### ISSUE THREAD

**Issue by weiyong** [binarywang/WxJava#887]
![_1545115954326 1](https://user-images.githubusercontent.com/6039245/50192972-8fc7cd00-036f-11e9-86f5-53faca196eda.png)
![_15451159085339](https://user-images.githubusercontent.com/6039245/50192984-9b1af880-036f-11e9-8a06-8d28c853cd75.png)

**Comment by binarywang** [comment]
你代码怎么写的

**Comment by weiyong** [comment]
@binarywang 

WxMpUser wxMpUser;
        try {
            wxMpUser = this.wxMpService.getUserService().userInfo(openId);
            logger.info("【获取用户基本信息】user_info={}", wxMpUser.toString());
            return new ResultBean<>(wxMpUser);
        } catch (WxErrorException e) {
            logger.error("【获取用户基本信息】error:{}", e);
            throw new ServiceException(e.getError().getErrorMsg());
        }

**Comment by binarywang** [comment]
没看到有用信息，你的日志也不全

**Comment by binarywang** [comment]
没自己尝试调试下吗？
