### ISSUE TITLE
路由能提供个场景值的正则匹配吗？

### ISSUE THREAD

**Issue by soulmz** [binarywang/WxJava#89]
需求：
假设，我有多个场景值。
```java
newRouter.rule().async(false).msgType(WxConsts.XML_MSG_EVENT).event(WxConsts.EVT_SUBSCRIBE).eventKey("qrscene_1234")
.interceptor(this.wxRegisterInterceptor).handler(this.msgHandler).next()
                .rule().async(false).msgType(WxConsts.XML_MSG_EVENT).event(WxConsts.EVT_SUBSCRIBE).eventKey("qrscene_4444")
.interceptor(this.wxRegisterInterceptor).handler(this.msgHandler).end()
                .rule().async(false).msgType(WxConsts.XML_MSG_EVENT).event(WxConsts.EVT_SUBSCRIBE).interceptor(this.wxRegisterInterceptor).handler(this.followHandler).end();
```
这样写好繁琐。
1.想像rContent 这样能匹配 并 统一处理带有场景值的匹配方式。
2.不太清楚这样写是否合理。
谢谢，你们提供 SDK。:)

**Comment by binarywang** [comment]
记得你在QQ群里聊过这个问题，我的意思你可能还没明白，
简单描述如下：
你可以写成这样：
```
newRouter.rule().async(false).msgType(WxConsts.XML_MSG_EVENT).event(WxConsts.EVT_SUBSCRIBE)
.handler(this.msgHandler).end();
```
然后在你的msgHandler里对enventKey进行进一步判断，想用正则也是没问题的，这样的好处是可以将路由的配置和具体的实现逻辑分离，因为你的eventKey也不可能是固定写死的吧，你可以将相关的针对eventKey的判断抽出相关配置，存在数据库里，或者配置文件里，以便随时生效

**Comment by soulmz** [comment]
@binarywang 我明白你的意思了。
我会将场景值在handler 里处理。
这样写确实不太好。
另外，我还有一个问题，async 如何理解和合理使用？
查阅了 javadoc / wiki 没有详细的介绍 。

**Comment by binarywang** [comment]
async就是异步的意思，就是一个请求不会立即返回结果，一般就是单独启动进程执行，不用等待该线程执行完毕就先返回给用户一个响应。比如记录日志，或者异步发送多条消息（使用客服接口）等，都是比较常用的应用场景。你仔细阅读下源码也就能加深理解了

**Comment by soulmz** [comment]
@binarywang 好的，谢谢。
