### ISSUE TITLE
这个方法，参数我看没有用到， 是故意的么？    调用的时候会感觉到疑惑

### ISSUE THREAD

**Issue by onekr-billy** [binarywang/WxJava#890]
public String getLatestAuditStatus(Long auditid) throws WxErrorException {
        String response = this.get("https://api.weixin.qq.com/wxa/get_latest_auditstatus", (String)null);
        return response;
    }

**Comment by binarywang** [comment]
你看的是哪儿的代码？我看最新的并不是这样的

**Comment by binarywang** [comment]
估计你是看的master分支代码，那个比较过时，请使用最新版
