### ISSUE TITLE
发送模板消息的时候无详细信息问题

### ISSUE THREAD

**Issue by annpeter** [binarywang/WxJava#891]
在发送模板消息后，每个模板消息都是带有url的，并且可以从日志中看到，但是用户接收之后，有的有详情，有的没有详情。而且我自己一直无法复现，我自己测试用服务器同样的参数再次给用户发送消息，用户收到的模板消息也是有详情的，无法复现当时的情况，想问问这有可能是什么问题呢。

1、发送的消息无法点击详情（时间2018-12-21 16:24:37.538）
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=16_5_GYpqHnlIGTC7gvr1S8zW9Ok5lbempmKTM82E7K_15eXGdfQ9WiZ8uX-WK1yw65vaCEpsE0YNbJzkFIprSuqjOg8t749dgoseyiQ3GXa2aiH0nDNKPJK5U-b0q4mKiUcCCtmgGF7v-vxYcjILGeADABEZ
【请求参数】：{"touser":"oSPyH1MW6wqQmIpZ4ewY0ZSLBGEI","template_id":"o4OCt7ty6wava84kXUnbYNiqPGv5PtNH2RQET_ZdFo0","url":"https://wechat.tanyibot.com/apiMiniApp/redirect/getCallRecordInfo?enableSetIntent=true&callRecordId=4JjQ8cpzdoVwNsKgs0FvDg==","data":{"first":{"value":"顾大嫂找到新的C级客户啦！","color":"#72B7E9"},"keyword1":{"value":"","color":"#686868"},"keyword2":{"value":"133XXXX0090","color":"#686868"},"keyword3":{"value":"12-21 16:24","color":"#686868"}}}
【响应数据】：{"errcode":0,"errmsg":"ok","msgid":600429826767405062}

2、发送的消息可以点击详情（时间2018-12-21 17:14:42.009）
【请求地址】: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=16_TjRQJQ9CJUC-SNo6i3OHLDwKRDqZ-pwo0JR3CHUmaHJFxDT8A8uYgA7_HuUfMTJpaGq-igd06aUO8R8cgfpaGptiTLTLL3hGxCq2yzB4zqA6dZ9k9k-keg6QZVfwcFFN57ZMBNcuiO7GlpR_LTDeAFAAIS
【请求参数】：{"touser":"oSPyH1MW6wqQmIpZ4ewY0ZSLBGEI","template_id":"o4OCt7ty6wava84kXUnbYNiqPGv5PtNH2RQET_ZdFo0","url":"https://wechat.tanyibot.com/apiMiniApp/redirect/getCallRecordInfo?enableSetIntent=true&callRecordId=4JjQ8cpzdoVwNsKgs0FvDg==","data":{"first":{"value":"顾大嫂找到新的C级客户啦！","color":"#72B7E9"},"keyword1":{"value":"","color":"#686868"},"keyword2":{"value":"133XXXX0090","color":"#686868"},"keyword3":{"value":"12-21 17:14","color":"#686868"}}}
【响应数据】：{"errcode":0,"errmsg":"ok","msgid":600480232738471938} 

![image](https://user-images.githubusercontent.com/7344217/50370030-2c8da300-05da-11e9-8fe6-60e585fe381b.png)

**Comment by mywsat** [comment]
找到对应请求 手动调用一下是否成功。应该不是SDK问题。感觉是你那边调用出现了问题

**Comment by binarywang** [comment]
估计是微信当时出bug了，既然不能复现，就没必要纠结了吧？
