### ISSUE TITLE
微信mp调用接口错误时返回信息反序列化问题

### ISSUE THREAD

**Issue by hieastz** [binarywang/WxJava#896]
您好，首先非常感谢，使用此工具可以快速构建支撑微信mp的应用。
在开发过程我发现在调用微信mp接口时，微信mp返回的错误信息为{"errcode":40003,"errmsg":"invalid openid hint: [bbGmAa01044119]"}
但是我看到反序列化对象WxError的字段为errorCode和errorMsg，这样导致不能准确的序列化到指定字段上。

我想问的，这样的设计是为了考虑兼容性还是因为微信调整了？我该如果处理调用mp接口返回的错误信息呢？

**Comment by binarywang** [comment]
本SDK对json的解析采用了gson，你如果需要自行转化，请参考对应的fromJson方法

**Comment by hieastz** [comment]
> 本SDK对json的解析采用了gson，你如果需要自行转化，请参考对应的fromJson方法

好的，不过我想问的是，为什么微信mp返回的json属性与WxError对应不上呢？
{"errcode":40003,"errmsg":"invalid openid hint: [bbGmAa01044119]"}
WxError的字段为errorCode和errorMsg
这样的话需要我自己写MyWxError

**Comment by binarywang** [comment]
没必要对应啊，WxError是sdk内部使用的，不知道你为啥有这个需求

**Comment by hieastz** [comment]
> 没必要对应啊，WxError是sdk内部使用的，不知道你为啥有这个需求

如果不对应的话，WxMpErrorMsgEnum的作用是什么？我看代码是有意获取errcode的代码，然后通过WxMpErrorMsgEnum进行中文化。

**Comment by binarywang** [comment]
你是发现现在代码有什么问题吗？建议调试看看，是不是你自己其他方面理解有问题？

**Comment by hieastz** [comment]
> 你是发现现在代码有什么问题吗？建议调试看看，是不是你自己其他方面理解有问题？

很抱歉，是我没有看到 WxErrorAdapter。
