### ISSUE TITLE
企业微信批量删除用户时的消息排重问题

### ISSUE THREAD

**Issue by LwNeighbor** [binarywang/WxJava#897]
在做通讯录管理时,假如批量删除两个用户,在route里面排重的时候, 在控制台打印的两条消息的create_time是一样的,所以经常会把其中一条消息判断为重复消息.最后我在route之前提前设置create_time临时解决了.新手上路,还望大佬指导下!

**Comment by binarywang** [comment]
楼主，你这个问题相信过了这么久你应该有新的认识吧？

**Comment by binarywang** [comment]
3.5.3.B 版本 已修复，欢迎试用
