### ISSUE TITLE
@RequestBody String

### ISSUE THREAD

**Issue by gustave001** [binarywang/WxJava#898]
客服消息无法解析json

**Comment by binarywang** [comment]
你这问题描述真够精简的，能否稍微详细些？

**Comment by gustave001** [comment]
现在已解决，问题是，小程序客服消息配置的是json的推送方式，但是用@RequestBody String requestBody没法解析字符串，然后我就建了个类来接收，然后因为微信的是开头大写的，用@jsonProperty注解解决的，也是折腾了会
