### ISSUE TITLE
模板消息无topcolor方法

### ISSUE THREAD

**Issue by anjia0532** [binarywang/WxJava#90]
在 wiki  https://github.com/wechat-group/weixin-java-tools/wiki/MP_%E5%8F%91%E9%80%81%E6%A8%A1%E6%9D%BF%E6%B6%88%E6%81%AF

templateMessage.setTopColor(...);

但是在2.4中已经移除了 https://github.com/wechat-group/weixin-java-tools/commit/6cf7b0889793ad7e5164220a55bb338f6d04efe4

在微信平台帮助文档中请求是可以指定color的
https://mp.weixin.qq.com/wiki?action=doc&id=mp1433751277&t=0.7656465062845041#.E4.BA.8B.E4.BB.B6.E6.8E.A8.E9.80.81

如何自定义color？

**Comment by binarywang** [comment]
wiki已更新，color和topcolor是不一样的，你要看仔细啊，topcolor早已不支持

**Comment by anjia0532** [comment]
是我没看仔细，之前用的1.3的老jar，按照wiki写的。升级后报错。已改好。谢谢
