### ISSUE TITLE
缺少获取用于计算agentConfig签名的应用jsapi_ticket的接口

### ISSUE THREAD

**Issue by zhaoyh001** [binarywang/WxJava#901]
获取应用的jsapi_ticket；https://qyapi.weixin.qq.com/cgi-bin/ticket/get?access_token=ACCESS_TOKEN&type=agent_config

**Comment by binarywang** [comment]
能否给出对应文档地址？
目前代码里使用的是 https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket 这个接口，不知道有什么区别

**Comment by binarywang** [comment]
楼主出来说明下？是不是有可能你看的是过期的旧的文档？

**Comment by TonyLuo** [comment]
楼主说的应该是应用的jsapi_ticket用于计算agentConfig
https://work.weixin.qq.com/api/doc#10029/%E8%8E%B7%E5%8F%96%E5%BA%94%E7%94%A8%E7%9A%84jsapi_ticket

**Comment by binarywang** [comment]
谢谢楼上的提醒，这个后期可以考虑加一下

**Comment by binarywang** [comment]
3.3.6.B测试版本 已添加
