### ISSUE TITLE
XXE Vulnerability

### ISSUE THREAD

**Issue by itsacoderepo** [binarywang/WxJava#903]
Hello,

i have tested the fix for the XXE vulnerability of the issue [889](https://github.com/Wechat-Group/WxJava/issues/889). 

Unfortunately, the vulnerability is still present in version `3.3.0`, see the image below.

![image](https://user-images.githubusercontent.com/5180740/50690962-9a50ba80-102f-11e9-8fea-90e0f3ad2f61.png)

Additional information on how to prevent such kind of issues can be found on https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Prevention_Cheat_Sheet.

Thank you and best regards

**Comment by binarywang** [comment]
Thank you for your information, we will check it, and fix it if necessary.

**Comment by binarywang** [comment]
The new test version of 3.3.2.B has fixed this.
