### ISSUE TITLE
发送消息模板每次都调用微信官方获取access_token接口，代码该如何修改？

### ISSUE THREAD

**Issue by xokonba** [binarywang/WxJava#908]
操作：发送微信公众号消息模板（需要token（基本的）、openid、模板id、模板内容）
问题：当我从数据库中获取token（基本的且在有效期中）并使用，微信公众平台中  “获取access_token —— 每日实时调用量/上线（次）”都会加1（正常情况不加）；
当数据库中token无效时，微信公众平台中  “获取access_token —— 每日实时调用量/上线（次）”都会加2（正常情况加1）；

请问代码如何写才正确？
附上代码：
@PostMapping("/send_template")
    public Result sendTemplate(@RequestBody SendTemplateReq sendTemplateReq) {

        WxMpService wxMpService = new WxMpServiceImpl();
        WxMpInMemoryConfigStorage wxMpConfigStorage = new WxMpInMemoryConfigStorage();
        wxMpConfigStorage.setAppId(WeiXinLoginConstant.MP1.APP_ID);
        wxMpConfigStorage.setSecret(WeiXinLoginConstant.MP1.SECRET);
        // 1、获取accessToken
        String accessToken = weiXinService.getMpNormalAccessToken(WeiXinLoginConstant.MP1.APP_ID);
        wxMpConfigStorage.setToken(accessToken);
        wxMpService.setWxMpConfigStorage(wxMpConfigStorage);

        // 2、输入用户openid、模板id
        WxMpTemplateMessage templateMessage = WxMpTemplateMessage.builder()
                .toUser(sendTemplateReq.getOpenid())
                .templateId(sendTemplateReq.getTemplateId())
                .url(" ")
                .build();
        
        // 3、添加模板内容
        templateMessage.addData(new WxMpTemplateData("first", sendTemplateReq.getData().get("first"), sendTemplateReq.getData().get("firstColor")))
                .addData(new WxMpTemplateData("keyword1", sendTemplateReq.getData().get("keyword1"), sendTemplateReq.getData().get("keyword1Color")))
                .addData(new WxMpTemplateData("keyword2", sendTemplateReq.getData().get("keyword2"), sendTemplateReq.getData().get("keyword2Color")))
                .addData(new WxMpTemplateData("keyword3", sendTemplateReq.getData().get("keyword3"), sendTemplateReq.getData().get("keyword3Color")))
                .addData(new WxMpTemplateData("remark", sendTemplateReq.getData().get("remark"), sendTemplateReq.getData().get("remarkColor")));

        // 4、发送模板消息
        String result = "";
        try {
            result = wxMpService.getTemplateMsgService().sendTemplateMsg(templateMessage); // 调试证明：此方法调用微信官方获取access_token
        } catch (WxErrorException e) {
            e.printStackTrace();
        }
        log.info("【{}——发送模板】FINISH~result={}", TAG, result);

        return ResultGenerator.genSuccessResult();
    }

**Comment by binarywang** [comment]
请参考下demo的方式来使用service
