### ISSUE TITLE
关于微信支付 服务商模式sub_openid

### ISSUE THREAD

**Issue by shaoyecf** [binarywang/WxJava#910]

**Comment by shaoyecf** [comment]
我看了 3.0版本 去掉了sub_openid 逻辑判断 我想问问 怎么传入
自定义WxPayService 吗？ 还是自定义  WxTransactionType  
单独自定义 WxTransactionType 是不能实现的 因为WxPayService 统一下单里面有强制类型转换 

版本3.0 更新说明中写道 由开发者实现  我不太明白怎么实现 能否指点一二 谢谢

**Comment by binarywang** [comment]
只是判断逻辑去掉了，你怎么传，可以自己控制

**Comment by shaoyecf** [comment]
有没有 案例

![image](https://user-images.githubusercontent.com/28694917/51012565-b22cbf00-1598-11e9-89ac-6b51fb100d81.png)



![image](https://user-images.githubusercontent.com/28694917/51012557-a8a35700-1598-11e9-8761-6996c650a290.png)

**Comment by binarywang** [comment]
看不懂你的代码，而且跟去掉判断代码也没关系吧，那个不判断也无所谓，只是你自己要清楚哪些该填，哪些不用填而已。
