### ISSUE TITLE
作为小程序和公众第三方，卡劵和微信小程序打通功能有没有支持

### ISSUE THREAD

**Issue by peihongpeng** [binarywang/WxJava#911]
文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1499332673_Unm7V
另外：
1 .有没有查询卡劵领取记录详情的接口（ps:官方文档上没有找到）
2. 卡劵第三方代制模式，有没有绑定卡劵核销员的接口？

**Comment by binarywang** [comment]
目前应该还没实现

**Comment by binarywang** [comment]
看文档，应该是需要依赖开放平台的

**Comment by peihongpeng** [comment]
没有验证，看说明需要依赖开放平台

**Comment by 007gzs** [comment]
我简单看了下文档，文档里的需要申请一个开放平台应该只是为了做公众号和小程序互通的（就像多公众号之间用unionid互通一样），只需要绑定到同一个开放平台就可以。目前WxJava的open项目主要是三方平台的代码，应该不需要依赖
