### ISSUE TITLE
服务商模式下的APP支付返回二次签名

### ISSUE THREAD

**Issue by stckiss** [binarywang/WxJava#912]
参考：
https://pay.weixin.qq.com/wiki/doc/api/app/app_sl.php?chapter=9_12&index=2
![image](https://user-images.githubusercontent.com/3785010/51024649-0ea5d380-15c5-11e9-95b3-c1f859924460.png)
签名时需要使用子商户的商户号：
![image](https://user-images.githubusercontent.com/3785010/51024742-50367e80-15c5-11e9-9e2e-3e04617153bf.png)

**Comment by binarywang** [comment]
欢迎直接提交PR

**Comment by binarywang** [comment]
3.3.2.B测试版本 已修复
