### ISSUE TITLE
领取卡券的jssdk页面调用总是提示config:invalid signature签名不对

### ISSUE THREAD

**Issue by tianxiajiangshan** [binarywang/WxJava#913]
long timestamp = System.currentTimeMillis() / 1000;
	    String nonceStr = RandomUtils.getRandomStr();
	    String cardApiTicket = wxMpService.getCardService().getCardApiTicket(false);
	    String[] optionalSignParam = {String.valueOf(timestamp), cardApiTicket, nonceStr, cardId};
	    String signature = SHA1.gen(optionalSignParam);
	    WxCardApiSignature cardApiSignature = new WxCardApiSignature();
	    cardApiSignature.setCardId(cardId);
	    cardApiSignature.setTimestamp(timestamp);
	    cardApiSignature.setNonceStr(nonceStr);
	    cardApiSignature.setSignature(signature);

wx.config({
	            debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来
	            appId: appId, // 必填，公众号的唯一标识
	            timestamp: timestamp, // 必填，生成签名的时间戳
	            nonceStr: nonceStr, // 必填，生成签名的随机串
	            signature: signature,// 必填，签名，见附录1
	            jsApiList : [ 'chooseCard', 'addCard' ] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
	        });
	        wx.ready(function(){
	        	document.querySelector('#addCard').onclick = function () {
	        		var cardExt = {
	                	apiTicket: cardApiTicket,
	                    timestamp: timestamp,
	                    nonceStr: nonceStr,
	                    signature: signature
	                };
	        		wx.addCard({
	                    cardList: [{
	                        cardId: cardId,
	                        cardExt: JSON.stringify(cardExt)
	                    }],
	                    success: function (res) {
	    	        		alert('已添加卡券：' + JSON.stringify(res.cardList));
	                    },
                        cancel: function (res) {
                            alert('卡券添加失败');
                        },
                        fail: function (res) {
                            alert('卡券添加失败');
                        }
	                });
	        	}

**Comment by binarywang** [comment]
楼主你的这个问题，按你在群里描述的，应该是跟BaseInfoUpdate少了brand_name有关系的？

**Comment by yuanqixun** [comment]
和BaseInfoUpdate应该没有关系，BaseInfoUpdate只是更新卡券时候用到，你这个是添加会员卡到卡包的API，没有关系，请楼主详细提供错误的原因。

**Comment by fanxl12** [comment]
我也遇到同样的问题，一直提示签名不对

**Comment by zhanuuuuu** [comment]
因为排序出了问题,楼主没有按照微信说的来,我已经解决了
![image](https://user-images.githubusercontent.com/35062847/58687822-5632cd80-83b5-11e9-9b11-3748121c8b4d.png)

参考地址:http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=cardsign

**Comment by binarywang** [comment]
参考#1060  @yuanqixun 袁总确认下？

**Comment by yuanqixun** [comment]
这个问题当初我也是一直没有调通，我没有用这个方法




在2019年05月31日 15:36，Binary Wang 写道：

参考#1060@yuanqixun 袁总确认下？

**Comment by tianxiajiangshan** [comment]
> 因为排序出了问题,楼主没有按照微信说的来,我已经解决了
> ![image](https://user-images.githubusercontent.com/35062847/58687822-5632cd80-83b5-11e9-9b11-3748121c8b4d.png)
> 
> 参考地址:http://mp.weixin.qq.com/debug/cgi-bin/sandbox?t=cardsign

按你说的在这顺序也不行，群主最好优化下，debug开启提示签名错误但是领卡却不影响
