### ISSUE TITLE
小程序二维码 临时文件自动清理

### ISSUE THREAD

**Issue by nickwongwong** [binarywang/WxJava#914]
小程序生成二维码时，会往本地写临时文件
如果没有重启服务，且没有及时清除，会导致磁盘用完

`cn.binarywang.wx.miniapp.util.http.QrCodeRequestExecutor
me.chanjar.weixin.common.util.fs.createTmpFile 创建了临时文件`
![image](https://user-images.githubusercontent.com/16626084/51158968-ca1a8080-18c1-11e9-8af8-696608e3ed75.png)

**Comment by binarywang** [comment]
建议自己使用完文件后，自行清理，毕竟每个人需求不一样，如果依赖sdk内部做删除，有的人的需求可能是想使用该文件直接进行操作，删除则会影响其使用。

**Comment by binarywang** [comment]
你可以使用另外的返回byte数组的方法，这样就不会生成临时文件。
