### ISSUE TITLE
WxCpUser对象缺少order属性

### ISSUE THREAD

**Issue by chenjunwen** [binarywang/WxJava#915]

**Comment by chenjunwen** [comment]
![image](https://user-images.githubusercontent.com/18376075/51225232-8b013380-1984-11e9-81ef-82e050b47f4e.png)

**Comment by binarywang** [comment]
看起来像是个新增加的东西，后期可以加一下

**Comment by chenjunwen** [comment]
谢谢了，麻烦后期有空的话加上。回复效率杠杠的

**Comment by binarywang** [comment]
以后提问少用图片，多发链接什么的，能用文字描述就不要用图片了，因为图片其实挺浪费服务器资源的。

**Comment by binarywang** [comment]
文档地址  https://work.weixin.qq.com/api/doc#90000/90135/90195

**Comment by binarywang** [comment]
3.3.3.B测试版本已增加
