### ISSUE TITLE
添加根据支付单号查询用户unionId的接口

### ISSUE THREAD

**Issue by linzehuan** [binarywang/WxJava#916]
麻烦添加根据支付单号查询用户unionId的接口

https://open.weixin.qq.com/cgi-bin/showdocument?
action=dir_list&t=resource/res_list&verify=1&id=215453152075Ry2s&token=&lang=zh_CN

**Comment by binarywang** [comment]
注意关注公众号，查看最近版本更新。你说的这个接口已经实现了。

**Comment by binarywang** [comment]
#895 重复
