### ISSUE TITLE
WxMaCryptUtils.decrypt AES解密失败

### ISSUE THREAD

**Issue by daiyun169** [binarywang/WxJava#917]
at cn.binarywang.wx.miniapp.util.crypt.WxMaCryptUtils.decrypt(WxMaCryptUtils.java:39)
Caused by: javax.crypto.IllegalBlockSizeException: Input length not multiple of 16 bytes

IV not 16 bytes long

**Comment by daiyun169** [comment]
![tim 20190117161228](https://user-images.githubusercontent.com/19162724/51304311-bfebb400-1a72-11e9-87a8-d16c532ea34c.png)

**Comment by daiyun169** [comment]
![tim 20190117161322](https://user-images.githubusercontent.com/19162724/51304341-dabe2880-1a72-11e9-974e-b0ae74d709d7.png)

**Comment by binarywang** [comment]
首先确认下你的程序版本，其次检查是否是相关参数配置不正确。

**Comment by binarywang** [comment]
请尽量少用截图，多用文本

**Comment by daiyun169** [comment]
好的，配置都是没有问题的。
程序版本： 3.3.0
这个错误不是必现的。

**Comment by daiyun169** [comment]
抱歉问题已经解决了，是在处理加密字符串的时候出现了特殊字符程序没有处理引起的  （+变成了空格）

**Comment by weiyierlei** [comment]
> 抱歉问题已经解决了，是在处理加密字符串的时候出现了特殊字符程序没有处理引起的 （+变成了空格）

请问具体怎么处理的，我的现象跟你一样，偶尔出现这个问题。加密字符串都是直接传到服务器的，里面有特殊字符要处理？
