### ISSUE TITLE
新建卡劵使用时段限制错误

### ISSUE THREAD

**Issue by peihongpeng** [binarywang/WxJava#918]
AdvancedInfo类中的TimeLimit应该是数组类型。
   "time_limit": [
                   {
                       "type": "MONDAY",
                       "begin_hour":0,
                       "end_hour":10,
                       "begin_minute":10,
                       "end_minute":59
                   },
                   {
                       "type": "HOLIDAY"
                   }
               ]

**Comment by binarywang** [comment]
请尽量给出对应文档地址：https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025056

**Comment by binarywang** [comment]
3.3.3.B测试版本已修复
