### ISSUE TITLE
微信推送用户礼品卡相关事件常量 缺失

### ISSUE THREAD

**Issue by sukeyYang** [binarywang/WxJava#919]
giftcard_pay_done、giftcard_send_to_friend、giftcard_user_accept

**Comment by binarywang** [comment]
请尽量给出对应文档地址，谢谢

**Comment by binarywang** [comment]
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=215143440770UT7Y

**Comment by binarywang** [comment]
另外对应事件常量已重构至`WxMpEventConstants`这个类统一管理

**Comment by binarywang** [comment]
3.3.3.B测试版本已增加
