### ISSUE TITLE
大神，文本卡片 描述 description 字段中如何使用div排版，目前版本使用的是3.2.0

### ISSUE THREAD

**Issue by Jerry-goodboy** [binarywang/WxJava#920]
大神，文本卡片 描述 description 字段中如何使用div排版，目前版本使用的是3.2.0，现在什么样式都没有，完全是文本格式，<a>标签的样式都出不来，企业微信文档https://work.weixin.qq.com/api/doc#90000/90135/90236/%E6%96%87%E6%9C%AC%E5%8D%A1%E7%89%87%E6%B6%88%E6%81%AF
@binarywang

**Comment by binarywang** [comment]
这个跟sdk丝毫关系没有，经过测试跟官方显示一致。

**Comment by Jerry-goodboy** [comment]
@binarywang 不好意思，是我理解错了，用企业微信是可以看textcard的信息的，但是用微信看不了，微信的是企业号，企业号不支持textcard信息，my fault，抱歉打扰大神了
