### ISSUE TITLE
大神，企业微信缺少Markdown消息格式的支持

### ISSUE THREAD

**Issue by Jerry-goodboy** [binarywang/WxJava#921]
企业微信开发文档
https://work.weixin.qq.com/api/doc#90000/90135/90236/markdown%E6%B6%88%E6%81%AF
@binarywang

**Comment by binarywang** [comment]
这个可以加上

**Comment by binarywang** [comment]
3.3.3.B测试版本已增加支持

**Comment by Jerry-goodboy** [comment]
@binarywang 大神厉害啊，我自己用post方法拼的参数，感觉好麻烦，我现在就去使用最新的版本，👍
