### ISSUE TITLE
企业号应用通过Long类型的部门id获取用户，返回的用户的部门Id是Integer的数组，超过int的范围

### ISSUE THREAD

**Issue by xishao666** [binarywang/WxJava#925]
List<WxCpUser> wxCpUserList = wxCpUserService.listByDepartment(2315041299L,true,0);

返回的WxCpUser的deptIds是个Integer数组，直接溢出了

**Comment by binarywang** [comment]
这个已经改了吧，你是用的是最新版本吗？

**Comment by binarywang** [comment]
用最新测试版本试下看看

**Comment by xishao666** [comment]
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-cp</artifactId>
    <version>3.3.3.B</version>
    <scope>provided</scope>
</dependency>
这个版本的me.chanjar.weixin.cp.bean.WxCpUser的departIds还是个Integer[]，并没有修复
