### ISSUE TITLE
wiki文档需要更新

### ISSUE THREAD

**Issue by Jerry-goodboy** [binarywang/WxJava#926]
wiki文档需要更新，好多方法新版本里都没有了，希望更新

**Comment by Jerry-goodboy** [comment]
@binarywang

**Comment by binarywang** [comment]
wiki人人都可以修改的，如果你发现不对的地方，欢迎随时修复，谢谢

**Comment by Jerry-goodboy** [comment]
@binarywang 好的，但是javadoc怎么更新，那个应该是用工具生成的吧，往那个地方push呢，javadoc里面也发现了一些失效的链接和过时的信息

**Comment by binarywang** [comment]
javadoc是源码里的。你找到对应源码，修改并提交PR。下次发布正式版我就会新生成一份javadoc
