### ISSUE TITLE
WxCpUser的departIds应该改为Long[]

### ISSUE THREAD

**Issue by xishao666** [binarywang/WxJava#927]
<dependency>
    <groupId>com.github.binarywang</groupId>
    <artifactId>weixin-java-cp</artifactId>
    <version>3.3.3.B</version>
    <scope>provided</scope>
</dependency>
这个版本的me.chanjar.weixin.cp.bean.WxCpUser的departIds还是个Integer[]，并没有修复

**Comment by binarywang** [comment]
这个稍后修复下

**Comment by binarywang** [comment]
3.3.4.B 测试版本已修复
