### ISSUE TITLE
消息路由设置为异步方式问题

### ISSUE THREAD

**Issue by lgl48128244** [binarywang/WxJava#929]
消息路由设置为异步方式时会出现"服务出现故障,请稍后再试"的提示信息.设置为同步时正常,但出现访问高峰时也会出现"服务出现故障,请稍后再试"的提示信息.

**Comment by binarywang** [comment]
你得理解异步是什么意思，异步处理里你返回的消息肯定没法返回给微信服务器，所以理所当然会出现那种提示，至于同步为什么会出现，那就是微信服务器那边的问题了。

**Comment by reflyhight** [comment]
相信很多人对这个路由规则的同步异步难以理解，有没有更详细一点儿的介绍或阐述。。
