### ISSUE TITLE
解析微信退款结果回调报错：Method threw 'javax.crypto.IllegalBlockSizeException' exception.

### ISSUE THREAD

**Issue by BMambaYe** [binarywang/WxJava#930]
wxPayService.parseRefundNotifyResult(param) 这行代码报错，
Method threw 'javax.crypto.IllegalBlockSizeException' exception.
Input length must be multiple of 16 when decrypting with padded cipher

**Comment by BMambaYe** [comment]
具体在Cipher的 doFinal方法 this.spi.engineDoFinal(var1, 0, var1.length)这行

**Comment by gaols** [comment]
54不是16的倍数。

**Comment by BMambaYe** [comment]
我算错了 但是还是没解决 

> 54不是16的倍数。

我算错了 但是问题还是解决

**Comment by BMambaYe** [comment]
> 54不是16的倍数。

我算错了 ，但是这不是问题的关键

**Comment by BMambaYe** [comment]
Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
源码里用的是AES/ECB/PKCS5Padding，但是微信用的是PKCS7Padding


解密步骤如下：

（1）对加密串A做base64解码，得到加密串B

（2）对商户key做md5，得到32位小写key* ( key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置 )

（3）用key*对加密串B做AES-256-ECB解密（PKCS7Padding）

是不是和这个有关

**Comment by binarywang** [comment]
不像是这个问题，如果是，你退款请求都发不出去，仔细检查下你的相关参数配置是不是有问题

**Comment by binarywang** [comment]
楼主有最新进展没有？

**Comment by GitWingSky** [comment]
这个问题我也遇到了，本地可以解密，到centos服务器就解密不了
