### ISSUE TITLE
微信公众号调用支付接口-返回签名错误

### ISSUE THREAD

**Issue by chuai-Git** [binarywang/WxJava#931]
使用<微信支付接口签名校验工具>校验显示，校验通过。

**Comment by chuai-Git** [comment]
已解决！32位mchKey，是商户API密钥，一定确认公众号的appSecret和商户号的API密钥没有搞混，不行可以重置商户API密钥。
![image](https://user-images.githubusercontent.com/45938039/51783574-bcdd7b80-2176-11e9-9d57-498784a59387.png)

**Comment by binarywang** [comment]
这两个其实不容易搞混吧，还是需要自己先搞清楚概念了

**Comment by yuantangxi** [comment]
我也遇到了这个问题，方法都试了个遍，依旧不好使，最后发现是自己的失误导致的，在重置商户号密钥时，我一直重置的是“APIV3”密钥，一直不好使，最后才发现是自己重置的不对，重置API密钥后，调用成功。
![image](https://user-images.githubusercontent.com/17607055/61852843-0839d200-aeed-11e9-8f74-8af8f27437d2.png)
