### ISSUE TITLE
微信h5支付

### ISSUE THREAD

**Issue by you-name-it** [binarywang/WxJava#935]
![image](https://user-images.githubusercontent.com/33728429/52063187-13025280-25ad-11e9-9fb7-5dfc6652a9c1.png)
你好，我想问一下这里的字符串加双引号解析出错，请问怎么解决？

**Comment by binarywang** [comment]
你这是微信的返回？

**Comment by you-name-it** [comment]
> 你这是微信的返回？

不是，这是请求微信的，请求微信前将字符串转成xml的时候，用的request.toXML方法

**Comment by binarywang** [comment]
感觉像是使用问题，楼主是否有新的进展，没有就先关闭了
