### ISSUE TITLE
使用沙箱环境退款时URL错误

### ISSUE THREAD

**Issue by xuyanatsyxl** [binarywang/WxJava#936]
使用JoddHttpImpl，退款时生成的URL是https://api.mch.weixin.qq.com/sandboxnew/secapi/pay/refund ，实际上应该是 https://api.mch.weixin.qq.com/sandboxnew/pay/refund

**Comment by binarywang** [comment]
你说的“实际上”的依据是什么？官方文档吗？没看到相关说明

**Comment by binarywang** [comment]
3.3.5.B 测试版本已修复
