### ISSUE TITLE
微信服务商AndroidAPP支付签名验证失败

### ISSUE THREAD

**Issue by qingfeng111** [binarywang/WxJava#938]
3.3.0微信支付APP服务商模式下,签名会出现问题

**Comment by binarywang** [comment]
请详细描述下你的问题出现的过程，我们需要确认是不是你自己代码写的有问题，或者配置有问题，或者你理解上出现了什么偏差？

**Comment by qingfeng111** [comment]
普通商户的签名   在ios/Android都是可以正常唤起微信支付.

服务商的签名  在iOS上可以唤起微信支付,但在Android上返回-1

前端代码没变过  想问一下Android的签名需要些什么配置细节@binarywang

**Comment by binarywang** [comment]
楼主问题解决了吗？没遇到过你描述的情况
