### ISSUE TITLE
下载iphone的声音文件时，微信返回来的文件名为空

### ISSUE THREAD

**Issue by binarywang** [binarywang/WxJava#942]
下载iphone的声音文件时，微信返回来的文件名为空。在当前的代码下，文件名为空时返回null。其实这个时候返回的文件内容是正确的，只是文件名为空而已。 参考#941

**Comment by shilianwang** [comment]
已修正，并提交PR。请确认！
--------------------------------------------------------
下载iphone的声音文件时，微信返回来的文件名为空。在当前的代码下，文件名为空时返回null。其实这个时候返回的文件内容是正确的，只是文件名为空而已。所以修改此处代码为当发现文件名为空时，使用当前系统时间生成文件名。已多次测试通过。

**Comment by binarywang** [comment]
3.3.5.B 测试版本已修复
