### ISSUE TITLE
signature 获取方式

### ISSUE THREAD

**Issue by xjar-s** [binarywang/WxJava#952]
// 用户信息校验
        if (!wxService.getUserService().checkUserInfo(sessionKey, rawData, signature)) {
            return "user check failed";
        }

请问 signature 参数在哪里获取呢

**Comment by binarywang** [comment]
你这是哪儿的代码？demo里的？建议去对应demo项目下询问相关问题。
另外关于此问题，建议看看对应方法注释，再结合官方文档，就知道怎么回事了。

**Comment by binarywang** [comment]
#796 另外楼主请关注下你之前提到的一个问题，别烂尾了啊

**Comment by xjar-s** [comment]
那个需求取消了 ，就没看那块的东西了
