### ISSUE TITLE
是否没有实现开放平台用户登录接口？

### ISSUE THREAD

**Issue by fengqiangboy** [binarywang/WxJava#953]
(接口地址)[https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316518&token=&lang=zh_CN]

是否没有实现？

**Comment by Hipple** [comment]
WxOpenMpService

**Comment by fengqiangboy** [comment]
> WxOpenMpService

在open项目下还是mp项目下啊？好像木有看到。。。

**Comment by Hipple** [comment]
wxOpenService.getWxOpenComponentService ().getWxMpServiceByAppid ("").oauth2getAccessToken ()

**Comment by fengqiangboy** [comment]
这是第三方平台的接口吧，貌似没有app的接口？

这里面的[https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317853&token=&lang=](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419317853&token=&lang=)

**Comment by binarywang** [comment]
如果只是用这个接口，不建议使用开放平台模块，直接使用公众号模块里很早前就实现的接口，具体搜索接口地址关键字就能找到了。

**Comment by fengqiangboy** [comment]
> 如果只是用这个接口，不建议使用开放平台模块，直接使用公众号模块里很早前就实现的接口，具体搜索接口地址关键字就能找到了。

确实可以用公众号的模块
