### ISSUE TITLE
WxPayRefundResult的cash_refund_fee应该是Integer类型的

### ISSUE THREAD

**Issue by rmfish** [binarywang/WxJava#957]
https://github.com/Wechat-Group/WxJava/blob/cc8359b22c05590e1fcdd9982de20c4cf7616285/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/result/WxPayRefundResult.java#L95-L96

参看官方文档：
https://pay.weixin.qq.com/wiki/doc/api/jsapi.php?chapter=9_4
```
现金退款金额 | cash_refund_fee | 否 | Int | 100 | 现金退款金额，单位为分，只能为整数，详见支付金额
```

**Comment by binarywang** [comment]
多谢提出，稍后修复一下

**Comment by binarywang** [comment]
3.3.5.B 测试版本已修复
