### ISSUE TITLE
多公众号http线程池共享问题

### ISSUE THREAD

**Issue by resrugam** [binarywang/WxJava#959]
目前在研发一个类似微盟的公众号管理平台， 需要维护多个公众号，  目前是否支持多appid？ 如现在不支持， 未来有计划支持吗？  有时间节点吗？

**Comment by binarywang** [comment]
这只是个sdk，多公众号支持没问题，具体你可以参考demo，请仔细阅读首页说明查找对应demo。

**Comment by resrugam** [comment]
查看了demo：weixin-java-mp-demo-springboot。

通过创建多WxConfig来实现。  在wxService.setConfig()时会创建httpclien连接池， 是否可以多个Appid共享一个client连接池呢？

**Comment by binarywang** [comment]
你有什么好的建议实现方法，欢迎随时提交PR

**Comment by chuntaojun** [comment]
> 你有什么好的建议实现方法，欢迎随时提交PR

大佬这个提上日程了吗？没有的话我想尝试下

**Comment by binarywang** [comment]
> > 你有什么好的建议实现方法，欢迎随时提交PR
> 
> 大佬这个提上日程了吗？没有的话我想尝试下

最近没时间考虑，你可以先尝试下吧

**Comment by WonderLand33** [comment]
> > 你有什么好的建议实现方法，欢迎随时提交PR
> 
> 大佬这个提上日程了吗？没有的话我想尝试下

大佬，公用 HttpClient Pool 尝试成功了吗？我也正好有这个需求。

**Comment by heyucong** [comment]
同样的需求啊，做服务商的基本上都是要考虑多个APPID的，之前就是这个原因一直没切换使用工具的

**Comment by chuntaojun** [comment]
我已经提交pull request了

**Comment by chuntaojun** [comment]
> 同样的需求啊，做服务商的基本上都是要考虑多个APPID的，之前就是这个原因一直没切换使用工具的

不是可以支持多APPID吗

**Comment by chuntaojun** [comment]
> > > 你有什么好的建议实现方法，欢迎随时提交PR
> > 
> > 
> > 大佬这个提上日程了吗？没有的话我想尝试下
> 
> 大佬，公用 HttpClient Pool 尝试成功了吗？我也正好有这个需求。

这个我感觉是可以的吧，我本人也没有多个APPID，也不太好测试，但是改起来挺快的

**Comment by WonderLand33** [comment]
> > > > 你有什么好的建议实现方法，欢迎随时提交PR
> > > 
> > > 
> > > 大佬这个提上日程了吗？没有的话我想尝试下
> > 
> > 
> > 大佬，公用 HttpClient Pool 尝试成功了吗？我也正好有这个需求。
> 
> 这个我感觉是可以的吧，我本人也没有多个APPID，也不太好测试，但是改起来挺快的

嗯，看了代码，调用`switchover(label)` 就可以切换了对吧？（等merge...）

**Comment by chuntaojun** [comment]
> > > > > 你有什么好的建议实现方法，欢迎随时提交PR
> > > > 
> > > > 
> > > > 大佬这个提上日程了吗？没有的话我想尝试下
> > > 
> > > 
> > > 大佬，公用 HttpClient Pool 尝试成功了吗？我也正好有这个需求。
> > 
> > 
> > 这个我感觉是可以的吧，我本人也没有多个APPID，也不太好测试，但是改起来挺快的
> 
> 嗯，看了代码，调用`switchover(label)` 就可以切换了对吧？（等merge...）

嗯，我想到的解决方案是这个的，类似多源数据库切换

**Comment by champion97** [comment]
> > > > > > 你有什么好的建议实现方法，欢迎随时提交PR
> > > > > 
> > > > > 
> > > > > 大佬这个提上日程了吗？没有的话我想尝试下
> > > > 
> > > > 
> > > > 大佬，公用 HttpClient Pool 尝试成功了吗？我也正好有这个需求。
> > > 
> > > 
> > > 这个我感觉是可以的吧，我本人也没有多个APPID，也不太好测试，但是改起来挺快的
> > 
> > 
> > 嗯，看了代码，调用`switchover(label)` 就可以切换了对吧？（等merge...）
> 
> 嗯，我想到的解决方案是这个的，类似多源数据库切换

在不改动源代码情况下我是这么做的 （未测试）[点击查看代码](https://github.com/champion97/wx-central/blob/0d3cd50da19d3c0d13382787c5bed1e6a8bbefa4/src/main/java/com/example/wx/central/service/WxBaseService.java#L92)

**Comment by binarywang** [comment]
> 我已经提交pull request了

你那个pr里包括实现共享httpclient连接池了吗？没看到呢

**Comment by binarywang** [comment]
> 同样的需求啊，做服务商的基本上都是要考虑多个APPID的，之前就是这个原因一直没切换使用工具的

本身也是支持多个appid的，你可以参考demo

**Comment by chuntaojun** [comment]
> > 我已经提交pull request了
> 
> 你那个pr里包括实现共享httpclient连接池了吗？没看到呢

```java
 @Override
  public void setMultiWxMpConfigStorage(HashMap<String, WxMpConfigStorage> configStorages) {
    wxMpConfigStoragePool = configStorages;
    isMultiWxApp = true;
    this.initHttp();
  }
```

这个

**Comment by binarywang** [comment]
看到了，

> > > 我已经提交pull request了
> > 
> > 
> > 你那个pr里包括实现共享httpclient连接池了吗？没看到呢
> 
> ```java
>  @Override
>   public void setMultiWxMpConfigStorage(HashMap<String, WxMpConfigStorage> configStorages) {
>     wxMpConfigStoragePool = configStorages;
>     isMultiWxApp = true;
>     this.initHttp();
>   }
> ```
> 
> 这个

好，看到了

**Comment by chuntaojun** [comment]
> 同样的需求啊，做服务商的基本上都是要考虑多个APPID的，之前就是这个原因一直没切换使用工具的

存在动态添加微信应用的需求吗

**Comment by binarywang** [comment]
3.3.6.B测试版本已加入相关代码，欢迎大家试用

**Comment by WonderLand33** [comment]
> 3.3.6.B测试版本已加入相关代码，欢迎大家试用

发现 3.3.6.B 在maven仓库中，jar包中的代码不是最新的。

**Comment by binarywang** [comment]
jar包是拿当时的源码打包的，当然不可能跟目前最新代码保持一致了

**Comment by SeeYouTurbo** [comment]
switchover(label)在线程池上，LocalThread获取后处理完业务没进行销毁，在线程重复使用的情况是不是会有线程安全呢

**Comment by SeeYouTurbo** [comment]
switchover(label)后通过LocalThread获取对应appid配置，处理完之后没有手动销毁LocalThread里面的数据，如果在线程池上使用的话线程重用下是不是有多线程问题呢？
