### ISSUE TITLE
WxPayRefundNotifyResult的successTime时间格式注释错误

### ISSUE THREAD

**Issue by rmfish** [binarywang/WxJava#960]
https://github.com/Wechat-Group/WxJava/blob/cc8359b22c05590e1fcdd9982de20c4cf7616285/weixin-java-pay/src/main/java/com/github/binarywang/wxpay/bean/notify/WxPayRefundNotifyResult.java#L218-L222

官方文档格式为： 2017-12-15 09:46:01  /  yyyy-MM-dd HH:mm:ss
```
退款成功时间 | success_time | 否 | String(20) | 2017-12-15 09:46:01 | 资金退款至用户帐号的时间，格式2017-12-15 09:46:01
```

**Comment by binarywang** [comment]
那应该是微信文档后来自己做了更新，代码里稍后也做个同步
