### ISSUE TITLE
xml解析异常ForbiddenClassException

### ISSUE THREAD

**Issue by hao2yue** [binarywang/WxJava#962]
我想自定义一个返回类的时候，xml会报这个错com.thoughtworks.xstream.security.ForbiddenClassException，
经过查看源代码，发现其中对于xml权限的定义为固定字符串，建议修改为变量

**Comment by binarywang** [comment]
你可以自己重新赋值，毕竟你是属于自定义扩展的部分；
当然如果有好的修改建议，欢迎直接提交PR。
