### ISSUE TITLE
这段刷新 accessToken的代码高并发下，可能会出现多次刷新。

### ISSUE THREAD

**Issue by unexpectedxx** [binarywang/WxJava#963]
https://github.com/Wechat-Group/WxJava/blob/6a0196aa01e7d0b36abea4388ce6a24115526cf3/weixin-java-mp/src/main/java/me/chanjar/weixin/mp/api/impl/WxMpServiceHttpClientImpl.java#L65-L98

**Comment by unexpectedxx** [comment]
如果有B线程在等锁，A线程获取AccessToken后释放锁，B线程获得锁后会再次获取AccessToken

**Comment by 007gzs** [comment]
A线程获取到AccessToken后过期时间会刷新，所以B线程获取到锁后 isAccessTokenExpired 返回false 不会再次获取AccessToken
