### ISSUE TITLE
微信公众号开发设置代理报错

### ISSUE THREAD

**Issue by heiheiyuan** [binarywang/WxJava#964]
![image](https://user-images.githubusercontent.com/18242327/54018852-af2f0300-41c4-11e9-88a9-039d289b1424.png)
![image](https://user-images.githubusercontent.com/18242327/54018888-c7068700-41c4-11e9-928b-9fc61625b612.png)
![image](https://user-images.githubusercontent.com/18242327/54018909-d08fef00-41c4-11e9-80bc-9109136046f9.png)
![image](https://user-images.githubusercontent.com/18242327/54019007-0fbe4000-41c5-11e9-9dcd-1ebc168eca1f.png)
麻烦帮忙看看是为什么？服务器Nginx日志都没变化，感觉请求都还没被送到nginx上就报错了

**Comment by binarywang** [comment]
看不出来，难道不是跟你服务器有关系？

**Comment by binarywang** [comment]
楼主问题解决了吗？
