### ISSUE TITLE
移动端链接快速授权生成预授权链接错误

### ISSUE THREAD

**Issue by ahacode** [binarywang/WxJava#966]
https://mp.weixin.qq.com/safe/bindcomponent?action=bindcomponent&no_scan=1&auth_type=3&component_appid=%s&pre_auth_code=%s&redirect_uri=%s&auth_type=xxx&biz_appid=xxx$#wechat_redirect

项目中配置的移动端快速授权地址模板错误，最后#wechat_redirect前是不是多了个'$'啊，导致回调回来后出现错误。

**Comment by binarywang** [comment]
@yuanqixun 袁总，这个看起来像是手抖了导致的？能否瞅一眼？

**Comment by binarywang** [comment]
3.3.6.B测试版本 已修复
