### ISSUE TITLE
XXE 疑问

### ISSUE THREAD

**Issue by zhonghuahero** [binarywang/WxJava#967]
对接微信支付，不同时期使用了不同的sdk，最近项目重构，用到该sdk，因为之前处理过其他sdk的xxe问题，所以对这个sdk的xml解析略微关注了下，想学习下如何规避XXE漏洞的，版本Weixin-java-common-3.3.0，没有特别明白，下面的地方是否有风险
com.github.binarywang.wxpay.bean.result.BaseWxPayResult.fromXML(String, Class<T>)

Stream xstream = XStreamInitializer.getInstance();

  public static XStream getInstance() {
    XStream xstream = new XStream(new PureJavaReflectionProvider(), XPP_DRIVER);

  private static final XppDriver XPP_DRIVER = new XppDriver() {
这个实现是没有禁止外部实体引用的。

这个问题可能很小白，各位大佬有空帮忙解惑指导下，多谢了哈。

**Comment by binarywang** [comment]
建议阅读xstream官方文档相关说明 http://x-stream.github.io/faq.html

**Comment by zhonghuahero** [comment]
> 建议阅读xstream官方文档相关说明 http://x-stream.github.io/faq.html
谢谢，我看了下官方文档，没有关于XppDriver的说明，应该是取决于自定义实现，然后又看了下源码，发现 xstream引用的xpp3，里面提供了SPI对应的Parser实现类：MxParser，该类里面禁止了外部引用。

我的理解不知道是否有偏差。多谢！

**Comment by binarywang** [comment]
仔细看文档里，有相关说明的。
```
Does XStream support entities?
Entity support is completely dependent on the XML parser. XStream uses by default the Xpp3 parser that does not support entities at all (like the kXML2 parser). Other parsers support entities, but they might have been turned off to avoid XXE vulnerability. To enable the entities again, you have to overload the individual method of the HierarchicalStreamDriver implementation that generated the parser factory.
```
