### ISSUE TITLE
麻烦问下怎么接入redis

### ISSUE THREAD

**Issue by adogcode** [binarywang/WxJava#972]

**Comment by binarywang** [comment]
能稍微明确说下你要做什么吗？

**Comment by adogcode** [comment]
因为我看demo里有WxCpJedisConfigStorage这个类，想用redis做些参数的持久化

**Comment by binarywang** [comment]
直接实例化该类，提供相应参数值就可以使用

**Comment by adogcode** [comment]
好的，还有个问题就是我发现
WxCpConfiguration.getCpService(3010040).getAccessToken(false)
WxCpConfiguration.getCpService(3010040).getWxCpConfigStorage().getAccessToken()
这两个方法后续获得的token值不一样，底下的这个时间长了会失效。

**Comment by binarywang** [comment]
自己看下源码就清楚怎么回事
