### ISSUE TITLE
调用申请退款接口报Username may not be null

### ISSUE THREAD

**Issue by MicroCreativity** [binarywang/WxJava#974]
![1552455833(1)](https://user-images.githubusercontent.com/18007558/54256198-2504e700-4596-11e9-8dd7-5c9e95d37284.jpg)

**Comment by MicroCreativity** [comment]
随便设置一个代理名就好了，不过这个坑还是得补掉...

**Comment by MicroCreativity** [comment]
![1552458041(1)](https://user-images.githubusercontent.com/18007558/54257719-461c0680-459b-11e9-8552-46c42b0c0761.jpg)

**Comment by binarywang** [comment]
我理解你这个问题跟退款没关系，只是代理设置的问题。

**Comment by MicroCreativity** [comment]
> 我理解你这个问题跟退款没关系，只是代理设置的问题。

嗯嗯，是的
