### ISSUE TITLE
怎么在自定义拦截器种获取wxsession？

### ISSUE THREAD

**Issue by qq229338869** [binarywang/WxJava#980]
我在springboot项目中设置了自定义的拦截器，想通过HttpServletRequest获取session中的信息。
request.getAttribute("openId");
我按照开发文档中设置了session，但是在拦截器中取不到值。
![image](https://user-images.githubusercontent.com/30120123/54535203-f0be6b80-4985-11e9-89fc-5e5482a929a3.png)
请问是不是有其他的api使用还是有更好的方法

**Comment by qq229338869** [comment]
这样子获取到了
`Object openId = request.getSession().getId();`
但是这个id和wxsession的id不同
`wxMessage.getFromUser()`

**Comment by qq229338869** [comment]
还是从网页授权获取了
`WxMpOAuth2AccessToken wxMpOAuth2AccessToken = wxMpService.oauth2getAccessToken(code);`
`String openId = wxMpOAuth2AccessToken.getOpenId();`

**Comment by binarywang** [comment]
wxSession跟httpsession不是一回事，不要搞混了，建议阅读下源码。

**Comment by qq229338869** [comment]
> wxSession跟httpsession不是一回事，不要搞混了，建议阅读下源码。

嗯，看了文档了，没理解透彻，最后还是通过微信网页授权获取的openId。
