### ISSUE TITLE
阅读代码时发现WxMpMemberCardServiceImpl构造函数是私有函数

### ISSUE THREAD

**Issue by junhsc** [binarywang/WxJava#981]
阅读代码时发现WxMpMemberCardServiceImpl的构造函数是私有函数?其他相关的mp.api.impl.*的构造函数是public的, 这个是不是需要调整下

**Comment by chuntaojun** [comment]
不是私有的构造函数，同一包中的类可以访问，声明时没有加修饰符，认为是friendly

**Comment by binarywang** [comment]
楼上说的很对，不过为统一起见，可以考虑改为public，方便自定义实现对应实现类。
