### ISSUE TITLE
公众号处理信息（实体类）入库的问题

### ISSUE THREAD

**Issue by joinme** [binarywang/WxJava#982]
用户关注，WxMpUser 信息 推送到 处理器类方法里面，然后我要把这些信息做入库操作，WxMpUser这个类有的属性没有，有的是多余的，（orm用 mybaits-plus）我是不是需要自己写一套实体类，然后做属性名映射转换后入库， 感觉这样很绕 麻烦， 有点不合适， 还是有其他方法？ 我看过demo的几个项目都没有入库是什么方式做的，所以在这里问问

**Comment by chuntaojun** [comment]
我个人觉得最好是能够根据业务自己写一个实体类，将WxMpUser的信息有选择的赋值到自己的业务实体类中

**Comment by binarywang** [comment]
同意楼上的
