### ISSUE TITLE
获取微信服务器IP地址

### ISSUE THREAD

**Issue by ghost** [binarywang/WxJava#984]
这个获取微信服务器IP地址  是不是没有集成到SDK? 那ACCESS_TOKEN哪里来.
http请求方式: GEThttps://api.weixin.qq.com/cgi-bin/getcallbackip?access_token=ACCESS_TOKEN

**Comment by einsitang** [comment]
请仔细阅读wiki

**Comment by binarywang** [comment]
没尝试搜索源码吗？关键字：getcallbackip
