### ISSUE TITLE
授权开放平台的时候，指定了auth_type字段，并没有生效

### ISSUE THREAD

**Issue by onekr-billy** [binarywang/WxJava#987]
版本：
implementation("com.github.binarywang:weixin-java-open:3.3.0")

方法：
wxOpenServiceClient.getWxOpenComponentService().getPreAuthUrl(callbackUrl, authType, null)

问题描述：
调用 getPreAuthUrl 方法的时候，传入的 authType参数，没有生效，我排查了源代码发现下面这一句没有起作用
代码路径： \weixin\open\api\impl\WxOpenComponentServiceImpl.java   217-226行
常量 COMPONENT_LOGIN_PAGE_URL 里并没有占位符  &auth_type=xxx 和 &biz_appid=xxx

请确认，是否存在问题？

**Comment by Hipple** [comment]
3.3.6.B版本已经修复了这个问题
