### ISSUE TITLE
第三方平台授权流程地址少了一部分

### ISSUE THREAD

**Issue by Asens** [binarywang/WxJava#994]
单独展示小程序类型时

当前代码

weixin-java-open/src/main/java/me/chanjar/weixin/open/api/WxOpenComponentService.java

String COMPONENT_LOGIN_PAGE_URL = "https://mp.weixin.qq.com/cgi-bin/componentloginpage?component_appid=%s&pre_auth_code=%s&redirect_uri=%s";

[微信文档]([url](https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1453779503&token=&lang=zh_CN))

![image](https://user-images.githubusercontent.com/12591195/55465895-aa793580-5630-11e9-9bba-f7fa634f94ce.png)

代码调用
`url = wxOpenService.getWxOpenComponentService().getPreAuthUrl(url,"2",null);`

![image](https://user-images.githubusercontent.com/12591195/55466022-f62bdf00-5630-11e9-8165-6282b08993a6.png)

本应把
`&auth_type=xxx`
替换为
`&auth_type=2`

但是因为URL没有`&auth_type=xxx`,导致最终的URL没有`&auth_type=2`

**Comment by binarywang** [comment]
这代码看来是有问题的，原实现者没添加相关单元测试，导致有问题，欢迎直接提供PR修复代码。

**Comment by binarywang** [comment]
这个代码已经修复了，请查看最新的测试版，以后有问题先检查develop分支版本代码，谢谢~
