### ISSUE TITLE
微信支付的跨城冗灾有实现吗？

### ISSUE THREAD

**Issue by yyblove** [binarywang/WxJava#995]
微信因上次上海南汇光纤被挖断，特地出了一套跨城冗灾指引，请问这个项目有会有吗？
[微信支付商户支付系统实现跨城冗灾指引](https://pay.weixin.qq.com/wiki/doc/api/micropay.php?chapter=23_6&index=4)

**Comment by binarywang** [comment]
暂未实现，欢迎提供可行实现方案

**Comment by hufancoder** [comment]
我司推出2种微信支付跨城冗灾方案，官方升级指引：https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=23_6&index=4
请问这两种方案实现了么。

**Comment by binarywang** [comment]
参考 #1111，目前sdk已实现可自定义请求url中的域名部分，有需求的请根据自己设定的策略修改对应值即可
