### ISSUE TITLE
使用wxService.createJsapiSignature(url)时空指针异常

### ISSUE THREAD

**Issue by Przeblysk** [binarywang/WxJava#996]
错误提示在`BaseWxMpServiceImpl`  `getTicket(TicketType type, boolean forceRefresh)`
`Lock lock = this.getWxMpConfigStorage().getTicketLock(type);` 这一行

**Comment by lidonghao1116** [comment]
为何close，怎么解决的？

**Comment by binarywang** [comment]
这种一声不吭就关闭的问题，多半是犯了低级错误。
另外，空指针问题再简单不过了，自己分析调试下就知道怎么回事

**Comment by lidonghao1116** [comment]
错误在这个地方
`public WxMpConfigStorage getWxMpConfigStorage() {
        return this.configStorageMap.size() == 1?(WxMpConfigStorage)this.configStorageMap.values().iterator().next():(WxMpConfigStorage)this.configStorageMap.get(WxMpConfigStorageHolder.get());
    }`
this.configStorageMap.size() 配置了两个，第一个key是我配置appid，另一个key是222
WxMpConfigStorageHolder.get() 这个取到的是“default”，
this.configStorageMap.get(“default”)值是null，造成空指针错误，
为何WxMpConfigStorageHolder.get()有问题？待细看源码..

解决办法是，配置一个公众号就行，this.configStorageMap.size() == 1
