### ISSUE TITLE
小程序企业微信专有接口wx.qy.login临时登录凭证校验有提供实现吗？

### ISSUE THREAD

**Issue by CuriousRookie** [binarywang/WxJava#997]
接口文档地址
[https://work.weixin.qq.com/api/doc#90000/90136/90289/%E7%99%BB%E5%BD%95%E5%87%AD%E8%AF%81%E6%A0%A1%E9%AA%8C](https://work.weixin.qq.com/api/doc#90000/90136/90289/%E7%99%BB%E5%BD%95%E5%87%AD%E8%AF%81%E6%A0%A1%E9%AA%8C)
这个接口是通过企业access_token获取的

**Comment by binarywang** [comment]
你这个看起来像是个前端接口吧？

**Comment by CuriousRookie** [comment]
> 你这个看起来像是个前端接口吧？

不是的，和普通微信小程序类似，小程序端调用wx.qy.login拿到code传到后台，后台使用code请求
https://qyapi.weixin.qq.com/cgi-bin/miniprogram/jscode2session?access_token=ACCESS_TOKEN&js_code=CODE&grant_type=authorization_code
这个地址获取用户userid、corpid、session_key等，但是这个请求参数里的ACCESS_TOKEN是使用企业微信的corpid和corpsecret获取

**Comment by binarywang** [comment]
那你就是标题写的有问题，其实应该后端实现“登录凭证校验”这个接口？

**Comment by CuriousRookie** [comment]
> 那你就是标题写的有问题，其实应该后端实现“登录凭证校验”这个接口？

......我改一下

**Comment by binarywang** [comment]
3.3.8.B测试版本 已加入该接口
