### ISSUE TITLE
微信支付模块 发送普通红包 ResultCode为FAIL时没有抛出WxPayException异常

### ISSUE THREAD

**Issue by Cartagra** [binarywang/WxJava#999]
请问这是需要自己处理？
但是我看其他支付接口ResultCode为FAIL时都是有抛出异常的。

**Comment by binarywang** [comment]
其实你可以直接看下源码的

**Comment by binarywang** [comment]
源码里其实有注明`//无需校验，因为没有返回签名信息`，因为没有返回签名，所以这块就忽略了，不过可以考虑加上结果的判断部分

**Comment by binarywang** [comment]
3.3.8.B测试版本 已加入相关代码
